### ISSUE TITLE
Objects.RubbleObject`1.TryPickup

### ISSUE THREAD

**Issue by GriffIngalls** [StrangeLoopGames/EcoIssues#10000]
Ms. Pam asked me to report this!

--BEGIN DUMP--
Dump Time
11/13/2018 11:36:15

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Core

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Serialization.ZipBlob.Delete()
   at Eco.Gameplay.Objects.EcoObjectManager.Remove(IEcoObject ecoObject)
   at Eco.Gameplay.Objects.RubbleObject`1.TryPickup(Player actor, Inventory inv)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

--END DUMP--

**Comment by seccombew** [comment]
Reopen if issue persists.
