### ISSUE TITLE
7.8.1 NullReferenceException when trying to load existing world

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10018]
Was told to post this as an issue.  Happening to majority of servers trying to update and run on 7.8.1 using and existing world

https://www.dropbox.com/s/hxopbwf46fdoov2/Game.eco?dl=0

--BEGIN DUMP--
Dump Time
11/14/2018 23:30:24

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Utils.PickerTracker.get_Inventories()
   at Eco.Gameplay.Utils.PickerTracker.SetRemaining(IEnumerable`1 stacks)
   at lambda_method(Closure , Object[] )
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.<>c__DisplayClass10_0.<.ctor>b__1()
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer`2.Decode(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.Decode(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.Load[T](String folder, Action`2 createFunc)
   at Eco.Core.Plugins.StorageManager.CreateOrLoad[StorageType](String folder, Action`1 onCreate)
   at Eco.Core.Plugins.SimplePlugin`1.DoLoad(String name)
   at Eco.Core.Plugins.SimplePlugin`1..ctor(String name)

--END DUMP--

**Comment by D3nnis3n** [comment]
Another world having this issue:
https://1drv.ms/u/s!AiWVzbLtAg3Xu17RDihtwOYw4oXP
