### ISSUE TITLE
Path to Long Exception

### ISSUE THREAD

**Issue by hami88** [StrangeLoopGames/EcoIssues#10054]
Since 7.8.x we have massive problems with corruption of our savegames. We already created multiple new world and after a few hours the save gets corrupted with a PathToLongException. Also on a freshly installed instance of the server the savegame wont load.

Savegame:
https://ufile.io/kmlfc

DUMP:
--BEGIN DUMP--
Dump Time
11/17/2018 11:16:12

Exception
Exception: PathTooLongException
Message:Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.
Source:mscorlib

System.IO.PathTooLongException: Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Eco.Core.Serialization.DataStore.<>c__DisplayClass46_0`1.<LoadAsync>b__0(ZipArchiveEntry entry)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.World.PersistentChunkGrid.Load()
   at Eco.World.WorldPlugin..ctor()

--END DUMP--

**Comment by elfl0rd** [comment]
Looks like https://github.com/StrangeLoopGames/EcoIssues/issues/10155
(https://github.com/StrangeLoopGames/Eco/pull/3699)
