### ISSUE TITLE
Server unable to load : Null reference Eco.Gameplay.LegislationSystem.LawLogic.Fields.AliasDropDown.AliasByCategoryDropDown.IdToDisplayName

### ISSUE THREAD

**Issue by TheKrush** [StrangeLoopGames/EcoIssues#10079]
```
--BEGIN DUMP--
Dump Time
11/20/2018 09:20:11

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.AliasDropDown.AliasByCategoryDropDown.IdToDisplayName(String id)
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.RefreshDisplayName()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.Items.Law.Initialize()
   at Eco.Gameplay.Legislation.Initialize(TimedTask timer)
   at InitializePlugins_Patch1(Object )
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

--END DUMP--
```

**Comment by D3nnis3n** [comment]
Can add a save file?

**Comment by BlazeGuy2** [comment]
Believe this got fixed last night.  Reopen if it is still occurring.

**Comment by SentilONE** [comment]
Hellow! I have this problem too on 9.7.9. 
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11136451/Player.log)

**Comment by Visiju** [comment]
got the same problem since today on v10 Seaotter
