### ISSUE TITLE
Hotfix broken migration

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10085]
> --BEGIN DUMP--
> Dump Time
> 11/21/2018 03:19:30
> 
> Exception
> Exception: NullReferenceException
> Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>    at Eco.Gameplay.Property.PropertyManager.GetDeed(Guid deedId)
>    at Eco.Gameplay.LegislationSystem.LawLogic.Fields.PropertyDropDown.IdToSelectedData(String id)
>    at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown1.RefreshSelectedData()
>    at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown1.GetSelectedData()
>    at Eco.Gameplay.LegislationSystem.LawLogic.Fields.PropertyDropDown.OnDeserialized()
> 
> --END DUMP--

**Comment by D3nnis3n** [comment]
Fixed.
