### ISSUE TITLE
Server Crash Dump

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10127]
Today we occured a new one:

> --BEGIN DUMP--
> Dump Time
> 11/25/2018 15:57:43
> 
> Exception
> Exception: InvalidOperationException
> Message:Die Sequenz enthält keine Elemente.
> Source:System.Core
> 
> System.InvalidOperationException: Die Sequenz enthält keine Elemente.
>    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
>    at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, String noneText)
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicRoot.IsAllowed(IPlayerAction action)
>    at Eco.Gameplay.Legislation.CreateAtomicAction(IPlayerAction action)
>    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
>    at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
>    at Eco.Gameplay.Stats.PlayerActionManager`1.CreateAtomicAction(T action)
>    at Eco.Gameplay.Items.WorkOrder.CreateCraftOneAction()
>    at Eco.Gameplay.Items.WorkOrder.get_Blocked()
>    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Eco.Gameplay.Components.CraftingComponent.UpdateBottlenecked()
>    at Eco.Gameplay.Components.CraftingComponent.Tick()
>    at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
>    at Eco.Gameplay.Objects.WorldObject.Tick()
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
> 
> --END DUMP--
>

**Comment by D3nnis3n** [comment]
We only had that occuring one once yet. Just thought it be good to post it here. I can attach you the save though: https://drive.google.com/file/d/1KuSHI6Vw7Z5lPJSd0dZ3l-n6uEds9NlF/view?usp=sharing

**Comment by Sekor2600** [comment]
Hi did have the same Crash Log today. 
--BEGIN DUMP--
Dump Time
02/21/2019 20:15:05

Exception
Exception: InvalidOperationException
Message:Sequence contains no matching element
Source:System.Core

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.LegislationSystem.LawLogic.Conditions.AnyCondition.IsMetReason(IPlayerAction action)
   at Eco.Gameplay.LegislationSystem.LawLogic.ControlFlow.LawControlFlowList.GetLawResult[T](IPlayerAction action, Func`2 operation, Func`2 createFailResult)
   at Eco.Gameplay.LegislationSystem.LawLogic.ControlFlow.LawControlFlowList.IsAllowed(IPlayerAction action)
   at Eco.Gameplay.LegislationSystem.LawLogic.Clauses.ActionList.IsAllowed(IPlayerAction action)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.Legislation.CreateAtomicAction(IPlayerAction action)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.Stats.PlayerActionManager`1.CreateAtomicAction(T action)
   at Eco.Gameplay.Items.WorkOrder.CreateCraftOneAction()
   at Eco.Gameplay.Items.WorkOrder.get_Blocked()
   at Eco.Gameplay.Items.WorkOrder.UpdateBlocked()
   at Eco.Gameplay.Components.CraftingComponent.UpdateBottlenecked()
   at Eco.Gameplay.Components.CraftingComponent.Tick()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--

**Comment by Sekor2600** [comment]
@mirasrael need stats too?

**Comment by mirasrael** [comment]
@Sekor2600 thanks, should be fixed in 8.2
