### ISSUE TITLE
Multiple demographic and world leader issues

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#10135]
This may or may not be multiple issues or a single core one.

The issues seemed to start on our server shortly after a reset.  The first world leader created a demographic that would match the "World Leader's" play hours with a player's play hours.  If they matched, that person is treated as the "World leader" for the sake of laws and such.  Well, shortly after this law was passed, we started experiencing massive lag issues whenever the world leader was logged in.  And it didn't matter who the world leader was, the impact was the same.

This lag was resulting in players not being able to log in at all to a server, forcing several restarts a day.  After dealing with this over the entire holiday weekend, it was decided last night to attempt to remove the "World Leader" demographic and see if that fixed the issue.  So as an admin, I created a law to remove said demographic and forced it through.  The instant I hit /passlaws, I was promptly kicked from the server, but was able to log back in with no issues.  The current world leader was able to log back in as well and could play with no issues.  In fact there were no apparent issues until this morning.

So, when the server is restarted this morning, it won't boot back up.  Look at the dump file and I see this:

--BEGIN DUMP--
Dump Time
11/26/2018 12:40:23

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.AliasDropDown.AliasByCategoryDropDown.IdToDisplayName(String id)
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown1.RefreshDisplayName()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown1.Init()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.Items.Law.Initialize()
   at Eco.Gameplay.Legislation.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

--END DUMP--

We have not been able to get the server running since then, mainly due to the joys of work, but also because I'm not totally sure what is actually broken, nor how to fix it.

I do think it could be one of a few possible scenarios:

1.  When the "World Leader" Demographic was created, it somehow interfaced with something in coding for the actual "World Leader" position, thus creating some sort of anomaly that broke the game when the demographic was removed.

2.  Because there were laws that had the "World Leader" Demographic in them, the removal of said laws irreparably broke something in the legal system of the game.

3.  Combination of the two.

After dealing with all this, I did have a couple of suggestions (may or may not already be in the game):

a) Have the World Leader as a default Demographic / role instead of something that needs to be defined.  Something similar to the Admin role in the (Other) section would probably work best.

b) Prevent any law from removing a demographic if there are "children" laws that use that demographic.

That's all I have for now.  I can probably provide additional logs if needed.

**Comment by Deantwo** [comment]
I believe adding a "World Leader" default option (similar to "Admin") is being added already, if not I already requested it once before at least.

As for why the law caused so much law, that just makes since. I don't know how often "Play Actions" are added, but the demographic likely refreshed every second the world leader's play time changed.

**Comment by D3nnis3n** [comment]
Please add your save file uploaded to google drive or similar.

**Comment by D3nnis3n** [comment]
Closing as of no further information provided. You can also use "World Leader" in laws directly now.
