### ISSUE TITLE
Server Players all Having Path to Long  Exceptions

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10155]
--BEGIN DUMP--
Dump Time
11/29/2018 03:39:00

Exception
Exception: PathTooLongException
Message:The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
Source:mscorlib

System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Eco.Core.Serialization.DataStore.<>cDisplayClass46_0`1.<LoadAsync>b0(ZipArchiveEntry entry)
   at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
   at System.Linq.Buffer1..ctor(IEnumerable1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source)
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.World.PersistentChunkGrid.Load()
   at Eco.World.WorldPlugin..ctor()

--END DUMP--

Going to backup works in some cases.  Will have them attach world with the error to this bug report

**Comment by pamduncan** [comment]
--BEGIN DUMP--
Dump Time
11/29/2018 11:51:10

Exception
Exception: PathTooLongException
Message:The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
Source:mscorlib

System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Eco.Core.Serialization.DataStore.<>c__DisplayClass46_0`1.<LoadAsync>b__0(ZipArchiveEntry entry)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.World.PersistentChunkGrid.Load()
   at Eco.World.WorldPlugin..ctor()

--END DUMP--

**Comment by Sephumbra** [comment]
I am having the same Issue with the same dump. Here is an example of such a world which causes the exception and a backup of that world which does not have any issues.

https://drive.google.com/open?id=1fkhodlf0eek0kODDZ2vT5uIgA-3cj1fO

**Comment by Quicksilv3r710** [comment]
I am also having the same issue.  Here are my server files. https://drive.google.com/open?id=1j0E2TXudjaRJ9Es0p8pbwJwvLZjJnv8C

**Comment by mirasrael** [comment]
I fixed loading for long paths in staging, but there seems are another problem which I wasn't able to trace down. Game fails to load because of very suspect path in the game save archive.

![image](https://user-images.githubusercontent.com/475445/49357978-0dd67380-f6e2-11e8-8508-8508d48dd072.png)

Until next release you can fix this by manually removing such entries from `Game.eco` (Eden.eco, whatever.eco etc). It is just a regular zip archive.

**Comment by MrManviFTAI** [comment]
Hey! So I had the same issue, I got in reach with one of the support devs and I got to this post.
The Fix helped me out but I had 2 unusually big users name in the game.eco file. with 964 characters each. He advised me to post the file here. So Mirasel will be informed regarding this. Here you go mate:
[https://mega.nz/#!W2ZgRSbT!FB_Jv77XVOfJhcdpRvEHqAvgifOVmEbst-teNyc8s7Q](url)

**Comment by mirasrael** [comment]
@MrManvi thanks!

**Comment by mirasrael** [comment]
Shouldn't happen with `RequireAuthentification` enabled. Happens because of for failed authentication Steam session ticket uses for new user creation.
