### ISSUE TITLE
[Master] Bank - Deleting account crashes the server

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10217]
https://gist.github.com/D3nnis3n/deee5498d698e05aefec9ef2ae542b25

**Comment by Quadbro** [comment]
can't find anything related to bank account editing in the crash, and i tested on master now - can't reproduce crashes.

**Comment by D3nnis3n** [comment]
Sorry, the issue is on deleting a bank account, not editing.

**Comment by D3nnis3n** [comment]
https://drive.google.com/file/d/12cXUQ7m5lD68fbXitbYS9nmsuV5P_34c/view?usp=sharing

There you go.

**Comment by elfl0rd** [comment]
@Quadbro 
Yes, immediately after click on X to delete bank account.

> System.InvalidCastException
  HResult=0x80004002
  Сообщение = Заданное приведение является недопустимым.
  Источник = Eco.Core
  Трассировка стека:
   at Eco.Core.Utils.ThreadSafeDictionary`2.Remove(Object key) in D:\DevelopECO\Eco\Server\Eco.Core\Utils\ThreadSafeDictionary.cs:line 77
   at Eco.Core.Utils.IDDictionary`2.Remove(INetObject player, Object entry) in D:\DevelopECO\Eco\Server\Eco.Core\Utils\IDDictionary.cs:line 43
   at Eco.Gameplay.Utils.RPCListExtensions.Remove(IContainsClientControlledContainer obj, Player player, Int32 iList, IController entry) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Utils\IRPCList.cs:line 25

**Comment by D3nnis3n** [comment]
I changed the title accordingly, sorry again.
