### ISSUE TITLE
Master: gathering lattice mushroom cause break

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10225]
and kick player from server.

> System.ArgumentNullException
  HResult=0x80004003
  Сообщение = Значение не может быть неопределенным.
Имя параметра: key
  Источник = mscorlib
  Трассировка стека:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Items.ItemAttribute.Get[T](Type itemType) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Items\ItemAttributes.cs:line 51
   at Eco.Gameplay.Plants.PlantEntity.TryHarvest(Player player, Boolean picked, Inventory targetInv) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Plants\PlantEntity.cs:line 111
   at Eco.Gameplay.Plants.InteractablePlantBlock.OnActInteract(InteractionContext context) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Plants\PlantBlocks.cs:line 78
   at Eco.Gameplay.Players.Player.<>c__DisplayClass48_0.<PlayerInteract>b__2(IInteractable inter) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Players\Player.cs:line 302
   at Eco.Gameplay.Interactions.InteractionExtensions.<>c__DisplayClass2_1`1.<ExecuteUntilSuccess>b__1() in D:\DevelopECO\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 102
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 111
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T](IEnumerable`1 enumerable, Func`2 resultFunc) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 102
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Players\Player.cs:line 308

**Comment by BlazeGuy2** [comment]
LatticeMushrooms don't have a ResourceItemType hooked in yet.

**Comment by Conchipedia** [comment]
![snap3590](https://user-images.githubusercontent.com/29383891/50659510-c834f100-0f94-11e9-9e13-55c97281c6a1.png)
![snap3591](https://user-images.githubusercontent.com/29383891/50659527-d4b94980-0f94-11e9-9a46-4efab856d659.png)
found it easier than typing 😄
