### ISSUE TITLE
Master: palm, interaction problems.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10237]
![default](https://user-images.githubusercontent.com/4980243/49685944-238ed300-fafe-11e8-997a-59db8197b4c4.png)

(can be chopped down, but see screenshots.... Chop position really hard to find
![default](https://user-images.githubusercontent.com/4980243/49685947-35707600-fafe-11e8-93ed-cf8f48eae475.png)
log OVERSIZED
![default](https://user-images.githubusercontent.com/4980243/49685952-49b47300-fafe-11e8-8ab4-d676a5e49b88.png)
And cause break+kick player in pickup attempt.

```
System.NullReferenceException
  HResult=0x80004003
  Сообщение = Ссылка на объект не указывает на экземпляр объекта.
  Источник = Eco.Mods
  Трассировка стека:
   at TreeEntity.PickupLog(Player player, Guid logID) in d:\DevelopECO\Eco\Server\Mods\Objects\TreeObject.cs:line 268
   at TreeEntity.OnActInteract(InteractionContext context) in d:\DevelopECO\Eco\Server\Mods\Objects\TreeObject.cs:line 199
   at Eco.Gameplay.Players.Player.<>c__DisplayClass48_0.<PlayerInteract>b__2(IInteractable inter) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Players\Player.cs:line 302
   at Eco.Gameplay.Interactions.InteractionExtensions.<>c__DisplayClass2_1`1.<ExecuteUntilSuccess>b__1() in D:\DevelopECO\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 102
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 111
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T](IEnumerable`1 enumerable, Func`2 resultFunc) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 102
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Players\Player.cs:line 308
```

**Comment by elfl0rd** [comment]
Collision - ok
Chop down - ok
wood debris - ok
stump - ok
chop to logs and gather - ok

Closing.
