### ISSUE TITLE
[8.0.0] Stuffed Elk Inventory Crash

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#10273]
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: key
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Items.InventoryChangeSet.ModifyItemsInternal(Type itemType, Int32 delta, Inventory inventory) in C:\Users\StuffedElk\Documents\GitHub\Eco\Server\Eco.Gameplay\Items\Inventory.cs:line 485
   at Eco.Gameplay.Items.InventoryChangeSet.AddItems(Type itemType, Int32 quantity, Inventory inventory) in C:\Users\StuffedElk\Documents\GitHub\Eco\Server\Eco.Gameplay\Items\Inventory.cs:line 102
   at Eco.Gameplay.Items.Inventory.TryAddItems(Type itemType, Int32 quantity, User user) in C:\Users\StuffedElk\Documents\GitHub\Eco\Server\Eco.Gameplay\Items\Inventory.cs:line 1233
   at Eco.Gameplay.Animals.AnimalEntity.OnActInteract(InteractionContext context) in C:\Users\StuffedElk\Documents\GitHub\Eco\Server\Eco.Gameplay\Animals\AnimalEntity.cs:line 112
   at Eco.Gameplay.Players.Player.<>c__DisplayClass48_0.<PlayerInteract>b__2(IInteractable inter) in C:\Users\StuffedElk\Documents\GitHub\Eco\Server\Eco.Gameplay\Players\Player.cs:line 302
   at Eco.Gameplay.Interactions.InteractionExtensions.<>c__DisplayClass2_1`1.<ExecuteUntilSuccess>b__1() in C:\Users\StuffedElk\Documents\GitHub\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 102
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results) in C:\Users\StuffedElk\Documents\GitHub\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 111
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T](IEnumerable`1 enumerable, Func`2 resultFunc) in C:\Users\StuffedElk\Documents\GitHub\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 102
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info) in C:\Users\StuffedElk\Documents\GitHub\Eco\Server\Eco.Gameplay\Players\Player.cs:line 308

![inventorycrash](https://user-images.githubusercontent.com/35509188/49838501-d447dd00-fd5f-11e8-90d5-e3c903c589ec.PNG)

**Comment by BlazeGuy2** [comment]
Sean claimed he triggered this from looting a bighorn.

**Comment by BlazeGuy2** [comment]
Reproduced, issue lies with bighornsheep not having a resourcetype.
