### ISSUE TITLE
Can't generate large world

### ISSUE THREAD

**Issue by Inumedia** [StrangeLoopGames/EcoIssues#1031]
When attempting to generate a large world (1k x 1k) the server crashes after roughly 10 minutes of generation. Likely related to new world sim 10 minute tick.

http://puu.sh/tmNoV/a0aa5162c3.png

Exception w/stack trace:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.WorldLayerSystem.SpreadWorldLayer.<>c__DisplayClass7_0.<Tick>b__1(Vect
or2i dir)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at Eco.WorldLayerSystem.SpreadWorldLayer.<>c__DisplayClass7_1.<Tick>b__0(Vect
or2i pos)
   at Eco.Core.Utils.ArrayUtils.<>c__DisplayClass3_0`1.<Set2D>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating
>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int
32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWit
hState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive
, ParallelOptions parallelOptions, Action`1 body)
   at Eco.Core.Utils.ArrayUtils.Set2D[T](Array2D`1 array, Func`2 calc)
   at Eco.WorldLayerSystem.SpreadWorldLayer.Tick()
   at Eco.WorldLayerSystem.WorldLayer.DoTick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration
, Action`1 action)
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.ExternalInputs.WorldLayerSync.Tick(Boolean allowWorldIntera
ction, Boolean forceWorldInteraction)
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.WorldLayerSystem.WorldLayerSimulation.ForceTick(Boolean worldInteracti
on)
   at Eco.WorldLayerSystem.WorldLayerSimulation.TryTick(Double time)
   at Eco.WorldLayerSystem.WorldLayerSimulation.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by D4Water** [comment]
I have this issue on both 0.5.3 and the 0.5.4-cbfbea3a . Can't regenerate the world. Same exact kind of info as the poster on this thread is showing.

I started a world, I can log in, move around do things.. like chop wood.. and everything seems fine. But I log out and while the server is running, I try to "regenerate" the world and it crashes.

Win7 x64 ( I hate windows 8 and 10 )
i7 5820K 6-Core @ 3.4 Gighertz per core
64 Gigs System Ram
GTX 980 NVidia card with 4 gigs ram on it.

Both the client and server I am running is both 64-Bit.

**Comment by metachronism** [comment]
this should be working now, as world layer tick changed, but worlds of that size are going to take a looooong time to generate
