### ISSUE TITLE
The requested name is valid, but no data of the requested type was found

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#10330]
Version: 0.7.8.5 beta Server

Steps to Reproduce:

Unknown

Expected behavior:

That the server would actually handle
the exeption properly. 

Actual behavior:

Ok so this is a crash dump that I got  even if say a connection 
goes down it should not throw exceptions like this and should
be able to properly handle it. 

I am not sure what exactly happened here but I thought I would 
post the dump.  This is a private test server of mine running on
Windows 7 Pro with about 20 GB of RAM. 

Also why do you not support *.txt files to be uploaded I tried to upload
the actual log file but it won't accept it. 

It threw this error and the sever froze right up and hung and I had to restart
the Eco server again. 

--BEGIN DUMP--
Dump Time
12/13/2018 17:07:50

Exception
Exception: SocketException
Message:The requested name is valid, but no data of the requested type was found
Source:System
NativeErrorCode:11004
ErrorCode:11004

System.Net.Sockets.SocketException (0x80004005): The requested name is valid, but no data of the requested type was found
   at System.Net.Dns.GetAddrInfo(String name)
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at Lidgren.Network.NetUtility.Resolve(String ipOrHost)
   at Eco.Shared.Networking.Constants.RefreshMasterServerEndpoint(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

--END DUMP--

Do you have mods installed? Does issue happen when no mods are installed?:
I have no mods installed.

![eco 0 7 8 5 server exception error dec 13 2018](https://user-images.githubusercontent.com/38896397/50021808-71408b00-ff97-11e8-9358-87c9cdc6eb1a.jpg)

**Comment by beastyn** [comment]
Please reopen if issue is actual.
Didn't meet with 0.8.1.4
