### ISSUE TITLE
ClimateSim crashes on larger worlds

### ISSUE THREAD

**Issue by Inumedia** [StrangeLoopGames/EcoIssues#1033]
After generating a 500x500 (height 64) world, the ClimateSim attempts to run and crashes.

![Crash](http://puu.sh/tmPIm/7133c857c0.png)

```
[22:52] Server Initialization finished in 127,879.2ms in 3.8ms
[40:05] Initializing world layers...
[40:33] Loading ClimateSim...
                              FinisheFinished in 28,551.2ms
Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> System.InvalidOperationException: Deserialization is not supported. Please cha
nge the serialization settings.
   at Microsoft.Hadoop.Avro.AvroSerializer`1.Deserialize(IDecoder decoder)
   at Microsoft.Hadoop.Avro.AvroSerializer`1.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.Load[T](String folder, Action`2 createFun
c)
   at Eco.Core.Plugins.StorageManager.CreateOrLoad[StorageType](String folder)
   at Eco.Simulation.ClimateSim..ctor()
   at Eco.WorldLayerSystem.WorldLayerSimulation.InitLayers(Boolean regenerated)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating
>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int
32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWit
hState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`
1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState
, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithE
verything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Act
ion`1 body)
   at Eco.WorldGenerator.WorldGeneratorPlugin.CreateWorld()
   at Eco.WorldGenerator.WorldGeneratorPlugin.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by metachronism** [comment]
this still happens

**Comment by metachronism** [comment]
this shouldnt happen anymore with seans "dont tick till world gen is done" change
