### ISSUE TITLE
[8.0.0 Steam Beta] Converted Server crashes shortly after start

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10372]
With this error:

```
--BEGIN DUMP--
Dump Time
12/19/2018 17:47:50

Exception
Exception: IndexOutOfRangeException
Message:Der Index war außerhalb des Arraybereichs.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   at Eco.Gameplay.Players.User.GetSpecialtyCost()
   at Eco.Gameplay.Players.User.AddExperience(Single amount)
   at Eco.Gameplay.Players.User.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Gameplay.Players.UserManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
```

Use world https://download.godsofwar.de/eco/cycle-5.zip to test.
I made them medium priority as we advised to create new worlds.

**Comment by seccombew** [comment]
No longer occurring.
