### ISSUE TITLE
Crash after restart - World Object

### ISSUE THREAD

**Issue by F3UR10** [StrangeLoopGames/EcoIssues#10442]
Hi there, 

cause I cant fix our problem, PAM told me to open an issue.

After restarting our server, I get the following dump, any solution:
Dump Time
12/28/2018 23:31:14

Exception
Exception: Exception
Message:Error(s) occurred when loading WorldObjects
Source:Eco.Core

System.Exception: Error(s) occurred when loading WorldObjects
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.Gameplay.Objects.WorldObjectManager..ctor()

--END DUMP--

EDIT: The server wasnt restarted ~2days, due the shop problem after restarts

------
I tried all things PAM told me @discord:
That can happen with a corrupt object in the world or a vehicle that has been left on or near the 0,999 border
It could be possible for you to see if you can find it if its a corrupt objects but if its a vehicle 8issue the onlt one to find that is causing the poroblem would be to delete all vehicles
The other option if you don't want to try and look yourself (I can give instructions) is to upload your world to a file share and to make a bug report and link the world and the devs can then take a look.  If you do that I cannot guarantee that it will be looked at today
how did you open the saved file, if you unzipped it then  recompressing it could be the issue
You would need to try doing what you did on a file that you did not unzip usually once unzipped it does not compress back where its seen correctly by the  server
The only vehicles that seem to be an issue are the trucks so we usually just remove those
But If it was not that then other thing to look for is a corrupted object
Did you have any mods running?
-------
Pam Thx for your response. Now its 08:40 AM and I can answer you. I opened the Game.eco file with Winrar (still have unopended Backup files :smiley: ).
-> Which program do you recommend?
-> How can I see which Object is near this 0,999 boarder?
-> We only use this mods: Better Farming, Better Mining, BetterLooging, JDFarmersPAradise(bearbeitet)
------
that way the world save is not unzipped and would need ot be compressed with something algorithm that is different from the one slg uses.  with open archive you can work in it without unzipping  it.  Then go to the world objects folder and first look through all the objects for anyone that instead of a name just has garbage characters that make no sense.
If there is a corrupt world objects that would look like  that or if there is an object in there that is 0 size or shows no information - in either case you would delete them,
If there seem to be no problems with any of the world objects then it could be a truck stuck near where the boundary is where teh world wraps around to form a globe
There is nothing to help it that I know of but to delete all the trucks,  As afar as anyone that has told me  the older vehicles like the  stean cart the excavatore or the skidsteer don't have a problem with this but there have been a couple of people that that did wipe all vehicles and it did not solve it so start with the most likely firs.
But before doing that
You should create a test world on your server to make sure that  it actually is a problem with the world and not something you need to re-install the server to fix
If you can create and get in a test world then you know its an issue in the save.  if you get the same error on a fresh world then its the server files not the world save.
Also another way to try and fix this is to go back a couple of backups to before it happened. and ask poeple to stay off the world boundary with vehicles
they might lose a day of work in game but that is better than losing everything

-----

Also an very old backup from 2018-12-22 works fine.

May you check the Game files if you find the issue?
You can find the Game.eco & Game.db in my dropbox: 
https://www.dropbox.com/sh/b7ugl03443bk4f1/AABe7ndrwRQZvVLIsxiSWqR6a?dl=0

I hope you can find an solution, that my community members can continue play that savegame.

Kind regards
F3UR10

**Comment by F3UR10** [comment]
FIX: activate the "CleanupFilesOnExceptions" in the Storage.eco config.
