### ISSUE TITLE
[0.8.0.0] Trying to Reap Unknown Plant on the Floor with Scythe Kicks me with an Error

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10496]
**Version:** 0.8.0.0 beta master-375c24eb

**Steps to Reproduce:**
find this in the World (no idea What it is called as nothing comes up as name)
![snap3589](https://user-images.githubusercontent.com/29383891/50657103-57d6a180-0f8d-11e9-99f0-9a95f831e933.png)
try to Reap with a scythe and an Error happens

**Expected behavior:**
should be able to Harvest this

**Actual behavior:**
kicked with the following Error

Server encountered an exception:

<size=60.00%>Exception: ArgumentNullException
Message:Value cannot be null.
Parameter name: key
Source:mscorlib

System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Items.ItemAttribute.Get[T](Type itemType)
   at Eco.Gameplay.Plants.PlantEntity.TryHarvest(Player player, Boolean picked, Inventory targetInv)
   at Eco.Mods.TechTree.ScytheItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>

**Do you have mods installed? Does issue happen when no mods are installed?:**
No Mods just Singleplayer generated world.

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2725061/output_log.txt)

**Comment by elfl0rd** [comment]
you can use soil sampler to identify blocks and plants :D

**Comment by Conchipedia** [comment]
thanks, found out it was Deer lichen and this is a duplicate of
[8.0.0] Crashed server after trying to reap deerlichen #10304
so closing this
