### ISSUE TITLE
Crash in Animal Behaviors

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#10531]
--BEGIN DUMP--
Dump Time
01/04/2019 16:12:18

Exception
Exception: InvalidOperationException
Message:Collection was modified; enumeration operation may not execute.
Source:mscorlib

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Eco.Mods.Organisms.Behaviors.GroupBehaviors.GetLeader(Animal agent)
   at Eco.Mods.Organisms.Behaviors.GroupBehaviors.SleepNearLeader(Animal agent)
   at Eco.Simulation.Agents.AI.FunctionalBehaviorTree`1.Selector(T context, Func`2[] children)
   at Eco.Simulation.Agents.Animal.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by BlazeGuy2** [comment]
https://drive.google.com/file/d/1OunClAacFWbPOl87wrytk-l7vUH6Avgn/view?usp=sharing
