### ISSUE TITLE
ClientReceiveException TargetInvocationException 09230310

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10534]
--BEGIN DUMP--
Dump Time
09/23/2018 13:03:10

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Core

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Serialization.ZipBlob.Delete()
   at Eco.Gameplay.Objects.EcoObjectManager.Remove(IEcoObject ecoObject)
   at Eco.Gameplay.Objects.RubbleObject`1.TryPickup(Player actor, Inventory inv)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

--END DUMP--

**Comment by seccombew** [comment]
Fixed.
