### ISSUE TITLE
[7.8.9] Server Crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10784]
> --BEGIN DUMP--
> Dump Time
> 01/19/2019 23:43:28
> 
> Exception
> Exception: NullReferenceException
> Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>    at Eco.Gameplay.Components.StoreComponent.<>c__DisplayClass35_0.<UpdateStock>b__0(ItemStack stack)
>    at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Eco.Gameplay.Components.StoreComponent.UpdateStock(Boolean initializing)
>    at Eco.Gameplay.Components.StoreComponent.Tick()
>    at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
>    at Eco.Gameplay.Objects.WorldObject.Tick()
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
> 
> --END DUMP--

**Comment by D3nnis3n** [comment]
Fixed.
