### ISSUE TITLE
Player crash when walking to certain part of the map (within radius of something)

### ISSUE THREAD

**Issue by DatorzX** [StrangeLoopGames/EcoIssues#10825]
Client version: 0.7.8.9 beta
No Mods
Repeatable when I enter a certain area of the map
Rebooted client machine several times
Issue happens over many days
Server has been rebooted
Reinstalled game on client machine
Cleared AppData for game

=====

I had been working on a ramp, dirt ramps to be exact.
Half way up the hill I crashed. Upon returning to the game, 10 seconds later I crashed again. I walked up the ramp and crashed, joined back in within 5 seconds crashed. I walked down the ramp after a few crashes and eventually made it down, at the bottom of the ramp I could play without issue. Next day I attempted to walk up the ramp, crash again.

My View distance is normally 150, if I lower it I can get "closer" to the cause, but if I get too close I can't even load the game, it crashes before I get into the game.  I lower my view distance and I'm good, run away and put my view distance back up.  

Other people can access that part of the map without issue.

Here is the crash details, any ideas how I can access that part of the map again?

=====

Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Simulation

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.Agents.Tree.GetBranchesBSON()
   at Eco.Simulation.Agents.Tree.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at TreeEntity.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, INetObjectContainer monitored)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__54_0()</size>

Log File:
Initialize engine version: 2018.2.20f1 (cef3e6c0c622)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 Ti (ID=0x1b06)
    Vendor:   
    VRAM:     11127 MB
    Driver:   25.21.14.1722
Begin MonoManager ReloadAssembly
- Completed reload, in  0.082 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.326200 ms
Client version: 0.7.8.9 beta
Friday, January 18, 2019 7:26 AM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following icons: TollItem
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

CheckResources () for Camera (WaterDistort) should be overwritten.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

**Comment by DatorzX** [comment]
Is this a client side file or server side file?  I don't see it client side.
I will have to ask the server admin to get me a copy if it's server side.

**Comment by DatorzX** [comment]
Added Game.eco file
[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2793983/Game.zip)

**Comment by redwyre** [comment]
@DatorzX it looks like that game save is corrupt, can you try uploading again?

**Comment by DatorzX** [comment]
[Game.eco 2nd Try.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2810249/Game.eco.2nd.Try.zip)
Stopped server, downloaded game.eco and uploaded to github.  Please let me know if this doesn't work.
