### ISSUE TITLE
0.8: reap PitherPlant cause exception.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11016]
```
Server encountered an exception:

<size=60.00%>Exception: ArgumentNullException
Message:Значение не может быть неопределенным.
Parameter name: key
Source:mscorlib

System.ArgumentNullException: Значение не может быть неопределенным.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Items.ItemAttribute.Get[T](Type itemType)
   at Eco.Gameplay.Plants.PlantEntity.TryHarvest(Player player, Boolean picked, Inventory targetInv)
   at Eco.Mods.TechTree.ScytheItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>
```

**Comment by BlazeGuy2** [comment]
Bumped up pri and milestone, easy fix.

**Comment by elfl0rd** [comment]
this is one of wetland plant. for now it's not spawned naturally :) (before wetland biome returns).
