### ISSUE TITLE
[8.0 Staging]  Error with Interactive window usage

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#11070]
This is an error that is happening when running a client world and there os no console or serverUI that is opening.  It also happens on servers that the serverUI is opened in the interactive services window instead on on the desktop which is where the serverUI is usually opened on servers  hosting Multiple Eco Servers so as to not clutter up the desk top and the console is directed into a separate console window which also copies to  log.  this has not happened with previous versions so I am wondering what was changes so the can try to resolve this either in the game panel hosting or in some other way.

Finished in 33.6msFinished in 7,908.6ms[02:58:27] Initializing NetworkManager... 
Finished in 47.6ms[02:58:27] Initializing WorldLayerManager... 
Finished in 0.1ms[02:58:27] Initializing WebServerPlugin... 
Finished in 471.1ms[02:58:27] Initializing IntegrationTestsPlugin... 
Finished in 0.7ms[02:58:27] Server Initialization finished in 24,817.0ms
[02:58:27] This operation requires an interactive window station
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Eco.Plugins.Networking.Firewall.EnsureRule(String serviceName, ProtocolType protocolType, Int32 port)

**Comment by iaidan** [comment]
This error is still happening.


[20:36:17.808] [5] [ Info] [Eco] Initializing WebServerPlugin...  
[20:36:18.141] [29] [Error] [Eco] System.ComponentModel.Win32Exception: This operation requires an interactive window station.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Eco.Plugins.Networking.Firewall.EnsureRule(String serviceName, ProtocolType protocolType, Int32 port)
 
[20:36:20.203] [29] [ Info] [Eco] Web Server now listening on: http://45.92.36.36:3001
 
[20:36:20.203] [5] [ Info] [Eco] Initializing WebServerPlugin... Finished in 2,402.6ms
 
[20:36:20.203] [5] [ Info] [Eco] Initializing IntegrationTestsPlugin...  
[20:36:20.203] [5] [ Info] [Eco] Initializing IntegrationTestsPlugin... Finished in 0.4ms
 
[20:36:21.186] [5] [ Info] [Eco] Saving world...  
[20:36:21.398] [118] [Error] [Eco] System.ComponentModel.Win32Exception: This operation requires an interactive window station.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Eco.Plugins.Networking.Firewall.EnsureRule(String serviceName, ProtocolType protocolType, Int32 port)

**Comment by WeaselDog** [comment]
This should be fixed in update 0.9.3
