### ISSUE TITLE
USER ISSUE: Connection failed

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#11259]
**Version:** 0.8.0.1 beta

**Steps to Reproduce:**
1. Try to join any server from the main menu
2. Receive "Connection failed" message
3. Get into the mp worlds list
4. Fail miserably

**Expected behavior:**
It should have worked

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: KeyNotFoundException
Message:The given key was not present in the dictionary.
Source:mscorlib

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.ModKit.ModContentSync.SendContentFiles(List`1 requestList, INetClient targetClient)
   at Eco.Plugins.Networking.Client.RequestContent(List`1 requestList)</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: KeyNotFoundException
Message:The given key was not present in the dictionary.
Source:mscorlib

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.ModKit.ModContentSync.SendContentFiles(List`1 requestList, INetClient targetClient)
   at Eco.Plugins.Networking.Client.RequestContent(List`1 requestList)</size>
```

**Comment by HetNeSS** [comment]
Steam file integrity check passed, no results

**Comment by HetNeSS** [comment]
Seems like it's not just me. A half of our server is sitting here, and the issue had somewhat happened to occur to people who even were already been able to get onto the 0.8.0.1 server earlier. It's only three people left online, everyone else is a sitting duck at discord.

**Comment by HetNeSS** [comment]
Seems like it was a one-time thing, something about unity updates-on-the-go. One server restart and we're back in business

**Comment by mirasrael** [comment]
Seems self-fixed by user report. @HetNeSS thanks for info!
