### ISSUE TITLE
Unable to connect to single player game

### ISSUE THREAD

**Issue by Padavar89** [StrangeLoopGames/EcoIssues#11307]
Trying to create a new world but get "Connection timed out" less than 20 seconds after choosing to launch the new world. I've tried with already existing  saves as well. 

Below is the error that I am receiving 

System.Exception: Error in Arashi_ConsoleCommands at 52: The best overloaded method match for 'Eco.Gameplay.Players.Player.SendTemporaryMessage(Eco.Shared.Localization.LocString, Eco.Shared.Services.ChatCategory)' has some invalid arguments (CS1502)
Error in Arashi_ConsoleCommands at 52: Argument 1: cannot convert from 'System.FormattableString' to 'Eco.Shared.Localization.LocString' (CS1503)
Error in Arashi_ConsoleCommands at 83: The best overloaded method match for 'Eco.Gameplay.Players.Player.SendTemporaryMessage(Eco.Shared.Localization.LocString, Eco.Shared.Services.ChatCategory)' has some invalid arguments (CS1502)
Error in Arashi_ConsoleCommands at 83: Argument 1: cannot convert from 'System.FormattableString' to 'Eco.Shared.Localization.LocString' (CS1503)

   at Eco.ModKit.RuntimeCompiler.HandleCompilerError(CompilerResults results)
   at Eco.ModKit.RuntimeCompiler.LoadOrCompileMods()
   at Eco.ModKit.ModKitPlugin..ctor(TaskCompletionSource`1 done) 
[12:45:10.899] [1] [ Info] [Eco] Saving...

**Comment by Padavar89** [comment]
Updated error. Looked at log to get correct error message.

**Comment by Padavar89** [comment]
Found the issue. Forgot I had installed a mod. removed and it is working now.
