### ISSUE TITLE
Server ISSUE : Error while Server updated from 0.8.0.3 to 0.8.0.4

### ISSUE THREAD

**Issue by SteelaCell** [StrangeLoopGames/EcoIssues#11512]
The Server generated an error after i updated the server from 0.8.0.3 to 0.8.0.4
Server starting without any problems in 0.8.0.3
I tried to update an older savegame ( 02/24/2019 ) and the same happend
tried to update the server with ecoserver32 and the Memory is getting full
its never generated an Dump Folder or corrupt file

[06:47:12] Server Initialization...
[06:47:12] Starting LocalizationPlugin... Finished in 186,4ms
[06:47:13] Starting ModKitPlugin... Finished in 982,6ms
[06:47:13] Loading mods...
[06:47:13] Compiling mods... Finished in 904,6ms
[06:47:14] Loading Eco.IntegrationTests...
[06:47:14] Loading mods finished in 981,2ms
[06:47:14] Starting NetworkManager... Finished in 27,0ms
[06:47:14] Initializing Simulation Types... Finished in 337,6ms
[06:47:14] Starting WorldGeneratorPlugin... Finished in 204,6ms
[06:47:14] Starting BackupPlugin... Finished in 3,7ms
[06:47:14] Starting GameplayStatsPlugin... Finished in 0,1ms
[06:47:14] Starting StorageManager... Finished in 2.114,9ms
[06:47:14] Initializing items... Finished in 2.360,8ms
[06:47:16] Starting PausePlugin... Finished in 7,8ms
[06:47:16] Loading Pause... Finished in 2,6ms
[06:47:16] Initializing skills... Finished in 48,1ms
[06:47:16] Starting StatDatabase... Finished in 8,7ms
[06:47:16] Starting WorldPlugin... Finished in 26.067,5ms
[06:47:16] Loading World... Finished in 3.112,7ms
[06:47:19] Converting world to new format... Finished in 22.928,3ms
[06:47:42] Server Initialization finished in 29.992,9ms
[06:47:42] Failed to load server, Exception was Exception: Exception
Message:1 Error(s) occurred when converting world
Source:Eco.World

System.Exception: 1 Error(s) occurred when converting world
   at Eco.World.PersistentChunkGrid.Convert()
   at Eco.World.PersistentChunkGrid.Initialize()
   at Eco.World.WorldPlugin..ctor()

**Comment by pamduncan** [comment]
This was resolved in discord support  - related to #11502

**Comment by BlazeGuy2** [comment]
https://github.com/StrangeLoopGames/EcoIssues/wiki/Work-around:-Converting-world-to-new-format-crashing-in-0.8.0.4

**Comment by SteelaCell** [comment]
That dont Work .... That Looks Like i have an corrupt chunk ?

**Comment by mirasrael** [comment]
@SteelaCell please upload and attach your world save file to this issue

**Comment by SteelaCell** [comment]
[URL=https://www.file-upload.net/download-13522268/Game-2019-02-27-17.03.12.zip.html]Game-2019-02-27-17.03.12.zip[/URL]

**Comment by mirasrael** [comment]
@SteelaCell can you please upload to google drive or something like this? Every time when I try to download from your link it shows me ads and offers to install malicious software.

**Comment by SteelaCell** [comment]
yes ofc

**Comment by mirasrael** [comment]
I checked your save. It seems corrupted for some reason. It doesn't fail on 0.8.0.3, because it doesn't touch every chunk during load. Only while world converted. I can repair it, but part of world may disappear. Or you can try to restore from older backup (if it is an option).

**Comment by SteelaCell** [comment]
thanks for you fast help :) you don t need to repair this savegame because we started a new one :) my friends and me are happy that is not our mistake that the savegame is lost ^^ 
we only want that this issue will not more create ^^
