### ISSUE TITLE
Server keeps restarting after 0.8.0.5

### ISSUE THREAD

**Issue by Bilgard** [StrangeLoopGames/EcoIssues#11535]
Since 0.8.0.5, my server keeps restarting with the following error(timestamps are in CET it's a german server):

`--BEGIN DUMP--
Dump Time
03/01/2019 13:59:21

Exception
Exception: InvalidOperationException
Message:Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application.
Source:System.Windows.Forms

System.InvalidOperationException: Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application.
   at System.Windows.Forms.MessageBox.ShowCore(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
   at Eco.Server.Startup.CheckWorkingDirectory()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

--END DUMP--`

**Comment by redwyre** [comment]
Was it a problem with the working directory?
