### ISSUE TITLE
Caught exception invoking RPC RemoveTrade on StorefrontInventory!

### ISSUE THREAD

**Issue by eviltek2099** [StrangeLoopGames/EcoIssues#1153]
Having a full inventory and clicking yes to remove: the first dump I had no empty slots, the second one i didn't have weight requirement to pick up.
--BEGIN DUMP--
Dump Time
03/09/2017 21:25:01
Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!
Caught exception invoking RPC RemoveTrade on StorefrontInventory!
Could not apply inventory changes! Inventory is full.
Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Items.InventorySafe.TryRemoveStack(InventoryBase inv, ItemCollection stack, User user)
   at Eco.Gameplay.Components.StorefrontInventory.RemoveTrade(Player player, ItemCollection stack)
Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer(Int64 maxMilliseconds)
   at Eco.Shared.Networking.NetPort.Update(Int64 maxMilliseconds)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_0()
--END DUMP--

--BEGIN DUMP--
Dump Time
03/09/2017 21:37:12
Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!
Caught exception invoking RPC RemoveTrade on StorefrontInventory!
Could not apply inventory changes! Inventory is full.
Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Items.InventorySafe.TryRemoveStack(InventoryBase inv, ItemCollection stack, User user)
   at Eco.Gameplay.Components.StorefrontInventory.RemoveTrade(Player player, ItemCollection stack)
Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer(Int64 maxMilliseconds)
   at Eco.Shared.Networking.NetPort.Update(Int64 maxMilliseconds)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_0()
--END DUMP--

**Comment by eviltek2099** [comment]
both crashed my client, it didn't effect the server.

**Comment by johnkslg** [comment]
fixed
