### ISSUE TITLE
Crafting tables not working (again)

### ISSUE THREAD

**Issue by Chaostheory2** [StrangeLoopGames/EcoIssues#11619]
basically the craft timers pause, the stations loop the sound but never make anything. Sleeping is disabled if this helps. happens at random. restart fixes the problem.

**Comment by uwap** [comment]
In addition to that: We are a server with about 50 to 100 active players who have large crafting projects open at all times.

**Comment by uwap** [comment]
We got two different potential null pointer exceptions that could have caused the bug. One of the is relative to stockpiles and the other one to contracts.

```
--BEGIN DUMP--
Dump Time
03/02/2019 08:39:48

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.Inventory.FillTargetStack(Type itemType, ItemStack targetStack, Func2 sourceStackPredicate, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable1 results)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

--END DUMP--
--BEGIN DUMP-- Dump Time 03/05/2019 12:53:49 Exception Exception: NullReferenceException Message:Object reference not set to an instance of an object. Source:Eco.Gameplay System.NullReferenceException: Object reference not set to an instance of an object. at Eco.Gameplay.Economy.Contracts.ContractClauseFinanceBase.Accept(User contractor, User client) at Eco.Gameplay.Economy.Contracts.Contract.<AcceptClauses>b__115_0(ContractClause x) at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext() at System.Linq.Buffer1..ctor(IEnumerable1 source) at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source)
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable1 e, String sep) at Eco.Gameplay.Economy.Contracts.Contract.AcceptJob(Player player) --END DUMP--
```
