### ISSUE TITLE
Client tooltip exception

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1163]
[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/838823/Dump.zip)

the Staging Alpha 5.5 #Ca9adc0e  was running fine no issues major for 3 days of game time roughly then all of a sudden out of blue it started to cause problems across the server for every one.

mostly issue started showing up in tool tips for one person then two people then every one where people get kicked for looking at items that where fine before, then server started crashing to the desktop on the server machine end  all the client network files are in dump zip along with the server crash files.
the dump file shows the progression over time from the 10th to the 13th as for frequency and as problems start become more of issue over time.

the other thing happened in game world is that the carts over night lost there deeds, became unattached from deeds so they became public items instead of private items.

they are also now really hard to push back wards which makes it hard to go up and down ramps that are in mines where you alot of time end up with not enough room to turn around.

the server is running 32 gigs ram AMD FX-8350 Black Edition Vishera 8-Core 4.0 with 2008 OS

**Comment by metachronism** [comment]
--BEGIN DUMP--
Dump Time
03/13/2017 01:58:21

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC GetTooltip on CharredMeatItem!

Exception has been thrown by the target of an invocation.
Sequence contains no elements


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Shared.Utils.ReflectionUtils.TryGetValueAsMethod(MemberInfo member, Object o, Object[] methodParams)
   at Eco.Shared.Utils.ReflectionUtils.Value(MemberInfo member, Object o, Object[] parameters)
   at Eco.Gameplay.Systems.Tooltip.TooltipExtensions.TooltipMember.GetContent(Object[] methodParams)
   at Eco.Gameplay.Systems.Tooltip.TooltipExtensions.<>c__DisplayClass10_0`1.<GetTooltipStrings>b__1(TooltipMember member)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable`1 e, String sep)
   at Eco.Gameplay.Systems.Tooltip.TooltipExtensions.GetTooltipBSON(Object obj, Player player, Type[] excludes)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer(Int64 maxMilliseconds)
   at Eco.Shared.Networking.NetPort.Update(Int64 maxMilliseconds)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_0()

--END DUMP--
