### ISSUE TITLE
[Server] 0.8.0.7 Beta Error 601: Argument Value out of Range

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#11678]
Version: 0.8.0.7 beta server

Steps to Reproduce:

Unknown all I did was a fresh install and then start
the server and it was throwing this error. 

Expected behavior:

That you will not get this error 601 it should
not be throwing this error.

Any mods installed?: No mods installed totally stock! 

Do you have mods installed? No

Actual behavior:

Well this is a brand new fresh installed I used the config 
files right from the zip file which was downloaded 
from the website. 

This was a brand new fresh install of 0.8.0.7 Beta server and 
I have not copied anything over I have no mods installed 
this was a fresh and brand new install. The only thing changed
was the world size in WorldGenerator.eco I changed the world
size to 200,200 and that was it and I started the server and let
it generate the world and then it started up and was throwing this 
error. 

  "Dimensions": {
    "x": 200,
    "y": 200
  },

I didn't copy any config files over or anything and used a db 
generated by this version of the game and it is throwing 
this error. 

The server is running Windows 7 with 20 GB of RAM.  I have
attached  a dxdiag with all the machine stats.

[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2968322/DxDiag.txt)

The exact error that I was getting is 

[14:03:51.039] [134] [ Info] [Eco] Error 601: Argument Value Out of Range
   at Open.Nat.SoapClient.GetXmlDocument(String response)
   at Open.Nat.SoapClient.<InvokeAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Open.Nat.StreamExtensions.<TimeoutAfter>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Open.Nat.UpnpNatDevice.<GetAllMappingsAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Eco.Plugins.Networking.UPnPMapper.<CreateAsync>d__3.MoveNext()

The logs have been attached as well. 

[log_190314014815.log](https://github.com/StrangeLoopGames/EcoIssues/files/2968319/log_190314014815.log)

![Eco Server 0 8 0 7 Error 601 March 14 2019](https://user-images.githubusercontent.com/38896397/54388942-9317df80-4664-11e9-96ab-aaa97e98a67c.jpg)

**Comment by mirasrael** [comment]
You can safely ignore this message, it will fallback to default connection schema if unable to create UPnP mapping.

**Comment by thereporter42** [comment]
I sohuldn't be getting this message in the first place it should silently fall back then
and not be displaying any message. 

This issue needs to be looked into and resolved still.
