### ISSUE TITLE
USER ISSUE: Press Y the Client crash

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#11670]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
Press Y the client crash
Restart the client fix the issue for a while. 

**Expected behavior:**
Menue to be open up. 

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.TradeTracker.get_Balance()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Items.Actionbar.EconomyViewerItem.OnSelected(Player player, ItemStack stack)</size>
```

**Comment by Quadbro** [comment]
Can you pack a world save, please?

**Comment by Alteraner** [comment]
Hello @Quadbro, the file is round about 180 MB big. The db is more than 4 GB, so i skiped it. If you need to have the db as well, let me know. Here is the link to the file:
https://1drv.ms/u/s!AqAvy5MYOuASwDOWFRmFIJ1dS5Sg (oneDrive because here is not more than 10MB allowed)
