### ISSUE TITLE
8.0.7: kicked after cutting tree

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#11685]
System.NullReferenceException: The object reference isn't set to an instance of an object.
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at TreeEntity.TryDamageStump(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>

**Comment by mirasrael** [comment]
Are you using any mods on your server?

**Comment by mirasrael** [comment]
You can use this server file until next hot-fix (it has 0.8.0.7 version as last released hot-fix)
[EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2971882/EcoServer.zip)

**Comment by Praefator** [comment]
Fix applied. @mirasrael I do use mods.

**Comment by Praefator** [comment]
This particular fix seems to have fixed things for one of my players, however one of the others has yet to log back in to test

**Comment by Praefator** [comment]
Been getting reports from players that they are unable to re-enter and a server reboot not helping

**Comment by Praefator** [comment]
People have been able to re-enter after a while (see #11684), however same error seems to occur every time someone is clearing a stump

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:De objectverwijzing is niet op een exemplaar van een object ingesteld.
Source:Eco.Shared

System.NullReferenceException: The object reference isn't set to an instance of an object
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at TreeEntity.TryDamageStump(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>

**Comment by mirasrael** [comment]
Should be fixed in next build
