### ISSUE TITLE
USER ISSUE: Fatal Law Bug

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#11749]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**

1. Pass a law that affects the run for office function.
2. Let it pass.
3. Try to open the law menu.

**Expected Behavior:**
It should have worked just fine.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Unhandled enum value Leader
Source:Eco.Gameplay

System.Exception: Unhandled enum value Leader
   at Eco.Gameplay.LegislationSystem.LawLogic.ActionQueries.PerformerActionQuery.GetQueryForAttempt(IPlayerAction action)
   at Eco.Gameplay.LegislationSystem.LawLogic.NumericValues.ActionNumericValue.GetValue(IPlayerAction action)
   at Eco.Gameplay.LegislationSystem.LawLogic.Conditions.NumericComparisonCondition.IsMet(IPlayerAction action)
   at Eco.Gameplay.LegislationSystem.LawLogic.ControlFlow.LawControlFlowList.IsRelevant(IPlayerAction action)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Items.Law.<>c__DisplayClass86_0.<IsRelevant>b__0(IPlayerActionManager manager)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)</size>
```

**Comment by Blanclour** [comment]
TITLE Presidential Term Act USER Auron
LAW
When attempting to Run For Office
If (the World Leader's Play hours where (time performed (days) > (current time (days) - 1.5)) = 0)
Then allow
Otherwise
If (everyone's Get Elected actions where (time performed (days) > (current time (days) - 5)) = 0)
Then allow
Otherwise prevent

This is what I think is causing it.

**Comment by Deantwo** [comment]
@Blanclour, interesting law.

**Comment by Blanclour** [comment]
I was hoping to create a law that gave presidents a generous amount of time in office while also allowing people to start another election if the president goes inactive.

**Comment by Deantwo** [comment]
@Blanclour, yup I see that, just looks like a nice idea. Might be a nice addition to the #law-examples channel.
Anyway, this is a bad place to discuss this.
