### ISSUE TITLE
USER ISSUE: Rubble pickup exception

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#11794]
**Version:** 0.8.1.0 beta staging-3ce3fe75 debug*-6

**Steps to Reproduce:**
Mined Limestone with a stone pickaxe, pickup rubble by holding e

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: Trying to remove non-existing block
Source:Eco.Core

System.Exception: A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: Trying to remove non-existing block
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply() in C:\slg\Eco\Server\Eco.Core\Utils\AtomicAction\MultiAtomicAction.cs:line 57
   at Eco.Gameplay.Objects.RubbleObject`1.TryPickup(Player actor, Inventory inv) in C:\slg\Eco\Server\Eco.Gameplay\Objects\RubbleObject.cs:line 326
   at Eco.Gameplay.Objects.RubbleObject`1.OnActInteract(InteractionContext context) in C:\slg\Eco\Server\Eco.Gameplay\Objects\RubbleObject.cs:line 309
   at Eco.Gameplay.Players.Player.<>c__DisplayClass60_0.<PlayerInteract>b__2(IInteractable inter) in C:\slg\Eco\Server\Eco.Gameplay\Players\Player.cs:line 323
   at Eco.Gameplay.Interactions.InteractionExtensions.<>c__DisplayClass2_1`1.<ExecuteUntilSuccess>b__1() in C:\slg\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 102
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results) in C:\slg\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 111
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T](IEnumerable`1 enumerable, Func`2 resultFunc) in C:\slg\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 102
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info) in C:\slg\Eco\Server\Eco.Gameplay\Players\Player.cs:line 329</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: Trying to remove non-existing block
Source:Eco.Core

System.Exception: A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: Trying to remove non-existing block
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply() in C:\slg\Eco\Server\Eco.Core\Utils\AtomicAction\MultiAtomicAction.cs:line 57
   at Eco.Gameplay.Objects.RubbleObject`1.TryPickup(Player actor, Inventory inv) in C:\slg\Eco\Server\Eco.Gameplay\Objects\RubbleObject.cs:line 326
   at Eco.Gameplay.Objects.RubbleObject`1.OnActInteract(InteractionContext context) in C:\slg\Eco\Server\Eco.Gameplay\Objects\RubbleObject.cs:line 309
   at Eco.Gameplay.Players.Player.<>c__DisplayClass60_0.<PlayerInteract>b__2(IInteractable inter) in C:\slg\Eco\Server\Eco.Gameplay\Players\Player.cs:line 323
   at Eco.Gameplay.Interactions.InteractionExtensions.<>c__DisplayClass2_1`1.<ExecuteUntilSuccess>b__1() in C:\slg\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 102
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results) in C:\slg\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 111
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T](IEnumerable`1 enumerable, Func`2 resultFunc) in C:\slg\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 102
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info) in C:\slg\Eco\Server\Eco.Gameplay\Players\Player.cs:line 329</size>
```

**Comment by SeanAtr0n** [comment]
Duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/11790
