### ISSUE TITLE
USER ISSUE: Opening someone's trash pile causes the client to disconnect

### ISSUE THREAD

**Issue by Frederikam** [StrangeLoopGames/EcoIssues#11818]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
1. Open a pile of trash

Other steps unknown.

**Expected behavior:**
The inventory should have been opened.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: ArgumentNullException
Message:Der Wert darf nicht NULL sein.
Source:mscorlib

System.ArgumentNullException: Der Wert darf nicht NULL sein.
   at System.Threading.Monitor.Enter(Object obj)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.GarbageInventoryBlock.GetBSON(InteractionContext context)
   at Eco.Gameplay.Objects.GarbageInventoryBlock.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>
```

I have no idea why this particular pile causes the exception.

The contents is wood pulp and plant fibers. Anyone who opens it, including the dumper, is kicked from the server. 

**Do you have mods installed? Does issue happen when no mods are installed?:**

There are no mods installed.

**Comment by Frederikam** [comment]
It's not my server, but I'll try to get a hold of the save.

I don't think the server has restarted recently.

I also noticed that one of my trash piles is permanently stuck at 100% decomposition.

**Comment by mirasrael** [comment]
@Frederikam do you have this issue on 8.1?

**Comment by Frederikam** [comment]
@mirasrael I have no way of reproducing it.

**Comment by D3nnis3n** [comment]
Closing as no reproduction case can be found. Open a new issue when it reoccurs and you have more information.
