### ISSUE TITLE
Client unable to connect to Server

### ISSUE THREAD

**Issue by frenchy128** [StrangeLoopGames/EcoIssues#1185]
Type: Server/Client
OS: Windows 10 Pro
Description: I restarted my server, and the restart happened without issue. When I attempt to connect my client to the server, I see the normal loading progress percentages increase, but when it gets to the "world" progress, it goes from 0% to 100% immediately, and promptly returns me to the server list. 
Reproduceable:  this isn't the first time it happened, happened last night, but was able to use a backup to get back in, today I've tried all the backups that in the Storage/Backup folder to no aval. 
Version: 0.5.4

Server Error Message: 
[08:57] Caught update exception from Frenchy128!  Disconnecting...
[08:57] Disconnecting client [reason: Caught exception: Object reference not set to an instance of an object.]...

Dump File: 
--BEGIN DUMP--
Dump Time
03/21/2017 13:08:57

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.PropertyPlot.get_Deed()
   at Eco.Gameplay.Property.PropertyPlot.ToBson()
   at Eco.Gameplay.Minimap.MinimapManager.GetPropertySince(Double time)
   at Eco.Gameplay.Minimap.MinimapManager.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_1()

--END DUMP--

**Comment by MarjieAVolk** [comment]
It looks like the code that caused this has already been changed significantly in 5.5 - closing for now.  If you keep experiencing this problem, feel free to open another issue!
