### ISSUE TITLE
Can't load old map and can't create new map either

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11933]
A user on steam reports he cannot convert his old world, nor create a new one, failing to connect on each time.

This is the map he tried to convert: https://drive.google.com/file/d/1k6WDIwEwMefrsnEcTedUEACJf_fiS1RT/view?usp=drive_web

I found an issue when converting the map through singleplayer, it throws an OOM error:

> [21:09:04.616] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
> [21:09:04.631] [1] [ Info] [Eco] Eco Server 0.8.1.1 beta
>  
> [21:09:04.735] [1] [ Info] [Eco] Server Initialization...  
> [21:09:04.735] [1] [ Info] [Eco] Starting LocalizationPlugin...  
> [21:09:05.013] [1] [ Info] [Eco] Starte ModKitPlugin...  
> [21:09:05.013] [1] [ Info] [Eco] Lade Mods...  
> [21:09:05.080] [1] [ Info] [Eco] Mods kompilieren...  
> [21:09:06.993] [1] [ Info] [Eco] Lade Eco.IntegrationTests...
>  
> [21:09:07.003] [1] [ Info] [Eco] Lade Mods finished in 1.988,7ms
>  
> [21:09:07.003] [1] [ Info] [Eco] Starte NetzwerkManager...  
> [21:09:07.003] [7] [ Info] [Eco] Initialisiere Simulationstypen...  
> [21:09:07.036] [16] [ Info] [Eco] Starte WeltGenerationsPlugin...  
> [21:09:07.036] [9] [ Info] [Eco] Starte GameplayStatsPlugin...  
> [21:09:07.036] [6] [ Info] [Eco] Starte BackupPlugin...  
> [21:09:07.036] [6] [ Info] [Eco] Starte LagerManager...  
> [21:09:08.217] [7] [ Info] [Eco] Objekte initialisieren...  
> [21:09:10.475] [6] [ Info] [Eco] Starte PausePlugin...  
> [21:09:10.475] [6] [ Info] [Eco] Lade Pause...  
> [21:09:10.915] [7] [ Info] [Eco] Fertigkeiten initialisieren...  
> [21:09:10.980] [6] [ Info] [Eco] Starte StatDatenbank...  
> [21:09:10.980] [14] [ Info] [Eco] Starte WeltPlugin...  
> [21:09:11.007] [14] [ Info] [Eco] Lade World...  
> [21:09:17.760] [14] [ Info] [Eco] Converting world to new format...  
> [21:10:12.840] [1] [ Info] [Eco] Server Initialization finished in 68.105,4ms
>  
> [21:10:12.844] [1] [ Info] [Eco] Failed to load server, Exception was Exception: OutOfMemoryException
> Message:Exception of type 'System.OutOfMemoryException' was thrown.
> Source:Eco.Core
> 
> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at Eco.Core.Utils.ThreadSafeQueue`1.Enqueue(T item)
>    at Eco.World.PersistentChunkGrid.<>c__DisplayClass8_1.<Convert>b__0(Vector2i posXZ)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object ) 
> [21:10:27.850] [1] [ Info] [Eco] Speichere...
>  

Converting by using the 64-bit exe works fine.

**Comment by D3nnis3n** [comment]
I assume the user may have altered world settings and the 32-bit server does not like them, i've asked him to provide information on the settings he used, as i could not reproduce not being able to create a new world.

**Comment by D3nnis3n** [comment]
The old world is a 4 km² world.
