### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12056]
> [03:00:07.693] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
> [03:00:07.708] [1] [ Info] [Eco] Eco Server 0.8.1.3 beta
>  
> [03:00:07.771] [1] [ Info] [Eco] Server Initialization...  
> [03:00:07.771] [1] [ Info] [Eco] Starting LocalizationPlugin...  
> [03:00:08.036] [1] [ Info] [Eco] Starting ModKitPlugin...  
> [03:00:08.036] [1] [ Info] [Eco] Loading mods...  
> [03:00:08.130] [1] [ Info] [Eco] Compiling mods...  
> [03:00:09.318] [1] [ Info] [Eco] Loading mods finished in 1.279,3ms
>  
> [03:00:09.318] [1] [ Info] [Eco] Starting NetworkManager...  
> [03:00:09.333] [5] [ Info] [Eco] Initializing Simulation Types...  
> [03:00:09.364] [12] [ Info] [Eco] Starting BackupPlugin...  
> [03:00:09.364] [6] [ Info] [Eco] Starting WorldGeneratorPlugin...  
> [03:00:09.364] [11] [ Info] [Eco] Starting GameplayStatsPlugin...  
> [03:00:09.364] [12] [ Info] [Eco] Starting StorageManager...  
> [03:00:09.833] [5] [ Info] [Eco] Initializing items...  
> [03:00:11.271] [12] [ Info] [Eco] Starting PausePlugin...  
> [03:00:11.286] [12] [ Info] [Eco] Loading Pause...  
> [03:00:12.614] [5] [ Info] [Eco] Initializing skills...  
> [03:00:12.630] [1] [ Info] [Eco] Server Initialization finished in 4.864,7ms
>  
> [03:00:12.646] [1] [ Info] [Eco] Failed to load server, Exception was Exception: KeyNotFoundException
> Message:Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
> Source:mscorlib
> 
> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
>    at System.ThrowHelper.ThrowKeyNotFoundException()
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at Eco.Gameplay.Skills.SkillTree.<>c__DisplayClass79_0.<BuildSkillTrees>b__9(Type rootSkillType)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object ) 
>

**Comment by D3nnis3n** [comment]
This error did also not cause an "exit", so my server did not try to restart again. It only happened on the first two tries, the third one worked without having changed anything. Totally weird issue.
