### ISSUE TITLE
Yet Another Sever Crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12114]
> --BEGIN DUMP--
> Dump Time
> 04/21/2019 18:44:04
> 
> Exception
> Exception: KeyNotFoundException
> Message:Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
> Source:mscorlib
> 
> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
>    at System.ThrowHelper.ThrowKeyNotFoundException()
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at Eco.Simulation.RouteProbing.RouteManager.AllWalkablesY(WorldPosition3i pos, Int32 searchRange, Int16 matchRegion)
>    at Eco.Simulation.Agents.AI.AIUtilities.FindRoute(Vector3 position, Single minRadius, Single maxRadius, Vector2 direction, Single minDirectionOffsetDegrees, Single maxDirectionOffsetDegrees, Int32 tryCount)
>    at Eco.Mods.Organisms.Behaviors.MovementBehaviors.LandMovement(Animal agent, Vector2 direction, Single speed, AnimalAnimationState state, Single minDistance, Single maxDistance, Single minDirectionOffsetDegrees, Single maxDirectionOffsetDegrees, Int32 tryCount)
>    at Eco.Mods.Organisms.Behaviors.GroupBehaviors.FollowLeader(Animal agent, Single maxDistance)
>    at Eco.Simulation.Agents.AI.FunctionalBehaviorTree`1.Selector(T context, Func`2[] children)
>    at Eco.Simulation.Agents.Animal.Tick()
>    at Eco.Simulation.Simulation.TickAll()
>    at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
>    at Eco.Simulation.EcoSim.DoTick(TickSample tick)
>    at Eco.Simulation.EcoSim.Run()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 
> --END DUMP--
>

**Comment by D3nnis3n** [comment]
Copied from my dump folder, occured three days ago - i cannot give reproduction steps for those unfortunately, as they just happen when i'm not there. If you cannot find the cause for one of those (though you found all of them yet), feel free to just close.
