### ISSUE TITLE
Version 5.5.1 Server Crash to desktop 

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1214]
Not sure what caused it but it just went straight to desktop.

[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/866898/Dump.zip)

add dump file for the crash

**Comment by MarjieAVolk** [comment]
Here are the exceptions from the dump:

1.)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.Player.SendInitialState(BSONObject obj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_1()

2.)
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.World.WorldPlugin.<>c__DisplayClass16_0.<Run>b__0(PersistentChunk chunk)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()

3.)
System.Exception: Caught exception invoking RPC ViewRPC on Client!
Caught exception invoking RPC AttachCurrentProperty on AuthorizationController!
The given key was not present in the dictionary.

Stack:
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Property.PropertyManager.AttachCurrentProperty(Player player, Guid authId)
   at Eco.Gameplay.Property.AuthorizationController.AttachCurrentProperty(Player player)

**Comment by MarjieAVolk** [comment]
#3 looks like an encounter with StrangeLoopGames/EcoIssues#1041 - I'm handling that one, so ignore that

**Comment by metachronism** [comment]
1) fixed in 5.5.2, this is an issue with being outside world boundaries
2) also fixed in 5.5.2
