### ISSUE TITLE
Server hangs - ClientReceiveException

### ISSUE THREAD

**Issue by FlyNeko48** [StrangeLoopGames/EcoIssues#12264]
Seems it happened when two person tried to move the same stack of reinforced concrete at one moment
```
--BEGIN DUMP--
Dump Time
05/12/2019 00:24:36

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.Inventory.CheckAuthForMove(ItemStack source, ItemStack target, User user, Int32& allowedQuantity)
   at Eco.Gameplay.Items.InventoryChangeSet.MoveStacks(ItemStack source, ItemStack destination, User user)
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, User user)
   at Eco.Gameplay.Items.Inventory.MoveItemsDoublePass(Player player, ItemStack sourceStack, ItemStack targetStack, Inventory alternativeInventoryTarget)

--END DUMP--
```

**Comment by beastyn** [comment]
@FlyNeko48 thank you for report.
Which version do you use to play?

**Comment by FlyNeko48** [comment]
8.1.4

**Comment by beastyn** [comment]
@FlyNeko48 
can you provide save with .db file?
https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by SlayksWood** [comment]
Checked on 8.2.0 staging-986 and before. Wasn't able to reproduce, seems fixed.
