### ISSUE TITLE
[0.8.2 staging -7-n] The error with the server starting

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12284]
[03:31:18] Eco Server 0.8.2.0 beta staging-5ae9b501*-7
[03:31:18] Server Initialization...
[03:31:18] Starting LocalizationPlugin... _Finished in 321.9ms_
[03:31:18] Error when loading Mod string tables:
Exception: DirectoryNotFoundException
Message:Не удалось найти часть пути "G:\Games\Steam\steamapps\common\Eco\Eco_Data\Server\Mods\Translations".
Source:mscorlib

System.IO.DirectoryNotFoundException: Не удалось найти часть пути "G:\Games\Steam\steamapps\common\Eco\Eco_Data\Server\Mods\Translations".
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Eco.Shared.Localization.Localizer.LoadStrings()[03:31:18] _Starting _ModKitPlugin__... _Finished in 1 810.6ms_
[03:31:18] _Loading mods_...

**Comment by BlazeGuy2** [comment]
It's a bug with how we export the server.
