### ISSUE TITLE
Exception while deleting blocks with devtool

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#12365]
![image](https://user-images.githubusercontent.com/14983165/58046228-8d71c680-7af9-11e9-808c-25e69ffc3703.png)

Got this while deleting some sand, sandstone, and iron ore from a beach with the devtool.

**Comment by keegan-o** [comment]
Server encountered an exception:

<size=60.00%>Exception: KeyNotFoundException
Message:The given key was not present in the dictionary.
Source:System.Collections.Immutable

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Core.Utils.ThreadSafeDictionary`2.get_Item(TKey key) in C:\Eco\Server\Eco.Core\Utils\ThreadSafeDictionary.cs:line 21
   at Eco.Gameplay.Minimap.MinimapManager.RemoveMinimapObject(IMinimapObject minimapObject) in C:\Eco\Server\Eco.Gameplay\Minimap\MinimapManager.cs:line 177
   at TreeEntity.Destroy()
   at Eco.Simulation.PlantSim.DestroyPlant(Plant plant, DeathType deathType, Boolean applyToWorldLayer) in C:\Eco\Server\Eco.Simulation\PlantSim.cs:line 290
   at DevtoolItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Players.Player.<>c__DisplayClass60_0.<PlayerInteract>b__0(IInteractable inter) in C:\Eco\Server\Eco.Gameplay\Players\Player.cs:line 329
   at Eco.Gameplay.Interactions.InteractionExtensions.<>c__DisplayClass2_1`1.<ExecuteUntilSuccess>b__1() in C:\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 109
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results) in C:\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 118
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T](IEnumerable`1 enumerable, Func`2 resultFunc) in C:\Eco\Server\Eco.Gameplay\Interactions\IInteractable.cs:line 109
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info) in C:\Eco\Server\Eco.Gameplay\Players\Player.cs:line 341</size>

Log File:
Log File missing.

**Comment by mirasrael** [comment]
Fixed as part of another fix.
