### ISSUE TITLE
Crash from Giant-Tortoise

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12451]
--BEGIN DUMP--
Dump Time
05/16/2019 07:32:37

Exception
Exception: ArgumentOutOfRangeException
Message:Specified argument was out of the range of valid values.
Parameter name: index
Source:System.Collections.Immutable

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.get_Item(Int32 index)
   at Eco.Gameplay.Wires.WireOutput.SendItem(ItemStack item, Boolean divideAmongOutputs)
   at Eco.Gameplay.Pipes.LiquidComponents.LiquidConverterComponent.OnConsumed(Type type, Int32 amount)
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at Eco.Gameplay.Pipes.LiquidComponents.LiquidConsumerComponent.OnReceive(ItemStack stack)
   at Eco.Gameplay.Wires.WireOutput.SendItem(ItemStack item, Boolean divideAmongOutputs)
   at Eco.Gameplay.Pipes.LiquidComponents.LiquidProducerComponent.Tick()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

--END DUMP--

**Comment by mirasrael** [comment]
Already fixed in 8.2
