### ISSUE TITLE
Migration for 9.0 needs to be fixed

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#12462]
All of the master PRs were failing with this error: 

testmigration: Test Failed with an exception

=====EXCEPTION in Server Loading=====

Exception: Exception
Message:Error(s) occurred when loading Users
Source:Eco.Core

System.Exception: Error(s) occurred when loading Users
at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
at Eco.Gameplay.Players.UserManager..ctor()

**Comment by BlazeGuy2** [comment]
Save:
https://drive.google.com/file/d/1ExAqbqNn7xQV3nmwopNlyUZaY0tWLPSO/view?usp=sharing

**Comment by PiezoMnemonic** [comment]
Having the same error when trying to start a personal server.

**Comment by PiezoMnemonic** [comment]
[15:55:20.330] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 

[15:55:20.356] [1] [ Info] [Eco] Eco Server 0.8.3.0 beta
 
[15:55:20.428] [1] [ Info] [Eco] Server Initialization...  
[15:55:20.428] [1] [ Info] [Eco] Starting LocalizationPlugin...  
[15:55:20.780] [1] [ Info] [Eco] Starting ModKitPlugin...  
[15:55:20.780] [1] [ Info] [Eco] Loading mods...  
[15:55:20.893] [1] [ Info] [Eco] Compiling mods...  
[15:55:22.715] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[15:55:22.715] [1] [ Info] [Eco] Loading mods finished in 1,941.5ms
 
[15:55:22.715] [1] [ Info] [Eco] Starting NetworkManager...  
[15:55:22.729] [5] [ Info] [Eco] Initializing Simulation Types...  
[15:55:22.959] [7] [ Info] [Eco] Starting BackupPlugin...  
[15:55:22.965] [7] [ Info] [Eco] Starting StorageManager...  
[15:55:23.119] [6] [ Info] [Eco] Starting WorldGeneratorPlugin...  
[15:55:23.205] [6] [ Info] [Eco] Starting GameplayStatsPlugin...  
[15:55:23.352] [5] [ Info] [Eco] Initializing items...  
[15:55:26.259] [7] [ Info] [Eco] Starting PausePlugin...  
[15:55:26.988] [5] [ Info] [Eco] Initializing skills...  
[15:55:27.065] [6] [ Info] [Eco] Starting StatDatabase...  
[15:55:27.065] [8] [ Info] [Eco] Starting WorldPlugin...  
[15:55:27.105] [8] [ Info] [Eco] Loading World...  
[15:55:42.802] [8] [ Info] [Eco] Converting world to new format...  
[15:55:44.749] [8] [ Info] [Eco] Initializing world...  
[15:55:44.792] [8] [ Info] [Eco] Starting TimePlugin...  
[15:55:44.792] [8] [ Info] [Eco] Loading Time...  
[15:55:44.792] [8] [ Info] [Eco] Starting ReputationPlugin...  
[15:55:44.792] [8] [ Info] [Eco] Loading Reputation...  
[15:55:44.792] [8] [ Info] [Eco] Starting PlayerHousingManager...  
[15:55:44.808] [8] [ Info] [Eco] Starting UserManager...  
[15:55:44.831] [8] [ Info] [Eco] Loading Users...  
[15:55:44.930] [1] [ Info] [Eco] Server Initialization finished in 24,501.7ms
 
[15:55:44.933] [1] [ Info] [Eco] Failed to load server, Exception was Exception: Exception
Message:Error(s) occurred when loading Users
Source:Eco.Core

System.Exception: Error(s) occurred when loading Users
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.Gameplay.Players.UserManager..ctor()
