### ISSUE TITLE
[0.8.2-staging 993] Contracts: fix for repeated contract

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12518]
**Steps**
1. Create the repeated contract Put In Container
2. Let someone take it for the first time
3. After completing let this person take it for the second time and complete
**Expected**
Just complete it
**Actual**
Our someone is putting needed stuff in the container but contract is not completing

**Comment by beastyn** [comment]
Repetions won't be saved with contract now, Reset to 1 always.
![bandicam 2019-12-04 19-13-19-586](https://user-images.githubusercontent.com/27898520/70149553-2b119980-16ca-11ea-83fb-bc0502180fca.jpg)
![bandicam 2019-12-04 19-13-23-008](https://user-images.githubusercontent.com/27898520/70149555-2c42c680-16ca-11ea-9a99-44b811c43c98.jpg)
![bandicam 2019-12-04 19-13-27-892](https://user-images.githubusercontent.com/27898520/70149558-2d73f380-16ca-11ea-9c0a-96689768f326.jpg)

**Comment by beastyn** [comment]
Ok, numbers are fine, but when another person is trying to take the contract, client is crashing
```
<size=60.00%>Exception: MissingMethodException
Message:No parameterless constructor defined for type 'Eco.Gameplay.Items.SearchAndSelect.SearchAndSelectItem'.
Source:System.Private.CoreLib

System.MissingMethodException: No parameterless constructor defined for type 'Eco.Gameplay.Items.SearchAndSelect.SearchAndSelectItem'.
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Eco.Gameplay.Civics.Misc.Cloner.Clone(Object source, Boolean topLevel)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyList(IList sourceVal, IList destVal)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyTo(Object source, Object dest)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyTo(Object source, Object dest)
   at Eco.Gameplay.Civics.Misc.Cloner.Clone(Object source, Boolean topLevel)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyList(IList sourceVal, IList destVal)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyTo(Object source, Object dest)
   at Eco.Gameplay.Civics.Misc.Cloner.Clone(Object source, Boolean topLevel)
   at Eco.Gameplay.Civics.Misc.Cloner.Clone(Object source)
   at Eco.Gameplay.Economy.Contracts.ContractManager.RepeatContract(Contract oldContract)
   at Eco.Gameplay.Economy.Contracts.Contract.AcceptJob(User user)
   at Eco.Gameplay.Economy.Contracts.Contract.AcceptJob(Player player)</size>
```
