### ISSUE TITLE
Server crashes when trying to get into law interface when the auth server is unreachable

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12533]
--BEGIN DUMP--
Dump Time
06/13/2019 15:33:44

Exception
Exception: SocketException
Message:Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat 50.112.72.195:443
Source:System
NativeErrorCode:10060
ErrorCode:10060

System.Net.Sockets.SocketException (0x80004005): Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat 50.112.72.195:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

--END DUMP--

**Comment by D3nnis3n** [comment]
Servers shouldnt crash when master server is unreachable.
