### ISSUE TITLE
[8.2.0] Crash when 8.1.4 or older connects to 8.2.0 server

### ISSUE THREAD

**Issue by quequiere** [StrangeLoopGames/EcoIssues#12570]
Hello since the update we have crash when the server saving arround 15 minutes after boot.

Here is the error log:

`--BEGIN DUMP--
Dump Time
06/19/2019 07:39:56

Exception
Exception: ArgumentOutOfRangeException
Message:Index and count must refer to a location within the buffer.
Parameter name: bytes
Source:mscorlib

System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
Parameter name: bytes
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeLocString(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeDocument(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.Load(Stream stream)
   at Eco.Shared.Networking.NetMessage.DecodePacket(NetIncomingMessage message)
   at Eco.Plugins.Networking.NetworkServer.<Initialize>b__23_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--`

**Comment by mirasrael** [comment]
Hello @quequiere ! Thanks for report. Can you pleas attach your server save (or you can send it to me in Discord)?

**Comment by quequiere** [comment]
I sent you the complete save on discord

**Comment by mirasrael** [comment]
You can get fixed version here:
[EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3305048/EcoServer.zip)

**Comment by mirasrael** [comment]
Fixed version in case if you don't want to wait until 8.2.1: [EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3305082/EcoServer.zip)
