### ISSUE TITLE
Sea Otter Crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12614]
> --BEGIN DUMP--
> Dump Time
> 06/20/2019 23:05:36
> 
> Exception
> Exception: NullReferenceException
> Message:Object reference not set to an instance of an object.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Eco.Gameplay.Players.Stomach.get_CalorieRate()
>    at Eco.Gameplay.Players.Stomach.UseCalories(Single change)
>    at Eco.Gameplay.Players.User.Tick()
>    at Eco.Simulation.Simulation.TickAll()
>    at Eco.Gameplay.Players.UserManager.Run()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 
> --END DUMP--

**Comment by D3nnis3n** [comment]
Happens around all 3 hours.
