### ISSUE TITLE
Pressing 'E' on Tree Stumps boots player from server

### ISSUE THREAD

**Issue by jvantuyl2000** [StrangeLoopGames/EcoIssues#1277]
After felling a tree, I clicked 'E' on the leftover stump and was booted from the server. 

Here is the EcoServer.exe response lines from the event:

[39:41] Disconnecting client [reason: Caught exception: Caught exception invoking RPC PlayerInteract on Player!

The given key was not present in the dictionary.

Stack:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
]...

(Thanks for the great game! I'll do what I can to help report any bugs/issues I come across!)

**Comment by metachronism** [comment]
fixed already in 5.5.2 :)

**Comment by jvantuyl2000** [comment]
Awesome - thanks!
