### ISSUE TITLE
[0.8.2.9] Crash while taking item from stockpile (multiplayer)

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12821]
1. Try to pick an item from stockpile with actLeft in one time with other player.
(was tested with fast left-right clicking on stockpile by two people).

Crash is:
```
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   at Eco.Gameplay.Items.ToolItem.<>c.<GetPreferedItem>b__46_1(ItemStack x)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Items.ToolItem.GetPreferedItem(Inventory inventory, Item carriedItem, Boolean takeAll)
   at Eco.Gameplay.Components.StorageComponent.GetItemsUserCanTake(WorldObject worldObject, User user, Item carriedItem, Item selectedItem, Boolean tryTakeAll)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Objects.WorldObject.OnActComponents(InteractionContext context, Func`2 regularInteractionMethod, Func`2 fallbackInteractionMethod)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>
```

2. Also there is a crash which I can't reprosuce but it seemd to have the same reason:

```
 at Eco.Gameplay.Items.ToolItem.<>c.b__46_0(ItemStack x)
 at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count) 
 at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count) 
 at System.Linq.OrderedEnumerable`1.d__1.MoveNext() 
 at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate) 
 at Eco.Gameplay.Items.ToolItem.GetPreferedItem(Inventory inventory, Item carriedItem, Boolean takeAll) 
 at Eco.Gameplay.Components.StorageComponent.GetItemsUserCanTake(WorldObject worldObject, User user, Item carriedItem, Item selectedItem, Boolean tryTakeAll)
  at Eco.Gameplay.Components.StorageComponent.GetActDesc(InteractionContext context) 
 at Eco.Gameplay.Objects.WorldObject.OnActComponentsDesc(InteractionContext context) 
 at Eco.Gameplay.Players.Player.GetPlayerInteractDescs(InteractionInfo info)
```

**Comment by SlayksWood** [comment]
`System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   at Eco.Gameplay.Components.StorageComponent.<>c.<GetItemsUserCanTake>b__14_4(Item i)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Components.StorageComponent.GetItemsUserCanTake(WorldObject worldObject, User user, Item carriedItem, Item selectedItem, Boolean tryTakeAll)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Objects.WorldObject.OnActComponents(InteractionContext context, Func`2 regularInteractionMethod, Func`2 fallbackInteractionMethod)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>`
