### ISSUE TITLE
[0.8.3.0 release-preview] Exception while connecting from the old client to the new server

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12962]
when trying to connect from 0.8.2.9 client to the 0.8.3 server by ID (or continue) we've got this message:
```
System.Exception: Original type is Object. Cannot convert from Object to Array
   at Eco.Shared.Serialization.BSONValue.get_ArrayValue()
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__56_2()
```

It should be fixed already #12570
Similar to #12327

**Comment by SlayksWood** [comment]
Fixed with https://github.com/StrangeLoopGames/Eco/pull/4933
#13010
