### ISSUE TITLE
Powered cart crossing world border causing server crashes

### ISSUE THREAD

**Issue by Stephenw92-git** [StrangeLoopGames/EcoIssues#1297]
Hi SLG, we've had a number of crashes on our server overnight, the biggest issue for us is that if a powered cart crosses and 0 co-ordinate, it crashes the server.

--BEGIN DUMP--
Dump Time
03/30/2017 08:49:37

Exception
System.AggregateException: One or more errors occurred. ---> **System.IndexOutOfRangeException:** Index was outside the bounds of the array.
   at Eco.Simulation.WorldLayers.Layers.WorldLayer.EntryWorldPos(Vector2i pos)
   at Eco.Simulation.ClimateSim_.**AddAirPollution(Vector2i pos, Single newPollution)_**
   at Eco.Gameplay.Components.**AirPollutionComponent.Tick(Single dtime)**
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Simulation.WorldLayers.Layers.WorldLayer.EntryWorldPos(Vector2i pos)
   at Eco.Simulation.ClimateSim.AddAirPollution(Vector2i pos, Single newPollution)
   at Eco.Gameplay.Components.AirPollutionComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Inner Exception
System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Simulation.WorldLayers.Layers.WorldLayer.EntryWorldPos(Vector2i pos)
   at Eco.Simulation.ClimateSim.AddAirPollution(Vector2i pos, Single newPollution)
   at Eco.Gameplay.Components.AirPollutionComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Simulation.WorldLayers.Layers.WorldLayer.EntryWorldPos(Vector2i pos)
   at Eco.Simulation.ClimateSim.AddAirPollution(Vector2i pos, Single newPollution)
   at Eco.Gameplay.Components.AirPollutionComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

--END DUMP--

**Comment by Stephenw92-git** [comment]
currently attempting to modify the powered cart but as yet haven't had much luck
