### ISSUE TITLE
5.5.3 Repetitive server crash caused by coal/inventory slot

### ISSUE THREAD

**Issue by Stephenw92-git** [StrangeLoopGames/EcoIssues#1321]
We had a server crash with the following crash log, each time the server came back online we would be moving for 10 seconds before another crash with the same log:
some light reading for you :) 

--BEGIN DUMP--
Dump Time
04/03/2017 01:59:15

Exception
System.AggregateException: One or more errors occurred. ---> Eco.Gameplay.Items.InventoryException: Could not apply inventory changes! Coals cannot be placed in that inventory.
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Components.FuelSupplyComponent.LoadFuel()
   at Eco.Gameplay.Components.FuelSupplyComponent.TryConsumeFuel(Single joules)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) Eco.Gameplay.Items.InventoryException: Could not apply inventory changes! Coals cannot be placed in that inventory.
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Components.FuelSupplyComponent.LoadFuel()
   at Eco.Gameplay.Components.FuelSupplyComponent.TryConsumeFuel(Single joules)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Inner Exception
System.AggregateException: One or more errors occurred. ---> Eco.Gameplay.Items.InventoryException: Could not apply inventory changes! Coals cannot be placed in that inventory.
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Components.FuelSupplyComponent.LoadFuel()
   at Eco.Gameplay.Components.FuelSupplyComponent.TryConsumeFuel(Single joules)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) Eco.Gameplay.Items.InventoryException: Could not apply inventory changes! Coals cannot be placed in that inventory.
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Components.FuelSupplyComponent.LoadFuel()
   at Eco.Gameplay.Components.FuelSupplyComponent.TryConsumeFuel(Single joules)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

--END DUMP--

**Comment by Stephenw92-git** [comment]
Thunder asked me to add:
Our theory is that the issue is linked with a furnace (or similar) or the powered cart.

Theory about the powered cart is because we have just upgraded to 5.5.3 from 5.5.1 last night and the players not seeing the changelog may have tried fuelling it with coal.

Theory with the furnace or similar station being because between 2 of the crashes me and 2 other players were the only players who connected. all of us were in voice chat and none of us moved and it still crashed again. 
one of those players wasn't online before the original crash, one was shovelling iron before the crash and i was nowhere near coal. from what i can tell (but i can by no means guarantee) nobody else was moving coal immediately before the original crash.

i was also asked to provide a world save as it may be of use : 
https://app.box.com/s/lma4t9u3z52ibp6habc3tiighsifyqki

**Comment by Stephenw92-git** [comment]
I may have found the cause! 
Ok so we were hit by the same server crash and dump file tonight, rolled back by an hour and in the meantime i downloaded a backup half an hour previous and half an hour ahead of the roll back to try to prevent the issue from recurring. 

the same players were online and i was more than confident that i knew where to find the issue, there was a group who started with the fresh server in 5.5 and i went through their furnaces etc removing the fuels before finding an induction generator. the induction generator was placed in 5.5.1 and had the hotfix added because of the deadlock with powering the pumpjack.
i.e. when it was placed it was made to accept only solid fuels, therefore when we transferred to 5.5.3, that hotfix wasn't removed and the induction generator, still fuelled with COAL, was just a ticking time bomb waiting for the same player to come online at the same time to hit order on the pumpjack.
The current fuel in the generator would then count down and when reaching 0 and transferring the next coal item into the fuel slot, the game would crash because its the wrong fuel type. 

bug solved by yours truly :)

\o/ \o/
