### ISSUE TITLE
[8.3] Servercrash from Legislation

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#13247]
We think Player didnt had enoug Money for the Craftingtax

Exception
Exception: InvalidOperationException
Message:Sequence contains no elements
Source:System.Core

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, String noneText)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicRoot.IsAllowed(IPlayerAction action)
   at Eco.Gameplay.Legislation.CreateAtomicAction(IPlayerAction action)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.Stats.PlayerActionManager`1.CreateAtomicAction(T action)
   at Eco.Gameplay.Items.WorkOrder.CreateCraftOneAction()
   at Eco.Gameplay.Items.WorkOrder.get_AvailableWork()
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders(Single dtime)
   at Eco.Gameplay.Components.CraftingComponent.Tick()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--

**Comment by mirasrael** [comment]
Legislation system was rewritten in 9.0. Please, re-open this if it will happen in 9.0.
