### ISSUE TITLE
[master-preview] World can't be loaded 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13318]
[08:44:57.075] [3] [Error] [Eco] Failed to load server, Exception was Exception: InvalidOperationException
Message:Операция является недопустимой из-за текущего состояния объекта.
Source:Eco.World

System.InvalidOperationException: Операция является недопустимой из-за текущего состояния объекта.
   at Eco.World.WorldChunkGrid.GetTopSolidBlock(Vector2i worldPos)
   at Eco.World.World.UpdateCachedDataUnsafe(Vector3i worldPos, Block block)
   at Eco.World.World.SetBlock[T](Vector3i worldPos, Object[] args)
   at Eco.World.Blocks.WaterBlock.TryMoveWater(Vector3i worldPosition, Block nearbyBlock, Single waterValue, Boolean checkForSolidBase)
   at Eco.World.Blocks.WaterBlock.Tick(Vector3i worldPosition)
   at Eco.World.PersistentChunk.Tick()
   at Eco.World.WorldPlugin.<>cDisplayClass30_0.<Initialize>b2(PersistentChunk chunk)
   at System.Threading.Tasks.Parallel.<>cDisplayClass42_0`2.<PartitionerForEachWorker>b1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>cDisplayClass176_0.<ExecuteSelfReplicating>b0(Object <p0>)
![image](https://user-images.githubusercontent.com/45708377/66748229-4fea4d00-ee8f-11e9-8156-efe292af5e5b.png)

**Comment by beastyn** [comment]
And I have different errors, when loading created Game

[15:41:41.348] [3] [Error] [Eco] Failed to load server, Exception was Exception: NullReferenceException
Message:Ссылка на объект не указывает на экземпляр объекта.
Source:Eco.Simulation

System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   at Eco.Simulation.RouteProbing.RouteManager.InitRouteCache(Boolean quick)
   at Eco.Simulation.RouteProbing.RouteManager.OnLoaded()
   at Eco.Simulation.RouteProbing.RouteProbingPlugin..ctor()
