### ISSUE TITLE
[master-preview] /civics testgameactions issues

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13410]
1. Use /civics testgameactions 
2. After some time server was shutdown with db error (] Timeout for db write operation)
3. After restarting server we can't connact with error

```
<size=60,00%>Exception: NullReferenceException
Message:Ссылка на объект не указывает на экземпляр объекта.
Source:mscorlib

System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   at System.Object.GetType()
   at Eco.Gameplay.Civics.CivicAction_ChangeElement.get_Describe()
   at Eco.Gameplay.Civics.Election.get_Description()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass13_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient boundClient)
   at Eco.Core.Controller.ControllerManager.ToBson(Object obj, INetClient client)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client, Boolean doAllParams)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(IDictionary dictionary, INetClient client, Boolean useReflection)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient boundClient)
   at Eco.Core.Controller.ControllerManager.ToBson(Object obj, INetClient client)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client, Boolean doAllParams)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(IDictionary dictionary, INetClient client, Boolean useReflection)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient boundClient)
   at Eco.Gameplay.Players.Player.SendInitialState(BSONObject obj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, INetObjectContainer monitored)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__61_0()</size>
```

In other case:
1. Use command
2. Shut down server properly
3. Try to start server and see this error
```
[12:25:21.093] [3] [Error] [Eco] Failed to load server, Exception was Exception: ArgumentNullException

Parameter name: key
Source:System.Collections.Immutable

Parameter name: key
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
 ```

**Comment by johnkslg** [comment]
This happens due to server attempting to load half-finished save, where some references were lost because those datastores were not saved. This will go away when we only allow saves with proper fixes. 

Can you file a separate issue for the db timeout error if there isnt one already?

**Comment by mirasrael** [comment]
Seems fixed in latest version. Also I found and fix problem with MinimapManager during investigation.

**Comment by beastyn** [comment]
will check later with new PR from Stanis
