### ISSUE TITLE
Crafting workbench with no ingredients failed:

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13456]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.Inventory.<>c__DisplayClass57_0.<TotalNumberOfItems>b__0(ItemStack stack)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Items.WorkOrder.<>c__DisplayClass172_0.<ScanInventoryAndContribute>b__0(IInventoryChangeSet changeSet)
   at Eco.Gameplay.Items.Inventory.Modify(Action`1 callback, User user)
   at Eco.Gameplay.Items.WorkOrder.ScanInventoryAndContribute(User actor, Inventory inventory)
   at Eco.Gameplay.Components.CraftingComponent.AddWorkOrderToBench(Player player, WorkOrder workOrder, BankAccount account)
   at Eco.Gameplay.Components.CraftingComponent.CreateWorkOrder(Player player, RecipeFamily recipe, Int32 quantity, BankAccount account, Boolean automatic)</size>

**Comment by Hakuhonoo** [comment]
Done in https://github.com/StrangeLoopGames/Eco/pull/5163
