### ISSUE TITLE
Workbench order

### ISSUE THREAD

**Issue by RobertMangano** [StrangeLoopGames/EcoIssues#13471]
When placing an order for a workbench from the starting tent, I would be disconnected from the server.

**Comment by SlayksWood** [comment]
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.Inventory.<>c__DisplayClass57_0.<TotalNumberOfItems>b__0(ItemStack stack)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Items.Inventory.TotalNumberOfItems(String itemTag)
   at Eco.Gameplay.Items.WorkOrder.<>c__DisplayClass172_0.<ScanInventoryAndContribute>b__0(IInventoryChangeSet changeSet)
   at Eco.Gameplay.Items.Inventory.Modify(Action`1 callback, User user)
   at Eco.Gameplay.Items.WorkOrder.ScanInventoryAndContribute(User actor, Inventory inventory)
   at Eco.Gameplay.Components.CraftingComponent.AddWorkOrderToBench(Player player, WorkOrder workOrder, BankAccount account)
   at Eco.Gameplay.Components.CraftingComponent.CreateWorkOrder(Player player, RecipeFamily recipe, Int32 quantity, BankAccount account, Boolean automatic)</size>
```

**Comment by SlayksWood** [comment]
dup #13456
