### ISSUE TITLE
[0.9.0 staging-1189] NullReferenceException

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13478]
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Shared

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Serialization.SimpleBSON.EncodeBinary(MemoryStream stream, Byte[] buf)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.BSONObject.Encode(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.SimpleBSON.EncodeArray(MemoryStream stream, BSONArray array)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.BSONObject.Encode(MemoryStream stream)
   at Eco.Plugins.Networking.NetworkServer.SendMessage(NetworkEvent netEvent, BSONObject bsonObj, Object connection)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.SendEvent(NetworkEvent netEvent, BSONObject bsonObj, INetClient target, INetObject netObj)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__61_0()</size>
 ```
I have fresh server with only /level 30,30, /bt 3,30,10,30,1,1 , /preset crafting and during 1 hour I place different crafting table. When the crash happened, I was jumping along the wall.
![image](https://user-images.githubusercontent.com/45708377/67764572-5665f080-fa5b-11e9-9a7f-91c57e95dbbf.png)

**Comment by mirasrael** [comment]
Not enough information for reproduce and not clear log to identify problem.

**Comment by mirasrael** [comment]
I added improved logging for SendMessage. So next time we will have more info.
