### ISSUE TITLE
[0.9.0 staging-1206] Crash with craft

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13491]
I can not reproduce it with 100%. It happen 2 times for me today. First time I can't say what I do. The second time I tried to move an order in queue
![image](https://user-images.githubusercontent.com/45708377/67857662-6ef00c80-fb28-11e9-8418-ef79ccb91d0b.png)
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.User.UpdateWorkOrderMarkers()
   at Eco.Gameplay.Components.CraftingComponent.AddWorkOrderToBench(Player player, WorkOrder workOrder, BankAccount account)
   at Eco.Gameplay.Components.CraftingComponent.CreateWorkOrder(Player player, RecipeFamily recipe, Int32 quantity, BankAccount account, Boolean automatic)</size>
```
[Crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3788784/Crash.txt)

**Comment by Hakuhonoo** [comment]
Cannot reproduce on staging. Tried to drag it all other the panel. While without line number it could be anything in the function. Could we get more detailed log?

**Comment by SlayksWood** [comment]
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.User.UpdateWorkOrderMarkers() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Gameplay\Players\User.cs:line 647
   at Eco.Gameplay.Components.CraftingComponent.AddWorkOrderToBench(User user, WorkOrder workOrder, BankAccount account) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Gameplay\Components\CraftingComponent.cs:line 418
   at Eco.Gameplay.Components.CraftingComponent.AddWorkOrderToBench(Player player, WorkOrder workOrder, BankAccount account) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Gameplay\Components\CraftingComponent.cs:line 363</size>
```
