### ISSUE TITLE
Crash server at yesterday playtest

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13535]
```
--BEGIN DUMP--
Dump Time
10/30/2019 12:52:09

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.User.UpdateWorkOrderMarkers()
   at Eco.Gameplay.Items.WorkOrder.Destroy()
   at Eco.Gameplay.Components.CraftingComponent.<>c.<Initialize>b__66_1(INetObject u, Object x)
   at Eco.Core.Utils.ControllerList`1.Remove(T item)
   at Eco.Gameplay.Components.CraftingComponent.CancelWorkOrder(Player player, WorkOrder workOrder)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

--END DUMP--
```

**Comment by Hakuhonoo** [comment]
Almost duplicate here https://github.com/StrangeLoopGames/EcoIssues/issues/13491

**Comment by Hakuhonoo** [comment]
Probably fixed, need to retest

**Comment by beastyn** [comment]
didn't meet lately. Will check im playtest
