### ISSUE TITLE
[0.9.0 staging-1239] Crash when starting craft

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13599]
Crash when starting craft with having ingredient to several tagged item in one recipe.
Step to reproduce:
- spawn Research table.
- /give Dendrology research paper I
- press order
![image](https://user-images.githubusercontent.com/45708377/68293130-6060a280-009e-11ea-848e-42d11cd202e9.png)
- crash
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Changes could not be applied, the requested operation would result in an invalid inventory state: Inventory does not contain the items requested to be removed
Source:Eco.Gameplay

System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state: Inventory does not contain the items requested to be removed
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.Modify(Action`1 callback, User user) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Gameplay\Items\InventoryRelated\Inventory.cs:line 603
   at Eco.Gameplay.Items.WorkOrder.ScanInventoryAndContribute(User actor, Inventory inventory) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Gameplay\Items\WorkOrder.cs:line 559
   at Eco.Gameplay.Components.CraftingComponent.AddWorkOrderToBench(Player player, WorkOrder workOrder, BankAccount account) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Gameplay\Components\CraftingComponent.cs:line 409
   at Eco.Gameplay.Components.CraftingComponent.CreateWorkOrder(Player player, RecipeFamily recipe, Int32 quantity, BankAccount account, Boolean automatic) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Gameplay\Components\CraftingComponent.cs:line 355</size>
```
[Crash with tagged craft.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3814029/Crash.with.tagged.craft.txt)

**Comment by SlayksWood** [comment]
In last staging you can start research at all.
