### ISSUE TITLE
[0.9.0 staging-1249] Contracts: crash with truck property permission

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13697]
1. /give truck
2. Start creating contract Receive Permission.
3. Pick your truck.
4. Choose Property Rights
5. Post
Crash client with this
```
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Utils.PickerMixed.ValidOwnership(String pickerName, User user)
   at Eco.Gameplay.Economy.Contracts.ContractClausePermissions.Valid(User contractor, User client)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at Eco.Core.Utils.ResultExtensions.Merge(IEnumerable`1 list)
   at Eco.Gameplay.Economy.Contracts.Contract.get_Valid()
   at Eco.Gameplay.Economy.Contracts.Contract.PostJob(User user)
   at Eco.Gameplay.Economy.Contracts.Contract.PostJob(Player player)
```
Can we leave vehicles only as objects?

**Comment by beastyn** [comment]
Its better now.
But I don't want to see truck's property if I can't choose it.
1. Place truck
2. Create contract for property permission. 
3. Pick the truck's property. It won't be picked and show None.
![799249b9fab13de3ff6865f0ea4ac66f](https://user-images.githubusercontent.com/27898520/69213705-b0ebfb80-0b86-11ea-84cc-650c2d74091a.gif)
