### ISSUE TITLE
Error after todays staging update

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13748]
Failed to load server, Exception was Exception: InvalidCastException
Message:Unable to cast object of type 'Eco.Gameplay.Civics.GameValues.GameValueContext`1[Eco.Gameplay.Players.User]' to type 'Eco.Gameplay.Civics.GameValues.GameValue`1[Eco.Gameplay.Aliases.IAlias]'.
Source:Eco.Core

System.InvalidCastException: Unable to cast object of type 'Eco.Gameplay.Civics.GameValues.GameValueContext`1[Eco.Gameplay.Players.User]' to type 'Eco.Gameplay.Civics.GameValues.GameValue`1[Eco.Gameplay.Aliases.IAlias]'.
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<ActionMethodHelper>b__0(TTarget target, Object param)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.<>c__DisplayClass4_0.<Initialize>b__4(Object& obj, Object val)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeReferenceableEnumerable(BinaryReader reader, Object decodeTarget, Int32 numElements)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Decode(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeReferenceableEnumerable(BinaryReader reader, Object decodeTarget, Int32 numElements)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Decode(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.DecodeReferenceableEntry(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.DecodeDictionary(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.Decode(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.CurrentSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.EcoSerializer.DeserializeObject[T](Stream stream)
   at Eco.Core.Serialization.DataStore.Load[T](String folder, Action`1 onLoad, Boolean migrate)
   at Eco.Core.Plugins.StorageManager.LoadOrCreate[TStorageType](String folder, Action`1 onCreate)
   at Eco.Gameplay.Civics.CivicsPlugin..ctor()

**Comment by johnkslg** [comment]
This looks like an internal migration problem between two eco versions. 

For our initial release of 9.0, we're not supporting migration of laws and civics stuff because its changed too much.  So when migrating something that fails, like laws, we should have a failsafe that skips it and allows the rest of the migration to continue, logging an error.  Alex can you make this more fault tolerant?  And once we ship 9 we can make sure migrations between versions work.

**Comment by D3nnis3n** [comment]
Yep, at least dump the stuff that can't be migrated - if required have it be confirmed by the user, with autoconfirm on specific command line parameter. We'll need this for testing, it makes no sense to start the playtest from the beginning for the over 9000th time.

A command filling the database with random users and random amounts of actions of random amounts of time would also be very appreciated to test law stuff accordingly.

**Comment by D3nnis3n** [comment]
Closing for https://github.com/StrangeLoopGames/EcoIssues/issues/13753.
