### ISSUE TITLE
Capitol missing status and other elements

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13754]
Got removed from autogen?

**Comment by Sekor2600** [comment]
@johnkslg When you place a Capitol the Server crashs

Can't encode instance of type 'Eco.Mods.TechTree.CapitolObject'
   at Eco.Core.Serialization.Serializers.NullClassSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags) in J:\Eco-Github\Server\Eco.Core\Serialization\Serializers\NullClassSerializer.cs:line 14
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags) in J:\Eco-Github\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 64
   at Eco.Core.Serialization.SimpleSerializer.Serialize(Object obj) in J:\Eco-Github\Server\Eco.Core\Serialization\SimpleSerializer.cs:line 629
   at Eco.Core.Serialization.ZipBlob.Persist(Object obj) in J:\Eco-Github\Server\Eco.Core\Serialization\DataStore.cs:line 83
   at Eco.Core.Serialization.PersistenceManager.Persist() in J:\Eco-Github\Server\Eco.Core\Serialization\PersistenceManager.cs:line 41
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass1_0.<CreateWithInterval>b__0(CancellationToken token) in J:\Eco-Github\Server\Eco.Core\Utils\Threading\PeriodicWorkerFactory.cs:line 29
   at Eco.Core.Utils.Threading.ActionWorker.MainLoop() in J:\Eco-Github\Server\Eco.Core\Utils\Threading\ActionWorker.cs:line 36
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
