### ISSUE TITLE
[0.9.0 staging] Capital not working in latest staging

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13752]
The capital is not working in latest staging version and can cause the server to crash.

Typing capital in chat:
![capitalchat](https://user-images.githubusercontent.com/47330823/69010094-b3452000-0910-11ea-8ee3-ae740d1ab9cc.png)

Typing /civics spawngov causes a server crash:

System.InvalidOperationException
  HResult=0x80131509
  Message=Can't encode instance of type 'Eco.Mods.TechTree.CapitolObject'
  Source=Eco.Core
  StackTrace:
   at Eco.Core.Serialization.Serializers.NullClassSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags) in C:\EcoSLG\Server\Eco.Core\Serialization\Serializers\NullClassSerializer.cs:line 14
   at Eco.Core.Serialization.Serializers.ObjectSerializer.EncodeWith(ISerializer serializer, BinaryWriter writer, Object instance, SerializeFlags flags) in C:\EcoSLG\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 89
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags) in C:\EcoSLG\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 72
   at Eco.Core.Serialization.SimpleSerializer.Serialize(Object obj) in C:\EcoSLG\Server\Eco.Core\Serialization\SimpleSerializer.cs:line 625
   at Eco.Core.Serialization.CurrentSerializer.Serialize(Object obj) in C:\EcoSLG\Server\Eco.Core\Serialization\Serializers.cs:line 46
   at Eco.Core.Serialization.EcoSerializer.Serialize(Object obj) in C:\EcoSLG\Server\Eco.Core\Serialization\Serializers.cs:line 84
   at Eco.Core.Serialization.ZipBlob.Persist(Object obj) in C:\EcoSLG\Server\Eco.Core\Serialization\DataStore.cs:line 67
   at Eco.Core.Serialization.PersistenceManager.Persist() in C:\EcoSLG\Server\Eco.Core\Serialization\PersistenceManager.cs:line 46
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass1_0.<CreateWithInterval>b__0(CancellationToken token) in C:\EcoSLG\Server\Eco.Core\Utils\Threading\PeriodicWorkerFactory.cs:line 28
   at Eco.Core.Utils.Threading.ActionWorker.MainLoop() in C:\EcoSLG\Server\Eco.Core\Utils\Threading\ActionWorker.cs:line 41
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by johnkslg** [comment]
Fixed
