### ISSUE TITLE
[staging] Civics: Hours Played comparison causes a server crash

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13796]
When you click Hours Played comparison like in the following screenshot, it causes the server to crash. Error log included below.
![HoursPlayed](https://user-images.githubusercontent.com/47330823/69194707-b3931600-0ade-11ea-828a-29345aedb3af.png)

Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.Values.HoursPlayed.get_Describe()
   at Eco.Gameplay.Civics.GameValues.GameValueExtensions.DescribeNullSafe(GameValue val)
   at Eco.Gameplay.Civics.GameValues.Compare.get_Describe()
   at Eco.Gameplay.Civics.GameValues.SetOfConditions.<>c.<get_Describe>b__11_0(GameValue`1 x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable`1 e, String sep)
   at Eco.Gameplay.Civics.GameValues.SetOfConditions.get_Describe()
   at Eco.Gameplay.Civics.Laws.LawSection.<>c.<Description>b__25_1(GameValue`1 x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable`1 e, String sep)
   at Eco.Gameplay.Civics.Laws.LawSection.Description()

**Comment by johnkslg** [comment]
🔨
