### ISSUE TITLE
Civics: Law - Action Count comparison w/ Within Hours set to 0 disconnects client 

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13849]
For action count comparisons, we are meant to set Within Hours to 0 when counting all actions regardless of time. Right now, using a law like this disconnects the player who triggers it. Error log included below.

Law Used: 
![WithinHoursBug](https://user-images.githubusercontent.com/47330823/69367327-eb1fd080-0c4c-11ea-84af-eb6d4f901087.png)

Crash Log:
Exception: ArgumentException
Message:At least two Query should be passed
Source:LiteDB

System.ArgumentException: At least two Query should be passed
   at LiteDB.Query.And(Query[] queries)
   at Eco.Stats.Stats.<>c__DisplayClass15_0.<CountActions>b__0() in C:\EcoSLG\Server\Eco.Stats\New\Stats.cs:line 102
   at Eco.Stats.PendingWritesDiskService.WithReadOnlyTransaction[T](Func`1 action) in C:\EcoSLG\Server\Eco.Stats\PendingWritesDiskService.cs:line 760
   at Eco.Stats.Stats.CountActions(Int32 time, Type action, Single withinHours, Int32 userID) in C:\EcoSLG\Server\Eco.Stats\New\Stats.cs:line 90
   at Eco.Gameplay.Civics.GameValues.ActionCount.Value(IContextObject action) in C:\EcoSLG\Server\Eco.Gameplay\Civics\GameValues\Values\StatGameValues.cs:line 65
   at Eco.Gameplay.Civics.GameValues.Compare.Value(IContextObject action) in C:\EcoSLG\Server\Eco.Gameplay\Civics\GameValues\Values\BasicGameValues.cs:line 34
   at Eco.Gameplay.Civics.GameValues.SetOfConditions.Value(IContextObject action) in C:\EcoSLG\Server\Eco.Gameplay\Civics\GameValues\Values\BasicGameValues.cs:line 77
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action) in C:\EcoSLG\Server\Eco.Gameplay\Civics\Laws\LawSection.cs:line 150
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action) in C:\EcoSLG\Server\Eco.Gameplay\Civics\Laws\LawSection.cs:line 136
   at Eco.Gameplay.Civics.Laws.Law.Perform(GameAction action) in C:\EcoSLG\Server\Eco.Gameplay\Civics\Laws\Law.cs:line 86
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action) in C:\EcoSLG\Server\Eco.Gameplay\Civics\Laws\LawManager.cs:line 37
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, IEnumerable`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects) in C:\EcoSLG\Server\Eco.Gameplay\GameActions\GameActionManager.cs:line 54
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify) in C:\EcoSLG\Server\Eco.Gameplay\GameActions\GameActionManager.cs:line 39
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameAction action, Boolean notify) in C:\EcoSLG\Server\Eco.Gameplay\GameActions\GameActionManager.cs:line 104
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user, INetObject target) in C:\EcoSLG\Server\Eco.Gameplay\Systems\Chat\ChatManager.cs:line 770
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(String text, User user, INetObject target) in C:\EcoSLG\Server\Eco.Gameplay\Systems\Chat\ChatManager.cs:line 704
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChatStripped(Player player, String text, INetObject target) in C:\EcoSLG\Server\Eco.Gameplay\Systems\Chat\ChatManager.cs:line 695

**Comment by johnkslg** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/3536496/69463392-4f679080-0d30-11ea-8675-ebef4ba53b55.png)
