### ISSUE TITLE
[0.9.0 staging] Civics - Server Crash when changing law trigger using comparison values from trigger

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13884]
To replicate this crash, setup law like in the picture. The key part is to have "Hours Since Last Trigger" as the comparison. Change the trigger to something else, like Chat Sent. It will crash the server.

![HoursSinceLastTrigger](https://user-images.githubusercontent.com/47330823/69582214-f47ea500-0f8c-11ea-97d1-ac81055a6639.png)

**Log Info:**
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.Values.HoursPlayed.get_Describe()
   at Eco.Gameplay.Civics.GameValues.GameValueExtensions.DescribeNullSafe(GameValue val)
   at Eco.Gameplay.Civics.GameValues.Compare.get_Describe()
   at Eco.Gameplay.Civics.Laws.LawSection.<>c.<Description>b__25_1(GameValue`1 x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable`1 e, String sep)
   at Eco.Gameplay.Civics.Laws.LawSection.Description()

**Comment by WeaselDog** [comment]
Here is another situation that causes a crash when changing trigger. I am thinking it related to Hours Played comparison only.
![TriggerCrash2](https://user-images.githubusercontent.com/47330823/69591244-fe150680-0fa6-11ea-85b0-d7e655e8f3eb.png)

**Comment by WeaselDog** [comment]
Crash is fixed. It is possible to pass the following law, but it does not cause an error. I believe it treats the incorrect value as 0 and will count all hours played.

![HoursPlayedComparison](https://user-images.githubusercontent.com/47330823/69733174-bc3cab00-10e1-11ea-97f3-453c726b3032.png)
