### ISSUE TITLE
[0.9.0 staging] Contracts: Server crash when accepting a loan

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13942]
This is new in today's build. When accepting a loan, trying to set the loan amount crashes the server no matter which method you use. 

![LoanAcceptanceCrash](https://user-images.githubusercontent.com/47330823/69890868-2e152000-12ad-11ea-95d3-b77c3040c2c4.png)

_(Let me know if it is better to upload a file than copy & paste)_
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Shared

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Serialization.BSONObject.<>c__DisplayClass29_1.<ToStringIndented>g__Text|1(BSONValue property) in C:\EcoSLG\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 981
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable`1 e, String sep) in C:\EcoSLG\Server\Eco.Shared\Utils\StringExtensions.cs:line 163
   at Eco.Shared.Serialization.BSONObject.ToStringIndented(Int32 indentLevel, HashSet`1 visited) in C:\EcoSLG\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 985
   at Eco.Shared.Serialization.BSONArray.<>c__DisplayClass15_0.<ToStringIndented>b__0(BSONValue element) in C:\EcoSLG\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1082
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Eco.Shared.Serialization.BSONArray.ToStringIndented(Int32 indentLevel, HashSet`1 visited) in C:\EcoSLG\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1082
   at Eco.Shared.Serialization.BSONValue.DebugToString() in C:\EcoSLG\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 171
   at Eco.Plugins.Networking.Client.Update() in C:\EcoSLG\Server\Eco.Plugins\Networking\Client.cs:line 387
   at Eco.Plugins.Networking.Client.<.ctor>b__61_0() in C:\EcoSLG\Server\Eco.Plugins\Networking\Client.cs:line 96</size>
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, Boolean)
System.Action`2:Invoke(T1, T2)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
Unity.Jobs.ExecuteJobFunction:Invoke(T&, IntPtr, IntPtr, JobRanges&, Int32)

**Comment by WeaselDog** [comment]
Works fine now for loans & bonds
