### ISSUE TITLE
0.9 removing role from crafting party cause exception

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13947]
(you need add\remove roles multiple times, may take a time)
(Repeatable.)

```
Server encountered an exception:

Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.WorkParties.WorkParty.<>c.<Initialize>b__27_8(Work work, User laborer)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T,TContext](IEnumerable`1 enumerable, TContext context, Action`2 action)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.<Initialize>b__27_7(INetObject p, Object obj)
   at Eco.Core.Utils.ClientControllerExtensions.RemoveAt(IClientControlledList container, INetObject player, Int32 index, PropertyInfo property)
   at Eco.Gameplay.Utils.RPCListExtensions.RemoveAt(IHasClientControlledContainers hasContainers, Player player, String listName, Int32 index)
```

**Comment by beastyn** [comment]
Still in ptogress, didn't see changes. Will leave this in case.

**Comment by SlayksWood** [comment]
Fixed with https://github.com/StrangeLoopGames/Eco/pull/5381
