### ISSUE TITLE
[0.9.0 staging-1282] Contracts: client crash

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13984]
1. Create contract - Put item in container
2. Press Pick
2. Crash
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.PointOfInterestManager.<>c__DisplayClass9_0.<GetList>b__0(PointOfInterest x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   at System.Collections.Immutable.ImmutableList`1.CreateRange(IEnumerable`1 items)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ControllerList`1.<>n__1(IEnumerable`1 items)
   at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass14_0.<AddRange>b__0()
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Core.Utils.ControllerList`1.AddRange(IEnumerable`1 items)
   at Eco.Core.Utils.ThreadSafeList`1..ctor(IEnumerable`1 contents)
   at Eco.Core.Utils.ControllerList`1..ctor(IController parent, String propertyName, IEnumerable`1 contents)
   at Eco.Gameplay.Economy.PointOfInterestList..ctor(IEnumerable`1 list)
   at Eco.Gameplay.Economy.PointOfInterestManager.GetList(String category, User owner, Boolean excludeZero, Boolean excludeEmpty)
   at Eco.Gameplay.Utils.Picker.GetView(Player player)
   at Eco.Gameplay.Utils.Picker.Pick(Player player)</size>
```

**Comment by olegshegai** [comment]
Repeated the required change. Might be a merging problem from some recent contract-related PR.
