### ISSUE TITLE
[0.9.0 staging-1285] Client crush with vehicle deed transfer

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14008]
1. Truck is not on my deed
![bandicam 2019-12-04 17-02-27-875](https://user-images.githubusercontent.com/27898520/70141033-eda41080-16b7-11ea-888b-209bb3f3b325.jpg)

2. I want to tranfer deed rights to rhe other player
![bandicam 2019-12-04 17-02-43-775](https://user-images.githubusercontent.com/27898520/70141037-ef6dd400-16b7-11ea-85fa-da96108b528e.jpg)

3. Crush
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Utils.Result.op_Implicit(Result result)
   at Eco.Gameplay.Property.Deed.<>c__DisplayClass68_0.<ChangeOwners>b__1(WorldObject x)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Eco.Gameplay.Property.Deed.ChangeOwners(Player changer, IAlias owner)</size>
```

**Comment by SlayksWood** [comment]
```
System.NullReferenceException Object reference not set to an instance of an object.
   at Eco.Core.Utils.Result.op_Implicit(Result result)
   at Eco.Gameplay.Property.Deed.c__DisplayClass73_0.CanChangeOwnerb__1(WorldObject x)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Property.Deed.CanChangeOwner(Player changer, IAlias owner)
   at Eco.Gameplay.Property.Deed.TryChangeOwners(GameActionPack pack, Player changer, IAlias newOwner, Boolean transferAction, Boolean autoPerform)
   at Eco.Gameplay.Property.Deed.ChangeOwners(Player changer, IAlias newOwner)size
```
