### ISSUE TITLE
TestPostedWorkParty - CI problem after additional 'run tests'

### ISSUE THREAD

**Issue by olegshegai** [StrangeLoopGames/EcoIssues#14137]
Jenkins is currently ending-up with a 'build succeeded' message, but after additional 'run tests' command it breaks with a NullReferenceException. 
The problem seems to be UI-related, here is a full message:
```
Failed to run Generated world CI tests
civicstestgameactions: Test Failed with 1 exceptions.

=====EXCEPTION 0=====
Warning: Exception Caught in Test civicstestgameactions - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Core

System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Core.Controller.ControllerManager.AddPendingView(IController controller, IMvcNetClient client)
at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient boundClient)
at Eco.Gameplay.Players.UIUtils.OpenUI(Player player, IController ui, String uiName)
at Eco.Gameplay.Economy.WorkParties.WorkPartyManager.CreateWorkParty(User user, WorkPartyType workPartyType)
at Eco.Gameplay.GameActions.GameActionTestsUtil.CreateTestParty(User client)
at Eco.Gameplay.GameActions.GameActionTests.TestPostedWorkParty(User mainUser)
```

**Comment by johnkslg** [comment]
Should be fixed now.
