### ISSUE TITLE
[0.9.0 staging-1298] DrillItem causes server crash.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14151]
```
Can't encode instance of type 'Eco.Mods.TechTree.DrillItem'
   at Eco.Core.Serialization.Serializers.NullClassSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.SimpleSerializer.Serialize(Object obj)
   at Eco.Core.Serialization.ZipBlob.Persist(Object obj)
   at Eco.Core.Serialization.PersistenceManager.Persist()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass1_0.<CreateWithInterval>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.ActionWorker.MainLoop()
```
[log_191216021003.log](https://github.com/StrangeLoopGames/EcoIssues/files/3967803/log_191216021003.log)

**Comment by SlayksWood** [comment]
We have drillItem that you can add to store and server crash.
![image](https://user-images.githubusercontent.com/45708377/72342505-a14be780-36dd-11ea-9420-3511eda7fe84.png)
