### ISSUE TITLE
[0.9.0 staging-1307] Crash with Transport Contract

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14212]
Step to reproduce:
- create contract like:
![image](https://user-images.githubusercontent.com/45708377/71352140-8971bf80-2586-11ea-95f5-550fee8bf916.png)
- crash when try to take this contract.
```
<size=60,00%>Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'source')
Source:System.Linq

System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.GroupedEnumerable`2..ctor(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.GroupBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at Eco.Gameplay.Items.ItemStackExtensions.Consolidate(IEnumerable`1 stackList)
   at Eco.Gameplay.Utils.PickerTracker.SetRemaining(IEnumerable`1 stacks)
   at Eco.Gameplay.Economy.Contracts.ContractClauseTransport.<TryJoin>b__21_0()
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, IEnumerable`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Economy.Contracts.Contract.ConfigureAndTryPerform(WorkableAction action, Action`2 checkClause, User citizen, Boolean notify)
   at Eco.Gameplay.Economy.Contracts.Contract.AcceptJob(User user)
   at Eco.Gameplay.Economy.Contracts.Contract.AcceptJob(Player player)</size>
```
[Crash with Transport Contract.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3994513/Crash.with.Transport.Contract.txt)

**Comment by olegshegai** [comment]
Crash cases fixed, but there is a problem related to inventories. 
You can complete the clause only by manual drag'n'dropping, as it was mentioned in #eco-code channel:
> There is a difference between manual object drag'n'dropping to an existing stack and moving to an empty slot (or just right-clicking on it). The first way triggers game actions, the second one - doesn't.

**Comment by SlayksWood** [comment]
Hm, I still have crash. I add the same source and target.

**Comment by olegshegai** [comment]
John reverted the PR, I will resubmit it today

**Comment by SlayksWood** [comment]
I still have this crash when I try to take Transport contract:
![image](https://user-images.githubusercontent.com/45708377/71963407-9cce8d00-320c-11ea-8022-988a10770596.png)
Maybe change notification from error to OkBox?
![image](https://user-images.githubusercontent.com/45708377/71962694-106f9a80-320b-11ea-8ea5-dbb7ce5b7430.png)

**Comment by olegshegai** [comment]
Fixed other crash case.
About OkBox: not sure, it's a default behaviour for error cases.

**Comment by olegshegai** [comment]
@Sekor2600 was it a missclick?
@SlayksWood can you please check if it crashes for you after the latest merge?
