### ISSUE TITLE
[0.9.0 staging-1322] Work Party: Client crash with resources adding (reputation payment)

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14297]
1. Create a party with reputation payment
2. Someone take it and try to place resources to the order,
Crash
```

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.WorkParties.ReputationPayment.PayUser(Laborer laborer, Single amount)
   at Eco.Gameplay.Economy.WorkParties.ValuePayment.WorkPerformed(Laborer laborer, Single percentPerformed)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.<>c__DisplayClass43_0.<OnWorkPerformed>b__0(Payment x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable`1 e, String sep)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.OnWorkPerformed(User user, Work work, Single percentDelta, String message)
   at Eco.Gameplay.Economy.WorkParties.CollectResourcesWork.UpdateWorkDone(User user, Type item, Int32 quantity, String message)
   at Eco.Gameplay.Utils.ItemTracker.ActionPerformed(GameAction action)
   at Eco.Gameplay.Economy.WorkParties.CollectResourcesWork.ActionPerformed(GameAction action)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.GameActions.ActionUtil.ActionPerformed(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, IEnumerable`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Items.WorkOrder.TryToContributeItemsResult(User user, ItemStack stack, Int32 maxToContribute, Boolean moveAll)
   at Eco.Gameplay.Items.WorkOrder.TryToContributeItems(Player player, ItemStack stack, Int32 maxToContribute, Boolean moveAll)</size>
```

**Comment by johnkslg** [comment]
I cant repro this:
![image](https://user-images.githubusercontent.com/3536496/71739887-8c36a500-2e0f-11ea-8586-31fbda7cf27d.png)

Can you give more specific steps? From a newly spawned world

**Comment by beastyn** [comment]
Just make a party with 10 000 reputation for payment.
https://drive.google.com/file/d/1ui_1suHQHsG--u_yFhvReMBFnXtpnR2f/view?usp=sharing

**Comment by johnkslg** [comment]
Ah the problem was happening when you switch the type of a payment.   Found and fixed, thanks
![image](https://user-images.githubusercontent.com/3536496/71917300-9c62c300-3134-11ea-90b5-97782176df13.png)
