### ISSUE TITLE
[0.9.0 staging-1326] Crash in craft submenu when try to see ingredient tooltips.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14321]
Step to reproduce:
- place anvil (for example)
- open craft iron tool submenu:
![image](https://user-images.githubusercontent.com/45708377/71877585-8b1cb500-313a-11ea-9b4e-ed85fa2fda12.png)
- try to see tooltip at any ingredients:
![image](https://user-images.githubusercontent.com/45708377/71877629-bacbbd00-313a-11ea-9cea-be8736caaa4b.png)
- crash: 
```
<size=60,00%>Exception: InvalidOperationException
Message:Cannot convert value: 4496 to type: System.Collections.Generic.List`1[[Eco.Core.Controller.IController, Eco.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
Source:Eco.Shared

System.InvalidOperationException: Cannot convert value: 4496 to type: System.Collections.Generic.List`1[[Eco.Core.Controller.IController, Eco.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
   at Eco.Shared.Serialization.BsonManipulator.FromBson(BSONValue value, Type type)
   at Eco.Shared.Networking.RPCManager.UnpackArgs(INetClient client, BSONArray bsonArray, RPCMethod method, Object target)
   at Eco.Shared.Networking.RPCManager.UnpackArgs(INetClient client, BSONArray bsonArray, RPCMethod[] methods, Object target, RPCMethod& targetMethod)</size>
```
Log file: [Rhfi.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4029404/Rhfi.txt)

**Comment by SlayksWood** [comment]
dup #14285
