### ISSUE TITLE
[Staging-1338] Can't create a world (possibly due to 16 core processor)

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14402]
See above. Error below.

```
Failed to load server, Exception was Exception: OverflowException
Message:Arithmetic operation resulted in an overflow.
Source:System.Private.CoreLib

System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.ToInt32()
   at Eco.Core.Utils.ProcessorUtils.GetAvailableProcessorCount()
   at Eco.Core.Utils.ThreadUtils.SplitWork[T](List1 work, Action1 processor)
   at Eco.Core.Serialization.SimpleSerializer.BuildSerializableTypes()
   at Eco.Core.Serialization.SimpleSerializer..ctor()
   at Eco.Core.Serialization.CurrentSerializer..ctor()
   at Eco.Core.Serialization.EcoSerializer.InitializeInternal()
   at Eco.Core.Serialization.EcoSerializer.Initialize()
   at Eco.Core.Plugins.StorageManager.Initialize()
   at Eco.Core.Plugins.StorageManager..ctor(PluginConfig`1 config, IFileStorage baseStorage, Boolean enableBackups)
```

I did successfully generate a world on my 16 Core Processor about 20 days ago, since then i didn't need to create a new one.

High Priority, due to me needing this for preparing videos.

**Comment by D3nnis3n** [comment]
Fixed.
