### ISSUE TITLE
BSON recycle errors

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#14409]
Server:

(I think this happend when the client was trying to connect with a different version and getting rejected)
```
[13:51:28.273] [2] [Error] [Eco] BSONObject wasn't fully recycled. Created from:
   at Eco.Shared.Serialization.BSONObject.get_New()
   at Eco.Shared.Serialization.SimpleBSON.DecodeDocument(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.Load(MemoryStream stream)
   at Eco.Shared.Networking.NetMessage.DecodePacket(UdpDataMessage& message)
   at Eco.Plugins.Networking.NetworkServer.HandleIncomingDataMessage(UdpDataMessage& message)
   at Eco.Networking.ENet.ENetUdpPeer.Service(Int32 timeoutMs)
   at Eco.Plugins.Networking.NetworkServer.<Initialize>b__34_3(Object cts)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

Client:
```
BSONObject wasn't fully recycled. Created from:
  at Eco.Shared.Serialization.BSONObject.get_New () [0x0000e] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeDocument (System.IO.MemoryStream stream) [0x00008] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeElement (System.IO.MemoryStream stream) [0x000a2] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeArray (System.IO.MemoryStream stream) [0x00012] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeElement (System.IO.MemoryStream stream) [0x000ae] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeDocument (System.IO.MemoryStream stream) [0x00012] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.Load (System.IO.MemoryStream stream) [0x00000] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.LoadCompressed (System.IO.Stream stream, System.Int32 bytesToDecompress) [0x00030] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeElement (System.IO.MemoryStream stream) [0x000e6] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeDocument (System.IO.MemoryStream stream) [0x00012] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeElement (System.IO.MemoryStream stream) [0x000a2] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeArray (System.IO.MemoryStream stream) [0x00012] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeElement (System.IO.MemoryStream stream) [0x000ae] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeDocument (System.IO.MemoryStream stream) [0x00012] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.Load (System.IO.MemoryStream stream) [0x00000] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.LoadCompressed (System.IO.Stream stream, System.Int32 bytesToDecompress) [0x00030] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Networking.NetMessage.DecodePacket (Eco.Shared.Networking.UdpDataMessage& message) [0x00063] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Networking.NetworkClient.HandleDataMessage (Eco.Shared.Networking.UdpDataMessage& dataMessage) [0x00002] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Networking.ENet.ENetUdpPeer.HandleEvent () [0x00000] in <a25fd7bfd53d4e7eab1f0ac1e56c6335>:0 
  at Eco.Networking.ENet.ENetUdpPeer.Service (System.Int32 timeoutMs) [0x00000] in <a25fd7bfd53d4e7eab1f0ac1e56c6335>:0 
  at Eco.Shared.Networking.NetworkClient.Service (System.Int32 timeoutMs) [0x00000] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at NetworkManager+ServiceJob.Execute () [0x0000c] in <f674c70146504bc49710e1157e523c90>:0 
  at Unity.Jobs.IJobExtensions+JobStruct`1[T].Execute (T& data, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) [0x00008] in <a278ebd44ab0472bb8e638263e06cd61>:0 

UnityEngine.Debug:LogError(Object)
UnityLogWriter:WriteError(String) (at Assets/Scripts/System/Settings.cs:16)
Eco.Shared.Utils.Log:WriteErrorLine(LocString) (at W:/StrangeLoopGames/Eco.Staging/Server/Eco.Shared/Utils/Log.cs:39)
Eco.Shared.Serialization.BSONObject:Finalize() (at W:/StrangeLoopGames/Eco.Staging/Server/Eco.Shared/Serialization/SimpleBSON.cs:800)
```

```
BSONObject wasn't fully recycled. Created from:
  at Eco.Shared.Serialization.BSONObject.get_New () [0x0000e] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeDocument (System.IO.MemoryStream stream) [0x00008] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeElement (System.IO.MemoryStream stream) [0x000a2] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeArray (System.IO.MemoryStream stream) [0x00012] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeElement (System.IO.MemoryStream stream) [0x000ae] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeDocument (System.IO.MemoryStream stream) [0x00012] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.Load (System.IO.MemoryStream stream) [0x00000] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.LoadCompressed (System.IO.Stream stream, System.Int32 bytesToDecompress) [0x00030] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Networking.NetMessage.DecodePacket (Eco.Shared.Networking.UdpDataMessage& message) [0x00063] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Networking.NetworkClient.HandleDataMessage (Eco.Shared.Networking.UdpDataMessage& dataMessage) [0x00002] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Networking.ENet.ENetUdpPeer.HandleEvent () [0x00000] in <a25fd7bfd53d4e7eab1f0ac1e56c6335>:0 
  at Eco.Networking.ENet.ENetUdpPeer.Service (System.Int32 timeoutMs) [0x00000] in <a25fd7bfd53d4e7eab1f0ac1e56c6335>:0 
  at Eco.Shared.Networking.NetworkClient.Service (System.Int32 timeoutMs) [0x00000] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at NetworkManager+ServiceJob.Execute () [0x0000c] in <f674c70146504bc49710e1157e523c90>:0 
  at Unity.Jobs.IJobExtensions+JobStruct`1[T].Execute (T& data, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) [0x00008] in <a278ebd44ab0472bb8e638263e06cd61>:0 

UnityEngine.Debug:LogError(Object)
UnityLogWriter:WriteError(String) (at Assets/Scripts/System/Settings.cs:16)
Eco.Shared.Utils.Log:WriteErrorLine(LocString) (at W:/StrangeLoopGames/Eco.Staging/Server/Eco.Shared/Utils/Log.cs:39)
Eco.Shared.Serialization.BSONObject:Finalize() (at W:/StrangeLoopGames/Eco.Staging/Server/Eco.Shared/Serialization/SimpleBSON.cs:800)
```

```
BSONObject wasn't fully recycled. Created from:
  at Eco.Shared.Serialization.BSONObject.get_New () [0x0000e] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeDocument (System.IO.MemoryStream stream) [0x00008] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.Load (System.IO.MemoryStream stream) [0x00000] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.LoadCompressed (System.IO.Stream stream, System.Int32 bytesToDecompress) [0x00030] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeElement (System.IO.MemoryStream stream) [0x000e6] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeDocument (System.IO.MemoryStream stream) [0x00012] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeElement (System.IO.MemoryStream stream) [0x000a2] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeArray (System.IO.MemoryStream stream) [0x00012] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeElement (System.IO.MemoryStream stream) [0x000ae] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.DecodeDocument (System.IO.MemoryStream stream) [0x00012] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.Load (System.IO.MemoryStream stream) [0x00000] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Serialization.SimpleBSON.LoadCompressed (System.IO.Stream stream, System.Int32 bytesToDecompress) [0x00030] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Networking.NetMessage.DecodePacket (Eco.Shared.Networking.UdpDataMessage& message) [0x00063] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Shared.Networking.NetworkClient.HandleDataMessage (Eco.Shared.Networking.UdpDataMessage& dataMessage) [0x00002] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at Eco.Networking.ENet.ENetUdpPeer.HandleEvent () [0x00000] in <a25fd7bfd53d4e7eab1f0ac1e56c6335>:0 
  at Eco.Networking.ENet.ENetUdpPeer.Service (System.Int32 timeoutMs) [0x00000] in <a25fd7bfd53d4e7eab1f0ac1e56c6335>:0 
  at Eco.Shared.Networking.NetworkClient.Service (System.Int32 timeoutMs) [0x00000] in <4546714ae7ab411f9431efaa8e82c4a2>:0 
  at NetworkManager+ServiceJob.Execute () [0x0000c] in <f674c70146504bc49710e1157e523c90>:0 
  at Unity.Jobs.IJobExtensions+JobStruct`1[T].Execute (T& data, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) [0x00008] in <a278ebd44ab0472bb8e638263e06cd61>:0 

UnityEngine.Debug:LogError(Object)
UnityLogWriter:WriteError(String) (at Assets/Scripts/System/Settings.cs:16)
Eco.Shared.Utils.Log:WriteErrorLine(LocString) (at W:/StrangeLoopGames/Eco.Staging/Server/Eco.Shared/Utils/Log.cs:39)
Eco.Shared.Serialization.BSONObject:Finalize() (at W:/StrangeLoopGames/Eco.Staging/Server/Eco.Shared/Serialization/SimpleBSON.cs:800)
```

**Comment by mirasrael** [comment]
Doesn't seems to happen now. If you still have it please re-open issue.
