### ISSUE TITLE
[0.9.0 staging-1352] Can't claim

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14452]
![image](https://user-images.githubusercontent.com/45708377/72875809-22baff80-3d06-11ea-86ac-029927494f68.png)
And Because of this, I can't place Starting Camp.

**Comment by SlayksWood** [comment]
After fixes need to check #14368, #10121.

**Comment by SlayksWood** [comment]
Server Crash:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.Deed.CanChangeOwner(Player changer, IAlias owner)
   at Eco.Gameplay.Property.Deed.TryChangeOwners(GameActionPack pack, Player changer, IAlias newOwner, Boolean transferAction, Boolean autoPerform)
   at Eco.Gameplay.GameActions.AtomicActions.ClaimProperty(GameActionPack pack, Deed deed, User actor, Inventory propertyClaimInv, Vector2i position, ClaimedOrUnclaimed actionType, Boolean isAdminCommand)
   at Eco.Gameplay.GameActions.AtomicActions.<>c__DisplayClass15_0.<ClaimNow>b__0(GameActionPack pack)
   at Eco.Gameplay.GameActions.AtomicActions.DoNow(Action`1 func)
   at Eco.Gameplay.GameActions.AtomicActions.ClaimNow(Deed deed, User actor, Inventory propertyClaimInv, Vector2i position)
   at Eco.Mods.TechTree.PropertyToolItem.DoClaim(Deed deed, User actor, Vector2i position) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\PropertyToolItem.cs:line 104
   at Eco.Mods.TechTree.PropertyToolItem.OnActRight(InteractionContext context) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\PropertyToolItem.cs:line 99
   at Eco.Gameplay.Players.Player.<>c__DisplayClass70_0.<PlayerInteractResult>b__2(IInteractable inter)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T](IEnumerable`1 enumerable, Func`2 resultFunc)
   at Eco.Gameplay.Players.Player.PlayerInteractResult(InteractionInfo info)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>
```
[crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4107038/crash.txt)

**Comment by beastyn** [comment]
also FYI
/spawn workbench 
now will spawm building with claim which is unowned. And it will crash client if you try to open workbench.

**Comment by SlayksWood** [comment]
Staging-1360: When I claim I gain Unnamed Deed without owner. And command  /owner doesn't work.
![image](https://user-images.githubusercontent.com/45708377/73153282-473b2100-40e4-11ea-8ca8-095cbc62ef3f.png)

**Comment by SlayksWood** [comment]
Also see #14499

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/5493
