### ISSUE TITLE
[0.9.0 staging-1373] Zoning office: client crash

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14542]
Hover over player on minimap
(or open map with Follow Player setting)
(or open zoning office)

```
[Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Wrong number of args passed to method: GetTooltip.
Source:Eco.Shared

System.Exception: Wrong number of args passed to method: GetTooltip.
   at Eco.Shared.Networking.RPCManager.UnpackArgs(INetClient client, BSONArray bsonArray, RPCMethod[] methods, Object target, RPCMethod& targetMethod)
   at Eco.Shared.Networking.RPCManager.TryInvoke(INetClient client, Object target, String methodname, BSONArray bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__61_2()</size>]
```

**Comment by johnkslg** [comment]
I'll take this one, is from my tooltip changes

**Comment by johnkslg** [comment]
Fixed! 
![image](https://user-images.githubusercontent.com/3536496/73406138-92069580-42aa-11ea-900a-e379a4434afb.png)
