### ISSUE TITLE
[0.9.0 staging-1387] Interacting with a Campfire causes null exception

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14649]
To replicate, interact with a campfire. The client will disconnect with a null exception.

```
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.RecipeFamily.get_Labor()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.AddPendingView(IController controller, IMvcNetClient client)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.AddPendingView(IController controller, IMvcNetClient client)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.PackageViewAndComponents(BSONObject bson, INetClient client, WorldObjectComponentClientAvailability availability)
   at Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Players.Player.<>c__DisplayClass70_0.<PlayerInteractResult>b__3(IInteractable inter)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T](IEnumerable`1 enumerable, Func`2 resultFunc)
   at Eco.Gameplay.Players.Player.PlayerInteractResult(InteractionInfo info)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
```

**Comment by mirasrael** [comment]
Fixed here https://github.com/StrangeLoopGames/Eco/pull/5578#pullrequestreview-355377341
