### ISSUE TITLE
[0.9.0 staging-1387] Server unabel to restart after Campfireproblem 

### ISSUE THREAD

**Issue by FalkosTMB** [StrangeLoopGames/EcoIssues#14651]
After Crash with campfire Server is unable to load gamesave.

[09:01:11] Loading Civics... Finished in 14,3ms
[09:01:11] Failed to load object of type 'CivicsData'. It will be ignored, but may cause inconsistency and errors in other entities: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.OnDecodeComplete(Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.CurrentSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.EcoSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream)
An element with the same key but a different value already exists. Key: basic election
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs)
   at Eco.Core.Utils.ThreadSafeDictionary`2.<>c__DisplayClass25_0.<AddRange>b__0(ImmutableDictionary`2 x)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ThreadSafeDictionary`2.AddRange(IEnumerable`1 pairs)
   at Eco.Core.Utils.ControllerDictionary`2.<>n__2(IEnumerable`1 pairs)
   at Eco.Core.Utils.ControllerDictionary`2.<>c__DisplayClass10_0.<AddRange>b__0()
   at Eco.Core.Utils.ControllerDictionary`2.ApplyChange(Action change)
   at Eco.Core.Utils.ControllerDictionary`2.AddRange(IEnumerable`1 pairs)
   at Eco.Core.Systems.Registrar.OnDeserialized()
[09:01:11] [Server Initialization]... Finished in 19.508,9ms
[09:01:11] Failed to load server, Exception was Exception: InvalidOperationException
Message:Singleton already assigned.
Source:Eco.Shared

System.InvalidOperationException: Singleton already assigned.
   at Eco.Shared.Utils.Singleton`1..ctor()
   at Eco.Gameplay.Civics.CivicsData..ctor()

**Comment by beastyn** [comment]
Thank you for the report.
Can you tell what steps were before crash with the campfire?

**Comment by beastyn** [comment]
campfire here #14705
Server launch issue here #14712
