### ISSUE TITLE
0.8.3.3 save broken after correct shutdown

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14770]
(for investigate, server owner already restored save from backup.)
correct save https://www.dropbox.com/s/3lfpt0zxkrc5xn5/HeraksW.zip?dl=1
broken save https://www.dropbox.com/s/i5f93468psno61k/HeraksNW.zip?dl=1

```
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   at Eco.Shared.Utils.MemoryStreamPool.GetStream(Byte[] buffer)
   at Eco.World.PersistentChunk.Thaw()
   at Eco.World.PersistentChunk.Access()
   at Eco.World.PersistentChunk.RemoveTransientBlocks()
   at Eco.World.PersistentChunkGrid.<>c__DisplayClass10_0.<Initialize>b__2(PersistentChunk chunk)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
 
```

**Comment by mirasrael** [comment]
Should be fixed in 9.0.
