### ISSUE TITLE
[0.9.0 staging-1418] Disconnect when checking Tags in Ecopedia

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14820]
Some tags have too many entries to be displayed in a tooltip. Some examples: Crafting Tables, Products, Ingredients. When highlighting one of these tags in the Ecopedia it causes a crash.

To replicate: 
- Open Ecopedia -> Reference -> Tags
- Highlight first entry on the list, "World Objects"

```Exception: ArgumentException
Message:Too many arguments for LocString: 443. Max: 127
Source:Eco.Shared

System.ArgumentException: Too many arguments for LocString: 443. Max: 127
   at Eco.Shared.Serialization.SimpleBSON.EncodeLocString(MemoryStream stream, LocString locString) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1433
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1340
   at Eco.Shared.Serialization.BSONObject.Encode(MemoryStream stream) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 933
   at Eco.Shared.Serialization.SimpleBSON.EncodeDocument(MemoryStream stream, BSONObject obj) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1345
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1288
   at Eco.Shared.Serialization.SimpleBSON.EncodeArray(MemoryStream stream, BSONArray array) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1351
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1291
   at Eco.Shared.Serialization.BSONObject.Encode(MemoryStream stream) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 933
   at Eco.Shared.Serialization.SimpleBSON.EncodeDocument(MemoryStream stream, BSONObject obj) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1345
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1288
   at Eco.Shared.Serialization.BSONObject.Encode(MemoryStream stream) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 933
   at Eco.Shared.Serialization.SimpleBSON.EncodeDocument(MemoryStream stream, BSONObject obj) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1345
   at Eco.Shared.Serialization.SimpleBSON.DumpTo(MemoryStream ms, BSONObject obj) in C:\Eco\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 1158
   at Eco.Plugins.Networking.NetworkServer.SendMessage(NetworkEvent netEvent, BSONObject bsonObj, Object connection) in C:\Eco\Server\Eco.Plugins\Networking\NetworkServer.cs:line 224```

**Comment by johnkslg** [comment]
Can just encode this as a string instead of a locstring.
