### ISSUE TITLE
[0.9.0 staging-1421] Server crash when try to mow with Modern Scythe.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14834]
System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Monitor.Exit(Object obj)
   at Eco.Gameplay.Items.InventoryLock.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Finalize()

**Comment by keegan-o** [comment]
happens with stone sickle as well so players will encounter this pretty quickly
