### ISSUE TITLE
[0.9.0.0 beta staging-1437] using the fishing pole going to crash the complete server.

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#14936]
**Version:** 0.9.0.0 beta staging-1437

**Steps to Reproduce:**
while using the fishing pole, quite after i hole them back, the server get crashed. 

**Expected behavior:**
![image](https://user-images.githubusercontent.com/47274045/75595216-c1681800-5a8b-11ea-9a03-7f91801d5b82.png)

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'key')
Source:System.Private.CoreLib

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Items.InventoryChangeSet.ModifyItemsInternal(Type itemType, Int32 delta, Inventory inventory)
   at Eco.Gameplay.Items.Inventory.CreateAddItemAction(Type itemType, User user)
   at Eco.Gameplay.Items.Inventory.TryAddItem(Type itemType, User user)
   at Eco.Mods.TechTree.FishingPoleItem.FinalizeCatch(Player player, INetObject target) in D:\Steamspiele\steamapps\common\Eco Server\Mods\Tools\FishingPoleItem.cs:line 34</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Comment by FalkosTMB** [comment]
--BEGIN DUMP--
Dump Time
02/29/2020 00:37:15

Exception
Exception: SynchronizationLockException
Message:Object synchronization method was called from an unsynchronized block of code.
Source:System.Private.CoreLib

System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Monitor.Exit(Object obj)
   at Eco.Gameplay.Items.InventoryLock.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Finalize()

--END DUMP--

**Comment by beastyn** [comment]
It happens with some specific fish. Its jellyfish?
Jellyfish doesn't want to be eaten.
https://drive.google.com/file/d/1sRw4Ed75n4IGkoW7GR78JiBE3_0K2HO2/view?usp=sharing

**Comment by beastyn** [comment]
@StanKryvenko @WeaselDog 
Maybe its for you?
Take a look please

**Comment by mirasrael** [comment]
I'll check this

**Comment by Quadbro** [comment]
@mirasrael  problem is herem probably
![image](https://user-images.githubusercontent.com/6802030/75653253-cac1d200-5c8f-11ea-8746-10723fc9daee.png)
