### ISSUE TITLE
[0.9.0 Staging 1446] Issue with executive Action

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#15008]
Hello,
 i have setup below executive action and I'm executor for executive Actions by constitution:
![image](https://user-images.githubusercontent.com/47274045/76023870-59ea1680-5f2a-11ea-8e12-7138c5313084.png)

then emidiatly by perform following exception pop up:
![image](https://user-images.githubusercontent.com/47274045/76023910-6f5f4080-5f2a-11ea-9bc9-92e5f6c47b4f.png)

**Comment by SlayksWood** [comment]
I can reproduce it in new world. Seems you need add some users (I add 1 Test Client).
[Executiveactioncrash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4296390/Executiveactioncrash.txt)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Eco.Gameplay.Civics.GameValues.GameValueContext`1.Value(IContextObject context)
   at Eco.Gameplay.Civics.GameValues.Values.CitizenAgeInHours.Value(IContextObject action)
   at Eco.Gameplay.Civics.SendNotice.Perform(String desc, GameAction action)
   at Eco.Gameplay.Civics.SendNotice.PerformExecutiveAction(User user, IContextObject context)
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.DoAction(User executingUser, StringBuilder sbUser, DemographicContext context, IExecutiveAction action)
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.PerformBase(User executingUser)
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.Perform(User executingUser, Election election)
   at Eco.Gameplay.Civics.CivicFuncs.TryExecuteAction(User user, CivicAction action)
   at Eco.Gameplay.Civics.CivicFuncs.FullExecuteAndGetElection(User user, CivicAction action, Boolean force)
   at Eco.Gameplay.Civics.CivicFuncs.FullExecute(User user, CivicAction action, Boolean force)
   at Eco.Gameplay.Components.PerformCivicActionComponent.<>c__DisplayClass11_0.<Select>b__0(IController obj)
   at Eco.Gameplay.Systems.ViewEditor.Apply(Player player)</size>
```
