### ISSUE TITLE
USER ISSUE: Bulletin board (9.0)

### ISSUE THREAD

**Issue by VokrugShum** [StrangeLoopGames/EcoIssues#15083]
**Version:** 0.9.0.0 beta staging-1445

**Steps to Reproduce:**
when you click on the bulletin board

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.ContractBoardComponent.<>c__DisplayClass27_0.<TryAdd>b__0(Workable x)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Economy.ContractBoardComponent.TryAdd(User user)
   at Eco.Gameplay.Economy.ContractBoardComponent.AddContract(Player player)</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Comment by VokrugShum** [comment]
Contract board

**Comment by SlayksWood** [comment]
Can't reproduce in last staging builds.
@VokrugShum 
Can you check it again after playtest update?

**Comment by SlayksWood** [comment]
Seems fixed
