### ISSUE TITLE
Dismond steam truck as passenger

### ISSUE THREAD

**Issue by Zoneman81** [StrangeLoopGames/EcoIssues#15136]
Pressed E to get out of a steam truck as a passenger and get kicked from the server

Error txt file at 27mb
Dropbox link https://www.dropbox.com/s/rqetk3dhjkra0cv/dismond_bug.txt?dl=0

**Comment by SlayksWood** [comment]
Step to reproduce:
- first player use steam truck(or truck) as Driver
- second player use steam truck as passenger.
- First player go out vehicle. Second player is still here.
- Second player go out vehicle.
- crash
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.MountComponent.<>c__DisplayClass10_0.<Dismount>b__0(Player occupant)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Eco.Gameplay.Components.MountComponent.Dismount(Int32 playerID)</size>
```
It's important that driver go out vehicle first.
