### ISSUE TITLE
[0.9.0 staging-1472] Civics: client crash with elected title

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15203]
1. Place cpitol and ratify it
2. Place Government office
3. Trey to create a title

Crash
Server encountered an exception:
```
<size=60.00%>Exception: MissingMethodException
Message:No parameterless constructor defined for type 'Eco.Gameplay.Civics.Titles.ElectedTitle'.
Source:System.Private.CoreLib

System.MissingMethodException: No parameterless constructor defined for type 'Eco.Gameplay.Civics.Titles.ElectedTitle'.
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Eco.Gameplay.Components.CivicSlot.MakeNew(User user, SimpleEntry copyFrom)
   at Eco.Gameplay.Components.CivicObjectComponent.Edit(Player player, Int32 index)</size>
```

**Comment by johnkslg** [comment]
doh, slipping an easy fix into staging for this.
