### ISSUE TITLE
[0.9.0 staging-1488] Crash for investigation

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15378]
1. It happened when I press Draft Law button:
```
erver encountered an exception:

<size=60.00%>Exception: KeyNotFoundException
Message:The given key was not present in the dictionary.
Source:System.Collections.Immutable

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Core.Controller.ControllerManager.GetControllerInstanceInfo(IController controller)
   at Eco.Core.Controller.ControllerExtensions.SubscribeAllRecursive(ISubscriptions subs, IController controller, Action`2 changedCallback, Func`2 filter)
   at Eco.Core.Controller.ControllerExtensions.SubscribeAllRecursive(ISubscriptions subs, IController controller, Action`2 changedCallback, Func`2 filter)
   at Eco.Core.Controller.ControllerExtensions.SubscribeAllRecursive(ISubscriptions subs, IController controller, Action`2 changedCallback, Func`2 filter)
   at Eco.Gameplay.Systems.ViewEditor.UpdateValidity(PropertyInfo prop, Object objParent)
   at Eco.Gameplay.Systems.ViewEditor.<Setup>b__32_0()
   at Eco.Shared.View.SubscriptionsExtensions.SubscribeAndCall(ISubscriptions ss, IObservable s, String propname, Action changedCallback)
   at Eco.Gameplay.Systems.ViewEditor.Setup(User user, ISaveablePlugin toSave, String buttonText, String overrideTitle)
   at Eco.Gameplay.Systems.ViewEditor..ctor(User user, IController toEdit, ISaveablePlugin toSave, String buttonText, String overrideTitle, Type restrictToType, Boolean readOnly)
   at Eco.Gameplay.Systems.ViewEditor.Edit(User user, IController controller, ISaveablePlugin toSave, Action`1 onSubmit, String buttonText, String overrideTitle, String uiStyle, Type restrictToType, Boolean readOnly)
   at Eco.Gameplay.Components.CivicObjectComponent.Edit(Player player, Int32 index)</size>
```
[Crash start to draft Law.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4394606/Crash.start.to.draft.Law.txt)

2. It happened when I placed Capitol (after reconnect after crash capitol was placed and working good.)
```
Server encountered an exception:

<size=60,00%>Exception: ArgumentException
Message:An element with the same key but a different value already exists. Key: 7186
Source:System.Collections.Immutable

System.ArgumentException: An element with the same key but a different value already exists. Key: 7186
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, IMvcNetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.AddPendingView(IController controller, IMvcNetClient client)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.AddPendingView(IController controller, IMvcNetClient client)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient boundClient)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client, Boolean doAllParams)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(IDictionary dictionary, INetClient client, Boolean useReflection)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.GetChanges(IMvcNetClient client)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__61_0()</size>
```
[Crash place capitol.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4394605/Crash.place.capitol.txt)

**Comment by johnkslg** [comment]
Could not repro these after lots of testing. Can you try again in latest staging and get exact steps if it still happens?

**Comment by SlayksWood** [comment]
@johnkslg 
Create new world
I am checking PR, place some items, use /give command, nothing special
![image](https://user-images.githubusercontent.com/45708377/78765476-b78dda80-7990-11ea-99cc-097d2fca7ff1.png)

Then I need to create 3 Laws to check this issue #13616. 
Use /bt 2,20,7,20,1,1 to create build for capitol and court
place capitol, ratify, /civics win election
place court, open UI, press Draft Law- Crash:
```
System.ArgumentException: An element with the same key but a different value already exists. Key: 9954
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, IMvcNetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient boundClient)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client, Boolean doAllParams)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(IDictionary dictionary, INetClient client, Boolean useReflection)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.GetChanges(IMvcNetClient client)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__61_0()</size>
```
[Crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4449423/Crash.txt)

**Comment by SlayksWood** [comment]
when place first capitol
```
System.Collections.Generic.KeyNotFoundException The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Core.Controller.ControllerManager.GetControllerInstanceInfo(IController controller)
   at Eco.Core.Controller.ControllerExtensions.SubscribeAllRecursive(ISubscriptions subs, IController controller, Action`2 changedCallback, Func`2 filter)
   at Eco.Gameplay.Civics.Constitution.Initializeg__ArticleListChanged18_1(INetObject player, CivicArticle article)
   at Eco.Core.Utils.ClientControllerExtensions.c__DisplayClass0_0`1.OnCurrentAndFutureEntriesb__0(INetObject u, Object x)
   at Eco.Gameplay.Civics.Constitution.AddBasicArticle(CivicCondition condition, String name, ElectionProcess defaultProcess)
   at Eco.Gameplay.Civics.Constitution.InitDefaultConstitution(ElectionProcess defaultProcess)
   at Eco.Gameplay.Components.ConstitutionComponent.InitializePersistentData()
   at Eco.Gameplay.Objects.TrackPlacementComponent.Initialize()
   at Eco.Gameplay.Components.ConstitutionComponent.Initialize()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.Add(WorldObject worldObject, User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.ForceAdd(Type worldObjectType, User creator, Vector3 position, Quaternion rotation, Boolean validatePlacement, WorldObjectItem item)
   at Eco.Gameplay.Objects.WorldObjectManager.TryPlaceWorldObject(Player player, WorldObjectItem item, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.c__DisplayClass25_1.OnActRightb__1()
   at Eco.Gameplay.Items.WorldObjectItem.c__DisplayClass25_0.OnActRightb__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client..ctorb__64_2()size
```
[Crash when place Capitol.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4538806/Crash.when.place.Capitol.txt)

**Comment by SlayksWood** [comment]
staging-1554 still an issue
> Click revise law, got disconnected with exception:
> ![image](https://user-images.githubusercontent.com/982322/82432855-eb304a00-9a90-11ea-8fbe-5e8bdfc0fac4.png)
> 
> Worked the second time.

**Comment by SlayksWood** [comment]
> Was doing things in law UI in solo.
> 
> ```
> Server encountered an exception:
> 
> <size=60,00%>Exception: KeyNotFoundException
> Message:The given key was not present in the dictionary.
> Source:System.Collections.Immutable
> 
> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
>    at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
>    at Eco.Core.Controller.ControllerManager.GetControllerInstanceInfo(IController controller)
>    at Eco.Core.Controller.ControllerExtensions.SubscribeAllRecursive(ISubscriptions subs, IController controller, Action`2 changedCallback, Func`2 filter)
>    at Eco.Core.Controller.ControllerExtensions.SubscribeAllRecursive(ISubscriptions subs, IController controller, Action`2 changedCallback, Func`2 filter)
>    at Eco.Gameplay.Systems.ViewEditor.UpdateValidity(PropertyInfo prop, Object objParent)
>    at Eco.Gameplay.Systems.ViewEditor.<Setup>b__32_0()
>    at Eco.Shared.View.SubscriptionsExtensions.SubscribeAndCall(ISubscriptions ss, IObservable s, String propname, Action changedCallback, Action unsubscribeCallback)
>    at Eco.Gameplay.Systems.ViewEditor.Setup(User user, ISaveablePlugin toSave, String buttonText, String overrideTitle)
>    at Eco.Gameplay.Systems.ViewEditor..ctor(User user, IController toEdit, ISaveablePlugin toSave, String buttonText, String overrideTitle, Type restrictToType, Boolean readOnly)
>    at Eco.Gameplay.Systems.ViewEditor.Edit(User user, IController controller, ISaveablePlugin toSave, Action`1 onSubmit, String buttonText, String overrideTitle, String uiStyle, Type restrictToType, Boolean readOnly)
>    at Eco.Gameplay.Components.CivicObjectComponent.Edit(Player player, Int32 index)</size>
> ```
> 
> [log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4950662/log.txt)

**Comment by beastyn** [comment]
Did  not any of this Lately. @SlayksWood close maybe?

**Comment by SlayksWood** [comment]
> press revise district:
```
System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Eco.Core.Utils.StringUtils.SplitIntoNameAndNumber(String str)
   at Eco.Core.Utils.StringUtils.UniqueKey(IDictionary existing, String root)
   at Eco.Core.Systems.Registrar.ValidateAndStoreName(IHasID obj)
   at Eco.Core.Systems.Registrar.Insert(IHasID newObj, INetObject netObj)
   at Eco.Gameplay.Components.CivicSlot.MakeNew(User user, SimpleEntry copyFrom)
   at Eco.Gameplay.Components.CivicObjectComponent.Edit(Player player, Int32 index)</size>
```
