### ISSUE TITLE
[0.9.0 staging-1496] Crash with mow Contract

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15505]
Step to reproduce:
- first player creates contract to harvest switchgrass
- second player take it and use scythe or sickle(I used modern scythe) start to mow. On second swing I have crash.
[CrashWithMowContract.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4419573/CrashWithMowContract.txt)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClauseMowLawn.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.Economy.Contracts.Contract.<>c__DisplayClass77_0.<ShouldOverrideAuth>b__0(ContractClause x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Economy.Contracts.Contract.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.Economy.Contracts.ContractManager.<>c__DisplayClass28_0.<ShouldOverrideAuth>b__1(Contract contract)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Economy.Contracts.ContractManager.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.GameActions.ActionUtil.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.Players.Player.QueryAuth(Guid authId)</size>
```

**Comment by SlayksWood** [comment]
After this crash I can't connect to server
