### ISSUE TITLE
Connection Failed: Server encountered an exception (client on same machine as server)

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#15545]
Version: 0.8.3.3 
OS: Windows 10 Pro 64-bit
RAM: 64 GB
Graphics Card: Nvidia 980 Ti (water cooled and overclocked)
CPU: i7 3.3 Ghz Intel i7 (water cooled, but not currently overclocked)
Server Size: 16 square kilometers; 400x400
World Height: 130
Sea level: 40

So.... I suddenly can't connect to my own server. That I am hosting on the same computer as the game client. With active users. I signed out so that I can see if an edit to server description posted right away, and it did, but couldn't sign back in. 

I closed the game client, reopened it, etc.I tried clicking continue, and I tried selecting from the server list. 

I really hated rebooting the server while there were active connections, but there doesn't appear to be any way to - from the server console - warn people of a pending reboot of the server (would be great if that was possible!) so I had to abruptly do backup now and shut the server down.

On startup, I could see that 1 user already logged back in, but I could not. I got the same error again.

This issue is EXACTLY the same as this fixed one:
https://github.com/StrangeLoopGames/EcoIssues/issues/12418

So it appears to have cropped up again.

```
`<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
Source:Eco.Gameplay

System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.AddItem(Type itemType, User user)
   at Eco.Gameplay.Players.User.FirstLogin()
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)</size>

Log File:
Initialize engine version: 2019.2.17f1 (8e603399ca02)
[XR] Discovering subsystems at path C:/EcoPC_v0.8.3.3-beta/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 980 Ti (ID=0x17c8)
    Vendor:   
    VRAM:     6097 MB
    Driver:   26.21.14.3064
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.514794 ms
Logging in as slg157 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU4NTk5MDczOSwidnhhIjoibG9naW4iLCJ2eGkiOjEwNDkwMzgsImYiOiJzaXA6LnN0cmFuZ2Vsb29wZ2FtZXMtZWNvLnNsZzE1Ny5AbXQxcC52aXZveC5jb20ifQ.TDM3-o-pASWQpMwNQlW8v7_S2cuGSp_Ya7_W5uSrbO0
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
UnityEngine.ReapplyDrivenProperties:Invoke(RectTransform)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
RunLoop:Invoke(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

IndexOutOfRangeException: Index was outside the bounds of the array.
  at TimeSelectorUI.Refresh () [0x00000] in <00000000000000000000000000000000>:0 
  at TimeSelectorUI.Init () [0x00000] in <00000000000000000000000000000000>:0 
  at TimeSelectorUI.Refresh () [0x00000] in <00000000000000000000000000000000>:0 
  at SelectedServerUI.SetSelected (ServerListing serverInfo) [0x00000] in <00000000000000000000000000000000>:0 
  at ServerListingUI.OnToggleServer (System.Boolean isOn) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityAction`1[T0].Invoke (T0 arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.Toggle.Set (System.Boolean value, System.Boolean sendCallback) [0x00000] in <00000000000000000000000000000000>:0 
  at System.EventHandler`1[TEventArgs].Invoke (System.Object sender, TEventArgs e) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ReleaseMouse (UnityEngine.EventSystems.PointerEventData pointerEvent, UnityEngine.GameObject currentOverGo) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (UnityEngine.EventSystems.PointerInputModule+MouseButtonEventData data) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32 id) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.Process () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.EventSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: currently not available on il2cpp Line: -1)

Connecting to 192.168.1.157:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
Steamworks.PlayersRefreshComplete:Invoke()
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.PlayersRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
Source:Eco.Gameplay

System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.AddItem(Type itemType, User user)
   at Eco.Gameplay.Players.User.FirstLogin()
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)</size>
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
Steamworks.PlayersRefreshComplete:Invoke()
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.PlayersRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)

Unloading 22621 unused Assets to reduce memory usage. Loaded Objects now: 89574.
Total: 203.522193 ms (FindLiveObjects: 5.762337 ms CreateObjectMapping: 10.041112 ms MarkObjects: 152.881277 ms  DeleteObjects: 34.836847 ms)

```

**Comment by Elliander** [comment]
Another user was able to sign into my server while I've been trying, but I can't. What kind of bug would keep the server host from signing in, but not anyone else?

**Comment by Elliander** [comment]
I borrowed a friend's laptop who never played Eco before, downloaded EcoPC 0.8.3.3 client, logged into it successfully, was able to see the server, but the join button is grayed out so I can't even login from another machine apparently. If it worked, I'd have created a new Virtual Machine on my desktop just to be able to login, but apparently I can't connect to my server from any computer. 

Since the server was rebooted, it couldn't be that it thinks I am connected. What could cause this?

**Comment by Elliander** [comment]
I read up on various forum posts about this going back a few years. Most said to change configuration options that no longer exist such as "Require Authentication" and "Detect NAT".. I tried downloading the client again (just in case something went bad client side) and I logged out and logged back in. 

Unlike the other issue I was having with 8.3.3 just yesterday, this one I can't just downgrade the server because the server is already up and running with people playing on it. I did try loading up 8.2.9 client, but it got the same error. Not sure if it should otherwise be able to connect to the 8.3.3 server though.

I don't know if it's relevant, but when I click "Your Worlds" I see under LAN the server shows the correct details, but says it's Offline which is incorrect. 

I also waited under players were offline, changed the server to paused, and tried logging in. I got the error, and the server didn't unpause indicating that it doesn't even try to get in. I'm going to try another full computer reboot now while no one is playing.

and no, I don't have a firewall enabled.

**Comment by Elliander** [comment]
I'm still having the problem, but I think I figured out what's going on. 

OK, so after another reboot didn't fix it, I got to thinking that maybe the problem is specific to my user account on the server, given that the error includes information about player inventory. 

"Requested Operation would result in an invalid inventory state: Not enough room in inventory"

Since I left the game running all night to test for stability I didn't have any backups with my inventory any different, but I always backup all the server files incrementally, and I had one from after it was initialized, but before any user joined. I was able to login to it no problem.

Closing that server, and launching the current one, I got the error again.

So my supposition is this: **something is being done with the player inventory when the player is logging in that makes the game think that the items the player is holding cannot be held.** Maybe an error calculating max weight? I'm not sure, but I'm almost positive that's where the problem is.

Until that is fixed I don't think I can play in my own server at all. Not without creating a new account, making that account the admin, and using admin commands to take control of my account's land, but even then I wouldn't feel safe logging out with anything held in my inventory.

**Comment by Elliander** [comment]
Trying to edit, replace, or even delete.eco > Users > _slg157 (my user profile) doesn't make any difference. I expected that if I alter the region of hex concerned with inventory it would let me in, but doesn't, so I restored from backup and will just have to wait for you guys to fix this horrible game breaking bug.

It's either that, or start the server over, but even if I did that I have no way of knowing if it will happen again.

**Comment by mirasrael** [comment]
@Elliander can you attach your save file? (only Game.eco)

**Comment by mirasrael** [comment]
Also you can try to open Game.eco (as zip file) and remove your user file from Users directory.

**Comment by Elliander** [comment]
I can't upload a large file without causing lag to those on the server. Someone else on the server encountered this bug as well, and it was suggested to delete "strange loop games" from user folder/app data/local and after doing that they were able to log back in, so will try that first and if it doesn't will find a time to upload that doesn't cause problems for others.

Unless you need the file to investigate?

**Comment by Elliander** [comment]
Unfortunately, deleting that folder wasn't a solution. It took me a few days to figure this out because when I would click browse all and search for the server the join button was greyed out for any logged in user, so I restored the folder and was able to continue as the second account.

I tried again today. This time I logged in from a second computer, and once again faced the greyed out join button, so instead of browse all I adjusted the filters on the recommended list and was able to join from here.

Doing so resulted in the same bug, but on a different computer. Here's the below is the relevant text. I'll find a time sometime today to upload the game.eco file and will add a link to it from google drive.

I am not sure if it is relevant, but I was logged in for more than 8 hours without interacting with anything before logging out when the problem occurred. Items in inventory weren't maxed out, and I don't think I was holding any large items. 

```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
Source:Eco.Gameplay

System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.AddItem(Type itemType, User user)
   at Eco.Gameplay.Players.User.FirstLogin()
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)</size>

Log File:
Initialize engine version: 2019.2.17f1 (8e603399ca02)
[XR] Discovering subsystems at path C:/EcoPC_v0.8.3.3-beta/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Intel(R) UHD Graphics 620 (ID=0x5917)
    Vendor:   
    VRAM:     4038 MB
    Driver:   23.20.16.4877
<RI> Initializing input.

XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 4.552988 ms
MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 280)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 280)

Logging in as slg157 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU4NjUxOTQ2OCwidnhhIjoibG9naW4iLCJ2eGkiOjEyNTE2NDcsImYiOiJzaXA6LnN0cmFuZ2Vsb29wZ2FtZXMtZWNvLnNsZzE1Ny5AbXQxcC52aXZveC5jb20ifQ.vZhNTM6NU3ruEN1H4GoHadT3kDQlf1XCAjzc9qWOOG8
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
UnityEngine.ReapplyDrivenProperties:Invoke(RectTransform)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
RunLoop:Invoke(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

IndexOutOfRangeException: Index was outside the bounds of the array.
  at TimeSelectorUI.Refresh () [0x00000] in <00000000000000000000000000000000>:0 
  at TimeSelectorUI.Init () [0x00000] in <00000000000000000000000000000000>:0 
  at TimeSelectorUI.Refresh () [0x00000] in <00000000000000000000000000000000>:0 
  at SelectedServerUI.SetSelected (ServerListing serverInfo) [0x00000] in <00000000000000000000000000000000>:0 
  at ServerListingUI.OnToggleServer (System.Boolean isOn) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityAction`1[T0].Invoke (T0 arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.Toggle.Set (System.Boolean value, System.Boolean sendCallback) [0x00000] in <00000000000000000000000000000000>:0 
  at System.EventHandler`1[TEventArgs].Invoke (System.Object sender, TEventArgs e) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ReleaseMouse (UnityEngine.EventSystems.PointerEventData pointerEvent, UnityEngine.GameObject currentOverGo) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (UnityEngine.EventSystems.PointerInputModule+MouseButtonEventData data) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32 id) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.Process () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.EventSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: currently not available on il2cpp Line: -1)

IndexOutOfRangeException: Index was outside the bounds of the array.
  at TimeSelectorUI.Refresh () [0x00000] in <00000000000000000000000000000000>:0 
  at SelectedServerUI.SetSelected (ServerListing serverInfo) [0x00000] in <00000000000000000000000000000000>:0 
  at ServerListingUI.OnToggleServer (System.Boolean isOn) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityAction`1[T0].Invoke (T0 arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.Toggle.Set (System.Boolean value, System.Boolean sendCallback) [0x00000] in <00000000000000000000000000000000>:0 
  at System.EventHandler`1[TEventArgs].Invoke (System.Object sender, TEventArgs e) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ReleaseMouse (UnityEngine.EventSystems.PointerEventData pointerEvent, UnityEngine.GameObject currentOverGo) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (UnityEngine.EventSystems.PointerInputModule+MouseButtonEventData data) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32 id) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.Process () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.EventSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: currently not available on il2cpp Line: -1)

IndexOutOfRangeException: Index was outside the bounds of the array.
  at TimeSelectorUI.Refresh () [0x00000] in <00000000000000000000000000000000>:0 
  at TimeSelectorUI.Init () [0x00000] in <00000000000000000000000000000000>:0 
  at TimeSelectorUI.Refresh () [0x00000] in <00000000000000000000000000000000>:0 
  at SelectedServerUI.SetSelected (ServerListing serverInfo) [0x00000] in <00000000000000000000000000000000>:0 
  at ServerListingUI.OnToggleServer (System.Boolean isOn) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityAction`1[T0].Invoke (T0 arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityEvent.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at System.EventHandler`1[TEventArgs].Invoke (System.Object sender, TEventArgs e) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ReleaseMouse (UnityEngine.EventSystems.PointerEventData pointerEvent, UnityEngine.GameObject currentOverGo) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (UnityEngine.EventSystems.PointerInputModule+MouseButtonEventData data) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32 id) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.Process () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.EventSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: currently not available on il2cpp Line: -1)

Connecting to 192.168.1.157:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
Steamworks.PlayersRefreshComplete:Invoke()
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.PlayersRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
Source:Eco.Gameplay

System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.AddItem(Type itemType, User user)
   at Eco.Gameplay.Players.User.FirstLogin()
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)</size>
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
Steamworks.PlayersRefreshComplete:Invoke()
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.PlayersRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)

Unloading 22622 unused Assets to reduce memory usage. Loaded Objects now: 91326.
Total: 421.152656 ms (FindLiveObjects: 11.895240 ms CreateObjectMapping: 13.894915 ms MarkObjects: 308.407477 ms  DeleteObjects: 86.953996 ms)



```

**Comment by Elliander** [comment]
OK, here is the Game.eco file that is having this issue:

https://drive.google.com/open?id=1VGE5XmaQPxvB3Tbcqw_hoav3NLPO-T8b

Username that can't login: "Elliander" 

While checking it out, a few other things to note: A forest grew around spawn that causes my client to crash every few minutes while present in that area, but only in that area. My guess it's the number and the size of the trees, but I am not otherwise sure what is causing it. No crashes outside of that area and not sure how to phrase that one as a bug report so just mentioning it for now.

Also: There is a Contract Board near "stonefall" that has a bug about it. If a player falls behind it they cannot escape, even with the use of /unstuck unless the player owning it removes the blocks. I'll post a separate bug report on that.

**Comment by mirasrael** [comment]
@Elliander sorry for very long no response for this issue. I investigated the issue and actually can fix the save, but guess it isn't actual anymore.
There two potential root causes of the issue:
- You logged into a paused world first time (with WorldTime == 0), so your user was marked with login time == 0 which is same as not logged user, so it thought you logged first time;
- You had a server crash/restart during login which prevented your user data to be persisted on the disk and so user hanged in invalid state.

**Comment by mirasrael** [comment]
I fixed first case (it will now start with negative login time and so even if world time is zero it will still correctly be counted as logged in) and also now reward items will go to Void Storage preventing login issues due to out of space inventory (it was also a bit disadvantaging to players with reward to start with lower free space in inventory).
