### ISSUE TITLE
[0.9.0.0 beta staging-1506] Trigger "Open Action" Location not working

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#15696]
Hello,
 in tooltip it is mentioned the trigger for "open Action" provides besides the civic as well the time and the location the trigger was done. As long there is no "if" condition to check where the trigger happened, the "then" is been executed well. As soon i would like to check whether the "open Action" has been done on players owned property, the whole trigger is not working. It is the same with "Property Requirements", "on owned land" as well on "on unowned land".

![image](https://user-images.githubusercontent.com/47274045/79017910-c502ba80-7b72-11ea-8134-1839e3b0ed88.png)

It would be great to fix it, as this might be the only way to prefent players sharing access to his own property with other users. For comercial concept servers the possibility to give other players access to his stuff is worst, as comunistic playing is destroying comercial playing.
A law with If you open an UI which is not an store, and you are not on your own property, then prevent. Assuming owned property is now with 9.0 realy the owner of the property and not like in 8.0 anyone who has access on property level. If not yet, to fix this would be great as well.

**Comment by johnkslg** [comment]
Good catch, the location was not being attached to the event. It is now!

**Comment by beastyn** [comment]
now law from the example above will cause a crash
```<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.Values.PropertyRequirements.CheckLocation(Vector3i pos, IContextObject action)
   at Eco.Gameplay.Civics.GameValues.Values.LocationTest.Value(IContextObject action)
   at Eco.Gameplay.Civics.GameValues.SetOfConditions.Value(IContextObject action)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.Law.Perform(GameAction action)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameAction action, Boolean notify)
   at Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Players.Player.<>c__DisplayClass75_0.<PlayerInteractResult>b__3(IInteractable inter)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T](IEnumerable`1 enumerable, Func`2 resultFunc)
   at Eco.Gameplay.Players.Player.PlayerInteractResult(InteractionInfo info)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>
```

**Comment by johnkslg** [comment]
Fixed!

**Comment by Alteraner** [comment]
Sorry, still an exception is been encountered. When open action on unclaimed property.

![image](https://user-images.githubusercontent.com/47274045/79558773-04fefb80-80a5-11ea-9d19-7a2949e0c18f.png)
