### ISSUE TITLE
Server crash in garbage

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15810]
Stresstest was down, this was last thing in log:

System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Items.DecayingInventory.get_AverageDecay()
   at Eco.Gameplay.Items.DecayingInventory.get_ClosestPercent()
   at Eco.Gameplay.Items.DecayingInventory.NextUpdateWorldTime()
   at Eco.Gameplay.Items.DecayingInventory.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Gameplay.Garbage.GarbageManager.Tick()
   at Eco.Gameplay.Garbage.GarbagePlugin.Tick()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[12:17:51.647] [6] [ Info] [Eco] Saving...  
[12:17:53.746] [59] [Error] [Eco] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Items.DecayingInventory.get_AverageDecay()
   at Eco.Gameplay.Items.DecayingInventory.get_ClosestPercent()
   at Eco.Gameplay.Items.DecayingInventory.NextUpdateWorldTime()
   at Eco.Gameplay.Items.DecayingInventory.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Gameplay.Garbage.GarbageManager.Tick()
   at Eco.Gameplay.Garbage.GarbagePlugin.Tick()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Garbage.GarbagePlugin.Shutdown()
   at Eco.Server.PluginManager.<>c.<Shutdown>b__36_0(PluginRegistration reg)

**Comment by SlayksWood** [comment]
fixed here #17234
