### ISSUE TITLE
Client exception when inventory Full and you read a SKillBook

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1583]

**Comment by metachronism** [comment]
This appears to be the relevant stack dump

--BEGIN DUMP--
Dump Time
06/04/2017 12:00:11

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC UseStack on LimitedInventory!

Could not apply inventory changes! Inventory is full.


Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Items.SkillBook.OnUsed(Player player)
   at Eco.Gameplay.Items.InventoryBase.UseStack(ItemCollection stack, Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer(Int64 maxMilliseconds)
   at Eco.Shared.Networking.NetPort.Update(Int64 maxMilliseconds)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_0()

--END DUMP--
