### ISSUE TITLE
Caught exception invoking RPC TryToCollectItems on WorkOrder!

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1587]
Seeing this exception a few times on SLG server.

--BEGIN DUMP--
Dump Time
06/05/2017 04:42:13

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC TryToCollectItems on WorkOrder!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.AddItem(InventoryBase inventory, Item item, ItemCollection stack, ChangedInventories originalState, ChangedStack& changedStack)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItems(InventoryBase inventory, IEnumerable`1 items, ItemCollection stack)
   at Eco.Gameplay.Items.WorkOrder.TryToGiveItems(InventoryBase destInventory, Boolean sendError)
   at Eco.Gameplay.Items.WorkOrder.TryToCollectItems(Player collector)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer(Int64 maxMilliseconds)
   at Eco.Shared.Networking.NetPort.Update(Int64 maxMilliseconds)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_0()

--END DUMP--

**Comment by MarjieAVolk** [comment]
Oh, I've already fixed this one.  Seems to have been another latent corner case bug, in inventories, just added a null check
