### ISSUE TITLE
[0.9.0 staging-1519] Civics: crash with timer trigger

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15891]
Start to create a law like this
![bandicam 2020-04-20 16-29-34-179](https://user-images.githubusercontent.com/27898520/79747300-d8f1ad80-8324-11ea-83c4-22d07479aa3e.jpg)

Try to pick Citizen in "Repeat for each user"

Have a client crash

```
<size=60.00%>Exception: ArgumentException
Message:Object of type 'Eco.Gameplay.Civics.GameValues.GameValueTypeContext' cannot be converted to type 'Eco.Gameplay.Aliases.IAlias'.
Source:System.Private.CoreLib

System.ArgumentException: Object of type 'Eco.Gameplay.Civics.GameValues.GameValueTypeContext' cannot be converted to type 'Eco.Gameplay.Aliases.IAlias'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Shared.Networking.RPCManager.TryInvoke(INetClient client, Object target, String methodname, BSONArray bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname)</size>
```

**Comment by johnkslg** [comment]
Fixed, that 'citizen' is no longer available on the trigger.
Also made timers state their next time in the tooltip:
![image](https://user-images.githubusercontent.com/3536496/80032711-6ad1f580-84a0-11ea-847f-34e130abf767.png)

And made them update trigger time when law is updated too.
