### ISSUE TITLE
[0.9.0 staging-1521] Wrong icons in Filter

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15946]
Research Papers:
![image](https://user-images.githubusercontent.com/45708377/79954893-b081c480-8486-11ea-92bb-4b123bb8c5ac.png)
Pipes:
![image](https://user-images.githubusercontent.com/45708377/79954962-c8f1df00-8486-11ea-94d1-6e7edd734aec.png)
and etc.

**Comment by SlayksWood** [comment]
It still has a bad shadow in Filter:
![image](https://user-images.githubusercontent.com/45708377/80101049-878e2c00-8579-11ea-96a6-d0b758c974ce.png)
For example in backpack:
![image](https://user-images.githubusercontent.com/45708377/80100957-64fc1300-8579-11ea-93d7-bc01bd5f804f.png)

**Comment by SlayksWood** [comment]
"Construction Post", "Steel Road tool", "Torch" icons are grey:
![image](https://user-images.githubusercontent.com/45708377/82289864-5a813d80-99ae-11ea-8c91-5db6f66eebfb.png)
One object is missing (between Iron Piston and Jaguar Carcass):
![image](https://user-images.githubusercontent.com/45708377/82290174-f448ea80-99ae-11ea-9527-1a3ee837253c.png)

**Comment by SlayksWood** [comment]
Still an issue.

**Comment by SlayksWood** [comment]
If you add this unknown item to list then it will be crash:
![image](https://user-images.githubusercontent.com/45708377/85264900-1801c380-b47a-11ea-8a85-b20ec391b25a.png)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.StoreComponent.<>c.<SetTrades>b__30_8(TradeOffer x)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Linq.Enumerable.ConcatIterator`1.ToList()
   at Eco.Shared.Utils.EnumerableExtensions.AsList[T](IEnumerable`1 this)
   at Eco.Core.Utils.ControllerList`1.Set(IEnumerable`1 entries)
   at Eco.Gameplay.Components.StoreComponent.SetTrades(Boolean buying, List`1 itemIDs)</size>
```

**Comment by SlayksWood** [comment]
Create separate issue for this item, so you need to fix 3 icons here:

> "Construction Post", "Steel Road tool", "Torch" icons are grey:
> ![image](https://user-images.githubusercontent.com/45708377/82289864-5a813d80-99ae-11ea-8c91-5db6f66eebfb.png)
Unknown item in filter list
