### ISSUE TITLE
Self-Corruptions

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15997]
I'm getting so many support requests for cases where the mods folder without any interaction of the user is breaking. They didn't install mods, didn't change files, still there are mods errors. They just need to reinstall the game and it works again.

I would like if some dev at some time could try to investigate why these random corruptions in mod-folder files happen - only on Steam client. It's probably one of the most issues on our social media, forums and on tickets. I can't believe they are all lying to me and were installing mods.

It's mostly issues like this (that one actually severy time in exact, sometimes other issues):

> [12:13:01.477] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
> [12:13:01.492] [1] [ Info] [Eco] Eco Server 0.8.3.3 beta
>  
> [12:13:01.571] [1] [ Info] [Eco] Server Initialization...  
> [12:13:01.571] [1] [ Info] [Eco] Starting LocalizationPlugin...  
> [12:13:01.821] [1] [ Info] [Eco] Starting ModKitPlugin...  
> [12:13:01.821] [1] [ Info] [Eco] Loading mods...  
> [12:13:01.880] [1] [ Info] [Eco] Compiling mods...  
> [12:13:03.282] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
>  
> [12:13:03.282] [1] [ Info] [Eco] Loading mods finished in 1,470.5ms
>  
> [12:13:03.294] [1] [ Info] [Eco] Starting NetworkManager...  
> [12:13:03.294] [8] [ Info] [Eco] Initializing Simulation Types...  
> [12:13:03.335] [11] [ Info] [Eco] Starting BackupPlugin...  
> [12:13:03.335] [11] [ Info] [Eco] Starting StorageManager...  
> [12:13:03.345] [6] [ Info] [Eco] Starting WorldGeneratorPlugin...  
> [12:13:03.345] [10] [ Info] [Eco] Starting GameplayStatsPlugin...  
> [12:13:04.403] [11] [ Info] [Eco] Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.FertilizerItem`1' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.FertilizerItem`1' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.FertilizerItem`1' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.FertilizerItem`1' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.FertilizerItem`1' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.FertilizerItem`1' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.FertilizerItem`1' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.FertilizerItem`1' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.FertilizerItem`1' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.FertilizerItem`1' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.AxeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.EckoTheDolphinItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.PickaxeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.RoadToolItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.ScytheItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.ShovelItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.TorchItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.AmanitaMushroomSporesItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.BeansItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.BeetSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.BirchSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.BullrushSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.BunchgrassSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.CamasBulbItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.CedarSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.CornSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.CreosoteBushSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.CriminiMushroomSporesItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.FernSporeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.FireweedSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.GrassSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.HuckleberrySeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.KelpSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.PricklyPearSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.RiceItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.SagebrushSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.SugarcaneItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.TomatoSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.WaterweedSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SpeciesName' in type 'Eco.Mods.TechTree.WheatSeedItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.AxeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HammerItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HammerItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HoeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HoeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.PickaxeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.ScytheItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.ShovelItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.AxeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HammerItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HoeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.PickaxeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.ScytheItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.ShovelItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.AxeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HammerItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HoeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.PickaxeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.ScytheItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.ShovelItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.AxeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HammerItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.PickaxeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.ScytheItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HoeItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.ShovelItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Could not load type 'Eco.Gameplay.Objects.IVariableAirtight' from assembly 'Eco.Gameplay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
> 
> Method 'OnPipeExit' in type 'Eco.Mods.TechTree.DirtItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'OnPipeExit' in type 'Eco.Mods.TechTree.WaterItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'OnPipeExit' in type 'Eco.Mods.TechTree.SewageItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Could not load type 'Eco.Gameplay.Objects.IVariableAirtight' from assembly 'Eco.Gameplay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
> 
> Method 'OnChanged' in type 'TreeEntity' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'BowItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'DevFloodToolItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HammerItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.FishingPoleItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'HydrometerItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Method 'get_SkilledRepairCost' in type 'Eco.Mods.TechTree.SoilSamplerItem' from assembly 'Eco.Mods, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
>  
> [12:13:04.403] [11] [ Info] [Eco] Starting PausePlugin...  
> [12:13:04.403] [1] [ Info] [Eco] Server Initialization finished in 2,836.7ms
>  
> [12:13:04.403] [1] [ Info] [Eco] Failed to load server, Exception was Exception: ReflectionTypeLoadException
> Message:Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
> Source:mscorlib
> 
> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
>    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    at System.Reflection.RuntimeModule.GetTypes()
>    at System.Reflection.Assembly.GetTypes()
>    at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass1_0`1.<InstancesOfCreatableTypesParallel>b__0(Assembly a)
>    at System.Linq.Parallel.SelectManyQueryOperator`3.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey)
>    at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
>    at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
>    at System.Linq.Parallel.SpoolingTaskBase.Work [http://System.Linq.Parallel.SpoolingTaskBase.Work]()
>    at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
>    at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()

Probably something goes wrong when updating or other stuff happens, that shouldn't. We should at least take a look. That would minimize a lot of negative reviews, support requests and unhappy people.

I'll post all further such crashes in this issue, every one i get via ticket or other means. If you require something specific, please tell me.

**Comment by D3nnis3n** [comment]
This is related to the countless "Connection failed" issues we have, these are the issues that typically lie beyond the message that doesn't help the users at all.

**Comment by D3nnis3n** [comment]
Addition: Lots of users report updates from Steam when there were none, i've seen this countless time on discord where some people ask what the new update brings, while there was none and others didnt get the message. I feel like Steam might have something to do with this, as i never had someone without Steam having these issues. (Though, steam users are far more, so that might also be the cause)

**Comment by D3nnis3n** [comment]
Another important info might be that this can not be fixed by steam repair. You need to actually (depending on which error you get) either delete the mods folder or the whole game folder, then repair. If you just press repair when you get this error, Steam does nothing to fix it - which is very weird.

**Comment by redwyre** [comment]
The problem is probably that steam isn't deleting files when they're removed. As users put their own files in there as well, we've gotten into a sticky situation where we can't just delete everything in there and replace it.

So the workaround is as you say, deleting the mods directory then verifying (if it is happening regularly then you can make a page on the wiki here and direct people to it for instructions).

Also note that @mirasrael has added some better crash reporting when a server launched from the client fails.

**Comment by redwyre** [comment]
Oh I just realised you mentioned in your first message that just deleting mods didn't work, if that happens again get the player to zip up their entire game dir and send it to us as something else must be failing too.

**Comment by trickenso** [comment]
> I can't (or don't want to) believe they are all lying to me and were installing mods.

Could it be related to downloading mods to match a modded server? This doesn't seem like 'downloading mods' to a player, and the server might not even advertise that it's modded, but i've still seen 'downloading mods' as part of the loading process for certain servers.

**Comment by redwyre** [comment]
> > I can't (or don't want to) believe they are all lying to me and were installing mods.
> 
> Could it be related to the client downloading mods to match a modded server? This doesn't seem like 'downloading mods' to a player, and the server might not even advertise that it's modded, but i've still seen 'downloading mods' as part of the loading process for certain servers even though I have not downloaded them myself.
> 
> If this is a server error, apologies - just highlighting something I noticed.

Nah, this is specifically an issue with the server, joining modded servers has no lasting effects on the client. "Downloading mods" happens with a vanilla server, the game itself is the mod.

**Comment by trickenso** [comment]
> Nah, this is specifically an issue with the server, joining modded servers has no lasting effects on the client. "Downloading mods" happens with a vanilla server, the game itself is the mod.

Acknowledged - thanks for clarifying.

**Comment by D3nnis3n** [comment]
> Oh I just realised you mentioned in your first message that just deleting mods didn't work, if that happens again get the player to zip up their entire game dir and send it to us as something else must be failing too.

Indeed. Of the three issues people had today one actually played with worldgen config and failed to produce valid json, the other one said he never installed mods or changed anything and deleting mods fixed it (noted that he didnt play eco for a long time, though) and the third had the issue i mentioned above, where just deleting mods did not fix it, so i suggested to delete the whole game directory after saving storage and configs (if necessary).

**Comment by redwyre** [comment]
The fix for this is complicated and requires a major re-working of how mods are loaded, so we'll push this to a later version. There is a workaround for the majority cases when this does break

**Comment by redwyre** [comment]
See also https://github.com/StrangeLoopGames/EcoIssues/issues/15997

**Comment by mirasrael** [comment]
Should be fixed with splitting user mods and non-user mods
