### ISSUE TITLE
[0.9.0 staging-1528] Crash when press revise 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16043]
Seems you should select "Prevent" to reproduce it
```
Server encountered an exception:

<size=60,00%>Exception: ArgumentException
Message:Property set method not found.
Source:System.Private.CoreLib

System.ArgumentException: Property set method not found.
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyTo(Object source, Object dest)
   at Eco.Gameplay.Civics.Misc.Cloner.Clone(Object source, Boolean topLevel)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyList(IList sourceVal, IList destVal)
   at Eco.Gameplay.Civics.Laws.TriggerSettings.CopyFrom(Object source)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyTo(Object source, Object dest)
   at Eco.Gameplay.Civics.Misc.Cloner.Clone(Object source, Boolean topLevel)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyList(IList sourceVal, IList destVal)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyTo(Object source, Object dest)
   at Eco.Gameplay.Civics.Misc.Cloner.Clone(Object source, Boolean topLevel)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyList(IList sourceVal, IList destVal)
   at Eco.Gameplay.Civics.Misc.Cloner.CopyTo(Object source, Object dest)
   at Eco.Gameplay.Components.CivicSlot.MakeNew(User user, SimpleEntry copyFrom)
   at Eco.Gameplay.Components.CivicObjectComponent.Edit(Player player, Int32 index)</size>
```
[Crash when press revise law.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4544285/Crash.when.press.revise.law.txt)
Step to reproduce:
- create law, /civics winelection, press revise law:
![image](https://user-images.githubusercontent.com/45708377/80464464-8460ba80-8942-11ea-904e-137e0c9985b3.png)

**Comment by johnkslg** [comment]
Excellent find, this is a quite hidden bug 🐛 
Fixed
