### ISSUE TITLE
[0.9.0 staging-1543] Can't load save files.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16207]
Step to reproduce:
- generate new world and join to it.
- place Blast Furnace and add fuel, electric water pump, wind turbine and connect it:
![image](https://user-images.githubusercontent.com/45708377/81388227-ac110900-9120-11ea-9943-7d65894cb498.png)
- place few stockpile, add iron concentrate to it, take Smelting.
- start iron bar order:
![image](https://user-images.githubusercontent.com/45708377/81388420-eed2e100-9120-11ea-9a7d-aac544abb44d.png)
- wait 5 minutes.
- close server. Try to load it. You can't:

```
[11:48:13.390] [28] [Error] [Eco] Failed to load server, Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.AirPollutionComponent.SetStatus()
   at Eco.Gameplay.Components.AirPollutionComponent.<Setup>b__26_0()
   at Eco.Core.Utils.ThreadSafeAction.Invoke()
   at Eco.Gameplay.Objects.WorldObject.set_Operating(Boolean value)
   at Eco.Gameplay.Objects.WorldObject.UpdateEnabledAndOperating()
   at Eco.Gameplay.Objects.WorldObject.BeginInitialize()
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass17_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__0(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```
[log_200508114743.log](https://github.com/StrangeLoopGames/EcoIssues/files/4597955/log_200508114743.log)

**Comment by johnkslg** [comment]
attach world?

**Comment by johnkslg** [comment]
https://drive.google.com/file/d/1dCzCFaeGe0Hj7_UZSbRIIhVXaRn1_xFc/view
