### ISSUE TITLE
[0.9.0 Staging-1542] Sending notification via executive action crashes the game or disconnects you

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16229]
Sending notification via executive action crashes the game or disconnects you.
First time i tried it, it crashed the game. Second time, I got disconnected with the attached error message
 
![image](https://user-images.githubusercontent.com/982322/81473508-3cbe1680-91ff-11ea-90f1-9f2b8672d288.png)

![image](https://user-images.githubusercontent.com/982322/81473525-52334080-91ff-11ea-8325-4fbe6c4ea9b4.png)

**Comment by beastyn** [comment]
Didn't crask, but message wasn't send and server had this
```
[12:31:33] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Gameplay.Systems.Chat.ChatManager.<>c__DisplayClass30_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass1_0.<RunWithExceptionLog>b__0()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.SendNotice.Perform(String desc, IContextObject action)
   at Eco.Gameplay.Civics.SendNotice.PerformExecutiveAction(User user, IContextObject context)
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.PerformBase(User executingUser)
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.Perform(User executingUser, Election election)
   at Eco.Gameplay.Civics.Election.ApplyIfFinished(Boolean forceEnd)
   at Eco.Gameplay.Civics.CivicsCommands.WinElection(User user, Election election, User winner)
[12:32:58] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Gameplay.Systems.Chat.ChatManager.<>c__DisplayClass30_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass1_0.<RunWithExceptionLog>b__0()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.SendNotice.Perform(String desc, IContextObject action)
   at Eco.Gameplay.Civics.SendNotice.PerformExecutiveAction(User user, IContextObject context)
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.PerformBase(User executingUser)
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.Perform(User executingUser, Election election)
   at Eco.Gameplay.Civics.Election.ApplyIfFinished(Boolean forceEnd)
   at Eco.Gameplay.Civics.CivicsCommands.WinElection(User user, Election election, User winner)```
