### ISSUE TITLE
[0.9.0 staging-1542] Server error and crash

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#16355]
Hello,
 in our Serverlog following error comes up:
![image](https://user-images.githubusercontent.com/47274045/82130034-0583d280-97c8-11ea-8a6e-8b8a06c4159f.png)
not quite sure if this is an general error or individual error.

but when exit server an server exception comes up:
--BEGIN DUMP--
Dump Time
05/16/2020 22:23:55

Exception
Exception: InvalidOperationException
Message:Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
Source:System.Windows.Forms

System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at Eco.Server.Startup.StopAsync()
   at Eco.Server.Startup.RunAsync(IHostApplicationLifetime applicationLifetime)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)

--END DUMP--
Server console close after a few secound automatically.

**Comment by SlayksWood** [comment]
dup #16290
