### ISSUE TITLE
[Beta 9.0 - 1542] Demographics draft can cause server crash

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#16377]
when trying to remove/delete a demographic draft that has been partially completed will crash the server,

If the draft is empty or had no modifications it can be deleted without issues

Expected Behaviour: Deletes partial draft without issue

Actual Behaviour: Causes a server crash,

Steps to reproduce:
Place a census bureau in a room so it is working
draft a demographic and edit some values
Save as a draft
try and delete/cancel

Server Error:
`
--BEGIN DUMP--
Dump Time
05/18/2020 20:16:05

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Gameplay.Components.CivicObjectComponent.<>c__DisplayClass39_0.b__0(IHasID x)
at System.Linq.Enumerable.Any[TSource](IEnumerable1 source, Func2 predicate)
at Eco.Gameplay.Components.CivicObjectComponent.Remove(Player player, Int32 index, Boolean removeActive)
at System.Threading.Tasks.Task.<>c.b__139_1(Object state)
at System.Threading.ThreadPoolWorkQueue.Dispatch()

--END DUMP--
`

**Comment by TheKye** [comment]
Can confirm still happens in beta 1554

**Comment by beastyn** [comment]
Was able to reproduce. Moving in here #18188
