### ISSUE TITLE
elections/generatetestdata fail to create ratification

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#16382]
On fresh server in newest staging build.
Need this for web devleopment work

`fail: Eco.WebServer.Web.Filters.ExceptionFilter[0]
      Error during execution of /api/v1/elections/generatetestdata
System.Exception: Failed to create ratification election.
   at Eco.Gameplay.Civics.CivicsTests.ConfigureCapitolObject(User mainUser, WorldObject capitolObject, WorldObject boardofElections, GovernmentType govType)
   at Eco.Gameplay.Civics.Elections.ElectionTests.SpawnElection(User user, Boolean forceFinish)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()`

**Comment by johnkslg** [comment]
got it fixed
