### ISSUE TITLE
Crash when Searching for Item

### ISSUE THREAD

**Issue by CaesarSquires** [StrangeLoopGames/EcoIssues#16477]
In 9.0, whenever entering "Advanced Upgrade Mining" in the #general chat window, the game crashes.

```
Server encountered an exception:

<size=60,00%>Exception: KeyNotFoundException
Message:The given key was not present in the dictionary.
Source:System.Collections.Immutable

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Systems.TextLinks.ItemFinder.<FindObjects>b__3_0(Match m)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at Eco.Gameplay.Systems.TextLinks.TextLinkManager.MarkUpText(String text)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessMessage(ChatMessage msg)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user, INetObject target)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(String text, User user, INetObject target)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChatStripped(Player player, String text, INetObject target)</size>
```

[Server encountered an exception.docx](https://github.com/StrangeLoopGames/EcoIssues/files/4678104/Server.encountered.an.exception.docx)

**Comment by SlayksWood** [comment]
dup #16476
