### ISSUE TITLE
[0.9.0.0 staging-1554] Module-Chat Issue

### ISSUE THREAD

**Issue by binaryclock03** [StrangeLoopGames/EcoIssues#16476]
**Version:** 0.9.0.0 beta staging-1554

**Steps to Reproduce:**
Type "Basic Upgrade Logging" into chat

**Expected behavior:**
Linked the module in chat like most other things in the game

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: KeyNotFoundException
Message:The given key was not present in the dictionary.
Source:System.Collections.Immutable

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Systems.TextLinks.ItemFinder.<FindObjects>b__3_0(Match m)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at Eco.Gameplay.Systems.TextLinks.TextLinkManager.MarkUpText(String text)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessMessage(ChatMessage msg)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user, INetObject target)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(String text, User user, INetObject target)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChatStripped(Player player, String text, INetObject target)</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Comment by binaryclock03** [comment]
I just checked and this seems to happen with all specialty modules not just logging

**Comment by SlayksWood** [comment]
And I can't see its link in chat if I enter module name with ( )
![image](https://user-images.githubusercontent.com/45708377/82869150-72b90580-9f36-11ea-8b28-82e558a556e8.png)
@WeaselDog maybe we should have any changes?
