### ISSUE TITLE
server crash in WorkOrder processing

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1652]
--BEGIN DUMP--
Dump Time
06/13/2017 03:46:08

Exception
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItems(InventoryBase inventory, IEnumerable`1 items, ItemCollection stack)
   at Eco.Gameplay.Items.WorkOrder.TryToGiveItems(InventoryBase destInventory, Boolean sendError)
   at Eco.Gameplay.Items.WorkOrder.UpdateCrafted()
   at Eco.Gameplay.Items.WorkOrder.set_Progress(Double value)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders(Single dtime)
   at Eco.Gameplay.Components.CraftingComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItems(InventoryBase inventory, IEnumerable`1 items, ItemCollection stack)
   at Eco.Gameplay.Items.WorkOrder.TryToGiveItems(InventoryBase destInventory, Boolean sendError)
   at Eco.Gameplay.Items.WorkOrder.UpdateCrafted()
   at Eco.Gameplay.Items.WorkOrder.set_Progress(Double value)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders(Single dtime)
   at Eco.Gameplay.Components.CraftingComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Inner Exception
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItems(InventoryBase inventory, IEnumerable`1 items, ItemCollection stack)
   at Eco.Gameplay.Items.WorkOrder.TryToGiveItems(InventoryBase destInventory, Boolean sendError)
   at Eco.Gameplay.Items.WorkOrder.UpdateCrafted()
   at Eco.Gameplay.Items.WorkOrder.set_Progress(Double value)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders(Single dtime)
   at Eco.Gameplay.Components.CraftingComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItems(InventoryBase inventory, IEnumerable`1 items, ItemCollection stack)
   at Eco.Gameplay.Items.WorkOrder.TryToGiveItems(InventoryBase destInventory, Boolean sendError)
   at Eco.Gameplay.Items.WorkOrder.UpdateCrafted()
   at Eco.Gameplay.Items.WorkOrder.set_Progress(Double value)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders(Single dtime)
   at Eco.Gameplay.Components.CraftingComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

--END DUMP--

**Comment by metachronism** [comment]
does not repro on master so closing out
