### ISSUE TITLE
Server crash with a law

### ISSUE THREAD

**Issue by Jhynx** [StrangeLoopGames/EcoIssues#16568]
I've got a server crash with a law. Here is the log :

[10:06:44.454] [108] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.PropertyValues.AllProperty.<>c__DisplayClass3_0.<Value>b__0(Deed x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Eco.Gameplay.Civics.GameValues.PropertyValues.AllProperty.Value(IContextObject context)
   at Eco.Gameplay.Civics.ChangePropertyOwner_LegalAction.Do(LocString desc, IContextObject context)
   at Eco.Gameplay.Civics.ChangePropertyOwner_LegalAction.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.LawManager.PerformTimerAction(Law law, LawSection section, Double timeSince, User user)
   at Eco.Gameplay.Civics.Laws.LawManager.<>c__DisplayClass3_2.<Tick>b__2(User user)
   at Eco.Shared.Utils.EnumerableExtensions.SelectNonNull[T,TResult](IEnumerable`1 sequence, Func`2 projection, TResult ifEmpty)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Civics.Laws.LawManager.Tick()
   at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[10:06:44.459] [5] [ Info] [Eco] Saving...  
[10:06:50.770] [145] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.PropertyValues.AllProperty.<>c__DisplayClass3_0.<Value>b__0(Deed x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Eco.Gameplay.Civics.GameValues.PropertyValues.AllProperty.Value(IContextObject context)
   at Eco.Gameplay.Civics.ChangePropertyOwner_LegalAction.Do(LocString desc, IContextObject context)
   at Eco.Gameplay.Civics.ChangePropertyOwner_LegalAction.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.LawManager.PerformTimerAction(Law law, LawSection section, Double timeSince, User user)
   at Eco.Gameplay.Civics.Laws.LawManager.<>c__DisplayClass3_2.<Tick>b__2(User user)
   at Eco.Shared.Utils.EnumerableExtensions.SelectNonNull[T,TResult](IEnumerable`1 sequence, Func`2 projection, TResult ifEmpty)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Civics.Laws.LawManager.Tick()
   at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Civics.CivicsPlugin.Shutdown()
   at Eco.Server.PluginManager.<>c.<Shutdown>b__37_0(PluginRegistration reg)
 
[10:06:52.420] [145] [ Info] [Eco] Shutdown finished

**Comment by SlayksWood** [comment]
@Jhynx Thank you for the report. Can you provide Steps and law example?

**Comment by Jhynx** [comment]
That was something like that, but i've do so many test...

![image](https://user-images.githubusercontent.com/11871836/83734731-adfeb700-a64f-11ea-8ed1-050a98ffcb61.png)
![law test](https://user-images.githubusercontent.com/11871836/83734767-b951e280-a64f-11ea-998d-1159e70aac63.JPG)

**Comment by Jhynx** [comment]
Or may be like this 
![law test2](https://user-images.githubusercontent.com/11871836/83734896-e605fa00-a64f-11ea-8c18-7dc1803daf0d.JPG)

**Comment by Jhynx** [comment]
I was trying to unclaim property of Abandonned and Deserteur, without sucess

**Comment by SlayksWood** [comment]
@Jhynx Can you give me Deserteur information? What is it like?

**Comment by Jhynx** [comment]
That only a title give by the registar :)

**Comment by beastyn** [comment]
One more case, looks the same##18525
After modifying law with this code, it caused the server to crash.
Current Law (Inactive Land Reclaim Act):
Section 1
On event Citizen Timer every 1 day on each person in Abandoned
Change owner of All property owned only by Abandoned to unowned
Proposed Law (Property Laws):
Inactive Land Reclaim Act
Citizens in the Abandoned demographics will have their properties reclaimed.
On event Citizen Timer every 1 day on each person in Abandoned
Change owner of All property owned by Citizen to unowned
log_200929100246.log
https://www.dropbox.com/s/h2e4hf1hocfn9cs/Game.eco?dl=0
https://www.dropbox.com/s/jqx26k9hmwxrzqs/Game.db?dl=0

**Comment by beastyn** [comment]
Also here #18636. Ask save from me.
