### ISSUE TITLE
[0.9.0 staging-1582] Can't learn skills

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16573]
1) At some point /skills all were not working.
It gives an error on the server
```
[14:01:45.568] [114] [Error] [Eco] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.<>c__DisplayClass34_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass1_0.<RunWithExceptionLog>b__0()
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Не удается найти указанный файл.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Eco.Shared.Utils.ReflectionUtils.<>c__DisplayClass10_0.<DerivedTypes>b__0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Eco.Gameplay.Items.DiscoveryManager.UpdateDiscoveredItems()
   at Eco.Gameplay.Skills.Skillset.LearnSkill(Type skillType)
   at Eco.Gameplay.Skills.Skillset.LearnSkillAndNotify(Skill skill)
   at Eco.Gameplay.Items.SkillScroll.OnUsed(Player player, ItemStack itemStack)
   at Eco.Gameplay.Systems.Chat.AdminCommands.All(User user)
```
2) Just take skill scroll and learn skill
In this case you will be disconnected but won;t see any errors on screen
Log is
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4729433/Player.log)

**Comment by redwyre** [comment]
It looks like this is actually happening a lot as part of CI tests but getting ignored
