### ISSUE TITLE
[0.9.0 staging-1586] Improve /road command to use new Asphalt concrete material

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16581]
/road 100,10,2 doesn't work anymore.

**Comment by SlayksWood** [comment]
Broken again after https://github.com/StrangeLoopGames/Eco/pull/6575

**Comment by SlayksWood** [comment]
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.<>c__DisplayClass12_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass1_0.<RunWithExceptionLog>b__0()
System.Collections.Generic.KeyNotFoundException: The given key 'AsphaltConcreteRampObject' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Objects.WorldObjectManager.GetTypeFromName(String s)
   at Eco.Gameplay.Systems.Chat.BuildingCommands.Road(User user, Int32 length, Int32 width, Int32 buildTypeVal, Int32 bottomType)
```

**Comment by WeaselDog** [comment]
I will fix this, sorry about the reopen.
