### ISSUE TITLE
[0.9.0 staging-1601] Graphs don't work.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16622]
Step to reproduce:
- create some law:
![image](https://user-images.githubusercontent.com/45708377/84367690-44495480-abdd-11ea-8c70-cf7eee388ede.png)
- open web ui and add some graps in comment in this election:
![image](https://user-images.githubusercontent.com/45708377/84367841-73f85c80-abdd-11ea-9150-c6138ff88f6e.png)
- graphs don't work whn you submit your comment and your have exception in command line.
![image](https://user-images.githubusercontent.com/45708377/84367615-2bd93a00-abdd-11ea-9314-b3e82a246fdc.png)
```
fail: Eco.WebServer.Web.Filters.ExceptionFilter[0]
      Error during execution of /datasets/get?dataSet=Redwood+Species&dayStart=0&dayEnd=0.2
System.Exception: No stat named Redwood Species was found (it is case sensitive).
   at Eco.Stats.StatInfoManager.GetInfo(String s)
   at Eco.Webserver.Web.Controllers.StatsController.GetGraphValues(String key, Double startDay, Double endDay)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by SlayksWood** [comment]
Also, the graphs don't work at all if the server is running in Gibberish.

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/6244
will create separate issue for Gibberish
