### ISSUE TITLE
[0.9.0-1605] Server Crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16788]
--BEGIN DUMP--
Dump Time
06/19/2020 23:49:37

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Districts.DistrictMap.UpdateDistrictStates()
   at Eco.Gameplay.Civics.Districts.DistrictMap.UpdateDistricts()
   at Eco.Gameplay.Civics.Districts.DistrictMap.Initialize()
   at Eco.Core.Systems.Registrar.Initialize()
   at Eco.Core.Systems.Registrars.Init()
   at Eco.Server.PluginManager.PostCreateAsync()
   at Eco.Server.Startup.StartAsync(String[] args)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)

--END DUMP--

Playtest failed to start after shutdown for update. It's not related to update to 1611 though, as rolling back to 1605 yielded the same result.

**Comment by D3nnis3n** [comment]
https://download.godsofwar.de/eco/buggedotter.zip

**Comment by D3nnis3n** [comment]
Required Rollback to 1605

**Comment by SlayksWood** [comment]
dup #16700
