### ISSUE TITLE
crash dump files from 5.6 server

### ISSUE THREAD

**Issue by Hazy21** [StrangeLoopGames/EcoIssues#1699]
Started using 5.6 Ecoserver. Tried to regen a new map,but nothin happened and then crashed
[Crash 06211344.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1090140/Crash.06211344.zip)
[Crash 06212006.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1090141/Crash.06212006.zip)
[Crash 06212512.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1090142/Crash.06212512.zip)

**Comment by MarjieAVolk** [comment]
We've got:

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.WorldGenerator.WorldGeneratorPlugin.<>c__DisplayClass25_0.<CreateWorld>b__8(PersistentChunk chunk)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.WorldGenerator.WorldGeneratorPlugin.CreateWorld()
   at Eco.WorldGenerator.WorldGeneratorPlugin.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Followed by 8 copies of:

---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.WorldGenerator.WorldGeneratorPlugin.<>c__DisplayClass25_0.<CreateWorld>b__8(PersistentChunk chunk)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
