### ISSUE TITLE
[0.9.0 staging-1657] Unclaiming the store cause server crash

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17086]
and I can't load it anymore. Step to reproduced:
- start a new server, /bt 2,10,7,10,1,1, claim some land and place store:
![image](https://user-images.githubusercontent.com/45708377/87301936-1d05e000-c519-11ea-8c1f-1546c1fb5d1f.png)
- add some items for bying/selling list:
![image](https://user-images.githubusercontent.com/45708377/87302051-5b030400-c519-11ea-9010-9ac3272d51f4.png)
- unclaim this property:
![image](https://user-images.githubusercontent.com/45708377/87301984-3444cd80-c519-11ea-8ba0-83047830b5a6.png)
- I have exception in client log:
```
Exception in view notify: System.NullReferenceException: Object reference not set to an instance of an object.
  at CreditComponentUI.GetCash () [0x00000] in <00000000000000000000000000000000>:0 
  at CreditComponentUI.ReactBankChanges () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.LowLevel.PlayerLoopSystem+UpdateFunction.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.View.ViewManager.ReceiveViewUpdate (Eco.Shared.Serialization.BSONArray updates) [0x00000] in <00000000000000000000000000000000>:0 
  at ClientPacketHandler.ReceiveWhile (Eco.Shared.Networking.NetworkClient client, System.Func`1[TResult] condition) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.OnTimeLimitedUpdate (TimeLimit timeLimit) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.PlannerGroup.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.FramePlannerSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.LowLevel.PlayerLoopSystem+UpdateFunction.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.View.View:NotifyChanged(String)
Eco.Shared.View.ViewManager:ReceiveViewUpdate(BSONArray)
ClientPacketHandler:ReceiveWhile(NetworkClient, Func`1)
NetworkManager:OnTimeLimitedUpdate(TimeLimit)
System.Action`1:Invoke(T)
FramePlanner.PlannerGroup:OnUpdate()
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
UnityEngine.LowLevel.UpdateFunction:Invoke()
```
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4912254/Player.log)

- my server was shutdowned:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Trackers.ItemMarketInfo.CompareTo(Object obj)
   at Eco.Core.Utils.ServerListExtensions.<>c__0`1.<Pairs>b__0_2(Tuple`2 tuple)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at Eco.Gameplay.Economy.Trackers.ExchangeRates.UpdateRates(IEnumerable`1 allTrades)
   at Eco.Gameplay.Economy.EconomyTracker.DoWork()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Economy.EconomyTracker.Shutdown()
   at Eco.Server.PluginManager.<>c.<Shutdown>b__37_0(PluginRegistration reg)
 ```
[log_200713025013.log](https://github.com/StrangeLoopGames/EcoIssues/files/4912260/log_200713025013.log)

**Comment by SlayksWood** [comment]
@StanKryvenko seems it related with your last changes, ask @olegshegai for helping.

**Comment by SlayksWood** [comment]
check #12361 after fixing
