### ISSUE TITLE
[0.9.0.0 beta staging-stable-3] server error : Exception: KeyNotFoundException

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17204]
Was doing things in law UI in solo.

```
Server encountered an exception:

<size=60,00%>Exception: KeyNotFoundException
Message:The given key was not present in the dictionary.
Source:System.Collections.Immutable

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Core.Controller.ControllerManager.GetControllerInstanceInfo(IController controller)
   at Eco.Core.Controller.ControllerExtensions.SubscribeAllRecursive(ISubscriptions subs, IController controller, Action`2 changedCallback, Func`2 filter)
   at Eco.Core.Controller.ControllerExtensions.SubscribeAllRecursive(ISubscriptions subs, IController controller, Action`2 changedCallback, Func`2 filter)
   at Eco.Gameplay.Systems.ViewEditor.UpdateValidity(PropertyInfo prop, Object objParent)
   at Eco.Gameplay.Systems.ViewEditor.<Setup>b__32_0()
   at Eco.Shared.View.SubscriptionsExtensions.SubscribeAndCall(ISubscriptions ss, IObservable s, String propname, Action changedCallback, Action unsubscribeCallback)
   at Eco.Gameplay.Systems.ViewEditor.Setup(User user, ISaveablePlugin toSave, String buttonText, String overrideTitle)
   at Eco.Gameplay.Systems.ViewEditor..ctor(User user, IController toEdit, ISaveablePlugin toSave, String buttonText, String overrideTitle, Type restrictToType, Boolean readOnly)
   at Eco.Gameplay.Systems.ViewEditor.Edit(User user, IController controller, ISaveablePlugin toSave, Action`1 onSubmit, String buttonText, String overrideTitle, String uiStyle, Type restrictToType, Boolean readOnly)
   at Eco.Gameplay.Components.CivicObjectComponent.Edit(Player player, Int32 index)</size>
```
[log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4950662/log.txt)

**Comment by SlayksWood** [comment]
merged to #15378
