### ISSUE TITLE
 [0.9.0.0 beta staging-stable-8] Can propose invalid elected title

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#17391]
[https://www.dropbox.com/s/dlhzwtry0m2a3zu/Desktop%202020.07.29%20-%2014.50.20.01.mp4?dl=0](https://www.dropbox.com/s/dlhzwtry0m2a3zu/Desktop%202020.07.29%20-%2014.50.20.01.mp4?dl=0)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4994933/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4994934/Player-prev.log)

**Comment by SlayksWood** [comment]
The same in Amendments:
- start to create new article:
![image](https://user-images.githubusercontent.com/45708377/88889417-bedf3980-d248-11ea-855d-5f2aea738b01.png)
- select applies to Demographic and it's all, now you can propose it:
![image](https://user-images.githubusercontent.com/45708377/88889456-d28aa000-d248-11ea-87f9-cbca9d2d428a.png)

**Comment by SlayksWood** [comment]
and if you try to create elected title with broken article server will crash:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Titles.ElectedTitle.Valid()
   at Eco.Gameplay.Civics.Misc.PropertyScanner.InternalCheck(Object obj, ScannerContext context, ScannerScope scope, Boolean testMainObj)
   at Eco.Gameplay.Civics.Misc.PropertyScanner.CheckAndApply(Object obj, ScannerContext context, ScannerScope scope)
   at Eco.Gameplay.Systems.ViewEditor.UpdateValidity(PropertyInfo prop, Object objParent)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Core.Controller.ControllerInstanceInfo.NotifyChanged(String propname)
   at Eco.Core.Controller.ControllerManager.NotifyChanges()
   at Eco.Core.Controller.ControllerManager.DoWork()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass4_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Core.Controller.ControllerManager.Shutdown()
   at Eco.Server.PluginManager.<>c.<Shutdown>b__37_0(PluginRegistration reg)
```
