### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17461]
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Nullable object must have a value.
Source:System.Private.CoreLib

System.InvalidOperationException: Nullable object must have a value.
   at Eco.Shared.Pathing.AITarget.Position(Single timeOffset)
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__69_1()</size>

Log File:
PlayerConnection initialized from D:/Programme/Steam/steamapps/common/Eco/Eco_Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55384
Multi-casting "[IP] 192.168.178.20 [Port] 55384 [Flags] 2 [Guid] 2146829102 [EditorId] 3238161807 [Version] 1048832 [Id] WindowsPlayer(DENNIS-PC) [Debug] 0 [PackageName] WindowsPlayer [ProjectName] Eco" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55384]
PlayerConnection already initialized - listening to [0.0.0.0:55384]
Initialize engine version: 2019.4.1f1 (e6c045e14e4e)
[Subsystems] Discovering subsystems at path D:/Programme/Steam/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 2080 Ti (ID=0x1e07)
    Vendor:   
    VRAM:     11048 MB
    Driver:   27.21.14.5167
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 5.506600 ms
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects. 
(Filename: C:\buildslave\unity\build\Runtime/SceneManager/SceneManager.cpp Line: 582)

WwiseUnity: Wwise(R) SDK Version 2019.2.1 Build 7250.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Running with audio. To disable audio and increase load speed, delete Content/Wwise_Eco folder or rename it.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script (ImportantNotificationsListController) on this Behaviour is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Scripting/ManagedReference/SerializableManagedRef.cpp Line: 199)

The referenced script on this Behaviour (Game Object 'Camera') is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 334)

The referenced script on this Behaviour (Game Object 'Important notifications') is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 334)

The referenced script on this Behaviour (Game Object 'Table') is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 334)

Ambiguous UI component types ignored: SeriesPopupUI,BaseUI,ViewEditorUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.UIManager:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 301)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 301)

Nat introduction received with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
RunLoop:Invoke(Boolean&)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(IntPtr, IntPtr, UInt32, Boolean&)
ENet.RawDataReceivedHandler:Invoke(IntPtr, IntPtr, UInt32, Boolean&)
ENet.Host:HandleIntercept(IntPtr, IntPtr)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass60_0:<Initialize>b__0()
RootMotion.FinalIK.GrounderDelegate:Invoke()
OnJoinInfo:Invoke(String)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
RootMotion.FinalIK.GrounderDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Nat punch received from 95.217.35.61:3020 with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
RunLoop:Invoke(Boolean&)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(IntPtr, IntPtr, UInt32, Boolean&)
ENet.RawDataReceivedHandler:Invoke(IntPtr, IntPtr, UInt32, Boolean&)
ENet.Host:HandleIntercept(IntPtr, IntPtr)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass60_0:<Initialize>b__0()
RootMotion.FinalIK.GrounderDelegate:Invoke()
OnJoinInfo:Invoke(String)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
RootMotion.FinalIK.GrounderDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Connecting to 95.217.35.61:3020...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleNatIntroductionSuccess(IPEndPoint, String)
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
RunLoop:Invoke(Boolean&)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(IntPtr, IntPtr, UInt32, Boolean&)
ENet.RawDataReceivedHandler:Invoke(IntPtr, IntPtr, UInt32, Boolean&)
ENet.Host:HandleIntercept(IntPtr, IntPtr)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass60_0:<Initialize>b__0()
RootMotion.FinalIK.GrounderDelegate:Invoke()
OnJoinInfo:Invoke(String)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
RootMotion.FinalIK.GrounderDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'LayerViewer') is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 334)

Unable to open archive file: D:/Programme/Steam/steamapps/common/Eco/Eco_Data/StreamingAssets/desc.unity3d 
(Filename: C:\buildslave\unity\build\Runtime/VirtualFileSystem/ArchiveFileSystem/ArchiveStorageReader.cpp Line: 584)

Missing following icons:
AttachmentComponent
BarterTrade
BlockForm
ChargingComponent
CurrencyTrade
DeedManagementComponent
DidntVote
FakePlantComponent
FormType
FuelConsumptionComponent
FuelSupplyComponent
LinkComponent
LiquidProducerComponent
LogicGateObject
ModularStockpileComponent
ModularVehicleComponent
MountComponent
OnOffComponent
PowerConsumptionComponent
PowerGeneratorComponent
PowerGridComponent
PowerGridNetworkComponent
RoofsFormGroup
RoomRequirementsComponent
StandaloneAuthComponent
TollComponent
VehicleHoeComponent
VehicleToolComponent
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<CreateMissingItems>d__52:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>d__53:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Missing following objects: AirPollutionGeneratorObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<BuildFromModKit>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>d__47:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Nullable object must have a value.
Source:System.Private.CoreLib

System.InvalidOperationException: Nullable object must have a value.
   at Eco.Shared.Pathing.AITarget.Position(Single timeOffset)
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__69_1()</size>
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, Boolean)
Eco.Shared.Networking.UdpDisconnectedHandler:Invoke(Object, Boolean)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass60_0:<Initialize>b__0()
RootMotion.FinalIK.GrounderDelegate:Invoke()
OnJoinInfo:Invoke(String)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
RootMotion.FinalIK.GrounderDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 1.35 GB.
System memory in use after: 1.01 GB.

Unloading 8914 unused Assets to reduce memory usage. Loaded Objects now: 92472.
Total: 366.985600 ms (FindLiveObjects: 11.902600 ms CreateObjectMapping: 5.281400 ms MarkObjects: 320.182800 ms  DeleteObjects: 29.618400 ms)
```

**Comment by SlayksWood** [comment]
need to investigate with new AI
