### ISSUE TITLE
Opened Stockpile, got DCed with error

### ISSUE THREAD

**Issue by Fr3aKeD** [StrangeLoopGames/EcoIssues#1752]
Been having odd issues, posted issue earlier about stockpiles and storages.

5.6.1 -
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC SetObjectEnabled on LinkComponent!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Objects.WorldObjectHandle..ctor(WorldObject obj)
   at Eco.Gameplay.Components.LinkComponent.GetLinkSettings(String username, WorldObject linkedObj)
   at Eco.Gameplay.Components.LinkComponent.SetObjectEnabled(String username, WorldObject linkedObj, Boolean enabled)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by metachronism** [comment]
latest staging #5314c8ac should be fixed
