### ISSUE TITLE
[0.9.0 staging-1702] White-Tiger server crash (AI related)

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#17531]
Server log: 

[18:19:02.439] [307] [Error] [Eco] System.AggregateException: One or more errors occurred. (Negating the minimum value of a twos complement number is invalid.)

```
System.OverflowException: Negating the minimum value of a twos complement number is invalid.
   at Eco.Simulation.Agents.AI.AIUtil.GridTraverse(Vector2 start, Vector2 end, Func`2 visit)
   at Eco.Simulation.Agents.AI.AIUtil.TargetPositionIsValidSwimming(Vector3 startPosition, Vector3 targetPosition, Single minDistance)
   at Eco.Simulation.Agents.AI.AIUtil.FindTargetSwimPosition(Vector3 position, Single minRadius, Single maxRadius, Vector2 direction, Single minDirectionOffsetDegrees, Single maxDirectionOffsetDegrees, Int32 tryCount, Boolean surface)
   at Eco.Mods.Organisms.Behaviors.MovementBehaviors.Swim(Animal agent, Vector2 direction, Boolean wandering, AnimalState state, Boolean surface, Int32 tries) in D:\Servers\Eco\White Tiger\Mods\Organisms\Animal\Behaviors\MovementBehaviors.cs:line 129
   at Eco.Mods.Organisms.Behaviors.MovementBehaviors.<>c.<.cctor>b__30_9(Behavior`1 beh, Animal agent) in D:\Servers\Eco\White Tiger\Mods\Organisms\Animal\Behaviors\MovementBehaviors.cs:line 42
   at Eco.Simulation.Agents.AI.BehaviorBasic`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorSelector`1.Do(T context)
   at Eco.Simulation.Agents.AI.Brain.TickBehaviors(Animal animal)
   at Eco.Simulation.Agents.AI.Brain.Tick(Animal animal)
   at Eco.Simulation.Agents.Animal.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Simulation.EcoSim.<DoTick>b__41_0()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[18:19:02.439] [5] [ Info] [Eco] Saving...  
[18:19:02.765] [182] [Debug] [Eco] Nat introduction received with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[18:19:02.994] [182] [Debug] [Eco] Nat punch received from 14.202.192.217:62022 with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[18:19:02.994] [182] [Debug] [Eco] Nat punch received from 14.202.192.217:62022 with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[18:19:09.400] [196] [Error] [Eco] System.OverflowException: Negating the minimum value of a twos complement number is invalid.
   at Eco.Simulation.Agents.AI.AIUtil.GridTraverse(Vector2 start, Vector2 end, Func`2 visit)
   at Eco.Simulation.Agents.AI.AIUtil.TargetPositionIsValidSwimming(Vector3 startPosition, Vector3 targetPosition, Single minDistance)
   at Eco.Simulation.Agents.AI.AIUtil.FindTargetSwimPosition(Vector3 position, Single minRadius, Single maxRadius, Vector2 direction, Single minDirectionOffsetDegrees, Single maxDirectionOffsetDegrees, Int32 tryCount, Boolean surface)
   at Eco.Mods.Organisms.Behaviors.MovementBehaviors.Swim(Animal agent, Vector2 direction, Boolean wandering, AnimalState state, Boolean surface, Int32 tries)
   at Eco.Mods.Organisms.Behaviors.MovementBehaviors.<>c.<.cctor>b__30_9(Behavior`1 beh, Animal agent)
   at Eco.Simulation.Agents.AI.BehaviorBasic`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorSelector`1.Do(T context)
   at Eco.Simulation.Agents.AI.Brain.TickBehaviors(Animal animal)
   at Eco.Simulation.Agents.AI.Brain.Tick(Animal animal)
   at Eco.Simulation.Agents.Animal.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Simulation.EcoSim.<DoTick>b__41_0()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Server.PluginManager.<>c.<Shutdown>b__37_0(PluginRegistration reg)
 
[18:19:13.204] [196] [ Info] [Eco] Shutdown finished

```

**Comment by WeaselDog** [comment]
There is a good chance this is already fixed in our develop branch.

**Comment by WeaselDog** [comment]
Save from 18 minutes before it happened: https://drive.google.com/file/d/1Ek6QcNzcIihdgSJmLXDJIZzemIOrHrEG/view?usp=sharing
