### ISSUE TITLE
NullReferenceException crash

### ISSUE THREAD

**Issue by legionaw** [StrangeLoopGames/EcoIssues#17546]
Server Version: Server 0.8.3.3 beta
OS Version: Windows 10 Home edition 64-bit, build 1903
Memory: 16GB RAM
Processor: Intel Core i7-7700K CPU - 4.20 GHz

I just had a server crash today which was NullReferenceException. I was the only user online on my server and was pulling a Wood Cart at the time it occurred. The crash would appear to be related to this Wood Cart as seem to be evident from the following line "at Eco.Gameplay.Components.VehicleComponent.Tick()" but I am uncertain. I should also note that the server is hosted on the same computer as my client. The file is attached below.

[ServerCrash NullReferenceException 08041151.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5025063/ServerCrash.NullReferenceException.08041151.zip)

**Comment by SlayksWood** [comment]
Thank you for the report, we'll investigate it
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.VehicleComponent.Tick()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
