### ISSUE TITLE
[0.9.0.0 - dev-23] Modding - Server crash on config manipulation

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#17581]
While developing DiscordLink is noticed the server would crash when any element (that is not a collection) was changed in the config via the server UI.
For booleans, this happens right away and for other types it crashes upon hitting enter while the input field has focus.
This is a huge issue for the 9.0 update of the mod as we recommend our users to do configuration via the server interface.

I've made a minimal project that reproduces the issue. I used DLLs fetched from the temp directory of the dev-23 server for this.
[EcoServerCrashMVP.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5033963/EcoServerCrashMVP.zip)

Here is the DLL output of the above project (compiled with debug flags)
[EcoServerCrashMVP.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5033974/EcoServerCrashMVP.zip)

Steps to reproduce:
1. Add the mod DLL to the server.
2. Start the server.
3. In the server UI, navigate to EcoServerCrashMVP.MVP (probably did something odd to get that name but that shouldn't be related to the crash).
4. Change the value of the "The Bool" field.
5. Observe NullReferenceException outside of the plugin code.

--------------------------
Exception + Stack trace
--------------------------
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Server.UI.ServerMainForm.<>c__DisplayClass7_0.<BuildEditor>b__0(Object o, PropertyValueChangedEventArgs e)
   at System.Windows.Forms.PropertyGrid.OnPropertyValueChanged(PropertyValueChangedEventArgs e)
   at System.Windows.Forms.PropertyGrid.OnPropertyValueSet(GridItem changedItem, Object oldValue)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.CommitValue(GridEntry ipeCur, Object value, Boolean closeDropDown)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.ProcessEnumUpAndDown(GridEntry gridEntry, Keys keyCode, Boolean closeDropDown)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.OnEditKeyDown(Object sender, KeyEventArgs ke)
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.GridViewEdit.OnKeyDown(KeyEventArgs ke)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.GridViewEdit.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

--------------------------
Plugin code reference
--------------------------
```
using System.ComponentModel;
using Eco.Core.Plugins;
using Eco.Core.Plugins.Interfaces;
using Eco.Core.Utils;

namespace EcoServerCrashMVP
{
    public class MVP : IModKitPlugin, IConfigurablePlugin, IInitializablePlugin
    {
        public ThreadSafeAction<object, string> ParamChanged { get; set; }
        private PluginConfig<TinyConfig> _configOptions;

        public string GetStatus()
        {
            return _configOptions.Config.TheBool ? "Bool is True" : "Bool is False";
        }

        public IPluginConfig PluginConfig
        {
            get { return _configOptions; }
        }

        public object GetEditObject()
        {
            return _configOptions.Config;
        }

        public void OnEditObjectChanged(object o, string param)
        {
            
        }

        public void Initialize(TimedTask timer)
        {
            _configOptions = new PluginConfig<TinyConfig>("CrashMVP");
        }
    }

    public class TinyConfig
    {
        [Description("Flip to crash!"), Category("Crashing")]
        public bool TheBool { get; set; } = false;
    }
}
```

**Comment by MonzUn** [comment]
Priority: Medium doesn't seem to fit this ticket in my opinion.
This does indeed prevent a feature from being used (Medium tag says it shouldn't prevent a feature from being used) and it also risks crashing servers in runtime.

**Comment by mirasrael** [comment]
Doesn't matter how much priority it have, because I already fixed this ;) BTW, issue was with ParamChanged not set.

**Comment by mirasrael** [comment]
BTW, thanks for detailed report which really helped to fix it fast.

**Comment by MonzUn** [comment]
Thanks a bunch! :D
This was a huge issue for us with DiscordLink as even if we warned users about it, they are unlikely to remember or even read it >.<

Haha, I know have a tendency to prefer issues that are easily reproducible when I pick form our backlog at work, so I figured making your life easier would increase the chances of this getting fixed :P I guess that goes for all bug reports though ^^

**Comment by mirasrael** [comment]
Yeah, you're right. It how it works ;)
