### ISSUE TITLE
Moving Stacks of 100 (usually crops) - Disconnects from Server 

### ISSUE THREAD

**Issue by Neurotik** [StrangeLoopGames/EcoIssues#1768]
So i have made a Large Scale Farm on my server I play on. I usually harvest between 5-7k of each crop per day. I am often moving 1000s of Wheat, Beans, etc. from my inventory into Storage Chests. It often takes a long time for the stack to be registered as being moved. If i move a stack into a place where one is still waiting to be put it comes up with this error.

Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on LimitedInventory!

Could not find target stack in target inventory!

Stack:
at Eco.Gameplay.Items.InventoryChangeSet.MoveStack(InventoryBase sourceInventory, ItemCollection sourceStack, InventoryBase targetInventory, ItemCollection targetStack)
at Eco.Gameplay.Items.InventoryBase.MoveItems(ItemCollection sourceStack, InventoryBase targetInventory, ItemCollection targetStack, Player player)

Stack:
at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by MarjieAVolk** [comment]
This should be fixed in the next release
