### ISSUE TITLE
Accessing blocks over the 0/1000 coordinates causes Out Of Bounds error

### ISSUE THREAD

**Issue by syhrus** [StrangeLoopGames/EcoIssues#1770]
When placing/harvesting camas bulbs I occasionally get this error and disconnect from the server:

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Index was outside the bounds of the array.

Stack:
   at Eco.Simulation.WorldLayers.Layers.WorldLayer.FuncAtWorldPos(Vector2i pos, Func`3 func)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Camas places/harvests correctly on server side (as it is gone/planted), but client side does not register the change (ie same number of camas as before planting/harvesting)

**Comment by syhrus** [comment]
UPDATE: It seems this is actually directly related to the plots in question. I've been building roads in the area and it causes the same issue.

**Comment by syhrus** [comment]
Worked it out: The error occurs when accessing a block on the other side of the coordinate start point. 
One side is at z=1000, other is z=0. If you access one from the other side of the line it causes the error
