### ISSUE TITLE
[0.9.0 staging-1728] Server exception: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by RedBaron88** [StrangeLoopGames/EcoIssues#17799]
I was kicked from my server for the attached reason and had to reconnect. Did not seem to effect anything with the game play.
[server.error.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5098861/server.error.txt)

**Comment by beastyn** [comment]
@RedBaron88 thank you for the report.
Can you provide a bit more information?
Like what were you doing? Maybe creating a contact or finishing it?

**Comment by RedBaron88** [comment]
I may have been looking at a contract board a few minutes prior and reading someone else's contract where the dropoff container was no longer linked because it had been moved. I went afk for a minute and came back to the error message.

**Comment by beastyn** [comment]
@RedBaron88 thank you, we will investigate it further

**Comment by SlayksWood** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClauseTransport.get_Contents() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Gameplay\Economy\Contracts\ContractClauseTransport.cs:line 26
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass19_0`2.<FuncMethodHelper>b__0(TTarget target) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Utils\ReflectionUtils.cs:line 210
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Controller\ControllerManager.cs:line 774
   at Eco.Core.Controller.ControllerManager.PackageView(IController controller, IMvcNetClient client, PackageFlags flags) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Controller\ControllerManager.cs:line 486
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient mvcClient, PackageFlags flags) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Controller\ControllerManager.cs:line 834
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Controller\ControllerManager.cs:line 751
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Controller\ControllerManager.cs:line 774
   at Eco.Core.Controller.ControllerManager.PackageView(IController controller, IMvcNetClient client, PackageFlags flags) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Controller\ControllerManager.cs:line 486
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, IMvcNetClient mvcClient, PackageFlags flags) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Controller\ControllerManager.cs:line 834
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Shared\Serialization\AutoBsonSerializer.cs:line 229
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client, Boolean doAllParams) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Shared\Utils\ContainerExtensions.cs:line 396
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Shared\Serialization\AutoBsonSerializer.cs:line 229
   at Eco.Shared.Serialization.BsonManipulator.ToBson(IDictionary dictionary, INetClient client, Boolean useReflection) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Shared\Serialization\AutoBsonSerializer.cs:line 167
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Shared\Serialization\AutoBsonSerializer.cs:line 229
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Controller\ControllerManager.cs:line 756
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Controller\ControllerManager.cs:line 774
   at Eco.Core.Controller.ControllerManager.GetChanges(IMvcNetClient client) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Controller\ControllerManager.cs:line 535
   at Eco.Plugins.Networking.Client.Update() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Plugins\Networking\Client.cs:line 372
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Plugins\Networking\Client.cs:line 115</size>
```

**Comment by TwixterZ** [comment]
@RedBaron88 apologies this took so long to get back to, but I can confirm this issue no longer persist.
