### ISSUE TITLE
[0.5.6.1] "Agriculture Skill Book" project stuck

### ISSUE THREAD

**Issue by Enkki2** [StrangeLoopGames/EcoIssues#1780]
"Agriculture skill book" project has been stuck for hours on status "Time 0%, ressources 100%" 
![image](https://user-images.githubusercontent.com/29982528/27964264-ec6d93e8-6337-11e7-8291-eb1eba44bfb6.png)

When trying to cancel this project, client crashes with following message:

_Caught exception: Caught exception invoking RPC ViewRPC on Client!
Caught exception invoking RPC CancelWorkOrder on CraftingComponent!
Object reference not set to an instance of an object.
Stack:
   at Eco.Gameplay.Items.ChangedInventories..ctor(ChangedInventories changedInventories)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItemRecursive(InventoryBase inventory, Item item, ItemCollection stack, ChangedInventories originalState)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItemRecursive(InventoryBase inventory, Item item, ItemCollection stack, ChangedInventories originalState)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItemRecursive(InventoryBase inventory, Item item, ItemCollection stack, ChangedInventories originalState)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItems(InventoryBase inventory, IEnumerable`1 items, ItemCollection stack)
   at Eco.Gameplay.Components.CraftingComponent.TryToCancel(WorkOrder workOrder, InventoryCollection destInventory, User user, IEnumerable`1 itemsToRefund)
   at Eco.Gameplay.Components.CraftingComponent.CancelWorkOrder(Player player, WorkOrder workOrder)
Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)_

**Comment by MarjieAVolk** [comment]
Would you be able to send me the server Game.eco save file this is happening on?

**Comment by Enkki2** [comment]
My wrong .. I missed following status warning:
![image](https://user-images.githubusercontent.com/29982528/27972658-6be0eae8-6357-11e7-97a0-113ad8b15450.png)
The reason was a shelter without any roof .. Now that the roof has been added, the project starts correctly.
The issue can therefore be closed (except if you want to focus on the crash).

**Comment by MarjieAVolk** [comment]
Yeah if your save is still giving the crash, I'd like to have it

**Comment by MarjieAVolk** [comment]
Well, okay we're going to change up the inventory system internally, so this crash might not be relevant anymore

**Comment by MarjieAVolk** [comment]
Oh just realized we had another report with this crash: StrangeLoopGames/EcoIssues#1780
