### ISSUE TITLE
[0.5.6.1] Picking up powered cart when gasoline is too heavy

### ISSUE THREAD

**Issue by Suomukas** [StrangeLoopGames/EcoIssues#1784]
So I got my powered cart stuck. I wanted to pick it up and it said that the gasoline is too heavy. I make some room, pick it up again and game crashes.
Error message complains about gasoline being too heavy;
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Could not apply inventory changes! The Gasolines are 1,200001kg too heavy.

Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Components.FuelSupplyComponent.OnPickUp(Player player)
   at Eco.Gameplay.Objects.WorldObject.OnPickUp(Player player)
   at Eco.Gameplay.Objects.WorldObject.PickUp(Player player)
   at HammerItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

So I return to the game and I noticed that I now have powered cart in my inventory, but the original cart is still there. I tried picking it up again, it crashed again and now I have 3 powered carts. Magic.

![capture](https://user-images.githubusercontent.com/30022480/27994422-b97a9ab8-64c6-11e7-9cd3-afec463fecca.JPG)

EDIT: So I did testing. Removing the gasoline first, then picking up the cart works fine.

**Comment by stormoffires** [comment]
This also happens with excavators. I've had to use admin tool to delete copies
