### ISSUE TITLE
Server stuck in restart loop.

### ISSUE THREAD

**Issue by ChrisMayhew** [StrangeLoopGames/EcoIssues#1785]
My server is now stuck in a restart loop, this is the crash dump.

`--BEGIN DUMP--
Dump Time
07/09/2017 15:56:27

Exception
System.AggregateException: One or more errors occurred. ---> Eco.Gameplay.Items.InventoryException: Could not apply inventory changes! Carpentry Tables cannot be placed in that inventory.
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Components.FuelSupplyComponent.LoadFuel()
   at Eco.Gameplay.Components.FuelSupplyComponent.TryConsumeFuel(Single joules)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) Eco.Gameplay.Items.InventoryException: Could not apply inventory changes! Carpentry Tables cannot be placed in that inventory.
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Components.FuelSupplyComponent.LoadFuel()
   at Eco.Gameplay.Components.FuelSupplyComponent.TryConsumeFuel(Single joules)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Inner Exception
System.AggregateException: One or more errors occurred. ---> Eco.Gameplay.Items.InventoryException: Could not apply inventory changes! Carpentry Tables cannot be placed in that inventory.
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Components.FuelSupplyComponent.LoadFuel()
   at Eco.Gameplay.Components.FuelSupplyComponent.TryConsumeFuel(Single joules)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) Eco.Gameplay.Items.InventoryException: Could not apply inventory changes! Carpentry Tables cannot be placed in that inventory.
   at Eco.Gameplay.Items.InventoryChangeSet.Apply(User user)
   at Eco.Gameplay.Components.FuelSupplyComponent.LoadFuel()
   at Eco.Gameplay.Components.FuelSupplyComponent.TryConsumeFuel(Single joules)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

--END DUMP--
`

Any ideas on how to fix this?

**Comment by MarjieAVolk** [comment]
Okay, so you have carpentry tables in a fuel supply somewhere, and it doesn't like that, is what I'm guessing.  Assigning Craig and Eric, since I think the inventory changes will fix this problem, but there also might be some power specific issue here.

**Comment by metachronism** [comment]
this is fixed as part of the inventory overhaul in alpha 6
