### ISSUE TITLE
[[0.9.0 staging-1740] Steam: can't connect to a server

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17893]
Try to connect to a local server
![bandicam 2020-08-26 10-17-02-908](https://user-images.githubusercontent.com/27898520/91305366-69089d80-e7c4-11ea-8d6e-8e795456b176.jpg)
[Player(1).log](https://github.com/StrangeLoopGames/EcoIssues/files/5129878/Player.1.log)

**Comment by redwyre** [comment]
Aug 26 05:16:53 ip-172-31-15-49 auth-staging[13024]: 
AuthServer.Controllers.AuthController[0] => 
ConnectionId:0HM24BIDOT2K7 => 
RequestPath:/game/verifytokenv3 RequestId:0HM24BIDOT2K7:00000001, SpanId:|f1a258e1-444d05cda17f44cc., TraceId:f1a258e1-444d05cda17f44cc, ParentId: => 
AuthServer.Controllers.AuthController.Verify (AuthServer) 
Unable to load shared library 'sdkencryptedappticket' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsdkencryptedappticket: cannot open shared object file: No such file or directory 
System.DllNotFoundException: Unable to load shared library 'sdkencryptedappticket' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsdkencryptedappticket: cannot open shared object file: No such file or directory
    at Steamworks.NativeMethods.SteamEncryptedAppTicket_BDecryptTicket(Byte[] rgubTicketEncrypted, UInt32 cubTicketEncrypted, Byte[] rgubTicketDecrypted, UInt32& pcubTicketDecrypted, Byte[] rgubKey, Int32 cubKey)
    at AuthServer.Services.SteamService.DecryptTicket(String encryptedTicket) in C:\Jenkins\workspace\auth.stagingland.strangeloopgames.com auto-deploy\AuthServer\Services\SteamService.cs:line 116
    at AuthServer.Services.AuthService.GetUserBySteamTicket(AuthDbContext ctx, String ticket) in C:\Jenkins\workspace\auth.stagingland.strangeloopgames.com auto-deploy\AuthServer\Services\AuthService.cs:line 395
    at AuthServer.Services.AuthService.VerifyTokenSteam(AuthDbContext ctx, String token, String serverId) in C:\Jenkins\workspace\auth.stagingland.strangeloopgames.com auto-deploy\AuthServer\Services\AuthService.cs:line 262
    at AuthServer.Services.AuthService.VerifyToken(AuthDbContext ctx, String token, String serverId) in C:\Jenkins\workspace\auth.stagingland.strangeloopgames.com auto-deploy\AuthServer\Services\AuthService.cs:line 129
    at AuthServer.Controllers.AuthController.Verify(String token, String serverId) in C:\Jenkins\workspace\auth.stagingland.strangeloopgames.com auto-deploy\AuthServer\Controllers\AuthController.cs:line 73

**Comment by D3nnis3n** [comment]
Blocks public test starting today, needs fix soon.

**Comment by redwyre** [comment]
was because auth server wasn't being built to target linux, and didn't have steam key set up
