### ISSUE TITLE
Game is crashing and disconnecting players  Caught exception invoking RPC ViewRPC on Client!

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#1790]
Game is crashing and disconnecting players:  Caught exception invoking RPC ViewRPC on Client!
Game.eco is here:  https://www.dropbox.com/s/t7ahahibi8pncm6/Game.eco?dl=0
Dump files from today are here:  https://www.dropbox.com/s/6q8pq1fnfp3mx12/Dump-7-10-17.zip?dl=0

**Comment by SeanAtr0n** [comment]
Looks like a bug in inventories during swap stacks

**Comment by MarjieAVolk** [comment]
There are a few different crashes in there

**Comment by MarjieAVolk** [comment]
The swap stacks one I haven't seen lately - could maybe have been an async thing, like someone tried to swap 2 stacks at the same time as someone else took one of those stacks out - but I don't think I can debug that one without more context.

There were 3 other unique exceptions; 1 of them I actually fixed here (https://github.com/StrangeLoopGames/Eco/pull/1613), 1 of them has it's own bug (StrangeLoopGames/EcoIssues#1744), and here is the last one, which I don't know anything about:

Exception
System.ArgumentNullException: Buffer cannot be null.
Parameter name: buffer
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at Eco.Shared.Utils.CompressionUtils.Decompress(Byte[] source)
   at Eco.World.WorldChunkGrid.GetChunkUpdate(WorldChunk chunk)
   at Eco.World.WorldChunkGrid.GetBSONChunkArray(IDictionary`2 lastSentChunks, Vector3 position, Single distance)
   at Eco.World.WorldChunkGrid.GetChunkUpdates(BSONObject bsonObj, IDictionary`2 lastSentChunks, Vector3 position, Single distance)
   at Eco.World.WorldChunkGrid.SendUpdate(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetObjectUpdates(IEnumerable`1 objects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_1()

**Comment by metachronism** [comment]
closing as there are separate issues for each other exception here
