### ISSUE TITLE
Collecting Charred Meat from campfire cause exception and disconnect.

### ISSUE THREAD

**Issue by papersneaker** [StrangeLoopGames/EcoIssues#1791]
I am receiving the following error when I attempt to collect charred meat from campfire.
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC TryToCollectItems on WorkOrder!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.ChangedInventories..ctor(ChangedInventories changedInventories)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItemRecursive(InventoryBase inventory, Item item, ItemCollection stack, ChangedInventories originalState)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItemRecursive(InventoryBase inventory, Item item, ItemCollection stack, ChangedInventories originalState)
   at Eco.Gameplay.Items.InventoryChangeSet.AddItemRecursive(InventoryBase inventory, Item item, ItemCollection stack, ChangedInventories originalState)
   at Eco.Gameplay.Items.WorkOrder.TryToGiveItems(InventoryBase destInventory, Boolean sendError)
   at Eco.Gameplay.Items.WorkOrder.TryToCollectItems(Player collector)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by papersneaker** [comment]
It may be related to trying to collect with a full inventory.

**Comment by MarjieAVolk** [comment]
Ah, this is another instance of a problem I fixed earlier (with InventoryChangeSet.changedInventories being null) - should be fixed in the next release!
