### ISSUE TITLE
[0.9.0 staging-1749] Law: crash(es) with Property requirement condition

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18008]
1. Make a law like this
![bandicam 2020-09-01 12-11-06-286](https://user-images.githubusercontent.com/27898520/91822147-c7180380-ec50-11ea-9134-4eb48a99cf20.jpg)

2. Go and claim some property with plants and some property where you can hunt (/animal Bison for spawn animal there)

You can have two crashes:
1. After harvesting a plant: server will crash
```
--BEGIN DUMP--
Dump Time
09/01/2020 12:16:48

Exception
Exception: SynchronizationLockException
Message:Object synchronization method was called from an unsynchronized block of code.
Source:System.Private.CoreLib

System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Monitor.Exit(Object obj)
   at Eco.Gameplay.Items.InventoryLock.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Finalize()

--END DUMP--
```

2. After you shoot an animal Client will crash
```
--BEGIN DUMP--
Dump Time
09/01/2020 12:41:19

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.Law.Perform(GameAction action)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameAction action, Boolean notify)
   at Eco.Gameplay.Animals.AnimalEntity.TryApplyDamage(INetObject damager, Single damage, InteractionContext context, Item tool, Type damageDealer)
   at Eco.Mods.TechTree.ArrowEntity.Hit(NetObjAttachInfo hitAttachInfo, Vector3 position, String location) in D:\Games\SteamLibrary\steamapps\common\Eco\Eco_Data\Server\Mods\Tools\BowItem.cs:line 118

--END DUMP--
```
Expected: with this kind of law you should be able hunt and harvest on any deed (authorized or not authorized)

**Comment by NDKilla** [comment]
Just wanted to mention this was originally(?) mentioned here #17949 and I'm subscribing to this issue :D thanks for separating them out and triaging as appropriate.

**Comment by beastyn** [comment]
@NDKilla thanks for linking )
