### ISSUE TITLE
Tables are not working, issues with blast furnace, game corruption, server list issues

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#1803]
Tables are not working, issues with blast furnace, game corruption, server list issues

https://www.dropbox.com/s/060pdxl7rsy0g2d/USKILLSERVERS.zip?dl=0

**Comment by REPOSEECO** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/1800

**Comment by MarjieAVolk** [comment]
Here's the exception:  I think I've seen this one before >> can't find a bug with it though

System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Cannot create an instance of an interface.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer`2.Decode(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToObject(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToObject(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer`2.Decode(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToObject(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToObject(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.Load[T](String folder, Action`2 createFunc)
   at Eco.Core.Plugins.StorageManager.CreateOrLoad[StorageType](String folder)
   at Eco.Gameplay.Legislation..ctor()

**Comment by MarjieAVolk** [comment]
Okay, well I fixed a couple of issues, and then I was able to get the save you sent to load.  So, fixed!  Not sure what was up with the Legislation thing though, guess that was already fixed?  I had seen it before so.

Anyway, will be fixed in a future release.
