### ISSUE TITLE
Giant Panda didn't start again after Restart

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18099]
```
[22:41:55.542] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[22:41:55.563] [1] [ Info] [Eco] [Eco Server 0.9.0.0 beta staging-1774]
 
[22:41:55.603] [5] [ Info] [Eco] [Starting [PerformancePlugin]]...  
[22:41:55.603] [5] [ Info] [Eco] [Server Initialization]...  
[22:41:56.111] [5] [ Info] [Eco] Starting LocalizationPlugin...  
[22:41:56.143] [5] [ Info] [Eco] Starting DifficultySettings...  
[22:41:56.143] [5] [ Info] [Eco] Loading mods...  
[22:42:05.276] [1] [ Info] [Eco] Mods recompiled with warnings.
 
[22:42:05.295] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[22:42:05.361] [1] [ Info] [Eco] Loading Rules...
 
[22:42:05.392] [5] [ Info] [Eco] Loading mods... Finished in 9,245.1ms
 
[22:42:05.392] [5] [ Info] [Eco] Starting ModKitPlugin...  
[22:42:05.392] [5] [ Info] [Eco] Initializing Simulation Types...  
[22:42:05.465] [5] [ Info] [Eco] Starting NetworkManager...  
[22:42:05.496] [5] [ Info] [Eco] Starting BackupPlugin...  
[22:42:06.058] [5] [ Info] [Eco] Starting WorldGeneratorPlugin...  
[22:42:06.137] [5] [ Info] [Eco] Initializing items...  
[22:42:08.881] [5] [ Info] [Eco] Starting StorageManager...  
[22:42:08.896] [5] [ Info] [Eco] Loading GameData...  
[22:42:08.933] [5] [ Info] [Eco] Starting GameDataPlugin...  
[22:42:08.933] [5] [ Info] [Eco] Loading Pause...  
[22:42:08.981] [5] [ Info] [Eco] Starting Stats...  
[22:42:09.006] [5] [ Info] [Eco] Starting PausePlugin...  
[22:42:10.581] [5] [ Info] [Eco] Initializing skills...  
[22:42:10.669] [5] [ Info] [Eco] Loading World...  
[22:42:22.237] [5] [ Info] [Eco] Initializing world...  
[22:42:22.610] [5] [ Info] [Eco] Starting WorldPlugin...  
[22:42:22.610] [5] [ Info] [Eco] Loading Time...  
[22:42:22.620] [5] [ Info] [Eco] Starting TimePlugin...  
[22:42:22.620] [5] [ Info] [Eco] Loading Reputation...  
[22:42:22.670] [5] [ Info] [Eco] Starting ReputationPlugin...  
[22:42:22.670] [5] [ Info] [Eco] Starting PlayerHousingManager...  
[22:42:22.726] [5] [ Info] [Eco] Loading Users...  
[22:42:24.536] [5] [ Info] [Eco] Initializing inventories...  
[22:42:24.589] [5] [ Info] [Eco] Starting UserManager...  
[22:42:24.613] [5] [ Info] [Eco] Loading Objects...  
[22:42:24.801] [5] [ Info] [Eco] Starting EcoObjectManager...  
[22:42:24.801] [5] [ Info] [Eco] Starting DataExporter...  
[22:42:24.808] [5] [ Info] [Eco] Starting VoiceManager...  
[22:42:24.808] [5] [ Info] [Eco] Loading Garbage...  
[22:42:24.808] [5] [ Info] [Eco] Starting GarbagePlugin...  
[22:42:24.833] [5] [ Info] [Eco] Loading EconomyManager...  
[22:42:25.837] [5] [ Info] [Eco] Starting EconomyPlugin...  
[22:42:25.846] [5] [ Info] [Eco] Loading Disasters...  
[22:42:25.846] [5] [ Info] [Eco] Starting DisasterPlugin...  
[22:42:25.846] [5] [ Info] [Eco] Loading ViewTypeData...  
[22:42:25.867] [5] [ Info] [Eco] Loading Chat...  
[22:42:28.536] [5] [ Info] [Eco] Starting ControllerManager...  
[22:42:35.091] [5] [ Info] [Eco] Starting ChatServer...  
[22:42:35.091] [5] [ Info] [Eco] Loading Property...  
[22:42:36.358] [5] [ Info] [Eco] Starting PropertyManager...  
[22:42:36.358] [5] [ Info] [Eco] Starting MinimapManager...  
[22:42:36.574] [5] [ Info] [Eco] Loading Plants...  
[22:42:37.676] [5] [ Info] [Eco] Initializing plants...  
[22:42:45.223] [5] [ Info] [Eco] Starting EcoSim...  
[22:42:45.223] [5] [ Info] [Eco] Loading RouteProbing...  
[22:42:48.144] [5] [ Info] [Eco] Starting RouteProbingPlugin...  
[22:42:48.144] [5] [ Info] [Eco] Loading Layers...  
[22:42:48.552] [5] [ Info] [Eco] Initializing world layers...  
[22:42:48.558] [5] [ Info] [Eco] Loading ClimateSim...  
[22:42:55.702] [5] [ Info] [Eco] Starting WorldLayerManager...  
[22:42:55.702] [5] [ Info] [Eco] Starting EconomyTracker...  
[22:42:55.702] [5] [ Info] [Eco] Starting UserTracker...  
[22:42:55.721] [5] [ Info] [Eco] Loading Civics...  
[22:42:55.864] [5] [ Info] [Eco] Starting CivicsPlugin...  
[22:42:56.290] [5] [ Info] [Eco] Loading WorldObjects...  
[22:42:57.072] [5] [ Info] [Eco] Starting WorldObjectManager...  
[22:42:57.081] [5] [ Info] [Eco] Loading Rooms...  
[22:42:57.089] [5] [ Info] [Eco] Starting RoomPlugin...  
[22:42:57.089] [5] [ Info] [Eco] Loading Objectives...  
[22:42:57.089] [5] [ Info] [Eco] Starting ObjectivePlugin...  
[22:42:57.089] [5] [ Info] [Eco] Loading Sleep...  
[22:42:57.105] [5] [ Info] [Eco] Starting SleepPlugin...  
[22:42:57.105] [5] [ Info] [Eco] Starting WebServerPlugin...  
[22:42:57.105] [5] [ Info] [Eco] Starting ExtendedUser...  
[22:42:57.105] [5] [ Info] [Eco] Starting IntegrationTestsPlugin...  
[22:42:57.132] [5] [ Info] [Eco] Initializing registrars for CivicsPlugin...  
[22:42:57.159] [5] [ Info] [Eco] Initializing registrars for GameDataPlugin...  
[22:42:57.173] [5] [ Info] [Eco] Initializing registrars for EconomyPlugin...  
[22:42:57.327] [13] [Error] [Eco] Enumerable deserialization error. Missing reference for element: Eco.Gameplay.Players.User:464. It will be ignored, but may cause inconsistency and errors in other entities.
 
[22:42:57.593] [13] [Error] [Eco] Enumerable deserialization error. Missing reference for element: Eco.Gameplay.Items.WorkOrder:33247. It will be ignored, but may cause inconsistency and errors in other entities.
 
[22:43:00.488] [5] [ Info] [Eco] Initializing DifficultySettings...  
[22:43:00.488] [5] [ Info] [Eco] Initializing Stats...  
[22:43:00.720] [5] [ Info] [Eco] Initializing CivicsPlugin...  
[22:43:00.755] [5] [ Info] [Eco] Initializing PerformancePlugin...  
[22:43:00.755] [5] [ Info] [Eco] Initializing LocalizationPlugin...  
[22:43:00.824] [5] [ Info] [Eco] Initializing ModKitPlugin...  
[22:43:01.292] [5] [ Info] [Eco] Initializing WorldGeneratorPlugin...  
[22:43:01.292] [5] [ Info] [Eco] Initializing TimePlugin...  
[22:43:01.292] [5] [ Info] [Eco] Initializing UserManager...  
[22:43:01.588] [5] [ Info] [Eco] Initializing GarbagePlugin...  
[22:43:01.588] [5] [ Info] [Eco] Initializing EconomyPlugin...  
[22:43:01.610] [5] [ Info] [Eco] [Server Initialization]... Finished in 66,004.6ms
 
[22:43:01.625] [13] [Error] [Eco] Failed to load server, Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.BankAccountManager.<>c.<Initialize>b__20_1(PersonalAccount x)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Eco.Gameplay.Economy.BankAccountManager.Initialize()
   at Eco.Gameplay.Economy.EconomyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync()
   at Eco.Server.Startup.StartAsync()
 
[22:43:06.636] [1] [Error] [Eco] Unhandled errorSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.BankAccountManager.<>c.<Initialize>b__20_1(PersonalAccount x)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Eco.Gameplay.Economy.BankAccountManager.Initialize()
   at Eco.Gameplay.Economy.EconomyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync()
   at Eco.Server.Startup.StartAsync()
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
```

**Comment by D3nnis3n** [comment]
Backup restored, so its working for the last few hours.

**Comment by gzatravkin** [comment]
Investigated. Looks like save data didn't got that migration https://github.com/StrangeLoopGames/Eco/pull/6734 because server already was at version 3805. But some account had old format, so after restart it loose his data (saying so because forcing migration by increasing number versions cause exceptions too, proabably because save data already have changed schema). 

And since it don't got migration it have wrong data and getting null exception. Should affect only a playtest, migration from 8.3 should go right. Anyway it's worth to test

**Comment by mirasrael** [comment]
Yes, this issue can only manually be fixed and won't happen on new worlds or worlds in 9.0 which didn't run broken update.
