### ISSUE TITLE
USER ISSUE: only person kicked from server

### ISSUE THREAD

**Issue by TrueDeser** [StrangeLoopGames/EcoIssues#18113]
\
**Version:** 0.9.0.0 beta

**Steps to Reproduce:**
fresh install- happened randomly

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Shared

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Shared.Math.Route.WaypointsAtTime(Single time)
   at Eco.Shared.Pathing.RouteFollower.Position(Single lookAhead)
   at Eco.Shared.Pathing.AITarget.Position(Single timeOffset)
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@TrueDeser thank you for the report. Were you able to reconnect?

**Comment by TrueDeser** [comment]
yes i was able to reconnect immediatly. The same thing happend one more time since then. I have been playing alot so it's 2 times in about 24 hours of actively playing.
btw thanks for the great patch, me and my friends are having alot of fun.

**Comment by beastyn** [comment]
And here #18196 with a lot of these errors and kicks off.
