### ISSUE TITLE
Lastest docker [Eco Server 0.9.0.0 beta] - network crash on start

### ISSUE THREAD

**Issue by geoffwong** [StrangeLoopGames/EcoIssues#18139]
[10:18:57] Initializing NetworkManager... Finished in 26.6ms
[10:18:57] Initializing WorldLayerManager... 
[10:18:57] Initializing WorldLayerManager... Finished in 0.1ms
[10:18:57] Initializing WebServerPlugin... 
[10:18:57] Skipping Windows firewall setup, platform = Unix
[10:18:57] (You may need to manually open port 3001 if the EcoWebServer is inaccessible)
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {65b99124-6f13-478b-8350-8032da9b7389} may be persisted to storage in unencrypted form.
[10:18:57] Web Server now listening on: http://0.0.0.0:3001
[10:18:57] Initializing WebServerPlugin... Finished in 333.0ms
[10:18:57] Initializing IntegrationTestsPlugin... 
[10:18:57] Initializing IntegrationTestsPlugin... Finished in 0.2ms
Unhandled exception. System.InvalidOperationException: Host creation call failed
   at ENet.Host.Create(Address address, Int32 peerLimit, Int32 channelLimit, UInt32 incomingBandwidth, UInt32 outgoingBandwidth, Int32 bufferSize)
   at ENet.Host.Create(Address address, Int32 peerLimit, Int32 channelLimit)
   at ENet.Host.Create(Address address, Int32 peerLimit)
   at Eco.Networking.ENet.ENetUdpPeer.Start() in C:\Jenkins\workspace\Eco Release\Server\Eco.Networking.ENet\ENetUdpPeer.cs:line 124
   at Eco.Plugins.Networking.NetworkServer.Initialize(IUdpLibrary udpLib) in C:\Jenkins\workspace\Eco Release\Server\Eco.Plugins\Networking\NetworkServer.cs:line 268
   at Eco.Plugins.Networking.NetworkManager.Run() in C:\Jenkins\workspace\Eco Release\Server\Eco.Plugins\Networking\NetworkManager.cs:line 292
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by geoffwong** [comment]
Same behavior in the 0.9.0.1 beta container.

**Comment by redwyre** [comment]
How are you running the container?

**Comment by geoffwong** [comment]
docker run -it -p 3000:3000/udp -p 3001:3001/tcp -v $(pwd)/Configs:/app/Configs  -v $(pwd)/Storage:/app/Storage strangeloopgames/eco-game-server:0.9.0.2-beta

**Comment by redwyre** [comment]
What OS is the host?

**Comment by geoffwong** [comment]
Ubuntu 18.04.

I followed the other threads mentioned here and it appears to be related to ipv6 - being enabled/disabled in the Host OS impacting the docker container (which I don't think it should?).

I generally have ipv6 disabled because I have other game servers on this host that prefer to bind to ipv6 rather than ipv4 (with no override). Anyway - I re-enabled it and it works from the container.

**Comment by redwyre** [comment]
Can you link the other thread for reference?

Are you saying you had to enable ipv6 on the host, or disable it?

**Comment by redwyre** [comment]
You could try putting 0.0.0.0 or the container's IP as the `IPAddress` in network.eco

**Comment by geoffwong** [comment]
I had to enable ipv6.

I had previously tried 0.0.0.0 in my Network config and that didn't help.

**Comment by mirasrael** [comment]
Probably fixed with ENet changes (https://github.com/StrangeLoopGames/Eco/pull/6928)

**Comment by SlayksWood** [comment]
@geoffwong Hi, this issue was fixed, but you need to wait 9.0.5 version to check it. If you are interested to check it early, please contact me on the discord Kirill (Slayks)#6251.
