### ISSUE TITLE
USER ISSUE: Cant join a server

### ISSUE THREAD

**Issue by Anne-Spitfyre** [StrangeLoopGames/EcoIssues#18159]
![image](https://user-images.githubusercontent.com/71087399/92753429-7e96cf00-f34f-11ea-9327-3b3c261ae10c.png)
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Cant join.

**Expected behavior:**
let me join

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60,00%>Exception: KeyNotFoundException
Message:The given key was not present in the dictionary.
Source:System.Collections.Immutable

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Tutorial.UserTaskManager.AddActiveTask(String taskName)
   at Eco.Gameplay.Tutorial.TutorialTasks.AddInitialTutorialTasks(User user)
   at Eco.Gameplay.Players.User.FirstLogin()
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client, Boolean allowDisconnectionAfterActionFailure, Boolean ignoreTestMode)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@Anne-Spitfyre Thank you for the report. Are you connecting there for the first time or have you already played there?

**Comment by beastyn** [comment]
issue will be discussed here #18132
