### ISSUE TITLE
[v9.0.1] Error when trying to connect to a server through steam

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#18162]
Step to reproduce :
- Friend invited me to join her game using steam overlay menu
- I accept the invitation, game load and after reaching 100% i have a connexion failed popup (see below)

I can ask for save file if required.

```<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60,00%>Exception: KeyNotFoundException
Message:The given key was not present in the dictionary.
Source:System.Collections.Immutable

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Core.Utils.ThreadSafeDictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Tutorial.UserTaskManager.AddActiveTask(String taskName)
   at Eco.Gameplay.Tutorial.TutorialTasks.AddInitialTutorialTasks(User user)
   at Eco.Gameplay.Players.User.FirstLogin()
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client, Boolean allowDisconnectionAfterActionFailure, Boolean ignoreTestMode)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)</size>

Log File:
Initialize engine version: 2019.4.9f1 (50fe8a171dd9)
[Subsystems] Discovering subsystems at path D:/Logiciels/SteamLibrary/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1be1)
    Vendor:   
    VRAM:     8082 MB
    Driver:   27.21.14.5206
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.725800 ms
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects. 
(Filename:  Line: 589)

WwiseUnity: Wwise(R) SDK Version 2019.2.5 Build 7349.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Setting Plugin DLL path to: D:/Logiciels/SteamLibrary/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Sound engine initialized successfully.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'Camera') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object 'Table') is missing! 
(Filename:  Line: 334)

DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
SteamManager:Awake()

[ line 589] 
(Filename:  Line: 589)

Ambiguous UI component types ignored: SeriesPopupUI,BaseUI,ViewEditorUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.UIManager:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:35:46.094] Nat introduction received with token = a5cb1359-a387-4cfd-9d56-0fdd1523f48e
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
Unity.Entities.JobRunWithoutJobSystemDelegate:Invoke(Void*)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(IntPtr, IntPtr, UInt32, Boolean&)
ENet.RawDataReceivedHandler:Invoke(IntPtr, IntPtr, UInt32, Boolean&)
ENet.Host:HandleIntercept(IntPtr, IntPtr)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass59_0:<Initialize>b__0()
HighlightingSystem.OnEndOfFrame:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
HighlightingSystem.OnEndOfFrame:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:35:46.203] Connecting to 192.168.0.16:3000...

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleNatIntroductionSuccess(IPEndPoint, String)
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
Unity.Entities.JobRunWithoutJobSystemDelegate:Invoke(Void*)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(IntPtr, IntPtr, UInt32, Boolean&)
ENet.RawDataReceivedHandler:Invoke(IntPtr, IntPtr, UInt32, Boolean&)
ENet.Host:HandleIntercept(IntPtr, IntPtr)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass59_0:<Initialize>b__0()
HighlightingSystem.OnEndOfFrame:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
HighlightingSystem.OnEndOfFrame:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'LayerViewer') is missing! 
(Filename:  Line: 334)

Unable to open archive file: D:/Logiciels/SteamLibrary/steamapps/common/Eco/Eco_Data/StreamingAssets/desc.unity3d 
(Filename:  Line: 584)

[10:36:11.367] Missing following icons:
AsphaltConcreteRampItem
AttachmentComponent
BlockForm
ChargingComponent
ContractEscrowBankAccount
FakePlantComponent
FormType
FuelConsumptionComponent
FuelSupplyComponent
GovernmentBankAccount
LinkComponent
LiquidProducerComponent
LogicGateObject
ModularStockpileComponent
ModularVehicleComponent
MountComponent
OnOffComponent
PersonalAccount
PowerConsumptionComponent
PowerGeneratorComponent
PowerGridComponent
PowerGridNetworkComponent
RoofsFormGroup
RoomRequirementsComponent
StandaloneAuthComponent
TollComponent
TreasuryBankAccount
VehicleHoeComponent
VehicleToolComponent
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<CreateMissingItems>d__52:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>d__53:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:36:11.593] Missing following objects: AirPollutionGeneratorObject
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<BuildFromModKit>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:36:12.734] Disconnected with error: Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.BankAccountManager.TryCreateUserAccount(User user)
   at Eco.Gameplay.Players.User.Initialize()
   at Eco.Core.Systems.Registrar.Insert(IHasID newObj, INetObject netObj)
   at Eco.Gameplay.Players.UserManager.PrepareNewUser(String steamId, String slgId, String username)
   at Eco.Gameplay.Players.UserManager.GetOrCreateUser(String steamId, String slgId, String username)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, Boolean)
System.Threading.WaitOrTimerCallback:Invoke(Object, Boolean)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass59_0:<Initialize>b__0()
HighlightingSystem.OnEndOfFrame:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
HighlightingSystem.OnEndOfFrame:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)

Unloading 30781 unused Assets to reduce memory usage. Loaded Objects now: 89056.
Total: 438.586300 ms (FindLiveObjects: 11.929300 ms CreateObjectMapping: 19.257700 ms MarkObjects: 356.034400 ms  DeleteObjects: 51.364100 ms)

[10:36:54.984] Nat introduction received with token = a5cb1359-a387-4cfd-9d56-0fdd1523f48e
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
Unity.Entities.JobRunWithoutJobSystemDelegate:Invoke(Void*)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(IntPtr, IntPtr, UInt32, Boolean&)
ENet.RawDataReceivedHandler:Invoke(IntPtr, IntPtr, UInt32, Boolean&)
ENet.Host:HandleIntercept(IntPtr, IntPtr)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass59_0:<Initialize>b__0()
HighlightingSystem.OnEndOfFrame:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
HighlightingSystem.OnEndOfFrame:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:36:54.988] Connecting to 192.168.0.16:3000...

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleNatIntroductionSuccess(IPEndPoint, String)
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
Unity.Entities.JobRunWithoutJobSystemDelegate:Invoke(Void*)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(IntPtr, IntPtr, UInt32, Boolean&)
ENet.RawDataReceivedHandler:Invoke(IntPtr, IntPtr, UInt32, Boolean&)
ENet.Host:HandleIntercept(IntPtr, IntPtr)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass59_0:<Initialize>b__0()
HighlightingSystem.OnEndOfFrame:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
HighlightingSystem.OnEndOfFrame:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'LayerViewer') is missing! 
(Filename:  Line: 334)

Unable to open archive file: D:/Logiciels/SteamLibrary/steamapps/common/Eco/Eco_Data/StreamingAssets/desc.unity3d 
(Filename:  Line: 584)

[10:37:02.179] Missing following icons:
AsphaltConcreteRampItem
AttachmentComponent
BlockForm
ChargingComponent
ContractEscrowBankAccount
FakePlantComponent
FormType
FuelConsumptionComponent
FuelSupplyComponent
GovernmentBankAccount
LinkComponent
LiquidProducerComponent
LogicGateObject
ModularStockpileComponent
ModularVehicleComponent
MountComponent
OnOffComponent
PersonalAccount
PowerConsumptionComponent
PowerGeneratorComponent
PowerGridComponent
PowerGridNetworkComponent
RoofsFormGroup
RoomRequirementsComponent
StandaloneAuthComponent
TollComponent
TreasuryBankAccount
VehicleHoeComponent
VehicleToolComponent
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<CreateMissingItems>d__52:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>d__53:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:37:02.377] Missing following objects: AirPollutionGeneratorObject
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<BuildFromModKit>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>d__47:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:37:03.411] Disconnected with error: Server encountered an exception:

<size=60,00%>Exception: KeyNotFoundException
Message:The given key was not present in the dictionary.
Source:System.Collections.Immutable

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Core.Utils.ThreadSafeDictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Tutorial.UserTaskManager.AddActiveTask(String taskName)
   at Eco.Gameplay.Tutorial.TutorialTasks.AddInitialTutorialTasks(User user)
   at Eco.Gameplay.Players.User.FirstLogin()
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client, Boolean allowDisconnectionAfterActionFailure, Boolean ignoreTestMode)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, Boolean)
System.Threading.WaitOrTimerCallback:Invoke(Object, Boolean)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass59_0:<Initialize>b__0()
HighlightingSystem.OnEndOfFrame:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
HighlightingSystem.OnEndOfFrame:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 30766 unused Assets to reduce memory usage. Loaded Objects now: 89119.
Total: 504.551200 ms (FindLiveObjects: 10.927300 ms CreateObjectMapping: 18.412800 ms MarkObjects: 428.394600 ms  DeleteObjects: 46.815600 ms)
```

**Comment by matheod** [comment]
Worked after she restarted her game. Feel free to close this issue.

**Comment by lagonnebula** [comment]
I think this is the same issue to this one : 
https://github.com/StrangeLoopGames/EcoIssues/issues/18132

**Comment by beastyn** [comment]
Yeap, its all the same. Players can have it after some time if server is localized.
