### ISSUE TITLE
USER ISSUE: Server crash

### ISSUE THREAD

**Issue by DCarts** [StrangeLoopGames/EcoIssues#18192]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Was just swimming

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Collection was modified; enumeration operation may not execute.
Source:System.Private.CoreLib

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client, Boolean doAllParams)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.GetChanges(IMvcNetClient client)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Server had modified the carry limits

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5211570/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5211571/Player.log)

**Comment by beastyn** [comment]
@DCarts thank you for the report.
Were you doing something specific before swimming?

**Comment by beastyn** [comment]
Rebasing to here #18214
