### ISSUE TITLE
Giant Panda failing to start after big RAM spikes

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18211]
First, this:
https://cdn.discordapp.com/attachments/591984093609066519/754430104935071815/unknown.png

Panda used 18 GB vs 4 for Tiger and Otter permanently and spiked up to 50 GB usage, stalling the server in _seconds_ every other minute.

```
[22:04:41.199] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[22:04:41.214] [1] [ Info] [Eco] [Eco Server 0.9.0.1 beta]
 
[22:04:41.245] [5] [ Info] [Eco] [Starting [PerformancePlugin]]...  
[22:04:41.245] [5] [ Info] [Eco] [Server Initialization]...  
[22:04:41.607] [5] [ Info] [Eco] Starting LocalizationPlugin...  
[22:04:41.634] [5] [ Info] [Eco] Starting DifficultySettings...  
[22:04:41.637] [5] [ Info] [Eco] Loading mods...  
[22:04:48.983] [1] [ Info] [Eco] Mods recompiled with warnings.
 
[22:04:48.983] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[22:04:49.040] [1] [ Info] [Eco] Loading Rules...
 
[22:04:49.058] [5] [ Info] [Eco] Loading mods... Finished in 7,420.6ms
 
[22:04:49.058] [5] [ Info] [Eco] Starting ModKitPlugin...  
[22:04:49.060] [5] [ Info] [Eco] Initializing Simulation Types...  
[22:04:49.105] [5] [ Info] [Eco] Starting NetworkManager...  
[22:04:49.115] [5] [ Info] [Eco] Starting BackupPlugin...  
[22:04:49.587] [5] [ Info] [Eco] Starting WorldGeneratorPlugin...  
[22:04:49.638] [5] [ Info] [Eco] Initializing items...  
[22:04:51.737] [5] [ Info] [Eco] Starting StorageManager...  
[22:04:51.747] [5] [ Info] [Eco] Loading GameData...  
[22:04:51.767] [5] [ Info] [Eco] Starting GameDataPlugin...  
[22:04:51.767] [5] [ Info] [Eco] Loading Pause...  
[22:04:51.806] [5] [ Info] [Eco] Starting PausePlugin...  
[22:04:51.806] [5] [ Info] [Eco] Starting Stats...  
[22:04:53.477] [5] [ Info] [Eco] Initializing skills...  
[22:04:53.534] [5] [ Info] [Eco] Loading World...  
[22:05:01.757] [5] [ Info] [Eco] Initializing world...  
[22:05:01.962] [5] [ Info] [Eco] Starting WorldPlugin...  
[22:05:01.966] [5] [ Info] [Eco] Loading Time...  
[22:05:01.966] [5] [ Info] [Eco] Starting TimePlugin...  
[22:05:01.966] [5] [ Info] [Eco] Loading Reputation...  
[22:05:01.988] [5] [ Info] [Eco] Starting ReputationPlugin...  
[22:05:01.988] [5] [ Info] [Eco] Starting PlayerHousingManager...  
[22:05:02.030] [5] [ Info] [Eco] Loading Users...  
[22:05:03.133] [5] [ Info] [Eco] Initializing inventories...  
[22:05:03.164] [5] [ Info] [Eco] Starting UserManager...  
[22:05:03.180] [5] [ Info] [Eco] Loading Objects...  
[22:05:03.395] [5] [ Info] [Eco] Starting EcoObjectManager...  
[22:05:03.395] [5] [ Info] [Eco] Starting DataExporter...  
[22:05:03.395] [5] [ Info] [Eco] Loading Garbage...  
[22:05:03.403] [5] [ Info] [Eco] Starting VoiceManager...  
[22:05:03.403] [5] [ Info] [Eco] Starting GarbagePlugin...  
[22:05:03.403] [5] [ Info] [Eco] Loading EconomyManager...  
[22:05:03.637] [5] [ Info] [Eco] Starting EconomyPlugin...  
[22:05:03.637] [5] [ Info] [Eco] Loading Disasters...  
[22:05:03.637] [5] [ Info] [Eco] Starting DisasterPlugin...  
[22:05:03.637] [5] [ Info] [Eco] Loading ViewTypeData...  
[22:05:03.674] [5] [ Info] [Eco] Loading Chat...  
[22:05:06.133] [5] [ Info] [Eco] Starting ControllerManager...  
[22:05:10.122] [5] [ Info] [Eco] Starting ChatServer...  
[22:05:10.122] [5] [ Info] [Eco] Loading Property...  
[22:05:11.287] [5] [ Info] [Eco] Starting PropertyManager...  
[22:05:11.287] [5] [ Info] [Eco] Starting MinimapManager...  
[22:05:11.349] [5] [ Info] [Eco] Loading Plants...  
[22:05:12.403] [5] [ Info] [Eco] Initializing plants...  
[22:05:18.865] [5] [ Info] [Eco] Starting EcoSim...  
[22:05:18.865] [5] [ Info] [Eco] Loading RouteProbing...  
[22:05:21.316] [5] [ Info] [Eco] Starting RouteProbingPlugin...  
[22:05:21.316] [5] [ Info] [Eco] Loading Layers...  
[22:05:21.684] [5] [ Info] [Eco] Initializing world layers...  
[22:05:21.687] [5] [ Info] [Eco] Loading ClimateSim...  
[22:05:27.153] [5] [ Info] [Eco] Starting WorldLayerManager...  
[22:05:27.153] [5] [ Info] [Eco] Starting EconomyTracker...  
[22:05:27.153] [5] [ Info] [Eco] Starting UserTracker...  
[22:05:27.178] [5] [ Info] [Eco] Loading Civics...  
[22:05:27.242] [5] [ Info] [Eco] Starting CivicsPlugin...  
[22:05:27.588] [5] [ Info] [Eco] Loading WorldObjects...  
[22:05:28.179] [5] [ Info] [Eco] Starting WorldObjectManager...  
[22:05:28.179] [5] [ Info] [Eco] Loading Rooms...  
[22:05:28.192] [5] [ Info] [Eco] Starting RoomPlugin...  
[22:05:28.209] [5] [ Info] [Eco] Loading Objectives...  
[22:05:28.209] [5] [ Info] [Eco] Starting ObjectivePlugin...  
[22:05:28.209] [5] [ Info] [Eco] Loading Sleep...  
[22:05:28.217] [5] [ Info] [Eco] Starting SleepPlugin...  
[22:05:28.217] [5] [ Info] [Eco] Starting WebServerPlugin...  
[22:05:28.217] [5] [ Info] [Eco] Starting ExtendedUser...  
[22:05:28.217] [5] [ Info] [Eco] Starting IntegrationTestsPlugin...  
[22:05:28.259] [5] [ Info] [Eco] Initializing registrars for CivicsPlugin...  
[22:05:28.301] [5] [ Info] [Eco] Initializing registrars for GameDataPlugin...  
[22:05:28.313] [5] [ Info] [Eco] Initializing registrars for EconomyPlugin...  
[22:05:28.390] [35] [Error] [Eco] Enumerable deserialization error. Missing reference for element: Eco.Gameplay.Players.User:494. It will be ignored, but may cause inconsistency and errors in other entities.
 
[22:05:28.448] [35] [Error] [Eco] Enumerable deserialization error. Missing reference for element: Eco.Gameplay.Items.WorkOrder:19726. It will be ignored, but may cause inconsistency and errors in other entities.
 
[22:05:30.314] [5] [ Info] [Eco] Initializing DifficultySettings...  
[22:05:30.314] [5] [ Info] [Eco] Initializing Stats...  
[22:05:30.478] [5] [ Info] [Eco] Initializing CivicsPlugin...  
[22:05:30.503] [35] [Error] [Eco] Contract 4 hosted by Contract Board, but host didn't list it.  Added to host.
 
[22:05:30.503] [5] [ Info] [Eco] Initializing PerformancePlugin...  
[22:05:30.503] [5] [ Info] [Eco] Initializing LocalizationPlugin...  
[22:05:30.589] [5] [ Info] [Eco] Initializing ModKitPlugin...  
[22:05:31.036] [5] [ Info] [Eco] Initializing WorldGeneratorPlugin...  
[22:05:31.036] [5] [ Info] [Eco] Initializing TimePlugin...  
[22:05:31.036] [5] [ Info] [Eco] Initializing UserManager...  
[22:05:31.254] [5] [ Info] [Eco] Initializing GarbagePlugin...  
[22:05:31.267] [5] [ Info] [Eco] Initializing EconomyPlugin...  
[22:05:31.267] [5] [ Info] [Eco] [Server Initialization]... Finished in 50,024.8ms
 
[22:05:31.279] [35] [Error] [Eco] Failed to load server, Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.BankAccountManager.<>c.<Initialize>b__20_1(PersonalAccount x)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Eco.Gameplay.Economy.BankAccountManager.Initialize()
   at Eco.Gameplay.Economy.EconomyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync()
   at Eco.Server.Startup.StartAsync()
 
[22:05:36.288] [1] [Error] [Eco] Unhandled errorSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.BankAccountManager.<>c.<Initialize>b__20_1(PersonalAccount x)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Eco.Gameplay.Economy.BankAccountManager.Initialize()
   at Eco.Gameplay.Economy.EconomyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync()
   at Eco.Server.Startup.StartAsync()
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
```

**Comment by D3nnis3n** [comment]
Save: https://drive.google.com/file/d/1alS2n5vYPharnpatTUsZRda1Adg_FfPP/view?usp=sharing

**Comment by beastyn** [comment]
#18326 can be related and helpful

**Comment by Quadbro** [comment]
Can't even analyze it properly, have some issues with dumps opening, etc

**Comment by johnkslg** [comment]
Calling in air support @mirasrael

**Comment by mirasrael** [comment]
Did we see this issue in last few weeks?

**Comment by D3nnis3n** [comment]
Yes.

Alexander Bondarev <notifications@github.com> schrieb am Do., 8. Okt. 2020,
13:01:

**Comment by mirasrael** [comment]
After few days of downloading and crashing my system during dump opening I finally was able to investigate the dump file :)
And issue related to way how .NET works with Large Object Heap (LOH). Unlike GC heaps it never makes unforced compaction what causes high memory fragmentation (like 99%):
![image](https://user-images.githubusercontent.com/475445/95742112-2b8aa180-0c98-11eb-9edc-63e6d78e3b89.png)

So only 1% of allocated LOH used. In total application only uses like 6Gb of memory while allocated ~57Gb.
