### ISSUE TITLE
Server Crash on startup

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18238]
```
[14:19:55.358] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[14:19:55.390] [1] [ Info] [Eco] [Eco Server 0.9.0.1 beta]
 
[14:19:55.465] [5] [ Info] [Eco] [Starting [PerformancePlugin]]...  
[14:19:55.465] [5] [ Info] [Eco] [Starting [PerformancePlugin]]... [Finished in 0.6ms]
 
[14:19:55.465] [5] [ Info] [Eco] [Server Initialization]...  
[14:19:56.060] [5] [ Info] [Eco] Starting LocalizationPlugin...  
[14:19:56.060] [5] [ Info] [Eco] Starting LocalizationPlugin... Finished in 0.4ms
 
[14:19:56.139] [5] [ Info] [Eco] Starting DifficultySettings...  
[14:19:56.139] [5] [ Info] [Eco] Starting DifficultySettings... Finished in 0.0ms
 
[14:19:56.139] [5] [ Info] [Eco] Loading mods...  
[14:20:08.355] [1] [ Info] [Eco] Mods recompiled with warnings.
 
[14:20:08.379] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[14:20:08.438] [1] [ Info] [Eco] Loading em-flagpack...
 
[14:20:08.488] [5] [ Info] [Eco] Loading mods... Finished in 12,341.2ms
 
[14:20:08.488] [5] [ Info] [Eco] [Server Initialization]... Finished in 13,023.4ms
 
[14:20:08.524] [1] [Error] [Eco] Unhandled errorSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Plugins.Networking.NetworkManager.get_Config()
   at Eco.Server.Startup.SendIpc(String ipcMessage, Exception exception)
   at Eco.Server.Startup.StartAsync()
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
```

**Comment by beastyn** [comment]
@D3nnis3n please more information.
PC spec + OS
Is it new server or loading save
From client or folder

**Comment by redwyre** [comment]
That does not look like it's properly starting up, and since mods aren't supported...

**Comment by SlayksWood** [comment]
Closed for now.
