### ISSUE TITLE
Selecting Gift Box crashes server

### ISSUE THREAD

**Issue by Shoe73** [StrangeLoopGames/EcoIssues#18236]
A member of ours tried to select a gift box from the store to purchase and it crashed the server.

Several items that have the fuzzy icon all say the same thing.  

Here is the error log..

[23:16:56.094] [11] [Error] [Eco] System.AggregateException: One or more errors occurred. (Can't encode instance of type 'Eco.EM.Items.GiftItem')

System.InvalidOperationException: Can't encode instance of type 'Eco.EM.Items.GiftItem'
   at Eco.Core.Serialization.Serializers.NullClassSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.SimpleSerializer.SerializeTo(Stream stream, Object obj)
   at Eco.Core.Serialization.PersistenceManager.Persist(ContentAccessor& contentAccessor, IStorage storage)
   at Eco.Core.Serialization.PersistenceManager.ApplyChanges(ContentAccessor& contentAccessor)
   at Eco.Core.Serialization.DataStore.ContentAccessor.ExecuteAsync(ExclusiveAccess exclusiveAccess, DataStoreContentAccessorDelegate action)
   at Eco.Core.Serialization.PersistenceManager.PersistAllAsync(ExclusiveAccess exclusiveAccess, Boolean forceFlush)
   at Eco.Core.Plugins.StorageManager.PersistAsync(Boolean forceFlush)
   at Eco.Core.Utils.Threading.IntervalActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)

![image](https://user-images.githubusercontent.com/4332815/93040991-5d690380-f619-11ea-8838-729c10aa4f64.png)

**Comment by Shoe73** [comment]
Forget it, it was a mod causing it.

**Comment by Shoe73** [comment]
I take that back, took off the few mods that I had and it is STILL crashing the server.

**Comment by Shoe73** [comment]
Take that back a 2nd time, it was a mod.
