### ISSUE TITLE
Wage payment error seems to cause server crash

### ISSUE THREAD

**Issue by 0600Zulu** [StrangeLoopGames/EcoIssues#18244]
Version 0.9.0.1, no mods.

The server crashed shortly after implementing new demographics groups ('poor' and 'wealthy'). Poor was when someone has <50 currency, they are paid 5/hour in wage. Wealthy is when they have > 0.2*circulation they get paid -5/hour in wage. The server cannot start up now without an immediate crash. I can't decipher the log, but it seems to reference demographics and wages.

`[13:34:10.501] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[13:34:10.515] [1] [ Info] [Eco] [Eco Server 0.9.0.1 beta]
 
[13:34:10.543] [5] [ Info] [Eco] [Starting [PerformancePlugin]]...  
[13:34:10.543] [5] [ Info] [Eco] [Server Initialization]...  
[13:34:10.837] [5] [ Info] [Eco] Starting LocalizationPlugin...  
[13:34:10.857] [5] [ Info] [Eco] Starting DifficultySettings...  
[13:34:10.857] [5] [ Info] [Eco] Loading mods...  
[13:34:17.838] [1] [ Info] [Eco] Mods recompiled with warnings.
 
[13:34:17.851] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[13:34:17.886] [5] [ Info] [Eco] Loading mods... Finished in 7,025.7ms
 
[13:34:17.886] [5] [ Info] [Eco] Starting ModKitPlugin...  
[13:34:17.886] [5] [ Info] [Eco] Initializing Simulation Types...  
[13:34:17.916] [5] [ Info] [Eco] Starting NetworkManager...  
[13:34:17.945] [5] [ Info] [Eco] Starting BackupPlugin...  
[13:34:18.385] [5] [ Info] [Eco] Starting WorldGeneratorPlugin...  
[13:34:18.435] [5] [ Info] [Eco] Initializing items...  
[13:34:20.510] [5] [ Info] [Eco] Starting StorageManager...  
[13:34:20.510] [5] [ Info] [Eco] Loading GameData...  
[13:34:20.541] [5] [ Info] [Eco] Starting GameDataPlugin...  
[13:34:20.541] [5] [ Info] [Eco] Loading Pause...  
[13:34:20.571] [5] [ Info] [Eco] Starting Stats...  
[13:34:20.571] [5] [ Info] [Eco] Starting PausePlugin...  
[13:34:22.221] [5] [ Info] [Eco] Initializing skills...  
[13:34:22.282] [5] [ Info] [Eco] Loading World...  
[13:34:25.815] [5] [ Info] [Eco] Initializing world...  
[13:34:28.218] [5] [ Info] [Eco] Starting WorldPlugin...  
[13:34:28.218] [5] [ Info] [Eco] Loading Time...  
[13:34:28.218] [5] [ Info] [Eco] Starting TimePlugin...  
[13:34:28.218] [5] [ Info] [Eco] Loading Reputation...  
[13:34:28.218] [5] [ Info] [Eco] Starting ReputationPlugin...  
[13:34:28.218] [5] [ Info] [Eco] Starting PlayerHousingManager...  
[13:34:28.261] [5] [ Info] [Eco] Loading Users...  
[13:34:28.356] [5] [ Info] [Eco] Initializing inventories...  
[13:34:28.392] [5] [ Info] [Eco] Starting UserManager...  
[13:34:28.392] [5] [ Info] [Eco] Loading Objects...  
[13:34:28.423] [5] [ Info] [Eco] Starting EcoObjectManager...  
[13:34:28.423] [5] [ Info] [Eco] Starting DataExporter...  
[13:34:28.423] [5] [ Info] [Eco] Loading Garbage...  
[13:34:28.429] [5] [ Info] [Eco] Starting VoiceManager...  
[13:34:28.429] [5] [ Info] [Eco] Starting GarbagePlugin...  
[13:34:28.429] [5] [ Info] [Eco] Loading EconomyManager...  
[13:34:28.548] [5] [ Info] [Eco] Starting EconomyPlugin...  
[13:34:28.548] [5] [ Info] [Eco] Loading Disasters...  
[13:34:28.554] [5] [ Info] [Eco] Loading ViewTypeData...  
[13:34:28.554] [5] [ Info] [Eco] Starting DisasterPlugin...  
[13:34:28.554] [5] [ Info] [Eco] Loading Chat...  
[13:34:29.088] [5] [ Info] [Eco] Starting ChatServer...  
[13:34:29.088] [5] [ Info] [Eco] Loading Property...  
[13:34:29.120] [5] [ Info] [Eco] Starting PropertyManager...  
[13:34:29.120] [5] [ Info] [Eco] Starting MinimapManager...  
[13:34:29.160] [5] [ Info] [Eco] Loading Plants...  
[13:34:30.985] [5] [ Info] [Eco] Initializing plants...  
[13:34:40.250] [5] [ Info] [Eco] Starting ControllerManager...  
[13:34:40.655] [5] [ Info] [Eco] Starting EcoSim...  
[13:34:40.655] [5] [ Info] [Eco] Loading RouteProbing...  
[13:34:42.623] [5] [ Info] [Eco] Starting RouteProbingPlugin...  
[13:34:42.623] [5] [ Info] [Eco] Loading Layers...  
[13:34:43.130] [5] [ Info] [Eco] Initializing world layers...  
[13:34:43.131] [5] [ Info] [Eco] Loading ClimateSim...  
[13:34:51.412] [5] [ Info] [Eco] Starting WorldLayerManager...  
[13:34:51.412] [5] [ Info] [Eco] Starting EconomyTracker...  
[13:34:51.412] [5] [ Info] [Eco] Starting UserTracker...  
[13:34:51.430] [5] [ Info] [Eco] Loading Civics...  
[13:34:51.471] [5] [ Info] [Eco] Starting CivicsPlugin...  
[13:34:51.564] [5] [ Info] [Eco] Loading WorldObjects...  
[13:34:51.634] [5] [ Info] [Eco] Starting WorldObjectManager...  
[13:34:51.634] [5] [ Info] [Eco] Loading Rooms...  
[13:34:51.634] [5] [ Info] [Eco] Starting RoomPlugin...  
[13:34:51.634] [5] [ Info] [Eco] Loading Objectives...  
[13:34:51.634] [5] [ Info] [Eco] Starting ObjectivePlugin...  
[13:34:51.634] [5] [ Info] [Eco] Loading Sleep...  
[13:34:51.647] [5] [ Info] [Eco] Starting SleepPlugin...  
[13:34:51.647] [5] [ Info] [Eco] Starting WebServerPlugin...  
[13:34:51.647] [5] [ Info] [Eco] Starting IntegrationTestsPlugin...  
[13:34:51.675] [5] [ Info] [Eco] Initializing registrars for CivicsPlugin...  
[13:34:51.710] [5] [ Info] [Eco] Initializing registrars for GameDataPlugin...  
[13:34:51.710] [5] [ Info] [Eco] Initializing registrars for EconomyPlugin...  
[13:34:54.680] [5] [ Info] [Eco] Initializing DifficultySettings...  
[13:34:54.680] [5] [ Info] [Eco] Initializing Stats...  
[13:34:54.818] [5] [ Info] [Eco] Initializing CivicsPlugin...  
[13:34:54.839] [5] [ Info] [Eco] Initializing PerformancePlugin...  
[13:34:54.839] [5] [ Info] [Eco] Initializing LocalizationPlugin...  
[13:34:54.900] [5] [ Info] [Eco] Initializing ModKitPlugin...  
[13:34:55.284] [5] [ Info] [Eco] Initializing WorldGeneratorPlugin...  
[13:34:55.284] [5] [ Info] [Eco] Initializing TimePlugin...  
[13:34:55.284] [5] [ Info] [Eco] Initializing UserManager...  
[13:34:55.433] [5] [ Info] [Eco] Initializing GarbagePlugin...  
[13:34:55.433] [5] [ Info] [Eco] Initializing EconomyPlugin...  
[13:34:55.433] [5] [ Info] [Eco] Initializing PropertyManager...  
[13:34:55.454] [5] [ Info] [Eco] Initializing MinimapManager...  
[13:34:55.749] [5] [ Info] [Eco] Initializing EcoSim...  
[13:34:55.749] [5] [ Info] [Eco] Initializing UserTracker...  
[13:34:55.749] [5] [ Info] [Eco] Initializing WorldObjectManager...  
[13:34:56.413] [5] [ Info] [Eco] Initializing RoomPlugin...  
[13:34:56.540] [5] [ Info] [Eco] Initializing SleepPlugin...  
[13:34:56.540] [5] [ Info] [Eco] Initializing WorldPlugin...  
[13:34:56.540] [5] [ Info] [Eco] Ticking Active Chunks...  
[13:34:56.945] [5] [ Info] [Eco] Compressing Frozen Chunks...  
[13:35:03.140] [5] [ Info] [Eco] Initializing NetworkManager...  
[13:35:03.514] [5] [ Info] [Eco] Initializing WorldLayerManager...  
[13:35:03.514] [5] [ Info] [Eco] Initializing WebServerPlugin...  
[13:35:04.131] [19] [ Info] [Eco] Web Server now listening on: http://[::]:3001
 
[13:35:04.133] [5] [ Info] [Eco] Initializing IntegrationTestsPlugin...  
[13:35:04.620] [5] [ Info] [Eco] Saving world...  
[13:35:04.855] [19] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.Values.MembershipRequirements.Value(IContextObject action)
   at Eco.Gameplay.Civics.GameValues.SetOfConditions.Value(IContextObject action)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.Law.Perform(GameAction action)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Economy.Transfers.TryTransferWithTaxSeparate(GameActionPack pack, TransferType reason, BankAccount sourceAccount, BankAccount targetAccount, Currency currency, User source, User target, LocString description, LocString taxReason, Boolean notify, Single amount, Single taxRate, Single sourceTaxAmount, Single targetTaxAmount, Boolean verify, Boolean autoPerform, Boolean superAccess, Boolean transferAsMuchAsPossible)
   at Eco.Gameplay.Economy.Transfers.TryTransferWithTaxIncluded(GameActionPack pack, TransferType reason, BankAccount sourceAccount, BankAccount targetAccount, Currency currency, User source, User target, LocString description, LocString taxReason, Boolean notify, Single totalAmount, Single taxRate, Boolean verify, Boolean autoPerform, Boolean superAccess)
   at Eco.Gameplay.Economy.Jobs.Wage.PayUser(IWageEarningGroup group, User user, Double time, Double activeTime, Double curTime)
   at Eco.Gameplay.Economy.Jobs.Wage.Pay(IWageEarningGroup group, Double activeTime, User user)
   at Eco.Gameplay.Economy.Jobs.WageManager.<>c__DisplayClass13_0.<MembershipChanged>b__0(Wage wage)
   at System.Linq.Enumerable.SelectIListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Economy.Jobs.WageManager.MembershipChanged(User user, Boolean added, IWageEarningGroup group)
   at Eco.Gameplay.Economy.Jobs.WageManager.<>c__DisplayClass11_0.<Register>b__2(User user, Boolean added)
   at Eco.Core.Utils.ThreadSafeAction`2.Invoke(T1 t1, T2 t2)
   at Eco.Gameplay.Civics.Titles.Membership.Sync(IEnumerable`1 users)
   at Eco.Gameplay.Civics.Demographics.Demographic.CacheUsers()
   at Eco.Gameplay.Civics.Demographics.DemographicManager.DoDemographicUpdate(Demographic limitToDemographic, Boolean suppressChangeNotice)
   at Eco.Gameplay.Civics.Demographics.DemographicManager.Tick()
   at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[13:35:24.940] [37] [ Info] [Eco] No UPnP device with public ip was found
 
[13:35:29.014] [5] [ Info] [Eco] [Server Initialization]... Finished in 78,469.8ms
 
[13:35:29.022] [5] [ Info] [Eco] Saving...  
[13:35:36.081] [37] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.Values.MembershipRequirements.Value(IContextObject action)
   at Eco.Gameplay.Civics.GameValues.SetOfConditions.Value(IContextObject action)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.Law.Perform(GameAction action)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Economy.Transfers.TryTransferWithTaxSeparate(GameActionPack pack, TransferType reason, BankAccount sourceAccount, BankAccount targetAccount, Currency currency, User source, User target, LocString description, LocString taxReason, Boolean notify, Single amount, Single taxRate, Single sourceTaxAmount, Single targetTaxAmount, Boolean verify, Boolean autoPerform, Boolean superAccess, Boolean transferAsMuchAsPossible)
   at Eco.Gameplay.Economy.Transfers.TryTransferWithTaxIncluded(GameActionPack pack, TransferType reason, BankAccount sourceAccount, BankAccount targetAccount, Currency currency, User source, User target, LocString description, LocString taxReason, Boolean notify, Single totalAmount, Single taxRate, Boolean verify, Boolean autoPerform, Boolean superAccess)
   at Eco.Gameplay.Economy.Jobs.Wage.PayUser(IWageEarningGroup group, User user, Double time, Double activeTime, Double curTime)
   at Eco.Gameplay.Economy.Jobs.Wage.Pay(IWageEarningGroup group, Double activeTime, User user)
   at Eco.Gameplay.Economy.Jobs.WageManager.<>c__DisplayClass13_0.<MembershipChanged>b__0(Wage wage)
   at System.Linq.Enumerable.SelectIListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Economy.Jobs.WageManager.MembershipChanged(User user, Boolean added, IWageEarningGroup group)
   at Eco.Gameplay.Economy.Jobs.WageManager.<>c__DisplayClass11_0.<Register>b__2(User user, Boolean added)
   at Eco.Core.Utils.ThreadSafeAction`2.Invoke(T1 t1, T2 t2)
   at Eco.Gameplay.Civics.Titles.Membership.Sync(IEnumerable`1 users)
   at Eco.Gameplay.Civics.Demographics.Demographic.CacheUsers()
   at Eco.Gameplay.Civics.Demographics.DemographicManager.DoDemographicUpdate(Demographic limitToDemographic, Boolean suppressChangeNotice)
   at Eco.Gameplay.Civics.Demographics.DemographicManager.Tick()
   at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Civics.CivicsPlugin.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__37_0(PluginRegistration reg)
 
[13:35:39.962] [37] [ Info] [Eco] Shutdown finished`

**Comment by beastyn** [comment]
@0600Zulu Thank you for the report. Is there a way to get screenshot with demographic logic?

**Comment by 0600Zulu** [comment]
Here is what the logic looks like:
![image](https://user-images.githubusercontent.com/26182839/93218101-7663d880-f72f-11ea-821c-2cce3fdae4f3.png)

**Comment by SlayksWood** [comment]
@0600Zulu I can't see any screensots in your comment.
![image](https://user-images.githubusercontent.com/45708377/93989015-105ffc80-fd92-11ea-9a0f-187c7534a8fa.png)

**Comment by SlayksWood** [comment]
@0600Zulu Can you provide save file? I still can't reproduce it. You can provide corrupted file and backup too
Instruction is here
https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by beastyn** [comment]
@0600Zulu and also a screenshot for the second demographic, Thanks )

**Comment by 0600Zulu** [comment]
Unfortunately the save game from this incident got cleaned up during the normal backup process. I *think* I saved a backup of just the bad save (I did a lot of backing up, saving, reloading, so hopefully the linked files are from the bad save - the files have 'old' appended to the extension). [google drive folder](https://drive.google.com/drive/folders/1WlhcnYt3XrLdM9oFyjKgVlAS3TOGkX38?usp=sharing)

I was able to get around the error by going back to a save right before the demographics went into effect, deleting them, and putting in new demographics without the wage. The server worked fine after just removing wages from the demographics. The other demographic was similar to this one, except the arithmetic was 'poor' if they had less than 50 GBD, and it paid them a wage of 5.

**Comment by Dahsnorf** [comment]
Having the same issue with 9.2.4-156 Server crash after demographic that pays a recurring wage. we dont have a backup to load :(
