### ISSUE TITLE
Server Crash on Reboot

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#18276]
```
--BEGIN DUMP--
Dump Time
09/15/2020 20:15:23

Exception
Exception: ArgumentOutOfRangeException
Message:Specified argument was out of the range of valid values. (Parameter 'arrayIndex')
Source:System.Collections.Immutable

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'arrayIndex')
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Immutable.ImmutableList`1.CopyTo(T[] array, Int32 arrayIndex)
   at Eco.Core.Utils.ThreadSafeList`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Eco.Core.Utils.ControllerList`1.RemoveAll(Predicate`1 predicate)
   at Eco.Gameplay.Players.WorldMarkerManager.UpdateGroupPartMarkers()
   at Eco.Gameplay.Players.WorldMarkerManager.SetGroupPartMarker(Guid id, Vector3i pos, String category, IEnumerable`1 items, String text, Boolean displayOffScreen)
   at Eco.Gameplay.Players.GroupMarker.UpdateMarkerForUser(User user)
   at Eco.Gameplay.Players.GroupMarker.AddUser(User user, Boolean notify)
   at Eco.Gameplay.Utils.ItemTracker.AddToGroupMarker(User user)
   at Eco.Gameplay.Components.ItemDistributionComponent.UpdateTrackerForUser(User user)
   at Eco.Gameplay.Components.ItemDistributionComponent.UpdateTrackers()
   at Eco.Gameplay.Components.ItemDistributionComponent.ApplyInternal(User executor)
   at Eco.Gameplay.Components.ItemDistributionComponent.Initialize()
   at Eco.Gameplay.Objects.WorldObject.<>c.<InitializeComponents>b__212_0(WorldObjectComponent x)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.InitializeComponents()
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass17_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__1(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()

--END DUMP--
```

**Comment by SlayksWood** [comment]
@Sekor2600 Does server start on second try? Today I have this issue. Yesterday I take one of live server (which I play ) to test plant behavior during migration from 9.0.3 to 9.0.4. It was fine yesterday, but today when I started it, server were crashed:

Everything went fine on second restart.
Save(use slg mail): https://drive.google.com/file/d/1MeyBY19IiXLYeDIldD4Ff-5mtNq_AAPm/view?usp=sharing

**Comment by Sekor2600** [comment]
@SlayksWood yeah with 2nd reboot all is normal
