### ISSUE TITLE
[9.0.1] Server crash "System.InvalidOperationException: Sequence contains no elements"

### ISSUE THREAD

**Issue by ky0uraku** [StrangeLoopGames/EcoIssues#18288]
9.0.1, Linux, day 7.

```
[11:18:14] System.AggregateException: One or more errors occurred. (Sequence contains no elements)

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Min(IEnumerable`1 source)
   at Eco.Gameplay.Items.DecayingInventory.NextUpdateWorldTime() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Items\TrashInventory.cs:line 205
   at Eco.Gameplay.Items.DecayingInventory.Tick() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Items\TrashInventory.cs:line 276
   at Eco.Simulation.Simulation.TickAll() in C:\Jenkins\workspace\Eco Release\Server\Eco.Simulation\Simulation.cs:line 47
   at Eco.Gameplay.Garbage.GarbageManager.Tick() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Garbage\GarbageManager.cs:line 115
   at Eco.Gameplay.Garbage.GarbagePlugin.Tick() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Garbage\GarbageManager.cs:line 41
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Utils\Threading\EventDrivenWorker.cs:line 60
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Utils\Threading\EventDrivenWorker.cs:line 69
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Utils\Threading\RepeatableWorkerBase.cs:line 23
[11:18:14] Saving... 
[11:18:20] Saving... Finished in 6,608.2ms
[11:18:20] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Min(IEnumerable`1 source)
   at Eco.Gameplay.Items.DecayingInventory.NextUpdateWorldTime() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Items\TrashInventory.cs:line 205
   at Eco.Gameplay.Items.DecayingInventory.Tick() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Items\TrashInventory.cs:line 276
   at Eco.Simulation.Simulation.TickAll() in C:\Jenkins\workspace\Eco Release\Server\Eco.Simulation\Simulation.cs:line 47
   at Eco.Gameplay.Garbage.GarbageManager.Tick() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Garbage\GarbageManager.cs:line 115
   at Eco.Gameplay.Garbage.GarbagePlugin.Tick() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Garbage\GarbageManager.cs:line 41
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Utils\Threading\EventDrivenWorker.cs:line 60
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Utils\Threading\EventDrivenWorker.cs:line 69
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Utils\Threading\RepeatableWorkerBase.cs:line 23
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync() in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Utils\Threading\WorkerBase.cs:line 45
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Utils\Threading\WorkerExtensions.cs:line 8
   at Eco.Gameplay.Garbage.GarbagePlugin.Shutdown() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Garbage\GarbageManager.cs:line 35
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\PluginManager.cs:line 293
[11:18:22] Shutdown finished
```

**Comment by beastyn** [comment]
@ky0uraku Thank you for the report.
Did you try to launch a save or catch with some conditions?

**Comment by ky0uraku** [comment]
@beastyn Yes, the last save was successfully launched, since then no errors has not appeared. Conditions are unknown.

**Comment by beastyn** [comment]
@ky0uraku thanks for the details. It would be good to have a backup save from before restarting with the craash (can use my e-mail for the save anna@strangeloopgames.com)

**Comment by SlayksWood** [comment]
seems fixed with https://github.com/StrangeLoopGames/Eco/pull/6441
There is one nuance that the issue was created after the fixes. But if before that we have a couple of such crashes, then after fixes only one. So closed for now.
