### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Kaerius** [StrangeLoopGames/EcoIssues#18363]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidOperationException
Message:Collection was modified; enumeration operation may not execute.
Source:System.Private.CoreLib

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client, Boolean doAllParams)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.GetChanges(IMvcNetClient client)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #18361
