### ISSUE TITLE
USER ISSUE: connexion au serveur français

### ISSUE THREAD

**Issue by SouSSouS16** [StrangeLoopGames/EcoIssues#18366]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
quand on essaie de se connecter pour la première fois à un serveur en langue French, impossible, un message d'erreur apparait.

**Expected behavior:**
connexion au serveur pour créer son personnage

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.BankAccountManager.TryCreateUserAccount(User user)
   at Eco.Gameplay.Players.User.Initialize()
   at Eco.Core.Systems.Registrar.Insert(IHasID newObj, INetObject netObj)
   at Eco.Gameplay.Players.UserManager.PrepareNewUser(String steamId, String slgId, String username)
   at Eco.Gameplay.Players.UserManager.GetOrCreateUser(String steamId, String slgId, String username)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
pas de mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by baguette-deluxe** [comment]
Salut, le souci va être résolu pour la 9.0.3 normalement

https://github.com/StrangeLoopGames/EcoIssues/issues/18326
