### ISSUE TITLE
9.0.3 All work order/processing etc stopped

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18545]
All processing of stone being grabbed by stamp mills, moving items between stockpiles and items being grabbed by tables seemed to stop, this seemed to be same as the pipes issue but the single user with a waste filter had not been online for 18 hours.

This happened at 12:20 ish BST, so all times are in BST, was running fine 30min before was only a few users online

[12:28] BOT SnepServECO1: Mishka:hmm
[12:28] BOT SnepServECO1: Mishka:i think something has crashed
[12:28] BOT SnepServECO1: Mishka:orders arent running
[12:29] BOT SnepServECO1: Mishka:Arnike you here?
[12:29] BOT SnepServECO1: Arnike:time to server restart?
[12:29] BOT SnepServECO1: Mishka:No i think i know what it might be
[12:29] BOT SnepServECO1: alexanderrievert02:ya mine arent either i think im out wood though
[12:29] BOT SnepServECO1: Mishka:Did you place some pipes recently
[12:29] BOT SnepServECO1: Arnike:here, in half eye)
[12:29] BOT SnepServECO1: Arnike:nope

Server log/window showed the below at approx the "right" time for the problem, the myself teleporting was me locating the single waste filter on the server to see if it was that, server was restarted and been running finr for 2 hours now.

![image](https://user-images.githubusercontent.com/61889138/94817313-cbbd0c80-03f4-11eb-9873-9db58d0a7022.png)

Log file below, some info removed for security

[11:53:35.485] [68] [Debug] [Eco] Nat punch received from  with token = 
[12:21:06.482] [178] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.RequireRoomContainmentAttribute.IsMet(RoomStats roomStats, User owner)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Components.RoomRequirementsComponent.CheckRoom()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[12:21:06.539] [5] [ Info] [Eco] Saving...  
[12:22:55.582] [68] [Debug] [Eco] Nat introduction received with token = 
[12:22:55.606] [68] [Debug] [Eco] Nat punch received from 9 with token =
[12:30:05.536] [87] [ Info] [log] Mishka invoked admin command '/fly' 
[12:30:26.328] [87] [ Info] [log] Mishka invoked admin command '/tp 1636,1595' 
[12:30:46.250] [87] [ Info] [log] Mishka invoked admin command '/tp 1636,2595' 
[12:32:41.391] [87] [ Info] [log] Mishka invoked admin command '/manage save'

**Comment by beastyn** [comment]
@MishkaFur can you provide .eco before this has happened?
Any news about waste filter or other loops?

**Comment by MishkaFur** [comment]
Only one waste filter existed on the server, it was not the cause of this as player had not been on for 18 hours and no loop, no other loops were created. server was restarted and then behaved without issue

Files were sent to Grigoriy as per GM chat briefly with him yesterday 22:30 BST

https://drive.google.com/drive/folders/1GCYcR-ayaja53qkKuv-QfWXKxvVoUsJ_

This has both, one from just before it (10min) and one after which was running finew and server has been running fine since so 16 hours

**Comment by beastyn** [comment]
Its not a loop, but still tick problem. So i's for @mirasrael 
Thanks for the save!

**Comment by mirasrael** [comment]
@MishkaFur does save fail every time or it only failed one time?

**Comment by MishkaFur** [comment]
It only failed once and after the restart it has been fine for now 27 hours, I think it was related to the error message.

Could it be whilst the server was trying to save it did not process any ticks despite server still being online and connectable for 10min?

**Comment by mirasrael** [comment]
I assume I fixed issue. It was related to multi-threading (when one thread changed state of another thread while it was still in progress).

**Comment by mirasrael** [comment]
So I just confirmed that it happens randomly, because it usually signals about thread-safety issues.
