### ISSUE TITLE
Game will not load from save file: "Error inserting stat of type ItemCraftedAction into databaseSystem.ArgumentException: An item with the same key has already been added"

### ISSUE THREAD

**Issue by TheSpaceDad** [StrangeLoopGames/EcoIssues#18564]
Keep getting errors when trying to load this save file and previous ones, a copy of latest save and log file is linked below:

https://drive.google.com/file/d/1eAZT1i9KWw28gW-LRtwi8s-DrrT4T-rr/view?usp=sharing

https://pastebin.com/HAFqSvGT

The part of the log that keeps being repeated before shutdown:

`[14:33:51.756] [45] [Error] [Eco] Error inserting stat of type ItemCraftedAction into databaseSystem.ArgumentException: An item with the same key has already been added. Key: 65535 (Parameter 'key')
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at LiteDB.Engine.BasePage.Defrag()
   at LiteDB.Engine.BasePage.InternalInsert(UInt16 bytesLength, Byte& index)
   at LiteDB.Engine.BasePage.Insert(UInt16 bytesLength, Byte& index)
   at LiteDB.Engine.DataPage.InsertBlock(Int32 bytesLength, Boolean extend)
   at LiteDB.Engine.DataService.<>c__DisplayClass3_0.<<Insert>g__source|0>d.MoveNext()
   at LiteDB.Engine.BufferWriter..ctor(IEnumerable`1 source)
   at LiteDB.Engine.DataService.Insert(BsonDocument doc)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.<>c__DisplayClass20_0.<Record>b__0()
   at Eco.Stats.LiteDbService.WithTransaction(Action action, Int32 timeout)
   at Eco.Stats.Stats.Record(IStat obj)`

**Comment by SlayksWood** [comment]
@TheSpaceDad 
You can try to delete .db file (make a backup just in case) and try to start. It would help you.

**Comment by SlayksWood** [comment]
merged to #18472
