### ISSUE TITLE
Exception: Thrown back to MainMenu

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#18589]
```
Server encountered an exception:

<size=60.00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Shared

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Shared.Math.Route.WaypointsAtTime(Single time)
   at Eco.Shared.Pathing.RouteFollower.Position(Single lookAhead)
   at Eco.Shared.Pathing.AITarget.Position(Single timeOffset)
   at Eco.Shared.Networking.NetObjectExtensions.Priority(INetObject netObject, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Client.NetObjectPriorityComparer.Compare(INetObject x, INetObject y)
   at Eco.Shared.Utils.EnumerableExtensions.MinRange[T](IEnumerable`1 enumerable, Int32 n, IComparer`1 comparer)
   at Eco.Shared.Collections.BatchedSet`1.GetNextBatch()
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1()</size>

Log File:
Initialize engine version: 2019.4.9f1 (50fe8a171dd9)
[Subsystems] Discovering subsystems at path E:/SteamLibrary/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1b81)
    Vendor:   
    VRAM:     8088 MB
    Driver:   27.21.14.5655
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.


 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:46:45.240] Missing following objects: AirPollutionGeneratorObject
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<BuildFromModKit>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>d__47:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:46:50.352] Icon does not contain ItemTemplate component, instantiating icon
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
IconUtils:AssignIcon(GameObject, Image)
UI.ItemIconUI:UpdateIcon(Int32)
UI.ItemCollectionUI:OnChange()
UI.InventoryUI:OnChange()
UI.SelectionInventoryUI:OnChange()
UI.InventoryUI:set_Inventory(InventoryView)
ToolbarUI:Init(UserView)
Player:ReceiveInitialState(BSONObject)
System.Action`1:Invoke(T)
NetObjComponent:OnReceiveInitialState(BSONObject)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:HandleNewObject(BSONObject)
ClientPacketHandler:ReceiveWhile(NetworkClient, TimeLimit)
UnityEngine.StateChanged:Invoke(CullingGroupEvent)
FramePlanner.PlannerGroup:OnUpdate()
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
System.Runtime.Remoting.Contexts.CrossContextDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:49:37.113] Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Shared

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Shared.Math.Route.WaypointsAtTime(Single time)
   at Eco.Shared.Pathing.RouteFollower.Position(Single lookAhead)
   at Eco.Shared.Pathing.AITarget.Position(Single timeOffset)
   at Eco.Shared.Networking.NetObjectExtensions.Priority(INetObject netObject, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Client.NetObjectPriorityComparer.Compare(INetObject x, INetObject y)
   at Eco.Shared.Utils.EnumerableExtensions.MinRange[T](IEnumerable`1 enumerable, Int32 n, IComparer`1 comparer)
   at Eco.Shared.Collections.BatchedSet`1.GetNextBatch()
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1()</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, Boolean)
System.Action`2:Invoke(T1, T2)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass59_0:<Initialize>b__0()
Steamworks.RulesRefreshComplete:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.RulesRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)

Unloading 9292 unused Assets to reduce memory usage. Loaded Objects now: 92297.
Total: 440.670500 ms (FindLiveObjects: 11.886100 ms CreateObjectMapping: 7.257500 ms MarkObjects: 392.997900 ms  DeleteObjects: 28.528800 ms)

```

**Comment by SlayksWood** [comment]
should be fixed in 9.1 #18113
