### ISSUE TITLE
Test failure in testplaceobjects

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#18613]
```
[11:36:30] Running test testplaceobjects
[11:36:31] Caught exception when trying to dump a prior exception: The process cannot access the file 'C:\Jenkins\workspace\Eco Test Pipeline\Build\CI_Tests\win-x64\Dump\ServerCrash ArgumentException 10063631.ecodmp' because it is being used by another process.Unhandled exception. Unhandled exception. System.ArgumentException: No network object provided to call RPC on it (Parameter 'obj')
   at Eco.Shared.Networking.RPCManager.DoCall(String methodname, INetObject obj, AwaitedQuery query, INetClient target, Object[] args)
   at Eco.Shared.Networking.RPCManager.Call[T](String methodname, INetObject obj, INetClient target, Action`1 resultCallback, Object[] args)
   at Eco.Shared.Networking.NetObjectExtensions.RPC[T](INetObject netObj, String method, INetClient target, Action`1 callback, Object[] args)
   at Eco.Shared.Networking.NetObjectExtensions.RPCAsync[T](INetObject netObj, String method, INetClient netClient, Object[] args)
   at Eco.Gameplay.Players.Player.ConfirmBox(LocString message)
   at Eco.Gameplay.Civics.Misc.OrphanAssignmentExtensions.AssignOrphans(IOrphanAssignment container, Boolean confirm)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.ArgumentException: No network object provided to call RPC on it (Parameter 'obj')
   at Eco.Shared.Networking.RPCManager.DoCall(String methodname, INetObject obj, AwaitedQuery query, INetClient target, Object[] args)
   at Eco.Shared.Networking.RPCManager.Call[T](String methodname, INetObject obj, INetClient target, Action`1 resultCallback, Object[] args)
   at Eco.Shared.Networking.NetObjectExtensions.RPC[T](INetObject netObj, String method, INetClient target, Action`1 callback, Object[] args)
   at Eco.Shared.Networking.NetObjectExtensions.RPCAsync[T](INetObject netObj, String method, INetClient netClient, Object[] args)
   at Eco.Gameplay.Players.Player.ConfirmBox(LocString message)
   at Eco.Gameplay.Civics.Misc.OrphanAssignmentExtensions.AssignOrphans(IOrphanAssignment container, Boolean confirm)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by gzatravkin** [comment]
Fixed as it can be seen in screenshot
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/1ecc194c-088c-42ee-9490-250b149e12b1)
