### ISSUE TITLE
Server going down in the middle of the night 9.0.3

### ISSUE THREAD

**Issue by dillon-temple** [StrangeLoopGames/EcoIssues#18636]
Only error I can find in the logs.

Also, our "Storage.eco" file keeps resetting randomly back to "SaveFrequency: 1500" which is causing massive rollbacks.

```
[02:46:50.474] [35] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.PropertyValues.AllProperty.<>c__DisplayClass3_0.<Value>b__0(Deed x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Eco.Gameplay.Civics.GameValues.PropertyValues.AllProperty.Value(IContextObject context)
   at Eco.Gameplay.Civics.ChangePropertyOwner_LegalAction.Do(LocString desc, IContextObject context)
   at Eco.Gameplay.Civics.ChangePropertyOwner_LegalAction.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.LegalAction.PerformAndProcessResullt(Law law, GameAction action)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.Law.Perform(GameAction action)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Civics.Demographics.DemographicManager.UpdateDemographicList(IEnumerable`1 demographicsList, Boolean suppressChangeNotice)
   at Eco.Gameplay.Civics.Demographics.DemographicManager.DoDemographicUpdate(Demographic limitToDemographic, Boolean suppressChangeNotice)
   at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[02:46:50.496] [5] [ Info] [Eco] Saving...  
[02:47:13.579] [39] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.PropertyValues.AllProperty.<>c__DisplayClass3_0.<Value>b__0(Deed x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Eco.Gameplay.Civics.GameValues.PropertyValues.AllProperty.Value(IContextObject context)
   at Eco.Gameplay.Civics.ChangePropertyOwner_LegalAction.Do(LocString desc, IContextObject context)
   at Eco.Gameplay.Civics.ChangePropertyOwner_LegalAction.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.LegalAction.PerformAndProcessResullt(Law law, GameAction action)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.Law.Perform(GameAction action)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Civics.Demographics.DemographicManager.UpdateDemographicList(IEnumerable`1 demographicsList, Boolean suppressChangeNotice)
   at Eco.Gameplay.Civics.Demographics.DemographicManager.DoDemographicUpdate(Demographic limitToDemographic, Boolean suppressChangeNotice)
   at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Civics.CivicsPlugin.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__37_0(PluginRegistration reg)
 
[02:47:14.828] [39] [ Info] [Eco] Shutdown finished
```

**Comment by beastyn** [comment]
@dillon-temple Thank you for the report.
Can you provide you . eco file? If it contains private information you can usr my e-mail (anna@strangeloopgames.com)
The reason most likely is in the civics, maybe you have some timer law with unclaiming land. Like this #16568

**Comment by dillon-temple** [comment]
[log_1.log](https://github.com/StrangeLoopGames/EcoIssues/files/5346142/log_1.log)
[log_2.log](https://github.com/StrangeLoopGames/EcoIssues/files/5346143/log_2.log)
[log_websockets.log](https://github.com/StrangeLoopGames/EcoIssues/files/5346144/log_websockets.log)

Here are the errors i've seen in the past couple days.

We also have this law

"Remove Future Inactive Claims
On event Demographic Change where Demographic is Abandoned
Change owner of All property owned by Citizen to unowned
Retroactive Unclaiming
On event Citizen Timer every 12 hours on each person in Abandoned
Change owner of All property owned only by Citizen to unowned"

**Comment by beastyn** [comment]
Yeap, looks like the same issue. I will merge it into #16568 for further investigation.
