### ISSUE TITLE
Server runs out of memory even if more memory is available.

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1870]
--BEGIN DUMP--
Dump Time
08/17/2017 14:06:36

Exception
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable1.InternalPartitionEnumerable..ctor(IEnumerator1 sharedReader, Boolean useSingleChunking, Boolean isStaticPartitioning)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable1.GetOrderableDynamicPartitions()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner1 source, ParallelOptions parallelOptions, Action1 simpleBody, Action2 bodyWithState, Action3 bodyWithStateAndIndex, Func4 bodyWithStateAndLocal, Func5 bodyWithEverything, Func1 localInit, Action1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable1 source, ParallelOptions parallelOptions, Action1 body, Action2 bodyWithState, Action3 bodyWithStateAndIndex, Func4 bodyWithStateAndLocal, Func5 bodyWithEverything, Func1 localInit, Action1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at Eco.Server.PluginManager.<>cDisplayClass11_0.<StartPlugins>b0(Object x)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

Users report of similar issues when setting world size to 200 or similar that there server crashes while using less then 4 gb ram.. and having more then 16 gb of ram still available on there system.

Possible 32 -64 bit issue  https://stackoverflow.com/questions/14186256/net-out-of-memory-exception-used-1-3gb-but-have-16gb-installed ? ???

**Comment by noblackthunder** [comment]
additional comment: Maybe the server runs not completely on 64 bit as it should ?
