### ISSUE TITLE
[9.0.4-release] IndexOutOfRange exceptions with animal pathing

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#18721]
We are receiving massive amounts of crashes related to IndexOutOfRange exceptions. It is similar to https://github.com/StrangeLoopGames/EcoIssues/issues/17898, but not a NullException.

Crash log:

```
IndexOutOfRangeException
--
   at Eco.Shared.Math.Route.WaypointsAtTime(Single time)
   at Eco.Shared.Pathing.RouteFollower.Position(Single lookAhead)
   at Eco.Shared.Pathing.AITarget.Position(Single timeOffset)
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1()</size>

```

**Comment by SlayksWood** [comment]
#18113 Stanislav try to fix it and maybe fixed it, but we can't check without massive playtest or without release.
