### ISSUE TITLE
[0.9.0.5] [server] [linux] [console] Error after shutdown

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#18743]
After update 0.9.0.4 to 0.9.0.5
After send signal shutdown server
[11:04:20] Сохранение... Завершено за 7 775,8мс
[11:04:46] System.AggregateException: One or more errors occurred. (Cannot access a closed file.)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Eco.Core.Plugins.StorageManager.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg)
System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.SetLength(Int64 value)
   at LiteDB.Engine.DiskService.SetLength(Int64 length, FileOrigin origin)
   at LiteDB.Engine.WalIndexService.Clear()
   at LiteDB.Engine.WalIndexService.CheckpointInternal()
   at LiteDB.Engine.WalIndexService.Checkpoint()
   at Eco.Stats.Stats.Flush()
   at Eco.Core.Plugins.StorageManager.PersistAsync(Boolean forceFlush)
   at Eco.Core.Utils.Threading.IntervalActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Plugins.StorageManager.ShutdownAsync()
[11:04:46] System.AggregateException: One or more errors occurred. (Cannot access a closed file.)

System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.SetLength(Int64 value)
   at LiteDB.Engine.DiskService.SetLength(Int64 length, FileOrigin origin)
   at LiteDB.Engine.WalIndexService.Clear()
   at LiteDB.Engine.WalIndexService.CheckpointInternal()
   at LiteDB.Engine.WalIndexService.Checkpoint()
   at Eco.Stats.Stats.Flush()
   at Eco.Core.Plugins.StorageManager.PersistAsync(Boolean forceFlush)
   at Eco.Core.Utils.Threading.IntervalActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Plugins.StorageManager.ShutdownAsync()
[11:04:46] Выключение завершено

**Comment by SlayksWood** [comment]
save file: https://drive.google.com/file/d/1wuQBTDbl5jVCjNrS12HTmJOsQRmfuuwZ/view?usp=sharing

**Comment by Darkhand81** [comment]
Just experienced this issue as well.  No recent upgrade, just at the end of a normal server shutdown.

v9.4.4

`[06:27:04] Rebuilding database... 
[06:27:35] Rebuilding database... Finished in 30,762.5ms
[06:27:35] Shutting down Stats... Finished in 30,772.2ms
[06:27:35] Shutting down StorageManager... 
[06:27:35] Shutting down StorageManager... Finished in 1.8ms
[06:27:35] System.AggregateException: One or more errors occurred. (Cannot access a closed file.)

System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.SetLength(Int64 value)
   at LiteDB.Engine.WalIndexService.Clear()
   at LiteDB.Engine.WalIndexService.CheckpointInternal()
   at LiteDB.Engine.WalIndexService.Checkpoint()
   at Eco.Stats.Stats.Flush()
   at Eco.Core.Plugins.StorageManager.PersistAsync()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass5_0.<<Create>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Plugins.StorageManager.ShutdownAsync()
   at Eco.Server.PluginManager.ShutdownAsync()
[06:27:35] System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.SetLength(Int64 value)
   at LiteDB.Engine.WalIndexService.Clear()
   at LiteDB.Engine.WalIndexService.CheckpointInternal()
   at LiteDB.Engine.WalIndexService.Checkpoint()
   at Eco.Stats.Stats.Flush()
   at Eco.Core.Plugins.StorageManager.PersistAsync()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass5_0.<<Create>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Plugins.StorageManager.ShutdownAsync()
   at Eco.Server.PluginManager.ShutdownAsync()
[06:27:35] Shutdown finished
`
