### ISSUE TITLE
[0.9.1 staging-1823] Can't start server

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18917]
I used one of the player's world to test issue. After that I started to test on this server. After using command '/level 50,50' 2 times the server was crashed, but log and dump files is empty. I started server again but it is failed again and now the server doesn't start at all.
https://drive.google.com/file/d/1IjM7ROrjLwcgpQZWKp6Dc7QYWAioakYh/view?usp=sharing
```
Failed to load server, Exception was Exception: ArgumentException
Message:An item with the same key has already been added. Key: Franco
Source:System.Private.CoreLib

System.ArgumentException: An item with the same key has already been added. Key: Franco
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Eco.Gameplay.Economy.CurrencyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
 
[15:39:18.307] [1] [Error] [Eco] Unhandled errorSystem.ArgumentException: An item with the same key has already been added. Key: Franco
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Eco.Gameplay.Economy.CurrencyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
```

**Comment by mirasrael** [comment]
This issue already fixed in 9.2. Happens after restart when server changes locale.
