### ISSUE TITLE
USER issue - PC crashed while walking to my camp site

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19021]
USER issue - PC crashed while walking to my camp site

**Comment by IcedForge** [comment]
@dmplatten Thank you for reporting.
You need to add your player logs by following the step instructions on the initial github page, and please list pc specifications as well for us to be able to help you in this issue.

**Comment by dmplatten** [comment]
not sure if this one is worth investigating or not because it only happened once. I have a 4 year old HP Omen laptop.
Let me know if you still want my player logs.

**Comment by IcedForge** [comment]
If you have the logs from the crash yes please. Otherwise feel free to close it.

**Comment by dmplatten** [comment]
I’ll try to get them for you.

I love the game but I’m having fun testing it too. I was a little disappointed that the staging server isn’t available for testing but that’s ok. For testing, is it better to play on one of the slg servers or on my own private server? I’m a software tester by day and having fun testing the game at night too :). Thanks for allowing public testing. I’ve always wanted to help test a game that I enjoyed playing. :) Dave

Sent from my iPad

On Nov 4, 2020, at 8:35 AM, IcedForge <notifications@github.com> wrote:

﻿

If you have the logs from the crash yes please. Otherwise feel free to close it.

**Comment by dmplatten** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5490998/Player.log)
here's the log.

**Comment by IcedForge** [comment]
This seems to be the disconnect / crash issue then there were some audio issues at the end of the log.

[07:28:49.438] Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Collection was modified; enumeration operation may not execute.
Source:System.Private.CoreLib

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client, Boolean doAllParams)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])

And

NullReferenceException: Object reference not set to an instance of an object.
  at Eco.Audio.UISoundController.get_obj () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Audio.UISoundController.SetLevelUp () [0x00000] in <00000000000000000000000000000000>:0 
  at LevelUpSequence.Go () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by SlayksWood** [comment]
probably fixed #18214
