### ISSUE TITLE
Repeated crash caused by a work party

### ISSUE THREAD

**Issue by HaxtonFale** [StrangeLoopGames/EcoIssues#19062]
I have set up a work party to create a windmill for a friend to show them the resources needed. The game crashed a few moments after they deposited some of the materials for work. This is the exception that I got as a result:

[16:13:11.362] [66] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.WorkParties.CurrencyPayment.PayUser(Laborer laborer, Single amount)
   at Eco.Gameplay.Economy.WorkParties.CurrencyPayment.<>c__DisplayClass14_0.<PayUsers>b__0(Laborer x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Eco.Gameplay.Economy.WorkParties.CurrencyPayment.PayUsers(IEnumerable`1 laborers, Single amount)
   at Eco.Gameplay.Economy.WorkParties.ValuePayment.WorkPerformed(Laborer laborer, Single percentPerformed)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.<>c__DisplayClass52_0.<OnWorkPerformed>b__0(Payment x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.OnWorkPerformed(User user, Work work, Single percentDelta, String message)
   at Eco.Gameplay.Economy.WorkParties.CollectResourcesWork.ActionPerformed(GameAction action)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.GameActions.ActionUtil.ActionPerformed(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Items.WorkOrder.TryToContributeMissingIngredients(GameActionPack actionPack, User user, Func`2 ingredientsProvider, WorkOrderContributionType contributionType)
   at Eco.Gameplay.Items.WorkOrder.ScanInventoryAndContribute(User actor, Inventory inventory, WorkOrderContributionType contributionType)
   at Eco.Gameplay.Components.CraftingComponent.OnInventoryChanged()
   at Eco.Gameplay.Components.CraftingComponent.Tick(Single deltaTime)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)

[16:13:11.375] [5] [ Info] [Eco] Saving...
[16:13:12.693] [5] [ Info] [Eco] Saving... Finished in 1,318.1ms

[16:13:12.731] [6] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.WorkParties.CurrencyPayment.PayUser(Laborer laborer, Single amount)
   at Eco.Gameplay.Economy.WorkParties.CurrencyPayment.<>c__DisplayClass14_0.<PayUsers>b__0(Laborer x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Eco.Gameplay.Economy.WorkParties.CurrencyPayment.PayUsers(IEnumerable`1 laborers, Single amount)
   at Eco.Gameplay.Economy.WorkParties.ValuePayment.WorkPerformed(Laborer laborer, Single percentPerformed)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.<>c__DisplayClass52_0.<OnWorkPerformed>b__0(Payment x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.OnWorkPerformed(User user, Work work, Single percentDelta, String message)
   at Eco.Gameplay.Economy.WorkParties.CollectResourcesWork.ActionPerformed(GameAction action)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.GameActions.ActionUtil.ActionPerformed(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Items.WorkOrder.TryToContributeMissingIngredients(GameActionPack actionPack, User user, Func`2 ingredientsProvider, WorkOrderContributionType contributionType)
   at Eco.Gameplay.Items.WorkOrder.ScanInventoryAndContribute(User actor, Inventory inventory, WorkOrderContributionType contributionType)
   at Eco.Gameplay.Components.CraftingComponent.OnInventoryChanged()
   at Eco.Gameplay.Components.CraftingComponent.Tick(Single deltaTime)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Objects.WorldObjectManager.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg)

**Comment by WeaselDog** [comment]
Hi @HaxtonFale . Thank you for reporting this. Are you still having this issue? We are not able to reproduce since the fix for work parties in 9.1.1

**Comment by HaxtonFale** [comment]
Hi, I haven't used work parties since. The issue has gone away after a few server restarts caused by these crashes.

**Comment by WeaselDog** [comment]
Thanks for getting back. Let us know if you have this issue again.
