### ISSUE TITLE
[0.9.1.0] Ballox Box and Executive Office can't be picked up.

### ISSUE THREAD

**Issue by NemoLArs** [StrangeLoopGames/EcoIssues#19077]
After the server i play on updated to 9.1 i can't pick up the Government tables that don't have the extra "pickup security prompt".
Ballox box and executive office.

I hear the sound when the hammer hits it but nothing happens. The other stuff were i get the prompt works just fine.

**Comment by legionaw** [comment]
I can confirm this issue as well. It appeared to be related to the following reporting from server log console:

> [06:04:41] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Civics.Misc.CivicsUtils.GetHostedProposables(IEnumerable`1 types, WorldObject obj)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 124
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 115
[06:04:44] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Civics.Misc.CivicsUtils.GetHostedProposables(IEnumerable`1 types, WorldObject obj)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 124
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 115
[06:04:52] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Civics.Misc.CivicsUtils.GetHostedProposables(IEnumerable`1 types, WorldObject obj)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 124
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 115
[06:05:47] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Civics.Misc.CivicsUtils.GetHostedProposables(IEnumerable`1 types, WorldObject obj)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 124
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 115
[06:05:50] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Civics.Misc.CivicsUtils.GetHostedProposables(IEnumerable`1 types, WorldObject obj)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 124
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 115
[06:06:47] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Civics.Misc.CivicsUtils.GetHostedProposables(IEnumerable`1 types, WorldObject obj)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 124
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 115
[06:07:32] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Civics.Misc.CivicsUtils.GetHostedProposables(IEnumerable`1 types, WorldObject obj)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 124
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 125
[06:07:34] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 121
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 125
[06:07:37] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 121
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 125
[06:18:17] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 121
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 125
[06:18:19] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 121
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 125
[06:18:20] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 121
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 125
[06:18:21] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 121
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 125
[06:18:22] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 121
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 125
[06:18:23] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 121
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 125
[06:18:36] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Mods.TechTree.CivicObject.get_PickupConfirmation() in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Objects\CivicsObjects.cs:line 121
   at HammerItem.PickupDialog(WorldObject obj, Player player) in C:\Program Files (x86)\Steam\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 125

**Comment by SlayksWood** [comment]
fixed in 0.9.1.1
