### ISSUE TITLE
[0.9.2 develop-105] Crash in Court.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19158]
Now this is facilitated by incorrect deletion of sections. But I guess it could be possible and without this bug. 
Steps to reproduce:
- open Court and start create law:
![image](https://user-images.githubusercontent.com/45708377/98355066-b27e3000-2032-11eb-8c39-9d639f4c7eea.png)
- press 10 times 'delete section' button:
![image](https://user-images.githubusercontent.com/45708377/98355170-d9d4fd00-2032-11eb-952f-1068afe4a95c.png)
- ConfirmBox will not be shown because it is located under this window, so close this window, you will see ConfirmBox(in fact there are 10 of them):
![image](https://user-images.githubusercontent.com/45708377/98355343-1143a980-2033-11eb-8ab3-7be51081ad8e.png)
- start press 'Yes' on each. I have crash on forth:
```
<size=60,00%>Exception: ArgumentOutOfRangeException
Message:Specified argument was out of the range of valid values. (Parameter 'index')
Source:System.Collections.Immutable

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.ItemRef(Int32 index)
   at System.Collections.Immutable.ImmutableList`1.get_Item(Int32 index)
   at Eco.Core.Utils.ThreadSafeList`1.GetAt(Int32 index)
   at Eco.Gameplay.Utils.RPCListExtensions.RemoveAt(IHasClientControlledContainers hasContainers, Player player, String listName, Int32 index)</size>
```
[Crash in Law.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5500690/Crash.in.Law.txt)

**Comment by serpopov** [comment]
SVN fixed
