### ISSUE TITLE
Prevent Duplication Bugs due to internal Exceptions

### ISSUE THREAD

**Issue by MeFisto94** [StrangeLoopGames/EcoIssues#19328]
Version: 0.9.1.4 beta release-116
Exception:
```
[02:46:50] System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Gameplay.Components.ElevatorCallPostComponent.OnDestroyElevator()
at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
at Eco.Gameplay.Objects.WorldObject.Destroy()
at Eco.Gameplay.Objects.WorldObject.<>c__DisplayClass111_0.<TryPickUp>b__1()
at Eco.Gameplay.GameActions.GameActionPack.<>c__DisplayClass13_0.<AddPostEffect>b__0()
at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
at Eco.Gameplay.Objects.WorldObject.TryPickUp(Player player, Single caloriesNeeded)
at HammerItem.PickupDialog(WorldObject obj, Player player) in /home/container/Mods/Tools/HammerItem.cs:line 125
```
Now unfortunately I cannot tell what has led to this duplication, only that picking up the elevator with a hammer caused the item to appear in the inventory without being deconstructed in the world, apparently due to the NRE in the ElevatorCallPostComponent.

Apart from this particular issue, it might be worth to catch Exceptions in WorldObject#Destroy and don't add the item to the inventory in this case. The downside could be, that in case of a partial destruction the object is already gone from the world but not awarded to the user, effectively stealing them from the user, which is also not really desirable.
On the other hand if we're at the stage of Exceptions in Destroy we could end up with a half corrupted world state anyway.

Talking about this ElevatorCallPost issue, it was fixed by restarting the server.

**Comment by StallEF** [comment]
@MeFisto94  Restart you server 1 time in day or "SaveFrequency": 30, in \Configs\Storage.eco
