### ISSUE TITLE
[0.9.2 develop-115] need to fix /gat

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19369]
use /gat 1 - will delete all items in toolbar and backpack
use /gat 1 second time - will spawn item
Also have exception in server log:
```
   System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.<>c__DisplayClass12_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass1_0.<RunWithExceptionLog>b__0()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Tutorial.TutorialTasks.<>c__DisplayClass20_0.<TrySubscribeTutorials>b__3(User u)
   at Eco.Core.Utils.SubscriptionExtensions.<>c__DisplayClass5_0`1.<SubscribeAndTrack>b__0(T t)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.InventoryChangeSet.Apply()
   at Eco.Gameplay.Items.Inventory.Clear(User user)
   at Eco.Gameplay.Systems.Chat.QACommands.GiveAllTools(User user, Single tier)
```

**Comment by SlayksWood** [comment]
and delete please bow from it

**Comment by beastyn** [comment]
crash part was fixed here
https://github.com/StrangeLoopGames/Eco/pull/7543
so only bow here
