### ISSUE TITLE
[0.9.1.5] [Eco-Server] [Crash] at Eco.Gameplay.Components.RoomRequirementsComponent.CheckRoom()

### ISSUE THREAD

**Issue by BartonsGit** [StrangeLoopGames/EcoIssues#19362]
### Environment Information:
**Operating System**: Windows Server 2019
**Memory**: 32768MB RAM
**Available OS Memory**: 32756MB RAM
**Page File**: 12184MB used, 25435MB available
**Processor/CPU**: Intel(R) Xeon(R) CPU E5645 @ 2.40GHz (24 CPUs), ~2.4GHz
**Eco Server:** Eco Server 0.9.1.5 beta release-119

### Issue:
Server has crashed with the following information:

### Stacktrace
```cs
[15:34:31.972] [399] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.RoomRequirementsComponent.CheckRoom()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[15:34:32.005] [5] [ Info] [Eco] Saving...  
[15:35:00.811] [460] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.RoomRequirementsComponent.CheckRoom()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Objects.WorldObjectManager.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg)
 
[15:35:07.130] [460] [ Info] [Eco] Shutdown finished
```

### Issue Attachments:
**Google Drive:** https://drive.google.com/file/d/1fd0BAbXh--GMsssFBrYmD3rSUGErKbOJ/

### Attached File Contents:
```log
\Diagnostics\Dumps
\Diagnostics\log_201116051725.log
\Diagnostics\Mods.zip
\Diagnostics\Saves
\Diagnostics\Dumps\ClientReceiveException TargetInvocationException 11164745.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11160040.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11160127.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11161314.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11161356.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11161854.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11161855.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11162101.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11162406.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11162501.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11162617.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11162622.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11162747.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11162820.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11162933.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11163010.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11163501.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11163647.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11164403.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11164511.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11164747.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11164808.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11164858.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11165148.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11170247.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11171101.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11171328.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11172450.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11172816.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11174830.ecodmp
\Diagnostics\Dumps\ClientUpdateException Exception 11174852.ecodmp
\Diagnostics\Dumps\ServerCrash SynchronizationLockException 11164825.ecodmp
\Diagnostics\Dumps\UnhandledException SynchronizationLockException 11164825.ecodmp
\Diagnostics\Saves\After Crash
\Diagnostics\Saves\Before Crash
\Diagnostics\Saves\After Crash\RedwoodValeAfter.eco
\Diagnostics\Saves\Before Crash\RedwoodValeBefore.eco
```

**Comment by NAKarwisch** [comment]
If any additional data or diagnostic information is needed, please let me know and I can provide it.

Thank you!

**Comment by SlayksWood** [comment]
@BartonsGit Thank you for the report and sorry for the wait.
Can you provide coordinates of room if known?
Has this happened again?

**Comment by BartonsGit** [comment]
@SlayksWood No worries on the wait.
I do not have the coordinates of the room unfortunately. :(
The issue did not happen again during the save. It was wiped shortly after.
