### ISSUE TITLE
Process cannot access the file.

### ISSUE THREAD

**Issue by harry2258** [StrangeLoopGames/EcoIssues#1944]
Server seems to randomly crash with an error saying it cannot access a file because it's in use by another process. I have made see that's there's only one instance of the sever running. 

When you do restart the server, it regenerates the entire world all over again.

The issue seems to be random, server does back up files, and it doesn't seems to be triggered by a specific action. 

It once crashed while placing a down a Tallow Candle.
It also crashed after restarting the server (from this crash) and no one had logged on since the restart. 

Crashlog:
```--BEGIN DUMP--
Dump Time
08/23/2017 01:06:58

Exception
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Ionic.Zip.ZipFile.Save()
   at Eco.Core.Serialization.DataStore.ProcessQueue()
   at Eco.Core.Serialization.DataStore.<Run>b__26_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--```

**Comment by metachronism** [comment]
closing, no repro/not enough info/need more repro steps
