### ISSUE TITLE
Player crashes the server when trying to delete or modify a title.

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#19446]
It creates two files in the Dump folder that have the same error details just one is called ServerCrash and the other UnhandledException.
[UnhandledException NullReferenceException 11241929.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5587833/UnhandledException.NullReferenceException.11241929.txt)
[ServerCrash NullReferenceException 11241929.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5587834/ServerCrash.NullReferenceException.11241929.txt)

Screenshot from player showing what he was trying to modify.
![image](https://user-images.githubusercontent.com/17730996/100056828-02c90080-2e2f-11eb-8c06-5f8b07e8d44d.png)

**Comment by SlayksWood** [comment]
```
--BEGIN DUMP--
Dump Time
11/24/2020 07:19:29

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.CivicObjectComponent.<>c__DisplayClass48_0.<Remove>b__0(IHasID x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Components.CivicObjectComponent.Remove(Player player, IProposable target)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

--END DUMP--

**Comment by SlayksWood** [comment]
Save files:
https://drive.google.com/file/d/1lEUMMFgx-6VXZXiU02GbuuSFbnz8BOPJ/view?usp=sharing
When I try to delete this tirle the server was crashed.
