### ISSUE TITLE
[0.9.2 staging-1853] Server doesn't migrate

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19451]
Try to migrate: 
https://drive.google.com/file/d/16UekkpGmwcQ3V1498r_JnLiF3qB_zafv/view?usp=sharing
[log_201124021518.log](https://github.com/StrangeLoopGames/EcoIssues/files/5589478/log_201124021518.log)

**Comment by IcedForge** [comment]
Tried to migrate mishkas long term server and got a bunch of migrate and overall issues
[migrations.log](https://github.com/StrangeLoopGames/EcoIssues/files/5589645/migrations.log)
[log_201124121553.log](https://github.com/StrangeLoopGames/EcoIssues/files/5589649/log_201124121553.log)

**Comment by SlayksWood** [comment]
Can't migrate any server now. This server is almost empty
https://drive.google.com/file/d/1n8hmKzq3jee6qZvemHjLCavqCFq63nA_/view?usp=sharing
[log_201126120140.log](https://github.com/StrangeLoopGames/EcoIssues/files/5602606/log_201126120140.log)

**Comment by SlayksWood** [comment]
Need to check #19468 and this #19469

**Comment by MishkaFur** [comment]
tried loading my world on 1856 and get the below/attached

Lemme know if anything else is needed :)


[16:41:10.701] [67] [Error] [Eco] Failed to load object of type 'EconomyManager'. It will be ignored, but may cause inconsistency and errors in other entities: System.Collections.Generic.KeyNotFoundException: The given key 'Eco.Core.Serialization.Migrations.DataMigrations.MemberDataInput' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.Core.Serialization.Migrations.DataMigrations.MigrationDataModification.GenerateOutput(MigrationContext context)
   at Eco.Core.Serialization.Migrations.DataMigrations.MemberDataModification.Apply(MigrationContext context)
   at Eco.Core.Serialization.Migrations.DataMigration.MigrateInstance(MigrationContext context)
   at Eco.Core.Serialization.Migrations.MigrationManager.MigrateInstanceInternal(MigrationContext context, IEnumerable`1 migrations)
   at Eco.Core.Serialization.Migrations.MigrationManager.MigrateInstance(MigrationContext context)
   at Eco.Core.Serialization.Serializers.MigrationChainSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.DecodeReferenceableEntry(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.DecodeDictionary(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.Decode(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream)
[migrations.log](https://github.com/StrangeLoopGames/EcoIssues/files/5604207/migrations.log)
[log_201126043438.log](https://github.com/StrangeLoopGames/EcoIssues/files/5604208/log_201126043438.log)

**Comment by mirasrael** [comment]
Fixed migration. Tested with Mishka world. Was able to load it. In current version it performs Deed split very slow (I stopped it after 30 minutes). But it may be optimized (in local version I applied some optimization and split was finished in less than a minute). I informed @gzatravkin about the issue and asked to fix performance of split.
But with local optimization the world loaded and I was able to connect.

**Comment by mirasrael** [comment]
Deed split fixed here: https://github.com/StrangeLoopGames/Eco/pull/7298

**Comment by SlayksWood** [comment]
Steel can't migrate this world:
https://drive.google.com/file/d/1DG6UpirOpwBpyGbtiVHZNSNFQJ6vYWL2/view?usp=sharing
[log_201207035738.log](https://github.com/StrangeLoopGames/EcoIssues/files/5652821/log_201207035738.log)
and this one too:
https://drive.google.com/file/d/1kAqhxV0yHz8pduL4hf2ZS5Bh7xgSQRxr/view?usp=sharing

**Comment by mirasrael** [comment]
Migration is breaking now due to recent changes in Void Storage and OnRemovingDueVerifyFailed callback.

**Comment by SlayksWood** [comment]
migration and void storage work.
