### ISSUE TITLE
[0.9.2.0 beta staging-1854]Civics: Server crash on picking incorrect materials in trigger selection

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19472]
Selecting non appropriate materials causes server crash with this exception

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Utils.PropertyScanning.ScanScope.ScopeOfHashEntry(Object entry)
   at Eco.Core.Utils.PropertyScanning.PropertyIteration.IterateProperties(Object obj, HashSet`1 dontScan, ScanScope objScope)+MoveNext()
   at Eco.Core.Utils.PropertyScanning.PropertyIteration.IterateProperties(Object obj, HashSet`1 dontScan, ScanScope objScope)+MoveNext()
   at Eco.Core.Utils.PropertyScanning.PropertyIteration.IterateProperties(Object obj, HashSet`1 dontScan, ScanScope objScope)+MoveNext()
   at Eco.Core.Utils.PropertyScanning.PropertyIteration.IterateProperties(Object obj, HashSet`1 dontScan, ScanScope objScope)+MoveNext()
   at Eco.Core.Utils.PropertyScanning.PropertyIteration.IterateProperties(Object obj, HashSet`1 dontScan, ScanScope objScope)+MoveNext()
   at Eco.Core.Utils.PropertyScanning.PropertyIteration.IterateProperties(Object obj, HashSet`1 dontScan, ScanScope objScope)+MoveNext()
   at Eco.Core.Utils.PropertyScanning.PropertyIteration.IterateProperties(Object obj, HashSet`1 dontScan, ScanScope objScope)+MoveNext()
   at Eco.Core.Utils.PropertyScanning.PropertyIteration.IterateProperties(Object obj, HashSet`1 dontScan, ScanScope objScope)+MoveNext()
   at Eco.Core.Utils.PropertyScanning.PropertyIteration.IterateProperties(Object obj, HashSet`1 dontScan, ScanScope objScope)+MoveNext()
   at Eco.Core.Utils.PropertyScanning.PropertyScanner.ScanObj(Object root, ScanSettings settings)
   at Eco.Core.Utils.PropertyScanning.PropertyScanner.Scan(ScanSettings settings)
   at Eco.Gameplay.Civics.Misc.DisplayErrorUIExtension.CheckAndUpdateValidity(IDisplayErrorUI displayErrorUI, PropertyInfo prop, Object objParent)
   at Eco.Core.Controller.ControllerExtensions.<>c__DisplayClass14_1.<SubscribeAllRecursive>b__1()
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<NotifyChanged>b__18_1(IPropertySubscription subscription)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Core.Controller.ControllerInstanceInfo.NotifyChanged(String propname)
   at Eco.Core.Controller.ControllerManager.NotifyChanges()
   at Eco.Core.Controller.ControllerManager.DoWork()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass4_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)

**Comment by IcedForge** [comment]
![Screenshot_61.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/4acda7f2-176f-41a9-8612-0d05abfa3626)
