### ISSUE TITLE
[0.9.2.0 beta staging-1856]/civics spawngov broken and causing exceptions when opening tables

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19494]
Using /civics spawngov will cause exceptions when opening ANY of the spawned tables as they contain invalid objects and depending on which you open it will throw different object called exceptions.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.<>c__DisplayClass12_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass2_0.<RunWithExceptionLog>b__0()
System.Exception: Failed to ratify constitution.
   at Eco.Gameplay.Civics.CivicsTests.ConfigureCapitolObject(User user, WorldObject capitolObject, WorldObject boardofElections, GovernmentType govType)
   at Eco.Gameplay.Civics.CivicsCommands.SpawnGov(User user, Boolean requireElections)
```

Which in returns starts to cause other weird things happening.
Spawn a building instead and spawn the objects separately for now until this is fixed. do NOT use /civics spawngov for reproducing or checking civics related objects as this can be faulty results.

**Comment by IcedForge** [comment]
Seems resolved will close for now
