### ISSUE TITLE
[Eco Server 0.9.1.7 beta release-126] [SeverCrash] [UserManager] ArgumentException - An element with the same key but a different value already exists.

### ISSUE THREAD

**Issue by BartonsGit** [StrangeLoopGames/EcoIssues#19504]
### Environment Information:
**Operating System**: Windows Server 2019
**Memory**: 32768MB RAM
**Available OS Memory**: 32756MB RAM
**Processor/CPU**: Intel(R) Xeon(R) CPU E5645 @ 2.40GHz (24 CPUs), ~2.4GHz
**Eco Server:** Eco Server 0.9.1.7 beta release-126

### Issue:
- Server crash during shutdown.
- Server not able to start after being shutdown.
- On startup after the previous shutdown, server console shows the following during bootup just before the server repeatedly crashes:
```cs 
[04:20:06.571] [5] [ Info] [Eco] Initializing UserManager...  
[04:20:06.581] [5] [ Info] [Eco] [Server Initialization]... Finished in 135,440.7ms
 
[04:20:06.608] [48] [Error] [Eco] Failed to load server, Exception was Exception: ArgumentException
Message:An element with the same key but a different value already exists. Key: slg184818
Source:System.Collections.Immutable

System.ArgumentException: An element with the same key but a different value already exists. Key: slg184818
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Gameplay.Players.UserManager.AddUser(User user)
   at Eco.Gameplay.Players.UserManager.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
```

### Dump/Stacktrace:
```cs
--BEGIN DUMP--
Dump Time
11/26/2020 04:20:11

Exception
Exception: ArgumentException
Message:An element with the same key but a different value already exists. Key: slg184818
Source:System.Collections.Immutable

System.ArgumentException: An element with the same key but a different value already exists. Key: slg184818
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Gameplay.Players.UserManager.AddUser(User user)
   at Eco.Gameplay.Players.UserManager.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)

--END DUMP--
```

### Troubleshooting Performed:
- The corruption/key appears to be contained within the severs .ECO file.
- I've narrowed down the issue between two save files, which are attached below.
- The issue occurred some time between 12:28AM Local server time, and 1:28AM Local server time.
- The issue occurs for all databases in the backup folder no matter how far back I go in the backups.

### Workaround:
- Continue rollback of server until working .ECO file boots past UserManager.

### Issue Attachments:
**Google Drive:** https://drive.google.com/file/d/1nVgx2E-rQb3hIrLIHVQooUY8Pozt0bRn/

### Attached File Contents:
```
\Dumps
\Log
\Saves
\Dumps\ServerCrash ArgumentException 11262011.ecodmp
\Dumps\UnhandledException ArgumentException 11262011.ecodmp
\Log\log_201125125421.log
\Saves\Crashing
\Saves\Working
\Saves\Crashing\RedwoodValeVanillaCrash.eco
\Saves\Working\RedwoodValeVanillaWorking.eco
```

**Comment by BartonsGit** [comment]
If you would like a database file, please let me know and I can start the upload of one of them. But from my understanding, the issue is contained within the .ECO save file.

**Comment by BartonsGit** [comment]
A user on the server stated that when they moved from playing on a Windows PC, and moved to their Mac, they were forced to recreate their character. I do not know if this would be the cause of the issue, but from the user was describing to me, it might be the cause of this.

**Comment by SlayksWood** [comment]
@BartonsGit 
Can you tell me how he logged into the game? Did he use Steam or SLG account?

**Comment by mirasrael** [comment]
I investigated the save and it seems he used two versions of game.
First he created user with Steam version of game (not linked to SLG site).
Then he used SLG account to login (another copy of game) and so it created new user, because there no way to know that these two users are same user, because Steam account wasn't linked.
Then he linked Steam to his SLG account and these users was partially merged, because now both user with Steam ID and user with SLG ID has same SLG ID. From now issue starts happening because when it loads and tries to build user index it has ID conflict.
You can try to fix it if open your save file (.eco) as zip file, go to Users directory and remove this entry: `_slg184818`.
![image](https://user-images.githubusercontent.com/475445/100425625-9f460980-30a0-11eb-8076-08f16f937b58.png)

**Comment by mirasrael** [comment]
I added check to code to avoid such ID conflict in feature. It just won't update ID for user if another user with such ID already exists. But it won't fix existing saves.

**Comment by BartonsGit** [comment]
@mirasrael Thank you very much for the investigation as well as steps to resolve issues like this in the future!

**Comment by SlayksWood** [comment]
@BartonsGit Thanks for a very good problem describing, it made finding a solution much easier.
If you have a SLG account and want a little reward, send an e-mail to dennis@strangeloopgames.com with your SLG ID and link with this issue.
