### ISSUE TITLE
[0.9.2 staging-1865] Server crash

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19634]
Create a new world. start toplat, play near 1 minute and server was crashed. I can't reproduce it, but we need to investigate it more:
```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.ExternalInputs.MovementTracker.ReactOnWorldChanges()
   at Eco.Simulation.ExternalInputs.MovementTracker.Tick()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[16:51:09.537] [5] [ Info] [Eco] Saving...  
[16:51:12.263] [83] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.ExternalInputs.MovementTracker.ReactOnWorldChanges()
   at Eco.Simulation.ExternalInputs.MovementTracker.Tick()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg)
```
[log_201207044638.log](https://github.com/StrangeLoopGames/EcoIssues/files/5653111/log_201207044638.log)

I start to record after press 'Save'. And it seems, before I was thrown out, I ran into a bad loaded chunk.
https://drive.google.com/file/d/1zHaUyp9cqD4pLfDx3SXjiYZ3iNLMxrwP/view?usp=sharing

**Comment by SlayksWood** [comment]
had this crash today second time

**Comment by IcedForge** [comment]
Will close this as i have not encountered it at all after the fix which happened every 5-30min before.
