### ISSUE TITLE
9.1.8 Unable to generate a world with specific worldgenerator.eco settings

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19642]
Unable to generate a world with some settings in the worldgenerator.eco not sure exactly what ones though as it just errors out to the below, Am unsure what setting in the worldgenerator broke it, all the mins are lower than the max and the error message is well...not useful to a non dev

`[19:29:26.066] [32] [Error] [Eco] Failed to load server, Exception was Exception: ArgumentOutOfRangeException
Message:Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Source:System.Private.CoreLib

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Eco.WorldGenerator.VoronoiWorldGenerator.Generate(VoronoiWorldGeneratorConfig config)
   at Eco.WorldGenerator.VoronoiWorldGeneratorConfig.GetGenerator(Boolean previewOnly)
   at Eco.WorldGenerator.VoronoiModule.GetValue(Double x, Double y, Double z)
   at Eco.WorldGenerator.EcoTerraceNode.GetValue(Double x, Double y, Double z)
   at Eco.WorldGenerator.TerrainGenerator.Generate(Int32 chunkPosX, Int32 chunkPosZ)
   at Eco.WorldGenerator.WorldGeneratorPlugin.<>c__DisplayClass34_1.<CreateWorld>b__1(Vector2i columnPos)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 
[19:29:31.084] [1] [Error] [Eco] Unhandled errorSystem.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.WorldGenerator.WorldGeneratorPlugin.CreateWorld()
   at Eco.WorldGenerator.WorldGeneratorPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Eco.WorldGenerator.VoronoiWorldGenerator.Generate(VoronoiWorldGeneratorConfig config)
   at Eco.WorldGenerator.VoronoiWorldGeneratorConfig.GetGenerator(Boolean previewOnly)
   at Eco.WorldGenerator.VoronoiModule.GetValue(Double x, Double y, Double z)
   at Eco.WorldGenerator.EcoTerraceNode.GetValue(Double x, Double y, Double z)
   at Eco.WorldGenerator.TerrainGenerator.Generate(Int32 chunkPosX, Int32 chunkPosZ)
   at Eco.WorldGenerator.WorldGeneratorPlugin.<>c__DisplayClass34_1.<CreateWorld>b__1(Vector2i columnPos)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
`

[WorldGenerator Arguementout of range.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5654902/WorldGenerator.Arguementout.of.range.zip)

**Comment by IcedForge** [comment]
Thanks for reporting @MishkaFur please attach the log next time as well :D it makes importing and reading it a bit easier.

**Comment by MishkaFur** [comment]
> 
> 
> Thanks for reporting @MishkaFur please attach the log next time as well :D it makes importing and reading it a bit easier.

Knew i forgot something!
[log_201207071738.log](https://github.com/StrangeLoopGames/EcoIssues/files/5658416/log_201207071738.log)

**Comment by mirasrael** [comment]
Can you also attach WorldGenerator.eco? And FYI we are not officially supporting worlds over 4km2.

**Comment by MishkaFur** [comment]
Mirasrael it was attached as zip file, was a 2km world, attached again, github does not support .eco files :)

[WorldGenerator Arguementout of range.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5658607/WorldGenerator.Arguementout.of.range.zip)

**Comment by mirasrael** [comment]
Ah sorry, missed it :(

**Comment by MishkaFur** [comment]
I think it might be related to landpercentrange if its 80 to 85 then it seems fine
