### ISSUE TITLE
Server crashing on startup

### ISSUE THREAD

**Issue by konradmoesch** [StrangeLoopGames/EcoIssues#19741]
After rebooting the system, my Eco Server is crashing on startup.
I tried loading a Backup and reinstalling a clean EcoServer, but the crash persists.

I think the interesting part of my log is the following:

```
[00:28:39.534] [13] [Error] [Eco] Failed to load server, Exception was Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.World

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.World.WorldChunk.SetBlockInternal(Block block, Vector3i localPosition)
   at Eco.World.PersistentChunk.SetBlockInternal(Block block, Vector3i localPosition)
   at Eco.World.WorldChunk.SetBlock[T](Vector3i localPosition, Object[] args)
   at Eco.World.WorldChunkGrid.SetBlock[T](WrappedWorldPosition3i worldPos, Object[] args)
   at Eco.World.World.SetBlock[T](WrappedWorldPosition3i worldPos, Object[] args)
   at Eco.World.Blocks.WaterBlock.TryMoveWater(Vector3i worldPosition, Block nearbyBlock, Single waterValue, Boolean checkForSolidBase)
   at Eco.World.Blocks.WaterBlock.Tick(Vector3i worldPosition)
   at Eco.World.PersistentChunk.Tick()
   at Eco.World.WorldPlugin.<>c__DisplayClass30_0.<Initialize>b__2(PersistentChunk chunk)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (Index was outside the bounds of the array.)
[log_201215122723.log](https://github.com/StrangeLoopGames/EcoIssues/files/5692200/log_201215122723.log)

[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5692202/Game.zip)


```
The full log and world files are attached

**Comment by IcedForge** [comment]
@konradmoesch thank you for reporting. Im sorry for the very late reply.
Looks like it was mods being removed from the world. 

If these crashes still persists even on a fresh new world could you remove your mods folder and verify the integrity of game files(steam) or if you are using an slg website download redownload it and provide a fresh server log when this happens.

Feel free to close this issue if you no longer have these problems.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
