### ISSUE TITLE
[0.9.2 staging-1874] Can't connect to server after migration

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19754]
I'm playing on this server, so I have a lot of properties.
```
<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.ResidencyManager.Eco.Gameplay.GameActions.IGameActionAware.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.GameActions.ActionUtil.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.Objects.WorldObject.QueryInteraction(Player player)
   at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, INetObjectContainer monitored)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1()</size>
   ```
I have at least 3 splitted deeds after migration on this server:
![image](https://user-images.githubusercontent.com/45708377/102350845-961cce00-3fb6-11eb-98c3-7c2bcfdde1a7.png)
[log_201216033141.log](https://github.com/StrangeLoopGames/EcoIssues/files/5702752/log_201216033141.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5702753/Player.log)

Save file 9.1.8: https://drive.google.com/file/d/1DG6UpirOpwBpyGbtiVHZNSNFQJ6vYWL2/view?usp=sharing

But I can connect first time to other migrated world's or worlds in which I don't have any deeds.

**Comment by gzatravkin** [comment]
I tried, it worked fine for me (at unity client with attached save file):
![image](https://user-images.githubusercontent.com/53317567/102387479-2fe07d00-3faf-11eb-844d-fef6f220d150.png)

I will try to check it at steam
