### ISSUE TITLE
[0.9.2 staging-1881] Command '/preset hidden' crashes server

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19810]
It probably crashed since 9.0, but it was not critical as I thought, but some players use these commands too(I got a message about this) for their own purposes. So I think it's worth fixing this.
[log_201221113540.log](https://github.com/StrangeLoopGames/EcoIssues/files/5723747/log_201221113540.log)

```
System.AggregateException: One or more errors occurred. (Can't encode instance of type 'Eco.Mods.OccupancyInitItem')
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Eco.Core.Plugins.StorageManager.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg)
System.InvalidOperationException: Can't encode instance of type 'Eco.Mods.OccupancyInitItem'
   at Eco.Core.Serialization.Serializers.NullClassSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeInstance(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(BinaryWriter writer, Object instance, SerializeFlags flags)
   at Eco.Core.Serialization.SimpleSerializer.SerializeTo(Stream stream, Object obj)
   at Eco.Core.Serialization.PersistenceManager.Persist(ContentAccessor& contentAccessor, IStorage storage)
   at Eco.Core.Serialization.PersistenceManager.ApplyChanges(ContentAccessor& contentAccessor)
   at Eco.Core.Serialization.DataStore.ContentAccessor.ExecuteAsync(ExclusiveAccess exclusiveAccess, DataStoreContentAccessorDelegate action)
   at Eco.Core.Serialization.PersistenceManager.PersistAllAsync(ExclusiveAccess exclusiveAccess, Boolean forceFlush)
   at Eco.Core.Plugins.StorageManager.PersistAsync(Boolean forceFlush)
   at Eco.Core.Utils.Threading.IntervalActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Plugins.StorageManager.ShutdownAsync()
```

**Comment by IcedForge** [comment]
I am pretty sure i used this command post 9.0

**Comment by IcedForge** [comment]
Worked in 9.0.4, adding regression to this.
