### ISSUE TITLE
USER ISSUE: Client Crash on WT

### ISSUE THREAD

**Issue by squished-01** [StrangeLoopGames/EcoIssues#19829]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Todd asked if we need hydrocholoids.  I moused over the tooltip.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Collection was modified; enumeration operation may not execute.
Source:System.Private.CoreLib

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client, Boolean doAllParams)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'PlayerCountAtEachLevel' of 'Eco.Gameplay.Skills.SkillTree'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@squished-01 Thank you for the report. Should be fixed in 9.2
