### ISSUE TITLE
USER ISSUE: Probably hacking of the official server [SLG] Giant Panda

### ISSUE THREAD

**Issue by netlanru** [StrangeLoopGames/EcoIssues#19874]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Try to vote for a "possibly specially created" proposed constitution created by the player Canary on the official server "[SLG] Giant Panda"

**Expected behavior:**
1. Doesn't let you vote. 2.http: //gs2.play.eco:3001/ not available in manual mode. 500 error

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Server encountered an exception:

<size=60.00%>Exception: FileNotFoundException
Message:
Source:Eco.Gameplay

System.IO.FileNotFoundException: 
File name: 'NetFabric.Hyperlinq, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Eco.Gameplay.Civics.ElectionManager.CanStartForActions(User user, Election election)
   at Eco.Gameplay.Civics.Elections.Election.Start(User user, Boolean notify, Boolean force)
   at Eco.Gameplay.Civics.Elections.Election.Start(Player player)


Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by netlanru** [comment]
An example of the use of vulnerability: creating a law for unclaim of all territories. vote yes. create this kind of constitutional overthrow

**Comment by IcedForge** [comment]
@netlanru Thank you for reporting this.
What was your username and localization setting at the time?
Was there an unusual name / tags involved in the civic object?

As for manual voting using the ip/dns of the server directly will never work to vote as it requires you to login to the web interface via the game to have a correct key linked to your ingame user to be able to vote.

**Comment by netlanru** [comment]
> What was your username and localization setting at the time?
> Was there an unusual name / tags involved in the civic object?

Username: Heidenlarm
Localization setting at the time: UTC+3:00 (Russia, Moscow)
Name to vote: Ratify Bison Constitution (draft)
in Linuas's Capitol
Server web face gives error 500 anyway

More details can be seen on the server "[SLG] Giant Panda" at the moment. Problem now

**Comment by IcedForge** [comment]
There were no hacking anywhere involved, the issue originated from a constitution that was voted for and active but not contained on a capitol causing permissions to go haywire, this needs further investigation to determine reproduction steps as it is a bug.

**Comment by IcedForge** [comment]
![Screenshot_26](https://user-images.githubusercontent.com/24981362/103367888-78775a80-4ac6-11eb-8ba2-ee15f5eeb43d.jpg)
![Screenshot_27](https://user-images.githubusercontent.com/24981362/103367890-79a88780-4ac6-11eb-87fc-2e27ecd8898f.jpg)

Trying to replace the active not contained item throws the OP's exception

**Comment by IcedForge** [comment]
When i looked into the bison constitution as well it was completely empty of all articles 
![Screenshot_25](https://user-images.githubusercontent.com/24981362/103368044-defc7880-4ac6-11eb-94cc-99b3836d93d8.jpg)

**Comment by IcedForge** [comment]
solved the situation on Giant Panda by force removing the active non contained constitution via 
/objects remove constitution, id + a server restart to clear all remaining cache issues
