### ISSUE TITLE
We keep getting this error popping up in our logs every few seconds and we are wondering what it means?

### ISSUE THREAD

**Issue by gunnin** [StrangeLoopGames/EcoIssues#19880]
[146] [Error] [Eco] Error inserting stat of type PolluteAir into databaseSystem.NotImplementedException: The method or operation is not implemented.
   at LiteDB.BufferSliceExtensions.ReadIndexKey(BufferSlice buffer, Int32 offset)
   at LiteDB.Engine.IndexNode..ctor(IndexPage page, Byte index, BufferSlice segment)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)

**Comment by IcedForge** [comment]
@gunnin Thanks for reporting an issue, could i ask you to provide some further information and have you upload your player log + the server log itself if its possible? From a glance it looks like a db corruption or a potential writing issue.

**Comment by gunnin** [comment]
@IcedForge heres the log from today when we started up the server and had nobody on there 
[log_201230030406.log](https://github.com/StrangeLoopGames/EcoIssues/files/5756079/log_201230030406.log)
