### ISSUE TITLE
Linux server have libgdiplus trouble

### ISSUE THREAD

**Issue by enexusde** [StrangeLoopGames/EcoIssues#19894]
```

[05:38:34] Initializing registrars for CivicsPlugin... Finished in 89.9ms
[05:38:34] Initializing registrars for GameDataPlugin...
[05:38:34] Initializing registrars for GameDataPlugin... Finished in 18.9ms
[05:38:34] Initializing registrars for EconomyPlugin...
[05:38:34] Initializing registrars for EconomyPlugin... Finished in 39.7ms
[05:38:34] Initializing DifficultySettings...
[05:38:34] Initializing DifficultySettings... Finished in 1.2ms
[05:38:34] Initializing Stats...
[05:38:35] Initializing Stats... Finished in 244.7ms
[05:38:35] Initializing CivicsPlugin...
[05:38:35] Initializing CivicsPlugin... Finished in 84.6ms
[05:38:35] Initializing PerformancePlugin...
[05:38:35] Initializing PerformancePlugin... Finished in 0.1ms
[05:38:35] Initializing LocalizationPlugin...
[05:38:35] Initializing LocalizationPlugin... Finished in 122.1ms
[05:38:35] Initializing ModKitPlugin...
[05:38:35] Initializing ModKitPlugin... Finished in 685.1ms
[05:38:35] Initializing WorldGeneratorPlugin...
[05:38:35] Generating world 0.52km²...
[05:38:37] Generating terrain...
[05:38:41] Generating terrain... Finished in 3,129.3ms
[05:38:41] Generating world 0.52km²... Finished in 5,066.5ms
[05:38:41] Initializing WorldGeneratorPlugin... Finished in 5,086.2ms
[05:38:41] [Server Initialization]... Finished in 38,996.2ms
[05:38:41] Failed to load server, Exception was Exception: DllNotFoundException
Message:Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
Source:System.Drawing.Common

System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
Outer Exceptions:
One or more errors occurred. (The type initializer for 'Gdip' threw an exception.)
The type initializer for 'Gdip' threw an exception.
[05:38:46] Unhandled errorSystem.AggregateException: One or more errors occurred. (The type initializer for 'Gdip' threw an exception.)
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.WorldGenerator.WorldGeneratorPlugin.CreateWorld()
   at Eco.WorldGenerator.WorldGeneratorPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, Int32 stride, PixelFormat format, IntPtr scan0)
   at Eco.WorldGenerator.DirectBitmap..ctor(Int32 width, Int32 height)
   at Eco.WorldGenerator.VoronoiWorldGenerator.RenderTerrainMap(VoronoiWorldGeneratorConfig config)
   at Eco.WorldGenerator.VoronoiWorldGenerator.Generate(VoronoiWorldGeneratorConfig config)
   at Eco.WorldGenerator.VoronoiWorldGeneratorConfig.GetGenerator(Boolean previewOnly)
   at Eco.WorldGenerator.VoronoiModule.GetValue(Double x, Double y, Double z)
   at Eco.WorldGenerator.EcoTerraceNode.GetValue(Double x, Double y, Double z)
   at Eco.WorldGenerator.TerrainGenerator.Generate(Int32 chunkPosX, Int32 chunkPosZ)
   at Eco.WorldGenerator.WorldGeneratorPlugin.<>c__DisplayClass34_1.<CreateWorld>b__1(Vector2i columnPos)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
Unhandled exception. System.AggregateException: One or more errors occurred. (The type initializer for 'Gdip' threw an exception.)
 ---> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, Int32 stride, PixelFormat format, IntPtr scan0)
   at Eco.WorldGenerator.DirectBitmap..ctor(Int32 width, Int32 height)
   at Eco.WorldGenerator.VoronoiWorldGenerator.RenderTerrainMap(VoronoiWorldGeneratorConfig config)
   at Eco.WorldGenerator.VoronoiWorldGenerator.Generate(VoronoiWorldGeneratorConfig config)
   at Eco.WorldGenerator.VoronoiWorldGeneratorConfig.GetGenerator(Boolean previewOnly)
   at Eco.WorldGenerator.VoronoiModule.GetValue(Double x, Double y, Double z)
   at Eco.WorldGenerator.EcoTerraceNode.GetValue(Double x, Double y, Double z)
   at Eco.WorldGenerator.TerrainGenerator.Generate(Int32 chunkPosX, Int32 chunkPosZ)
   at Eco.WorldGenerator.WorldGeneratorPlugin.<>c__DisplayClass34_1.<CreateWorld>b__1(Vector2i columnPos)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.WorldGenerator.WorldGeneratorPlugin.CreateWorld()
   at Eco.WorldGenerator.WorldGeneratorPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
Aborted (core dumped)
[root@rm-1 134 rm1wws.de ~/eco]#

```

**Comment by D3nnis3n** [comment]
You need to install libgdiplus - this is not a bug. Install the library and it works :)

**Comment by enexusde** [comment]
Could you please improve the documentation?

**Comment by D3nnis3n** [comment]
The use of the linux server is intended for experienced users. Reading a error message, identifying missing libraries and installing them is pretty much mandatory basic knowledge for anyone working with Linux. Nontheless, this very exact problem is already mentioned on the Wiki, so there is nothing on our side to do: https://wiki.play.eco/en/Server_on_Linux

**Comment by enexusde** [comment]
I am an experienced user and I expected to have a readme.txt in the root of the project. As long as we have no installer a readme.txt would be helpfull.

**Comment by D3nnis3n** [comment]
We have no plans to add such a file.
