### ISSUE TITLE
Trying to pick up vehicle on law protected by law causing server crash

### ISSUE THREAD

**Issue by BigWolfChris** [StrangeLoopGames/EcoIssues#19905]
A player is trying to pick up a "crashed" steam truck on land that is prevented from doing so by law, it is throwing the following exception in the logs, and then crashing the server

`[106] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Laws.LawUtil.AnyTriggerSpecifies(LawSection section, Type triggerType, String propertyName, Type typeToMatch)
   at Eco.Gameplay.Civics.Misc.CivicsUtils.ShouldStopCaptiolChangingAction(Type action, String propName, LawSection section)
   at Eco.Gameplay.GameActions.PlaceOrPickUpObject.CanPreventStatic(LawSection section)
   at Eco.Gameplay.GameActions.PlaceOrPickUpObject.CanPrevent(LawSection section)
   at Eco.Gameplay.Civics.Laws.LawUtil.TryPrevent(LegalAction legalAction, Law law, IContextObject action)
   at Eco.Gameplay.Civics.Prevent_LegalAction.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.LegalAction.PerformAndProcessResullt(Law law, GameAction action)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Conditional_LegalAction.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.LegalAction.PerformAndProcessResullt(Law law, GameAction action)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.Law.Perform(GameAction action)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, List`1 actions, IEnumerable`1 preTests, IEnumerable\`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Objects.WorldObject.TryPickUp(Player player, Single caloriesNeeded)
   at HammerItem.PickupDialog(WorldObject obj, Player player) in /home/ecoserver/serverfiles/Mods/Tools/HammerItem.cs:line 116`

**Comment by IcedForge** [comment]
Clarified a bit on discord but thanks you again for reporting these things.
Using the following law (example)will cause the client to disconnect with a crash NRE
![Screenshot_2](https://user-images.githubusercontent.com/24981362/104125096-dc1a4700-5354-11eb-944e-08b2faeea456.jpg)


This happens any time you are using a nested Prevent ( as a result of Condition usage )
Not specific to what the condition is, just the trigger and using conditional prevents.
