### ISSUE TITLE
9.1.9 Entire servers users kicked back to main menu

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19906]
All users got kicked back to main menu at same time, server remained online and allowed connection again, it did it about week ago but was not able to get player.logs

Files attached

![image](https://user-images.githubusercontent.com/61889138/103583565-d4335080-4ed7-11eb-90d6-7dcc4bf7879c.png)

Text of the above
[21:55:03.249] [93] [ Info] [Eco] Caught exception when trying to dump a prior exception: The process cannot access the file 'E:\9.1.9\Dump\ClientUpdateException Exception 01045502.ecodmp' because it is being used by another process. 
[21:55:03.249] [96] [ Info] [Eco] Caught exception when trying to dump a prior exception: The process cannot access the file 'E:\9.1.9\Dump\ClientUpdateException Exception 01045502.ecodmp' because it is being used by another process. 
[21:55:03.249] [20] [ Info] [Eco] Caught exception when trying to dump a prior exception: The process cannot access the file 'E:\9.1.9\Dump\ClientUpdateException Exception 01045502.ecodmp' because it is being used by another process. 
[21:55:03.249] [82] [ Info] [Eco] Caught exception when trying to dump a prior exception: The process cannot access the file 'E:\9.1.9\Dump\ClientUpdateException Exception 01045502.ecodmp' because it is being used by another process. 
[21:55:03.998] [90] [ Info] [Eco] Uploaded crash report
 
[21:55:03.998] [15] [ Info] [Eco] Uploaded crash report
 
[21:55:04.066] [102] [ Info] [Eco] Uploaded crash report
 
[21:55:04.066] [102] [ Info] [Eco] Uploaded crash report
 
[21:55:04.092] [102] [ Info] [Eco] Uploaded crash report

My player log
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5766962/Player.log)

NomNom player log
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5766968/Player.log)

Server dump log file though think its useless as server had several at same time
[ClientUpdateException Exception 01045502.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5766964/ClientUpdateException.Exception.01045502.zip)

**Comment by IcedForge** [comment]
Thanks for reporting as always! Great work!
Dmp file content looks like a transport contract exploded 
need to further check contracts in general for these types of issues.
```

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClauseTransport.get_Contents()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass19_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'NameToObj' of 'Eco.Core.Systems.Registrar'
Error during packaging property 'Clauses' of 'Eco.Gameplay.Economy.Contracts.Contract'
Error during packaging property 'Contents' of 'Eco.Gameplay.Economy.Contracts.ContractClauseTransport'

--END DUMP--

```

**Comment by SlayksWood** [comment]
> Multiple users all kicked at once
> 
> --BEGIN DUMP--
> Dump Time
> 04/28/2021 18:10:05
> 
> Exception
> Exception: NullReferenceException
> Message:Object reference not set to an instance of an object.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
> at Eco.Gameplay.Economy.Contracts.ContractClauseTransport.get_Contents()
> at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.b__0(TTarget target)
> at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
> Outer Exceptions:
> Error during packaging property 'NameToObj' of 'Eco.Core.Systems.Registrar'
> Error during packaging property 'Clauses' of 'Eco.Gameplay.Economy.Contracts.Contract'
> Error during packaging property 'Contents' of 'Eco.Gameplay.Economy.Contracts.ContractClauseTransport'
> 
> --END DUMP--
> 
> ![image](https://user-images.githubusercontent.com/61889138/116444987-434d0000-a84d-11eb-81d2-3a13cb76b14f.png)
> 
> ![image](https://user-images.githubusercontent.com/61889138/116445009-49db7780-a84d-11eb-9d75-2138c368bc4b.png)
