### ISSUE TITLE
Players unable to log on - exception error.  6.0 e34aa2e5

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#1996]
Players on server unable to log in with this message "Caught Exception:  Exception has been thrown by a target of an invocation.  The player has no clue what that message means or is telling them to do.  Not sure what exception was thrown but then multiple players complained that the server was showing offline in browser for a few minutes like it crashed.  There was a crash log as well as several exception logs.

This is 6.0 alpha e34aa2e5

https://www.dropbox.com/s/qa1svbn6n02xj1w/2531_Dump.zip?dl=0

**Comment by MarjieAVolk** [comment]
Exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Economy.Reputation.get_ReputationTitle()
   at Eco.Gameplay.Economy.Reputation.ToString()
   at Eco.Gameplay.Players.User.RepUILink()
   at Eco.Gameplay.Property.AuthorizationKey.get_OwnerDisplay()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Eco.Core.Controller.ControllerManager.PackageProperty(BSONObject bson, INetClient boundClient, IController controller, SyncPropertyInfo propertyInfo)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, String memberName)
   at Eco.Core.Controller.ControllerManager.SendChanges()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
