### ISSUE TITLE
holding 1 log w/ axe, left click on cart with more logs = crash

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#1997]
#1998 

Staging Alpha 6.0.0 #E34aa2e5

> possibly related to my other bug report
NOT related to item stack being over the limit (10) 

i was repeatedly kick for Inactivity after i tried to pull out wood from this (ONLY a server restart stoped the repeated kicks for inactivity)
![image](https://user-images.githubusercontent.com/30765409/29746709-438cb18e-8b26-11e7-89b4-7126323da108.png)

(this report was possable from the item limit being >10 of the wood i was trying to pickup

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Changes could not be applied, the requested operation would result in an invalid inventory state.

Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.Modify(Action`1 callback, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnAct(InteractionContext context, Func`2 resultFunc)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment]
Ah, I've fixed this already
