### ISSUE TITLE
[0.9.2 staging-1896] Receive Permission contract crash

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19977]
Step to reproduce:
- Player on create contract like this (vehicle was fuelled):
![image](https://user-images.githubusercontent.com/45708377/104179814-7e056680-541d-11eb-88f8-5cfc3b6a3ed1.png)
- and post it
- Player 2 accept this contract:
![image](https://user-images.githubusercontent.com/45708377/104179877-92e1fa00-541d-11eb-90bb-d5acee38ba18.png)
- Player 1 change truck owner to player 2:
![image](https://user-images.githubusercontent.com/45708377/104180122-d63c6880-541d-11eb-96c0-8d9e1e4d7b27.png)
- yes:
![image](https://user-images.githubusercontent.com/45708377/104180154-de94a380-541d-11eb-9ce2-f247427714cf.png)
- Player 2 pick up this vehicle and place it again!!! Important! I made this first time and couldn't reproduce a several times after without this point.
- Player 2 open this contract:
![image](https://user-images.githubusercontent.com/45708377/104180345-10a60580-541e-11eb-8a18-e942c6773d02.png)
- and press 'Job finished':
![image](https://user-images.githubusercontent.com/45708377/104180382-1ac80400-541e-11eb-8c42-4c3f21ba2a5b.png)
- crash:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClausePermissions.SetAuth(User user, Boolean set)
   at Eco.Gameplay.Economy.Contracts.ContractClausePermissions.<>c__DisplayClass30_0.<TrySucceed>b__0()
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Economy.Contracts.Contract.ConfigureAndTryPerform(WorkableAction action, Action`2 checkClause, User citizen, Boolean notify, Boolean forced)
   at Eco.Gameplay.Economy.Contracts.Contract.FinishContract(User user, Boolean forced)
   at Eco.Gameplay.Economy.Contracts.Contract.JobFinished(User user)
   at Eco.Gameplay.Economy.Contracts.Contract.JobFinished(Player player)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```
[Receive permission contract crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5795602/Receive.permission.contract.crash.txt)
 
found from #19896.

**Comment by SlayksWood** [comment]
when first player try to delete this contract Server was crashed.
