### ISSUE TITLE
Problem with my own Server

### ISSUE THREAD

**Issue by xXMITCHOo** [StrangeLoopGames/EcoIssues#20146]
Hello there, today i closed my server and afterward when i start the server i got a error. 

I tried to start new server and use my backup files but I always got the same error.

thank you 

there is the Dump file i got : 

--BEGIN DUMP--
Dump Time
01/23/2021 16:13:59

Exception
Exception: InvalidDataException
Message:Error decoding Referenceable
Source:Eco.Core

System.IO.InvalidDataException: Error decoding Referenceable
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeReferenceableEnumerable(BinaryReader reader, Object decodeTarget, Int32 numElements)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Decode(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream)
   at Eco.Core.Serialization.DataStore.<>cDisplayClass47_1`1.<LoadAsync>b1()
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
Error(s) occurred when loading World (Error decoding Referenceable)

--END DUMP--

**Comment by D3nnis3n** [comment]
Can you attach your broken world file?

**Comment by xXMITCHOo** [comment]
i hope these are the good file.

https://www.dropbox.com/s/w4p82ia6kipgle4/Game.db?dl=0
https://www.dropbox.com/s/3k4jkqddhvbw5gv/Game.eco?dl=0

**Comment by mirasrael** [comment]
Hi @xXMITCHOo 
Seems like your save file broken. Seems like you have to restore from backup. If you can attach backup file here it may help with investigation why save became broken.

**Comment by xXMITCHOo** [comment]
here's my only backup left

https://www.dropbox.com/s/yo8vpidsoz6sgs6/Game%2014%20jan.eco?dl=0
https://www.dropbox.com/s/2a3u3nb0fc4s0y3/Game%2018%20jan.eco?dl=0
https://www.dropbox.com/s/aob13emdrk75dxa/Game%2022%20jan%202.eco?dl=0
https://www.dropbox.com/s/xcy3r2ihxf5ywfk/Game%2022%20jan.eco?dl=0

**Comment by mirasrael** [comment]
@xXMITCHOo I checked all these files and they all corrupted (non valid zip files). I checked binary content and they only have zeroes inside. For original file it also seems like some kind of binary corruption, but I didn't found how it may happen in code.
All broken backups may signal that you have some problems with either Windows, disk drive system or may be viruses which may corrupt files. 
Also in the original save file it has broken zip entry which fails to load. I didn't find any way how it may be corrupted internally in code, so it looks like it was corrupted externally.
I recovered save in case if you need it, but it will miss few land pieces in some cases down to the bottom layer: https://drive.google.com/file/d/1S-UPv7YHfBEyExTkMOlUXOV160SwoeZV/view?usp=sharing

**Comment by xXMITCHOo** [comment]
now i have deleted all my folder to restard a game and this happen
![image](https://user-images.githubusercontent.com/77902334/105928248-95467580-6013-11eb-92ee-3492d3136f54.png)

**Comment by D3nnis3n** [comment]
Please install the latest VC++ Redistributables from https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by WeaselDog** [comment]
Hi @xXMITCHOo . If you are still having this issue after updating, please let us know.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
