### ISSUE TITLE
[0.9.2.0 beta staging-1911] ResidentOfDistrict causes Server Crash

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#20182]
Hello,
 for testing purpuse i have created below law:
![image](https://user-images.githubusercontent.com/47274045/105897972-2b30cf00-6019-11eb-8840-2963b91f666e.png)

While the change resident trigger works fine, the server is going to crash all the times any user is claiming new plots. Below you can find error log by the server:

`[12:08:37] [Server Initialization]... Finished in 71.267,1ms
;49mSystem.AggregateException: One or more errors occurred. (Nullable object must have a value.)

System.InvalidOperationException: Nullable object must have a value.
   at Eco.Gameplay.Civics.GameValues.Values.ResidentOfDistrict.Value(IContextObject action)
   at Eco.Gameplay.Civics.Demographics.Demographic.<>c__DisplayClass52_0.<CacheUsers>b__0(User user)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Eco.Gameplay.Civics.Demographics.Demographic.CacheUsers()
   at Eco.Gameplay.Civics.Demographics.DemographicManager.DoDemographicUpdate(Demographic limitToDemographic, Boolean suppressChangeNotice)
   at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
[02:45:01] Saving...
[02:45:03] Saving... Finished in 1.888,6ms
[02:45:04] System.InvalidOperationException: Nullable object must have a value.
   at Eco.Gameplay.Civics.GameValues.Values.ResidentOfDistrict.Value(IContextObject action)
   at Eco.Gameplay.Civics.Demographics.Demographic.<>c__DisplayClass52_0.<CacheUsers>b__0(User user)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Eco.Gameplay.Civics.Demographics.Demographic.CacheUsers()
   at Eco.Gameplay.Civics.Demographics.DemographicManager.DoDemographicUpdate(Demographic limitToDemographic, Boolean suppressChangeNotice)
   at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Civics.CivicsPlugin.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__33_0(PluginRegistration reg)
[02:45:04] Shutdown finished`

**Comment by SlayksWood** [comment]
@Alteraner Thank you for the report. Did you have enabled or disabled Rent feature?
![image](https://user-images.githubusercontent.com/45708377/105968052-a33dda00-6097-11eb-85e2-f462ae849963.png)

**Comment by Alteraner** [comment]
Hello @SlayksWood,
 i have enabled it. But Resident trigger is not part of the rental system, isn't it. It's not marked in as it is in the trigger menu...

**Comment by IcedForge** [comment]
Thank you for reporting this. It should be resolved on release build.
