### ISSUE TITLE
[9.2 Staging] Lite Exception with Server Start

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#20180]
Did have this Error sometimes. and after 3rd attempt Server starts normal

[10:40:11] LiteDB.LiteException: Database lock timeout when entering in transaction mode after 00:01:00
   at LiteDB.Engine.LockService.EnterTransaction()
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable1.ToDocuments()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator2.ToArray()
   at Eco.Stats.Stats.SquashAggregatableStats()
   at Eco.Core.Utils.Threading.ActionUtils.<>cDisplayClass1_0.<AsAsyncCancellableAction>b0(CancellationToken _)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.IntervalActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Stats.Stats.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__33_0(PluginRegistration reg)

**Comment by Alteraner** [comment]
Hello, this issue occures quite often in the server error log and sometimes it ends with server crash. I recommend to priorise this topic:

`[10:38:06] Error inserting stat of type CreateWorkOrder into databaseLiteDB.LiteException: Database lock timeout when entering in transaction mode after 00:01:00
   at LiteDB.Engine.LockService.EnterTransaction()
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
[10:38:06] Error inserting stat of type ItemCraftedAction into databaseLiteDB.LiteException: Database lock timeout when entering in transaction mode after 00:01:00
   at LiteDB.Engine.LockService.EnterTransaction()
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)`

**Comment by mirasrael** [comment]
Hi @Alteraner Thanks for report. Can you make server process dump next time when you have this error?

**Comment by Alteraner** [comment]
@mirasrael, what do you mean with process dump? You want me to send the files in ECO dump folder or what do you want me to do?

**Comment by mirasrael** [comment]
@Alteraner no, I mean in Windows Process Manager you can select Eco Server process, right click on it and then select "Create memory dump". Also, are you using SSD disk for Eco Server?

**Comment by Alteraner** [comment]
I'm using an SSD disk but the mentioned server is running under Linux. I need to check how to create a memory dump within linux. will let you know once the issue reoccur...

**Comment by TwixterZ** [comment]
@Alteraner Its safe to say issue did not re-occur since you last reported this, can you confirm so we can close this issue?

**Comment by Alteraner** [comment]
Hello, yes i did not observe the issue any more. Thanks for your support.

**Comment by TwixterZ** [comment]
@Alteraner, happy to hear that.
