### ISSUE TITLE
Contracts exception selecting 'Build a room'

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2021]
Was using Eric's contract board on test server

Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC ChangeClause on Contract!

Specified argument was out of the range of valid values.
Parameter name: index

Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.RemoveAt(Int32 index)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass12_0.<RemoveAt>b__0()
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Gameplay.Economy.Contracts.ClauseListExtensions.ChangeClause(IClauseList list, Int32 index, String newClauseType)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by SeanAtr0n** [comment]
Can't seem to reproduce it now... initially I tried to make a contract to add items, opened the item selection UI and it was empty, couldn't select anything then switched to build a room and hit this exception.

**Comment by johnkslg** [comment]
Cant repro, made a bunch of fixes to contracts, may have fixed whatever it was.  Closing for now.
