### ISSUE TITLE
9.2.1 Consistent Crash related to Animal AI

### ISSUE THREAD

**Issue by thetestgame** [StrangeLoopGames/EcoIssues#20226]
We are currently experiencing a crash every 10-15 minutes or so relating to Animal Behavior and it has totally brought our server to a halt.

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Simulation.Agents.Animal.FindFreeSpace(Vector3 curPos, Boolean& habitable)
   at Eco.Simulation.Agents.Animal.Stop()
   at Eco.Simulation.Agents.Animal.ChangeState(AnimalState state, Single duration, Boolean stopMovement)
   at Eco.Simulation.Agents.AI.Brain.<>c__DisplayClass13_0.<Anim>b__0(Behavior`1 beh, Animal animal)
   at Eco.Simulation.Agents.AI.BehaviorBasic`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorSelector`1.Do(T context)
   at Eco.Simulation.Agents.AI.Brain.TickBehaviors(Animal animal)
   at Eco.Simulation.Agents.AI.Brain.Tick(Animal animal)
   at Eco.Simulation.Agents.Animal.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Simulation.EcoSim.<DoTick>b__41_0()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 ```

[log_210128092721.log](https://github.com/StrangeLoopGames/EcoIssues/files/5891261/log_210128092721.log)

**Comment by thetestgame** [comment]
Save that caused this error.
https://drive.google.com/file/d/1vX8CZwYO4GpvFnjtIO14SaJ5sNycnFGn/view?usp=sharing

**Comment by WeaselDog** [comment]
Thanks for the save. It helped with testing.
