### ISSUE TITLE
[0.9.2.1 release] Rent related crash even when it is disabled

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#20231]
We are getting a lot of rent related crashes, regardless if experimental mode is enabled. I do not have clear reproduction steps at this time.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.Deed.get_IsRentable()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'RentableDeeds' of 'Eco.Gameplay.Property.PropertyManager'</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
UnityEngine.Experimental.Audio.SampleFramesHandler:Invoke(AudioSampleProvider, UInt32)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass63_0:<Initialize>b__0()
UnityEngine.DisplaysUpdatedDelegate:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
UnityEngine.DisplaysUpdatedDelegate:Invoke()
```

**Comment by SlayksWood** [comment]
dup #20211 at least exception is the same. Will investigate in one issue.
