### ISSUE TITLE
Server Issue: Can't Load My Save

### ISSUE THREAD

**Issue by Carcol12** [StrangeLoopGames/EcoIssues#20255]
This is the server log:

[17:52:11.813] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[17:52:11.829] [1] [ Info] [Eco] [Eco Server 0.9.1.9 beta release-136]
 
[17:52:11.814] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[17:52:11.828] [1] [ Info] [Eco] [Eco Server 0.9.1.9 beta release-136]
 
[17:52:11.987] [5] [ Info] [Eco] [Starting [PerformancePlugin]]...  
[17:52:11.987] [5] [ Info] [Eco] [Starting [PerformancePlugin]]... [Finished in 0.3ms]
 
[17:52:11.987] [5] [ Info] [Eco] [Server Initialization]...  
[17:52:11.986] [5] [ Info] [Eco] [Starting [PerformancePlugin]]...  
[17:52:11.986] [5] [ Info] [Eco] [Starting [PerformancePlugin]]... [Finished in 0.3ms]
 
[17:52:11.986] [5] [ Info] [Eco] [Server Initialization]...  
[17:52:12.972] [5] [ Info] [Eco] Starting LocalizationPlugin...  
[17:52:12.972] [5] [ Info] [Eco] Starting LocalizationPlugin... Finished in 0.4ms
 
[17:52:12.973] [5] [ Info] [Eco] Starting LocalizationPlugin...  
[17:52:12.973] [5] [ Info] [Eco] Starting LocalizationPlugin... Finished in 0.2ms
 
[17:52:12.997] [5] [ Info] [Eco] Starting DifficultySettings...  
[17:52:12.997] [5] [ Info] [Eco] Starting DifficultySettings... Finished in 0.0ms
 
[17:52:12.996] [5] [ Info] [Eco] Starting DifficultySettings...  
[17:52:12.996] [5] [ Info] [Eco] Starting DifficultySettings... Finished in 0.0ms
 
[17:52:13.086] [5] [ Info] [Eco] Loading mods...  
[17:52:13.086] [5] [ Info] [Eco] Loading mods...  
[17:52:22.164] [1] [ Info] [Eco] Mods recompiled with warnings.
 
[17:52:22.177] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[17:52:22.305] [1] [ Info] [Eco] Mods recompiled with warnings.
 
[17:52:22.319] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[17:52:22.670] [5] [ Info] [Eco] Loading mods... Finished in 9,583.3ms
 
[17:52:22.670] [5] [ Info] [Eco] Starting ModKitPlugin...  
[17:52:22.670] [5] [ Info] [Eco] Starting ModKitPlugin... Finished in 0.0ms
 
[17:52:22.670] [5] [ Info] [Eco] Initializing Simulation Types...  
[17:52:22.829] [5] [ Info] [Eco] Loading mods... Finished in 9,742.8ms
 
[17:52:22.829] [5] [ Info] [Eco] Starting ModKitPlugin...  
[17:52:22.829] [5] [ Info] [Eco] Starting ModKitPlugin... Finished in 0.0ms
 
[17:52:22.829] [5] [ Info] [Eco] Initializing Simulation Types...  
[17:52:23.201] [5] [ Info] [Eco] Starting NetworkManager...  
[17:52:23.201] [5] [ Info] [Eco] Starting NetworkManager... Finished in 0.0ms
 
[17:52:23.225] [5] [ Info] [Eco] Starting BackupPlugin...  
[17:52:23.225] [5] [ Info] [Eco] Starting BackupPlugin... Finished in 0.0ms
 
[17:52:23.304] [5] [ Info] [Eco] Starting NetworkManager...  
[17:52:23.304] [5] [ Info] [Eco] Starting NetworkManager... Finished in 0.1ms
 
[17:52:23.325] [5] [ Info] [Eco] Starting BackupPlugin...  
[17:52:23.325] [5] [ Info] [Eco] Starting BackupPlugin... Finished in 0.0ms
 
[17:52:23.386] [13] [Error] [Eco] Couldn't open save 'Planet Dirt'.
Exception: IOException
Message:The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Storage\Planet Dirt.eco' because it is being used by another process.
Source:System.Private.CoreLib

System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Storage\Planet Dirt.eco' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager.LoadSaveAsync(Boolean restoreBackupIfSaveMissing)
 
[17:52:24.146] [5] [ Info] [Eco] Initializing Simulation Types... Finished in 1,314.3ms
 
[17:52:24.146] [5] [ Info] [Eco] Initializing items...  
[17:52:24.221] [5] [ Info] [Eco] Initializing Simulation Types... Finished in 1,547.8ms
 
[17:52:24.221] [5] [ Info] [Eco] Initializing items...  
[17:52:24.247] [5] [ Info] [Eco] Starting WorldGeneratorPlugin...  
[17:52:24.256] [5] [ Info] [Eco] Starting WorldGeneratorPlugin... Finished in 0.0ms
 
[17:52:24.281] [5] [ Info] [Eco] Starting WorldGeneratorPlugin...  
[17:52:24.281] [5] [ Info] [Eco] Starting WorldGeneratorPlugin... Finished in 0.0ms
 
[17:52:26.647] [5] [ Info] [Eco] [Server Initialization]... Finished in 14,658.6ms
 
[17:52:26.647] [13] [Error] [Eco] Failed to load server, Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Core

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Serialization.DataStore.Load(String fileName)
   at Eco.Core.Plugins.StorageManager.Load(String fileName)
   at Eco.Core.Serialization.EcoSerializer.InitializeInternal()
   at Eco.Core.Serialization.EcoSerializer.Initialize()
   at Eco.Core.Plugins.StorageManager.Initialize()
   at Eco.Core.Plugins.StorageManager..ctor(PluginConfig`1 config, IFileStorage baseStorage, Boolean enableBackups)
   at Eco.Core.Plugins.StorageManager..ctor()
Outer Exceptions:
Exception has been thrown by the target of an invocation.
 
[17:52:26.669] [1] [Error] [Eco] Unhandled errorSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.AddPlugin[T](Object[] p)
   at Eco.Server.PluginManager.<>c__DisplayClass31_0.<AddPluginsAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo)
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Serialization.DataStore.Load(String fileName)
   at Eco.Core.Plugins.StorageManager.Load(String fileName)
   at Eco.Core.Serialization.EcoSerializer.InitializeInternal()
   at Eco.Core.Serialization.EcoSerializer.Initialize()
   at Eco.Core.Plugins.StorageManager.Initialize()
   at Eco.Core.Plugins.StorageManager..ctor(PluginConfig`1 config, IFileStorage baseStorage, Boolean enableBackups)
   at Eco.Core.Plugins.StorageManager..ctor()
 
[17:52:26.801] [5] [ Info] [Eco] Starting StorageManager...  
[17:52:26.801] [5] [ Info] [Eco] Starting StorageManager... Finished in 0.0ms
 
[17:52:26.804] [5] [ Info] [Eco] Loading GameData...  
[17:52:26.828] [5] [ Info] [Eco] Loading GameData... Finished in 23.4ms
 
[17:52:26.828] [5] [ Info] [Eco] Starting GameDataPlugin...  
[17:52:26.828] [5] [ Info] [Eco] Starting GameDataPlugin... Finished in 0.0ms
 
[17:52:26.828] [5] [ Info] [Eco] Loading Pause...  
[17:52:26.828] [5] [ Info] [Eco] Loading Pause... Finished in 0.2ms
 
[17:52:26.868] [5] [ Info] [Eco] Starting Stats...  
[17:52:26.868] [5] [ Info] [Eco] Starting Stats... Finished in 0.0ms
 
[17:52:26.868] [5] [ Info] [Eco] Starting PausePlugin...  
[17:52:26.868] [5] [ Info] [Eco] Starting PausePlugin... Finished in 0.0ms
 
[17:52:28.923] [5] [ Info] [Eco] Initializing items... Finished in 4,701.6ms
 
[17:52:28.923] [5] [ Info] [Eco] Initializing skills...  
[17:52:28.951] [5] [ Info] [Eco] Initializing skills... Finished in 27.0ms
 
[17:52:28.968] [5] [ Info] [Eco] Loading World...  
[17:52:29.534] [5] [ Info] [Eco] Loading World... Finished in 565.2ms
 
[17:52:29.534] [5] [ Info] [Eco] Initializing world...  
[17:52:30.062] [5] [ Info] [Eco] Initializing world... Finished in 526.0ms
 
[17:52:30.062] [5] [ Info] [Eco] Starting WorldPlugin...  
[17:52:30.062] [5] [ Info] [Eco] Starting WorldPlugin... Finished in 0.0ms
 
[17:52:30.062] [5] [ Info] [Eco] Loading Time...  
[17:52:30.062] [5] [ Info] [Eco] Loading Time... Finished in 0.6ms
 
[17:52:30.062] [5] [ Info] [Eco] Starting TimePlugin...  
[17:52:30.062] [5] [ Info] [Eco] Starting TimePlugin... Finished in 0.0ms
 
[17:52:30.062] [5] [ Info] [Eco] Loading Reputation...  
[17:52:30.062] [5] [ Info] [Eco] Loading Reputation... Finished in 2.8ms
 
[17:52:30.062] [5] [ Info] [Eco] Starting ReputationPlugin...  
[17:52:30.068] [5] [ Info] [Eco] Starting ReputationPlugin... Finished in 0.0ms
 
[17:52:30.068] [5] [ Info] [Eco] Starting PlayerHousingManager...  
[17:52:30.068] [5] [ Info] [Eco] Starting PlayerHousingManager... Finished in 0.0ms
 
[17:52:30.106] [5] [ Info] [Eco] Loading Users...  
[17:52:30.173] [5] [ Info] [Eco] Loading Users... Finished in 66.4ms
 
[17:52:30.173] [5] [ Info] [Eco] Starting UserManager...  
[17:52:30.173] [5] [ Info] [Eco] Starting UserManager... Finished in 0.0ms
 
[17:52:30.173] [5] [ Info] [Eco] Starting EcoObjectManager...  
[17:52:30.173] [5] [ Info] [Eco] Starting EcoObjectManager... Finished in 0.0ms
 
[17:52:30.173] [5] [ Info] [Eco] Starting DataExporter...  
[17:52:30.173] [5] [ Info] [Eco] Starting DataExporter... Finished in 0.0ms
 
[17:52:30.173] [5] [ Info] [Eco] Loading Garbage...  
[17:52:30.177] [5] [ Info] [Eco] Loading Garbage... Finished in 1.4ms
 
[17:52:30.177] [5] [ Info] [Eco] Starting GarbagePlugin...  
[17:52:30.177] [5] [ Info] [Eco] Starting GarbagePlugin... Finished in 0.0ms
 
[17:52:30.177] [5] [ Info] [Eco] Loading EconomyManager...  
[17:52:30.177] [5] [ Info] [Eco] Starting VoiceManager...  
[17:52:30.177] [5] [ Info] [Eco] Starting VoiceManager... Finished in 0.0ms
 
[17:52:30.206] [5] [ Info] [Eco] Loading EconomyManager... Finished in 28.6ms
 
[17:52:30.206] [5] [ Info] [Eco] Starting EconomyPlugin...  
[17:52:30.206] [5] [ Info] [Eco] Starting EconomyPlugin... Finished in 0.0ms
 
[17:52:30.206] [5] [ Info] [Eco] Loading Disasters...  
[17:52:30.206] [5] [ Info] [Eco] Loading Disasters... Finished in 0.1ms
 
[17:52:30.206] [5] [ Info] [Eco] Loading ViewTypeData...  
[17:52:30.208] [5] [ Info] [Eco] Starting DisasterPlugin...  
[17:52:30.208] [5] [ Info] [Eco] Starting DisasterPlugin... Finished in 0.0ms
 
[17:52:30.208] [5] [ Info] [Eco] Loading ViewTypeData... Finished in 1.7ms
 
[17:52:30.208] [5] [ Info] [Eco] Loading Chat...  
[17:52:30.208] [5] [ Info] [Eco] Loading Chat... Finished in 2.0ms
 
[17:52:30.208] [5] [ Info] [Eco] Loading Property...  
[17:52:30.208] [5] [ Info] [Eco] Starting ChatServer...  
[17:52:30.208] [5] [ Info] [Eco] Starting ChatServer... Finished in 0.0ms
 
[17:52:30.238] [5] [ Info] [Eco] Loading Property... Finished in 26.6ms
 
[17:52:30.238] [5] [ Info] [Eco] Starting PropertyManager...  
[17:52:30.238] [5] [ Info] [Eco] Starting PropertyManager... Finished in 0.0ms
 
[17:52:30.240] [5] [ Info] [Eco] Starting MinimapManager...  
[17:52:30.240] [5] [ Info] [Eco] Starting MinimapManager... Finished in 0.0ms
 
[17:52:30.276] [5] [ Info] [Eco] Loading Plants...  
[17:52:30.493] [5] [ Info] [Eco] Loading Plants... Finished in 216.8ms
 
[17:52:30.493] [5] [ Info] [Eco] Initializing plants...  
[17:52:31.611] [5] [ Info] [Eco] Initializing plants... Finished in 1,117.0ms
 
[17:52:31.668] [5] [ Info] [Eco] Starting EcoSim...  
[17:52:31.668] [5] [ Info] [Eco] Starting EcoSim... Finished in 0.0ms
 
[17:52:31.668] [5] [ Info] [Eco] Loading RouteProbing...  
[17:52:33.470] [5] [ Info] [Eco] Loading RouteProbing... Finished in 1,798.2ms
 
[17:52:33.480] [5] [ Info] [Eco] Starting RouteProbingPlugin...  
[17:52:33.480] [5] [ Info] [Eco] Starting RouteProbingPlugin... Finished in 0.0ms
 
[17:52:33.493] [5] [ Info] [Eco] Loading Layers...  
[17:52:33.733] [5] [ Info] [Eco] Loading Layers... Finished in 246.7ms
 
[17:52:33.740] [5] [ Info] [Eco] Initializing world layers...  
[17:52:33.740] [5] [ Info] [Eco] Loading ClimateSim...  
[17:52:33.740] [5] [ Info] [Eco] Loading ClimateSim... Finished in 0.7ms
 
[17:52:34.286] [5] [ Info] [Eco] Starting ControllerManager...  
[17:52:34.286] [5] [ Info] [Eco] Starting ControllerManager... Finished in 0.0ms
 
[17:52:35.205] [5] [ Info] [Eco] Initializing world layers... Finished in 1,464.9ms
 
[17:52:35.205] [5] [ Info] [Eco] Starting WorldLayerManager...  
[17:52:35.205] [5] [ Info] [Eco] Starting WorldLayerManager... Finished in 0.0ms
 
[17:52:35.205] [5] [ Info] [Eco] Starting EconomyTracker...  
[17:52:35.205] [5] [ Info] [Eco] Starting EconomyTracker... Finished in 0.0ms
 
[17:52:35.208] [5] [ Info] [Eco] Starting UserTracker...  
[17:52:35.208] [5] [ Info] [Eco] Starting UserTracker... Finished in 0.0ms
 
[17:52:35.208] [5] [ Info] [Eco] Loading Civics...  
[17:52:35.224] [5] [ Info] [Eco] Loading Civics... Finished in 6.1ms
 
[17:52:35.224] [5] [ Info] [Eco] Starting CivicsPlugin...  
[17:52:35.224] [5] [ Info] [Eco] Starting CivicsPlugin... Finished in 0.0ms
 
[17:52:35.335] [5] [ Info] [Eco] Loading WorldObjects...  
[17:52:35.335] [5] [ Info] [Eco] Loading WorldObjects... Finished in 4.9ms
 
[17:52:35.335] [5] [ Info] [Eco] Starting WorldObjectManager...  
[17:52:35.335] [5] [ Info] [Eco] Starting WorldObjectManager... Finished in 0.0ms
 
[17:52:35.335] [5] [ Info] [Eco] Loading Rooms...  
[17:52:35.335] [5] [ Info] [Eco] Loading Rooms... Finished in 3.1ms
 
[17:52:35.335] [5] [ Info] [Eco] Starting RoomPlugin...  
[17:52:35.335] [5] [ Info] [Eco] Starting RoomPlugin... Finished in 0.0ms
 
[17:52:35.335] [5] [ Info] [Eco] Loading Objectives...  
[17:52:35.335] [5] [ Info] [Eco] Loading Objectives... Finished in 0.6ms
 
[17:52:35.335] [5] [ Info] [Eco] Starting ObjectivePlugin...  
[17:52:35.335] [5] [ Info] [Eco] Starting ObjectivePlugin... Finished in 0.0ms
 
[17:52:35.335] [5] [ Info] [Eco] Loading Sleep...  
[17:52:35.349] [5] [ Info] [Eco] Loading Sleep... Finished in 0.3ms
 
[17:52:35.349] [5] [ Info] [Eco] Starting SleepPlugin...  
[17:52:35.349] [5] [ Info] [Eco] Starting SleepPlugin... Finished in 0.0ms
 
[17:52:35.349] [5] [ Info] [Eco] Starting WebServerPlugin...  
[17:52:35.349] [5] [ Info] [Eco] Starting WebServerPlugin... Finished in 0.0ms
 
[17:52:35.349] [5] [ Info] [Eco] Starting IntegrationTestsPlugin...  
[17:52:35.349] [5] [ Info] [Eco] Starting IntegrationTestsPlugin... Finished in 0.0ms
 
[17:52:35.386] [5] [ Info] [Eco] Initializing registrars for CivicsPlugin...  
[17:52:35.417] [5] [ Info] [Eco] Initializing registrars for CivicsPlugin... Finished in 31.4ms
 
[17:52:35.417] [5] [ Info] [Eco] Initializing registrars for GameDataPlugin...  
[17:52:35.417] [5] [ Info] [Eco] Initializing registrars for GameDataPlugin... Finished in 6.2ms
 
[17:52:35.417] [5] [ Info] [Eco] Initializing registrars for EconomyPlugin...  
[17:52:35.443] [5] [ Info] [Eco] Initializing registrars for EconomyPlugin... Finished in 19.2ms
 
[17:52:35.790] [5] [ Info] [Eco] Initializing DifficultySettings...  
[17:52:35.790] [5] [ Info] [Eco] Initializing DifficultySettings... Finished in 0.8ms
 
[17:52:35.790] [5] [ Info] [Eco] Initializing Stats...  
[17:52:35.938] [5] [ Info] [Eco] Initializing Stats... Finished in 147.0ms
 
[17:52:35.938] [5] [ Info] [Eco] Initializing CivicsPlugin...  
[17:52:35.953] [5] [ Info] [Eco] Initializing CivicsPlugin... Finished in 14.6ms
 
[17:52:35.953] [5] [ Info] [Eco] Initializing PerformancePlugin...  
[17:52:35.953] [5] [ Info] [Eco] Initializing PerformancePlugin... Finished in 0.1ms
 
[17:52:35.953] [5] [ Info] [Eco] Initializing LocalizationPlugin...  
[17:52:36.014] [5] [ Info] [Eco] Initializing LocalizationPlugin... Finished in 59.8ms
 
[17:52:36.014] [5] [ Info] [Eco] Initializing ModKitPlugin...  
[17:52:36.396] [5] [ Info] [Eco] Initializing ModKitPlugin... Finished in 381.3ms
 
[17:52:36.396] [5] [ Info] [Eco] Initializing WorldGeneratorPlugin...  
[17:52:36.396] [5] [ Info] [Eco] Initializing WorldGeneratorPlugin... Finished in 0.3ms
 
[17:52:36.396] [5] [ Info] [Eco] Initializing TimePlugin...  
[17:52:36.396] [5] [ Info] [Eco] Initializing TimePlugin... Finished in 0.1ms
 
[17:52:36.396] [5] [ Info] [Eco] Initializing UserManager...  
[17:52:36.580] [5] [ Info] [Eco] Initializing UserManager... Finished in 182.7ms
 
[17:52:36.580] [5] [ Info] [Eco] Initializing GarbagePlugin...  
[17:52:36.585] [5] [ Info] [Eco] Initializing GarbagePlugin... Finished in 4.7ms
 
[17:52:36.585] [5] [ Info] [Eco] Initializing EconomyPlugin...  
[17:52:36.585] [5] [ Info] [Eco] Initializing EconomyPlugin... Finished in 5.1ms
 
[17:52:36.585] [5] [ Info] [Eco] Initializing PropertyManager...  
[17:52:36.601] [5] [ Info] [Eco] Initializing PropertyManager... Finished in 10.1ms
 
[17:52:36.601] [5] [ Info] [Eco] Initializing MinimapManager...  
[17:52:36.632] [5] [ Info] [Eco] Initializing MinimapManager... Finished in 31.1ms
 
[17:52:36.632] [5] [ Info] [Eco] Initializing EcoSim...  
[17:52:36.632] [5] [ Info] [Eco] Initializing EcoSim... Finished in 1.0ms
 
[17:52:36.632] [5] [ Info] [Eco] Initializing UserTracker...  
[17:52:36.632] [5] [ Info] [Eco] Initializing UserTracker... Finished in 3.5ms
 
[17:52:36.632] [5] [ Info] [Eco] Initializing WorldObjectManager...  
[17:52:36.745] [5] [ Info] [Eco] Initializing WorldObjectManager... Finished in 107.3ms
 
[17:52:36.745] [5] [ Info] [Eco] Initializing RoomPlugin...  
[17:52:36.745] [5] [ Info] [Eco] Initializing RoomPlugin... Finished in 1.5ms
 
[17:52:36.745] [5] [ Info] [Eco] Initializing SleepPlugin...  
[17:52:36.745] [5] [ Info] [Eco] Initializing SleepPlugin... Finished in 1.8ms
 
[17:52:36.745] [5] [ Info] [Eco] Initializing WorldPlugin...  
[17:52:36.745] [5] [ Info] [Eco] Ticking Active Chunks...  
[17:52:36.813] [5] [ Info] [Eco] Ticking Active Chunks... Finished in 62.6ms
 
[17:52:36.813] [5] [ Info] [Eco] Compressing Frozen Chunks...  
[17:52:37.625] [5] [ Info] [Eco] Compressing Frozen Chunks... Finished in 812.1ms
 
[17:52:38.019] [5] [ Info] [Eco] Initializing WorldPlugin... Finished in 1,270.5ms
 
[17:52:38.019] [5] [ Info] [Eco] Initializing NetworkManager...  
[17:52:38.041] [5] [ Info] [Eco] Initializing NetworkManager... Finished in 21.5ms
 
[17:52:38.041] [5] [ Info] [Eco] Initializing WorldLayerManager...  
[17:52:38.041] [5] [ Info] [Eco] Initializing WorldLayerManager... Finished in 0.1ms
 
[17:52:38.041] [5] [ Info] [Eco] Initializing WebServerPlugin...  
[17:52:40.407] [20] [ Info] [Eco] Web Server now listening on: http://0.0.0.0:3001
 
[17:52:40.407] [5] [ Info] [Eco] Initializing WebServerPlugin... Finished in 2,367.2ms
 
[17:52:40.407] [5] [ Info] [Eco] Initializing IntegrationTestsPlugin...  
[17:52:40.407] [5] [ Info] [Eco] Initializing IntegrationTestsPlugin... Finished in 0.1ms
 
[17:52:41.322] [5] [ Info] [Eco] Saving world...  
[17:52:44.920] [5] [ Info] [Eco] Saving world... Finished in 3,597.5ms
 
[17:52:44.920] [5] [ Info] [Eco] [Server Initialization]... Finished in 32,932.9ms
 
[17:53:01.737] [23] [Error] [Eco] WARN: UPnP mapping wasn't created due to an error. Server fallback to default connection settings.
 
[17:53:05.050] [5] [ Info] [Eco] Saving...  
[17:53:06.210] [5] [ Info] [Eco] Saving... Finished in 1,159.5ms
 
[17:53:06.262] [22] [ Info] [Eco] Shutdown finished

**Comment by SlayksWood** [comment]
@Carcol12 Thank you for the report. Seems you save file was opened by another program.
```
Message:The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Storage\Planet Dirt.eco' because it is being used by another process.
```
This is just like zip file, so maybe you opened it with something else too?

**Comment by mirasrael** [comment]
Or you just started game. Press escape and immediately start it again from same save file. It is known issue that server may run in background at this time. So you have to wait until it exit. This issue already fixed for 9.3.

**Comment by Carcol12** [comment]
I know I didn't open it with something else.

**Comment by Carcol12** [comment]
I just updated my game to 9.3.2 and I still cannot open my world.

**Comment by SlayksWood** [comment]
@Carcol12 we found an issue that if you double clicking on continue button you will start 2 servers and they will be crashed for this reason. Did you start the server with a single click?

**Comment by Carcol12** [comment]
No I only click once to start my server.

**Comment by IcedForge** [comment]
Hello, please reopen this issue if you still encounter the same problems after updating to 9.3.x as this now should prevent duplicate launches of the server application.
