### ISSUE TITLE
Migration exception

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2025]
https://github.com/StrangeLoopGames/EcoIssues/files/1262248/Crash.08300328.txt

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error(s) occurred when loading Objects
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.Gameplay.Objects.EcoObjectManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__4_1()
   at System.Threading.Tasks.Task.Execute()

**Comment by MarjieAVolk** [comment]
Looks like a debris serialization problem?

**Comment by EmuLegs** [comment]
Same error/dump every attempt

**Comment by MarjieAVolk** [comment]
Sure, if you have those files that could help

**Comment by EmuLegs** [comment]
Mods File : https://www.dropbox.com/s/ls2spstqb7e8fgp/Old%20Mods.rar?dl=0

Storage File : https://www.dropbox.com/s/st9sdvfiqa15rpw/Old%20Storage.rar?dl=0

Files included working with v/ Staging Alpha 6.0.0 #E34aa2e5

the storage file has a bunch of small carts with very large stacks, we have since fixed that and we are still having the problem, i will update the save / Storage file soon (add to this comment)

**Comment by EmuLegs** [comment]
please let me know if there is anything i can do to help you figure this out, as i would love to update w/ my map in one peace :p

**Comment by metachronism** [comment]
this should be all working now
