### ISSUE TITLE
Cloud world:  migration KeyNotFoundException

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#20253]
world293 and slg164729-324 on sfo2

```
Migration was performed, migrations.log was saved.
=================================================
[10:41:38] [Server Initialization]... Finished in 70,631.0ms
[10:41:38] Failed to load server, Exception was Exception: KeyNotFoundException
Message:The given key 'Eco.Core.Serialization.Migrations.DataMigrations.MemberDataInput' was not present in the dictionary.
Source:System.Private.CoreLib

System.Collections.Generic.KeyNotFoundException: The given key 'Eco.Core.Serialization.Migrations.DataMigrations.MemberDataInput' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.Core.Serialization.Migrations.DataMigrations.MemberNameChangeDataModification.Apply(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\DataMigrations\MemberNameChangeDataModification.cs:line 21
   at Eco.Core.Serialization.Migrations.DataMigration.MigrateInstance(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\DataMigration.cs:line 56
   at Eco.Core.Serialization.Migrations.AggregateMigration.MigrateInstance(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\AggregateMigration.cs:line 37
   at Eco.Core.Serialization.Migrations.MigrationManager.MigrateInstanceInternal(MigrationContext context, IEnumerable`1 migrations) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\MigrationManager.cs:line 224
   at Eco.Core.Serialization.Migrations.MigrationManager.MigrateInstance(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\MigrationManager.cs:line 146
   at Eco.Core.Serialization.Serializers.MigrationChainSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\MigrationChainSerializer.cs:line 37
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 122
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.DecodeReferenceableEntry(BinaryReader reader, Object instance) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\DictionarySerializer.cs:line 115
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.DecodeDictionary(BinaryReader reader, Object instance) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\DictionarySerializer.cs:line 96
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.Decode(BinaryReader reader, Object instance) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\DictionarySerializer.cs:line 88
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ClassSerializer.cs:line 160
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ClassMigrationSerializer.cs:line 148
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ClassSerializer.cs:line 49
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 153
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 153
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 122
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 131
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\SimpleSerializer.cs:line 665
   at Eco.Core.Serialization.CurrentSerializer.Deserialize(Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers.cs:line 48
   at Eco.Core.Serialization.EcoSerializer.Deserialize(Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers.cs:line 113
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 447
   at Eco.Core.Serialization.DataStore.Load[T](ExclusiveAccess exclusiveAccess, String folder, Action`1 onLoad, Boolean migrate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 329
   at Eco.Core.Serialization.DataStore.ExclusiveAccess.Load[T](String folder, Action`1 onLoad, Boolean migrate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 64
   at Eco.Core.Serialization.DataStore.Load[T](String folder, Action`1 onLoad, Boolean migrate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 305
   at Eco.Core.Plugins.StorageManager.LoadOrCreate[TStorageType](String folder, Action`1 onCreate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Plugins\StorageManager.cs:line 244
   at Eco.Gameplay.Property.PropertyManager..ctor() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Property\PropertyManager.cs:line 412
Outer Exceptions:
Exception has been thrown by the target of an invocation.
[10:41:38] Unhandled errorSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\PluginManager.cs:line 320
   at Eco.Server.PluginManager.AddPlugin[T](Object[] p) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\PluginManager.cs:line 317
   at Eco.Server.PluginManager.<>c__DisplayClass29_0.<AddPluginsAsync>b__1() in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\PluginManager.cs:line 212
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\PluginManager.cs:line 233
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\PluginManager.cs:line 106
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\Startup.cs:line 181
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\ApplicationHostedService.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\Main.cs:line 42
System.Collections.Generic.KeyNotFoundException: The given key 'Eco.Core.Serialization.Migrations.DataMigrations.MemberDataInput' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.Core.Serialization.Migrations.DataMigrations.MemberNameChangeDataModification.Apply(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\DataMigrations\MemberNameChangeDataModification.cs:line 21
   at Eco.Core.Serialization.Migrations.DataMigration.MigrateInstance(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\DataMigration.cs:line 56
   at Eco.Core.Serialization.Migrations.AggregateMigration.MigrateInstance(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\AggregateMigration.cs:line 37
   at Eco.Core.Serialization.Migrations.MigrationManager.MigrateInstanceInternal(MigrationContext context, IEnumerable`1 migrations) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\MigrationManager.cs:line 224
   at Eco.Core.Serialization.Migrations.MigrationManager.MigrateInstance(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\MigrationManager.cs:line 146
   at Eco.Core.Serialization.Serializers.MigrationChainSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\MigrationChainSerializer.cs:line 37
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 122
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.DecodeReferenceableEntry(BinaryReader reader, Object instance) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\DictionarySerializer.cs:line 115
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.DecodeDictionary(BinaryReader reader, Object instance) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\DictionarySerializer.cs:line 96
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.Decode(BinaryReader reader, Object instance) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\DictionarySerializer.cs:line 88
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ClassSerializer.cs:line 160
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ClassMigrationSerializer.cs:line 148
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ClassSerializer.cs:line 49
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 153
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 153
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 122
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 131
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\SimpleSerializer.cs:line 665
   at Eco.Core.Serialization.CurrentSerializer.Deserialize(Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers.cs:line 48
   at Eco.Core.Serialization.EcoSerializer.Deserialize(Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers.cs:line 113
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 447
   at Eco.Core.Serialization.DataStore.Load[T](ExclusiveAccess exclusiveAccess, String folder, Action`1 onLoad, Boolean migrate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 329
   at Eco.Core.Serialization.DataStore.ExclusiveAccess.Load[T](String folder, Action`1 onLoad, Boolean migrate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 64
   at Eco.Core.Serialization.DataStore.Load[T](String folder, Action`1 onLoad, Boolean migrate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 305
   at Eco.Core.Plugins.StorageManager.LoadOrCreate[TStorageType](String folder, Action`1 onCreate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Plugins\StorageManager.cs:line 244
   at Eco.Gameplay.Property.PropertyManager..ctor() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Property\PropertyManager.cs:line 412
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Eco.Core.Serialization.Migrations.DataMigrations.MemberDataInput' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.Core.Serialization.Migrations.DataMigrations.MemberNameChangeDataModification.Apply(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\DataMigrations\MemberNameChangeDataModification.cs:line 21
   at Eco.Core.Serialization.Migrations.DataMigration.MigrateInstance(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\DataMigration.cs:line 56
   at Eco.Core.Serialization.Migrations.AggregateMigration.MigrateInstance(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\AggregateMigration.cs:line 37
   at Eco.Core.Serialization.Migrations.MigrationManager.MigrateInstanceInternal(MigrationContext context, IEnumerable`1 migrations) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\MigrationManager.cs:line 224
   at Eco.Core.Serialization.Migrations.MigrationManager.MigrateInstance(MigrationContext context) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Migrations\MigrationManager.cs:line 146
   at Eco.Core.Serialization.Serializers.MigrationChainSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\MigrationChainSerializer.cs:line 37
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 122
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.DecodeReferenceableEntry(BinaryReader reader, Object instance) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\DictionarySerializer.cs:line 115
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.DecodeDictionary(BinaryReader reader, Object instance) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\DictionarySerializer.cs:line 96
   at Eco.Core.Serialization.Serializers.DictionarySerializer`3.Decode(BinaryReader reader, Object instance) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\DictionarySerializer.cs:line 88
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ClassSerializer.cs:line 160
   at Eco.Core.Serialization.Serializers.ClassMigrationSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ClassMigrationSerializer.cs:line 148
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ClassSerializer.cs:line 49
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 153
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 153
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 122
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 131
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\SimpleSerializer.cs:line 665
   at Eco.Core.Serialization.CurrentSerializer.Deserialize(Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers.cs:line 48
   at Eco.Core.Serialization.EcoSerializer.Deserialize(Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\Serializers.cs:line 113
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 447
   at Eco.Core.Serialization.DataStore.Load[T](ExclusiveAccess exclusiveAccess, String folder, Action`1 onLoad, Boolean migrate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 329
   at Eco.Core.Serialization.DataStore.ExclusiveAccess.Load[T](String folder, Action`1 onLoad, Boolean migrate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 64
   at Eco.Core.Serialization.DataStore.Load[T](String folder, Action`1 onLoad, Boolean migrate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Serialization\DataStore.cs:line 305
   at Eco.Core.Plugins.StorageManager.LoadOrCreate[TStorageType](String folder, Action`1 onCreate) in C:\Jenkins\workspace\Eco Release\Server\Eco.Core\Plugins\StorageManager.cs:line 244
   at Eco.Gameplay.Property.PropertyManager..ctor() in C:\Jenkins\workspace\Eco Release\Server\Eco.Gameplay\Property\PropertyManager.cs:line 412
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\PluginManager.cs:line 320
   at Eco.Server.PluginManager.AddPlugin[T](Object[] p) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\PluginManager.cs:line 317
   at Eco.Server.PluginManager.<>c__DisplayClass29_0.<AddPluginsAsync>b__1() in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\PluginManager.cs:line 212
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\PluginManager.cs:line 233
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\PluginManager.cs:line 106
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\Startup.cs:line 181
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\ApplicationHostedService.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args) in C:\Jenkins\workspace\Eco Release\Server\Eco.Server\Main.cs:line 42
```

**Comment by mirasrael** [comment]
0.9.3.0 beta remove_itween-78 and slg164729-324 have save version "0.9.3.0 beta remove_itween-78" which isn't compatible with 9.2.2 and can't be migrated.

**Comment by j3fffff** [comment]
In db it says their version is 0.9.1.9-beta
they also dont have option to pick a 9.3.0 vesrion
Also, not all new worlds were set to 9.3 version, so i dont think there is an error with new world defaulting to that.

@redwyre can you confirm that v0.9.1.9-beta (or any release version) is not actually pointing to 9.3.0

**Comment by redwyre** [comment]
`9.3` is not released yet
`0.9.2.3-beta` is the latest version

**Comment by mirasrael** [comment]
I get this version from game save file. So somehow (I don't know how) it was upgraded to 9.3 version. You can try to recover from backup.

**Comment by redwyre** [comment]
iirc, the `0.9.3.0 beta remove_itween-78` version was incorrectly picked up by cloud worlds, but that was a while ago

**Comment by j3fffff** [comment]
That explains it then. these worlds may have not been in use for awhile. but auto updated.

Is there a permanent fix so that doesnt happen again @redwyre ?
