### ISSUE TITLE
Modkit - Modded Item Issue 

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#20259]
Okay so this is mod related but is very Strange,

I have alot of modded objects, but only a select few are causing this error, out of all the other objects only  these ones are doing it, we don't know why, the code structure is exactly the same:

The Issue: 
These world objects can be crafted, placed but not picked up, when you try to pick these items up it causes this error and crashes the server:

```
[02:46:59] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.GameActions.GameActionExtensions.AffectedDeeds(GameAction action)
   at Eco.Gameplay.Auth.AuthManager.CanPerform(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Objects.WorldObject.TryPickUpNow(Player player, Inventory targetInventory, Single caloriesNeeded)
   at HammerItem.PickupDialog(WorldObject obj, Player player) in H:\Steam Library\steamapps\common\Eco Server\Mods\Tools\HammerItem.cs:line 111
Unhandled exception. System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Monitor.Exit(Object obj)
   at Eco.Gameplay.Items.InventoryLock.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Finalize()
```

Please Note! These objects are not on claimed land, have also tested on claimed land and the same error still happens

**Comment by TheKye** [comment]
Update. This issue is due to the PropertyAuthComponent Not being on a world object, this now seems to be nessecary to allow the WorldObjects to be picked up

**Comment by IcedForge** [comment]
As per discord discussion this seems to be related to the new residency permission layers extending into worldobjects auth hence the change, ill see if i can clarify a bit and checking with the code team to understand it a bit better feel free to poke me on discord in a day or so if i forget it @TheKye. Will close the issue per say as it was clarified what was causing the problem at least.
