### ISSUE TITLE
9.2.2 beta release -149 - Server Crash Randomly

### ISSUE THREAD

**Issue by Thibault-Brocheton** [StrangeLoopGames/EcoIssues#20272]
OS: Linux

Server crashed, restart worked without any problem. 

Saw this in logs before shutdown:

[22:45:36.933] [480] [Error] [Eco] System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Eco.Simulation.Agents.Animal.SetMemory(String name, Object memory)
   at Eco.Mods.Organisms.Behaviors.PredatorBehaviors.ConsiderFleeing(Animal agent, Boolean skipChance) in /home/debian/eco/server/Mods/Organisms/Animal/Behaviors/PredatorBehaviors.cs:line 61
   at Eco.Mods.Organisms.Behaviors.PredatorBehaviors.CheckAttacking(Animal agent) in /home/debian/eco/server/Mods/Organisms/Animal/Behaviors/PredatorBehaviors.cs:line 78
   at Eco.Simulation.Agents.AI.BehaviorConditional`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorSelector`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorConditional`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorSelector`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorSelector`1.Do(T context)
   at Eco.Simulation.Agents.AI.Brain.TickBehaviors(Animal animal)
   at Eco.Simulation.Agents.AI.Brain.Tick(Animal animal)
   at Eco.Simulation.Agents.Animal.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Simulation.EcoSim.<DoTick>b__41_0()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)

[22:45:36.943] [5] [ Info] [Eco] Saving...
[22:45:45.572] [5] [ Info] [Eco] Saving... Finished in 8,628.4ms

[22:46:02.198] [481] [Error] [Eco] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Eco.Simulation.Agents.Animal.SetMemory(String name, Object memory)
   at Eco.Mods.Organisms.Behaviors.PredatorBehaviors.ConsiderFleeing(Animal agent, Boolean skipChance) in /home/debian/eco/server/Mods/Organisms/Animal/Behaviors/PredatorBehaviors.cs:line 61
   at Eco.Mods.Organisms.Behaviors.PredatorBehaviors.CheckAttacking(Animal agent) in /home/debian/eco/server/Mods/Organisms/Animal/Behaviors/PredatorBehaviors.cs:line 78
   at Eco.Simulation.Agents.AI.BehaviorConditional`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorSelector`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorConditional`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorSelector`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorSelector`1.Do(T context)
   at Eco.Simulation.Agents.AI.Brain.TickBehaviors(Animal animal)
   at Eco.Simulation.Agents.AI.Brain.Tick(Animal animal)
   at Eco.Simulation.Agents.Animal.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Simulation.EcoSim.<DoTick>b__41_0()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__33_0(PluginRegistration reg)

[22:46:04.279] [481] [ Info] [Eco] Shutdown finished

**Comment by SlayksWood** [comment]
@Thibault-Brocheton Thank you for the report. Can you provide information about the time when this happened (how much time has passed since the 9.2.2 update) and how often does it happen to you? If this happens periodically, please provide save files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Thibault-Brocheton** [comment]
It was a fresh 9.2.1 server, started 29 jan at 7pm utc.
9.2.2 update was made only few minutes after official release
It happened only one time, around 20 hours after the update to 9.2.2
didn't happened again.

The world might be a little strange, I generated it with modified source code (I'm going to open a PR for a way to generate custom worlds based on a biome and heightmap image), with the release branch, around the 27 / 28 jan

If I'm the only report with this issue, might be my custom world that cause it

**Comment by WeaselDog** [comment]
Thanks for the extra information. Please let us know if you are still experiencing this issue in 9.2.4

**Comment by Cicrocoft** [comment]
I have this issue with 9.2.4.
![crash](https://user-images.githubusercontent.com/20983572/108140735-a4748c80-70c2-11eb-8352-c14f5301d93b.png)

**Comment by keegan-o** [comment]
Am I correct in assuming this is something for 9.3 to be done ASAP?

**Comment by WeaselDog** [comment]
Yes it is marked for 9.3
