### ISSUE TITLE
Clam population data possibly being read/recorded twice

### ISSUE THREAD

**Issue by RoronoaDroagon** [StrangeLoopGames/EcoIssues#20281]
Restarted up the server with the same game/save files and got this error:

[log_210131074743.log](https://github.com/StrangeLoopGames/EcoIssues/files/5899327/log_210131074743.log)

Save and Data Base file:

(https://drive.google.com/drive/folders/1FE_kijmYBgxFbRCCI5Mc6pie0bq5sw8O?usp=sharing)

**Comment by SlayksWood** [comment]
```
[07:50:07.885] [34] [Error] [Eco] Failed to load server, Exception was Exception: ArgumentException
Message:An item with the same key has already been added. Key: ClamSpecies
Source:System.Private.CoreLib

System.ArgumentException: An item with the same key has already been added. Key: ClamSpecies
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Eco.Shared.Utils.BidirectionalMap`2.Add(TKey key, TVal val)
   at Eco.Stats.ShortNameMap.<Init>b__8_0(ShortNameEntry x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Stats.ShortNameMap.Init(List`1 collection)
   at Eco.Stats.StatInfoManager.Initialize(List`1 entries)
   at Eco.Stats.Stats.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
 
[07:50:12.896] [1] [Error] [Eco] Unhandled errorSystem.ArgumentException: An item with the same key has already been added. Key: ClamSpecies
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Eco.Shared.Utils.BidirectionalMap`2.Add(TKey key, TVal val)
   at Eco.Stats.ShortNameMap.<Init>b__8_0(ShortNameEntry x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Stats.ShortNameMap.Init(List`1 collection)
   at Eco.Stats.StatInfoManager.Initialize(List`1 entries)
   at Eco.Stats.Stats.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
   ```

**Comment by SlayksWood** [comment]
@RoronoaDroagon Thank you fo the report. What window version do you use?
seems similar with #20015

**Comment by IcedForge** [comment]
Will close due to lack of reply, please add the requested information and reopen this issue if you still encounter this problem.
