### ISSUE TITLE
Server Disconnects since 9.2.2

### ISSUE THREAD

**Issue by IceWarden** [StrangeLoopGames/EcoIssues#20291]
[Eco Dumps.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5900653/Eco.Dumps.zip)
We've been having a series of ECO Client crashes and server performance issues. Attached are dump files created by the server.

**Comment by IcedForge** [comment]
Looks like transport contract NRE, Did anyone use a transport contract and then picked up the container before this contract was completed or canceled?
```
Dump Time
01/31/2021 13:09:55

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClauseTransport.get_Contents()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'NameToObj' of 'Eco.Core.Systems.Registrar'
Error during packaging property 'Clauses' of 'Eco.Gameplay.Economy.Contracts.Contract'
Error during packaging property 'Contents' of 'Eco.Gameplay.Economy.Contracts.ContractClauseTransport'

--END DUMP--

```


Looks like a potential localization problem?

```
--BEGIN DUMP--
Dump Time
01/30/2021 12:28:47

Exception
Exception: ArgumentException
Message:Too many arguments for LocString: 892. Max: 382
Source:Eco.Shared

System.ArgumentException: Too many arguments for LocString: 892. Max: 382
   at Eco.Shared.Serialization.SimpleBSON.EncodeLocString(MemoryStream stream, LocString locString)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.BSONObject.EncodeNow(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.SimpleBSON.EncodeArray(MemoryStream stream, BSONArray array)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.BSONObject.EncodeNow(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.BSONObject.EncodeNow(MemoryStream stream)
   at Eco.Shared.Networking.NetMessage.EncodePacket(MemoryStream message, NetworkEvent netEvent, BSONObject payload)
   at Eco.Shared.Networking.NetMessage.SendPacket(IUdpPeer peer, NetworkEvent netEvent, BSONObject payload, Object connection)
   at Eco.Plugins.Networking.NetworkServer.DeliverMessage(NetworkMessage message)
   at Eco.Plugins.Networking.NetworkServer.DeliverMessages()
   at Eco.Plugins.Networking.NetworkServer.Run(CancellationToken token)

--END DUMP--

```

**Comment by D3nnis3n** [comment]
As this issue hasn't received an response in the last 14 days, I'm closing it.
If you still want to provide the required information, please feel free to do so and I'll reopen the issue :)
