### ISSUE TITLE
Even Moar Tiger Crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20302]
[09:28:03.755] [6] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.Values.MembershipRequirements.Value(IContextObject action)
   at Eco.Gameplay.Civics.GameValues.SetOfConditions.Value(IContextObject action)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.Law.Perform(GameAction action)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.Property.RentUtils.PackStuffIntoVoidStorage(User user, Deed deed)
   at Eco.Gameplay.Property.Residency.Evict(GameActionPack pack, User userEvicted)
   at Eco.Gameplay.Property.RentForProperty.Eco.Gameplay.Economy.Jobs.IRecurringTransferService.OnTransferFailed(RecurringTransfer transfer, LocString result)
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.Pay()
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.TryPay()
   at Eco.Gameplay.Economy.Jobs.RecurringTransferServiceExtensions.TryPayAll(IRecurringTransferService transferService)
   at Eco.Gameplay.Economy.Jobs.RecurringTransferManager.TryPayAll()
   at Eco.Gameplay.Economy.EconomyManager.Tick()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)

**Comment by IcedForge** [comment]
Preventing startup and as mentioned in the duplicate this happens when a resident cannot afford the rent.

Add a rentable property 
Have a user take up renting
Recurring payment tick happens and the user cannot afford rent ->> crash
