### ISSUE TITLE
Server crashes after updating to 9.2.3

### ISSUE THREAD

**Issue by psybitio** [StrangeLoopGames/EcoIssues#20309]
Server crashes after updating to lastest version. Tried restoring backup also, same issue.

--BEGIN DUMP--
Dump Time
02/02/2021 00:53:51

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.get_SourceAccount()
   at Eco.Gameplay.Economy.Jobs.RecurringTransferManager.<>c__DisplayClass8_0.<TransfersForUser>b__0(RecurringTransfer x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'IncomeAndExpenses' of 'Eco.Gameplay.Players.User'

--END DUMP--

**Comment by BarudinSoltara** [comment]
For our server specifically this seems to be the result of an issue via the Census Bureau. For us the issue was in "demographic 6" and "demographic 8". We removed 6 as it was spamming the server due to lack of funds.

Demographics 6 was a pay wages to players in a personal credit (Berran's Currency) from Ivorach's Private Bank. Ivo had 0 berran coin, so we removed the law. Eventually Berran bought stuff from my store to make the wages go away.

Demographics 8 was just a pay 1 wage per hour to all "active" members. This was in personal credit (Ivorach's Currency) from Ivorach's Private bank. It was my personal credit so I have infinit.

My assumption is one of those two is causing the above issue.

**Comment by BarudinSoltara** [comment]
It seems a similar issue is happening here from currency related laws: https://github.com/StrangeLoopGames/EcoIssues/issues/20307

**Comment by SlayksWood** [comment]
@psybitio Thank you for the report. Can you provide save files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by psybitio** [comment]
> @psybitio Thank you for the report. Can you provide save files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

Here is the link to download the Game.eco file:
https://drive.google.com/file/d/1IR85N3klXjI2Vzm7Et48-vOJYCucxY2p

**Comment by cfulton** [comment]
I have gotten the same exception attempting to load a second backup.
Looks like I've managed to get two different bugs. 

following is my second backup with a different issue. 

https://drive.google.com/file/d/1fooF8190gVc7tONcBxQLE6-FXNn-X3Df/view?usp=sharing

--BEGIN DUMP--
Dump Time
02/04/2021 00:52:23

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.get_SourceAccount()
   at Eco.Gameplay.Economy.Jobs.RecurringTransferManager.<>c__DisplayClass8_0.<TransfersForUser>b__0(RecurringTransfer x)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'IncomeAndExpenses' of 'Eco.Gameplay.Players.User'

--END DUMP--

**Comment by IcedForge** [comment]
Are you still having this issue after the latest update?

**Comment by IcedForge** [comment]
Closing this issue as it should be resolved in the next hotfix (0.9.2.5)
