### ISSUE TITLE
Server hard crash

### ISSUE THREAD

**Issue by IceWarden** [StrangeLoopGames/EcoIssues#20310]
New issue within the last 24 hours. Server has hard crashed twice today. It is not generating a dump log or throwing an exception in the Event logs of a Windows 2019 server. However there is a fair bit in the normal server log file for review:

`System.InvalidOperationException: Nullable object must have a value.
   at Eco.Gameplay.Civics.GameValues.Values.ResidentOfDistrict.Value(IContextObject action)
   at Eco.Gameplay.Civics.Demographics.Demographic.<>c__DisplayClass52_0.<CacheUsers>b__0(User user)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Eco.Gameplay.Civics.Demographics.Demographic.CacheUsers()
   at Eco.Gameplay.Civics.Demographics.DemographicManager.DoDemographicUpdate(Demographic limitToDemographic, Boolean suppressChangeNotice)
   at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[19:11:57.146] [5] [ Info] [Eco] Saving...  
[19:12:16.957] [325] [Error] [Eco] System.InvalidOperationException: Nullable object must have a value.
   at Eco.Gameplay.Civics.GameValues.Values.ResidentOfDistrict.Value(IContextObject action)
   at Eco.Gameplay.Civics.Demographics.Demographic.<>c__DisplayClass52_0.<CacheUsers>b__0(User user)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Eco.Gameplay.Civics.Demographics.Demographic.CacheUsers()
   at Eco.Gameplay.Civics.Demographics.DemographicManager.DoDemographicUpdate(Demographic limitToDemographic, Boolean suppressChangeNotice)
   at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Civics.CivicsPlugin.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg)
 
[19:12:26.388] [325] [ Info] [Eco] Shutdown finished`

**Comment by tuha263** [comment]
Step to reproduce:
-Become a resident of property without plot
![PropertyWithoutPlot](https://user-images.githubusercontent.com/9598614/106561711-c2d37780-655b-11eb-8a4c-f0f241e2a0f1.png)
- Setup a law with Resident Of District value
![ResidentOfDistrictLaw](https://user-images.githubusercontent.com/9598614/106561758-d2eb5700-655b-11eb-8281-dc2d7b3d9ac8.png)
- the trigger it and get the error
![ResidentOfDistrictLawError](https://user-images.githubusercontent.com/9598614/106561791-e8f91780-655b-11eb-82f2-294edfdad12e.png)
