### ISSUE TITLE
[0.9.2.3 release-150] Crash Exception Type: ArgumentException

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20333]
Crash Exception Type: ArgumentException
Version: 0.9.2.3 beta release-150
Count: 6550
Stack
at Eco.Shared.Validation.PropertyValidation.ValidateObject(Object propertyContainer)

Can't copy exception, bugreport is unavailable

**Comment by serpopov** [comment]
at Eco.Shared.Validation.PropertyValidation.ValidateObject(Object propertyContainer)
at Eco.Gameplay.Players.DifficultySettings.ApplyParameters()
at Eco.Gameplay.Players.DifficultySettings.Initialize(TimedTask timer)
at Eco.Server.PluginManager.InitializePlugins()
at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
at Eco.Server.MainClass.Main(String[] args)

**Comment by serpopov** [comment]
at Eco.Shared.Validation.PropertyValidation.ValidateObject(Object propertyContainer)
at Eco.Gameplay.Players.DifficultySettings.ApplyParameters()
at Eco.Gameplay.Players.DifficultySettings.Initialize(TimedTask timer)
at Eco.Server.PluginManager.InitializePlugins()
at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
at Eco.Server.MainClass.Main(String[] args)

**Comment by tuha263** [comment]
this happens because Users set up the world with the wrong Difficulty's property value:
![SettingNewWorld](https://user-images.githubusercontent.com/9598614/106900905-abe28000-6729-11eb-8fa6-7cd121e517db.png)
![InvalidPropertyValueError](https://user-images.githubusercontent.com/9598614/106900913-aedd7080-6729-11eb-9564-d4ddd6afbf9e.png)
![PropertyAttribute](https://user-images.githubusercontent.com/9598614/106900942-b56be800-6729-11eb-8062-f08b967213d0.png)

**Comment by redwyre** [comment]
This has hit 7300 reports for 9.2.4 in 12 hours

If it's coming from hosting a local world then the UI shouldn't let them

**Comment by SlayksWood** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/45708377/107179618-00b31e80-69e8-11eb-99a2-04baefa06f53.png)
![image](https://user-images.githubusercontent.com/45708377/107179660-1de7ed00-69e8-11eb-8161-997773818abe.png)
