### ISSUE TITLE
failed to load local server, any suggastions?

### ISSUE THREAD

**Issue by mrjixer** [StrangeLoopGames/EcoIssues#20332]
was working perfectly yesterday then i got this:
[11:25:29.760] [20] [Error] [Eco] Failed to load server, Exception was Exception: ArgumentException
Message:An item with the same key has already been added. Key: Vote
Source:System.Private.CoreLib

System.ArgumentException: An item with the same key has already been added. Key: Vote
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Eco.Shared.Utils.BidirectionalMap`2.Add(TKey key, TVal val)
   at Eco.Stats.ShortNameMap.<Init>b__8_0(ShortNameEntry x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Stats.ShortNameMap.Init(List`1 collection)
   at Eco.Stats.StatInfoManager.Initialize(List`1 entries)
   at Eco.Stats.Stats.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
 
[11:25:29.767] [1] [Error] [Eco] Unhandled errorSystem.ArgumentException: An item with the same key has already been added. Key: Vote
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Eco.Shared.Utils.BidirectionalMap`2.Add(TKey key, TVal val)
   at Eco.Stats.ShortNameMap.<Init>b__8_0(ShortNameEntry x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Stats.ShortNameMap.Init(List`1 collection)
   at Eco.Stats.StatInfoManager.Initialize(List`1 entries)
   at Eco.Stats.Stats.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
 
Does it has something to do with 9.2.3 update?

**Comment by SlayksWood** [comment]
@mrjixer Thank you for the report. What Operation System version do you use? (for example Windows 10 Pro 20H2)
You can read more about your problem here #20015
Seems to solve this problem now, you can try to update Windows to the latest version 20H2.
Did it help you?

**Comment by mrjixer** [comment]
I did the 20h2 update yesterday, after that server worked fine for 1 gaming session, then after system restart i got this problem.
seemes the windows update is the problem atm?
any workaround for now?

windows home 20h2

**Comment by mirasrael** [comment]
@mrjixer can you attach your save file?

**Comment by mrjixer** [comment]
https://www.dropbox.com/preview/p.db?role=personal
hope this work.

**Comment by mirasrael** [comment]
No. This link doesn't work. You need to share this.

**Comment by mrjixer** [comment]
https://drive.google.com/file/d/1F9l4zHq8lN4yPKMxqyU4SAt4_sQD4WUt/view?usp=sharing

**Comment by mirasrael** [comment]
I fixed your .db file:
[p.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5919312/p.zip)

**Comment by mrjixer** [comment]
awsome thanks alot
