### ISSUE TITLE
Server Crash while Starting - NullReferenceException - Eco.Gameplay.Economy.Jobs.RecurringTransfer.Pay

### ISSUE THREAD

**Issue by cfulton** [StrangeLoopGames/EcoIssues#20338]
Server is crashing while starting, showing the following exception:

```
[12:41:44] Initializing SettlementsPlugin... Finished in 0.0ms
[12:41:44] Initializing NetworkManager... Finished in 289.6ms
[12:41:44] Initializing WorldLayerManager... Finished in 0.1ms
[12:41:44] Initializing WebServerPlugin... Finished in 425.1ms
[12:41:45] Web Server now listening on: http://0.0.0.0:3001
[12:41:45] Initializing IntegrationTestsPlugin... Finished in 0.1ms
[12:41:45] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.Pay()
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.TryPay()
   at Eco.Gameplay.Economy.Jobs.RecurringTransferServiceExtensions.TryPayAll(IRecurringTransferService transferService)
   at Eco.Gameplay.Economy.Jobs.RecurringTransferManager.TryPayAll()
   at Eco.Gameplay.Economy.EconomyManager.Tick()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
[12:41:45] Saving world...
```

Copy of the DB files: 
https://drive.google.com/file/d/1yMJtH9W2HxiGnfigCSopsFhGzZRjtJpj/view?usp=sharing

**Comment by Venopsis** [comment]
Hi,
Previously before updating the server to 9.2.x did you have some elected titles or demographics using wages?
I had some issue and crash related to this.

**Comment by cfulton** [comment]
This was a fresh server on Eco Server 0.9.2.2 beta release-149
The server was only updated to Eco Server 0.9.2.3 beta release-150

It did have a "Welfare" system where it transferred money at set interval to a demographic.

**Comment by SlayksWood** [comment]
Can't start this server in 0.9.2.4 release-156 too.
