### ISSUE TITLE
picking up stone from a cart using shovel only picks up one stone and doesn't show icon in carrying slot

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2034]

**Comment by Conchipedia** [comment]
Seeing as we can pickup/carry 20 stone max, this doesn't happen when using a shovel on a cart or Stockpile. from Stockpile i get the icon picture and 1 stone, from cart i get 1 stone don't always get the icon picture . When trying to duplicate this happening, isometimes can or i get Disconnected with this 

Caught Exception: Caught exception invoking RPC PlayerInteract on Player!

Changes could not be applied, the requested operation would result in an invalid inventory state.


Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.Modify(Action`1 callback, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnAct(InteractionContext context, Func`2 resultFunc)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Also is it correct we can only pickup stone with E and it selects the shovel or are we supposed to be able to use the Shovel to pickup the stone?

#bac3d6c8 version

**Comment by metachronism** [comment]
intended; stone harvesting has been reworked to not require a shovel
