### ISSUE TITLE
Server restarts on an infinte loop

### ISSUE THREAD

**Issue by Shadowknight441** [StrangeLoopGames/EcoIssues#20387]
at Eco.Gameplay.Civics.CivicsPlugin.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg)
[01:43:56] Shutdown finished

at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Civics.CivicsPlugin.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg)
[02:28:00] Shutdown finished

For two days now been getting this and its manually putting the server in a restart loop the moment someone joins.

**Comment by SlayksWood** [comment]
@Shadowknight441 Thank you for the report. Can you provide save file? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by D3nnis3n** [comment]
As you haven't responded for over 14 days, I'm closing this issue.
Feel free to add the missing information to get it reopened at a later date.
