### ISSUE TITLE
Staging alpha 6.0.0 #cc778b68 - Can't place doors.

### ISSUE THREAD

**Issue by Senbotsu** [StrangeLoopGames/EcoIssues#2038]
Clean install of this staging build, new world, no mods.  Attempting to place a door causes the user to get kicked, once this happens the user keeps getting kicked upon loading into the world near where the door placement attempt was.  Restarting the server doesn't fix the issue, but the server will start up without any errors.

Error
-------------
--BEGIN DUMP--
Dump Time
08/30/2017 21:10:06

Exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Economy.Reputation.get_ReputationTitle()
   at Eco.Gameplay.Economy.Reputation.ToString()
   at Eco.Gameplay.Players.User.RepUILink()
   at Eco.Gameplay.Property.AuthorizationKey.get_OwnerDisplay()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at DoorObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_1()

Inner Exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Economy.Reputation.get_ReputationTitle()
   at Eco.Gameplay.Economy.Reputation.ToString()
   at Eco.Gameplay.Players.User.RepUILink()
   at Eco.Gameplay.Property.AuthorizationKey.get_OwnerDisplay()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at DoorObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_1()

--END DUMP--

**Comment by MarjieAVolk** [comment]
Not sure about the door thing, but looks like the same exception as https://github.com/StrangeLoopGames/EcoIssues/issues/1996 - Closing as duplicate
