### ISSUE TITLE
[9.2.4] Wage system revision in Titles Server crash.

### ISSUE THREAD

**Issue by chrisheff29** [StrangeLoopGames/EcoIssues#20460]
We had a fatal crash with our server once a revision on a title for wages was passed. The string the server gave back is as follows.

[06:39:47] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.Pay()
at Eco.Gameplay.Economy.Jobs.RecurringTransfer.Pay()
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.TryPay()
   at Eco.Gameplay.Economy.Jobs.RecurringTransferServiceExtensions.TryPayAll(IRecurringTransferService transferService)
   at Eco.Gameplay.Economy.Jobs.RecurringTransferManager.TryPayAll()
   at Eco.Gameplay.Economy.EconomyManager.Tick()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>cDisplayClass0_0.b0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Economy.EconomyPlugin.Shutdown()
   at Eco.Server.PluginManager.<>c.b__35_0(PluginRegistration reg)

I have attached the backup that this issue exists on it will be on the google drive link. We had to rollback the server to a time before it was passed, but still in the process of election. Any help would be much appreciated.

https://drive.google.com/drive/folders/1ivFmmjaYHRnUvYIA9n5Q_CvpII_ISpbR?usp=sharing

**Comment by IcedForge** [comment]
@chrisheff29 Thank you for uploading the save.
Will test this on the next update to make sure its fixed.

**Comment by IcedForge** [comment]
[log_210308081637.log](https://github.com/StrangeLoopGames/EcoIssues/files/6099578/log_210308081637.log)

Log/Migration log, looks like its starting and migrating fine into build 162

**Comment by Dahsnorf** [comment]
Im Having this exact issue 9.2.4 release 156. also dont have a backup to load :(
