### ISSUE TITLE
Staging alpha 6.0.0 #cc778b68 - Wood Cart kicks user when hit with axe.

### ISSUE THREAD

**Issue by Senbotsu** [StrangeLoopGames/EcoIssues#2047]
Hitting a wood cart with an axe (with the goal of picking up wood from said cart) causes a server kick with the following message:

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Changes could not be applied, the requested operation would result in an invalid inventory state.

Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.Modify(Action`1 callback, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnAct(InteractionContext context, Func`2 resultFunc)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment]
I've fixed this exception on master, will be fixed in the next staging release
