### ISSUE TITLE
crash saving world objects

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#205]
Likely need to lock the object whenever its contents can change

Exception
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at lambda_method(Closure , ItemCollection , IEncoder )
   at lambda_method(Closure , LimitedInventory , IEncoder )
   at lambda_method(Closure , IEncoder , WorldObject )
   at Microsoft.Hadoop.Avro.AvroSerializer`1.Serialize(Stream stream, T obj)
   at Eco.Core.Serialization.PluginAvroSerializer`1.Serialize(Object obj)
   at Eco.Core.Serialization.ZipBlob.Persist(Object obj)
   at Eco.Gameplay.Interactable.WorldObject.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Gameplay.Objects.Manager.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by johnkslg** [comment]
Possibly on the Carrying member? Its an ItemCollection
