### ISSUE TITLE
Just Yet Another Not Enough Tiger Crashes ...

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20518]
--BEGIN DUMP--
Dump Time
02/12/2021 18:20:57

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.PlayerRPCs.EditMap(Player player, MapEditRequest mapEditRequest)
   at Eco.Gameplay.Property.Deed.EditInMap(User user)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

--END DUMP--

**Comment by mirasrael** [comment]
@gzatravkin seems like Deed and Map related.

**Comment by mirasrael** [comment]
@WeaselDog why re-opened?
