### ISSUE TITLE
[0.9.3 staging-1931] Animal Client Crash

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20612]
Had one time, it  happened when I was AFK
```
--BEGIN DUMP--
Dump Time
02/16/2021 18:51:16

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Simulation

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__71_2()

--END DUMP--
```

**Comment by WeaselDog** [comment]
Please reopen if you encounter this in 9.3.3
