### ISSUE TITLE
USER ISSUE: Exception running by a stockpile

### ISSUE THREAD

**Issue by Kharzette** [StrangeLoopGames/EcoIssues#20639]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
I was running by a stockpile, not sure what happened.

Since it was a server thing, maybe it was my previous actions.  I emptied gold and copper concentrate into a large lumber stockpile, then picked up the cart that held the aforementioned concentrates.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'source')
Source:System.Linq

System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Auth.AuthManager.IsAuthorized(WorldObject obj, IAlias alias, AccessType access, GameAction action)
   at Eco.Gameplay.Components.Auth.AuthComponent.IsAuthorizedFullAccess(Player player)
Outer Exceptions:
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6001233/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6001234/Player-prev.log)

**Comment by Kharzette** [comment]
More info...

I think I know what caused this.  We enacted a law that caused abandoned players' property to go public.  I think that happened and the former players holdings were quite extensive.  He basically left carts full of junk everywhere.

**Comment by SlayksWood** [comment]
@Kharzette Can you provide screenshot of Law?

**Comment by Kharzette** [comment]
Sure thing!  Blurred a bad word:
![decree](https://user-images.githubusercontent.com/6589537/108339856-8f206080-719d-11eb-8135-c658de5eedf9.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.2.4 Release-162.

I implemented the law and summoned test subjects. Gave each subject property then fast-forwarded time to make test subjects meet abandoned requirements.
However, I did not get the same error.
Furthermore, only happened once.

Complete Log: [https://app.zenhub.com/files/47210472/fb2201f4-a612-44a5-8ce0-b9cf5668a641/download](https://app.zenhub.com/files/47210472/fb2201f4-a612-44a5-8ce0-b9cf5668a641/download)

```
<size=60.00%>Exception: TargetException
Message:Object does not match target type.
Source:System.Private.CoreLib

System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Shared.Networking.RPCManager.TryInvoke(INetClient client, Object target, String methodname, BSONArray bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname)
   at Eco.Plugins.Networking.Client.ViewRPC(INetClient client, Int32 id, String methodname, BSONObject bson)
Outer Exceptions:
Exception has been thrown by the target of an invocation.</size>
```
