### ISSUE TITLE
Server crashes when Item is placed

### ISSUE THREAD

**Issue by GRSC97** [StrangeLoopGames/EcoIssues#20661]
The server crashes when an item is placed in the game and when I log back into the server the item has been deleted.

The error code is as follows:
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Base OnCreate method must be called.
Source:Eco.Gameplay

System.InvalidOperationException: Base OnCreate method must be called.
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.Add(WorldObject worldObject, User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.ForceAdd(Type worldObjectType, User creator, Vector3 position, Quaternion rotation, Boolean validatePlacement, WorldObjectItem item)
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass34_0.<TryPlaceWorldObject>b__0()
   at Eco.Gameplay.GameActions.GameActionPack.<>c__DisplayClass17_0.<AddPostEffect>b__0()
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Objects.WorldObjectManager.TryPlaceWorldObject(Player player, WorldObjectItem item, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass26_1.<OnActRight>b__1()
   at Eco.Gameplay.Items.WorldObjectItem.TryPlaceObject(Player player, Vector3i position, Quaternion rotation, Action successCallback)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass26_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.<>c__DisplayClass22_0`1.<Call>b__0(Object o)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__70_3()</size>

Log File:
Initialize engine version: 2019.4.15f1 (fbf367ac14e9)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 6GB (ID=0x1c03)
    Vendor:   
    VRAM:     6052 MB
    Driver:   27.21.14.6140
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.493600 ms
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects. 
(Filename:  Line: 589)

WwiseUnity: Wwise(R) SDK Version 2019.2.5 Build 7349.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Setting Plugin DLL path to: C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Sound engine initialized successfully.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'Camera') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object 'Table') is missing! 
(Filename:  Line: 334)

DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
SteamManager:Awake()

[ line 589] 
(Filename:  Line: 589)

Ambiguous UI component types ignored: SeriesPopupUI,BaseUI,ViewEditorUI,AutoViewUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.UIManager:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:49:05.475] LoginSession: connectorHandle=C0
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
VivoxUnity.VivoxDebug:DebugMessage(Object, vx_log_level)
VivoxUnity.Private.<>c__DisplayClass89_0:<BeginLogin>b__0(IAsyncResult)
VivoxUnity.HandleEventMessage:Invoke(vx_evt_base_t)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.<>c__DisplayClass12_0:<BeginGetConnectorHandle>b__0(IAsyncResult)
VivoxUnity.HandleEventMessage:Invoke(vx_evt_base_t)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
MessagePump:RunOnce()
MessagePump:RunUntil(LoopDone)
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:50:01.906] Connecting to local host.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:50:01.907] Connecting to 127.0.0.1:3000...

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:50:01.908] Connection complete.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'LayerViewer') is missing! 
(Filename:  Line: 334)

Unable to open archive file: C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/StreamingAssets/desc.unity3d 
(Filename:  Line: 584)

Failed to read data for the AssetBundle 'StreamingAssets\desc.unity3d'. 
(Filename:  Line: 449)

[10:50:07.814] Missing sprite in MiscIconMap.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
ModBundleManager:SetupSprites()
<ReceiveModData>d__47:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:50:08.060] Missing following objects: AirPollutionGeneratorObject, CountryMarkerObject, FedeartionMarkerObject, HomesteadMarkerObject, TownMarkerObject
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<BuildFromModKit>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>d__47:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

NullReferenceException: Object reference not set to an instance of an object.
  at WorldLayerView.GetPercentRaw (Eco.Shared.Math.Vector2i pos) [0x00000] in <00000000000000000000000000000000>:0 
  at BiomeTracker.GetBiomeIndexRaw (Eco.Shared.Math.Vector2i rawPos) [0x00000] in <00000000000000000000000000000000>:0 
  at DecorationParticleSpawner.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
 
(Filename: currently not available on il2cpp Line: -1)

NullReferenceException: Object reference not set to an instance of an object.
  at WorldLayerView.GetPercentRaw (Eco.Shared.Math.Vector2i pos) [0x00000] in <00000000000000000000000000000000>:0 
  at BiomeTracker.GetBiomeIndexRaw (Eco.Shared.Math.Vector2i rawPos) [0x00000] in <00000000000000000000000000000000>:0 
  at DecorationParticleSpawner.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
 
(Filename: currently not available on il2cpp Line: -1)

[10:50:20.181] Missing Connecting
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UI.ConnectionUI:GotoState(ConnectState)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:50:53.316] LinkedInventory doesn't support pooling. It may cause problems in runtime. Either add [SupportsPooling] attribute to all it's and it's children components or implement pool supporting interface(s) (IPoolRentAware, IPoolReturnAware). For third-party components you can use PoolingExtensions.RegisterPoolableType. List of components missing pooling support: StorageParent (SimpleRaycastTarget)
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
EcoEngine.Pooling.ObjectPool:SetPrefab(PooledObject)
EcoEngine.Pooling.PooledObjectOwnerExtensions:PoolInstantiate(GameObject, Transform, Boolean, IPooledObjectOwner)
UI.<UpdateLinkedCoroutine>d__25:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UI.StorageUI:UpdateLinked()
Unity.Entities.WithCodeAction:Invoke()
Eco.Shared.View.SubscriptionsExtensions:SubscribeAndCall(ISubscriptions, IObservable, String, Action)
UI.StorageUI:InitLinked(LinkComponentView)
UI.StorageUI:OnInitPanel()
UI.WorldObjectUI:SetPanelEnabled(PanelData, Boolean)
UnityEngine.Events.UnityAction`1:Invoke(T0)
UnityEngine.Events.InvokableCall`1:Invoke(T1)
UnityEngine.Events.UnityEvent`1:Invoke(T0)
UnityEngine.UI.Toggle:Set(Boolean, Boolean)
System.Data.DataTableNewRowEventHandler:Invoke(Object, DataTableNewRowEventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:51:21.486] Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Base OnCreate method must be called.
Source:Eco.Gameplay

System.InvalidOperationException: Base OnCreate method must be called.
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.Add(WorldObject worldObject, User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.ForceAdd(Type worldObjectType, User creator, Vector3 position, Quaternion rotation, Boolean validatePlacement, WorldObjectItem item)
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass34_0.<TryPlaceWorldObject>b__0()
   at Eco.Gameplay.GameActions.GameActionPack.<>c__DisplayClass17_0.<AddPostEffect>b__0()
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Objects.WorldObjectManager.TryPlaceWorldObject(Player player, WorldObjectItem item, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass26_1.<OnActRight>b__1()
   at Eco.Gameplay.Items.WorldObjectItem.TryPlaceObject(Player player, Vector3i position, Quaternion rotation, Action successCallback)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass26_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.<>c__DisplayClass22_0`1.<Call>b__0(Object o)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__70_3()</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
UnityEngine.Experimental.Audio.SampleFramesHandler:Invoke(AudioSampleProvider, UInt32)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass63_0:<Initialize>b__0()
Steamworks.RulesRefreshComplete:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.RulesRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:51:23.336] Destroyed FoodStatusUI has active subscriptions for: CachedHouseValueView.HousingSkillRate

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteErrorLineLoc(FormattableString)
GenericClient`1:ReportNonReleasedSubscriptions()
GenericClient`1:<OnDisconnect>b__38_0()
Unity.Entities.WithCodeAction:Invoke()
<InOneFrame>d__16:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:51:23.337] Destroyed ViewUIContainer has active subscriptions for: UserTaskManagerView.Tasks

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteErrorLineLoc(FormattableString)
GenericClient`1:ReportNonReleasedSubscriptions()
GenericClient`1:<OnDisconnect>b__38_0()
Unity.Entities.WithCodeAction:Invoke()
<InOneFrame>d__16:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:51:23.337] Destroyed UserTaskManagerUI has active subscriptions for: UserTaskManagerView.Tasks

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteErrorLineLoc(FormattableString)
GenericClient`1:ReportNonReleasedSubscriptions()
GenericClient`1:<OnDisconnect>b__38_0()
Unity.Entities.WithCodeAction:Invoke()
<InOneFrame>d__16:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)

Unloading 9227 unused Assets to reduce memory usage. Loaded Objects now: 97959.
Total: 445.936400 ms (FindLiveObjects: 12.932000 ms CreateObjectMapping: 9.823300 ms MarkObjects: 387.701700 ms  DeleteObjects: 35.478800 ms)

[10:54:50.302] Connecting to local host.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:54:50.302] Connecting to 127.0.0.1:3000...

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:54:50.302] Connection complete.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'LayerViewer') is missing! 
(Filename:  Line: 334)

Unable to open archive file: C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/StreamingAssets/desc.unity3d 
(Filename:  Line: 584)

Failed to read data for the AssetBundle 'StreamingAssets\desc.unity3d'. 
(Filename:  Line: 449)

[10:54:54.213] Missing sprite in MiscIconMap.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
ModBundleManager:SetupSprites()
<ReceiveModData>d__47:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:54:54.443] Missing following objects: AirPollutionGeneratorObject, CountryMarkerObject, FedeartionMarkerObject, HomesteadMarkerObject, TownMarkerObject
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<BuildFromModKit>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>d__47:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:55:05.020] Missing Connecting
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UI.ConnectionUI:GotoState(ConnectState)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:59:04.250] LinkedInventory doesn't support pooling. It may cause problems in runtime. Either add [SupportsPooling] attribute to all it's and it's children components or implement pool supporting interface(s) (IPoolRentAware, IPoolReturnAware). For third-party components you can use PoolingExtensions.RegisterPoolableType. List of components missing pooling support: StorageParent (SimpleRaycastTarget)
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
EcoEngine.Pooling.ObjectPool:SetPrefab(PooledObject)
EcoEngine.Pooling.PooledObjectOwnerExtensions:PoolInstantiate(GameObject, Transform, Boolean, IPooledObjectOwner)
UI.<UpdateLinkedCoroutine>d__25:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UI.StorageUI:UpdateLinked()
Unity.Entities.WithCodeAction:Invoke()
Eco.Shared.View.SubscriptionsExtensions:SubscribeAndCall(ISubscriptions, IObservable, String, Action)
UI.StorageUI:InitLinked(LinkComponentView)
UI.StorageUI:OnInitPanel()
UI.WorldObjectUI:SetPanelEnabled(PanelData, Boolean)
UnityEngine.Events.UnityAction`1:Invoke(T0)
UnityEngine.Events.InvokableCall`1:Invoke(T1)
UnityEngine.Events.UnityEvent`1:Invoke(T0)
UnityEngine.UI.Toggle:Set(Boolean, Boolean)
System.Data.DataTableNewRowEventHandler:Invoke(Object, DataTableNewRowEventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:59:18.721] Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Base OnCreate method must be called.
Source:Eco.Gameplay

System.InvalidOperationException: Base OnCreate method must be called.
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.Add(WorldObject worldObject, User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.ForceAdd(Type worldObjectType, User creator, Vector3 position, Quaternion rotation, Boolean validatePlacement, WorldObjectItem item)
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass34_0.<TryPlaceWorldObject>b__0()
   at Eco.Gameplay.GameActions.GameActionPack.<>c__DisplayClass17_0.<AddPostEffect>b__0()
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Objects.WorldObjectManager.TryPlaceWorldObject(Player player, WorldObjectItem item, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass26_1.<OnActRight>b__1()
   at Eco.Gameplay.Items.WorldObjectItem.TryPlaceObject(Player player, Vector3i position, Quaternion rotation, Action successCallback)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass26_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.<>c__DisplayClass22_0`1.<Call>b__0(Object o)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__70_3()</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
UnityEngine.Experimental.Audio.SampleFramesHandler:Invoke(AudioSampleProvider, UInt32)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass63_0:<Initialize>b__0()
Steamworks.RulesRefreshComplete:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.RulesRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

NullReferenceException: Object reference not set to an instance of an object.
  at Unity.Entities.LambdaSingleJobDescriptionConstructionMethods+WithCodeAction.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.OnDisconnected () [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
 
(Filename: currently not available on il2cpp Line: -1)

[10:59:20.649] Destroyed FoodStatusUI has active subscriptions for: CachedHouseValueView.HousingSkillRate

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteErrorLineLoc(FormattableString)
GenericClient`1:ReportNonReleasedSubscriptions()
GenericClient`1:<OnDisconnect>b__38_0()
Unity.Entities.WithCodeAction:Invoke()
<InOneFrame>d__16:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:59:20.649] Destroyed ViewUIContainer has active subscriptions for: UserTaskManagerView.Tasks

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteErrorLineLoc(FormattableString)
GenericClient`1:ReportNonReleasedSubscriptions()
GenericClient`1:<OnDisconnect>b__38_0()
Unity.Entities.WithCodeAction:Invoke()
<InOneFrame>d__16:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[10:59:20.650] Destroyed UserTaskManagerUI has active subscriptions for: UserTaskManagerView.Tasks

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteErrorLineLoc(FormattableString)
GenericClient`1:ReportNonReleasedSubscriptions()
GenericClient`1:<OnDisconnect>b__38_0()
Unity.Entities.WithCodeAction:Invoke()
<InOneFrame>d__16:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 8 Unused Serialized files (Serialized files now loaded: 0)

Unloading 8414 unused Assets to reduce memory usage. Loaded Objects now: 118436.
Total: 397.320500 ms (FindLiveObjects: 10.878800 ms CreateObjectMapping: 8.009700 ms MarkObjects: 363.594300 ms  DeleteObjects: 14.837000 ms)

**Comment by SlayksWood** [comment]
@GRSC97 Can you provide save files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by GRSC97** [comment]
gareth crowther has shared a OneDrive file with you. To view it, click the link below.
<https://1drv.ms/u/s!AhYKfkXULpZSng22Zt3Km01qV1qs>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://1drv.ms/u/s!AhYKfkXULpZSng22Zt3Km01qV1qs>
Eco_Data.zip<https://1drv.ms/u/s!AhYKfkXULpZSng22Zt3Km01qV1qs>



________________________________

**Comment by GRSC97** [comment]
[Uploading My world 1.zip…]()

**Comment by IcedForge** [comment]
As it was never clarified, what item were you trying to place?

**Comment by GRSC97** [comment]
Anything, stockpiles, torch stands are all I have tried though
________________________________

**Comment by IcedForge** [comment]
Following up on this, are you still running into this problem on a world post 9.3 ?

**Comment by TwixterZ** [comment]
Closing this issue as its already more than 20 days without response from player, if issue still persist, please open a new issue for us to check
