### ISSUE TITLE
Server crash related to wages

### ISSUE THREAD

**Issue by Cicrocoft** [StrangeLoopGames/EcoIssues#20667]
I had this crash this morning, and I know a person was messing around with wages some time before. Ive not been able to locate a ticket with this error content. Server is running 9.2.4

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.CustomStatQuery.get_ActionName()
   at Eco.Gameplay.Civics.GameValues.StatSum.Value(IContextObject action)
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.UpdateValues(IRecurringTransferService service, Boolean notifyUpdate)
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.Initialize(IRecurringTransferService service, User user, BankAccount userBankAccount)
   at Eco.Gameplay.Economy.Jobs.RecurringTransferServiceExtensions.MakeTransferForUser(IRecurringTransferService transferService, User user, BankAccount userBankAccount, Boolean notify)
   at Eco.Gameplay.Economy.Jobs.RecurringTransferServiceExtensions.UpdateTransfers(IRecurringTransferService service)
   at Eco.Gameplay.Economy.Jobs.RecurringTransferManager.UpdateTransfers(IRecurringTransferService service)
   at Eco.Gameplay.Economy.Jobs.RecurringTransferManager.Register(IRecurringTransferService transferService)
   at Eco.Gameplay.Economy.Jobs.RecurringTransferServiceExtensions.RegisterWages(IRecurringTransferService group)
   at Eco.Gameplay.Civics.Titles.Title.Initialize()
   at Eco.Gameplay.Civics.Titles.AppointedTitle.Initialize()
   at Eco.Core.Systems.Registrar.Initialize()
   at Eco.Core.Systems.Registrars.Init()
   at Eco.Core.Utils.Initializer.Initialize()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)

**Comment by IcedForge** [comment]
@Cicrocoft Thank you for reporting, could i ask you for an upload of the save file to have a look at and verify? Seems most of these final problems have been resolved in a yet not released hotfix.

**Comment by IcedForge** [comment]
Closing this issue as it should be resolved in the next hotfix (0.9.2.5)
