### ISSUE TITLE
Player Can't connect to the server - Contract Crash

### ISSUE THREAD

**Issue by RobCod** [StrangeLoopGames/EcoIssues#20749]
Hello, I recently had a friend accept one of my contracts on my server, and now he cannot connect to the server and it saves a crash report every time he tries to join.

Steps to reproduce:
1. create a contract to plow fields with 20 tiles.
2. Have someone accept the contract -> will result in a kick from the server and making it impossible to rejoin.

here is the log file:

--BEGIN DUMP--
Dump Time
02/25/2021 16:34:20

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClausePlowField.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.Economy.Contracts.Contract.<>c__DisplayClass83_0.<ShouldOverrideAuth>b__0(ContractClause x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Economy.Contracts.Contract.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.Economy.Contracts.ContractManager.<>c__DisplayClass27_0.<ShouldOverrideAuth>b__1(Contract contract)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Economy.Contracts.ContractManager.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.GameActions.ActionUtil.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.Objects.WorldObject.QueryInteraction(Player player)
   at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, INetObjectContainer monitored)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1()

--END DUMP--

**Comment by RobCod** [comment]
How would I go about deleting that accepting contract so he can join again?

**Comment by TwixterZ** [comment]
@RobCod  Thank you for reporting this issue, 

Steps to reproduce:

1. create a contract to plow fields with 20 tiles.
![image](https://user-images.githubusercontent.com/78054747/110888221-ba264c00-8326-11eb-86de-c57286124881.png)
2. Have someone accept the contract 
3. User that accepted contact will be kicked from server with error message
![image](https://user-images.githubusercontent.com/78054747/110888457-315be000-8327-11eb-9273-eed24dde0a53.png)

**Comment by ptitducanh** [comment]
It was fixed by this pr https://github.com/StrangeLoopGames/Eco/pull/7837

**Comment by IcedForge** [comment]
Fixed on current 9.3 - staging branch 1964
