### ISSUE TITLE
ModKitPlugin gets Initialized before NetworkPlugin, making SendIpc fail on errors

### ISSUE THREAD

**Issue by cemeceme** [StrangeLoopGames/EcoIssues#20770]
If any Mods fail when the server is launched through the game client, Eco.Server.Startup.SendIpc fails because the Network plugin isn't loaded yet. This results in an error log like the following:
```
[02:20:25.220] [1] [Error] [Eco] Unhandled errorSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Plugins.Networking.NetworkManager.get_Config()
   at Eco.Server.Startup.SendIpc(String ipcMessage, Exception exception)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
```
The issue is, because `SendIpc` relies on a `NetworkManager` for its logging, a null reference exception is raised before the real exception can be sent. This wouldn't be too big of an issue if it wasn't for the fact that this eats the real exception, and the user has no idea what the cause of the issue may actually be.

Just changing the loading order so that the NetworkPlugin loads first should fix the issue. Binding that, removing the requirement, or checking for an invalid NetworkPlugin in the SendIpc method itself could also be a fix.

**Comment by mirasrael** [comment]
Already fixed in staging.
