### ISSUE TITLE
Develop build integration test failure: buildtech

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#20815]
https://jks.strangeloopgames.com/job/Eco%20Develop/193//console
https://jks.strangeloopgames.com/job/Eco%20Develop/199//console

```
[03:08:22] Running test buildtech
[03:08:22] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Rooms.Room.UpdateRoomValue()
   at Eco.Gameplay.Rooms.Room.ScanRoomAndUpdate(Vector3i pos, Boolean rescanBlocks)
   at Eco.Gameplay.Rooms.Room.ScanRoomAndUpdate(Boolean rescanBlocks)
   at Eco.Gameplay.Rooms.RoomUpdater.InvalidateRoom(Room room, Boolean scanBlocks)
   at Eco.Gameplay.Rooms.RoomUpdater.AddBlock(Room room, Vector3i pos, Boolean isWall)
   at Eco.Gameplay.Rooms.RoomUpdater.TestChange(Vector3i position)
   at Eco.Gameplay.Rooms.RoomUpdater.Update(ThreadSafeList`1 rooms, ThreadSafeDictionary`2 posToRooms, IEnumerable`1 positions)
   at Eco.Gameplay.Rooms.RoomData.ScanChangesForRooms()
   at Eco.Gameplay.Rooms.RoomPlugin.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass4_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
```

**Comment by WeaselDog** [comment]
Please reopen if we see this again.
