### ISSUE TITLE
Develop build server test failure: GridTraverseLineTest 

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#20816]
https://jks.strangeloopgames.com/job/Eco%20Test%20Pipeline%20(develop)/607/console

```
Failed GridTraverseLineTest [102 ms]
  Error Message:
   System.AggregateException : One or more errors occurred. (  Expected: True
  But was:  False
)
  ----> NUnit.Framework.AssertionException :   Expected: True
  But was:  False


  1)   Expected: True
  But was:  False


  Stack Trace:
     at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Tests.AITests.GridTraverseLineTest() in C:\Jenkins\workspace\Eco Test Pipeline (develop)\Server\Eco.Tests\AITests.cs:line 23
--AssertionException
   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.IsTrue(Boolean condition)
   at Eco.Tests.AITests.TestLine(Vector2 start, Vector2 end) in C:\Jenkins\workspace\Eco Test Pipeline (develop)\Server\Eco.Tests\AITests.cs:line 58
   at Eco.Tests.AITests.<GridTraverseLineTest>b__0_0(Double angle) in C:\Jenkins\workspace\Eco Test Pipeline (develop)\Server\Eco.Tests\AITests.cs:line 32
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()

```

**Comment by j3fffff** [comment]
@Abhiw205 can you check in with simon and determine what needs to be fixed?
if its jenkins side fix it. if its game side, let me or todd know and we can assign someone to new task for it

**Comment by redwyre** [comment]
This is a game side issue

**Comment by redwyre** [comment]
@WeaselDog please assign to AI

**Comment by WeaselDog** [comment]
Fix was submitted to 9.5

**Comment by WeaselDog** [comment]
Please bring this change to staging.

**Comment by SlayksWood** [comment]
closed as fixed.
