### ISSUE TITLE
Alpha.6 [Cc778b68] Caught exception

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2085]
Kiln moved Coal via drag & drop from Storage (Stockpile) to Power    
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on LimitedInventory!

Object reference not set to an instance of an object


Stack:
  at Eco.Gameplay.Items.InventoryChangeSet.MoveStacks (Eco.Gameplay.Items.ItemStack source, Eco.Gameplay.Items.ItemStack destination) [0x000a4] in <10535f9da1284dab8b9deb6571aeae10>:0 
  at Eco.Gameplay.Items.Inventory.MoveItems (Eco.Gameplay.Items.ItemStack sourceStack, Eco.Gameplay.Items.ItemStack targetStack, Eco.Gameplay.Players.Player player) [0x0002b] in <10535f9da1284dab8b9deb6571aeae10>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <e883190669d44e94b2ce2969ed9fbd03>:0 



Stack:
  at Eco.Shared.Networking.RPCManager.TryInvoke (System.Object controller, System.String methodname, Eco.Shared.Serialization.BSONObject bsonArgs, System.Object& result) [0x000ac] in <81ea587cc2294aa5927c8c675cd12232>:0 
  at Eco.Shared.Networking.RPCManager.InvokeOn (Eco.Shared.Serialization.BSONObject bson, System.Object controller, System.String methodname) [0x0005f] in <81ea587cc2294aa5927c8c675cd12232>:0 
  at Eco.Core.Controller.ControllerManager.HandleViewRPC (System.Guid controllerID, System.String methodname, Eco.Shared.Serialization.BSONObject bson) [0x00007] in <27ce67a426244d4aa1345f8b0040f62c>:0 
  at Eco.Plugins.Networking.Clients.Client.ViewRPC (System.Guid guid, System.String methodname, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <7891e663b4384021ac9e21dfe524b041>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <e883190669d44e94b2ce2969ed9fbd03>:0 
```

**Comment by Fank** [comment]
Maybe related to #2084 (mono issue)

**Comment by MarjieAVolk** [comment]
This one I'm not sure about.  I haven't been able to reproduce the issue yet.  Do you have any more information about when this error happens?  Do you see it consistently, or was it just once?  Could you post screenshots / gifs to show how you got the error in more detail?

**Comment by Fank** [comment]
It happend only once, unable to reproduce.

**Comment by metachronism** [comment]
closing as no repro

**Comment by MarjieAVolk** [comment]
Will just saw this on staging build.  He placed a stockpile, but the stockpile item was not visually removed from his toolbar.  When he tried to move the phantom stockpile stack, it kicked him with this same exception.

**Comment by clairemarshal** [comment]
another crash report for this issue

-------------
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on LimitedInventory!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by metachronism** [comment]
should be working now
