### ISSUE TITLE
USER ISSUE: flipped car

### ISSUE THREAD

**Issue by waudvdl** [StrangeLoopGames/EcoIssues#20876]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
put car with the top on the ground so it is reversed and then press E to drive and then it crashes

**Expected behavior:**
not give a nullException and crash

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Simulation

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i don't have any mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi @waudvdl thank you for your report

I'm unable to reproduce above error from my end, please assist to provide more information 

- vehicle type
- private game or public server
- please share your game save if possible

**Comment by IcedForge** [comment]
Will close due to lack of reply, please reopen if you still encounter this problem with the above mentioned information.
