### ISSUE TITLE
Server Crashing with LiteDB exception: Database lock timeout

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20908]
[06:33:48.792] [517] [Error] [Eco] System.AggregateException: One or more errors occurred. (Database lock timeout when entering in exclusive mode after 00:01:00)

LiteDB.LiteException: Database lock timeout when entering in exclusive mode after 00:01:00
   at LiteDB.Engine.LockService.EnterExclusive()
   at LiteDB.Engine.WalIndexService.Checkpoint()
   at Eco.Stats.Stats.Flush()
   at Eco.Core.Plugins.StorageManager.PersistAsync(Boolean forceFlush)
   at Eco.Core.Utils.Threading.IntervalActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[06:33:48.903] [5] [ Info] [Eco] Saving...  
[06:33:50.613] [324] [Debug] [Eco] Nat introduction received with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:33:50.646] [324] [Debug] [Eco] Nat punch received from 173.21.121.127:61505 with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:33:50.646] [324] [Debug] [Eco] Nat punch received from 173.21.121.127:61505 with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:33:51.009] [324] [Debug] [Eco] Nat introduction received with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:33:51.198] [324] [Debug] [Eco] Nat punch received from 84.241.193.153:14247 with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:33:51.198] [324] [Debug] [Eco] Nat punch received from 84.241.193.153:14247 with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:33:51.494] [324] [Debug] [Eco] Nat introduction received with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:33:51.623] [324] [Debug] [Eco] Nat punch received from 219.161.22.6:4895 with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:33:51.623] [324] [Debug] [Eco] Nat punch received from 219.161.22.6:4895 with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:34:06.824] [324] [Debug] [Eco] Nat introduction received with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:34:06.824] [324] [Debug] [Eco] Nat punch received from 8.20.127.19:56780 with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:34:06.824] [324] [Debug] [Eco] Nat punch received from 8.20.127.19:56780 with token = 1901d46d-d6e9-4bd6-8c66-c05d59d59e69 
[06:34:49.170] [1] [Error] [Eco] Unhandled errorSystem.AggregateException: One or more hosted services failed to stop. (Database lock timeout when entering in exclusive mode after 00:01:00)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
LiteDB.LiteException: Database lock timeout when entering in exclusive mode after 00:01:00
   at LiteDB.Engine.LockService.EnterExclusive()
   at LiteDB.Engine.WalIndexService.Checkpoint()
   at Eco.Stats.Stats.Flush()
   at Eco.Core.Plugins.StorageManager.ForceSaveAll()
   at Eco.Core.Plugins.StorageManager.SaveAndFlushAsync(ExclusiveAccess access)
   at Eco.Core.Plugins.StorageManager.SaveAndFlushAsync()
   at Eco.Server.Startup.StopAsync()
   at Eco.Server.Startup.RunAsync(IHostApplicationLifetime applicationLifetime, StartupInfo startupInfo)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)

**Comment by D3nnis3n** [comment]
--BEGIN DUMP--
Dump Time
03/12/2021 06:34:49

Exception
Exception: LiteException
Message:Database lock timeout when entering in exclusive mode after 00:01:00
Source:LiteDB

LiteDB.LiteException: Database lock timeout when entering in exclusive mode after 00:01:00
   at LiteDB.Engine.LockService.EnterExclusive()
   at LiteDB.Engine.WalIndexService.Checkpoint()
   at Eco.Stats.Stats.Flush()
   at Eco.Core.Plugins.StorageManager.ForceSaveAll()
   at Eco.Core.Plugins.StorageManager.SaveAndFlushAsync(ExclusiveAccess access)
   at Eco.Core.Plugins.StorageManager.SaveAndFlushAsync()
   at Eco.Server.Startup.StopAsync()
   at Eco.Server.Startup.RunAsync(IHostApplicationLifetime applicationLifetime, StartupInfo startupInfo)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
Outer Exceptions:
One or more hosted services failed to stop. (Database lock timeout when entering in exclusive mode after 00:01:00)

--END DUMP--

**Comment by SlayksWood** [comment]
closed as fixed.

**Comment by WeaselDog** [comment]
Happened again on [0.9.4.0 staging-2037] on our company play
![PlaytestCrash](https://user-images.githubusercontent.com/47330823/123558994-534e6680-d74e-11eb-993b-90f560a4a821.png)
test.

**Comment by IcedForge** [comment]
![Screenshot_194](https://user-images.githubusercontent.com/24981362/123620410-7d655e80-d80a-11eb-93ba-1a5aaf07202c.jpg)

This is causing a crash on placement im trying to isolate exactly why its happening and in which specific interaction part of it but due to the exclusive mode delay you need to perform action, wait 1-2 min for DB timer to run and try another so its taking a long time.

**Comment by IcedForge** [comment]
Happens when an action trigger i used to call a null value entry.
Make that law, do not input any value into "Stone" and try to place a mortared stone block.
Observe as it will terminate the server after 1 min/1.5 min

Add a law to add a value ( On chat, record value +1 to Stone )
Now try to place block, it will work properly.

**Comment by SlayksWood** [comment]
Can't do it now:
![image](https://user-images.githubusercontent.com/45708377/124889446-c7ef9380-dfdf-11eb-949c-8fe8fe737a8f.png)
seems fixed.
