### ISSUE TITLE
Test failure: testsewage

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#20965]
Happening randomly and failing PRs. The pipe generation code for tests could use a refactor to be deterministic (ie build a fixed grid), as I have had issues with it causing failures before.

```
Test run Existing world CI failed!
testsewage: Test Failed with 1 exceptions.

=====EXCEPTION 0=====
Warning: Exception Caught in Test testsewage - System.Exception: Test failed! Waste Filter is not enabled and operating.
Exception: Exception
Message:Test failed! Waste Filter is not enabled and operating.
Source:Eco.Gameplay

System.Exception: Test failed! Waste Filter is not enabled and operating.
at Eco.Gameplay.WorldObjectDebugUtil.ThrowIfNotRunning(WorldObject obj)
at Eco.Gameplay.Pipes.PipeTests.Sewage(User user)
```

**Comment by WeaselDog** [comment]
Related to https://github.com/StrangeLoopGames/Eco/pull/7818

**Comment by IcedForge** [comment]
While the command seemingly works ingame, it is throwing exceptions on execution.

```
[13:53:52.113] [110] [Error] [Eco] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.<>c__DisplayClass12_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass2_0.<RunWithExceptionLog>b__0()
System.Exception: Test failed! [Ice Forge's [Waste Filter]] is not enabled and operating.
   at Eco.Gameplay.WorldObjectDebugUtil.ThrowIfNotRunning(WorldObject obj)
   at Eco.Gameplay.Pipes.PipeTests.Sewage(User user)
```

**Comment by WeaselDog** [comment]
Re-disabled CITest. There is an existing issue to get the test about to CITest: https://github.com/strangeloopgames/ecoissues/issues/13687
