### ISSUE TITLE
Client will be kicked by do some interactions with carts

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2103]
He said by doing some interactions with cars moving from carts to stockpile and vise versa it causes following error in server console:

```
[41:39] Caught network exception from Failender!  Disconnecting...
[41:39] Disconnecting client [reason: Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Changes could not be applied, the requested operation would result in an invalid inventory state.


Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.Modify(Action`1 callback, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnAct(InteractionContext context, Func`2 resultFunc)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
]...
```

**Comment by MarjieAVolk** [comment]
I believe this will be fixed in the next staging build too, which will be released today.  Reopen if you still see the issue on the new version
