### ISSUE TITLE
Election corrupted server savefiles

### ISSUE THREAD

**Issue by Thalassicus** [StrangeLoopGames/EcoIssues#21074]
An executive action on our server to transfer all property owned by a demographic to a title crashed the server, and corrupted the savefiles. We had to revert to an earlier backup.

```
[17:59:46.984] [12] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.GameValueContext`1.Value(IContextObject context)
   at Eco.Gameplay.Civics.GameValues.Values.Residence.Value(IContextObject action)
   at Eco.Gameplay.Civics.SendNotice.<>c__DisplayClass23_0.b__0()
   at Eco.Gameplay.GameActions.PostResult.<>c__DisplayClass13_0.b__0()
   at Eco.Gameplay.GameActions.PostResult.DoPostResults()
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.PerformBase(User executingUser)
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.Perform(User executingUser, Election election)
   at Eco.Gameplay.Civics.Elections.Election.ApplyIfFinished(Boolean forceEnd)
   at Eco.Gameplay.Civics.ElectionManager.Tick()
   at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
```

**Comment by TwixterZ** [comment]
@Thalassicus thank you for reporting this issue, can you also shares the draft for this executive action?(in game screenshot)

**Comment by Thalassicus** [comment]
I'll try to get you a screenshot as soon as I have time.

Here's a link to the savefile:
https://www.dropbox.com/s/nzt6kce8dr81a0l/corrupted.zip?dl=0

In general, the executive action transferred all property belonging to the Migrant demographic (not active or admin, <1 hour played, >48 hour citizen age) to the elected title Minister of Commerce.

**Comment by IronyTroll** [comment]
Looks like these 3 recent issues are related:

#20804 

#21101 

#21074

**Comment by IcedForge** [comment]
Following up on this issue post 9.3 Are you still running into these? (there were some fixes for these issues deployed ) and if so please comment on it.

**Comment by IcedForge** [comment]
Will close as non responsive for 14 days, assume issue is resolved with the fixes we applied. Please reopen if you still run into this problem.
