### ISSUE TITLE
[0.9.3.0 beta staging-1964]Admin command /owner if not authorized does not work if owner is a title

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21089]
If you try to use admin command /owner on a property that is owned by a title that you do not have access to it will throw the following error

```
[12:59:28.607] [106] [Error] [Eco] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.<>c__DisplayClass12_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass2_0.<RunWithExceptionLog>b__0()
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Property.Deed.TryChangeOwners(GameActionPack pack, Player changer, IAlias newOwner, Boolean transferAction, Boolean autoPerform, Boolean okBox, Boolean superAccess)
   at Eco.Gameplay.Property.PropertyCommands.Owner(User user, User newOwner)
```

**Comment by IcedForge** [comment]
Resolved in 9.3 staging 1967
