### ISSUE TITLE
9.2.4 - Server crash - Animal Brain

### ISSUE THREAD

**Issue by mrstark22** [StrangeLoopGames/EcoIssues#21128]
Version: 9.2.4

Occasional server crashing (roughly once per week) with due to what appears to be a crash during animal brain tick. Unable to reproduce through any player action, appears to be completely random. Possibility exists that there is a player trigger but seems unlikely.

Relevant error log details. Everything prior to this is NAT Punches and server boot logging:

[07:06:19.992] [175] [Error] [Eco] System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Eco.Simulation.Agents.AI.BehaviorComplex`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorSelector`1.Do(T context)
   at Eco.Simulation.Agents.AI.Brain.TickBehaviors(Animal animal)
   at Eco.Simulation.Agents.AI.Brain.Tick(Animal animal)
   at Eco.Simulation.Agents.Animal.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Simulation.EcoSim.<DoTick>b__41_0()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[07:06:20.010] [5] [ Info] [Eco] Saving...  
[07:06:35.460] [5] [ Info] [Eco] Saving... Finished in 15,430.0ms
 
[07:06:39.612] [152] [Error] [Eco] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Eco.Simulation.Agents.AI.BehaviorComplex`1.Do(T context)
   at Eco.Simulation.Agents.AI.BehaviorSelector`1.Do(T context)
   at Eco.Simulation.Agents.AI.Brain.TickBehaviors(Animal animal)
   at Eco.Simulation.Agents.AI.Brain.Tick(Animal animal)
   at Eco.Simulation.Agents.Animal.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Simulation.EcoSim.<DoTick>b__41_0()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__33_0(PluginRegistration reg)

Full Error Log Attached
[log_210326034347.log](https://github.com/StrangeLoopGames/EcoIssues/files/6216733/log_210326034347.log)

**Comment by StanKryvenko** [comment]
I've investigated this issue and it should be related to the fixed not the thread-safe issue: https://github.com/StrangeLoopGames/EcoIssues/issues/20771
