### ISSUE TITLE
[0.9.3 staging-1966] Vehicle authorization issue.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21138]
- [ ] 1. You are not authorized to use your own vehicle. Step to reproduce:
- place any vehicle and try to use it:
![image](https://user-images.githubusercontent.com/45708377/112796681-fa99ff80-9072-11eb-9cb3-122e79890c92.png)
- I found 1 legal way to fix it. Open vehicle authorization window by click Shift+LMB here:
![image](https://user-images.githubusercontent.com/45708377/112796767-1bfaeb80-9073-11eb-9465-4dd1426fdfb0.png)
- and add yourself to access list:
![image](https://user-images.githubusercontent.com/45708377/112796823-303ee880-9073-11eb-8a3e-ae4538e86385.png)

- [ ] 2. Claim button should be visible only when vehicle is unowned. 
![image](https://user-images.githubusercontent.com/45708377/112797259-d12da380-9073-11eb-9af7-63ca7aa72b5c.png)
But I think there is a problem with determining the owner because you can see that this vehicle unowned here:
![image](https://user-images.githubusercontent.com/45708377/112797362-f3272600-9073-11eb-8bad-d7fd13909e7b.png)

Also check adding players in Authorized consumers after fix this issue.

**Comment by SlayksWood** [comment]
check #20950 too

**Comment by SlayksWood** [comment]
Still have problem with authorization tab. It says that Vehicle is unowned. But I don't know how to reproduce it. It happens only with one vehicle(perhaps this vehicle is first placed)
![image](https://user-images.githubusercontent.com/45708377/113145302-f28abd00-9236-11eb-86e7-4168ee0abb05.png)

Also when I unclaim vehicle I have UI glitch:
![image](https://user-images.githubusercontent.com/45708377/113146471-624d7780-9238-11eb-9e09-7d042ec15911.png)
But when I claim it again I have crash:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Auth.AuthManager.<>c__DisplayClass0_0.<CanPerform>b__0(Deed deed)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Auth.AuthManager.CanPerform(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Property.Deed.TryChangeOwners(GameActionPack pack, Player changer, IAlias newOwner, Boolean transferAction, Boolean autoPerform, Boolean okBox, Boolean superAccess)
   at Eco.Gameplay.Property.Deed.ChangeOwners(Player changer, IAlias newOwner)
   at Eco.Gameplay.Components.Auth.StandaloneAuthComponent.ClaimOwnership(Player player)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```
[vehicle crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6236615/vehicle.crash.txt)
