### ISSUE TITLE
[0.9.3.0 beta staging-1966] /test interactobjects disconnect clients 

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21147]
Server error log

```
[13:14:54.434] [25] [Error] [Eco] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.<>c__DisplayClass12_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass2_0.<RunWithExceptionLog>b__0()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.IntegrationTests.Framework.Helpers.Log(Exception e, Type t, String msg)
   at Eco.IntegrationTests.Tests.TestWorldObjectPlacement.InteractObjects(User user)
```

**Comment by IcedForge** [comment]
This is most likely due to incorrect behavior of the settlement objects that are not yet properly functioning.
this is whats in the chat log just prior to kicking me out
![Screenshot_31.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/7b73a065-ecfd-42d6-9e07-fa27696ad846)

**Comment by TwixterZ** [comment]
Performed retest on 9.5.1 Release - 310, issue no longer persist
