### ISSUE TITLE
[0.9.3.0 beta staging-1966] /test placeobjects

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21149]
Server error Log
```
[13:26:09.636] [23] [Error] [Eco] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.<>c__DisplayClass12_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass2_0.<RunWithExceptionLog>b__0()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.IntegrationTests.Framework.Helpers.Log(Exception e, Type t, String msg)
   at Eco.IntegrationTests.Tests.TestWorldObjectPlacement.PlaceObjects(User user)
```
Most likely the settlement objects causing trouble here as well, similar to /test interactobjects exception

**Comment by WeaselDog** [comment]
Related to settlements
