### ISSUE TITLE
[0.9.3.0 beta staging-1966]/test InteractItems throws exception on use

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21145]
Server error log

```
[13:09:49.095] [124] [Error] [Eco] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.<>c__DisplayClass12_0.<InvokeCommand>b__1()
   at Eco.Core.Utils.Async.TaskUtils.<>c__DisplayClass2_0.<RunWithExceptionLog>b__0()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.IntegrationTests.Framework.Helpers.Log(Exception e, Type t, String msg)
   at Eco.IntegrationTests.Tests.TestItems.InteractItems(User user)
```

**Comment by WeaselDog** [comment]
I get a null reference exception related to RPC which causes a server crash.

**Comment by SlayksWood** [comment]
It crashes my server now:
[ServerCrash NullReferenceException 05110132.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6457163/ServerCrash.NullReferenceException.05110132.txt)
[UnhandledException NullReferenceException 05110132.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6457164/UnhandledException.NullReferenceException.05110132.txt)
