### ISSUE TITLE
[0.9.3 release-184] Can't migrate White tiger cycle 10

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21308]
https://drive.google.com/file/d/1vBiHPylX02eiHy53IfosJ8ZJSu-62x9p/view?usp=sharing
[log_210408120622.log](https://github.com/StrangeLoopGames/EcoIssues/files/6277913/log_210408120622.log)
```
Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.WorkOrder.get_Product()
   at Eco.Gameplay.Items.WorkOrder.UILinkContent()
   at Eco.Gameplay.Systems.TextLinks.UILinkExtensions.UILink(ILinkable linkable)
   at Eco.Gameplay.Utils.SimpleEntry.get_MarkedUpName()
   at Eco.Core.Utils.PropertyScanning.PropertyScanner.SetupValidity(ScanScope scope, ScanSettings settings, ScanResults results)
   at Eco.Core.Utils.PropertyScanning.PropertyScanner.ScanObj(Object root, ScanSettings settings)
   at Eco.Core.Utils.PropertyScanning.PropertyScanner.Scan(ScanSettings settings)
   at Eco.Gameplay.Utils.SimpleEntry.Initialize()
   at Eco.Gameplay.Economy.WorkParties.WorkParty.Initialize()
   at Eco.Core.Systems.Registrar.Initialize()
   at Eco.Core.Systems.Registrars.Init()
   at Eco.Core.Utils.Initializer.Initialize()
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   ```

**Comment by WeaselDog** [comment]
This one breaks because of custom recipes being missing. Can you test migrating a work order with tailoring upgrade? It should be fine.

**Comment by SlayksWood** [comment]
We are constantly migrating worlds, with changed recipes, tiger still does not migrate with this exception.
