### ISSUE TITLE
Giant Panda Boot Loop Error

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21309]
Doesn't come up again:
[14:20:23.042] [25] [Error] [Eco] System.AggregateException: One or more errors occurred. (The method or operation is not implemented.)

System.NotImplementedException: The method or operation is not implemented.
   at LiteDB.BufferSliceExtensions.ReadIndexKey(BufferSlice buffer, Int32 offset)
   at LiteDB.Engine.IndexNode..ctor(IndexPage page, Byte index, BufferSlice segment)
   at LiteDB.Engine.IndexPage.GetIndexNode(Byte index)
   at LiteDB.Engine.LiteEngine.GetLastId(Snapshot snapshot)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass16_0.<SetSequence>b__0(String s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at LiteDB.Engine.LiteEngine.SetSequence(Snapshot snapshot, BsonValue newId)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 entities)
   at LiteDB.LiteCollection`1.Upsert(T entity)
   at Eco.Stats.Stats.Record(Int32 time, String collection, Single value)
   at Eco.Simulation.WorldLayers.SimStats.CollectStats(Double delta)
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[14:20:37.430] [5] [ Info] [Eco] [Server Initialization]... Finished in 65.158,8ms
 
[14:20:37.430] [5] [ Info] [Eco] Saving...  
[14:20:41.389] [41] [Error] [Eco] System.NotImplementedException: The method or operation is not implemented.
   at LiteDB.BufferSliceExtensions.ReadIndexKey(BufferSlice buffer, Int32 offset)
   at LiteDB.Engine.IndexNode..ctor(IndexPage page, Byte index, BufferSlice segment)
   at LiteDB.Engine.IndexPage.GetIndexNode(Byte index)
   at LiteDB.Engine.LiteEngine.GetLastId(Snapshot snapshot)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass16_0.<SetSequence>b__0(String s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at LiteDB.Engine.LiteEngine.SetSequence(Snapshot snapshot, BsonValue newId)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 entities)
   at LiteDB.LiteCollection`1.Upsert(T entity)
   at Eco.Stats.Stats.Record(Int32 time, String collection, Single value)
   at Eco.Simulation.WorldLayers.SimStats.CollectStats(Double delta)
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg)

**Comment by D3nnis3n** [comment]
Happened after this crash:
[giantpanda.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6278583/giantpanda.txt)

**Comment by gzatravkin** [comment]
Well seems like this issue happened due to slow db operations.
"Error inserting stat of type ItemCraftedAction into databaseLiteDB.LiteException: Database lock timeout when entering in transaction mode after 00:01:00".

Database perfomance was improved in 9.3 (and 9.4) so hopefully it won't happen again.

**Comment by D3nnis3n** [comment]
Doesn't seem so. Tiger just started to throw these and become unavailable to join:
[20:27:46.395] [1166] [Error] [Eco] Error inserting stat of type PayRentOrMoveInFee into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:46.395] [1166] [Error] [Eco] Error inserting stat of type TransferMoney into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:46.438] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:46.438] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:46.438] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:46.502] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:46.524] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:46.644] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:46.889] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.167] [1253] [Error] [Eco] Error when verifying login token: The operation has timed out.
 
[20:27:47.167] [1253] [ Info] [Eco] User Sparky's login info could not be verified. Our auth servers may be down...
 
[20:27:47.228] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.228] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.365] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.427] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.427] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.447] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.447] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.506] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.660] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.679] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.679] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:47.701] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:48.001] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:48.126] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)
 
[20:27:48.126] [1185] [Error] [Eco] Error inserting stat of type Play into databaseLiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj)

**Comment by D3nnis3n** [comment]
Otter also shown issues:
https://github.com/StrangeLoopGames/EcoIssues/issues/21559

**Comment by gzatravkin** [comment]
So most probably this issue will be fixed by using @mirasrael branch of LiteDb. So I am offering to upgrade staging and develop to use it.

**Comment by SlayksWood** [comment]
сдщыув фы ашчувю
