### ISSUE TITLE
[0.9.3.0 beta release-194] Crash on startup after server update

### ISSUE THREAD

**Issue by thoys** [StrangeLoopGames/EcoIssues#21394]
```
[08:02:35] [Eco Server 0.9.3.0 beta release-194]
[08:02:35] [Starting [PerformancePlugin]]...
[08:02:35] [Starting [PerformancePlugin]]... [Finished in 0.3ms]
[08:02:35] [Server Initialization]...
[08:02:35] Starting LocalizationPlugin...
[08:02:35] Starting LocalizationPlugin... Finished in 0.3ms
[08:02:35] Starting NetworkManager...
[08:02:35] Starting NetworkManager... Finished in 0.0ms
[08:02:35] Starting DifficultySettings...
[08:02:35] Starting DifficultySettings... Finished in 0.0ms
[08:02:35] Loading mods...
[08:02:42] Loading Eco.IntegrationTests...
[08:02:42] Loading mods... Finished in 6,581.6ms
[08:02:42] Starting ModKitPlugin...
[08:02:42] Starting ModKitPlugin... Finished in 0.0ms
[08:02:42] Initializing Simulation Types...
[08:02:42] Starting BackupPlugin...
[08:02:42] Starting BackupPlugin... Finished in 0.0ms
[08:02:42] Initializing Simulation Types... Finished in 387.5ms
[08:02:42] Initializing items...
[08:02:42] Starting WorldGeneratorPlugin...
[08:02:42] Starting WorldGeneratorPlugin... Finished in 0.0ms
[08:02:45] [Server Initialization]... Finished in 10,627.9ms
[08:02:45] Failed to start the server. Exception was Exception: FormatException
Message:Input string was not in a correct format.
Source:System.Private.CoreLib

System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Could not convert string '37chemaType' to dictionary key type 'System.Int32'. Create a TypeConverter to convert from the string to the key type object. Path '37chemaType', line 1, position 79156.
Error converting value "37chemaType" to type 'System.Int32'. Path '37chemaType', line 1, position 79156.
[08:02:48] Initializing items... Finished in 5,961.2ms
[08:02:48] Initializing skills...
[08:02:48] Initializing skills... Finished in 34.8ms
[08:02:50] Shutdown finished
```

**Comment by thoys** [comment]
Turns out that my save games corrupted since this morning. Bringing back a backup from in the night worked for me. But it is strange that it keeps on putting 37chemaType throughout the whole schema json file
