### ISSUE TITLE
[9.4 Develop 260] Skill learning broken in develop

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21483]
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/bcdf0d43-c159-4af7-b4a2-0f7391fb68cd)

Learning any skills in Develop build will cause server error, blocking player from loading back their world. 

Log : 
```
[Error] [Eco] Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Skills.Skillset.LearnSkill(Type skillType)
   at Eco.Gameplay.Skills.Skillset.OnDeserialized()
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
Error(s) occurred when loading Users (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
```

**Comment by TwixterZ** [comment]
Repro steps : 
Create fresh world > learn a skill > disconnect > try to reconnect back

**Comment by TwixterZ** [comment]
Same will happens even without learning any skills 
Create fresh world > disconnect > try to reconnect back

this only happens on 9.4 build 260, tested on build 259 is working fine.
