### ISSUE TITLE
White Tiger crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21563]
[log_210424111702.log](https://github.com/StrangeLoopGames/EcoIssues/files/6370744/log_210424111702.log)

Please reassign as needed.

**Comment by mirasrael** [comment]
@gzatravkin seems laws transfer related:
```
[23:29:36.341] [9] [Error] [Eco] System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.)
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Gameplay.Objects.WorldObjectManager.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__36_0(PluginRegistration reg)
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Eco.Gameplay.Economy.Transfers.AccountsChangeSet..ctor(GameActionPack pack)
   at Eco.Gameplay.Economy.Transfers.AccountsChangeSet.GetOrCreate(GameActionPack pack)
   at Eco.Gameplay.Economy.Transfers.TransferInternal(GameActionPack pack, Single amount, Currency currency, BankAccount sourceAccount, BankAccount targetAccount, Boolean isTax, Boolean useFullDesc, Nullable`1 notify, LocString desc, Nullable`1 sourceDesc, Nullable`1 targetDesc)
   at Eco.Gameplay.Economy.Transfers.Transfer(GameActionPack pack, TransferData data)
   at Eco.Gameplay.Civics.Tax_LegalAction.ComposeTransfers(GameActionPack helperPack, TransferInfo values)
   at Eco.Gameplay.Civics.MoneyTransfer_LegalAction.Do(LocString description, IContextObject action, Law law)
   at Eco.Gameplay.Civics.MoneyTransfer_LegalAction.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.LegalAction.PerformAndProcessResullt(Law law, GameAction action)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, LawSection section, Int32 index, StringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action)
   at Eco.Gameplay.Civics.Laws.Law.Perform(GameAction action)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.Components.AirPollutionComponent.PolluteByLaw(Vector3i worldPos, Single pollutionTons, Single timePolluting)
   at Eco.Gameplay.Components.AirPollutionComponent.TryPollute(Single tons, Single timePolluting)
   at Eco.Gameplay.Components.AirPollutionComponent.Tick()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```
