### ISSUE TITLE
USER ISSUE: Tried to sell to the government store

### ISSUE THREAD

**Issue by Sleepybear** [StrangeLoopGames/EcoIssues#21588]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
Have store owned by a government title, sell items to it. 

**Expected behavior:**
Sold the thing

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Titles.ElectedTitle.Contains(IAlias alias)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Economy.TreasuryBankAccount.CanAccess(IAlias alias, AccountAccess access, Boolean sendNoticeOnFail)
   at Eco.Gameplay.Economy.Transfers.Transfer(GameActionPack pack, TransferData data)
   at Eco.Gameplay.Components.StoreComponent.BuildTransfers(GameActionPack pack, PurchaseData data, User customer, BankAccount customerAccount)
   at Eco.Gameplay.Components.StoreComponent.PerformTradeWithPurchaseData(User purchaser, PurchaseData tradeData, BankAccount purchaserAccount)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player tradeIniator, BSONObject tradeData, BankAccount purchaserAccount)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope!

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for your report. This should be resolved with 9.3.3, please reopen the issue if you still encounter this after updating.
