### ISSUE TITLE
USER ISSUE: Crash after setting up carving table

### ISSUE THREAD

**Issue by BogusCurry** [StrangeLoopGames/EcoIssues#21621]
\
**User Id: (slg21810)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
Carving table hinstellen

**Expected behavior:**
crash vom Clienten

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Server encountered an exception:

<size=60.00%>Exception: MissingMethodException
Message:Method not found: 'Void Eco.Gameplay.Components.MinimapComponent.Initialize(System.String)'.
Source:em-games

System.MissingMethodException: Method not found: 'Void Eco.Gameplay.Components.MinimapComponent.Initialize(System.String)'.
   at Eco.EM.Games.CarvingTableObject.Initialize()
   at Eco.Gameplay.Objects.WorldObject.BeginInitialize()
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.Add(WorldObject worldObject, User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.ForceAdd(Type worldObjectType, User creator, Vector3 position, Quaternion rotation, Boolean validatePlacement, WorldObjectItem item)
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass34_0.<TryPlaceWorldObject>b__0()
   at Eco.Gameplay.GameActions.GameActionPack.<>c__DisplayClass17_0.<AddPostEffect>b__0()
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Objects.WorldObjectManager.TryPlaceWorldObject(Player player, WorldObjectItem item, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass26_1.<OnActRight>b__1()
   at Eco.Gameplay.Items.WorldObjectItem.TryPlaceObject(Player player, Vector3i position, Quaternion rotation, Action successCallback)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass26_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.<>c__DisplayClass22_0`1.<Call>b__0(Object o)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__71_4()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
EM - Artistry, EM - Framework, EM - The Conv Pack, EM - The Deco Pack, EM - The Features Pack

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Greetings
Bogus

**Comment by TwixterZ** [comment]
@BogusCurry thank you for raising this issue, however this issue is coming from one of the mod you use, kindly raise this issue with the mod author instead.
