### ISSUE TITLE
[0.9.4 develop-270] ArgumentOutOfRangeException when try to connect from develop to any release server.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21644]
I tried to connect with 0.9.4 develop-270 to server 0.9.3.3 release-219 by id:
![image](https://user-images.githubusercontent.com/45708377/116540898-70ec8480-a8f3-11eb-8981-fdd663b279b9.png)
![image](https://user-images.githubusercontent.com/45708377/116540969-8661ae80-a8f3-11eb-8028-880c804af56d.png)

```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: ArgumentOutOfRangeException
Message:Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Source:System.Private.CoreLib

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Eco.Shared.Serialization.BSONObject.get_Item(String key) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Shared\Serialization\SimpleBSON.cs:line 893
   at Eco.Shared.Authentication.LoginSession.FromBson(BSONObject bson) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Shared\Authentication\LoginSession.cs:line 47
   at Eco.Shared.Serialization.BsonManipulator.FromBson(BSONValue value, Type type) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Shared\Serialization\AutoBsonSerializer.cs:line 178
   at Eco.Shared.Networking.RPCManager.UnpackArgs[TArg](INetClient client, IList`1 packedArgs, Func`3 unpackArg, RPCMethod method, Object target) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Shared\Networking\RPCManager.cs:line 515
   at Eco.Shared.Networking.RPCManager.UnpackArgs[TArg](INetClient client, IList`1 packedArgs, Func`3 unpackArg, RPCMethod[] methods, Object target, RPCMethod& targetMethod) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Shared\Networking\RPCManager.cs:line 534
Outer Exceptions:
Could not finding matching RPC signature for method: Authorize.</size>
```
Should have notifdication that I have wronf game version.

**Comment by ptitducanh** [comment]
LoginSession BSON data in 9.4 and 9.3 are different. 
We properly need to figure out how to match those data.

**Comment by gzatravkin** [comment]
@SlayksWood what exactly is excepted? Some message "Invalid version of client" or similar right?

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/117785323-23eea380-b24d-11eb-8e48-01c2d2b2b146.png)
@gzatravkin sorry something didn't see comment. Example here where it was fixed last times:
https://github.com/StrangeLoopGames/EcoIssues/issues/12327#issuecomment-526579060

**Comment by ptitducanh** [comment]
@SlayksWood apparently my fix is on both client and server side. 
That means it only works from client/server 0.9.4

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/120797943-51c1c200-c545-11eb-9938-65b1b32c8d6c.png)

**Comment by SlayksWood** [comment]
Client: 0.9.3.5 release-231, Server: 0.9.4 staging-2041 - works fine:
![image](https://user-images.githubusercontent.com/45708377/124078577-b3941f80-da50-11eb-8482-f6e9c5349c53.png)

Client: staging-2041, Server: 0.9.4 0.9.3.5 release-231 - failed to connect:
![image](https://user-images.githubusercontent.com/45708377/124080983-a75d9180-da53-11eb-9dc7-8947735b8881.png)
also didn't have notice in Server UI that someone tried to connect with wrong version:
![image](https://user-images.githubusercontent.com/45708377/124081042-b7757100-da53-11eb-8b94-28b26055a402.png)

**Comment by SlayksWood** [comment]
In general, this does not work quite as it should, but if in the future this problem does not appear(client 0.9.5 and server 0.9.4), then we can close this bug.
