### ISSUE TITLE
Error with server version mismatch: 9.4 develop client vs 9.3 server

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#21729]
Error when trying to connect to 9.3.x server

Server encountered an exception:

Exception: ArgumentOutOfRangeException
Message:Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Source:System.Private.CoreLib

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Eco.Shared.Authentication.LoginSession.FromBson(BSONObject bson) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Shared\Authentication\LoginSession.cs:line 46
   at Eco.Shared.Serialization.BsonManipulator.FromBson(BSONValue value, Type type) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Shared\Serialization\AutoBsonSerializer.cs:line 178
   at Eco.Shared.Networking.RPCManager.UnpackArgs[TArg](INetClient client, IList`1 packedArgs, Func`3 unpackArg, RPCMethod method, Object target) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Shared\Networking\RPCManager.cs:line 515
   at Eco.Shared.Networking.RPCManager.UnpackArgs[TArg](INetClient client, IList`1 packedArgs, Func`3 unpackArg, RPCMethod[] methods, Object target, RPCMethod& targetMethod) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Shared\Networking\RPCManager.cs:line 534
Outer Exceptions:
Could not finding matching RPC signature for method: Authorize.

**Comment by SlayksWood** [comment]
merged to #21644
