### ISSUE TITLE
[0.9.3.3 beta release-219] Server crash: System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by peetya** [StrangeLoopGames/EcoIssues#21742]
Hi,

Unfortunately, we were not able to start our server in the past 4 hours. Before that, it was working without any problem. Please find the log attached.

Here is the error what we get:
```
[06:32:43.565] [26] [Error] [Eco] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LiteDB.Engine.IndexService.DeleteList(PageAddress pkAddress, HashSet`1 toDelete)
   at LiteDB.Engine.LiteEngine.UpdateDocument(Snapshot snapshot, CollectionPage col, BsonDocument doc, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 entities)
   at LiteDB.LiteCollection`1.Upsert(T entity)
   at Eco.Stats.Stats.Record(Int32 time, String collection, Single value)
   at Eco.Simulation.WorldLayers.SimStats.CollectStats(Double delta)
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__34_0(PluginRegistration reg)
 ```

[log_210503020004.log](https://github.com/StrangeLoopGames/EcoIssues/files/6413153/log_210503020004.log)

**Comment by SlayksWood** [comment]
@peetya Thank you for the report. CAn yopu provide save files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by TwixterZ** [comment]
@peetya Can you assist to provide the save files for this issue for us to look into this better?

**Comment by TwixterZ** [comment]
Closing this issue due to lack of response

Should this issue persist, kindly raise a new Issue
