### ISSUE TITLE
9.3.4 NRE Object reference not set instance - Housing due to no world occupancy on paper machine

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21818]
had been online around 12 hours since previous reboot then got this below error, does the same upon booting up the same world so not a one off but actual issue, restarted to a backup 10min before the error but does the same.

EDIT, server has had to be rolle dback to 6hours 30min ago to find a valid backup, can provide the valid backup and a non working one to help narrow down where the exact issue was, but due to it taking 6 hours 30min to actually cause the crash has.........irritated some of my playerbase due to the length of the rollback

Worldfile available on request via DM on discord 

[08:31:14.049] [860] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Housing.Internal.HousingCalculation.<>c.<EvalRooms>b__8_2(HousingComponent x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Housing.Internal.HousingCalculation.EvalRooms(IEnumerable`1 housingComponents, Single occupancyMult)
   at Eco.Gameplay.Housing.Internal.HousingCalculation.UpdateHousingValue(Deed deed, IList`1 housingComponents)
   at Eco.Gameplay.Housing.PlayerHousingManager.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[08:31:14.081] [4] [ Info] [Eco] Saving...  
[08:38:47.660] [801] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Housing.Internal.HousingCalculation.<>c.<EvalRooms>b__8_2(HousingComponent x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Housing.Internal.HousingCalculation.EvalRooms(IEnumerable`1 housingComponents, Single occupancyMult)
   at Eco.Gameplay.Housing.Internal.HousingCalculation.UpdateHousingValue(Deed deed, IList`1 housingComponents)
   at Eco.Gameplay.Housing.PlayerHousingManager.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__36_0(PluginRegistration reg)
 
[08:39:47.907] [801] [ Info] [Eco] Shutdown finished

**Comment by IcedForge** [comment]
Forwarding this to you @mirasrael since i dont really have the hardware to test whats going on here on his world.

**Comment by MishkaFur** [comment]
Backup from 2AM worked for 2hrs 40min then crashed again with same NRE

[15:56:07.020] [417] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Housing.Internal.HousingCalculation.<>c.<EvalRooms>b__8_2(HousingComponent x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Housing.Internal.HousingCalculation.EvalRooms(IEnumerable`1 housingComponents, Single occupancyMult)
   at Eco.Gameplay.Housing.Internal.HousingCalculation.UpdateHousingValue(Deed deed, IList`1 housingComponents)
   at Eco.Gameplay.Housing.PlayerHousingManager.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[15:56:07.020] [4] [ Info] [Eco] Saving...  
[15:57:12.261] [377] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Housing.Internal.HousingCalculation.<>c.<EvalRooms>b__8_2(HousingComponent x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Housing.Internal.HousingCalculation.EvalRooms(IEnumerable`1 housingComponents, Single occupancyMult)
   at Eco.Gameplay.Housing.Internal.HousingCalculation.UpdateHousingValue(Deed deed, IList`1 housingComponents)
   at Eco.Gameplay.Housing.PlayerHousingManager.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__36_0(PluginRegistration reg)
 
[15:57:43.282] [377] [ Info] [Eco] Shutdown finished

**Comment by MishkaFur** [comment]
Update, testing again due to the above.

Seems placing the paper machine due to it thinking it is 1x1x1 so it is half outside a room makes it crash but only if the object has been given room requirements, crash is seemingly due to no world occupancy for the papermachine

![image](https://user-images.githubusercontent.com/61889138/117545534-16070b80-b01e-11eb-8112-b85aff6a7291.png)

**Comment by WeaselDog** [comment]
It is a hidden item that is not fully setup. We can fix this, and we have a separate issue to address hidden placeholder items in the future.
