### ISSUE TITLE
[9.3.4 release] pan-troglodytes server crashed and unable to start from database issue

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21887]
The pan-trogolodytes server crashed at around 7 AM PDT and has errors when attempting to restart.  I have attached the full logs and a copy of the save, but below is a quick summary of the errors.

[log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6487931/log.txt)

Save: https://drive.google.com/file/d/1z562IOgzczD5CjdHqRnripb6Uq7DQdmg/view?usp=sharing

Happens once to start:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LiteDB.Engine.IndexService.Find(CollectionIndex index, BsonValue value, Boolean sibling, Int32 order)
   at LiteDB.Engine.LiteEngine.UpdateDocument(Snapshot snapshot, CollectionPage col, BsonDocument doc, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 entities)
   at LiteDB.LiteCollection`1.Upsert(T entity)
   at Eco.Stats.Stats.Record(Int32 time, String collection, Single value) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Stats\Stats.cs:line 111
   at Eco.Simulation.WorldLayers.SimStats.RecordStatProps(Int32 timeSeconds, Object statHolder) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Simulation\WorldLayers\SimStats.cs:line 44
   at Eco.Simulation.WorldLayers.SimStats.CollectStats(Double delta) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Simulation\WorldLayers\SimStats.cs:line 37
   at Eco.Simulation.EcoSim.CollectStats() in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Simulation\EcoSim.cs:line 227
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Core\Plugins\PluginTickTimer.cs:line 30
   at Eco.Simulation.EcoSim.DoTick(TickSample tick) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Simulation\EcoSim.cs:line 215
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Simulation\EcoSim.cs:line 192
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Core\Utils\Threading\RepeatableWorkerBase.cs:line 23
```

Spams of this error:
```
Error inserting stat of type ItemCraftedAction into databaseSystem.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at Eco.Stats.Stats.Record(IStat obj) in D:\jenkins_agent\workspace\Eco Release\Server\Eco.Stats\Stats.cs:line 86   
```

**Comment by gzatravkin** [comment]
This issue should be fixed by using @mirasrael fork of litedb

**Comment by SlayksWood** [comment]
closed as fixed.
