### ISSUE TITLE
9.4 Dev 287 - Object reeference not set to instance  lambda method?

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21903]
Not sure exactly what this NRE is from, this is from a backup of my 9.3.4 World, DM me on discord for copy of the world+database

Wiped the database and the world loads

Migrations log file
[2021-05-17.log](https://github.com/StrangeLoopGames/EcoIssues/files/6496970/2021-05-17.log)

![image](https://user-images.githubusercontent.com/61889138/118559129-69d0cd80-b75f-11eb-8355-68c1f92834b3.png)

Text below

[22:27:02.058] [21] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method16436(Closure , Object )
   at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.ToDocument(Type type, Object entity)
   at LiteDB.BsonMapper.ToDocument[T](T entity)
   at Eco.Stats.StatsAggregator.MergeStats(ILiteCollection`1 collection, IEnumerable`1 aggregatableStats, List`1 toUpdate, HashSet`1 toDelete)
   at Eco.Stats.StatsAggregator.Aggregate()
   at Eco.Stats.Stats.SquashAggregatableStats()
   at Eco.Core.Utils.Threading.ActionUtils.<>c__DisplayClass1_0.<AsAsyncCancellableAction>b__0(CancellationToken _)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.IntervalActionWorker.<>n__0(CancellationToken token)
   at Eco.Core.Utils.Threading.IntervalActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
[22:29:45.041] [4] [ Info] [Eco] Server Initialization... Finished in 588,550.7ms

**Comment by SlayksWood** [comment]
Still an issue on 0.9.4 staging-2004
save file: https://drive.google.com/file/d/1oOA402UjHjpV9BPevJBdItyqV97ryMek/view?usp=sharing
[log_210602090215.log](https://github.com/StrangeLoopGames/EcoIssues/files/6582334/log_210602090215.log)
