### ISSUE TITLE
[0.9.3.5]Server not starting due to files not properly extracted .net

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#22080]
User reports getting this error after updating and not being able to boot up a server.

> [12:27:55.640] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
> [12:27:55.659] [1] [ Info] [Eco] [Eco Server 0.9.3.5 beta release-231]
>  
> [12:27:55.809] [1] [Error] [Eco] [Unhandled error]System.BadImageFormatException: Could not load file or assembly 'Eco.Gameplay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Format of the executable (.exe) or library (.dll) is invalid.
>    at Eco.Server.Startup.RegisterCustomTypes()
>    at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
>    at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
>    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
>    at Eco.Server.MainClass.Main(String[] args)

Applied solution

open %temp%\.net in explorer
delete all the EcoServer and EcoServer32 folders
try again

This should force it to retry and apply everything and boot up as intentional.
Need to make sure this works properly and doesn't occur in 9.4 with .net5

**Comment by mirasrael** [comment]
For me seems like files was corrupted or blocked by virus or antivirus from normal load. @IcedForge was you able to reproduce this issue?
