### ISSUE TITLE
[staging-2012] Missing world file crashes when backup runs (Cloud worlds)

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#22161]
Also note it's deleting the stats db

```
[07:04:32] Eco Server 0.9.4.0 beta staging-2012
[07:04:32] Starting PerformancePlugin...
[07:04:32] Starting PerformancePlugin... Finished in 3.7ms
[07:04:32] Server Initialization...
[07:04:32] Starting FeaturesPlugin...
[07:04:32] Starting FeaturesPlugin... Finished in 49.3ms
[07:04:32] Starting BalancePlugin...
[07:04:32] Starting BalancePlugin... Finished in 17.4ms
[07:04:32] Starting NetworkManager...
[07:04:32] Starting NetworkManager... Finished in 128.2ms
[07:04:32] Starting DifficultySettings...
[07:04:32] Starting DifficultySettings... Finished in 37.2ms
[07:04:32] Starting ModKitPlugin...
[07:04:45] Starting ModKitPlugin... Finished in 12,674.8ms
[07:04:45] Loading mods...
[07:04:45] Loading Eco.IntegrationTests...
[07:04:45] Initializing Simulation Types...
[07:04:45] Starting WorldGeneratorPlugin...
[07:04:45] Starting BackupPlugin...
[07:04:45] Starting BackupPlugin... Finished in 80.5ms
[07:04:45] Starting StorageManager...
[07:04:45] Initializing Simulation Types... Finished in 322.6ms
[07:04:45] Initializing items...
[07:04:47] Starting WorldGeneratorPlugin... Finished in 2,406.6ms
[07:04:47] Restoring backup 'hosted-worlds-backups-us-west-1:\[REDACTED]\Storage\HeadBackup\Game\'...
[07:04:53] Starting StorageManager... Finished in 8,684.1ms
[07:04:58] Initializing items... Finished in 12,942.1ms
[07:04:58] Initializing skills...
[07:04:58] Initializing skills... Finished in 59.9ms
[07:04:58] Loading mods... Finished in 13,344.5ms
[07:04:58] Starting GameDataPlugin...
[07:04:58] Starting GameDataPlugin... Finished in 5.3ms
[07:04:58] Starting PausePlugin...
[07:04:58] Starting Stats...
[07:04:58] Stats Database deleted, because of incompatibility with current version
[07:04:58] Starting Stats... Finished in 71.3ms
[07:04:58] Starting PausePlugin... Finished in 82.5ms
[07:04:58] Starting WorldPlugin...
[07:04:58] Initializing world...
[07:04:58] Initializing world... Finished in 8.3ms
[07:04:58] Caching world data...
[07:04:58] Caching world data... Finished in 1.2ms
[07:04:58] Starting WorldPlugin... Finished in 58.0ms
[07:04:58] Starting TimePlugin...
[07:04:58] Starting TimePlugin... Finished in 0.6ms
[07:04:58] Starting ReputationPlugin...
[07:04:58] Starting ReputationPlugin... Finished in 0.8ms
[07:04:58] Starting UserManager...
[07:04:58] Starting UserManager... Finished in 123.0ms
[07:04:58] Starting EcoObjectManager...
[07:04:58] Starting EcoObjectManager... Finished in 0.5ms
[07:04:58] Starting ControllerManager...
[07:05:07] Starting ControllerManager... Finished in 8,833.7ms
[07:05:07] Starting ChatServer...
[07:05:07] Starting GarbagePlugin...
[07:05:07] Starting EconomyPlugin...
[07:05:07] Starting DataExporter...
[07:05:07] Starting VoiceManager...
[07:05:07] Starting DisasterPlugin...
[07:05:07] Starting EconomyPlugin... Finished in 1.9ms
[07:05:07] Starting PropertyManager...
[07:05:07] Starting DataExporter... Finished in 2.1ms
[07:05:07] Starting GarbagePlugin... Finished in 4.2ms
[07:05:07] Starting PropertyManager... Finished in 11.0ms
[07:05:07] Starting MinimapManager...
[07:05:07] Starting MinimapManager... Finished in 3.7ms
[07:05:07] Starting EcoSim...
[07:05:07] Starting ChatServer... Finished in 84.4ms
[07:05:07] Starting VoiceManager... Finished in 83.9ms
[07:05:07] Starting DisasterPlugin... Finished in 99.4ms
[07:05:07] Initializing plants...
[07:05:07] Initializing plants... Finished in 13.6ms
[07:05:07] Starting EcoSim... Finished in 135.7ms
[07:05:07] Starting RouteProbingPlugin...
[07:05:07] Starting RouteProbingPlugin... Finished in 1.0ms
[07:05:07] Starting WorldLayerManager...
[07:05:07] Starting WorldLayerManager... Finished in 61.4ms
[07:05:07] Starting EconomyTracker...
[07:05:07] Starting EconomyTracker... Finished in 1.7ms
[07:05:07] Starting UserTracker...
[07:05:07] Starting UserTracker... Finished in 0.1ms
[07:05:07] Starting CivicsPlugin...
[07:05:07] Starting CivicsPlugin... Finished in 33.1ms
[07:05:07] Starting SettlementsPlugin...
[07:05:07] Starting SettlementsPlugin... Finished in 16.9ms
[07:05:07] Starting WorldObjectManager...
[07:05:08] Starting WorldObjectManager... Finished in 244.1ms
[07:05:08] Starting RoomPlugin...
[07:05:08] Starting RoomPlugin... Finished in 19.7ms
[07:05:08] Starting ObjectivePlugin...
[07:05:08] Starting ObjectivePlugin... Finished in 0.7ms
[07:05:08] Starting SleepPlugin...
[07:05:08] Starting SleepPlugin... Finished in 22.9ms
[07:05:08] Starting AreaBuffManager...
[07:05:08] Starting AreaBuffManager... Finished in 0.9ms
[07:05:08] Starting GameActionAccumulator...
[07:05:08] Starting GameActionAccumulator... Finished in 1.5ms
[07:05:08] Starting WebServerPlugin...
[07:05:08] Starting WebServerPlugin... Finished in 0.1ms
[07:05:08] Starting RconPlugin...
[07:05:08] Starting ChatLogger...
[07:05:08] Starting IntegrationTestsPlugin...
[07:05:08] Starting RconPlugin... Finished in 0.1ms
[07:05:08] Starting IntegrationTestsPlugin... Finished in 0.4ms
[07:05:08] Starting ChatLogger... Finished in 2.3ms
[07:05:08] Initializing registrars for CivicsPlugin...
[07:05:08] Initializing registrars for CivicsPlugin... Finished in 111.9ms
[07:05:08] Initializing registrars for GameDataPlugin...
[07:05:08] Initializing registrars for GameDataPlugin... Finished in 22.0ms
[07:05:08] Initializing registrars for EconomyPlugin...
[07:05:08] Initializing registrars for EconomyPlugin... Finished in 46.9ms
[07:05:08] Initializing registrars for SettlementsPlugin...
[07:05:08] Initializing registrars for SettlementsPlugin... Finished in 9.6ms
[07:05:08] Initializing DifficultySettings...
[07:05:08] Initializing DifficultySettings... Finished in 3.0ms
[07:05:08] Initializing Stats...
[07:05:08] Initializing Stats... Finished in 332.8ms
[07:05:08] Initializing CivicsPlugin...
[07:05:08] Initializing CivicsPlugin... Finished in 59.8ms
[07:05:08] Initializing LocalizationPlugin...
[07:05:08] Initializing LocalizationPlugin... Finished in 40.0ms
[07:05:08] Initializing PerformancePlugin...
[07:05:08] Initializing PerformancePlugin... Finished in 0.2ms
[07:05:08] Initializing ModKitPlugin...
[07:05:09] Initializing ModKitPlugin... Finished in 615.5ms
[07:05:09] Initializing WorldGeneratorPlugin...
[07:05:09] Generating world 0.52km²...
[07:05:11] Generating terrain...
[07:06:00] Generating terrain... Finished in 49,185.2ms
[07:06:00] Spawn terrain blocks...
[07:06:11] Spawn terrain blocks... Finished in 10,921.3ms
[07:06:11] Placing water...
[07:06:12] Placing water... Finished in 1,031.9ms
[07:06:12] Caching world data...
[07:06:17] Caching world data... Finished in 5,408.9ms
[07:06:17] Generating special features...
[07:06:17] Generating special features... Finished in 80.6ms
[07:06:17] Extruding cliffs...
[07:06:20] Extruding cliffs... Finished in 2,850.2ms
[07:06:20] Ticking (Pass 1)...
[07:06:40] Ticking (Pass 1)... Finished in 19,198.8ms
[07:06:40] Initializing world layers...
[07:06:50] Ticking world layers...
[07:06:51] Ticking world layers... Finished in 735.3ms
[07:07:01] Initializing world layers... Finished in 21,898.1ms
[07:07:01] Ticking (Pass 2)...
[07:07:01] Ticking (Pass 2)... Finished in 83.3ms
[07:07:01] Computing stats...
[07:07:04] Computing stats... Finished in 2,791.6ms
[07:07:04] Determining visibility...
[07:07:06] Determining visibility... Finished in 1,438.9ms
[07:07:06] Compressing...
[07:07:16] Compressing... Finished in 10,228.6ms
[07:07:17] Generating world 0.52km²... Finished in 127,919.2ms
[07:07:17] Initializing WorldGeneratorPlugin... Finished in 127,933.2ms
[07:07:17] Initializing GameDataPlugin...
[07:07:17] Initializing GameDataPlugin... Finished in 34.7ms
[07:07:17] Initializing TimePlugin...
[07:07:17] Initializing TimePlugin... Finished in 0.2ms
[07:07:17] Initializing UserManager...
[07:07:17] Initializing UserManager... Finished in 337.9ms
[07:07:17] Initializing EconomyPlugin...
[07:07:17] Initializing EconomyPlugin... Finished in 21.3ms
[07:07:17] Initializing GarbagePlugin...
[07:07:17] Initializing GarbagePlugin... Finished in 5.7ms
[07:07:17] Initializing PropertyManager...
[07:07:17] Initializing PropertyManager... Finished in 13.7ms
[07:07:17] Initializing MinimapManager...
[07:07:17] Initializing MinimapManager... Finished in 135.8ms
[07:07:17] Initializing EcoSim...
[07:07:17] Initializing EcoSim... Finished in 1.1ms
[07:07:17] Initializing UserTracker...
[07:07:17] Initializing UserTracker... Finished in 2.3ms
[07:07:17] Initializing WorldObjectManager...
[07:07:18] Initializing WorldObjectManager... Finished in 112.9ms
[07:07:18] Initializing RoomPlugin...
[07:07:18] Initializing RoomPlugin... Finished in 6.4ms
[07:07:18] Initializing SleepPlugin...
[07:07:18] Initializing SleepPlugin... Finished in 0.3ms
[07:07:18] Initializing AreaBuffManager...
[07:07:18] Initializing AreaBuffManager... Finished in 4.6ms
[07:07:18] Initializing RconPlugin...
[07:07:18] Initializing RconPlugin... Finished in 514.7ms
[07:07:18] Initializing ChatLogger...
[07:07:18] Initializing ChatLogger... Finished in 0.3ms
[07:07:18] Initializing WorldPlugin...
[07:07:18] Ticking Active Chunks...
[07:07:18] Ticking Active Chunks... Finished in 28.4ms
[07:07:18] Compressing Frozen Chunks...
[07:07:18] Compressing Frozen Chunks... Finished in 9.8ms
[07:07:19] Initializing WorldPlugin... Finished in 394.1ms
[07:07:19] Initializing SettlementsPlugin...
[07:07:19] Initializing SettlementsPlugin... Finished in 0.1ms
[07:07:19] Initializing NetworkManager...
[07:07:19] Initializing NetworkManager... Finished in 66.3ms
[07:07:19] Initializing WorldLayerManager...
[07:07:19] Initializing WorldLayerManager... Finished in 0.1ms
[07:07:19] Initializing WebServerPlugin...
[07:07:19] Skipping Windows firewall setup, platform = Unix
[07:07:19] (You may need to manually open port 3001 if the EcoWebServer is inaccessible)
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {7e755d83-f614-4fd4-aa07-d07ed9255d33} may be persisted to storage in unencrypted form.
[07:07:19] Web Server now listening on: http://0.0.0.0:3001
[07:07:19] Initializing WebServerPlugin... Finished in 399.3ms
[07:07:19] Initializing IntegrationTestsPlugin...
[07:07:19] Initializing IntegrationTestsPlugin... Finished in 0.2ms
[07:07:19] EducationComponent references an ecopedia page which should already exist (Education Component) but is missing.
[07:07:20] Skipping Windows firewall setup, platform = Unix
[07:07:20] (You may need to manually open port 3000 if the EcoGameServer is inaccessible)
[07:07:20] Server Initialization... Finished in 168,312.0ms
[07:07:20] Failed to start the server. Exception was Exception: FileNotFoundException
Message:Could not find file '/app/Storage/Game.eco'.
Source:System.Private.CoreLib

System.IO.FileNotFoundException: Could not find file '/app/Storage/Game.eco'.
File name: '/app/Storage/Game.eco'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Eco.Core.Serialization.DataStore.BackupAsync(IFileStorage fileStorage) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Serialization\DataStore.cs:line 163
   at Eco.Core.Backup.BackupPlugin.BackupToAsync(IFileStorage backupStorage) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Backup\BackupPlugin.cs:line 224
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Server\PluginManager.cs:line 149
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Server\Startup.cs:line 192
[07:07:20] Shutting down IntegrationTestsPlugin...
[07:07:20] Shutting down IntegrationTestsPlugin... Finished in 1.3ms
[07:07:20] Shutting down WorldLayerManager...
[07:07:20] Shutting down WorldLayerManager... Finished in 10.6ms
[07:07:20] Shutting down VoiceManager...
[07:07:20] Shutting down VoiceManager... Finished in 0.1ms
[07:07:20] Shutting down NetworkManager...
[07:07:40] No UPnP device with public ip was found
[07:07:40] Shutting down NetworkManager... Finished in 19,515.4ms
[07:07:40] Shutting down SettlementsPlugin...
[07:07:40] Shutting down SettlementsPlugin... Finished in 0.4ms
[07:07:40] Shutting down WorldPlugin...
[07:07:40] Shutting down WorldPlugin... Finished in 0.5ms
[07:07:40] Shutting down RconPlugin...
[07:07:40] Shutting down RconPlugin... Finished in 0.4ms
[07:07:40] Shutting down GameActionAccumulator...
[07:07:40] Shutting down GameActionAccumulator... Finished in 0.3ms
[07:07:40] Shutting down SleepPlugin...
[07:07:40] Shutting down SleepPlugin... Finished in 0.8ms
[07:07:40] Shutting down RoomPlugin...
[07:07:40] Shutting down RoomPlugin... Finished in 0.4ms
[07:07:40] Shutting down WorldObjectManager...
[07:07:40] Shutting down WorldObjectManager... Finished in 2.4ms
[07:07:40] Shutting down EconomyTracker...
[07:07:40] Shutting down EconomyTracker... Finished in 0.3ms
[07:07:40] Shutting down RouteProbingPlugin...
[07:07:40] Shutting down RouteProbingPlugin... Finished in 0.3ms
[07:07:40] Shutting down EcoSim...
[07:07:40] Shutting down EcoSim... Finished in 0.2ms
[07:07:40] Shutting down DisasterPlugin...
[07:07:40] Shutting down DisasterPlugin... Finished in 0.1ms
[07:07:40] Shutting down MinimapManager...
[07:07:40] Shutting down MinimapManager... Finished in 0.1ms
[07:07:40] Shutting down PropertyManager...
[07:07:40] Shutting down PropertyManager... Finished in 0.1ms
[07:07:40] Shutting down GarbagePlugin...
[07:07:40] Shutting down GarbagePlugin... Finished in 0.4ms
[07:07:40] Shutting down EconomyPlugin...
[07:07:40] Shutting down EconomyPlugin... Finished in 0.2ms
[07:07:40] Shutting down ControllerManager...
[07:07:40] Shutting down ControllerManager... Finished in 0.1ms
[07:07:40] Shutting down UserManager...
[07:07:40] Shutting down UserManager... Finished in 0.3ms
[07:07:40] Shutting down ReputationPlugin...
[07:07:40] Shutting down ReputationPlugin... Finished in 0.1ms
[07:07:40] Shutting down TimePlugin...
[07:07:40] Shutting down TimePlugin... Finished in 0.7ms
[07:07:40] Shutting down BackupPlugin...
[07:07:40] Shutting down BackupPlugin... Finished in 262.8ms
[07:07:40] System.IO.FileNotFoundException: Could not find file '/app/Storage/Game.eco'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Eco.Core.Serialization.DataStore.BackupAsync(IFileStorage fileStorage) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Serialization\DataStore.cs:line 163
   at Eco.Core.Backup.BackupPlugin.BackupToAsync(IFileStorage backupStorage) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Backup\BackupPlugin.cs:line 224
   at Eco.Core.Backup.BackupPlugin.ShutdownAsync() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Backup\BackupPlugin.cs:line 203
   at Eco.Server.PluginManager.ShutdownAsync() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Server\PluginManager.cs:line 327
[07:07:40] Shutting down PerformancePlugin...
[07:07:40] Shutting down PerformancePlugin... Finished in 0.3ms
[07:07:40] Shutting down CivicsPlugin...
[07:07:40] Shutting down CivicsPlugin... Finished in 0.3ms
[07:07:40] Shutting down Stats...
[07:07:40] Rebuilding database...
[07:07:40] Rebuilding database... Finished in 83.8ms
[07:07:40] Shutting down Stats... Finished in 89.3ms
[07:07:40] Shutting down StorageManager...
[07:07:40] Shutting down StorageManager... Finished in 2.2ms
[07:07:40] Shutdown finished
```

**Comment by SlayksWood** [comment]
closed as fixed.
