### ISSUE TITLE
[0.9.4 staging-2020] Crash with "objects in the world" tooltip

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22233]
Created a separate issue because I caught it today without /test economics too, just want to find my hewn bench in the world
![image](https://user-images.githubusercontent.com/45708377/121874448-09a65a80-cd10-11eb-970f-3d5a031cfb3b.png)

Step to reproduce:
- create a new world (English), connect to it.
- use /test economics
- write "Store" in chat, mouseover this text to seee tooltip:
![image](https://user-images.githubusercontent.com/45708377/121488635-eb70ef80-c9db-11eb-9b69-66459582fcfe.png)
- crash. 
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Private.CoreLib

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Eco.Shared.Networking.RPCManager.TryCreateInvocation[TArg](INetClient client, Object target, String methodName, IList`1 packedArgs, Func`3 unpackArg, RPCInvocation& invocation)
   at Eco.Core.Controller.ControllerManager.HandleViewRPC(INetClient client, Int32 controllerID, String methodName, BSONObject bson)
Outer Exceptions:
Exception has been thrown by the target of an invocation.</size>
```
[rhfi.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6629529/rhfi.txt)
- This does not always happen. I'd say that it happened 60% with English client and 0/3 with gibberish for me. But a coincidence is possible. If you can't catch crash you can download my world and just try to open this tooltip.
Save files: https://drive.google.com/file/d/1ubpt96RePM-gdJ5Y0UD2N6YSgbBRkW9u/view?usp=sharing

**Comment by SlayksWood** [comment]
Seems fixed, can't reproduce anymore
