### ISSUE TITLE
Hide CDATA / Comments in Ecopedia or give any other option to use full textmeshpro

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#22437]
Currently, in Ecopedia you can't use (or I don't know how to) anything that has attributes, like <color=red>x</color>, as that is not valid XML:
```
System.Xml.XmlException: The '=' character, hexadecimal value 0x3D, cannot be included in a name. Line 30, position 10.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Eco.Shared.Localization.EcopediaLocTools.LoadEcopediaFiles(String targetDirectoryPath, Boolean translate)
   at Eco.Gameplay.EcopediaRoot.EcopediaManager.Build()
   at Eco.Gameplay.Systems.GlobalData.Init()
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
```
The short notation <#FF0000>X</color> has the same issue, as "#" as first in a name is not acceptable for XML.

You can workaround that by either using CDATA or commenting the line out, but Eco will show the CDATA or comment notation:

becomes:
![image](https://user-images.githubusercontent.com/25908592/124381246-bb0e2f80-dcc1-11eb-88e3-a01e317bc5d4.png)

<![CDATA[<b><color=#FF0000>(Disqualified)</color></b>]]>
becomes:
![image](https://user-images.githubusercontent.com/25908592/124381253-c82b1e80-dcc1-11eb-89e7-2a13e8d44792.png)

It would be useful if admins could use the full range of text styling.

**Comment by TwixterZ** [comment]
@WeaselDog This sounds like something how Ecopedia is built, would need your input here on what can be done for it.
