### ISSUE TITLE
Exception has been thrown by target of an invocation - Server Disconnect

### ISSUE THREAD

**Issue by PT-III** [StrangeLoopGames/EcoIssues#22451]
Hello (Sorry for the novel, but want to give you as much detail as possible),

Our team is in the late stages of the game (all tables researched, computer built, 16MW generated), and last night after 150+ hours of game play the server began disconnecting.  

**Actions that occurred that night that were "New" for us:**

- We moved our capital structures from "Old Capital" to "New Tier 4 Capital" - This included our Green Lord and GloWPA Laws which basically limit our CO2 production, and our constitution 
- We produced our first Super Computer and Laboratory (We applied power and hook-ups to both)
- Created first steam tractor (I know... our poor farmers were working in the stone age)
- Added 8MW of power

**Host PC:**
Nvidia 3080
32GB ram
Intel 10850k
Windows 10
Google Fiber connection
No Mods

**The Error:**
The error starts with a red disconnect icon in the lower right hand corner of the screen; after a disconnect I'll attempt to log back in and get the following error:

"The server crashed with error 'Exception has been thrown by the target of an invocation.' and you can't play (!!!)... [see logs]

The logs go through all the normal items, I'll only include the first last few items:

[23:46:23.331] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[23:46:23.331] [1] [ Info] [Eco] [Eco Server 0.9.3.5 beta release-231]

...Bunch of Items that All Finished...

[23:46:51.675] [5] [ Info] [Eco] Starting AreaBuffManager...  
[23:46:51.675] [5] [ Info] [Eco] Starting AreaBuffManager... Finished in 0.0ms
 
[23:46:51.675] [5] [ Info] [Eco] [Server Initialization]... Finished in 28,073.2ms
 
[23:46:51.675] [38] [Error] [Eco] Failed to start the server. Exception was Exception: EndOfStreamException
Message:Unable to read beyond the end of the stream.
Source:System.Private.CoreLib

System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.CurrentSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.EcoSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream)
   at Eco.Core.Serialization.DataStore.Load[T](ExclusiveAccess exclusiveAccess, String folder, Action`1 onLoad, Boolean migrate)
   at Eco.Core.Serialization.DataStore.ExclusiveAccess.Load[T](String folder, Action`1 onLoad, Boolean migrate)
   at Eco.Core.Serialization.DataStore.Load[T](String folder, Action`1 onLoad, Boolean migrate)
   at Eco.Core.Plugins.StorageManager.LoadOrCreate[TStorageType](String folder, Action`1 onCreate)
   at Eco.Gameplay.Systems.Chat.ChatServer..ctor()
Outer Exceptions:
Exception has been thrown by the target of an invocation.
 
[23:46:51.695] [38] [ Info] [Eco] Shutdown finished

Restoring the back up, and rebooting (to be safe), resulted in an additional 60 minutes of play before the next identical crash.

**Comment by PT-III** [comment]
Update:  Jens on the Discord server has recommended purging our chat history using /chat clearhistoryolderthan #, which I have completed, we removed roughly 28,000 chat messages; will test again on Saturday!

**Comment by TwixterZ** [comment]
@PT-III 

its been a while since your last update, does Jens advice helps?

**Comment by PT-III** [comment]
Hello!  
Yes it worked fabulously, we've saved the planet ;-)
THanks!
~P~
    On Tuesday, August 3, 2021, 05:28:15 AM EDT, Khairi ***@***.***> wrote:  
 
 


@PT-III

its been a while since your last update, does Jens advice helps?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TwixterZ** [comment]
thanks for the update, glad that helps!
