### ISSUE TITLE
Room exceptions while loading

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2245]
Some rooms have RoomStats = null while this is running

   at Eco.Gameplay.Rooms.RoomData.AddRoomVolume(Room room)
   at Eco.Gameplay.Rooms.RoomData.<Initialize>b__26_2(Room room)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Rooms.RoomData.Initialize()
   at Eco.Core.Plugins.EditablePlugin`2..ctor(String name)
   at Eco.Gameplay.Rooms.RoomPlugin..ctor()

**Comment by johnkslg** [comment]
Fixed in roomfix branch
