### ISSUE TITLE
Create server crash

### ISSUE THREAD

**Issue by lag78** [StrangeLoopGames/EcoIssues#22471]
Hello,

I have an issue when I launch a local server from the UI with "Host a game button"
Same error when launching manualy EcoServer32.exe but it's work with EcoServer.exe
I try to uninstall and install again but the issue still occurs.

For information : "Host a game button" work fine the day before installing update to 0.9.3.6

Log :
[23:50:53.495] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[23:50:53.505] [1] [ Info] [Eco] [Eco Server 0.9.3.6 beta release-235]
 
[23:50:53.538] [5] [ Info] [Eco] [Starting [PerformancePlugin]]...  
[23:50:53.538] [5] [ Info] [Eco] [Starting [PerformancePlugin]]... [Finished in 0,3ms]
 
[23:50:53.538] [5] [ Info] [Eco] [Server Initialization]...  
[23:50:53.553] [5] [ Info] [Eco] [Server Initialization]... [Finished in 14,1ms]
 
[23:50:53.623] [1] [Error] [Eco] [Failed to start the server. Exception was Exception: BadImageFormatException
Message:Could not load file or assembly 'Eco.ModKit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Format of the executable (.exe) or library (.dll) is invalid.
Source:EcoServer

System.BadImageFormatException: Could not load file or assembly 'Eco.ModKit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'Eco.ModKit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo)
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)]
 
[23:50:53.625] [1] [ Info] [Eco] [Shutdown finished]
 
Thanks for your help

**Comment by lag78** [comment]
Fixed with #18345 solution : opening %TEMP%\.net\ in explorer, and delete any eco folders
