### ISSUE TITLE
[Eco Server 0.9.3.6 beta release-235] Crash on start of server: System.ArgumentNullException: Value cannot be null. (Parameter 'address')

### ISSUE THREAD

**Issue by Motakl** [StrangeLoopGames/EcoIssues#22472]
The Server is running on Debian 10, 16GB Ram ,6 Cores.
Downloaded via SteamCMD.

[02:12:08] [Eco Server 0.9.3.6 beta release-235]
[02:12:08] [Starting [PerformancePlugin]]...
[02:12:08] [Starting [PerformancePlugin]]... [Finished in 0,6ms]
[02:12:08] [Server Initialization]...
[02:12:08] Starting LocalizationPlugin...
[02:12:08] Starting LocalizationPlugin... Finished in 0,6ms
[02:12:09] Starting NetworkManager...
[02:12:09] Starting NetworkManager... Finished in 0,0ms
[02:12:09] Starting DifficultySettings...
[02:12:09] Starting DifficultySettings... Finished in 0,1ms
[02:12:09] Loading mods...
[02:12:25] Loading Eco.IntegrationTests...
[02:12:25] Loading mods... Finished in 15.383,1ms
[02:12:25] Starting ModKitPlugin...
[02:12:25] Starting ModKitPlugin... Finished in 0,1ms
[02:12:25] Initializing Simulation Types...
[02:12:25] Starting BackupPlugin...
[02:12:25] Starting BackupPlugin... Finished in 0,0ms
[02:12:25] Initializing Simulation Types... Finished in 776,1ms
[02:12:25] Initializing items...
[02:12:25] Starting WorldGeneratorPlugin...
[02:12:25] Starting WorldGeneratorPlugin... Finished in 0,0ms
[02:12:33] Starting StorageManager...
[02:12:33] Starting StorageManager... Finished in 0,1ms
[02:12:33] Loading GameData...
[02:12:33] Loading GameData... Finished in 47,1ms
[02:12:33] Starting GameDataPlugin...
[02:12:33] Starting GameDataPlugin... Finished in 0,0ms
[02:12:33] Loading Pause...
[02:12:33] Loading Pause... Finished in 0,2ms
[02:12:33] Starting Stats...
[02:12:33] Starting Stats... Finished in 0,0ms
[02:12:33] Starting PausePlugin...
[02:12:33] Starting PausePlugin... Finished in 0,0ms
[02:12:38] Initializing items... Finished in 12.883,3ms
[02:12:38] Initializing skills...
[02:12:38] Initializing skills... Finished in 102,6ms
[02:12:38] Loading World...
[02:12:41] Loading World... Finished in 2.687,2ms
[02:12:41] Initializing world...
[02:12:42] Initializing world... Finished in 616,7ms
[02:12:42] Caching world data...
[02:12:42] Caching world data... Finished in 1,8ms
[02:12:42] Starting WorldPlugin...
[02:12:42] Starting WorldPlugin... Finished in 0,0ms
[02:12:42] Loading Time...
[02:12:42] Loading Time... Finished in 0,8ms
[02:12:42] Starting TimePlugin...
[02:12:42] Starting TimePlugin... Finished in 0,0ms
[02:12:42] Loading Reputation...
[02:12:42] Loading Reputation... Finished in 7,2ms
[02:12:42] Starting ReputationPlugin...
[02:12:42] Starting ReputationPlugin... Finished in 0,0ms
[02:12:42] Starting PlayerHousingManager...
[02:12:42] Starting PlayerHousingManager... Finished in 0,0ms
[02:12:42] Loading Users...
[02:12:42] Loading Users... Finished in 205,4ms
[02:12:42] Starting UserManager...
[02:12:42] Starting UserManager... Finished in 0,0ms
[02:12:42] Loading Objects...
[02:12:42] Loading Objects... Finished in 134,9ms
[02:12:42] Starting EcoObjectManager...
[02:12:42] Starting EcoObjectManager... Finished in 0,0ms
[02:12:42] Loading ViewTypeData...
[02:12:42] Loading ViewTypeData... Finished in 3,2ms
[02:12:51] Starting ControllerManager...
[02:12:51] Starting ControllerManager... Finished in 0,1ms
[02:12:51] Starting DataExporter...
[02:12:51] Starting DataExporter... Finished in 0,0ms
[02:12:51] Loading Garbage...
[02:12:51] Loading Garbage... Finished in 9,1ms
[02:12:51] Starting VoiceManager...
[02:12:51] Starting VoiceManager... Finished in 0,0ms
[02:12:51] Loading EconomyManager...
[02:12:51] Starting GarbagePlugin...
[02:12:51] Starting GarbagePlugin... Finished in 0,0ms
[02:12:51] Loading EconomyManager... Finished in 126,0ms
[02:12:51] Loading Disasters...
[02:12:51] Starting EconomyPlugin...
[02:12:51] Starting EconomyPlugin... Finished in 0,0ms
[02:12:51] Loading Disasters... Finished in 0,2ms
[02:12:51] Starting DisasterPlugin...
[02:12:51] Starting DisasterPlugin... Finished in 0,0ms
[02:12:51] Loading Chat...
[02:12:52] Loading Chat... Finished in 359,0ms
[02:12:52] Starting ChatServer...
[02:12:52] Starting ChatServer... Finished in 0,1ms
[02:12:52] Loading Property...
[02:12:52] Loading Property... Finished in 85,3ms
[02:12:52] Starting PropertyManager...
[02:12:52] Starting PropertyManager... Finished in 0,0ms
[02:12:52] Starting MinimapManager...
[02:12:52] Starting MinimapManager... Finished in 0,0ms
[02:12:52] Loading Plants...
[02:12:53] Loading Plants... Finished in 685,4ms
[02:12:53] Initializing plants...
[02:12:54] Initializing plants... Finished in 1.344,2ms
[02:12:54] Starting EcoSim...
[02:12:54] Starting EcoSim... Finished in 0,0ms
[02:12:54] Loading RouteProbing...
[02:12:55] Loading RouteProbing... Finished in 640,6ms
[02:12:55] Starting RouteProbingPlugin...
[02:12:55] Starting RouteProbingPlugin... Finished in 0,0ms
[02:12:55] Loading Layers...
[02:12:55] Loading Layers... Finished in 255,2ms
[02:12:55] Initializing world layers...
[02:12:55] Loading ClimateSim...
[02:12:55] Loading ClimateSim... Finished in 1,5ms
[02:12:59] Initializing world layers... Finished in 3.666,0ms
[02:12:59] Starting WorldLayerManager...
[02:12:59] Starting WorldLayerManager... Finished in 0,0ms
[02:12:59] Starting EconomyTracker...
[02:12:59] Starting EconomyTracker... Finished in 0,0ms
[02:12:59] Starting UserTracker...
[02:12:59] Starting UserTracker... Finished in 0,0ms
[02:12:59] Loading Civics...
[02:12:59] Loading Civics... Finished in 20,8ms
[02:12:59] Starting CivicsPlugin...
[02:12:59] Starting CivicsPlugin... Finished in 0,0ms
[02:12:59] Loading Settlements...
[02:12:59] Loading Settlements... Finished in 1,1ms
[02:12:59] Starting SettlementsPlugin...
[02:12:59] Starting SettlementsPlugin... Finished in 0,0ms
[02:12:59] Loading WorldObjects...
[02:12:59] Loading WorldObjects... Finished in 139,5ms
[02:12:59] Starting WorldObjectManager...
[02:12:59] Starting WorldObjectManager... Finished in 0,0ms
[02:12:59] Loading Rooms...
[02:12:59] Loading Rooms... Finished in 11,5ms
[02:12:59] Starting RoomPlugin...
[02:12:59] Starting RoomPlugin... Finished in 0,0ms
[02:12:59] Loading Objectives...
[02:12:59] Loading Objectives... Finished in 0,8ms
[02:12:59] Starting ObjectivePlugin...
[02:12:59] Starting ObjectivePlugin... Finished in 0,0ms
[02:12:59] Loading Sleep...
[02:12:59] Loading Sleep... Finished in 0,6ms
[02:12:59] Starting SleepPlugin...
[02:12:59] Starting SleepPlugin... Finished in 0,0ms
[02:12:59] Starting AreaBuffManager...
[02:12:59] Starting AreaBuffManager... Finished in 0,0ms
[02:12:59] Starting WebServerPlugin...
[02:12:59] Starting WebServerPlugin... Finished in 0,0ms
[02:12:59] Starting IntegrationTestsPlugin...
[02:12:59] Starting IntegrationTestsPlugin... Finished in 0,0ms
[02:12:59] Starting ChatLogger...
[02:12:59] Starting ChatLogger... Finished in 0,0ms
[02:12:59] Initializing registrars for CivicsPlugin...
[02:12:59] Initializing registrars for CivicsPlugin... Finished in 123,9ms
[02:12:59] Initializing registrars for GameDataPlugin...
[02:13:00] Initializing registrars for GameDataPlugin... Finished in 26,7ms
[02:13:00] Initializing registrars for EconomyPlugin...
[02:13:00] Initializing registrars for EconomyPlugin... Finished in 67,7ms
[02:13:00] Initializing registrars for SettlementsPlugin...
[02:13:00] Initializing registrars for SettlementsPlugin... Finished in 11,8ms
[02:13:00] Initializing DifficultySettings...
[02:13:00] Initializing DifficultySettings... Finished in 5,8ms
[02:13:00] Initializing Stats...
[02:13:01] Initializing Stats... Finished in 472,4ms
[02:13:01] Initializing CivicsPlugin...
[02:13:01] Initializing CivicsPlugin... Finished in 32,3ms
[02:13:01] Initializing PerformancePlugin...
[02:13:01] Initializing PerformancePlugin... Finished in 0,3ms
[02:13:01] Initializing LocalizationPlugin...
[02:13:01] Initializing LocalizationPlugin... Finished in 145,8ms
[02:13:01] Initializing ModKitPlugin...
[02:13:03] Initializing ModKitPlugin... Finished in 1.493,4ms
[02:13:03] Initializing WorldGeneratorPlugin...
[02:13:03] Initializing WorldGeneratorPlugin... Finished in 0,5ms
[02:13:03] Initializing TimePlugin...
[02:13:03] Initializing TimePlugin... Finished in 0,1ms
[02:13:03] Initializing PlayerHousingManager...
[02:13:03] Initializing PlayerHousingManager... Finished in 0,5ms
[02:13:03] Initializing UserManager...
[02:13:03] Initializing UserManager... Finished in 381,2ms
[02:13:03] Initializing GarbagePlugin...
[02:13:03] Initializing GarbagePlugin... Finished in 8,3ms
[02:13:03] Initializing EconomyPlugin...
[02:13:03] Initializing EconomyPlugin... Finished in 8,5ms
[02:13:03] Initializing PropertyManager...
[02:13:03] Initializing PropertyManager... Finished in 40,6ms
[02:13:03] Initializing MinimapManager...
[02:13:03] Initializing MinimapManager... Finished in 109,0ms
[02:13:03] Initializing EcoSim...
[02:13:03] Initializing EcoSim... Finished in 2,8ms
[02:13:03] Initializing UserTracker...
[02:13:03] Initializing UserTracker... Finished in 8,7ms
[02:13:03] Initializing WorldObjectManager...
[02:13:05] Initializing WorldObjectManager... Finished in 1.406,8ms
[02:13:05] Initializing RoomPlugin...
[02:13:05] Initializing RoomPlugin... Finished in 187,6ms
[02:13:05] Initializing SleepPlugin...
[02:13:05] Initializing SleepPlugin... Finished in 0,7ms
[02:13:05] Initializing AreaBuffManager...
[02:13:05] Initializing AreaBuffManager... Finished in 7,9ms
[02:13:05] Initializing ChatLogger...
[02:13:05] Initializing ChatLogger... Finished in 0,5ms
[02:13:05] Initializing WorldPlugin...
[02:13:05] Ticking Active Chunks...
[02:13:08] Ticking Active Chunks... Finished in 3.654,4ms
[02:13:08] Compressing Frozen Chunks...
[02:13:10] Compressing Frozen Chunks... Finished in 1.235,2ms
[02:13:10] Initializing WorldPlugin... Finished in 5.677,2ms
[02:13:10] Initializing SettlementsPlugin...
[02:13:10] Initializing SettlementsPlugin... Finished in 0,4ms
[02:13:10] Initializing NetworkManager...
[02:13:10] Initializing NetworkManager... Finished in 58,7ms
[02:13:10] Initializing WorldLayerManager...
[02:13:10] Initializing WorldLayerManager... Finished in 0,1ms
[02:13:10] Initializing WebServerPlugin...
[02:13:10] Skipping Windows firewall setup, platform = Unix
[02:13:10] (You may need to manually open port 3001 if the EcoWebServer is inaccessible)
[02:13:11] Web Server now listening on: http://0.0.0.0:3001
[02:13:11] Initializing WebServerPlugin... Finished in 713,7ms
[02:13:11] Initializing IntegrationTestsPlugin...
[02:13:11] Initializing IntegrationTestsPlugin... Finished in 0,2ms
[02:13:12] Saving world...
[02:13:12] Skipping Windows firewall setup, platform = Unix
[02:13:12] (You may need to manually open port 3000 if the EcoGameServer is inaccessible)

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'address')
   at System.Net.IPEndPoint..ctor(IPAddress address, Int32 port)
   at Eco.Plugins.Networking.NetworkServer.RefreshMasterServerListing(Boolean publicServer)
   at Eco.Plugins.Networking.NetworkManager.ServerListingHeartbeatUpdate()
   at Eco.Plugins.Networking.NetworkManager.<RefreshServerInfo>b__27_0(Object obj)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)

Crash/Dumpfiles i could find:

[ServerCrash ArgumentNullException 07151312.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6819510/ServerCrash.ArgumentNullException.07151312.txt)
[log_210715021208.log](https://github.com/StrangeLoopGames/EcoIssues/files/6819511/log_210715021208.log)
[UnhandledException ArgumentNullException 07151312.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6819512/UnhandledException.ArgumentNullException.07151312.txt)

**Comment by Daniel-Magulado** [comment]
Hi @Motakl 

Thank you for writing this bug report. However, Debian 10 is currently not a supported operating system for this game.
I will, however, forward this to our development team so they can look into it.
Thank you.

**Comment by Motakl** [comment]
Thank you

**Comment by Motakl** [comment]
I tried multiple OS now, always new clean install.
Same error on:

- Ubuntu 18.04LTS 64bit
- CentOS 7 64bit
- CentOS 8 64bit
- Debian 9 64bit
- Debian 10 64bit

Each time the server was installed via SteamCMD and LinuxGSM separately.

**Comment by ThePaul-T** [comment]
Bit of a necro, but this issue has occurred for me, too.

This is likely caused (as it was for myself) by the code used for interface detection (which now can't be bypassed in recent updates), excluding interfaces marked as an "Unknown" type.

It also only grabs the primary IP on an interface (some containerization puts 127.0.0.1/32 on the public interface as the primary IP with the actual public IP as the second IP)

Many containerization types show their virtual interface types as "Unknown" and they are explicitly excluded in the lookup, so it can't find a valid interface.

A workaround is to use network namespaces, but it would be nice to at least document this behaviour better, and allow workarounds.
