### ISSUE TITLE
[9.4 staging 2086]  tooltip crashes server

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#22530]
![2021-08-16 (2)](https://user-images.githubusercontent.com/26339332/129561871-a2d344c9-9fb6-45d0-a052-c27c248dd12f.png)

--BEGIN DUMP--
Dump Time
08/16/2021 11:30:11

Exception
Exception: FormatException
Message:Input string was not in a correct format.
Source:System.Private.CoreLib

System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatError()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Eco.Shared.Localization.Localizer.ToString(LocString locString)
   at Eco.Gameplay.Items.RecipeFamily.LaborExpertsTooltip(TooltipContext context)
   at Eco.Gameplay.Items.RecipeFamily.GetLaborTooltip(Player player)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.

--END DUMP--

**Comment by D3nnis3n** [comment]
Already logged internally, we're currently working on a fix, I'll get you a DM when we got something.

**Comment by D3nnis3n** [comment]
Here is a patched server exe for you, fix is in next staging build: https://drive.google.com/file/d/1ZrZVIggdCBCivkhF2bJ_UIFyO_BMKm4D/view
