### ISSUE TITLE
traded incorrectly at store and got error kicked #4c637828

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2253]
Store was setup as credit (no currency yet) (prices for sale and buying are all 1) i had 2 credit already i thought if i sold one more that would give me 3 credit so i also set it to buy 3 items, this then caused this error

Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC PerformTrade on StoreComponent!

Moving items with a changeset is not yet supported after any stacks have been changed.

Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.MoveItems[TKey](Type itemType, Int32 quantity, Inventory source, Inventory destination, Func2 sourceStackPredicate, Func2 sourceStackOrder)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

When i relogged kept being kicked for inactivity, Server had to be restarted.

**Comment by MarjieAVolk** [comment]
Looks like this will happen any time you try to perform a trade involving more than 1 type of item

**Comment by MarjieAVolk** [comment]
Fixed in next staging
