### ISSUE TITLE
Connection Failed after changing a law using formula

### ISSUE THREAD

**Issue by Spouke-ECO** [StrangeLoopGames/EcoIssues#22585]
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'input')
Source:System.Text.RegularExpressions

System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at Eco.Shared.Utils.MathParser.MathParser.ReplaceVariable(String expression, String variableName, String value)
   at Eco.Gameplay.Civics.GameValues.TextFormula.Description()
Outer Exceptions:
Error during packaging property 'Registrars' of 'Eco.Gameplay.Systems.GlobalData'
Error during packaging property 'IdToObj' of 'Eco.Core.Systems.Registrar'
Error during packaging property 'Sections' of 'Eco.Gameplay.Civics.Laws.Law'
Error during packaging property 'IfThenBlocks' of 'Eco.Gameplay.Civics.Laws.LawSection'
Error during packaging property 'Then' of 'Eco.Gameplay.Civics.IfThenBlock'
Error during packaging property 'Count' of 'Eco.Gameplay.Civics.GameValues.RecordCustomStat'
Exception has been thrown by the target of an invocation.</size>
[log-cant connect.txt](https://github.com/StrangeLoopGames/EcoIssues/files/7046790/log-cant.connect.txt)

**Comment by Daniel-Magulado** [comment]
Hello @Spouke-ECO 

Thank you for writing this bug report.
An internal report has been created.

[ClickUp Report](https://app.clickup.com/t/10591183/ECO-14926)
