### ISSUE TITLE
Problem after restart

### ISSUE THREAD

**Issue by Kederac** [StrangeLoopGames/EcoIssues#22591]
Hello,

Have you ever had this kind of problem after restarting a server?

`[10:16:59.255] [22] [Error] [Eco] Failed to start the server. Exception was Exception: ArgumentOutOfRangeException
Message:Specified argument was out of the range of valid values. (Parameter 'index')
Source:System.Collections.Immutable

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
at System.Collections.Immutable.ImmutableList`1.Node.ItemRef(Int32 index)
at System.Collections.Immutable.ImmutableList`1.get_Item(Int32 index)
at Eco.Core.Utils.ThreadSafeList`1.get_Item(Int32 index)
at Eco.Gameplay.Systems.Chat.CompositeChatData.<>c.b__4_1(ChatData x, ChatData y)
at System.Collections.Generic.ArraySortHelper`1.InsertionSort(Span`1 keys, Comparison`1 comparer)
at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Failed to compare two elements in the array.
`

**Comment by WeaselDog** [comment]
Thank you for reporting this. It seems this was fixed in 9.4.2 but let us know if you encounter any issues in the future.
