### ISSUE TITLE
Database getting corrupted...

### ISSUE THREAD

**Issue by Chickenw** [StrangeLoopGames/EcoIssues#22598]
User Id: (Not logged user)
Version: 0.9.4.1 beta release-242

Steps to Reproduce:
Restart server and server fails to start..

Actual behavior:
Server is failing to restart and throwing errors If i roll back the map it seems to fix itself..
`[09:22:21.454] [4] [ Info] [Eco] Loading Sleep...  
[09:22:21.454] [4] [ Info] [Eco] Starting AreaBuffManager...  
[09:22:21.454] [4] [ Info] [Eco] Starting GameActionAccumulator...  
[09:22:21.454] [4] [ Info] [Eco] Server Initialization... Finished in 90,610.7ms
 
[09:22:21.474] [38] [Error] [Eco] Failed to start the server. Exception was Exception: ArgumentOutOfRangeException
Message:Specified argument was out of the range of valid values. (Parameter 'index')
Source:System.Collections.Immutable

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.ItemRef(Int32 index)
   at System.Collections.Immutable.ImmutableList`1.get_Item(Int32 index)
   at Eco.Core.Utils.ThreadSafeList`1.get_Item(Int32 index)
   at Eco.Gameplay.Systems.Chat.CompositeChatData.<>c.<LoadOrCreate>b__4_1(ChatData x, ChatData y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Failed to compare two elements in the array.
 `

Do you have mods installed? Does the issue happen when no mods are installed?:
Yes Not sure as we never had this issue before and don't know whats triggering it

**Comment by Ry4ndrew** [comment]
Hi @Chickenw 

Thank you for writing this bug report.
We are currently aware of this issue so I'll be merging this report with #22638.

Thank you.
