### ISSUE TITLE
Null Pointer Referencing Old (Removed) Civic Demographic

### ISSUE THREAD

**Issue by Valderg** [StrangeLoopGames/EcoIssues#22609]
Issue: Server Nullpointer exception on startup, causing an instant crash and preventing the server from launching

Steps to Create: Create Civic referencing a bank account for wages, delete bank account, edit civic to use the new bank account which replaces the old civic/bank account reference, restart server.

After creating a working Civic Demographic, after a restart it tries to reference to the previous civic demographic which references to a bank account that no longer exists and gets stuck in a crash loop null pointer exception.

` 
[14:43:21.213] [14] [Error] [Eco] Error: Removing corrupted entry <b><link="ref:Election:4"><ecoicon item="Election"><style="Government">Government Advisor Election</style> <style="ErrorLight">(removed)</style></ecoicon></link></b>: 2 errors:
Position For Winner: If setting wages, must set all of: the wages currency, amount and bank account for the wages.
Position For Winner: <b><link="ref:ElectedTitle:2"><ecoicon item="ElectedTitle"><style="Government">Old Government Advisor</style> <style="ErrorLight">(removed)</style></ecoicon></link></b> is <style="ErrorLight">invalid.</style>: If setting wages, must set all of: the wages currency, amount and bank account for the wages.

[14:44:10.030] [4] [ Info] [Eco] Server Initialization... Finished in 76,577.0ms
 
[14:44:10.034] [14] [Error] [Eco] Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.Pay()
   at Eco.Gameplay.Economy.Jobs.RecurringTransferServiceExtensions.UpdateTransfers(IRecurringTransferService service)
   at Eco.Gameplay.Economy.Jobs.RecurringTransferManager.UpdateTransfers(IRecurringTransferService service)
   at Eco.Gameplay.Economy.Jobs.RecurringTransferManager.Register(IRecurringTransferService transferService)
   at Eco.Gameplay.Economy.Jobs.RecurringTransferServiceExtensions.RegisterWages(IRecurringTransferService group)
   at Eco.Gameplay.Civics.Demographics.Demographic.Initialize()
   at Eco.Core.Systems.Registrar.Initialize()
   at Eco.Core.Systems.Registrars.Init()
   at Eco.Core.Utils.Initializer.Initialize()
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
 
[14:44:15.047] [14] [ Info] [Eco] Shutdown finished
`

**Comment by Daniel-Magulado** [comment]
Hi @Valderg 

Thank you for writing this bug report. However, we are unable to reproduce this issue.
We tried following the steps to recreate that you provided but it's not happening on our end.
Could you upload a video recording of the issue? This will further help us investigate this issue.
Please also provide your complete PC specification including the operating system.
