### ISSUE TITLE
USER ISSUE: Exception when accessing crafting table

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22605]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
No steps to reproduce, it happened randomly one time while playing on the White Tiger official server, just at the moment of accessing a Butchery Table.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidOperationException
Message:Collection was modified; enumeration operation may not execute.
Source:System.Private.CoreLib

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'IncomeAndExpenses' of 'Eco.Gameplay.Players.User'</size>
```

**Log File**
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7070663/Player.log)

**Comment by Daniel-Magulado** [comment]
Hello @Azzurite 

Thank you for writing this bug report. I'll be merging it to an earlier similar report that has the same exception error but has no reproduction steps. https://github.com/StrangeLoopGames/EcoIssues/issues/20939
