### ISSUE TITLE
Database Crashing & Fix?

### ISSUE THREAD

**Issue by Chickenw** [StrangeLoopGames/EcoIssues#22625]
User Id: (Not logged user)
Version: 0.9.4.1 beta release-242

Steps to Reproduce:
It seems to happen at Random? 

Expected behavior:

Actual behavior:
When you restart the server it gives an error
[12:32:26.645] [20] [Error] [Eco] Failed to start the server. Exception was Exception: ArgumentOutOfRangeException
Message:Specified argument was out of the range of valid values. (Parameter 'index')
Source:System.Collections.Immutable

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.ItemRef(Int32 index)
   at System.Collections.Immutable.ImmutableList`1.get_Item(Int32 index)
   at Eco.Core.Utils.ThreadSafeList`1.get_Item(Int32 index)
   at Eco.Gameplay.Systems.Chat.CompositeChatData.<>c.<LoadOrCreate>b__4_1(ChatData x, ChatData y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(Span`1 keys, Comparison`1 comparer, Int32 i, Int32 j)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Failed to compare two elements in the array.
 
[12:32:31.670] [20] [ Info] [Eco] Shutdown finished

Only way to seem to fix this is open the Server database and remove the chat history and its working again.  The command to remove older chat history doesn't seem to be working. But even if it is its still happening...  
![chat](https://user-images.githubusercontent.com/19636340/131551259-445bd932-1d25-49d2-8ae2-90b1557758ab.PNG)
![chat1](https://user-images.githubusercontent.com/19636340/131551279-36a2fc15-f770-41aa-a3fd-61d450fd8667.PNG)

[message.txt](https://github.com/StrangeLoopGames/EcoIssues/files/7085808/message.txt)

**Comment by mirasrael** [comment]
Fix will be available in next version, for now you can just remove entries with 5 bytes size. I.e. Day 0.

**Comment by MishkaFur** [comment]
> 
> 
> Fix will be available in next version, for now you can just remove entries with 5 bytes size. I.e. Day 0.

Any ETA on this being fixed? just had to wipe the files manually following Chickenw's suggestion, clearing chat often helps massively with performance especially memory

**Comment by Ry4ndrew** [comment]
Merging this report with #22638.
