### ISSUE TITLE
USER ISSUE: Crashed server and can no longer log on.

### ISSUE THREAD

**Issue by ApocalypsePal** [StrangeLoopGames/EcoIssues#22632]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Messing with the rent formula
I had enter text formula open and was clicking on things. The plus symbol, drop downs. I'm not sure exactly what I clicked to cause the crash.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'input')
Source:System.Text.RegularExpressions

System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at Eco.Shared.Utils.MathParser.MathParser.ReplaceVariable(String expression, String variableName, String value)
   at Eco.Gameplay.Civics.GameValues.TextFormula.Description()
Outer Exceptions:
Error during packaging property 'PropertyManager' of 'Eco.Gameplay.Systems.GlobalData'
Error during packaging property 'Deeds' of 'Eco.Gameplay.Property.PropertyManager'
Error during packaging property 'Rent' of 'Eco.Gameplay.Property.Deed'
Error during packaging property 'Rent' of 'Eco.Gameplay.Property.RentForProperty'
Error during packaging property 'AmountPerHour' of 'Eco.Gameplay.Economy.Jobs.RecurringTransferDefinition'
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @ApocalypsePal 

Thank you for writing this bug report.
I'll be merging this to an earlier report https://github.com/StrangeLoopGames/EcoIssues/issues/22585
