### ISSUE TITLE
9.4.1 - Save file corrupted [Failed to compare two elements in the array.]

### ISSUE THREAD

**Issue by ChickenHacker1** [StrangeLoopGames/EcoIssues#22658]
Hi SLG,

We regularly reboot our server daily with an automated system. It shuts it down gracefully with the interrupt signal, waits a minute for the save to complete before attempting to start again.
This time, the server did not start up. I can't really reproduce this since it had corrupted so many of the backups. Not entirely sure why, the error points to the chats being the culprit.

Failed to start the server. Exception was Exception: ArgumentOutOfRangeException
Message:Specified argument was out of the range of valid values. (Parameter 'index')
Source:System.Collections.Immutable

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.ItemRef(Int32 index)
   at System.Collections.Immutable.ImmutableList`1.get_Item(Int32 index)
   at Eco.Core.Utils.ThreadSafeList`1.get_Item(Int32 index)
   at Eco.Gameplay.Systems.Chat.CompositeChatData.<>c.<LoadOrCreate>b__4_1(ChatData x, ChatData y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Failed to compare two elements in the array.

I say the save is corrupt, because normally I'm able to restore backups in a less destructive way to the players, by opening Game.eco, finding the file that is causing the errors, and pull that file from a backup. Typically much better for the players to not lose all of their progress. This time, opening Game.eco gave me an error saying that the file was corrupt.

**Comment by Daniel-Magulado** [comment]
Hi @ChickenHacker1 

Thank you for writing this bug report. A fix is already set to roll out in the coming game updates.
Merging this report with https://github.com/StrangeLoopGames/EcoIssues/issues/22591. For now, we recommend to open Game.eco file (it is just a zip) and remove files with 0 length from the Chat directory.
