### ISSUE TITLE
USER ISSUE: "Citizen Statistics" -> "Global Timer" causes exception

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22666]
I tried to make a law that finds out how many hours the server has been running:

![image](https://user-images.githubusercontent.com/2777158/133293594-84883d54-7c69-467d-8b50-d175a021291d.png)

When I then executed that law, the following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: Exception
Message:No stat named GlobalTimer was found (it is case sensitive).
Source:Eco.Stats

System.Exception: No stat named GlobalTimer was found (it is case sensitive).
   at Eco.Stats.StatInfoManager.GetInfo(String s)
   at Eco.Stats.Stats.CountStat(Type stat, Single time, Double withinSeconds, Int32 userID)
   at Eco.Gameplay.Civics.GameValues.StatSum.CountStat(IContextObject context, Double time, Double timeRangeSeconds, Int32 userId)
   at Eco.Gameplay.Civics.GameValues.StatSum.Value(IContextObject action)
   at Eco.Gameplay.Civics.SendNotice.<>c__DisplayClass23_0.<Perform>b__0()
   at Eco.Gameplay.GameActions.PostResult.<>c__DisplayClass13_0.<AddPostEffect>b__0()
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user, SupportedLanguage language, INetObject target)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(String text, User user, SupportedLanguage language, INetObject target)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChatStripped(Player player, String text, SupportedLanguage language, INetObject target)
Outer Exceptions:
Exception has been thrown by the target of an invocation.</size>
```

**Comment by TwixterZ** [comment]
@Azzurite thanks for your report, i can confirm this is happening in current live build 

I will forward this issue to our developer

**Comment by TwixterZ** [comment]
Fix checked and confirmed as of 9.4.3 Staging 2126.

*Removed "Global Timer" from "Then" Action section and moved to "Trigger". As Global Timer is not meant as a stat to show but an action trigger event.

Any existing Law created using Global Timer as action in Then section will need to be removed
