### ISSUE TITLE
PC Server v9.4.2 - The type or namespace name 'SolidWorldObjectBlock' could not be found

### ISSUE THREAD

**Issue by MagicalCodeMonkey** [StrangeLoopGames/EcoIssues#22693]
Just updated to EcoServerPC_v0.9.4.2-beta and I am now getting the following error when trying to start the server.

```
CS0246: The type or namespace name 'SolidWorldObjectBlock' could not be found (are you missing a using directive or an assembly reference?)
Source:Eco.ModKit
```

Full logs:
```
[00:26:09.960] [1] [ Info] [Eco] Eco Server 0.9.4.2 beta release-256
 
[00:26:09.989] [5] [ Info] [Eco] Starting PerformancePlugin...  
[00:26:09.999] [5] [ Info] [Eco] Server Initialization...  
[00:26:09.999] [5] [ Info] [Eco] Starting FeaturesPlugin...  
[00:26:10.030] [5] [ Info] [Eco] Starting BalancePlugin...  
[00:26:10.054] [5] [ Info] [Eco] Starting NetworkManager...  
[00:26:10.157] [5] [ Info] [Eco] Starting DifficultySettings...  
[00:26:10.197] [5] [ Info] [Eco] Starting ModKitPlugin...  
[00:26:28.504] [1] [ Info] [Eco] Mods recompiled with errors.
 
[00:26:28.517] [1] [ Info] [Eco] T:\EcoServer\Mods\UserCode\Objects\TollObject.override.cs(55,91): error CS0246: The type or namespace name 'SolidWorldObjectBlock' could not be found (are you missing a using directive or an assembly reference?)
 
[00:26:28.517] [5] [ Info] [Eco] Server Initialization... Finished in 18,525.2ms
 
[00:26:28.544] [1] [Error] [Eco] Failed to start the server. Exception was Exception: Exception
Message:T:\EcoServer\Mods\UserCode\Objects\TollObject.override.cs(55,91): error CS0246: The type or namespace name 'SolidWorldObjectBlock' could not be found (are you missing a using directive or an assembly reference?)
Source:Eco.ModKit

System.Exception: T:\EcoServer\Mods\UserCode\Objects\TollObject.override.cs(55,91): error CS0246: The type or namespace name 'SolidWorldObjectBlock' could not be found (are you missing a using directive or an assembly reference?)
   at Eco.ModKit.RoslynCompiler.HandleCompilerError(ImmutableArray`1 diagnostics)
   at Eco.ModKit.RoslynCompiler.Compile()
   at Eco.ModKit.RoslynCompiler..ctor(String modsAssemblyPath)
   at Eco.ModKit.ModKitPlugin..ctor()
Outer Exceptions:
Exception has been thrown by the target of an invocation.
 
[00:26:33.556] [1] [ Info] [Eco] Shutdown finished
```

**Comment by SlayksWood** [comment]
@MagicalCodeMonkey Thank you for the report. Looks like you installed mods that cause this crash. Try to delete mod that have this file T:\EcoServer\Mods\UserCode\Objects\TollObject.override.cs

**Comment by MagicalCodeMonkey** [comment]
Apologies, I uninstalled the 3 of the mods that we used but... we also used the [Eco Server Extra Configuration](https://eco.mod.io/eco-server-extra-confuguration) tool to change some values and with it being late last night when I updated, I didn't think about the fact that it obviously dropped those files there.

If anyone else has this same error and comes across this issue, all you need to do is re-run Eco Server Extra Configuration with the previous settings used and it will fix it.

Thanks @SlayksWood and sorry again for reporting something that isn't actually SLG's issue!
