### ISSUE TITLE
Alpha.6 [C25d3277] Server crash on connect

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2270]
![image](https://user-images.githubusercontent.com/1900106/30825631-f0d3d718-a233-11e7-83c4-2e058032e725.png)

Got this crash on on an earliser version too, its quite rare but it appear sometimes if multiple people try to join at the same time.
And again no logs just the pic.

**Comment by Fank** [comment]
Server won't restart only getting follow on startup:
```
C:\Users\Administrator\Downloads\EcoServer_v0.6.0.0-alpha-staging-c25d3277>EcoServer.exe
[57:57] Eco Server 0.6.0.0 alpha staging-c25d3277
[57:57] Server Initialization...
[57:57] Initializing ModKitPlugin... Finished in 4,955.4ms
[57:58] Loading mods... Finished in 20.2ms
[57:58] Initializing items... Finished in 3,483.4ms
[58:02] Initializing skills... Finished in 161.9ms
[58:02] Initializing inventories... Finished in 339.8ms
[58:02] Initializing StorageManager... Finished in 2,235.9ms
[58:02] Initializing WorldGeneratorPlugin... Finished in 191.2ms
[58:02] Initializing NetworkManager... Finished in 48.1ms
[58:04] Initializing SimStats... Finished in 2,619.0ms
[58:04] Initializing WorldPlugin... Finished in 7,453.4ms
[58:05] Loading Stats... Finished in 2,606.2ms
[58:07] Loading World... Finished in 4,830.8ms
[58:12] Initializing TimePlugin... Finished in 45.0ms
[58:12] Loading Time... Finished in 1.3ms
[58:12] Initializing ReputationPlugin... Finished in 132.4ms
[58:12] Loading Reputation... Finished in 97.8ms
[58:12] Initializing UserManager... Finished in 1,734.2ms
[58:12] Loading Users... Finished in 1,677.2ms
[58:14] Initializing EcoObjectManager... Finished in 1,633.8ms
[58:14] Loading Objects... Finished in 1,625.0ms
[58:16] Initializing PropertyManager... Finished in 211.6ms
[58:16] Initializing EcoSim... Finished in 6,389.5ms
[58:16] Initializing ChatServer... Finished in 1,441.5ms
[58:16] Initializing ControllerManager... Finished in 3,093.0ms
[58:16] Loading Property... Finished in 190.6ms
[58:16] Initializing MinimapManager... Finished in 41.6ms
[58:16] Loading Chat... Finished in 1,194.8ms
[58:16] Initializing DisasterPlugin... Finished in 6.9ms
[58:16] Initializing BackupPlugin... Finished in 16.6ms
[58:16] Initializing WirePlugin... Finished in 3.9ms
[58:16] Initializing DifficultySettings... Finished in 41.6ms
[58:17] Loading Plants... Finished in 4,911.9ms

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error(s) occurred when loading Plants
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.Simulation.PlantSim..ctor()
   at Eco.Simulation.EcoSim.Initialize()
   at Eco.Simulation.EcoSim..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__4_3()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor(String configDir)
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
```
@MarjieAVolk this may help :ship:

**Comment by craig-jong** [comment]
Sounds like a migration error. This bug is pre-beta so I'm going close it. If this occurs again in a recent build, please reopen it.
