### ISSUE TITLE
Error: "Server Crashed with error 'Object reference not set to an instance of an object.' and you can't play.  Check logs in 'Eco_Data\Server\Logs' for more information."

### ISSUE THREAD

**Issue by RyukoJohn** [StrangeLoopGames/EcoIssues#22713]
[log_210928122322.log](https://github.com/StrangeLoopGames/EcoIssues/files/7241052/log_210928122322.log)

See attached logs.

Might be related to:
[00:23:43.671] [19] [Error] [Eco] Duplicate special type: Welfare Revision and Everyone.  Destroying second one.
"Welfare Revision" is a demograph that I copied "everyone" and modified to target a specific user to receive credits per hour... Looks like "Everyone" was deleted.

Error cited for failure to launch:

[00:23:43.695] [19] [Error] [Eco] Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Jobs.RecurringTransferServiceExtensions.DeregisterWages(IRecurringTransferService group)
   at Eco.Gameplay.Civics.Demographics.Demographic.Destroyed()
   at Eco.Core.Systems.Registrar.Remove(INetObject netObj, Object obj)
   at Eco.Gameplay.Systems.IRegistrarManager`2.Eco.Gameplay.Systems.IRegistrarManager.InitSpecialEntries()
   at Eco.Gameplay.Civics.Demographics.DemographicManager.Initialize()
   at Eco.Gameplay.Civics.CivicsData.Initialize()
   at Eco.Gameplay.Civics.CivicsPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)

**Comment by RyukoJohn** [comment]
Oh, its worth noting that the "Welfare Revision" was not yet enacted yet.  It was still being voted on.

**Comment by Daniel-Magulado** [comment]
Hi @RyukoJohn 

Thank you for writing this report. Based on your report, does that mean that the "Welfare Revisions" has no Backup Owner?

**Comment by RyukoJohn** [comment]
I think so.  Not 100% sure since I can't log in to check it.

**Comment by RyukoJohn** [comment]
@Daniel-Magulado Post says needs information; but its not clear what information you're looking for...  Please clarify.

**Comment by Acromatic** [comment]
somehow add the everyone demographic back onto the server.. if it's your server do a wipe by deleting the world and database files in storage folder

**Comment by Acromatic** [comment]
if you put the world file into a new folder and point the server gui to find it there you can save the world, but not it's users and info

**Comment by Acromatic** [comment]
somehow add the everyone demographic back onto the server.. if it's your server do a wipe by deleting the world and database files in storage folder

BEST WAY IS TO PERFORM A BACKUP, WHICH IS DONE MANUALLY FAR AS I KNOW

if you put the world file into a new folder and point the server gui to find it there you can save the world, but not it's users and info ***********Duplicate special type: Welfare Revision and Everyone. Destroying second one. ******* but it doesn't "replace"... technically that is a bug but for now you need to use a separate demographic and leave "everyone" intact.

probably you just need a law that addresses everyone rather than trying to change the demographic.. not sure how or why you would do it that way anyway.
