### ISSUE TITLE
Failed to start the server. Exception was Exception: IndexOutOfRangeException

### ISSUE THREAD

**Issue by ClanHost** [StrangeLoopGames/EcoIssues#22710]
Hi, 

We are unable to load our server. We tried rolling back to a different save and found a save that worked 7 days ago.

Link to save http://221.121.159.236/Storage.rar

`[13:01:14.387] [5] [ Info] [Eco] Server Initialization... Finished in 47,256.6ms
 
[13:01:14.409] [11] [Error] [Eco] Failed to start the server. Exception was Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:System.Private.CoreLib

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Shared.Voxel.HashChunkContainer`1.Set(Vector3i pos, T val)
   at Eco.Shared.Voxel.ChunkGrid`1.AddChunk(TChunk chunk)
   at Eco.World.PersistentChunkPack.ForEachChunk(Action`1 action)
   at Eco.World.PersistentChunkGrid.<Load>b__11_0(PersistentChunkObject obj)
   at Eco.Core.Serialization.DataStore.<>c__DisplayClass45_1`1.<LoadAsync>b__1()
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
Error(s) occurred when loading World (Index was outside the bounds of the array.)
 
[13:01:19.417] [11] [ Info] [Eco] Shutdown finished`

**Comment by Daniel-Magulado** [comment]
Hi @ClanHost 

Thank you for writing this report. Upon a close inspection of the world you provided, it looks like a player has used a significant number of admin commands. Due to the use of commands to progress in the world, you uploaded here, certain factors in-game might have maxed out their data capacity or have reached the limits that the developers have set for the world thus the reason for the exception Index Out of Range.

Can you share with us the most recent action any player has done in your world save before you encounter this issue? Specifically, using admin commands.

**Comment by ClanHost** [comment]
Thanks for your reply,

I have attached the Logs directory. http://221.121.159.236/Logs.rar

The server successfully started 15mins after the last server update was released.

I can try find the date and time, but will take time to restore backups. Hope this helps

Ta
