### ISSUE TITLE
Segmentation Fault (Unity/Linux)

### ISSUE THREAD

**Issue by iuriguilherme** [StrangeLoopGames/EcoIssues#22720]
We have the game crash before it starts with a segfault either in the Steam version and in the Linux binary from play.eco

Contents of Player.log:

```
Mono path[0] = '/home/user/Downloads/EcoLinux_v0.9.4.3-beta/Eco_Data/Managed'
Mono config path = '/home/user/Downloads/EcoLinux_v0.9.4.3-beta/Eco_Data/MonoBleedingEdge/etc'
Preloaded 'libAkGuitarDistortion.so'
Preloaded 'libAkPitchShifter.so'
Preloaded 'libAkRecorder.so'
Preloaded 'libAkStereoDelay.so'
Preloaded 'libAkTimeStretch.so'
Preloaded 'libAkTremolo.so'
Preloaded 'libOni.so'
Preloaded 'libdiscord-rpc.so'
Preloaded 'libenet.so'
Preloaded 'libsteam_api.so'
Unable to preload the following plugins:
	libAkSoundEngine.so
Display 0 'LRK32G30RQ 45"': 1920x1080 (primary device).
Unable to load player prefs
Desktop is 1920 x 1080 @ 60 Hz
[Vulkan init] extensions: count=18
[Vulkan init] extensions: name=VK_KHR_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_display_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=1
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_surface_protected_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_wayland_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
Vulkan detection: 2
Initialize engine version: 2020.1.17f1 (9957aee8edc2)
[Subsystems] Discovering subsystems at path /home/user/Downloads/EcoLinux_v0.9.4.3-beta/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
[Vulkan init] extensions: count=18
[Vulkan init] extensions: name=VK_KHR_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_display_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=1
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_surface_protected_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_wayland_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
[Vulkan init] SelectPhysicalDevice requestedDeviceIndex=-1 xrDevice=(nil)
[Vulkan init] Physical Device 0x28cc490 [0]: "llvmpipe (LLVM 12.0.0, 256 bits)" deviceType=4 vendorID=10005 deviceID=0
[Vulkan init] Selected physical device (nil)
Caught fatal signal - signo:11 code:1 errno:0 addr:(nil)
Obtained 12 stack frames.
#0  0x007f23af66c1f0 in funlockfile
#1  0x007f23a63f5a04 in vkGetPhysicalDeviceQueueFamilyProperties
#2  0x007f23afe51dfb in vk::Initialize()
#3  0x007f23afe5bb19 in CreateVKGfxDevice()
#4  0x007f23afdd551e in CreateClientGfxDevice(GfxDeviceRenderer, GfxCreateDeviceFlags)
#5  0x007f23b0264767 in CreateGfxDevice(GfxDeviceRenderer, GfxCreateDeviceFlags)
#6  0x007f23b0264a91 in InitializeGfxDevice()
#7  0x007f23b011b816 in InitializeEngineGraphics(bool)
#8  0x007f23b0132220 in PlayerInitEngineGraphics(bool)
#9  0x007f23b02f84d3 in PlayerMain(int, char**)
#10 0x007f23af490565 in __libc_start_main
#11 0x00000000400569 in _start
```

We've been using Vulkan drivers for AMD from the Ubuntu PPA https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

**Comment by FeepingCreature** [comment]
I have the same issue.
