### ISSUE TITLE
USER ISSUE: Clay Stockpile

### ISSUE THREAD

**Issue by drspencer124** [StrangeLoopGames/EcoIssues#22730]
\
**User Id: (slg171638)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
/build stockpile clay

**Expected behavior:**
Produced a clay stockpile

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
Source:Eco.Gameplay

System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.AddItems(IEnumerable`1 stacks, User user)
   at Eco.Gameplay.Economy.EconomyChatCommands.SpawnStockpile(User user, Vector3i pos, String item1, String item2, String item3, String item4, String item5)
   at Eco.Gameplay.Economy.EconomyChatCommands.Stockpile(User user, String item1, String item2, String item3, String item4, String item5)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @drspencer124 

Thank you for writing this bug report and we apologize if it took us a while to get back to this.
I've created an internal report for this.

**Comment by TwixterZ** [comment]
@drspencer124 Apologies for the late update on your issue. 

Happy to report that his is now fixed for future patch, thank you for your support.
