### ISSUE TITLE
USER ISSUE: White Tiger connect bug

### ISSUE THREAD

**Issue by mitaka99331** [StrangeLoopGames/EcoIssues#22774]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
Connect to White Tiger

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Eco.Mods.Companies.Company.Description()
Outer Exceptions:
Error during packaging property 'Registrars' of 'Eco.Gameplay.Systems.GlobalData'
Error during packaging property 'IdToObj' of 'Eco.Core.Systems.Registrar'
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This should be fixed by now.
