### ISSUE TITLE
USER ISSUE: Crash on exchanging currencties

### ISSUE THREAD

**Issue by SirMcBunny** [StrangeLoopGames/EcoIssues#22846]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
Set down Currency Exchange on plot owned by Title holder
Select non-personal bank account
Attempt to transfer money from another players personal currency to a minted currency

**Expected behavior:**
Exchanged currency properly

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Titles.ElectedTitle.Contains(IAlias alias)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Economy.TreasuryBankAccount.CanAccess(IAlias alias, AccountAccess access, Boolean sendNoticeOnFail)
   at Eco.Gameplay.Economy.Transfers.Transfer(GameActionPack pack, TransferData data)
   at Eco.Gameplay.Components.ExchangeComponent.Purchase(Player player, BankAccount purchaserAccount, Single amount, ExchangeEntry entry)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @SirMcBunny 

Thank you for this report. However, my attempts to reproduce this issue results in failure as no crashes happened on my end. 
Can I request that you reproduce this issue while recording? Furthermore, once you successfully reproduced this issue, kindly upload here your complete game log.
This will help us further investigate this issue.
