### ISSUE TITLE
Server Crash wont reboot 0.9.4.5 beta release 278

### ISSUE THREAD

**Issue by xMasterCrafter** [StrangeLoopGames/EcoIssues#22937]
Could not connect to our server we were playing on it and it crashed when trying to boot up it starts and stops with this error:

[23:52:17.557] [11] [Error] [Eco] Failed to start the server. Exception was Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'target')
Source:Newtonsoft.Json

System.ArgumentNullException: Value cannot be null. (Parameter 'target')
at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
at Eco.Core.Serialization.SerializationUtils.PopulateObjectWithJson(JObject json, Object instance, ObjectCreationHandling objectCreationHandling)
at Eco.Core.Plugins.PluginConfig`1.LoadAsync(String filename)
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
One or more errors occurred. (Value cannot be null. (Parameter 'target'))

no Mods on this game version is the 0.9.4.5 beta release 278 the game was functioning properly then crashed

**Comment by mirasrael** [comment]
The issue seems related to broken .eco config. Can you try to backup Configs folder, replace it with default and try to start server? If it will work then you can try to recover configs from backup one by one until you understand which one is corrupted.

**Comment by IcedForge** [comment]
Will close as lack of response, please reopen with any further additional information after taken the steps above.
