### ISSUE TITLE
Null references when attempting to use slash commands over rcon

### ISSUE THREAD

**Issue by Darkhand81** [StrangeLoopGames/EcoIssues#22948]
Version: 9.4.5 (and any other versions with rcon)

Running almost any informational text command over rcon results in a null reference exception. I'm assuming the server is attempting to send the text to a player, but there is no player when rcon is the entity sending the command.

My specific example is when trying to run `/manage useractivity` to get a list of players and the last time they connected, over rcon. But almost all similar commands result in the same error:

Result in server console:

```[10:43:49] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Systems.Chat.ChatCommandService.HandleCommandAsync(IChatClient chatClient, String text, SupportedLanguage language, INetObject target)
   at Eco.Gameplay.Systems.Chat.ChatManager.ExecuteCommandAsync(IChatClient chatClient, String command, SupportedLanguage language)
   at Eco.Plugins.Rcon.RconClient.PollConnection(CancellationToken token)
```

**Comment by 0ln** [comment]
I second this. I got the exact same error while trying to add players to the whitelist through RCON. The same commands work just fine in-game.
