### ISSUE TITLE
[9.4.6] - Executive action causes server error and client disconnection

### ISSUE THREAD

**Issue by Asharas** [StrangeLoopGames/EcoIssues#22974]
Beforehand: I did rename a user with potentialy offensive nickname 4 days ago with `/objects edit citizen,<ID>` (#22959). I do know it's an unsupported method of doing that and I am aware that it could be the root to this bug.  
If you have any idea of how I could fix this I'm all ears but if you don't, well, reset it is then ^^'

Description:  
When creating an executive action, selecting the type of action (tax, send notice, etc...) causes a server error resulting in client abruptly disconnected with error

Dump file content:
```
--BEGIN DUMP--
Dump Time
02/06/2022 20:59:43

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Constitutional.CivicCondition_ExecutiveActions.<>c.<PassesCondition>b__9_1(IExecutiveAction x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Civics.Constitutional.CivicCondition_ExecutiveActions.PassesCondition(User user, CivicAction action)
   at Eco.Gameplay.Civics.CivicArticle.CanAttempt(User user, CivicAction action)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at Eco.Shared.Utils.ListUtil.TakeSame[TEntry,TVal](IEnumerable`1 list, Func`2 testSame)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Civics.CivicActionFuncs.GetConstitutionActionResult(User user, CivicAction action)
   at Eco.Gameplay.Civics.Laws.ExecutiveActions.CivicAction_PerformExecutiveAction.CanEdit(User user)
   at Eco.Gameplay.Civics.CivicAction.RPCCanSetProperty(INetClient client, String propertyName)
   at Eco.Gameplay.Utils.ClientSetViewExtensions.SetClassOfProperty(Object target, Player player, String newClassName, String propertyName, Int32 listIndex)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.

--END DUMP--
```
 ([full client error](https://github.com/StrangeLoopGames/EcoIssues/files/8011326/client_disconnect.log)).

Steps to reproduce:
- Users noticed shops marked as non-existing, incorrect prices in infoboxes and excessive lag. A server restart fixed it.
- Now selecting any type of executive action when creating an new one causes the client to disconnect with a server error.

Mods:
- Eco Cost Calculator (intalled prior to the bug appearance). Tried without didn't fix.

Thanks in advance 🙏 

Ash

**Comment by Asharas** [comment]
Another thing that may be linked is that an elected title modification passed but resulted in an invalid title. This was fixed by another vote (forced by admin) but the bug persists so no idea if correlation or causality..

**Comment by Asharas** [comment]
Turned out it was the invalid title, I'm closing this issue and will open a new one better documented.
