### ISSUE TITLE
USER ISSUE: Game crashes everytime I try to enter an election

### ISSUE THREAD

**Issue by wmattbrown16** [StrangeLoopGames/EcoIssues#23031]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta staging-2240

**Steps to Reproduce:**
1. Select "enter election" at a ballot box
2. Game crashes to main menu and produces the error message listed below

**Expected behavior:**
I should have been able to enter an election.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Constitutional.CivicDutyUtils.GetSubmitButtonText(CivicDuties civicDuties, Type type, LocString actionText, LocString typeName)
   at Eco.Gameplay.Components.PerformCivicActionComponent.Select(Player player, Type type)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
This is happening on White Tiger. THe server has mods installed, but I don't have any mods installed, personally.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hello @wmattbrown16 ,

Thank you very much for your feedback. Is this issue happening all the time? Were you able to enter election after one more try? Please, it would be appreciated if you could provide the logs.

**Comment by wmattbrown16** [comment]
It’s happened every time I’ve tried to enter an election since 9.5 playtest opened. I know others have had the same issue. I’m sure I could reproduce it, how do I get the logs to send to you?

**Comment by tomesc99** [comment]
@wmattbrown16 The issue has already been reported. It is known that this is happening to a lot of players, we are currently working on it. Thank you very much for your reply.

-* For internal usage purpose: https://app.clickup.com/t/10591183/ECO-18606_
