### ISSUE TITLE
Web server crash

### ISSUE THREAD

**Issue by SDRplay** [StrangeLoopGames/EcoIssues#23053]
Eco Server 0.9.5.0 beta staging-2246

When using the web interface, clicking on "Ecosystem" that is below "Average Global Temperature" in the environmental data section causes the following exception...

```
--BEGIN DUMP--
Dump Time
03/17/2022 21:18:15

Exception
Exception: Exception
Message:No stat named Ecosystem was found (it is case sensitive).
Source:Eco.Stats

System.Exception: No stat named Ecosystem was found (it is case sensitive).
   at Eco.Stats.StatInfoManager.GetInfo(String s)
   at Eco.WebServer.Web.Controllers.StatsController.GetGraphValues(String key, Double startDay, Double endDay)
   at lambda_method36292(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

--END DUMP--
```

**Comment by Daniel-Magulado** [comment]
Hi @SDRplay 

Thank you for submitting this bug report

We have an internal report about this and will be merging your report with it. Thank you for including the game log exception error.

**Comment by Daniel-Magulado** [comment]
This will be patched in the coming game updates.
