### ISSUE TITLE
Server broke between changes to laws.

### ISSUE THREAD

**Issue by alandillon** [StrangeLoopGames/EcoIssues#23086]
eco and db files can be found here 

https://github.com/alandillon/eco

Exception on login was:  https://github.com/alandillon/eco/blob/main/broken/exception.md 

Seemed to happen after we made changes to laws using custom variables.

We also see this in the startup to but it does not prevent login it seems:

![image](https://user-images.githubusercontent.com/3331097/162285917-f90a2b74-8cec-4bc2-be7f-e1482905f8c9.png)

**Comment by MishkaFur** [comment]
This is in 9.5 ^

**Comment by alandillon** [comment]
Yes! Thank you!

**Comment by alandillon** [comment]
So I swapped out the civics file with a older backup and it errored some on start the first time but then was good.

Also before I saw that error there was one about jsonreader was null. I solved that one by replacing all the config files with my backup of them.

**Comment by alandillon** [comment]
it seems today's update has broke civics again?

`--BEGIN DUMP--
Dump Time
04/18/2022 17:11:55

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.CivicAction_ChangeElement.Description()
   at Eco.Gameplay.Civics.Elections.Election.Description()
   at lambda_method14656(Closure , IMvcNetClient , Object )
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Error during packaging property 'Registrars' of 'Eco.Gameplay.Systems.GlobalData'
Error during packaging property 'IdToObj' of 'Eco.Core.Systems.Registrar`1[[Eco.Gameplay.Civics.Elections.Election, Eco.Gameplay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'
Error during packaging property 'Description' of 'Eco.Gameplay.Civics.Elections.Election'

--END DUMP--
`
