### ISSUE TITLE
Server console exception output missing the path to file.

### ISSUE THREAD

**Issue by ChickenHacker1** [StrangeLoopGames/EcoIssues#23103]
Here's an excerpt of an exception. It tells me there's an error, the line and character the error is on, but it does not include the path.

Don't need help fixing the exception, but it should include the path.

[02:12:25] Failed to start the server. Exception was Exception: JsonReaderException
Message:After parsing a value an unexpected character was encountered: c. Path 'Description', line 5, position 31.
Source:Newtonsoft.Json

Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: c. Path 'Description', line 5, position 31.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Eco.Core.Plugins.PluginConfig`1.LoadAsync(String filename)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
One or more errors occurred. (After parsing a value an unexpected character was encountered: c. Path 'Description', line 5, position 31.)

**Comment by D3nnis3n** [comment]
The path not being displayed isn't very comfortable but does work as developed, hence closing this issue.
It's a configuration error, check the configs for mistakes in the json files, can use a validator for quick checking.
Typically we'd recommend just resetting them to default.
