### ISSUE TITLE
USER ISSUE: Se rompió la partida

### ISSUE THREAD

**Issue by FedericoOlive** [StrangeLoopGames/EcoIssues#23196]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
1- jUGADOR OWIN SOLTÓ 2 RECETAS CULINARIAS.
2- YO (Host) agarré los objetos con click izquierdo
3- Crash

**Expected behavior:**

**Actual behavior:**
Ha aparecido el siguiente error:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidOperationException
Message:Could not find object for RPC call of 'GetTooltip' (ID 150797)
Source:Eco.Core

System.InvalidOperationException: Could not find object for RPC call of 'GetTooltip' (ID 150797)
   at Eco.Core.Controller.ControllerManager.HandleViewRPC(INetClient client, Int32 universalID, String methodName, BSONObject bson)
   at Eco.Plugins.Networking.Client.ViewRPC(INetClient client, Int32 id, String methodname, BSONObject bson)
Outer Exceptions:
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, sin mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hola @FedericoOlive ,

Muchas gracias por tu reporte, será investigado. Mientras tanto, ¿podrías describir más detalladamente la situación?, ¿cómo fue exactamente?. También, si pudieras brindarnos los logs de tu partida sería de gran utilidad.

Desde ya muchísimas gracias.
