### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Ramzitopia** [StrangeLoopGames/EcoIssues#23213]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Clicked link has a target that is not ILinkable. Target: Eco.Gameplay.Civics.GameValues.GameValueContext`1[Eco.Gameplay.Aliases.IAlias], Link: view:313:748575
Source:Eco.Gameplay

System.Exception: Clicked link has a target that is not ILinkable. Target: Eco.Gameplay.Civics.GameValues.GameValueContext`1[Eco.Gameplay.Aliases.IAlias], Link: view:313:748575
   at Eco.Gameplay.Systems.TextLinks.TextLinkManager.OnLinkClicked(String linkId, TooltipContext context, TooltipClickContext clickContext)
   at Eco.Gameplay.Players.Player.HandleLinkClicked(String linkId, Boolean cntrPressed, Boolean shiftPressed, TooltipOrigin origin)
Outer Exceptions:
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Thanks for reporting, internal bug report already exists at https://app.clickup.com/t/10591183/ECO-21723
