### ISSUE TITLE
USER ISSUE: out of memory at connecting server (solo server)

### ISSUE THREAD

**Issue by bfaltrep** [StrangeLoopGames/EcoIssues#23245]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
On a solo server.
I played with "continue button" 
I came back to the menu (i presumed the server closed when i came back to the menu)
After few hours, I click on the continue button --> BUG

**Expected behavior:**
it should start the server and connect me to it.

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Failed to connect to the local server. It may be because of server crash, you can check the server logs in D:/PROGRAMS/Steam/steamapps/common/Eco/Eco_Data\Server\Logs for more details.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by bfaltrep** [comment]
today logs associated
[Logs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/8878122/Logs.zip)

**Comment by dl748** [comment]
Adding my log to this

[log_220614041028.log](https://github.com/StrangeLoopGames/EcoIssues/files/8903973/log_220614041028.log)
.

Its worth noting that the EcoServer32.exe shows in Task Manager as getting up to 2GB of used RAM. I was surprised that the Eco game itself was a x64 (64-bit) app and can get over 6 gig, but the server is a x86 (32-bit) app that can't go much over 2gb.  Also my system was using 40 of 256 gb of RAM, so I know I had a enough memory in the system.

**Comment by AlexDocking** [comment]
I got a couple of out of memory exceptions as well on 9.6.2 when I had VS or chrome open using ~2GB/16GB. Windows 11

[12:30:24.230] [106] [Error] [Eco] Failed to start the server. Exception was Exception: OutOfMemoryException
Message:Insufficient memory to continue the execution of the program.
Source:System.Private.CoreLib

System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb)
   at Eco.Shared.LZ4.LZ4Utils.StreamDecode(ReadOnlySpan`1 compressed, MemoryStream decompressed)
   at Eco.Shared.Utils.CompressionUtils.Decompress[TResult](ReadOnlySpan`1 data, Func`2 converter)
   at Eco.World.PersistentChunk.Thaw()
   at Eco.World.PersistentChunk.Access()
   at Eco.World.PersistentChunk.GetBlock(Vector3i localPosition)
   at Eco.World.WorldChunkGrid.GetBlock(WrappedWorldPosition3i worldPos)
   at Eco.World.World.GetBlock(WrappedWorldPosition3i worldPos)
   at Eco.Simulation.Types.PlantSpecies.IsGoodPlacement(WrappedWorldPosition3i placementPosition)
   at Eco.Simulation.PlantSim.<>c__DisplayClass15_0.<.ctor>b__2(KeyValuePair`2 plantPackPair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
Exception has been thrown by the target of an invocation.
One or more errors occurred. (Insufficient memory to continue the execution of the program.) (Insufficient memory to continue the execution of the program.)
 
[12:33:08.406] [25] [Error] [Eco] Failed to start the server. Exception was Exception: OutOfMemoryException
Message:Exception of type 'System.OutOfMemoryException' was thrown.
Source:System.Private.CoreLib

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.WriteByte(Byte value)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.BSONObject.EncodeNow(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.SimpleBSON.EncodeArray(MemoryStream stream, BSONArray array)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.BSONObject.EncodeNow(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.SimpleBSON.EncodeArray(MemoryStream stream, BSONArray array)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.BSONObject.EncodeNow(MemoryStream stream)
   at Eco.Shared.Serialization.BSONObject.Encode(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.EncodeDocument(MemoryStream stream, BSONObject obj)
   at Eco.Shared.Serialization.SimpleBSON.Dump(BSONObject obj)
   at Eco.Core.Controller.ControllerManager..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
