### ISSUE TITLE
Server crash while cutting grass

### ISSUE THREAD

**Issue by surcoufx83** [StrangeLoopGames/EcoIssues#23259]
Dear Strange Loop Games,

I had multiple crashes in Single Player mode. The server log shows an ´System.AggregateException´: ´The given key 'OccupiedShrubSpace' was not present in the dictionary.´ which leads to lost connection.
I've no mods installed. version Eco Server 0.9.5.3 beta release-325

```
[21:19:08.246] [5] [ Info] [Eco] Server Initialization                             ... Finished in 36,437 sec
 
[21:29:05.744] [12] [Error] [Eco] System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (The given key 'OccupiedShrubSpace' was not present in the dictionary.)))

System.AggregateException: One or more errors occurred. (One or more errors occurred. (The given key 'OccupiedShrubSpace' was not present in the dictionary.))
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Eco.Simulation.WorldLayers.NewWorldLayerSync.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerSync.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.<>c.<Tick>b__91_0()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.TryTick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.DoWork()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass4_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
System.AggregateException: One or more errors occurred. (The given key 'OccupiedShrubSpace' was not present in the dictionary.)
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at Eco.Simulation.WorldLayers.NewWorldLayerSync.ApplyInteractions(IGrouping`2 grouping)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
System.Collections.Generic.KeyNotFoundException: The given key 'OccupiedShrubSpace' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.Simulation.WorldLayers.LayerInteractions.PlantInteraction`1.ApplyCapacityConstraints(Single& availablePopulationExtension, String& layerName, Single[] dependencyValues)
   at Eco.Simulation.WorldLayers.LayerInteractions.ProducerSpeciesGrowth.ConstrainedGrowthValue(Single currentValue, Single[] dependencyValues, Single& availablePopulationExtension, String& constrainingLayerName)
   at Eco.Simulation.WorldLayers.LayerInteractions.ProducerSpeciesGrowth.Apply(Single currentValue, Single[] dependencyValues, WorldLayerNeighborInfo[] neighborValues)
   at Eco.Simulation.WorldLayers.NewWorldLayerSync.<>c__DisplayClass22_0.<ApplyInteractions>b__1(Int32 rowIndex)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
 
[21:29:05.744] [5] [ Info] [Eco] Saving                                            ...  
[21:29:07.013] [5] [ Info] [Eco] Saving                                            ... Finished in 1,267 sec
 
[21:29:07.013] [5] [ Info] [Eco] Shutting down IntegrationTestsPlugin              ...  
[21:29:07.013] [5] [ Info] [Eco] Shutting down IntegrationTestsPlugin              ... Finished in 0,000 sec
 
[21:29:07.013] [5] [ Info] [Eco] Shutting down WorldLayerManager                   ...  
[21:29:07.013] [5] [ Info] [Eco] Shutting down WorldLayerManager                   ... Finished in 0,001 sec
 
[21:29:07.013] [129] [Error] [Eco] System.AggregateException: One or more errors occurred. (One or more errors occurred. (The given key 'OccupiedShrubSpace' was not present in the dictionary.))
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Eco.Simulation.WorldLayers.NewWorldLayerSync.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerSync.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.<>c.<Tick>b__91_0()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.TryTick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.DoWork()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass4_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Server.PluginManager.ShutdownAsync()
System.AggregateException: One or more errors occurred. (The given key 'OccupiedShrubSpace' was not present in the dictionary.)
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at Eco.Simulation.WorldLayers.NewWorldLayerSync.ApplyInteractions(IGrouping`2 grouping)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
System.Collections.Generic.KeyNotFoundException: The given key 'OccupiedShrubSpace' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.Simulation.WorldLayers.LayerInteractions.PlantInteraction`1.ApplyCapacityConstraints(Single& availablePopulationExtension, String& layerName, Single[] dependencyValues)
   at Eco.Simulation.WorldLayers.LayerInteractions.ProducerSpeciesGrowth.ConstrainedGrowthValue(Single currentValue, Single[] dependencyValues, Single& availablePopulationExtension, String& constrainingLayerName)
   at Eco.Simulation.WorldLayers.LayerInteractions.ProducerSpeciesGrowth.Apply(Single currentValue, Single[] dependencyValues, WorldLayerNeighborInfo[] neighborValues)
   at Eco.Simulation.WorldLayers.NewWorldLayerSync.<>c__DisplayClass22_0.<ApplyInteractions>b__1(Int32 rowIndex)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by surcoufx83** [comment]
HI @tomesc99 

I've cut a lot of grass with a iron scythe.
Normally nothing special and I did this for some minutes already.
After the crash (and restarting) I continued cutting grass and it worked without any further crashes
