### ISSUE TITLE
9.5.3 - server wont start InvalidDataException 

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#23264]
Server migrated to 9.5.3 on Friday without any issues, just tried to restart server today and receiving the below, same is happening for a backup from 12 hours ago, 24 and 36 hours.

Backup from 12 hours after the migration on Friday is fine

message me on discord mishka#1337 for world file+mods that the server uses

[12:02:17] Failed to start the server. Exception was Exception: InvalidDataException
Message:Error decoding Referenceable
Source:Eco.Core

System.IO.InvalidDataException: Error decoding Referenceable
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeReferenceableEnumerable(BinaryReader reader, Object decodeTarget, Int32 numElements)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Decode(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream)
   at Eco.Core.Serialization.DataStore.Load[T](ExclusiveAccess exclusiveAccess, String folder, Action1 onLoad, Boolean migrate)
   at Eco.Core.Serialization.DataStore.ExclusiveAccess.Load[T](String folder, Action1 onLoad, Boolean migrate)
   at Eco.Core.Serialization.DataStore.Load[T](String folder, Action1 onLoad, Boolean migrate)
   at Eco.Core.Plugins.StorageManager.Load[T](String folder, Action1 onLoad)
   at Eco.Gameplay.Utils.PartitionedData`2.LoadOrCreate(String folder)
   at Eco.Gameplay.Systems.Messaging.Notifications.NotificationManager..ctor()
   at Eco.Gameplay.Systems.Messaging.MessagingServer..ctor()
Outer Exceptions:
Exception has been thrown by the target of an invocation.

**Comment by mirasrael** [comment]
After investigation I found that it somehow has binary corrupted zip entry for Notifications/Day35. When remove that entry it works fine.
