### ISSUE TITLE
USER ISSUE: Error dialog when joining game

### ISSUE THREAD

**Issue by noahfalk** [StrangeLoopGames/EcoIssues#23311]
\
**User Id: (slg184995)**
**Version:** 0.9.6.0 beta staging-2363

**Steps to Reproduce:**
1. Launch Eco
2. Attempt to join the 9.6 playtest game (either via the Continue button or via the list of servers in the Your Worlds UI)
3. The join progress reaching 'Entering World' and then stops with an error prompt

Note: I joined a few hours ago without issue, but after quiting the game and returning now I get this error reliably

**Expected behavior:**
Joined the game with no error message

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Aliases.AliasExtensions.<>c__DisplayClass4_0.<ContainsExactAlias>b__0(IAlias x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Auth.AuthManager.GetAuthorizationLevel(IAlias alias, IOwned property, LazyResult& specialResult, GameAction action)
   at Eco.Gameplay.Auth.AuthManager.GetAuthorizationLevel(IAlias alias, IOwned property, GameAction action)
   at Eco.Gameplay.Property.PropertyPlot.IsAuthorized(IAlias alias)
   at lambda_method45293(Closure , IMvcNetClient , Object )
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Error during packaging property 'PropertyManager' of 'Eco.Gameplay.Systems.GlobalData'
Error during packaging property 'Deeds' of 'Eco.Gameplay.Property.PropertyManager'
Error during packaging property 'Ownables' of 'Eco.Gameplay.Property.Deed'
Error during packaging property 'IsAuthorized' of 'Eco.Gameplay.Property.PropertyPlot'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
In the past yes, but I don't know if those mods would have automatically caried over to the playtest build? I didn't install any mods since switching to this build on steam.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9172759/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9172760/Player-prev.log)

**Comment by noahfalk** [comment]
There error has gone away and I can join the game again.
