### ISSUE TITLE
USER ISSUE: Storing food that is being eaten causes crash.

### ISSUE THREAD

**Issue by X-BT** [StrangeLoopGames/EcoIssues#23316]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.0 beta staging-2363

**Steps to Reproduce:**
1. Carried lumber while eating
2. Clicked to put lumber in cart
3. Clicked once more and accidentially put the food I was eating in the cart

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.InventoryChangeSet.ModifyStack(ItemStack stack, ChangedStack changedStack, Int32 oldQuantity, Int32 delta, Item newItem, Boolean updateComponents)
   at Eco.Gameplay.Items.ItemStackExtensions.TryModifyStack(ItemStack itemStack, User user, Int32 increment, Func`1 test, Action onSuccess)
   at Eco.Gameplay.Items.FoodItem.Consume(Player player)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Mkorny** [comment]
Confirmed!

I could also repro this just by moving the food i was eating from the Quickbar to the Inventory (but only reproed this way once)
