### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by SergeyLesnyak-Roko** [StrangeLoopGames/EcoIssues#23322]
\
**User Id: (slg208386)**
**Version:** 0.9.6.0 beta staging-2363

**Steps to Reproduce:**
1. Login to server (Sea Otter 9.6  playtest)
2. Wait object load progress 100%

**Expected behavior:**
Able to login

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Aliases.AliasExtensions.<>c__DisplayClass4_0.<ContainsExactAlias>b__0(IAlias x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Auth.AuthManager.GetAuthorizationLevel(IAlias alias, IOwned property, LazyResult& specialResult, GameAction action)
   at Eco.Gameplay.Auth.AuthManager.GetAuthorizationLevel(IAlias alias, IOwned property, GameAction action)
   at Eco.Gameplay.Property.PropertyPlot.IsAuthorized(IAlias alias)
   at lambda_method45246(Closure , IMvcNetClient , Object )
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, ISyncMemberInfo memberInfo)

Outer Exceptions:
Error during packaging property 'PropertyManager' of 'Eco.Gameplay.Systems.GlobalData'
Error during packaging property 'Deeds' of 'Eco.Gameplay.Property.PropertyManager'
Error during packaging property 'Ownables' of 'Eco.Gameplay.Property.Deed'
Error during packaging property 'IsAuthorized' of 'Eco.Gameplay.Property.PropertyPlot'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9182895/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9182896/Player-prev.log)

**Comment by SergeyLesnyak-Roko** [comment]
same issues:
https://github.com/StrangeLoopGames/EcoIssues/issues/23321
https://github.com/StrangeLoopGames/EcoIssues/issues/23310
