### ISSUE TITLE
USER ISSUE: Consolodate Crash

### ISSUE THREAD

**Issue by Caldrena** [StrangeLoopGames/EcoIssues#23320]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.0 beta staging-2363

**Steps to Reproduce:**
Attempt to consolidate storage 

**Expected behavior:**
sorted

**Actual behavior:**
Crash

The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: DivideByZeroException
Message:Attempted to divide by zero.
Source:Eco.Gameplay

System.DivideByZeroException: Attempted to divide by zero.
   at Eco.Gameplay.Items.InventoryRelated.ConsolidationUtils.MergeIntoAsFewStacksAsPossible(List`1 changedStack, Int32 currentQuantity, Item itemToAdd, Inventory inventory, User user)
   at Eco.Gameplay.Items.InventoryRelated.ConsolidationUtils.ConsolidateInventory(Inventory inventory, User user)
   at Eco.Gameplay.Components.LinkComponent.ConsolidateLinkedInventory(User user)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Caldrena** [comment]
![image](https://user-images.githubusercontent.com/68741535/180767453-ba091c88-9755-4067-ba4a-8f11c9f91bb4.png)
Storage has many things of varying spoilage

**Comment by D3nnis3n** [comment]
This should have been fixed since the report.
