### ISSUE TITLE
USER ISSUE: 9.6 Sorting items throws divide by zero error

### ISSUE THREAD

**Issue by SergeyLesnyak-Roko** [StrangeLoopGames/EcoIssues#23325]
\
**User Id: (slg208386)**
**Version:** 0.9.6.0 beta staging-2363

**Steps to Reproduce:**

1. have some spoiled food in icebox
2. press sort items

**Expected behavior:**

**Actual behavior:**
game crashed with error message:
Было получено следующее сообщение об ошибке:
```
Server encountered an exception:

<size=60,00%>Exception: DivideByZeroException
Message:Attempted to divide by zero.
Source:Eco.Gameplay

System.DivideByZeroException: Attempted to divide by zero.
   at Eco.Gameplay.Items.InventoryRelated.ConsolidationUtils.MergeIntoAsFewStacksAsPossible(List`1 changedStack, Int32 currentQuantity, Item itemToAdd, Inventory inventory, User user)
   at Eco.Gameplay.Items.InventoryRelated.ConsolidationUtils.ConsolidateInventory(Inventory inventory, User user)
   at Eco.Gameplay.Components.LinkComponent.ConsolidateLinkedInventory(User user)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9196731/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9196733/Player-prev.log)

**Comment by D3nnis3n** [comment]
This should have been fixed since the report.
