### ISSUE TITLE
sever crashed!

### ISSUE THREAD

**Issue by MAD0903** [StrangeLoopGames/EcoIssues#23332]
[21:58:37.317] [1] [ Info] [Eco] Eco 서버 0.9.5.4 beta release-327
 
[21:58:37.349] [5] [ Info] [Eco] 성능 플러그인 시작 중                                      ...  
[21:58:37.349] [5] [ Info] [Eco] 성능 플러그인 시작 중                                      ... Finished in 0.007 sec
 
[21:58:37.349] [5] [ Info] [Eco] ProfilingPlugin 시작 중                              ...  
[21:58:37.349] [5] [ Info] [Eco] ProfilingPlugin 시작 중                              ... Finished in 0.000 sec
 
[21:58:37.349] [5] [ Info] [Eco] MaintenancePlugin 시작 중                            ...  
[21:58:37.395] [5] [ Info] [Eco] MaintenancePlugin 시작 중                            ... Finished in 0.042 sec
 
[21:58:37.395] [5] [ Info] [Eco] 서버 초기값 설정 중                                       ...  
[21:58:37.417] [5] [ Info] [Eco] FeaturesPlugin 시작 중                               ...  
[21:58:37.441] [5] [ Info] [Eco] FeaturesPlugin 시작 중                               ... Finished in 0.029 sec
 
[21:58:37.441] [5] [ Info] [Eco] BalancePlugin 시작 중                                ...  
[21:58:37.441] [5] [ Info] [Eco] BalancePlugin 시작 중                                ... Finished in 0.004 sec
 
[21:58:37.484] [5] [ Info] [Eco] 네트워크 관리자 시작 중                                     ...  
[21:58:37.549] [5] [ Info] [Eco] 네트워크 관리자 시작 중                                     ... Finished in 0.066 sec
 
[21:58:37.549] [5] [ Info] [Eco] 난이도 설정 시작 중                                       ...  
[21:58:37.596] [5] [ Info] [Eco] 난이도 설정 시작 중                                       ... Finished in 0.047 sec
 
[21:58:37.596] [5] [ Info] [Eco] 모드킷 플러그인 시작 중                                     ...  
[21:58:56.199] [5] [ Info] [Eco] 모드킷 플러그인 시작 중                                     ... Finished in 18.603 sec
 
[21:58:56.199] [5] [ Info] [Eco] 모드 불러오는 중                                         ...  
[21:58:56.242] [1] [ Info] [Eco] Eco.통합 테스트 불러오는 중...
 
[21:59:02.924] [5] [ Info] [Eco] 시뮬레이션 종류 초기 설정 중                                  ...  
[21:59:02.924] [5] [ Info] [Eco] 백업 플러그인 시작 중                                      ...  
[21:59:02.924] [5] [ Info] [Eco] 세계 생성 플러그인 시작 중                                   ...  
[21:59:02.924] [5] [ Info] [Eco] 백업 플러그인 시작 중                                      ... Finished in 0.014 sec
 
[21:59:02.924] [5] [ Info] [Eco] 저장 관리자 시작 중                                       ...  
[21:59:03.090] [5] [ Info] [Eco] 시뮬레이션 종류 초기 설정 중                                  ... Finished in 0.131 sec
 
[21:59:03.090] [5] [ Info] [Eco] 아이템 초기값 설정 중                                      ...  
[21:59:03.212] [5] [ Info] [Eco] 세계 생성 플러그인 시작 중                                   ... Finished in 0.287 sec
 
[21:59:08.578] [5] [ Info] [Eco] 저장 관리자 시작 중                                       ... Finished in 5.640 sec
 
[21:59:13.811] [5] [ Info] [Eco] 아이템 초기값 설정 중                                      ... Finished in 10.756 sec
 
[21:59:13.811] [5] [ Info] [Eco] 기술 초기값 설정 중                                       ...  
[21:59:13.870] [5] [ Info] [Eco] 기술 초기값 설정 중                                       ... Finished in 0.059 sec
 
[21:59:13.870] [5] [ Info] [Eco] 모드 불러오는 중                                         ... Finished in 17.667 sec
 
[21:59:13.870] [5] [ Info] [Eco] 게임 데이터 플러그인 시작 중                                  ...  
[21:59:13.870] [5] [ Info] [Eco] GameData 불러오는 중                                   ...  
[21:59:19.365] [5] [ Info] [Eco] GameData 불러오는 중                                   ... Finished in 5.488 sec
 
[21:59:19.365] [5] [ Info] [Eco] 게임 데이터 플러그인 시작 중                                  ... Finished in 5.491 sec
 
[21:59:19.365] [5] [ Info] [Eco] 일시 정지 플러그인 시작 중                                   ...  
[21:59:19.365] [5] [ Info] [Eco] 상태 시작 중                                           ...  
[21:59:19.365] [5] [ Info] [Eco] Pause 불러오는 중                                      ...  
[21:59:19.365] [5] [ Info] [Eco] Pause 불러오는 중                                      ... Finished in 0.000 sec
 
[21:59:19.365] [5] [ Info] [Eco] 상태 시작 중                                           ... Finished in 0.012 sec
 
[21:59:19.407] [5] [ Info] [Eco] 일시 정지 플러그인 시작 중                                   ... Finished in 0.043 sec
 
[21:59:19.407] [5] [ Info] [Eco] 세계 플러그인 시작 중                                      ...  
[21:59:19.445] [5] [ Info] [Eco] World 불러오는 중                                      ...  
[21:59:19.445] [5] [ Info] [Eco] World 불러오는 중                                      ... Finished in 0.002 sec
 
[21:59:19.445] [5] [ Info] [Eco] 세계 플러그인 시작 중                                      ... Finished in 0.034 sec
 
[21:59:19.445] [5] [ Info] [Eco] 서버 초기값 설정 중                                       ... Finished in 42.047 sec
 
[21:59:19.508] [7] [Error] [Eco] Failed to start the server. Exception was Exception: ZlibException
Message:Bad state (invalid stored block lengths)
Source:DotNetZip

Ionic.Zlib.ZlibException: Bad state (invalid stored block lengths)
   at Ionic.Zlib.InflateManager.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibCodec.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ionic.Zlib.DeflateStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ionic.Crc.CrcCalculatorStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at Eco.Core.Serialization.DataStore.LoadAsync[T](ExclusiveAccess exclusiveAccess, String folder, Action`1 onLoad)
   at Eco.Core.Serialization.DataStore.ExclusiveAccess.LoadAsync[T](String folder, Action`1 onLoad)
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`1 onLoad)
   at Eco.Core.Plugins.StorageManager.LoadAsync[T](String folder, Action`1 onLoad)
   at Eco.World.PersistentChunkGrid.Load()
   at Eco.World.PersistentChunkGrid..ctor()
   at Eco.World.WorldPlugin..ctor()
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
 
[21:59:19.508] [7] [ Info] [Eco] 종료 마침

**Comment by D3nnis3n** [comment]
Your savegame is corrupted. You will need to restore a backup. Eco creates those automatically and you can find them in the Storage/Backups folder. Just move the files from the backup you want to restore to the Storage folder (.db and .eco).

Please make sure to always shut down the server gracefully - the most common cause for corrupted save files is shutdowns that weren't graceful and the savegame hence saved incompletely.
