### ISSUE TITLE
USER ISSUE: NullRef: Eating charred sausage (the last sausage)

### ISSUE THREAD

**Issue by Lamargo** [StrangeLoopGames/EcoIssues#23343]
\
**User Id: (slg187722)**
**Version:** 0.9.6.0 beta staging-2387

**Steps to Reproduce:**
1. Log in
2. Equip charred sausage (stack of 1) in 1st person
3. Switch to 3rd person
4. Consume sausage.
5. NullRef shown once eating is complete.

**Expected behavior:**
let me enjoy my sausage, no matter my view point, and no matter the stack size remaining of said sausage.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.InventoryChangeSet.ModifyStack(ItemStack stack, ChangedStack changedStack, Int32 oldQuantity, Int32 delta, Item newItem, Boolean updateComponents)
   at Eco.Gameplay.Items.ItemStackExtensions.TryModifyStack(ItemStack itemStack, User user, Int32 increment, Func`1 test, Action onSuccess)
   at Eco.Gameplay.Items.FoodItem.Consume(Player player)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Just what WT uses.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hello @Lamargo ,

Thank you very much for your report. Please, could you provide more details? Have you been able to reproduce this issue again? If you could provide your logs it would be very useful.

Thanks in advance.

**Comment by Lamargo** [comment]
Unable to replicate. Would logs from 5 days ago still exist on my system?

**Comment by Lamargo** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9374943/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9374944/Player-prev.log)

**Comment by Lamargo** [comment]
Repro'd this just now with baked meat.

Other things I noted was I was looking directly down on my character in 3rd person, so I could see the food get eaten from the plate. The food was in the 0 position on hotbar.
