### ISSUE TITLE
Delivery Contract Crashes Server (Repeatable)

### ISSUE THREAD

**Issue by bakedog417** [StrangeLoopGames/EcoIssues#23388]
A player completed a delivery contract causing a reliable crash.

Error Message Everytime:

`System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.MakeAddItemsNotification(IEnumerable`1 users, IEnumerable`1 data)
   at Eco.Gameplay.Systems.Messaging.Notifications.AggregatedNotifications.GetAndClearReadyAggegatedMessages()+MoveNext()
   at Eco.Gameplay.Systems.Messaging.Notifications.NotificationManager.Tick()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)`

**Comment by ActuallyHappy** [comment]
I believe this was fixed in 0.9.6.1 that was released today

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/23388
