### ISSUE TITLE
USER ISSUE: Was holding up land claim papers

### ISSUE THREAD

**Issue by Berserker66** [StrangeLoopGames/EcoIssues#23387]
\
**User Id: (slg221666)**
**Version:** 0.9.6.0 beta release-334

**Steps to Reproduce:**
pull out land claim papers

**Expected behavior:**
not crash

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Aliases.AliasExtensions.<>c__DisplayClass4_0.<ContainsExactAlias>b__0(IAlias x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Auth.AuthManager.GetAuthorizationLevel(IAlias alias, IOwned property, LazyResult& specialResult, GameAction action)
   at Eco.Gameplay.Auth.AuthManager.IsAuthorized(WorldObject obj, IAlias alias, AccessType access, GameAction action)
   at Eco.Gameplay.Components.Auth.AuthComponent.IsAuthorizedConsumerAccess(Player player)
   at lambda_method22514(Closure , IMvcNetClient , Object )
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Error during packaging property 'IsAuthorizedConsumerAccess' of 'Eco.Gameplay.Components.Auth.PropertyAuthComponent'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and and

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This issue is no longer relevant in Update 10 due to changes claiming mechanics.
