### ISSUE TITLE
workparties got the server in a crash loop had to rollback

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#23399]
[13:39:30.351] [13] [Error] [Eco] System.AggregateException: One or more errors occurred. (Sequence contains no elements)

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable1 source)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.MakeAddItemsNotification(IEnumerable1 users, IEnumerable`1 data)
   at Eco.Gameplay.Systems.Messaging.Notifications.AggregatedNotifications.GetAndClearReadyAggegatedMessages()+MoveNext()
   at Eco.Gameplay.Systems.Messaging.Notifications.NotificationManager.Tick()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>cDisplayClass0_0.<Create>b0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)

**Comment by Asharas** [comment]
Had the same issue on my server except I didn't rollback but users report it did happen as their latest actions where lost (approximatively 5 minutes).  

```
[16:46:08.422] [243] [Error] [Eco] System.AggregateException: One or more errors occurred. (Sequence contains no elements)

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.MakeAddItemsNotification(IEnumerable`1 users, IEnumerable`1 data)
   at Eco.Gameplay.Systems.Messaging.Notifications.AggregatedNotifications.GetAndClearReadyAggegatedMessages()+MoveNext()
   at Eco.Gameplay.Systems.Messaging.Notifications.NotificationManager.Tick()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
  ```
