### ISSUE TITLE
stockpile made the server crash (i think )

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#23401]
[18:06:43.075] [38] [Error] [Eco] System.AggregateException: One or more errors occurred. (LiteDB ENSURE: empty page must be defined as empty type)

System.Exception: LiteDB ENSURE: empty page must be defined as empty type
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.Snapshot.NewPage[T]()
   at LiteDB.Engine.Snapshot.GetFreeDataPage(Int32 bytesLength)
   at LiteDB.Engine.DataService.<>c__DisplayClass3_0.<<Insert>g__source|0>d.MoveNext()
   at LiteDB.Engine.BufferWriter..ctor(IEnumerable`1 source)
   at LiteDB.Engine.DataService.Insert(BsonDocument doc)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.InsertBulk(IEnumerable`1 entities, Int32 batchSize)
   at Eco.Stats.Stats.<>c__DisplayClass31_0.<RecordBulk>b__1(IGrouping`2 group)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Stats.Stats.RecordBulk(IEnumerable`1 objs)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameAction action, Boolean notify)
   at Eco.Gameplay.Items.WorkOrder.TryFinishIteration()
   at Eco.Gameplay.Items.WorkOrder.CheckTime(Boolean canBeActive)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders()
   at Eco.Gameplay.Components.CraftingComponent.Tick(Single deltaTime)
   at Eco.Gameplay.Components.CraftingComponent.Tick()
   at Eco.Gameplay.Objects.WorldObject.<>c.<TickComponents>b__246_0(WorldObjectComponent x)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.TickComponents()
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Gameplay.Objects.WorldObjectManager.TickObject(WorldObject worldObject)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
 
![image](https://user-images.githubusercontent.com/31536813/188279086-9fef61c6-556a-446a-8eba-d49276b80668.png)

**Comment by D3nnis3n** [comment]
That's an issue in LiteDB itself that is reported for over a year and they have unfortunately not found a fix yet: https://github.com/mbdavid/LiteDB/issues/1940

There is not really anything we can do.
