### ISSUE TITLE
USER ISSUE: Exception wehen becoming a resident

### ISSUE THREAD

**Issue by fuchs82** [StrangeLoopGames/EcoIssues#23475]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
I got an invite for a residency and clicked on accept. Then the exception occured and i got disconnected from the server.

**Expected behavior:**
I should have become residency without an error

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Private.CoreLib

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Networking.RPCManager.<>c__DisplayClass23_0`1.<Call>b__0(Object o)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__76_4()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by fuchs82** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9610245/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9610246/Player.log)

**Comment by fuchs82** [comment]
Bug is reproducible when trying to become resident on my friend's deed.

**Comment by Daniel-Magulado** [comment]
Hi @fuchs82 

Thank you for submitting this bug report. Are you by chance playing on one of our official servers? If not, are you able to provide us with the save file? It will aid us in our investigation of this issue. If yes, could you tell us which server it is as well as the coordinates of the plot that you got invited to be a resident of? Looking forward to your response.

**Comment by fuchs82** [comment]
First, I had the problem on a german server called Ecotopia. But now I started a game locally and a friend joined and we have the same problem again, no matter who tries to join the other one's deed as resident. Here is the content of my storage folder. The position of the plot is 73,76,579:
[game-resident-crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/9649178/game-resident-crash.zip)

**Comment by Daniel-Magulado** [comment]
Hi @fuchs82 

Thank you for replying and providing the saved file. I'll provide an update here if we find anything.

**Comment by fuchs82** [comment]
Hi there, I think you can remove the 'status needs information' and classify it as a bug. Or do you need further information?
