### ISSUE TITLE
USER ISSUE: Moving Raw fish in the shop crashes me

### ISSUE THREAD

**Issue by CozyKittenTV** [StrangeLoopGames/EcoIssues#23529]
\
**User Id: (slg164040)**
**Version:** 0.9.6.6 beta release-357

**Steps to Reproduce:**
Shop has all plant seeds available, fish was added and at the bottom, tried to move it to the slot with the seeds to move up more and it crashed

**Expected behavior:**
moved the fish to the spot bove	

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: ArgumentOutOfRangeException
Message:Specified argument was out of the range of valid values. (Parameter 'index')
Source:System.Collections.Immutable

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.ItemRef(Int32 index)
   at System.Collections.Immutable.ImmutableList`1.get_Item(Int32 index)
   at Eco.Core.Utils.ThreadSafeList`1.<>c__DisplayClass46_0.<Move>b__0(ImmutableList`1 x)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ThreadSafeList`1.Move(Int32 index, Int32 newIndex)
   at Eco.Core.Utils.ControllerList`1.<>n__10(Int32 index, Int32 newIndex)
   at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass34_0.<Eco.Core.Utils.IClientControlledList.Move>b__0()
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Core.Utils.ControllerList`1.Eco.Core.Utils.IClientControlledList.Move(INetObject caller, Int32 iEntry, Int32 newIndex)
   at Eco.Gameplay.Utils.IHasClientControlledContainers.Move(Player player, String listName, Int32 iEntry, Int32 newIndex)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, Not sure. Mods include Elixr mods Frame pack, big shovel, and whetstones

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@CozyKittenTV sorry to hear this happens to you, do you still face this issue if you tries to replicate it? 

Is it possible for you to share a video of this happens? as we have not been able to replicate the same result at our end.
