### ISSUE TITLE
new error on opening Minimap

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2355]
Caught exception: Caught exception invoking RPC GetTooltip on MinimapManager!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.

Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Shared.Utils.ReflectionUtils.TryGetValueAsMethod(MemberInfo member, Object o, Object[] methodParams)
   at Eco.Shared.Utils.ReflectionUtils.Value(MemberInfo member, Object o, Object[] parameters)
   at Eco.Gameplay.Systems.Tooltip.TooltipExtensions.TooltipMember`1.GetAsString(Player player)
   at Eco.Gameplay.Systems.Tooltip.TooltipExtensions.<>c__DisplayClass9_0`1.<GetSortedTooltipMembers>b__1(TooltipMember`1 member)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Eco.Shared.Utils.EnumerableExtensions.ToBson[T](IEnumerable`1 enumeration, INetClient client)
   at Eco.Gameplay.Systems.Tooltip.TooltipExtensions.GetTooltipBSON(String title, IEnumerable`1 sections)

--------------------------------------------------------------------------------------------------
was just trying to see if i could scroll down and see more of the word

**Comment by Conchipedia** [comment]
i can scroll in and out with mousewheel, but soon as i click on map to move it, same error, this time logging in seems to sort of work, just a bit laggy (not sure if thats server side)

**Comment by MarjieAVolk** [comment]
Since this is a tooltip exception, does the error happen based on what you are hovering over with your cursor?

Tooltip errors should be caught and shown in the tooltip, rather than disconnecting you, so I can fix that.
