### ISSUE TITLE
[9.7.1] Server Crash on Server Initialization    

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#23561]
[Error] [Eco] Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Housing.HousingComponent.Initialize()
   at Eco.Gameplay.Objects.WorldObject.<>c.<InitializeComponents>b__249_0(WorldObjectComponent x)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.InitializeComponents()
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass21_0.<Initialize>b__1(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (Object reference not set to an instance of an object.)

Removed all Mods and changed Recipes but Server still crashes

**Comment by Sekor2600** [comment]
https://drive.google.com/file/d/1xSwggxzuWQTBvQGlMWPTpehlze7JTwyl/view

**Comment by D3nnis3n** [comment]
This save has a normally unavailable object in the save (via /give) that had housing and now has no longer, as such we consider this a mod error. There is a fix in 9.6.2 for the chair, but it might also appear for objects that were modded in to be functional and are now no longer - those are mod errors, though.
