### ISSUE TITLE
USER ISSUE: Ate food, crashed :'(

### ISSUE THREAD

**Issue by Altaric** [StrangeLoopGames/EcoIssues#23622]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.4 beta staging-2515

**Steps to Reproduce:**
Unlikely reproducible

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: ArgumentException
Message:The index is equal to or greater than the length of the array, or the number of elements in the set is greater than the available space from index to the end of the destination array.
Source:ConcurrentCollections

System.ArgumentException: The index is equal to or greater than the length of the array, or the number of elements in the set is greater than the available space from index to the end of the destination array.
   at ConcurrentCollections.ConcurrentHashSet`1.System.Collections.Generic.ICollection<T>.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Eco.Gameplay.Systems.NewTooltip.TooltipSubscriptions.ApplyDirtyTooltips()
   at Eco.Gameplay.Systems.NewTooltip.TooltipSubscriptions.MarkDirty(User user, IController controller, TooltipPartBase part)
   at Eco.Gameplay.Systems.NewTooltip.TooltipSubscriptions.MarkDirtyForInstance(IController controller, String tooltipName)
   at Eco.Gameplay.Systems.NewTooltip.TooltipSubscriptions.MarkTooltipPartDirty(String partName, Type type, IController instance, User user, Boolean includeDerivedTypes)
   at Eco.Gameplay.Systems.NewTooltip.Internal.TooltipSubscriptionHelper.<>c__DisplayClass1_0.<CreateTooltipInvalidationActionByAttribute>b__0(Object source, MemberChangedBeforeAfterEventArgs _)
   at Eco.Core.PropertyHandling.Internal.TypeSubscriptions.Invoke(Object sender, MemberChangedBeforeAfterEventArgs args)
   at Eco.Gameplay.Players.Stomach.set_Nutrients(Nutrients value)
   at Eco.Gameplay.Players.Stomach.RecalcAverageNutrients()
   at Eco.Gameplay.Players.Stomach.Eat(FoodItem food, String& message)
   at Eco.Gameplay.Items.FoodItem.<>c__DisplayClass33_0.<ConsumeInternal>b__1()
   at Eco.Gameplay.Items.ItemStackExtensions.TryModifyStack(ItemStack itemStack, User user, Int32 increment, Func`1 test, Action onSuccess)
   at Eco.Gameplay.Items.FoodItem.ConsumeInternal(ItemStack itemStack, User user, Boolean reaction, Boolean overrideSlot)
   at Eco.Gameplay.Items.FoodItem.OnUsed(Player player, ItemStack itemStack)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Should be fixed in 2525 staging, report if not.
