### ISSUE TITLE
USER ISSUE: Connect to my server 9.7.9

### ISSUE THREAD

**Issue by SentilONE** [StrangeLoopGames/EcoIssues#23738]
\
**User Id: (slg101815)**
**Version:** 0.9.7.9 beta release-451

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Systems.Messaging.Chat.ChatManager.<>c__DisplayClass51_0.<GetMessagesVisibleTo>b__0(ChatMessage m)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ReverseIterator`1.MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ReverseIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, BsonSerializationContext& context, Boolean doAllParams)
   at Eco.Gameplay.Systems.Messaging.Chat.ChatManager.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, INetObjectContainer monitored, ClientUpdate[] clientUpdates)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__76_2()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Need full client and server log and savegame.

**Comment by SentilONE** [comment]
Hello! I understand that my base with modifications. I understand that can break the game, but at least help me please find what is the reason. The server starts, but the client does not connect to the server. Where I can write you password for .7z? http://77.51.180.28:5432/share.cgi?ssid=034Tuqn

**Comment by SentilONE** [comment]
Hello! I understand that my base with modifications. I understand that can break the game, but at least help me please find what is the reason. The server starts, but the client does not connect to the server. Where I can write you password for .7z? http://77.51.180.28:5432/share.cgi?ssid=034Tuqn

**Comment by D3nnis3n** [comment]
Please upload the requested files to a public host, like Google Drive or similar and send it to support@strangeloopgames.com.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/25731
