### ISSUE TITLE
USER ISSUE: server crashed

### ISSUE THREAD

**Issue by Atlaz7z** [StrangeLoopGames/EcoIssues#23736]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.9 beta release-451

**Steps to Reproduce:**
I was just running. Then not possible to launch the server.

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Server encountered an exception:

<size=60,00%>Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'source')
Source:System.Linq

System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Components.MountComponent.get_OccupantIDs()
   at Eco.Core.Controller.ControllerManager.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Error during packaging property 'OccupantIDs' of 'Eco.Gameplay.Components.MountComponent'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Atlaz7z** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11132637/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11132639/Player-prev.log)
