### ISSUE TITLE
USER ISSUE: Error when harvesting plants

### ISSUE THREAD

**Issue by ExiationYy** [StrangeLoopGames/EcoIssues#23748]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.10 beta release-474

**Steps to Reproduce:**
1. Collect plants

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Tutorial.Internal.UserSubTaskCarvePath.IsComplete(Plant plant, Object killer)
   at Eco.Gameplay.Tutorial.UserSubTaskSubscribe`2.CheckComplete(TParam1 p1, TParam2 p2)
   at Eco.Simulation.PlantSim.DestroyPlant(Plant plant, DeathType deathType, Boolean addToPuller, Object killer)
   at Eco.Gameplay.Plants.PlantEntity.OnHarvested(Player player, Boolean picked)
   at Eco.Gameplay.Plants.PlantEntity.<>c__DisplayClass6_0.<TryHarvest>b__0()
   at Eco.Gameplay.GameActions.GameActionPack.<>c__DisplayClass18_0.<AddPostEffect>b__0()
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.GetResultWithLock(User user, GameActionPack pack)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Plants.InteractablePlantBlock.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Players.Player.<>c__DisplayClass112_0.<PlayerInteractResult>b__4(IInteractable inter)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess[T](IEnumerable`1 enumerable, Func`2 resultFunc)
   at Eco.Gameplay.Players.Player.PlayerInteractResult(InteractionInfo info)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
One or more errors occurred. (Object reference not set to an instance of an object.)</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11176065/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11176066/Player-prev.log)

**Comment by D3nnis3n** [comment]
Can you attach the server save and your username ingame?

**Comment by ExiationYy** [comment]
Can you help direct me to the file location of the server save file? It is a local game.

**Comment by D3nnis3n** [comment]
You will find it in /Steam/steamapps/common/Eco/Eco_Data/Server/Storage. Zip the respective .db and .zip file of the effected save, upload it on Google Drive or a similar provider that does not require registration and mention the exact name of your player inside the game save.

**Comment by ExiationYy** [comment]
Uploaded to Google Drive [Save File](https://drive.google.com/file/d/1dhl1vG_oGZRez0D5MkVuwBCgS4z0PSVj/view?usp=sharing). Player name, BaByGoMaZz[Yuan]

**Comment by ExiationYy** [comment]
Just noticed if I skipped all the tutorials, the errors wont occur.

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/12523 in 9.7.11.
