### ISSUE TITLE
Server failed to start Eco 9.7.10

### ISSUE THREAD

**Issue by primo4e** [StrangeLoopGames/EcoIssues#23750]
Failed to start the server. Exception was Exception: FileLoadException
Message:0x80131621
Source:System.Private.CoreLib
 
System.IO.FileLoadException: 0x80131621
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at Eco.ModKit.ModKitPlugin.LoadModDlls()
   at Eco.ModKit.ModKitPlugin.LoadModsDataAsync()
Outer Exceptions:
One or more errors occurred. (0x80131621)

**Comment by D3nnis3n** [comment]
Can you provide the full log?

**Comment by D3nnis3n** [comment]
That's what I assumed as well, hence the question for the log. Thanks for confirming :)
