### ISSUE TITLE
USER ISSUE: couldn't unclaim a deed with title as owner while backpack was full

### ISSUE THREAD

**Issue by iuriguilherme** [StrangeLoopGames/EcoIssues#23818]
\
**User Id: (slg203510)**
**Version:** 0.9.7.12 beta release-482

**Steps to Reproduce:**
unclaim deed assigned to a title while being elected the title, storage full

**Expected behavior:**
sent a notification that wasn't possible

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough space in destination inventory.
Source:Eco.Gameplay

System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough space in destination inventory.
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid, Boolean consolidating)
   at Eco.Gameplay.Items.InventoryChangeSet.GameActionPackPostEffect()
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.GetResultWithLock(User user, GameActionPack pack)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.Property.RentUtils.PackStuffIntoVoidStorage(User user, Deed deed)
   at Eco.Gameplay.GameActions.GameActionPack.<>c__DisplayClass18_0.<AddPostEffect>b__0()
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.GetResultWithLock(User user, GameActionPack pack)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.Property.PropertyManager.RemoveDeed(Deed deed, User performer, Boolean force, Boolean usePapers)
   at Eco.Gameplay.Property.Deed.DeleteDeed(Player player)
   at Eco.Gameplay.Property.Deed.Delete(Player player)
   at InvokeStub_Deed.Delete(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and not sure

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by iuriguilherme** [comment]
This crashed the server by the way

**Comment by iuriguilherme** [comment]
Additional context: That deed was transferred by law to a title when the original owner entered abandoned demographics. Also, the action of deleting the claim would lead to the original owner to lose residency, and another law would send all their belongings to their void storage.

**Comment by iuriguilherme** [comment]
Still happening in v0.9.7.13
