### ISSUE TITLE
USER ISSUE: Client crash when updating districts

### ISSUE THREAD

**Issue by iuriguilherme** [StrangeLoopGames/EcoIssues#23821]
\
**User Id: (slg203510)**
**Version:** 0.9.7.12 beta release-482

**Steps to Reproduce:**
Open a Zoning Desk and edit the districts. Save / submit. 

**Expected behavior:**
Popup appearing to add changes to election

**Actual behavior:**
This is the third time I get this behaviour and have to do it all again. Happened last week as well as the week before. Our server lags a lot, so after I submitted the changes and before the popup would appear, I could see that myself was editing that zone.

The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Invalid Query - Query never existed or was already processed
Source:Eco.Shared

System.InvalidOperationException: Invalid Query - Query never existed or was already processed
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__73_4()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and don't know

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by jwmc80** [comment]
When editing districts and making a _large number of changes_ the client crashes and changes to the districts are not saved.

**Comment by Daniel-Magulado** [comment]
Hi @iuriguilherme 

Thank you for submitting this bug report. However, we are unable to reproduce this on our end.
If you don't mind, we would like to request a copy of your server's save file so we can try to attempt to reproduce it using your world.

You can send the save file to me either via email or discord at [daniel@strangeloopgames.com](mailto:daniel@strangeloopgames.com) or Nielzx#6566.

**Comment by iuriguilherme** [comment]
@Daniel-Magulado que passa

A backup from day 8 is available at https://github.com/StrangeLoopGames/EcoIssues/issues/23808#issue-1689255187

If a newer one with more lag introduced is needed have to ask the OP of #23808

More logs:

- https://pastebin.com/P9uK0EEQ
- https://pastebin.com/cpQG9nAN

**Comment by iuriguilherme** [comment]
I almost always have a client crash updating too many map districts at once at Mountopia Zoning Desk. Maybe helps to crash the fact that I take a long time doing it too.

**Comment by D3nnis3n** [comment]
Providing a list of changes to do to districts that triggers the bug for you could help for us to reproduce the problem.

**Comment by iuriguilherme** [comment]
I was using mountopia zoning desk as mayor to update mountopia map. updated multiple districts, many spots around the map. all overlapping with other districts from another zoning desk and some with districts of that same zoning desk. was alt tabbing sometimes to check where the changes should be, didn't quit the district edit screen from time to time without starting an election to save changes.
