### ISSUE TITLE
USER ISSUE: Can't authenticate steam account with local servers

### ISSUE THREAD

**Issue by iuriguilherme** [StrangeLoopGames/EcoIssues#23912]
\
**User Id: (slg203510)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Attempt to connect to local server, either created with the in-game steam eco server, or through another one running on windows on the same machine

**Expected behavior:**
joined the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I tried with a brand new server unmodded and the error persists

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by iuriguilherme** [comment]
Log in the server console:

```
[08:43:26] Error while requesting AuthServer endpoint: game/verifytokenv3?token=REDACTED&serverId=REDACTED&tokenType=steam_encrypted_ticket: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Eco.Shared.Authentication.UserAuthentication.AuthRequestAsync[TModel](HttpMethod method, String url, HttpContent content)
System.TimeoutException: A task was canceled.

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[08:43:26] User failed to authenticate: iggy
```

**Comment by iuriguilherme** [comment]
Was using a Starlink connection with high ping and jitter

**Comment by iuriguilherme** [comment]
How do I raise `HttpClient.Timeout`?

**Comment by D3nnis3n** [comment]
We are aware of problems with starlink being unable to reach our authentication servers, it seems Starlink simply doesn't work with Eco currently as they do something on their side preventing connection. There is nothing you can do, unfortunately.
