### ISSUE TITLE
USER ISSUE: Save from 9.5 to 9.6

### ISSUE THREAD

**Issue by aaroneicker** [StrangeLoopGames/EcoIssues#24102]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.6 beta release-357

**Steps to Reproduce:**
Old savegame that i tried to load in the newest version. I only can use 9.5.4 and 9.6.6. in the steam beta selection. 9.5.4 did work, 9.6.6 did not

**Expected behavior:**
throw the following exception while loading

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.Avatar.get_Clothing()
   at Eco.Core.Controller.SyncPropertyInfo.GetValue(IMvcNetClient client, Object obj)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Error during packaging property 'Avatar' of 'Eco.Gameplay.Players.User'
Error during packaging property 'Clothing' of 'Eco.Gameplay.Players.Avatar'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Migration from that old versions will not be supported, hence closing.
