### ISSUE TITLE
USER ISSUE: Abandoned citizen law caused server loop crash

### ISSUE THREAD

**Issue by TheEvilGreebo** [StrangeLoopGames/EcoIssues#24121]
\
**User Id: (slg233066)**
**Version:** 0.10.0.0 beta release-524

**Steps to Reproduce:**
pass a law which revokes citizenship and property rights on demographic change, and which also looks for existing inactive players and does the same thing	

**Expected behavior:**
Revoked property and citizenship cleanly

**Actual behavior:**

[19:50:08.507] [5] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>c__DisplayClass42_0.<<Initialize>b__7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>c__DisplayClass42_0.<<Initialize>b__7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[19:50:08.712] [5] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>c__DisplayClass42_0.<<Initialize>b__7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>c__DisplayClass42_0.<<Initialize>b__7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TheEvilGreebo** [comment]
This problem causes a server loop crash.  I was able several times to get back in, see the timer tick over to execute the newly passed law and crash again.  Each time was tied to having an inactive player status update.  

The law in question is posted here http://205.209.104.60:3001/election/4494173

**Comment by D3nnis3n** [comment]
Internal 32322

**Comment by D3nnis3n** [comment]
Fixed
