### ISSUE TITLE
Contracts exception

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2416]
Caught exception invoking RPC JobFinished on Contract!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.EnumerableItemStackExtensions.<>c.<ToDict>b1_0(ItemStack x)
   at System.Linq.Lookup2.Create[TSource](IEnumerable1 source, Func2 keySelector, Func2 elementSelector, IEqualityComparer1 comparer)
   at System.Linq.GroupedEnumerable3.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable1 source, Func2 keySelector, Func2 elementSelector, IEqualityComparer1 comparer)
   at Eco.Gameplay.Items.EnumerableItemStackExtensions.ToDict(IEnumerable1 stackList)
   at Eco.Gameplay.Items.EnumerableItemStackExtensions.Contains(IEnumerable1 stackList, IEnumerable`1 testList)
   at Eco.Gameplay.Economy.Contracts.ContractClauseItemsInContainer.<Test>b17_0(StorageComponent x)
   at System.Linq.Enumerable.All[TSource](IEnumerable1 source, Func2 predicate)
   at Eco.Gameplay.Economy.Contracts.ContractClauseItemsInContainer.Test(User contractor, User client)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
   at Eco.Core.Utils.ResultExtensions.Merge(IEnumerable1 list)
   at Eco.Gameplay.Economy.Contracts.Contract.JobFinished(Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by Koden02** [comment]
I'm getting this same issue, it happens when there is a contract that involves placing a certain number of item within a stockpile.  I haven't tested it on a chest yet but I know this happens on stockpiles.  Version 0.6.0.0 with server hotfix current to today.

Bug is reproducible easily.
Have a job with a 'Put Items In Container' clause, and have the container be a stockpile.
We also had a permissions clause for the stockpile to allow the player to be able to put the items within the stockpile, haven't tested to see if this is a factor in the bug.

**Comment by johnkslg** [comment]
Fixed
