### ISSUE TITLE
Server crash when customizing StorageDirectory from Configs/Storage.eco

### ISSUE THREAD

**Issue by A-xis** [StrangeLoopGames/EcoIssues#24259]
Hello,

I'm using the linuxgsm install for Eco on a linux server. (game version is correct)

I have change the Configs/Storage.eco file :
`{
  "SaveName": "Saison3",
  "SaveFrequency": 60,
  "CleanupFilesOnExceptions": false,
  "StorageDirectory": "Storage_saison3",
  "NewGameTemplate": ""
}`

Changing this issue the following error :
`[14:58:55.713] [28] [Error] [Eco] System.ArgumentException: The directory name '/data/a-xis/eco/serverfiles/Storage/UserTextures/Reviewed' does not exist. (Parameter 'path')
   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Eco.Gameplay.Systems.UserTextures.UserTextureManagerServer.SetupFileWatcher()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.ArgumentException: The directory name '/data/a-xis/eco/serverfiles/Storage/UserTextures/Reviewed' does not exist. (Parameter 'path')
   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Eco.Gameplay.Systems.UserTextures.UserTextureManagerServer.SetupFileWatcher()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[log_231218025819.log](https://github.com/StrangeLoopGames/EcoIssues/files/13704907/log_231218025819.log)
`

**Comment by A-xis** [comment]
As a temporary solution I'm using a symboling link. Seems to be working fine. I guess something is now hardcoded, that was not previously

 `ln -s Storage_saison3 Storage`
