### ISSUE TITLE
USER ISSUE: Town Foundation issues

### ISSUE THREAD

**Issue by ZazzyMacdaddy** [StrangeLoopGames/EcoIssues#24271]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
using an existing world from v9 to v10
can't craft a foundation block from the settlement table
admin spawned in one and now every time it is placed, it crashes the server

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

--BEGIN DUMP--
Dump Time
12/18/2023 21:05:00

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementFoundationItem`1.CanPlaceObject(Player player, Vector3i worldPos, Quaternion rotation)
   at Eco.Gameplay.Placement.WorldObjectPlacementUtils.TryPlaceWorldObject(GameActionPack pack, Player player, WorldObjectItem item, ItemStack containingStack, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Placement.WorldObjectPlacementUtils.TryPlaceWorldObjectNow(Player player, WorldObjectItem item, ItemStack containingStack, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.Place(Player player, Vector3i pos, Quaternion rotation)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

--END DUMP--

**Comment by D3nnis3n** [comment]
Migrated worlds have settlements turned off and cannot use foundations, spawning them despite they are not craftable will cause the save to break, as you observed.

**Comment by demortes** [comment]
I think I ran into this, but all I did to start a new server but kept old settings. The foundation was was built fine, however when placed it crashed the server immediately. I've downloaded the dump as well as a backup, but will restart the server.

**Comment by demortes** [comment]
@D3nnis3n Is it worth a new bug? Or is this something that wont be worked?

**Comment by D3nnis3n** [comment]
If the issue appears when trying to place it on a server that has settlements off, it will not be adressed.
