### ISSUE TITLE
Server Crashes [10.0.2]

### ISSUE THREAD

**Issue by ChickenHacker1** [StrangeLoopGames/EcoIssues#24328]
Here's an error trace from a few server crashes we've been getting.  We've seen this message as well on 10.0.1.

I don't really have any details on what causes this, but hopefully this helps!

```
at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
at Eco.Core.Controller.ControllerPacker.PackageViewWithMembers(IController controller, BsonSerializationContext& context, IControllerMarshaler marshaler, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
at Eco.Core.Controller.ControllerPacker.PackageView(IController controller, BsonSerializationContext& context, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
at Eco.Core.Controller.ControllerPacker.SyncController(IMvcNetClient mvcClient, IController controller, BsonSerializationContext& context, ControllerBoundingLevel requiredSyncLevel)
at Eco.Core.Controller.ControllerPacker.PackageControllerRecursivelyAndCollectPendingViews(IController controller, BsonSerializationContext& context, PackageFlags flags)
at Eco.Core.Controller.ControllerPacker.PackControllerForBroadcasting(IEnumerable`1 clients, IController controller, String property, NetworkChannel& deliveryChannel)
at Eco.Core.Controller.ControllerPacker.PackageChange(IController controller, ValueTuple`2[] members, PoolableListWrapper`1 notifications, IMvcNetClient[] boundClients)
at Eco.Core.Controller.ControllerPacker.PackageChangesInternal(IController controller, String propertyName, PoolableListWrapper`1 notifications, IMvcNetClient[] clients)
at Eco.Core.Controller.Internal.ControllerUpdater.CollectUpdates(PoolableListWrapper`1 list, List`1& propertiesNames)
at Eco.Core.Controller.Internal.ClientUpdater.UpdateTask()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Mods.TechTree.PictureItem.UILinkContent()
at Eco.Gameplay.Systems.TextLinks.UILinkExtensions.UILink(ILinkable linkable)
at Eco.Gameplay.Items.Stackable.get_MarkedUpName()
at lambda_method21113(Closure, Object)
at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
Unhandled exception. System.Exception: Error during packaging property 'MarkedUpName' of 'Eco.Mods.TechTree.PictureItem'
---> System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Mods.TechTree.PictureItem.UILinkContent()
at Eco.Gameplay.Systems.TextLinks.UILinkExtensions.UILink(ILinkable linkable)
at Eco.Gameplay.Items.Stackable.get_MarkedUpName()
at lambda_method21113(Closure, Object)
at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
--- End of inner exception stack trace ---
at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
at Eco.Core.Controller.ControllerPacker.PackageViewWithMembers(IController controller, BsonSerializationContext& context, IControllerMarshaler marshaler, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
at Eco.Core.Controller.ControllerPacker.PackageView(IController controller, BsonSerializationContext& context, Boolean skipNonMustRequestProperties, Boolean forceMustRequestProperties)
at Eco.Core.Controller.ControllerPacker.SyncController(IMvcNetClient mvcClient, IController controller, BsonSerializationContext& context, ControllerBoundingLevel requiredSyncLevel)
at Eco.Core.Controller.ControllerPacker.PackageControllerRecursivelyAndCollectPendingViews(IController controller, BsonSerializationContext& context, PackageFlags flags)
at Eco.Core.Controller.ControllerPacker.PackControllerForBroadcasting(IEnumerable`1 clients, IController controller, String property, NetworkChannel& deliveryChannel)
at Eco.Core.Controller.ControllerPacker.PackageChange(IController controller, ValueTuple`2[] members, PoolableListWrapper`1 notifications, IMvcNetClient[] boundClients)
at Eco.Core.Controller.ControllerPacker.PackageChangesInternal(IController controller, String propertyName, PoolableListWrapper`1 notifications, IMvcNetClient[] clients)
at Eco.Core.Controller.Internal.ControllerUpdater.CollectUpdates(PoolableListWrapper`1 list, List`1& propertiesNames)
at Eco.Core.Controller.Internal.ClientUpdater.UpdateTask()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by Arend90** [comment]
happens here too and like 5 times a day or more... very frustrating 😤

**Comment by ChickenHacker1** [comment]
I believe this is related to the Picture bug that was fixed in the last patch.
