### ISSUE TITLE
Server crash related with settlement annexation (guess) [10.0.3]

### ISSUE THREAD

**Issue by Knaak53** [StrangeLoopGames/EcoIssues#24351]
Server stacktrace:

[21:37:31.882] [792] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>cDisplayClass42_0.<<Initialize>b7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>cDisplayClass42_0.<<Initialize>b7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[21:37:32.047] [792] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>cDisplayClass42_0.<<Initialize>b7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>cDisplayClass42_0.<<Initialize>b7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Player log in case is usefull:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13746119/Player.log)

**Comment by D3nnis3n** [comment]
Fixed in playtest.
