### ISSUE TITLE
Inventory change set not disposed

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#24362]
Our server has been experiencing some strange issues where things will get funky like stockpiles unable to be accessed, stores not working and work orders not going down that require manually restarting the server to fix it. These kinds of issues are usually followed by a error log of some kind that don't kill the server but do cripple it. Unfortunately for this one we are unsure of what specific in-game action might be causing it to trigger, but it has appeared twice in our log in the same day a few hours apart, both requiring a server restart to fix.

In the event we do get more information and/or are able to narrow down a cause I will come back to update the ticket.

`
[03:01:30.430] [2] [Error] [Eco] Inventory change set not disposed. Inventory: <style="ErrorLight">Unknown</style>, User:  Inventories:<style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <link="view:839:6497853"><icon name="StockpileItem" type="">Venice Mayor's Stockpile</icon></link>, <link="view:839:6499889"><icon name="StockpileItem" type="">Venice Mayor's Stockpile</icon></link>, <link="view:839:6499743"><icon name="StockpileItem" type="">Venice Mayor's Stockpile</icon></link>, <link="view:839:6498146"><icon name="StockpileItem" type="">Venice Mayor's Stockpile</icon></link>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>
`

**Comment by Reyalsorik** [comment]
This is happening to our server as well. We haven't identified the trigger, but this has occurred roughly 15-20 times over the last 4? days.

We have about 846 players that have joined the server on day 12. It can happen almost immediately after a server restart or be hours between.

The most noticeable trigger from my player base is when tables stop working. Each time, this error or similar is present.
When we restart the server after this error, the worldobjectmanager never stops (waited up to about 10 minutes as an experiment). The server must be forcefully killed once it hangs. Now and then, other managers will freeze, but it's 9/10 the worldobjectmanager.

This issue is critical to my player base and VERY disruptive for server management. 
More information can be provided as needed; happy to help.

**Comment by gzatravkin** [comment]
Hi! We are going to need some help to get more information, its very difficult to reproduce. 
Could you please try to run https://drive.google.com/file/d/1ALWgwDU-Dk-3N8nclFnKNgDqq4FiJut2/view?usp=sharing that build until it will get same error? It should write the callstack of inventory change set creation which should help with the investigation.

**Comment by Dave247** [comment]
> Hi! We are going to need some help to get more information, its very difficult to reproduce. Could you please try to run https://drive.google.com/file/d/1ALWgwDU-Dk-3N8nclFnKNgDqq4FiJut2/view?usp=sharing that build until it will get same error? It should write the callstack of inventory change set creation which should help with the investigation.

Hey thanks for the reply, but can you compile/share one for Linux too? As we recently switched out host to that.

**Comment by gzatravkin** [comment]
> > Hi! We are going to need some help to get more information, its very difficult to reproduce. Could you please try to run https://drive.google.com/file/d/1ALWgwDU-Dk-3N8nclFnKNgDqq4FiJut2/view?usp=sharing that build until it will get same error? It should write the callstack of inventory change set creation which should help with the investigation.
> 
> Hey thanks for the reply, but can you compile/share one for Linux too? As we recently switched out host to that.

Sure, https://drive.google.com/file/d/1JKDsFG2BTj4hCnOiKUWK4zKKkKAyP9-3/view?usp=sharing

**Comment by Reyalsorik** [comment]
I've enabled this on my windows server as well. I will post any updates I get from my end.

**Comment by Dave247** [comment]
> > > Hi! We are going to need some help to get more information, its very difficult to reproduce. Could you please try to run https://drive.google.com/file/d/1ALWgwDU-Dk-3N8nclFnKNgDqq4FiJut2/view?usp=sharing that build until it will get same error? It should write the callstack of inventory change set creation which should help with the investigation.
> > 
> > 
> > Hey thanks for the reply, but can you compile/share one for Linux too? As we recently switched out host to that.
> 
> Sure, https://drive.google.com/file/d/1JKDsFG2BTj4hCnOiKUWK4zKKkKAyP9-3/view?usp=sharing

Thanks.

I only took the executable as I assume that is all that was needed. Will keep an eye out following the next restart (for it to apply) when it happens again.

The one thing I have noticed is the consistency of around the time of today the issue happens. We do a daily scheduled restart at 6am, and the inventory issue always seems to happen later in the morning and early afternoon. Never in the evening though.

**Comment by Dave247** [comment]
Alright here's the new log entry, it feels like it's been getting worse and happening 2-3 times a day now. There's not much we can really do aside from schedule restarts every few hours. 
```
[23:55:36.166] [2] [Error] [Eco] Inventory change set not disposed. Stacktrace of creation:    at System.Environment.get_StackTrace()
   at Eco.Gameplay.Items.InventoryChangeSet..ctor(Inventory inventory, User user)
   at Eco.Gameplay.GameActions.GameActionPackExtension.<>c__DisplayClass0_0.<GetOrCreateInventoryChangeSet>b__0()
   at Eco.Gameplay.GameActions.GameActionPack.GetOrCreateChangeSet[T](Func`1 newChangeSetFunc)
   at Eco.Gameplay.Components.Store.StoreComponent.BuildInventoryActions(GameActionPack pack, PurchaseData data)
   at Eco.Gameplay.Components.Store.StoreComponent.PerformTradeWithPurchaseData(User purchaser, PurchaseData tradeData, BankAccount purchaserAccount)
   at Eco.Gameplay.Components.Store.StoreComponent.PerformTrade(Player tradeIniator, BSONObject tradeData, BankAccount purchaserAccount)
   at InvokeStub_StoreComponent.PerformTrade(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Shared.Networking.RPCManager.Invoke(INetClient client, RPCInvocation invocation)
   at Eco.Core.Controller.ControllerManager.HandleViewRPC(INetClient client, Int32 universalID, String methodIdOrName, BSONObject bson)
   at InvokeStub_Client.ViewRPC(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Shared.Networking.RPCManager.Invoke(INetClient client, RPCInvocation invocation)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodName)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONValue bsonValue)
   at Eco.Plugins.Networking.Client.<.ctor>b__78_4()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state). Inventory: <style="ErrorLight">Unknown</style>, User:  Inventories:<style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <link="view:4443:2156313"><icon name="IceboxItem" type="">Hood's Icebox</icon></link>, <link="view:4024:8810034"><icon name="LargeLumberStockpileItem" type="">Hood's Large Lumber Stockpile South</icon></link>, <link="view:4024:8816417"><icon name="LargeLumberStockpileItem" type="">Hood's Large Lumber Stockpile North</icon></link>, <link="view:2947:619345"><icon name="StorageChestItem" type="">papers</icon></link>, <link="view:2947:7522965"><icon name="StorageChestItem" type="">Shop</icon></link>, <link="view:2947:7523680"><icon name="StorageChestItem" type="">Shop</icon></link>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>, <style="ErrorLight">Unknown</style>
```

**Comment by aritchie05** [comment]
Based on that log entry it seems performing a trade is the trigger. I'm seeing the same issue on my server about twice a day, I will run it with the more verbose logs and see if I can identify anything.

**Comment by Dave247** [comment]
If it's at all useful. the settlements don't have any laws that affect or trigger on a trade action. At most there is the Treasury that is applying a sales tax to stores which would appears to be working correctly/as intended.

**Comment by aritchie05** [comment]
Kind of amusing, my server just hit this bug again. I had moved a bunch of materials to a larger stockpile after the error existed. After restarting the server, the materials existed in the world in both stockpiles (but not in the inventory ui). I picked up the small stockpiles that appeared full and the materials still exist in the world, I can pick them up manually. So essentially duped all those materials

**Comment by gzatravkin** [comment]
> Alright here's the new log entry, it feels like it's been getting worse and happening 2-3 times a day now. There's not much we can really do aside from schedule restarts every few hours.


Thanks. That particular problem can happen when you buy something at the store and in that particular moment some data is changed: you suddenly have less money than needed for the transfer by example. 

I fixed it here https://github.com/StrangeLoopGames/Eco/pull/13587 , there are could be some other cases of similar problems so I added a property "VerboseLogsOfInventoryChangeSets" to performance plugin.

**Comment by ScottEco** [comment]
Having the same problem on the server I play (Sprout ECO). If this issue is linked to trade, we have a trade tracked that logs on our discord server.

**Comment by ncottrill** [comment]
> Kind of amusing, my server just hit this bug again. I had moved a bunch of stockpiles of wood to a Large Lumber Stockpile after the error existed. After restarting the server, the materials existed in the world in both the regular stockpiles and the LLS (but not in the inventory ui for the regular stockpiles). I picked up the regular stockpiles that appeared full with a hammer and the logs still exist in the world, I can pick them up manually. So essentially duped 5 stockpiles of wood.

I noticed that when simply "sorting" a stockpile, there are ghost images of items that were moved to a different location. So, before sort 64 cedar logs are in the last stockpile position. Then, I sort the stockpile and I see 64 cedar logs STILL IN the last stockpile position, but there are now 64 cedar logs in, say, the 4th or 5th stack in the stockpile.

**Comment by D3nnis3n** [comment]
Fixed.

**Comment by Dave247** [comment]
> Fixed.

I totally missed that this was part of 10.0.4, as for whatever reason the issue stopped happening a day before it. Still glad to know it won't be coming back.
