### ISSUE TITLE
Server Crash [10.0.3]

### ISSUE THREAD

**Issue by ChickenHacker1** [StrangeLoopGames/EcoIssues#24364]
Just a random crash. Seems like from the fishing boat. We haven't tried to replicate this.

[08:28:48] System.AggregateException: One or more errors occurred. (No network object provided to call RPC 'SoundActionRPC' on. (Parameter 'obj'))
System.ArgumentException: No network object provided to call RPC 'SoundActionRPC' on. (Parameter 'obj')
at Eco.Shared.Networking.RPCEvent..ctor(String methodName, INetObject obj, INetClient target, Object[] args)
at Eco.Gameplay.Items.RepairableItem.UseDurability(Single multiplier, Player player)
at Eco.Mods.Organisms.SpeciesCatchers.BoatCatcher.ApplyCatch(Species species, Int32 amount) in /home/amp/.ampdata/instances/EcoPublic02/eco/739590/Mods/__core__/Organisms/Animal/AnimalCatchers/BoatCatcher.cs:line 61
at Eco.Gameplay.Animals.Catchers.Internal.LayeredCatchEntry.Tick()
at Eco.Gameplay.Animals.Catchers.SpeciesLayeredCatchPlugin.TickAll()
at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass4_0.<Create>b__0(CancellationToken token)
at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)

**Comment by D3nnis3n** [comment]
Should be fixed already.
