### ISSUE TITLE
USER ISSUE: Having Twitch integration enabled makes game unplayable currently

### ISSUE THREAD

**Issue by FireByTrial** [StrangeLoopGames/EcoIssues#24495]
\
**User Id: (slg167222)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
- enable twitch integration
- login/start game

**Expected behavior:**
things work normally

**Actual behavior:**
errors in server, uninteractable on client for several minutes while server gets timeouts

```
[03:55:24] Failed to start connection. Error starting transport 'WebSockets'.
[03:56:25] The handshake timed out after 15 seconds.
[03:56:25] Error starting connection.
[03:56:25] Failed to establish Twitch connection for user FireByTrial.
[03:56:25] System.AggregateException: One or more errors occurred. (A task was canceled.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Eco.Integrations.Twitch.TwitchPlugin.SubscribeTwitchChannel(String twitchId, Player player)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Eco.Integrations.Twitch.TwitchPlugin.SubscribeTwitchChannel(String twitchId, Player player)
   at Eco.Integrations.Twitch.TwitchPlugin.OnTwitchEnableStateChange(User user, Boolean state)
   at Eco.Core.Utils.ThreadSafeAction`2.Invoke(T1 t1, T2 t2)
   at Eco.Gameplay.Players.Player.SetTwitchEnabled(Boolean state)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Shared.Networking.RPCManager.Invoke(INetClient client, RPCInvocation invocation)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodName)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONValue bsonValue)
   at Eco.Plugins.Networking.Client.<.ctor>b__78_4()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in playtest.
