### ISSUE TITLE
[Settlement][10.0.4] Crash when founding country (Annex)

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#24533]
I'm hesitant to post this as a bug report as I'm not fully confident in the stability of our server, in that I worry the issue may be impossible to reproduce and is the product of whatever weird state our server has found itself it.

Nethertheless, here it is. The server crashes when we are trying to found a country, having admin assigned a neighboring town. In case it makes a difference this is the third time a country has been created on the server, as the first two feel though and were dissolved.
I can provide the world save on request.

```[11:45:28.503] [32] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Aliases.AliasExtensions.Mail(IAlias alias, LocString text, NotificationCategory tag)
   at Eco.Gameplay.Property.Deed.Eco.Gameplay.Settlements.IAnnexable.Notify(LocString msg)
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementBuilders.AnnexationRecordBuilder.SendNotice(AnnexationRecord after, LocString s)
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementBuilders.AnnexationRecordBuilder.SendNoticesIfNeeded(Boolean prevCanAnnex, Single prevCultureProgress, AnnexationRecord record)
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementBuilders.AnnexationRecordBuilder.RecalcAnnexRecords(IEnumerable`1 dirtySettlementSet)
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementChangeDetector.Tick()
   at Eco.Gameplay.Settlements.SettlementManager.FastTick()
   at Eco.Gameplay.Civics.CivicsData.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   --- End of inner exception stack trace --- System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Aliases.AliasExtensions.Mail(IAlias alias, LocString text, NotificationCategory tag)
   at Eco.Gameplay.Property.Deed.Eco.Gameplay.Settlements.IAnnexable.Notify(LocString msg)
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementBuilders.AnnexationRecordBuilder.SendNotice(AnnexationRecord after, LocString s)
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementBuilders.AnnexationRecordBuilder.SendNoticesIfNeeded(Boolean prevCanAnnex, Single prevCultureProgress, AnnexationRecord record)
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementBuilders.AnnexationRecordBuilder.RecalcAnnexRecords(IEnumerable`1 dirtySettlementSet)
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementChangeDetector.Tick()
   at Eco.Gameplay.Settlements.SettlementManager.FastTick()
   at Eco.Gameplay.Civics.CivicsData.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)```

**Comment by Dave247** [comment]
Due to our cycle still being ongoing and not wanting to share it publicly, I have sent an email to the support address which contains a link to the world save and instructions as to how it was created.

**Comment by D3nnis3n** [comment]
Confirmed.

**Comment by Dave247** [comment]
Ah one other thing i forgot to mention that is probably useful, the provided world was originally generated in 10.0.0 and has been migrated each time to the current patch (at the time of posting).

**Comment by silsha** [comment]
We have the same problem. While I cannot pinpoint the exact time or reason for this, we are currently unable to start our server.

Unfortunately, all available backups from the last week have the same problem.

I'll send you the information requested above via support mail.

**Comment by Dave247** [comment]
> We have the same problem. While I cannot pinpoint the exact time or reason for this, we are currently unable to start our server.
> 
> Unfortunately, all available backups from the last week have the same problem.
> 
> I'll send you the information requested above via support mail.

Thankfully ours isn't that bad an is still playable, we just can't create the country. It makes for something of a joke where the run just meant to have a country due to the multiple failed attempts at creating one (bugs or no).

**Comment by silsha** [comment]
We have "solved" this problem for now by using the current 10.0.5 playtest version. This allows the server to start again.

**Comment by D3nnis3n** [comment]
Fixed in playtest.
