### ISSUE TITLE
[10.0.4][Server] Revoke Citizenship Laws sending server into crash loop.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24592]
Server crashes and goes into bootloop when trying to execute a law that Revokes Citizenship.

```
[13:31:14.232] [211] [Error] [Eco] System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>c__DisplayClass42_0.<<Initialize>b__7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>c__DisplayClass42_0.<<Initialize>b__7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
 Full server log: 
[log_240111094233.log](https://github.com/StrangeLoopGames/EcoIssues/files/13904593/log_240111094233.log)

**Comment by D3nnis3n** [comment]
Fixed in playtest, try with this custom build:
https://drive.google.com/file/d/1XvTV8VEZVcdL6ispK5dEbBQlwkAl5DDB/view
