### ISSUE TITLE
Server issue: Crash due to Constitution after World Ends

### ISSUE THREAD

**Issue by Thibault-Brocheton** [StrangeLoopGames/EcoIssues#24616]
Server 10.0.4

Several meteor hit the world at the end of our cycle.
I just discovered, that after this event, the server was not able to start anymore.

Stacktrace:

```[13:00:10.247] [21] [Error] [Eco] Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.ConstitutionComponent.InitializePersistentData()
   at Eco.Gameplay.Objects.TrackPlacementComponent.Initialize()
   at Eco.Gameplay.Components.ConstitutionComponent.Initialize()
   at Eco.Gameplay.Objects.WorldObject.InitializeComponents()
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass22_0.<Initialize>b__1(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)))
One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.))
One or more errors occurred. (Object reference not set to an instance of an object.)
```

We spawned multiple meteor to make a nice end of the world, some countries / cities hall have been wiped. probably the cause of the issue ?

Link to the map: https://drive.google.com/drive/folders/1F-Yq9egPoQPruoR_X23d9SrvXPzkTYci?usp=sharing

Our server is over, so no need to rush, but i'm sharing this for the knowledge

**Comment by D3nnis3n** [comment]
Fixed in 10.1.2.
