### ISSUE TITLE
USER ISSUE: Citizen timer to revoke citizenship crashes server

### ISSUE THREAD

**Issue by dterbeest** [StrangeLoopGames/EcoIssues#24615]
Made a law that Revokes citizenship for all abandoned people, to make sure the people who where already abandoned i wanted to run it once on a Citizen Timer trigger with demographic Abandoned, this consitently crashed the server with the following message:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>c__DisplayClass42_0.<<Initialize>b__7>d.MoveNext()
--- End of stack trace from previous location ---
   at Eco.Gameplay.UI.UserRoster.Leave(User userLeaving, Boolean notify)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementCitizenship.<>c__DisplayClass42_0.<<Initialize>b__7>d.MoveNext()
  ... omitted for brevity
  
  next it goes into a loop of not being able to dump the log
  `Caught exception when trying to dump a prior exception: The process cannot access the file '[REDACTED]\Dump\NullReferenceException 01160127.ecodmp' because it is being used by another process.`

Steps to reproduce:

1. Make Federation
2. Make law with trigger Citizen Timer Trigger and Revoke Citizenship action

full logs available on request, world save has gone lost in my hurry to roll back and get back online

**Comment by D3nnis3n** [comment]
Already fixed in playtest, you can use this custom build (just replace your EcoServer.exe) to fix it: https://drive.google.com/file/u/1/d/1XvTV8VEZVcdL6ispK5dEbBQlwkAl5DDB/view?usp=sharing
