### ISSUE TITLE
SERVER ISSUE: Startup crash after Town Foundation deed creator turns to abandoned

### ISSUE THREAD

**Issue by aritchie05** [StrangeLoopGames/EcoIssues#24629]
Game version: Eco 10.0.4 beta release-557

I have the following law in place on my server for the whole server (Federation):
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/15224019/0172305d-2d08-4c05-b7ba-599b4c362439)

There is a town deed that was founded by a player (Devilsreborn):
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/15224019/896f3a41-f290-46f9-a33c-b69ca67fa29a)

Note that the creator of the deed is Devilsreborn, however the owner of the deed is the "Riverside Town Council" title. Devilsreborn was the original sole holder of the title, but now the title is held by another player (eripfeng).
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/15224019/293329e3-189c-46d6-aa7f-ed5a8d8d57ee)

When Devilsreborn turned to Abandoned demographic (7d of inactivity), the server crashes on startup with the following error:

`﻿System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Gameplay.Objects.WorldObjectUtil.Unplace (WorldObject obj, LocString desc, Inventory inventory)
at Eco.Gameplay.Settlements.SettlementUtils.UnplaceAndReturnProperty (WorldObject host0bj)
at Eco.Gameplay.Civics.LegalActions.ChangePropertyOwner_LegalAction.<>c.<Do>b__13_4(Deed deed)
at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
at Eco.Gameplay.Civics.LegalActions.ChangePropertyOwner_LegalAction.Do (LocString desc, IContextObject context, Settlement jurisdictionSettlement)
at Eco.Gameplay.Civics.LegalActions.ChangePropertyOwner_LegalAction.Perform(Law law, GameAction action, AccountChangeSet acc)
at Eco.Gameplay.Civics.LegalAction.PerformAndProcessResult(Law law, GameAction action, AccountChangeSet acc)
at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, AccountChangeSet acc, LawSection section, Int32 i ndex, LocStringBuilder sbDebug)
at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApply Effects (Law law, GameAction action, AccountChangeSet acc)
at Eco.Gameplay.Civics.Laws.LawSection.InternalPerform(Law law, GameAction action, AccountChangeSet acc)
at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action, AccountChangeSet acc)
at Eco.Gameplay.Civics.Laws.Law.TryPerform(GameAction action, AccountChangeSet acc)
at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action, AccountChangeSet acc)
at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions (PackFlags flags, List`1 actions, IEnumerable`1 preTests, IE numerable`1 postEffects, AccountChangeSet acc)
at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions (User userToNotify, GameActionPack actionPack)
﻿at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, User userToNotify)
at Eco.Gameplay.Civics.Demographics.DemographicManager.UpdateDemographicList(IEnumerable`1 demographicsList, Boolean suppre ssChangeNotice)
at Eco.Gameplay.Civics.Demographics.DemographicManager.DoDemographicUpdate (Demographic limitToDemographic, Boolean suppressChangeNotice)
at Eco.Gameplay.Civics.Demographics.DemographicManager.SlowTick()
at Eco.Gameplay.Civics.CivicsData.TickAll()
at Eco.Gameplay.Civics.CivicsPlugin.TickAll()
at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork (CancellationToken token)`

**Comment by D3nnis3n** [comment]
Fixed in playtest.
