### ISSUE TITLE
USER ISSUE: Unable to join recently updated server.

### ISSUE THREAD

**Issue by dwuerfel** [StrangeLoopGames/EcoIssues#24634]
\
**User Id: (slg241027)**
**Version:** 0.10.1.0 beta release-576

**Steps to Reproduce:**
Press Continue on recently updated server.

**Expected behavior:**
Load into game

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.UserHelpers.UserAccounts.<UpdateClaimableSettlements>g__Iter|21_0()+MoveNext()
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other, MutationInput origin)
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 items, Boolean avoidWithComparer)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T,TArg](T& original, TArg arg, Func`3 apply)
   at Eco.Core.Utils.ControllerHashSet`1.<>n__3(IEnumerable`1 e)
   at Eco.Core.Utils.ControllerHashSet`1.<>c__DisplayClass21_0.<SetInternal>b__0()
   at Eco.Core.Utils.Trac</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by dwuerfel** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13979852/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13979853/Player-prev.log)

**Comment by D3nnis3n** [comment]
We're currently investigating this. If you can, please provide the save game of the server and the exact names of affected users.

**Comment by dwuerfel** [comment]
Exceptions thrown on server:
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Shared.Networking.RPCInvocation.Invoke()
   at Eco.Shared.Networking.RPCManager.Invoke(INetClient client, RPCInvocation invocation, Boolean notifyOnPermissionFail)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodName)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONValue bsonValue)
   at Eco.Plugins.Networking.Client.<.ctor>b__78_4()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.UserHelpers.UserAccounts.<UpdateClaimableSettlements>g__Iter|21_0()+MoveNext()
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other, MutationInput origin)
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 items, Boolean avoidWithComparer)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T,TArg](T& original, TArg arg, Func`3 apply)
   at Eco.Core.Utils.ControllerHashSet`1.<>n__3(IEnumerable`1 e)
   at Eco.Core.Utils.ControllerHashSet`1.<>c__DisplayClass21_0.<SetInternal>b__0()
   at Eco.Core.Utils.TrackedCollectionExtensions.ApplyChange(ITrackedControllerEnumerable list, Action change)
   at Eco.Core.Utils.ControllerHashSet`1.SetInternal(INetObject caller, IEnumerable`1 entries)
   at Eco.Core.Utils.ControllerHashSet`1.Set(IEnumerable`1 e)
   at Eco.Gameplay.Players.UserHelpers.UserAccounts.UpdateClaimableSettlements()
   at Eco.Gameplay.Players.UserHelpers.UserAccounts.<Initialize>b__23_0(User _)
   at Eco.Gameplay.Players.User.LoginCompleted()
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)
   at InvokeStub_Client.SpawnPlayer(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)`

**Comment by dwuerfel** [comment]
User name "Det" is the only confirmed user affected currently but I have not heard from other users yet.

Link to Storage folder: https://drive.google.com/drive/folders/1Xt2dmOG_UQrTgPX75OFHGZDMuYW-kHKQ?usp=sharing

**Comment by GPRatcliffe** [comment]
I believe this may be the same server but I too am having the same error, username GaryRatcliffe.

[player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13980751/player.log)

**Comment by gzatravkin** [comment]
Can you attach related mods if any?

**Comment by dwuerfel** [comment]
The server and my client do not have any mods.

**Comment by randomO9** [comment]
Was a patch pushed for this? We are also seeing this issue on my server.  Or is there a manual fix that server admins must do?

**Comment by randomO9** [comment]
If not is there anything I can provide to help.with debugging? I can provide my servers save files and the names of our effect users (we have 2 confirmed so far). We also have no mods installed

**Comment by ragimoc** [comment]
Same error here; username DurT
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13982449/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13982450/Player-prev.log)

**Comment by xreplica** [comment]
Same error here as well, username Vikenti and can confirm users Kieran Ragar and Chrisso have experienced the same issue.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13982663/Player.log)

**Comment by D3nnis3n** [comment]
We have a prepared a hotfix that will address this issue and release in the next few hours after basic QA testing.

**Comment by D3nnis3n** [comment]
Released, should have addressed this.
