### ISSUE TITLE
USER ISSUE: File Eco.Twitch.Shared

### ISSUE THREAD

**Issue by villafanezgd** [StrangeLoopGames/EcoIssues#24732]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
Continue my saved match

**Expected behavior:**
Start the server

**Actual behavior:**
Showme, in the log file the next message: System.IO.FileNotFoundException: 
File name: 'Eco.Twitch.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. Si.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Log file:
[09:56:52.333] [1] [ Info] [Eco] ]Anonymous app login.[
 
[09:56:52.630] [1] [ Info] [Eco] Servidor 0.10.1.3 beta release-592 de Eco
 
[09:56:52.630] [4] [ Info] [Eco] Empezando PerformancePlugin                       ...  
[09:56:52.659] [4] [ Info] [Eco] Empezando PerformancePlugin                       ... Terminado en 0,024 segundos
 
[09:56:52.659] [4] [ Info] [Eco] Empezando ProfilingPlugin                         ...  
[09:56:52.659] [4] [ Info] [Eco] Empezando ProfilingPlugin                         ... Terminado en 0,000 segundos
 
[09:56:52.659] [4] [ Info] [Eco] Empezando MaintenancePlugin                       ...  
[09:56:52.659] [4] [ Info] [Eco] Empezando MaintenancePlugin                       ... Terminado en 0,009 segundos
 
[09:56:52.659] [4] [ Info] [Eco] Iniciando servidor                                ...  
[09:56:52.677] [4] [ Info] [Eco] Iniciando servidor                                ... Terminado en 0,009 segundos
 
[09:56:52.722] [1] [Error] [Eco] Failed to start the server. Exception was Exception: FileNotFoundException
Message:
Source:EcoServer

System.IO.FileNotFoundException: 
File name: 'Eco.Twitch.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo)
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
 
[09:56:52.722] [1] [ Info] [Eco] Apagado finalizado
 
[09:56:52.722] [1] [Error] [Eco] Errors report:
Failed to start the server. Exception was Exception: FileNotFoundException
Message:
Source:EcoServer

System.IO.FileNotFoundException: 
File name: 'Eco.Twitch.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo)
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
: 1

**Comment by D3nnis3n** [comment]
That looks like a corrupted installation, please reinstall the server and reach out to support@strangeloopgames.com in case that doesn't work.
