### ISSUE TITLE
Server Issue: Server crash loop due to CraftingFees [10.1.3]

### ISSUE THREAD

**Issue by Thibault-Brocheton** [StrangeLoopGames/EcoIssues#24737]
Server version 10.1.3

Server is not able to start anymore, due to:

```
[05:11:15.701] [21] [Error] [Eco] Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementUtils.GetSettlementsAtPos(PlotPos plotPos)+MoveNext()
   at System.Linq.Enumerable.Sum[TSource,TResult,TAccumulator](IEnumerable`1 source, Func`2 selector)
   at Eco.Gameplay.Economy.Transfer.Internal.TaxIntenalUtils.CalculateTax(TransferData data)
   at Eco.Gameplay.Economy.Transfer.Transfers.Transfer(GameActionPack pack, TransferData data)
   at Eco.Gameplay.Economy.Transfer.Transfers.TransferNow(User userToNotify, TransferData data)
   at Eco.Gameplay.Components.CraftingFees.RefundCraftingFee()
   at Eco.Gameplay.Components.CraftingFees.CreditDataChanged()
   at Eco.Gameplay.Components.CraftingFees.Initialize(WorldObject worldObject, WorkOrder workOrder)
   at Eco.Gameplay.Items.WorkOrder.Initialize()
   at Eco.Core.Systems.Registrar`1.Initialize()
   at Eco.Core.Systems.Registrars.<>c.<InitializeAllRegistrars>b__23_0(IRegistrar reg)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (Object reference not set to an instance of an object.)
```

You can access the map here: https://drive.google.com/drive/u/0/folders/1SebzB69rqCgN82hQH4IBJLnrojdzPyAg
(I made sure everyone can access the files)

Anything we can do to avoid this issue ? Or only a fix in your side is necessary ?

Kind Regards,

**Comment by D3nnis3n** [comment]
Fixed in 10.1.4.
