### ISSUE TITLE
USER ISSUE: Fehler bei Portfreigabe

### ISSUE THREAD

**Issue by Domini02** [StrangeLoopGames/EcoIssues#24790]
\
**User Id: (slg147459)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Habe alle nötitgen ports frei gegeben aber trotzdem keine verbindung zum server

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein keine Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Domini02** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14389618/Player.log)

**Comment by Domini02** [comment]
[07:54:54] Error while requesting AuthServer endpoint: game/verifytokenv3?token=---------serverId=------&tokenType=steam_encrypted_ticket: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at Eco.Shared.Authentication.UserAuthentication.AuthRequestAsync[TModel](HttpMethod method, String url, HttpContent content)
System.TimeoutException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

**Comment by D3nnis3n** [comment]
Für den Kontakt zu unseren Backendservern ist keine Portfreigabe nötig, in diesem Fall kann dein Netzwerk keine ausgehende Verbindung aufbauen, womit der Kontaktversuch nach zehn Sekunden abbricht. Das ist allerdings kein Fehler, sondern ein Problem in deiner Netzwerkkonfiguration.
