### ISSUE TITLE
Finished contract threw exception

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2479]
"This error popped up when I clicked on the job finished icon for a contract ----It kicked me out to the server list." --ImperatorDecens

```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC JobFinished on Contract!

Object reference not set to an instance of an object.

Stack:
at Eco.Gameplay.Items.EnumerableItemStackExtensions.<>c.b__1_0(ItemStack x)
at System.Linq.Lookup2.Create[TSource](IEnumerable1 source, Func2 keySelector, Func2 elementSelector, IEqualityComparer1 comparer) at System.Linq.GroupedEnumerable3.GetEnumerator()
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable1 source, Func2 keySelector, Func2 elementSelector, IEqualityComparer1 comparer)
at Eco.Gameplay.Items.EnumerableItemStackExtensions.ToDict(IEnumerable1 stackList) at Eco.Gameplay.Items.EnumerableItemStackExtensions.Contains(IEnumerable1 stackList, IEnumerable1 testList) at Eco.Gameplay.Economy.Contracts.ContractClauseItemsInContainer.<Test>b__17_0(StorageComponent x) at System.Linq.Enumerable.All[TSource](IEnumerable1 source, Func2 predicate) at Eco.Gameplay.Economy.Contracts.ContractClauseItemsInContainer.Test(User contractor, User client) at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
at Eco.Core.Utils.ResultExtensions.Merge(IEnumerable`1 list)
at Eco.Gameplay.Economy.Contracts.Contract.JobFinished(Player player)

Stack:
at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)
```

**Comment by MarjieAVolk** [comment]
Been trying to repro and I haven't been able to

**Comment by Fank** [comment]
Duplicate of #2416

**Comment by MarjieAVolk** [comment]
Oh you're right, thanks

**Comment by MarjieAVolk** [comment]
weird daisy chain for the bug reporter lol
