### ISSUE TITLE
USER ISSUE: removing dirty ramp bug

### ISSUE THREAD

**Issue by netopyra** [StrangeLoopGames/EcoIssues#24878]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
when I remove dirty ramp with spade, game crash.

**Expected behavior:**
Dirty ramp should be remove.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:EcoCompaniesMod

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Mods.Companies.CompanyManager.InterceptPlaceOrPickupObjectGameAction(PlaceOrPickUpObject placeOrPickUpObject, PostResult& lawPostResult)
   at Eco.Mods.Companies.CompanyLawManager.Perform(GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects, AccountChangeSet acc)
   at Eco.Gameplay.GameActions.GameActionManager.GetResultWithLock(GameActionPack pack)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User userToNotify, </size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, playing on White Tiger.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Not a game bug, mod error. WT Administration is aware.
