### ISSUE TITLE
USER ISSUE: Error which Place town settlment

### ISSUE THREAD

**Issue by Philyaa3** [StrangeLoopGames/EcoIssues#24894]
\
**User Id: (slg228020)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
1. place the block to ground2. it was invisible3. if I unclaim territory - getting crash the world.

**Expected behavior:**
town exploration

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.Unclaim(User user, PlotPos plotPos)
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.Unclaim(Player player, InteractionTriggerInfo triggerInfo, InteractionTarget target)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, I has

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Known issue, see here: https://github.com/StrangeLoopGames/EcoIssues/issues/24889
Internal ticket: ECO-33807
