### ISSUE TITLE
Server Crash - Corrupt backups - EndOfStreamException

### ISSUE THREAD

**Issue by ThatOneDolpgin** [StrangeLoopGames/EcoIssues#24899]
SERVER FILES - https://drive.google.com/file/d/1QhOp6JOguJ8tLu6cPXFBwmfa77oJweDY/view?usp=sharing

[13:08:14.354] [31] [Error] [Eco] Failed to start the server. Exception was Exception: EndOfStreamException
Message:Unable to read beyond the end of the stream.
Source:System.Private.CoreLib

System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadString()
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeReferenceableEnumerable(BinaryReader reader, Object decodeTarget, Int32 numElements)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.DecodeEnumerable(BinaryReader reader, Object decodeTarget)
   at Eco.Core.Serialization.Serializers.EnumerableSerializer.Decode(BinaryReader reader, Object instance)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeToMember(BinaryReader reader, Object instance, MemberInfo memberInfo)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeMember(MemberInfo member, Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.DecodeToInstance(Object& instance, BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ClassSerializer.DecodeInstance(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeObject(BinaryReader reader, Int32 objTypeID)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader)
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader)
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.CurrentSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.EcoSerializer.Deserialize(Stream stream)
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream)
   at Eco.Core.Serialization.DataStore.Load[T](ExclusiveAccess exclusiveAccess, String folder, Action`1 onLoad, Boolean migrate)
   at Eco.Core.Serialization.DataStore.ExclusiveAccess.Load[T](String folder, Action`1 onLoad, Boolean migrate)
   at Eco.Core.Serialization.DataStore.Load[T](String folder, Action`1 onLoad, Boolean migrate)
   at Eco.Core.Plugins.StorageManager.LoadOrCreate[TStorageType](String folder, Action`1 onCreate)
   at Eco.Gameplay.Systems.GameDataPlugin..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
Outer Exceptions:
Exception has been thrown by the target of an invocation.

**Comment by D3nnis3n** [comment]
This file wasn't saved correctly to disk, that can happen when the saving process is interrupted by any means - security software or settings, server being shutdown during saving, defect in hardware or slow disk operations. There is no way to figure out why this happened from the provided data and the backup cannot be fixed when it wasn't saved correctly.
