### ISSUE TITLE
Server Docker Image failing to start

### ISSUE THREAD

**Issue by lasercheesecake** [StrangeLoopGames/EcoIssues#24946]
I'm trying to run an Eco server using the Docker image. However, the container is refusing to start the server and I'm getting the following message in the logs:

`
[03:42:57] ]Anonymous app login.[
[03:42:57] Eco Server 0.10.2.4 beta release-674
[03:42:57] Starting PerformancePlugin                        ... 
[03:42:57] Starting PerformancePlugin                        ... Finished in 0.023 sec
[03:42:57] Starting ProfilingPlugin                          ... 
[03:42:57] Starting ProfilingPlugin                          ... Finished in 0.000 sec
[03:42:57] Starting MaintenancePlugin                        ... 
[03:42:57] Starting MaintenancePlugin                        ... Finished in 0.007 sec
[03:42:57] Server Initialization                             ... 
[03:42:57] Starting FeaturesPlugin                           ... 
[03:42:57] Starting FeaturesPlugin                           ... Finished in 0.005 sec
[03:42:57] Starting BalancePlugin                            ... 
[03:42:57] Starting BalancePlugin                            ... Finished in 0.004 sec
[03:42:57] Starting NetworkManager                           ... 
[03:42:57] Starting NetworkManager                           ... Finished in 0.022 sec
[03:42:57] Starting DifficultySettings                       ... 
[03:42:57] Starting DifficultySettings                       ... Finished in 0.011 sec
[03:42:57] Starting ModKitPlugin                             ... 
[03:42:58] Starting ModKitPlugin                             ... Finished in 1.034 sec
[03:42:58] Server Initialization                             ... Finished in 1.086 sec
[03:42:58] Shutdown finished
[03:42:58] Errors report:
Failed to start the server. Exception was Exception: WeavingException
Message:Can't resolve reference to assembly Eco.Core for Eco.Core.PropertyHandling.INotifyPropertyChangedInvoker, Eco.Core
Source:StrangeLoopGames.PropertyChanged.Fody
Fody.WeavingException: Can't resolve reference to assembly Eco.Core for Eco.Core.PropertyHandling.INotifyPropertyChangedInvoker, Eco.Core
   at CecilUtils.MakeTypeReference(String assemblyQualifiedName, ModuleDefinition module) in C:\slg\PropertyChanged\PropertyChanged.Fody\CecilUtils.cs:line 26
   at ModuleWeaver.get_PropertyChangedInvoker() in C:\slg\PropertyChanged\PropertyChanged.Fody\Config\AddPropertyChangedInvokerConfig.cs:line 38
   at ModuleWeaver.ProcessPropertyChangedInvoker() in C:\slg\PropertyChanged\PropertyChanged.Fody\PropertyChangedInvokerProcessing.cs:line 20
   at ModuleWeaver.Execute() in C:\slg\PropertyChanged\PropertyChanged.Fody\ModuleWeaver.cs:line 24
   at Eco.ModKit.Internal.Weaving.RuntimeWeaver.ExecuteWeavers(XElement xWeavers)
   at Eco.ModKit.Internal.Weaving.RuntimeWeaver.Weave(Stream assemblyStream, Stream symbolsStream, String configPath)
   at Eco.ModKit.RoslynCompiler.Weave(Stream assemblyStream, Stream symbolsStream)
   at Eco.ModKit.RoslynCompiler.Compile(AssemblyLoadContext assemblyContext)
   at Eco.ModKit.RoslynCompiler..ctor(AssemblyLoadContext assemblyContext, String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.RoslynCompiler..ctor(String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.ModKitPlugin..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
`

I'm running docker on an Debian 12 turnkey-core_18.0-1 LXC on Proxmox 8.8.2. Any help would be appreciated.

**Comment by D3nnis3n** [comment]
We do not offer support or take bug reports for the docker containers, they are provided as is.

You probably have the best chances for help with that on our Discord by asking other server admins in the #server-help channel.
https://discord.gg/eco.
