### ISSUE TITLE
USER ISSUE: Company Unclaim DC

### ISSUE THREAD

**Issue by Caldrena** [StrangeLoopGames/EcoIssues#25011]
\
**User Id: (36a3d481-05b4-453b-40c2-08dc9ba1882d)**
**Version:** 0.11.0.0 beta playtest-455

**Steps to Reproduce:**
Be in a company and unclaim property owned by the company. Property is the housing section (we are tryign to seperate so we can utilize our outdoors)

**Expected behavior:**
unclaim and remain logged in

**Actual behavior:**
Disconnected from the server after every unclaim.

The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Rooms.OutdoorRoomUtil.<>c.<Initialize>b__0_3(WorldObject x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Immutable.ImmutableHashSet`1.Except(IEnumerable`1 other, IEqualityComparer`1 equalityComparer, IEqualityComparer`1 hashBucketEqualityComparer, SortedInt32KeyNode`1 root)
   at System.Collections.Immutable.ImmutableHashSet`1.Except(IEnumerable`1 other)
   at Eco.Core.Utils.ThreadSafeHashSet`1.<>c.<RemoveAll>b__21_0(ImmutableHashSet`1 x, Func`2 match_)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutableReturn[T,TArg,</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Its on White Tiger 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Mod related issue, noted to developer directly.
