### ISSUE TITLE
USER ISSUE: Moved settlement for town

### ISSUE THREAD

**Issue by JeremyDX** [StrangeLoopGames/EcoIssues#25015]
\
**User Id: (slg232136)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.Settlement.<Initialize>b__178_0()
   at Eco.Gameplay.Items.WorldObjectItem.Move(Player player, Vector3i pos, Quaternion rotation, INetObject woNetObject)
Outer Exceptions:
One or more errors occurred. (Object reference not set to an instance of an object.)</size>

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
What were you doing when this happened?

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/25567
