### ISSUE TITLE
Multiples errors appear in server terminal

### ISSUE THREAD

**Issue by Maverick0581** [StrangeLoopGames/EcoIssues#25095]
Hey, 
Since **Eco 11.0.2** some errors are apparently randomly poping in my server's terminal. Here is some :

```
[Out: Infinity k/s]. Exception: System.Exception: Don't know elementType = 101
   at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.DecodeObject(MemoryStream stream, BSONObject obj)
   at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
   at Eco.Shared.Networking.NetMessage.DecodePacket(ReadOnlySpan`1 message)
   at Eco.Plugins.Networking.NetworkServer.HandleIncomingDataMessage(UdpDataMessage& message). The message length is: 70 and text representation isid
     ��
       methodViewRPargs
                       ���
1698args���
query
     �8
```
The one bellow is very common
```
[11:04:48] Sending 19890 minimap objects to thomas18:                       [Ping: 49 ms]   [CPU: 0.8 ms]   [In: Infinity k/s][Out: Infinity k/s]
```
And this one appear only when server is booting
```
[07:53:11] Component RateCultureComponent has to explicitly define [HasIcon] or [NoIcon], because it's parent has [DerivedMustDefineIcon].
```
I can't find how players manage to reproduce the error, it seems a bit random...
Hope you can help me, thanks !

_SLG ID : c42e9f54-3dfc-4bd1-7cfe-08dc8d1bff58_

**Comment by D3nnis3n** [comment]
These are debug logs and can be ignored, is there an actual problem that player have?

Can you note more details about that?

**Comment by Maverick0581** [comment]
> These are debug logs and can be ignored, is there an actual problem that players have?
> 
> Can you note more details about that?

They haven't report anything yet, I was just curious.

As I was about to unclaim all abandoned deeds (with **/property unclaimabandoned**), my server crashed within the following seconds. Here is the new error :

`[15:58:16.057] [154] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementInfluenceUtils.HasSatisfactoryCoverage(IEnumerable`1 influencePoints, LocString sourceName, LocString coverDesc, IAnnexable target, Single& percentCovered, IEnumerable`1 considerExtraPlots, IEnumerable`1 ignorePlots)
   at Eco.Gameplay.Settlements.SettlementInfluenceUtils.HasSatisfactoryCoverage(Settlement settlement, IAnnexable target, Single& percentCovered, IEnumerable`1 considerExtraPlots, IEnumerable`1 ignorePlots)
   at Eco.Gameplay.Settlements.Components.HomesteadFoundationComponent.<RecalcTowns>b__25_1(Settlement x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Eco.Gameplay.Settlements.Components.HomesteadFoundationComponent.RecalcTowns(Boolean notify)
   at Eco.Gameplay.Settlements.Components.HomesteadFoundationComponent.<Initialize>b__19_1()
   at Eco.Gameplay.InfluenceObjects.InfluenceChangeNotifier.MarkInfluenceChanged(IEnumerable`1 changedPlots)
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementChangeDetector.DoUpdateNow()
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementChangeDetector.Tick()
   at Eco.Gameplay.Settlements.SettlementManager.FastTick()
   at Eco.Gameplay.Civics.CivicsData.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   --- End of inner exception stack trace --- System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.SettlementInfluenceUtils.HasSatisfactoryCoverage(IEnumerable`1 influencePoints, LocString sourceName, LocString coverDesc, IAnnexable target, Single& percentCovered, IEnumerable`1 considerExtraPlots, IEnumerable`1 ignorePlots)
   at Eco.Gameplay.Settlements.SettlementInfluenceUtils.HasSatisfactoryCoverage(Settlement settlement, IAnnexable target, Single& percentCovered, IEnumerable`1 considerExtraPlots, IEnumerable`1 ignorePlots)
   at Eco.Gameplay.Settlements.Components.HomesteadFoundationComponent.<RecalcTowns>b__25_1(Settlement x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Eco.Gameplay.Settlements.Components.HomesteadFoundationComponent.RecalcTowns(Boolean notify)
   at Eco.Gameplay.Settlements.Components.HomesteadFoundationComponent.<Initialize>b__19_1()
   at Eco.Gameplay.InfluenceObjects.InfluenceChangeNotifier.MarkInfluenceChanged(IEnumerable`1 changedPlots)
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementChangeDetector.DoUpdateNow()
   at Eco.Gameplay.Settlements.Internal.ChangeDetection.SettlementChangeDetector.Tick()
   at Eco.Gameplay.Settlements.SettlementManager.FastTick()
   at Eco.Gameplay.Civics.CivicsData.TickAll()
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)`

The exact command was **/property unclaimabandoned 5**

**Comment by Maverick0581** [comment]
It's not affecting players directly, I think this happens when a player loads part of the map.  I can't manage to reproduce the first error so maybe it's related to a mod..
