### ISSUE TITLE
Loans contracts hang around after completion but can me Marked as failed

### ISSUE THREAD

**Issue by CraigWCooper** [StrangeLoopGames/EcoIssues#25111]
\
**User Id: (484cf1c9-434a-4071-035a-08dc8cbaa722)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
1. Make Loan
2. someone takes loan
3. They complete loan and pay back
4. contract still in contracts list and gives me option to mark as failed even when its been paided
5. mark as failed

**Expected behavior:**
Contract thats been paid cannot be marked as failed or appear in the contract list

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClauseFinanceBase.Fill(FinanceAction action)
   at Eco.Gameplay.Economy.Contracts.ContractClauseFinanceBase.TryFail(GameActionPack pack, User contractor, User client)
   at Eco.Gameplay.Economy.Contracts.Contract.<MarkJobFailed>b__109_0(ContractClause clause, GameActionPack pack)
   at Eco.Gameplay.Economy.Contracts.Contract.ConfigureAndTryPerform(WorkableAction action, Action`2 checkClause, User citizen, Boolean notify, Boolean forced)
   at Eco.Gameplay.Economy.Contracts.Contract.MarkJobFailed(User user)
   at Eco.Gameplay.Economy.Contracts.Cont</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @CraigWCooper 

Thank you for submitting this bug report.
I was able to verify the issue and have created an internal report.
A fix should be implemented soon with the upcoming game updates.

Ref. ECO-36241

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14499 in staging.
