### ISSUE TITLE
USER ISSUE: Can't connect to server

### ISSUE THREAD

**Issue by IneaFaedyn** [StrangeLoopGames/EcoIssues#25143]
\
**User Id: (15d8af73-9240-4df7-2d54-08dcce89dbe7)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
I created a server using a cloud hosting service. When joining the server, I get an error message.

The server seems to start properly, I can access the web UI and see the world, but when I try to connect I get NullReferenceException

**Expected behavior:**
connected

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client, Boolean allowDisconnectionAfterActionFailure, Boolean ignoreTestMode)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Outer Exceptions:
Exception has been thrown by the targ</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IneaFaedyn** [comment]
[Player.log](https://github.com/user-attachments/files/16914179/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16914180/Player-prev.log)
[log_240906111239.log](https://github.com/user-attachments/files/16914182/log_240906111239.log)

**Comment by pflannigan** [comment]
in the service hosting console did you link your eco account? something like this
![pic](https://github.com/user-attachments/assets/ffcc8e0c-5a6d-44df-8351-ce3ca81b0252)

**Comment by IneaFaedyn** [comment]
Yes
<img width="468" alt="2024-09-07 11_53_26-g-portal com — Mozilla Firefox" src="https://github.com/user-attachments/assets/89ff57b8-4f57-4e09-99a5-49c6b4d56c7f">

**Comment by IneaFaedyn** [comment]
@pflannigan Not sure if it helps, but I also noticed that it stops responding with the NullReferenceException and changes to

Authentication handshake failed with exception:
Server is offline or running in offline mode. It needs to be started in online mode to allow players to connect to it.

I didn't turn it off and I didn't change anything to offline or online mode. 

It seems to consistently do this though, starts with NullReferenceException no matter who logs in, and then sometime after shows offline. I assume something internal is breaking and making it shut itself down? But I can still access the web UI and it seems to suggest that time is moving forward in-game.

**Comment by IneaFaedyn** [comment]
Also found this in a recent log that I don't remember seeing in the initial log, just mentions that it's receiving a 401 response somewhere

[11:53:00.009] [113] [Error] [Eco] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client, Boolean allowDisconnectionAfterActionFailure, Boolean ignoreTestMode)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Shared.Networking.RPCInvocation.Invoke()
   at Eco.Shared.Networking.RPCManager.Invoke(INetClient client, RPCInvocation invocation, Boolean notifyOnPermissionFail)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodName)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONValue bsonValue)
   at Eco.Shared.Networking.NetObject.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONValue bson)
   at Eco.Plugins.Networking.Client.<.ctor>b__86_4() System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client, Boolean allowDisconnectionAfterActionFailure, Boolean ignoreTestMode)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Shared.Networking.RPCInvocation.Invoke()
   at Eco.Shared.Networking.RPCManager.Invoke(INetClient client, RPCInvocation invocation, Boolean notifyOnPermissionFail)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodName)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONValue bsonValue)
   at Eco.Shared.Networking.NetObject.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONValue bson)
   at Eco.Plugins.Networking.Client.<.ctor>b__86_4()
[12:51:41.700] [136] [Error] [Eco] The HTTP status code of the response was not expected (401).

Status: 401
Response:

**Comment by IneaFaedyn** [comment]
Actually that log file also shows that I'm logged in I think

[log_240907010609.log](https://github.com/user-attachments/files/16920153/log_240907010609.log)

[11:50:11.026] [10] [ Info] [Eco] Logged in to Strange Cloud using username and password.
 
[11:50:11.051] [15] [ Info] [Eco] Eco Server 0.11.0.4 beta release-722, Logged in as Sizdian
 
[11:50:11.051] [4] [ Info] [Eco] Starting PerformancePlugin                        ...

**Comment by IneaFaedyn** [comment]
Also I can see the join attempts in the chat logs

[2024-09-06 22:30:25.530][ Info] --> Inea Faedyn joined the server. 
[2024-09-06 22:53:25.145][ Info] --> Inea Faedyn joined the server. 
[2024-09-06 23:01:34.197][ Info] --> Inea Faedyn joined the server. 
[2024-09-06 23:14:32.283][ Info] --> Inea Faedyn joined the server. 
[2024-09-06 23:15:41.635][ Info] --> Vundecat joined the server.

**Comment by D3nnis3n** [comment]
What cloud service is that? A 401 could indicate a block by cloudflare.

**Comment by IneaFaedyn** [comment]
@D3nnis3n G-Portal

**Comment by D3nnis3n** [comment]
Is this solely happening for you or for everyone?
Does the issue persist when you create a new world?

**Comment by IneaFaedyn** [comment]
@D3nnis3n It was happening for everyone and persisted each time I created a new world. I didn't try to join another world, but I just switched cloud hosts and everything's good now, so it might have been something specific to the other one.

I dunno if the issue should be kept open. I don't have a problem anymore, but I feel like the error could have been more descriptive as I wouldn't have solved it with the old game host because I didn't have enough insight or control over the server and the error and logs didn't tell me much about the actual underlying issue. I assume something network related.

**Comment by D3nnis3n** [comment]
Well, it's a 401 - Unauthorized, so requests from that server were denied. Potentially by Cloudflare for security reasons.
Without direct contact to someone that has system access to the server host and the IP of the server while it's running there isn't anything that could be investigated there, hence I'm going to close the report.

That also wouldn't be a bug, but an issue for support@strangeloopgames.com.
