### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by Maverick0581** [StrangeLoopGames/EcoIssues#25142]
```
Eco 11.0.4
SLG ID : c42e9f54-3dfc-4bd1-7cfe-08dc8d1bff58
```
Logs & save files [here](https://drive.google.com/drive/folders/1W2uew9R1Ti0PNTe1Vaia6mfceozAJDBB?usp=sharing)

Hey,
The server crashed for no reason after 30 mins online
```
[22:39:34.790] [145] [Error] [Eco] System.AggregateException: One or more errors occurred. (LiteDB ENSURE: transaction must be active to rollback (current state: Disposed))
 ---> System.Exception: LiteDB ENSURE: transaction must be active to rollback (current state: Disposed)
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.TransactionService.Rollback()
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at Eco.Stats.Stats.<>c__DisplayClass31_0.<RecordBulk>b__1(IGrouping`2 group)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects, AccountChangeSet acc)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User userToNotify, GameActionPack actionPack)
   at Eco.Gameplay.Items.WorkOrder.TryFinishIteration()
   at Eco.Gameplay.Items.WorkOrder.CheckTime(Boolean canBeActive)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders()
   at Eco.Gameplay.Components.CraftingComponent.Tick(Single deltaTime)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   --- End of inner exception stack trace --- System.Exception: LiteDB ENSURE: transaction must be active to rollback (current state: Disposed)
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.TransactionService.Rollback()
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at Eco.Stats.Stats.<>c__DisplayClass31_0.<RecordBulk>b__1(IGrouping`2 group)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects, AccountChangeSet acc)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User userToNotify, GameActionPack actionPack)
   at Eco.Gameplay.Items.WorkOrder.TryFinishIteration()
   at Eco.Gameplay.Items.WorkOrder.CheckTime(Boolean canBeActive)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders()
   at Eco.Gameplay.Components.CraftingComponent.Tick(Single deltaTime)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass8_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
```

**Comment by D3nnis3n** [comment]
Known issue in LiteDB that has been reported there and needs to be fixed there, but hasn't so far. Nothing we could do.
