### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by xSev07** [StrangeLoopGames/EcoIssues#25175]
\
**User Id: (48a467a8-8598-4a87-cbdc-08dcd3649fe7)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
buy in shop

**Expected behavior:**
goods bought

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: KeyNotFoundException
Message:The given key 'itemsToBuy' was not present in the dictionary.
Source:System.Private.CoreLib

System.Collections.Generic.KeyNotFoundException: The given key 'itemsToBuy' was not present in the dictionary.
   at Eco.Gameplay.Components.Store.StoreComponent.ValidateOffers(PurchaseData data, BSONObject tradeData)
   at Eco.Gameplay.Components.Store.StoreComponent.Validate(BSONObject tradeData, User tradeInitiator, BankAccount purchaserAccount, PurchaseData& purchaseData)
   at Eco.Gameplay.Components.Store.StoreComponent.PerformTrade(Player tradeIniator, BSONObject tradeData, BankAccount purchaserAccount)
   at InvokeStub_StoreComponent.PerformTrade(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, B</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Can you please provide the full client log and also the full server log?
