### ISSUE TITLE
USER ISSUE: game crashes when moving store items (playtest)

### ISSUE THREAD

**Issue by legolias706** [StrangeLoopGames/EcoIssues#25189]
\
**User Id: (58eac573-5ff8-47c2-fee4-08dcaf2430bb)**
**Version:** 0.11.1.0 beta staging-2989

**Steps to Reproduce:**
1. get a store item.
2. put any item for sale/buying.
3. move that item to any other category in the menu.

It happens even when the store is off or disabled.
Only happens moving between categories, not within them. 

**Expected behavior:**
It should have moved the item to another category

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Shared

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Shared.Networking.RPCInvocation..ctor(RPCMethod method, Object target, Int32 argsCount)
   at Eco.Shared.Networking.RPCManager.PrepareInvocation[TArg](INetClient client, IList`1 packedArgs, Func`3 unpackArg, RPCMethod method, Object target)
   at Eco.Shared.Networking.RPCManager.TryCreateInvocation[TArg](INetClient client, Object target, String methodName, IList`1 packedArgs, Func`3 unpackArg, RPCInvocation& invocation)
   at Eco.Core.Controller.ControllerManager.HandleViewRPC(INetClient client, Int32 universalID, String methodIdOrName, BSONObject bson)
   at InvokeStub_Client.ViewRPC(Object,</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, but I am playing playtest update 11.1 on Coast Redwood

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/user-attachments/files/17237817/Player.log)
[Player.log.copy.txt](https://github.com/user-attachments/files/17237818/Player.log.copy.txt)

**Comment by D3nnis3n** [comment]
Already reported on Discord.
