### ISSUE TITLE
USER ISSUE: Not able to connect to any server

### ISSUE THREAD

**Issue by Rhoff3** [StrangeLoopGames/EcoIssues#25198]
\
**User Id: (d14e4b69-608f-4b4b-d488-08dce995d450)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
Load Eco

Start game and join server
error pops up		

**Expected behavior:**
Let me enter server

**Actual behavior:**
The following error message popped up:
```
Authentication handshake failed with exception:
User does not own Eco.
   at StrangeCloud.Api.Controllers.AuthenticationController.GetWorldTicket(Guid serverId) in C:\Strange-Cloud\StrangeCloud.Api\Controllers\AuthorizationController.cs:line 187
   at lambda_method2402(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The account does not own Eco and hence cannot play on multiplayer servers, please reach out to support@strangeloopgames.com, account issues cannot be taken care of here.

**Comment by Rhoff3** [comment]
I bought the game on STEAM though. My gmail is ***@***.***

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com, we cannot deal with sensitive data on this platform where everyone can read it.
