### ISSUE TITLE
USER ISSUE: Server exception upon sending a whisper chat

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#25208]
\
**User Id: (31387c40-a57f-4255-babb-08dcbe0ab005)**
**Version:** 0.11.1.0 beta release-750

**Steps to Reproduce:**
Upon sending whisker mail to someone with 2 messages already or less, server throws up an exception

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Systems.TextLinks.TextLinkManager.MarkUpText(String text, Boolean checkIgnoreList)
   at Eco.Gameplay.Systems.Messaging.Chat.ChatMessage.ToBson(INetClient client)
   at Eco.Gameplay.Systems.Messaging.Chat.ChatManager.ProcessMessage(ChatMessage message)
   at Eco.Gameplay.Systems.Messaging.Chat.ChatManager.Send(User user, IChatReceiver to, String message)
   at Eco.Gameplay.Systems.Messaging.Chat.ChatManager.ParseAndSendMessage(User user, String text, String tag)
   at Eco.Gameplay.Systems.Messaging.Chat.ChatManager.SanitizeAndSendChat(User user, String text, Supp</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
server-side only

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Can you please provide the full logfile of the exception from both client and server side and any additional details, for example the names of the players this appears with? The issue is not reproducible by simply sending someone a message that already received one before, there must be specific circumstances it happens with.
