### ISSUE TITLE
dynamite on bedrock = server crash

### ISSUE THREAD

**Issue by Arranoa-jolasten** [StrangeLoopGames/EcoIssues#25240]
---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.World.PersistentChunk.GetBlock(Vector3i localPosition)
   at Eco.Simulation.RouteProbing.RouteManager.UpdateBlocks()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.RouteProbing.RouteManager.Update()
   at Eco.Core.Serialization.StorageExtensions.Modify[T](T storage, Action`1 action)
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   --- End of inner exception stack trace --- System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.World.PersistentChunk.GetBlock(Vector3i localPosition)
   at Eco.Simulation.RouteProbing.RouteManager.UpdateBlocks()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.RouteProbing.RouteManager.Update()
   at Eco.Core.Serialization.StorageExtensions.Modify[T](T storage, Action`1 action)
   at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)

**Comment by D3nnis3n** [comment]
Already fixed in 11.1.2: https://github.com/StrangeLoopGames/Eco/pull/14576
