### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Oreloth** [StrangeLoopGames/EcoIssues#25280]
Logs from a newly installed server:

```
[10:07:37] Logged in to Strange Cloud using user token.
[10:07:37] Eco Server 0.11.1.2 beta release-767, Logged in as oreloth
[10:07:37] Starting PerformancePlugin                        ...
[10:07:37] Starting PerformancePlugin                        ... Finished in 0.024 sec
[10:07:37] Starting ProfilingPlugin                          ...
[10:07:37] Starting ProfilingPlugin                          ... Finished in 0.000 sec
[10:07:37] Starting MaintenancePlugin                        ...
[10:07:37] Starting MaintenancePlugin                        ... Finished in 0.009 sec
[10:07:37] Server Initialization                             ...
[10:07:37] Starting FeaturesPlugin                           ...
[10:07:37] Starting FeaturesPlugin                           ... Finished in 0.013 sec
[10:07:37] Starting BalancePlugin                            ...
[10:07:37] Starting BalancePlugin                            ... Finished in 0.007 sec
[10:07:37] Starting StrangeWorldsPlugin                      ...
[10:07:37] Starting StrangeWorldsPlugin                      ... Finished in 0.010 sec
[10:07:37] Starting NetworkManager                           ...
[10:07:37] Starting NetworkManager                           ... Finished in 0.016 sec
[10:07:37] Starting DifficultySettings                       ...
[10:07:37] Starting DifficultySettings                       ... Finished in 0.139 sec
[10:07:37] Starting ModKitPlugin                             ...
[10:07:50] Starting ModKitPlugin                             ... Finished in 12.267 sec
[10:07:50] Loading mods                                      ...
[10:07:50] Loading Eco.IntegrationTests...
[10:07:50] Starting WorldGeneratorPlugin                     ...
[10:07:50] Initializing Simulation Types                     ...
[10:07:50] Starting StorageManager                           ...
[10:07:50] Starting BackupPlugin                             ...
[10:07:50] Starting BackupPlugin                             ... Finished in 0.005 sec
[10:07:50] Initializing Simulation Types                     ... Finished in 0.424 sec
[10:07:50] Initializing items                                ...
[10:07:50] Starting WorldGeneratorPlugin                     ... Finished in 0.479 sec
[10:07:56] Starting StorageManager                           ... Finished in 6.188 sec
[10:07:57] Initializing items                                ... Finished in 6.587 sec
[10:07:57] Initializing skills                               ...
[10:07:57] Initializing skills                               ... Finished in 0.036 sec
[10:07:57] Loading mods                                      ... Finished in 7.067 sec
[10:07:58] Starting GameDataPlugin                           ...
[10:07:59] Starting GameDataPlugin                           ... Finished in 1.712 sec
[10:08:00] Starting WorldPlugin                              ...
[10:08:00] Initializing world                                ...
[10:08:00] Initializing world                                ... Finished in 0.009 sec
[10:08:00] Caching world data                                ...
[10:08:00] Caching world data                                ... Finished in 0.001 sec
[10:08:00] Starting WorldPlugin                              ... Finished in 0.034 sec
[10:08:00] Starting ControllerManager                        ...
[10:08:00] Starting UserManager                              ...
[10:08:00] Starting TimePlugin                               ...
[10:08:00] Starting Stats                                    ...
[10:08:00] Starting EcoObjectManager                         ...
[10:08:00] Starting EcoObjectManager                         ... Finished in 0.001 sec
[10:08:00] Starting Stats                                    ... Finished in 0.015 sec
[10:08:00] Starting TimePlugin                               ... Finished in 0.109 sec
[10:08:01] Starting UserManager                              ... Finished in 0.766 sec
[10:08:10] Starting ControllerManager                        ... Finished in 10.281 sec
[10:08:10] Starting MinimapManager                           ...
[10:08:10] Starting MinimapManager                           ... Finished in 0.003 sec
[10:08:10] Starting DevSectionPlugin                         ...
[10:08:10] Starting DevSectionPlugin                         ... Finished in 0.002 sec
[10:08:10] Starting ExhaustionPlugin                         ...
[10:08:10] Starting ExhaustionPlugin                         ... Finished in 0.059 sec
[10:08:10] Starting EcoSim                                   ...
[10:08:10] Initializing plants                               ...
[10:08:10] Initializing plants                               ... Finished in 0.008 sec
[10:08:10] Starting EcoSim                                   ... Finished in 0.069 sec
[10:08:10] Starting WorldLayerManager                        ...
[10:08:10] Starting EconomyPlugin                            ...
[10:08:10] Starting ReputationPlugin                         ...
[10:08:10] Starting RouteProbingPlugin                       ...
[10:08:10] Starting PropertyManager                          ...
[10:08:10] Starting PausePlugin                              ...
[10:08:10] Starting EconomyTracker                           ...
[10:08:10] Starting UserTracker                              ...
[10:08:10] Starting InitialSpawnPlugin                       ...
[10:08:10] Starting SettlementsPlugin                        ...
[10:08:10] Starting WorldObjectManager                       ...
[10:08:10] Starting ObjectivePlugin                          ...
[10:08:10] Starting RoomPlugin                               ...
[10:08:10] Starting SleepPlugin                              ...
[10:08:10] Starting PowerGridManager                         ...
[10:08:10] Starting MessagingServer                          ...
[10:08:10] Starting GameActionAccumulator                    ...
[10:08:10] Starting DisasterPlugin                           ...
[10:08:10] Starting VoiceManager                             ...
[10:08:10] Starting UserTracker                              ... Finished in 0.001 sec
[10:08:10] Starting MemoryManager                            ...
[10:08:10] Starting DataExporter                             ...
[10:08:10] Starting DataExporter                             ... Finished in 0.000 sec
[10:08:10] Starting UserTexturePlugin                        ...
[10:08:10] Starting WeatherPlugin                            ...
[10:08:10] Starting GarbagePlugin                            ...
[10:08:10] Starting HolidayPlugin                            ...
[10:08:10] Starting SpoilagePlugin                           ...
[10:08:10] Starting CivicsPlugin                             ...
[10:08:10] Starting EconomyTracker                           ... Finished in 0.005 sec
[10:08:10] Starting SpeciesLayeredCatchPlugin                ...
[10:08:10] Starting EconomyPlugin                            ... Finished in 0.006 sec
[10:08:10] Starting EnvVarManager                            ...
[10:08:10] Starting VoiceManager                             ... Finished in 0.005 sec
[10:08:10] Starting PowerGridManager                         ... Finished in 0.007 sec
[10:08:10] Starting SpoilagePlugin                           ... Finished in 0.006 sec
[10:08:10] Starting GarbagePlugin                            ... Finished in 0.006 sec
[10:08:10] Starting EnvVarManager                            ... Finished in 0.003 sec
[10:08:10] Starting GameActionAccumulator                    ... Finished in 0.009 sec
[10:08:10] Starting ObjectivePlugin                          ... Finished in 0.009 sec
[10:08:10] Starting RouteProbingPlugin                       ... Finished in 0.011 sec
[10:08:10] Starting PropertyManager                          ... Finished in 0.011 sec
[10:08:10] Starting UserTexturePlugin                        ... Finished in 0.017 sec
[10:08:10] Starting DisasterPlugin                           ... Finished in 0.021 sec
[10:08:10] Starting InitialSpawnPlugin                       ... Finished in 0.022 sec
[10:08:10] Starting ReputationPlugin                         ... Finished in 0.024 sec
[10:08:10] Starting SpeciesLayeredCatchPlugin                ... Finished in 0.019 sec
[10:08:10] Starting RoomPlugin                               ... Finished in 0.024 sec
[10:08:10] Starting MemoryManager                            ... Finished in 0.024 sec
[10:08:10] Starting WeatherPlugin                            ... Finished in 0.026 sec
[10:08:10] Starting HolidayPlugin                            ... Finished in 0.033 sec
[10:08:10] Starting CivicsPlugin                             ... Finished in 0.033 sec
[10:08:10] Starting SleepPlugin                              ... Finished in 0.043 sec
[10:08:10] Starting PausePlugin                              ... Finished in 0.044 sec
[10:08:10] Starting WorldLayerManager                        ... Finished in 0.059 sec
[10:08:10] Starting SettlementsPlugin                        ... Finished in 0.082 sec
[10:08:10] Starting MessagingServer                          ... Finished in 0.082 sec
[10:08:10] Starting WorldObjectManager                       ... Finished in 0.139 sec
[10:08:10] Starting TwitchPlugin                             ...
[10:08:10] Starting TwitchPlugin                             ... Finished in 0.001 sec
[10:08:10] Starting RconPlugin                               ...
[10:08:10] Starting RconPlugin                               ... Finished in 0.000 sec
[10:08:10] Starting WebServerPlugin                          ...
[10:08:10] Starting WebServerPlugin                          ... Finished in 0.000 sec
[10:08:10] Starting ActorsPlugin                             ...
[10:08:10] Starting IntegrationTestsPlugin                   ...
[10:08:10] Starting ChatLogger                               ...
[10:08:10] Starting SettlementDefs                           ...
[10:08:10] Starting ActorsPlugin                             ... Finished in 0.000 sec
[10:08:10] Starting SettlementDefs                           ... Finished in 0.000 sec
[10:08:10] Starting ChatLogger                               ... Finished in 0.000 sec
[10:08:10] Starting IntegrationTestsPlugin                   ... Finished in 0.000 sec
[10:08:10] Skipping Windows firewall setup, platform = Unix
[10:08:10] (You may need to manually open port 3001 if the EcoWebServer is inaccessible)
[10:08:10] Initializing registrars for EconomyPlugin         ...
[10:08:10] Initializing registrars for EconomyPlugin         ... Finished in 0.025 sec
[10:08:10] Initializing registrars for CivicsPlugin          ...
[10:08:10] Initializing registrars for CivicsPlugin          ... Finished in 0.021 sec
[10:08:10] Initializing registrars for SettlementsPlugin     ...
[10:08:10] Initializing registrars for SettlementsPlugin     ... Finished in 0.001 sec
[10:08:10] Initializing registrars for PropertyManager       ...
[10:08:11] Initializing registrars for PropertyManager       ... Finished in 0.001 sec
[10:08:11] Initializing registrars for MessagingServer       ...
[10:08:11] Initializing registrars for MessagingServer       ... Finished in 0.002 sec
[10:08:11] Initializing registrars for GameDataPlugin        ...
[10:08:11] Initializing registrars for GameDataPlugin        ... Finished in 0.010 sec
[10:08:11] Initializing registrars for InitialSpawnPlugin    ...
[10:08:11] Initializing registrars for InitialSpawnPlugin    ... Finished in 0.000 sec
[10:08:11] Initializing DifficultySettings                   ...
[10:08:11] Initializing EconomyPlugin                        ...
[10:08:11] Initializing CivicsPlugin                         ...
[10:08:11] Initializing Stats                                ...
[10:08:11] Initializing DifficultySettings                   ... Finished in 0.008 sec
[10:08:11] Initializing EconomyPlugin                        ... Finished in 0.050 sec
[10:08:11] Initializing CivicsPlugin                         ... Finished in 0.072 sec
[10:08:11] Can't find ecopedia link 'HomesteadSupportClaimItem' (referenced on page 'Settlements')
[10:08:12] Initializing Stats                                ... Finished in 0.877 sec
[10:08:12] Initializing WorldGeneratorPlugin                 ...
[10:08:12] Generating world 0.52km²                          ...
[10:08:15] Generating terrain                                ...
[10:08:16] Generating terrain                                ... Finished in 1.436 sec
[10:08:16] Generating world 0.52km²                          ... Finished in 4.383 sec
[10:08:16] Initializing WorldGeneratorPlugin                 ... Finished in 4.387 sec
[10:08:16] Server Initialization                             ... Finished in 38.828 sec
[10:08:16] Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.WorldGenerator

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.WorldGenerator.TerrainModule.TrySpawnBlock(TerrainGeneratorPosition& pos, Double height, Int32 depth, Random random, Type parentBlockType, Type& blockType)
   at Eco.WorldGenerator.TerrainModule.Eco.WorldGenerator.ITerrainModule.TrySpawnBlock(TerrainGeneratorPosition& pos, Double height, Int32 depth, Random random, Type parentBlockType, Type& blockType)
   at Eco.WorldGenerator.TerrainGenerator.Generate(Int32 chunkPosX, Int32 chunkPosZ)
   at Eco.WorldGenerator.WorldGeneratorPlugin.<>c__DisplayClass34_1.<CreateWorld>b__1(Vector2i columnPos)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.) (The type initializer for 'Gdip' threw an exception.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)))
One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.) (The type initializer for 'Gdip' threw an exception.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.))
One or more errors occurred. (Object reference not set to an instance of an object.) (The type initializer for 'Gdip' threw an exception.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
[10:08:21] Shutdown finished
[10:08:21] Errors report:
Can't find ecopedia link 'HomesteadSupportClaimItem' (referenced on page 'Settlements'): 1
Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.WorldGenerator

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.WorldGenerator.TerrainModule.TrySpawnBlock(TerrainGeneratorPosition& pos, Double height, Int32 depth, Random random, Type parentBlockType, Type& blockType)
   at Eco.WorldGenerator.TerrainModule.Eco.WorldGenerator.ITerrainModule.TrySpawnBlock(TerrainGeneratorPosition& pos, Double height, Int32 depth, Random random, Type parentBlockType, Type& blockType)
   at Eco.WorldGenerator.TerrainGenerator.Generate(Int32 chunkPosX, Int32 chunkPosZ)
   at Eco.WorldGenerator.WorldGeneratorPlugin.<>c__DisplayClass34_1.<CreateWorld>b__1(Vector2i columnPos)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.) (The type initializer for 'Gdip' threw an exception.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)))
One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.) (The type initializer for 'Gdip' threw an exception.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.))
One or more errors occurred. (Object reference not set to an instance of an object.) (The type initializer for 'Gdip' threw an exception.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
: 1
```
System:
```
OS: AlmaLinux release 8.10 (Cerulean Leopard)
CPU: Intel Xeon E3-1275v5
RAM: 64 GB DDR4 ECC
```

**Comment by padmanek** [comment]
Did you run the install.sh script that comes with Eco Linux server? if that script fails your OS is not supported. (unless you fix the script yourself to install all the required components)

**Comment by Oreloth** [comment]
Yeah, it seems the script isn't ready for RHEL based Linux. I'll check if I can fix it and share it when the script is ready.

**Comment by padmanek** [comment]
[10:08:11] Can't find ecopedia link 'HomesteadSupportClaimItem' (referenced on page 'Settlements') 
is a harmless warning, can be ignored

**Comment by Oreloth** [comment]
Okay, so what about this part?

```
[10:08:16] Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.WorldGenerator

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.WorldGenerator.TerrainModule.TrySpawnBlock(TerrainGeneratorPosition& pos, Double height, Int32 depth, Random random, Type parentBlockType, Type& blockType)
   at Eco.WorldGenerator.TerrainModule.Eco.WorldGenerator.ITerrainModule.TrySpawnBlock(TerrainGeneratorPosition& pos, Double height, Int32 depth, Random random, Type parentBlockType, Type& blockType)
   at Eco.WorldGenerator.TerrainGenerator.Generate(Int32 chunkPosX, Int32 chunkPosZ)
   at Eco.WorldGenerator.WorldGeneratorPlugin.<>c__DisplayClass34_1.<CreateWorld>b__1(Vector2i columnPos)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.) (The type initializer for 'Gdip' threw an exception.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)))
One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.) (The type initializer for 'Gdip' threw an exception.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.))
One or more errors occurred. (Object reference not set to an instance of an object.) (The type initializer for 'Gdip' threw an exception.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
[10:08:21] Shutdown finished
```

**Comment by padmanek** [comment]
I still think there's an issue with dependencies. - (The type initializer for 'Gdip' threw an exception.)
Gdip is just GDI+ so a graphics library for .NET. 
World generator makes a lot of images during world generation - for layers and maps and such. 
Do you have libgdiplus installed? 
It's my best guess and since this is not an officialy supported OS you're pretty much on your own in figuring this out.

**Comment by padmanek** [comment]
Glad u got it working. Looks like I was at least able to lead you towards a solution :)

**Comment by Oreloth** [comment]
Yep, I'm gonna let the post open for now, maybe someone will show up here soon.

**Comment by D3nnis3n** [comment]
Thanks, we have added your changes to the script and noted your authorship in a comment.

**Comment by Oreloth** [comment]
> Thanks, we have added your changes to the script and noted your authorship in a comment.

Oh, thank you very much, sir.
