### ISSUE TITLE
USER ISSUE: Ошибка

### ISSUE THREAD

**Issue by 8Siegfried8** [StrangeLoopGames/EcoIssues#25282]
\
**User Id: (f841e055-6f62-4711-b94d-08dcfdbdc43c)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
Вход на любой сервер 

**Expected behavior:**
Я долже войти на сервер 

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Authentication handshake failed with exception:
User does not own Eco.
   at StrangeCloud.Api.Controllers.AuthenticationController.GetWorldTicket(Guid serverId) in C:\Strange-Cloud\StrangeCloud.Api\Controllers\AuthorizationController.cs:line 187
   at lambda_method1834(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Нет, да

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is an account issue, please reach out to support@strangeloopgames.com. Typically this happens because you had a Steam account linked to an SLG account before owning the game on Steam. In that case a simple login via Steam on play.eco will update your SLG account to own Eco again.
