### ISSUE TITLE
USER ISSUE: Crash following colony relocation

### ISSUE THREAD

**Issue by Jack-Midard** [StrangeLoopGames/EcoIssues#25314]
\
**User Id: (87e055bb-d8c0-4bbf-df1a-08dd0b3bb4a7)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**
- Place a colony in a claim room
- Take the hammer and move the colony 2 blocks further into the same room
- Press confirm

**Expected behavior:**
Server disconnection

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.Settlement.<Initialize>b__182_0()
   at Eco.Gameplay.Items.WorldObjectItem.Move(Player player, Vector3i pos, Quaternion rotation, INetObject woNetObject)
Outer Exceptions:
One or more errors occurred. (Object reference not set to an instance of an object.)</size>

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, mods are installed, I didn't test without mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Not been able to reproduce, can you attach the savegame this happens with and note where the foundation is that you try to move within the room?

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/25567
