### ISSUE TITLE
Server crash on next startup if there is a Water Filter in game.

### ISSUE THREAD

**Issue by TannicArturo98** [StrangeLoopGames/EcoIssues#25320]
When you build a Water Filter in game, save and shutdown the server, to the next server startup it will crash with:

```
[19:50:04.940] [10] [Error] [Eco] Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Mods

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Mods.TechTree.FilterComponent.get_Operating() in F:\Giochi\steamapps\common\Eco\Eco_Data\Server\Mods\__core__\Objects\WaterFilter.cs:line 113
   at Eco.Gameplay.Objects.WorldObject.<>c.<UpdateEnabledAndOperating>b__135_1(IOperatingWorldObjectComponent c)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Objects.WorldObject.UpdateEnabledAndOperating()
   at Eco.Gameplay.Components.MustBeOwnedComponent.UpdateOwner()
   at Eco.Gameplay.Components.MustBeOwnedComponent.Initialize()
   at Eco.Gameplay.Objects.WorldObject.InitializeComponents()
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass23_0.<Initialize>b__1(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)))
One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.))
One or more errors occurred. (Object reference not set to an instance of an object.)
```

To fix this error i should change the condition at 113 line in Eco\Eco_Data\Server\Mods\__core__\Objects\WaterFilter.cs:
`public bool Operating => this.converter != null && (this.converter.In.BufferAmount > 0 || this.converter.In.LastTickConsumed > 0);`

**Comment by D3nnis3n** [comment]
Fixed in 11.1.5.
