### ISSUE TITLE
server in crash loop after update

### ISSUE THREAD

**Issue by Arranoa-jolasten** [StrangeLoopGames/EcoIssues#25324]
Can't find ecopedia link 'HomesteadSupportClaimItem' (referenced on page 'Settlements'): 1
Failed to start the server. Exception was Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.ClaimStakes.SettlementClaimStakeItem.RepresentsItem(Item other)
   at Eco.Gameplay.Items.InventoryChangeSet.<>c__DisplayClass54_0.<RemoveItemsUnique>b__0(ItemStack x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Eco.Gameplay.Items.InventoryChangeSet.RemoveItemsUnique(Item matchesItem, Int32 quantity, Inventory inventory)
   at Eco.Gameplay.Items.Inventory.TryRemoveItemsAsManyAsPossibleUnique(Item mustMatchItem, Int32 quantity, User user)
   at Eco.Gameplay.Components.SpawnedClaimsComponent.AdjustSpawnedStakesAndClaims(Type itemType, Int32 count)
   at Eco.Gameplay.Settlements.SettlementProperty.SynchornizeClaims(Boolean forceRecountAllPapersAndStakes)
   at Eco.Gameplay.Settlements.Components.SettlementFoundationComponent.<InitFoundedSettlement>b__65_0()
   at Eco.Core.Utils.Initializer.Initialize()
   at Eco.Gameplay.Civics.Demographics.DemographicManager.<Initialize>b__24_1()
   at Eco.Core.Utils.Initializer.Initialize()
   at Eco.Core.Utils.Initializer.Initialize()
   at Eco.Core.Systems.Registrars.InitializeAllRegistrars()
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
: 1

**Comment by Arranoa-jolasten** [comment]
tried to upload the server files but those are to big

**Comment by D3nnis3n** [comment]
We already have a release candidate for a fix for this issue, use the steam beta branch "11.1.6" for your players and the server and everything should work.

For players: Right click Eco in Steam -> Properties -> Betas -> "11.1.6" in the dropdown.
For the server: add -beta 11.1.6 to the SteamCMD commandline for updating the server.
