### ISSUE TITLE
Crash on Clicking on Red Light on Workbench

### ISSUE THREAD

**Issue by Gremwatch** [StrangeLoopGames/EcoIssues#2717]
this is the crash error that I got. 

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Do not create ItemAttributes after cache has been initialized.  Used the cached attribute.

Stack:
   at Eco.Gameplay.Items.ItemAttribute..ctor()
   at System.RuntimeTypeHandle.CreateCaInstance(RuntimeType type, IRuntimeMethodInfo ctor)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at Eco.Shared.Utils.ReflectionUtils.HasAttribute[T](Type type, Boolean inherit)
   at Eco.Gameplay.Components.StorageComponent.<>c.<OnActLeft>b__7_2(ItemStack stack)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Components.StorageComponent.<>c__DisplayClass7_0.<OnActLeft>b__0(IInventoryChangeSet changeSet)
   at Eco.Gameplay.Items.Inventory.TryModify(Action`1 callback, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnAct(InteractionContext context, Func`2 resultFunc)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment]
Just fixed this a minute ago, should be fixed in next staging
