### ISSUE TITLE
Crash when picking up a store

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2832]
Filed on Arend's behalf

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.StockpileComponent.TryUpdateInventoryFromWorld()
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback,
i cant hammer a store without a server crash :frowning:(edited)

**Comment by knexer** [comment]
The stockpile seems to think the store is still alive during its tick - possibly related to the worldobjecthandle lifecycle changes?

**Comment by Arend90** [comment]
Phlo - Today 18:38
anyone else getting this error?
sry for long post
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.StockpileComponent.TryUpdateInventoryFromWorld()
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Think we still getting this but now without stores

**Comment by noblackthunder** [comment]
Constant crashes with long loading time issue https://github.com/StrangeLoopGames/EcoIssues/issues/2865 is causing lots of frustration. Needs a hotfix

**Comment by Arend90** [comment]
every crash we had the last 3 days had something to do with a stockpile

**Comment by MarjieAVolk** [comment]
So @knexer @metachronism - are we thinking this.Parent is the thing that's null in that method?

**Comment by MarjieAVolk** [comment]
Oh wait, Eric marked the change to that line as fixing this bug, haha.  They don't get auto marked as fixed if they don't go into master.  Okay, it's fixed on release branch apparently, as of like 2 weeks ago, so should be fixed in next release.
