### ISSUE TITLE
New World on 6.1.1 experience crash loop after fresh build

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2861]
https://www.dropbox.com/s/p5bj88n1576ufcj/USKillservers.zip?dl=0

**Comment by MarjieAVolk** [comment]
Exception
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Plants.PlantBlock.get_Extra()
   at Eco.World.WorldChunk.PackIntoBson()
   at Eco.World.PersistentChunk.LocklessFreeze()
   at Eco.World.PersistentChunk.Freeze()
   at Eco.World.WorldPlugin.<>c__DisplayClass21_0.<Run>b__0(PersistentChunk chunk)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Eco.World.WorldPlugin.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Plants.PlantBlock.get_Extra()
   at Eco.World.WorldChunk.PackIntoBson()
   at Eco.World.PersistentChunk.LocklessFreeze()
   at Eco.World.PersistentChunk.Freeze()
   at Eco.World.WorldPlugin.<>c__DisplayClass21_0.<Run>b__0(PersistentChunk chunk)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

**Comment by MarjieAVolk** [comment]
I think there is another bug for this, but I can't find it

**Comment by knexer** [comment]
Looks related to https://github.com/StrangeLoopGames/EcoIssues/issues/2895 to me - at least it's the same stack trace.

**Comment by MarjieAVolk** [comment]
Oh yes there it is, thanks

**Comment by knexer** [comment]
Dibs

**Comment by knexer** [comment]
Yep, as expected it is an issue with the world wrapping.  The offending PlantBlock's position is (658, 100, 1400), in a chunk with chunk coordinates of (65, 10, 0).  So apparently the world is 140 in the z direction, and whatever sets that position is not wrapping correctly, presumably only when it's exactly on the boundary.

**Comment by knexer** [comment]
It's hard to confidently trace execution through all this reflection, but I *think* that the only place that this position is set is in PlantFactory::Create, which in turn is called only from PlantSim::SpawnPlant, which in turn is called only by SeedItem and PlantLayer.  We've seen both of these cases actually happen now - if this is a fresh world, it must be PlantLayer doing the deed, whereas the related issue was obviously SeedItem.

**Comment by knexer** [comment]
This is fixed.
