### ISSUE TITLE
Phantom Items in toolbar/Bag

### ISSUE THREAD

**Issue by Leadenigma** [StrangeLoopGames/EcoIssues#2864]
After moving items from toolbar to chests/worktables etc phantom icons remain in the toolbar.
When attempting to move these items results in the following error:

Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on AuthorizationInventory!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.Inventory.CheckAuthForMove(ItemStack source, ItemStack target, Player player)
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by johnkslg** [comment]
Tried this for quite awhile, with various simulated lag settings, and couldnt get it to happen.  Will close as no-repro for now, if you see it again can you try working out specific steps?

**Comment by MarjieAVolk** [comment]
Sean says he's seen it and has ideas about it, let's not close it

**Comment by MarjieAVolk** [comment]
Another report from #2975: "I made a campfire on a new save, placed the campfire and still had it in my toolbar. I moved it to another slot and my game crashed with this: {same exception}"

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/33855378-9be9525a-de79-11e7-9c3f-dfe77d651d17.png)
Getting it as well with campfire, research table, etc.
