### ISSUE TITLE
Planting on Join of World gave me Error and then Crashed Server 6.1.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2895]
I tried planting some beans and i got this
Caught exception: Object reference not set to an instance of an object.
and i had crashed the server
server was restarted, Admin planted beans ok, i tried again and got dropped and server crashed, this time i didnt get error (admin said was for inactivity) 
attaching the crash file

[Crash_11255737.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1502999/Crash_11255737.zip)

**Comment by Conchipedia** [comment]
this is also Happening with tomato seeds (giving same error and crashing server)

**Comment by Conchipedia** [comment]
uploading the world save (just in case it's something that might be causing this)

tried as a Zip but too big so linking it 
https://www.dropbox.com/s/ta7781k75xiihtk/game.eco?dl=0

**Comment by Conchipedia** [comment]
Think i found out why Server was Crashing, I'm trying to Plant one side at 999 and then other at 0
so it is right on the Join of the world

**Comment by MarjieAVolk** [comment]
Exception
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Plants.PlantBlock.get_Extra()
   at Eco.World.WorldChunk.PackIntoBson()
   at Eco.World.PersistentChunk.LocklessFreeze()
   at Eco.World.PersistentChunk.Freeze()
   at Eco.World.WorldPlugin.<>c__DisplayClass21_0.<Run>b__0(PersistentChunk chunk)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Eco.World.WorldPlugin.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Plants.PlantBlock.get_Extra()
   at Eco.World.WorldChunk.PackIntoBson()
   at Eco.World.PersistentChunk.LocklessFreeze()
   at Eco.World.PersistentChunk.Freeze()
   at Eco.World.WorldPlugin.<>c__DisplayClass21_0.<Run>b__0(PersistentChunk chunk)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

**Comment by knexer** [comment]
This is definitely fixed :)
