### ISSUE TITLE
server crash in seededobject

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#293]
--BEGIN DUMP--
Dump Time
06/16/2016 11:56:31

Exception
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Objects.SeededBlockObject.DoTick()
   at Eco.Gameplay.Interactable.WorldObject.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Gameplay.Objects.Manager.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by metachronism** [comment]
happened 2x now
