### ISSUE TITLE
Crashed my client when selling to shop, server seems to have soft crashed too

### ISSUE THREAD

**Issue by stromhurst** [StrangeLoopGames/EcoIssues#2936]
Alpha 6.1.1 (hotfixed one) release. I was selling about 459 Huckleberry and 620 wheat at the same time, Shop was using the serverwide minted currency we have, not the players credit. Maybe the player was out of the server wide currency? server being soft crashed means, after this, you could log on to the server chat with other players, but cant interact with tables. You can open the tables to see whats inside but when trying to do an action, craft or trade, nothing happens. nothing queues or gets traded.

```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC PerformTrade on StoreComponent!

Value cannot be null.
Parameter name: key

Stack:
at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
at System.Collections.Generic.Dictionary2.FindEntry(TKey key)
at Eco.Gameplay.Items.InventoryChangeSet.MoveItemsInternal[TKey](Type itemType, Int32 quantity, Inventory source, Inventory destination, Func2 sourceStackPredicate, Func`2 sourceStackOrder)
at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)

Stack:
at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)
```

might be related to issue 2376

**Comment by stromhurst** [comment]
Happend again, this time i broke the sale to 200 huckleberry, then 259 huckleberry worked fine, when selling 300 wheat next, i got this message 

`Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC PerformTrade on StoreComponent!

Value cannot be null.
Parameter name: key


Stack:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at Eco.Gameplay.Items.InventoryChangeSet.MoveItemsInternal[TKey](Type itemType, Int32 quantity, Inventory source, Inventory destination, Func`2 sourceStackPredicate, Func`2 sourceStackOrder)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)
`

**Comment by stromhurst** [comment]
An update. We are testing on our server so posting the pattern we have found. With a server restart, everything is working fine. then once anyone uses a bugged shop, one particular shop in our server as yet, their client crashes with the above error report. Then when they relog, that player cant use any other shop or crafting table untill the next server restart. and while this, when a player uses a shop and clicks the trade button, the game freezes, you can walk around but nothing else. Eventually server kicks u out for inactivty, upon relog, same thing. Only fixed with a server restart. even then if you use the 'bugged' shop same thing happens again. Not sure what causes the bugged shop, still investigating.

**Comment by MarjieAVolk** [comment]
Yep that's the same call stack, probably the same issue.  I'm going to close that one, since there is so much more data on this one.

**Comment by MarjieAVolk** [comment]
Okay this is really a shot in the dark here, but I'm thinking if one of the store's linked inventories had a null stack, that might explain this.  As far as I can tell, the only dictionary lookups in MoveItemsInternal are for changedStacks, which would take a stack from one of the inventories there, so that would have to be null.

@Arend90 posted a save file in the other bug, but the link is no longer working.  It would be really helpful to get that save, so I could see line numbers here.  (Or verify that it's been fixed already)

**Comment by stromhurst** [comment]
ok, i will ask Arend90 to see if he still has that save. But it wasnt resolved in 6.1.1, will keep trying on 6.1.2 now anyways to reproduce this.

**Comment by Arend90** [comment]
haha and i will ask phlo for the save :D <3

**Comment by Phlo123** [comment]
https://www.dropbox.com/s/95jj1uluayzynta/store%20save.eco?dl=0

The store.cs has the following lines commented as this was the easiest workaround the error when the room is broken and stores don't work anymore.
{...
//[RequireRoomContainment]
//[RequireRoomVolume(25)]                              
//[RequireRoomMaterialTier(1, 18)]
...}

**Comment by MarjieAVolk** [comment]
Okay, that shouldn't affect it I don't think.

Also, could you guys tell me which store is the bad one?

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/33456089-9ba0f9aa-d61e-11e7-8b19-ae41984e402d.png)
1419,107,507

**Comment by MarjieAVolk** [comment]
Okay, I'm trading at this shop on our dev version here, and not seeing any crashes.  Does it happen every time someone trades at this store?  Or only big trades or just randomly?

**Comment by Arend90** [comment]
to big trades and not enough storage i think

**Comment by Arend90** [comment]
we got it at the bank 2

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/33458352-31d4a500-d626-11e7-9de9-de707f64304e.png)
1248,480

**Comment by Arend90** [comment]
people will get inactivities from trading when there is not enough room

**Comment by MarjieAVolk** [comment]
Yeah still not seeing any issues.  I actually switch to the release branch, so it should be the same as what you are running.  But it's working fine for me, showing an error message right away when I try to trade too many things.  Eg. I traded 1100 huckleberries for 50 pies, got an error message right away.

**Comment by MarjieAVolk** [comment]
I am seeing pretty bad performance on this save though.

**Comment by MarjieAVolk** [comment]
Hey guys, are you still having this problem on 6.2?

**Comment by ClayC90** [comment]
Marjie can you mimic an environment where that has around a dozen people active on the server, doing stuff and then try to use this same shop?

**Comment by stromhurst** [comment]
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC PerformTrade on StoreComponent!

Value cannot be null.
Parameter name: key


Stack:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at Eco.Gameplay.Items.InventoryChangeSet.MoveItemsInternal[TKey](Type itemType, Int32 quantity, Inventory source, Inventory destination, Func`2 sourceStackPredicate, Func`2 sourceStackOrder)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)

Ok on 6.2 release. and got it again!

I dont know if its the same or not... but I was selling 107 stone from a small cart to a shop that I have been selling. I did it like 10 minutes ago too, with the same amount and it worked. this time it messed up. The cart was linked to the shop.

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by stromhurst** [comment]
Oh I should also add, after this bug crash, the player keeps disconnecting due to inactivity error or seomthing. anyone who has used this shop keeps disconnecting due to inactivty till the server restart. The server does warn you once that invalid moving locations of the said item, but when you try a different amount the next time, it doesnt give warning and just crashed after a while. it takes some time to crash with this, its not immediate.

**Comment by Nes112** [comment]
We've been having the same issue on our 6.3.1 server. In this case it is reproducible when either 
A. selling lots of stockpile items at a shop at one time or 
B. selling lots of stockpile items in rapid succession.
We haven't reproduced it with non-stockpile items. However it can be reproduced at any store.

The server has had the same issue as stromhurst describes, where upon logging back in the player cannot interact with inventory at all, crafting is halted, can't pick up anything, but you can still chop trees and mine.

Could be closely related to https://github.com/StrangeLoopGames/EcoIssues/issues/3203. That issue happened on the same 6.3.1 server.

```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC PerformTrade on StoreComponent!

Value cannot be null.
Parameter name: key

Stack:
   at System.Collections.Generic.Dictionary2.FindEntry(TKey key)
   at Eco.Gameplay.Items.InventoryChangeSet.MoveItemsInternal[TKey](Type itemType, Int32 quantity, Inventory source, Inventory destination, Func2 sourceStackPredicate, Func`2 sourceStackOrder)
   at Eco.Gameplay.Items.InventoryChangeSet.MoveItems(Type itemType, Int32 quantity, Inventory source, Inventory destination)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)
```

**Comment by MarjieAVolk** [comment]
Aha... stockpile items /facepalm

**Comment by stromhurst** [comment]
well, with me, i was selling wheat.... Lots of it, like 600 in succession,
so not just stockpile items.

**Comment by MarjieAVolk** [comment]
Trying to repro with stockpile, still seeing good and fast behavior for both success and failure due to not enough room.  :'(

**Comment by metachronism** [comment]
dropping priority due to repro steps
