### ISSUE TITLE
Server Crash with no symptoms experienced

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2937]
Players said they were just basically finishing up game play for the day and had not really been doing anything but shutting down stations.  They said that they were not experiencing and issues and then teh server crashed.  Default configuration on 6.1.1 world

--BEGIN DUMP--
Dump Time
11/28/2017 21:42:42

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Pipes.LiquidComponents.PipeComponent.Tick()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by MarjieAVolk** [comment]
Might this be because of all the non null-checked references to ItemStack.Item.Type?  This is also done freely in LiquidTank despite that stack being initialized to empty.  But that almost seems too obvious.

**Comment by johnkslg** [comment]
probably! fixing

**Comment by johnkslg** [comment]
Fixed I believe
