### ISSUE TITLE
Server crashing during save 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2938]
Default configuration 6.1.1 world

I am sorry if this is a repeat as I know I made a report the last time this happened and there was a Dot Net Zip Tmp file in the storage folder and that zip process was what was keeping Game.eco in use and lead to the crash.   The game would then keep trying to load again but the file is still 'being used.  The only way to fix it is to go into windows services, locate that process and manually kill it to free Game.eco.    Saw this originally happen in 6.0 but it seems to happen more with 6.1 as the game saves get larger.  The game save frequency ins storage.eco is 60 and compression is normal.  Can't seem to determine what is hanging that process up so it does not just complete the archiving pass and the result is that the server crashes

--BEGIN DUMP--
Dump Time
11/28/2017 22:39:02

Exception
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Ionic.Zip.ZipFile.Save()
   at Eco.Core.Serialization.DataStore.ProcessQueue()
   at Eco.Core.Serialization.DataStore.<Run>b__26_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--

**Comment by pamduncan** [comment]
A couple more instances of this happening.  Now on 6.1.2 On a 200X200 dimension world - otherwise all other configurations are default settings:

--BEGIN DUMP--
Dump Time
11/29/2017 19:01:12

Exception
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Ionic.Zip.ZipFile.Save()
   at Eco.Core.Serialization.DataStore.ProcessQueue()
   at Eco.Core.Serialization.DataStore.<Run>b__26_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--

**Comment by pamduncan** [comment]
And on this server updated to 6.1.2 with fresh world, default dimensions and default configurations 

--BEGIN DUMP--
Dump Time
11/30/2017 03:01:06

Exception
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Ionic.Zip.ZipFile.Save()
   at Eco.Core.Serialization.DataStore.ProcessQueue()
   at Eco.Core.Serialization.DataStore.<Run>b__26_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--


This does not see to need a specific world to reproduce but would you like the game saves from these servers?

**Comment by metachronism** [comment]
this wouldn't be a problem with the server - is there some other process running on the machine that tries to get the game.eco file at any point?
