### ISSUE TITLE
6.2.0 - Double key in ChatCommands

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#3043]
An exception is being thrown when commands have the same "key"

--BEGIN DUMP--
Dump Time
12/09/2017 02:02:18

Exception
System.Exception: Caught exception invoking RPC SendChat on ChatManager!

An item with the same key has already been added.

Stack:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Eco.Gameplay.ChatManager.BuildHandlers()
   at Eco.Gameplay.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.ChatManager.SendChat(ChatMessage msg, String text, User user)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__50_0()

--END DUMP--

**Comment by MarjieAVolk** [comment]
Presumably that means the same command name.  You can't add another command using a name that's already taken.  But we could have a better error message here

**Comment by Nanders** [comment]
Yeah, I can probably check this on startup too, and log errors in the serverlog

**Comment by ClayC90** [comment]
Maybe checking authorization levels aswell?

This issue was found because of my /leader conflicting with your /leader,
Mine is accessed by everyone, whilst your is admin only,
The admin only makes you leader, the one I added simply tells you who the leader is.

This sort of functionality should be possible

**Comment by MarjieAVolk** [comment]
I think that's an additional layer of complexity that we don't need to support.
