### ISSUE TITLE
Crash due to file in use by another process

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3151]
This crashing is happening on all of the servers that we currently host and occurs at the time that the backups are configured to run.  The errors are all exactly the same so I am not posting all of them, but they end up causing multiple crashes daily - depending on how often the Backup.eco is configured to run.  

--BEGIN DUMP--
Dump Time
12/16/2017 00:05:24

Exception
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Ionic.Zip.ZipFile.Save()
   at Eco.Core.Serialization.DataStore.ProcessQueue()
   at Eco.Core.Serialization.DataStore.<Run>b__26_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--

**Comment by MarjieAVolk** [comment]
Do you have another program running that is using any of the save files?  For example, do you have a file sitting open in a text editor, or do you have another server running?

**Comment by pamduncan** [comment]
No other app has anything in the server open when this happens.  I found that most of the servers that have had this issue - when we change the compression speed to "BestSpeed" this stopped happening except rarely

**Comment by MarjieAVolk** [comment]
Is this on staging by any chance?  (Wondering if this is the stat database thing again)

**Comment by metachronism** [comment]
changed backup plugin to hours, also didnt see anyhting in the code that would stomp on the file at the same time, still suspect an outside process doing it
