### ISSUE TITLE
6.3 crashing on TechTreeError

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3195]
https://www.dropbox.com/s/bygkha8r1z082k8/Odd%20Crash%20on%206.3.0%20server.zip?dl=0

crash logs and Game.eco in zip file

**Comment by NikkyAI** [comment]
also happinging on 6.3.1

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Eco.Gameplay.Objects.TechTreeVisualizer.MakeImage(String s)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by elfl0rd** [comment]
@D3nnis3n fixed or\and too old issue))

**Comment by D3nnis3n** [comment]
Old issue.
