### ISSUE TITLE
Server Disconnect Upon Transaction at Store

### ISSUE THREAD

**Issue by mrogers6t** [StrangeLoopGames/EcoIssues#3203]
Server, Client or Website? Big Little Planet

Detailed Description of Issue: When I try to buy and sell at stores, it crashes me out of the server.

Reproducible? How difficult is it to reproduce? It is easy to reproduce and it has happened multiple times. 

Steps to reproduce bug/issue: Just buy or sell at a store.

Additional Comments: `Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC PerformTrade on StoreComponent!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Systems.TextLinks.UILinkExtensions.UILink[T](ILinkableParameterized`1 linkable, T param)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)
`

Client Version? 0.6.3.1

**Comment by Quicksilv3r710** [comment]
I've had this happen on my server multiple times.  When it does happen, the server "freezes".  You can join, walk around, but cannot interact with anything. Restart fixes the "freeze".

**Comment by MarjieAVolk** [comment]
Hm, that error message is a little different from similar ones that have been reported.  Still haven't been able to reproduce it though.

**Comment by johnkslg** [comment]
Fixed all possible null uses of UILink in Perform Trade
