### ISSUE TITLE
Caught exception

### ISSUE THREAD

**Issue by RossP28** [StrangeLoopGames/EcoIssues#3232]
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on AuthorizationInventory!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.MoveStacks(ItemStack source, ItemStack destination)
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by metachronism** [comment]
sean fixed this
