### ISSUE TITLE
/giveskillpoints <User>, <amount> throws error when number is too big

### ISSUE THREAD

**Issue by mbenitezmeiss** [StrangeLoopGames/EcoIssues#3236]
999,999,999 is the largest number i was able to get to work. Needs some kinda catch to that, that gives message rather than kicks user from server.

Crash occurred:
--------------------------------------------------------------------------
Caught exception: Caught exception invoking RPC SendChat on ChatManager!
Value was either too large or too small for an Int32.

Stack:
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Eco.Gameplay.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.ChatManager.SendChat(ChatMessage msg, String text, User user)

**Comment by Nanders** [comment]
Fixed all max/min value errors on chat commands
