### ISSUE TITLE
clicking on stats tab kills server

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#3256]
LiteDB.LiteException: Property 'TimeSeconds' was not mapped into BsonDocument.
   at LiteDB.QueryVisitor`1.GetField(Expression expr, String prefix)
   at LiteDB.LiteCollection`1.Max[K](Expression`1 property)
   at Eco.Stats.StatDatabase.<GetDisplayText>b__21_0(String x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Eco.Stats.StatDatabase.GetDisplayText()
   at Eco.Server.UI.ServerMainForm.<>c__DisplayClass8_0.<BuildDisplay>b__0(Object obj2, EventArgs args2) in C:\slg\Eco\Server\Eco.Server\UI\ServerMainForm.cs:line 131
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MarjieAVolk** [comment]
Uh oh.  What is the stats tab?  Is this something on the web page, or in game?

**Comment by MarjieAVolk** [comment]
Oh wait I see, in the server browser
