### ISSUE TITLE
Deleting contract clause throws exception 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3293]
Caught exception invoking RPC Delete on Contract!

Specified argument was out of the range of valid values.
Parameter name: index

Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.RemoveAt(Int32 index)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass14_0.<RemoveAt>b__0()
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Core.Controller.RPCListExtensions.Delete(IContainsRPCList obj, Int32 iList, Int32 iEntry)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by johnkslg** [comment]
Fixed in next PR
