### ISSUE TITLE
Changing clauses on a contract throws an index out of range exception

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3313]
Disconnecting client [reason: Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC ChangeClause on Contract!

Specified argument was out of the range of valid values.
Parameter name: index

Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.RemoveAt(Int32 index)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass14_0.<RemoveAt>b__0()
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Gameplay.Economy.Contracts.ClauseListExtensions.ChangeClause(IClauseList list, Int32 index, String newClauseType)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by johnkslg** [comment]
Fixed in next PR
