### ISSUE TITLE
Placing a Hammer in Repair Station Slot kicks me with Error

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3397]
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on ToolbarInventory!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Skills.RequiresSkillAttribute.get_Description()
   at Eco.Gameplay.Components.RepairComponent.RepairSlotChanged(User user)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by Conchipedia** [comment]
found out it is ONLY the hammer that you get from learning Basic Crafting 1 (which is Still the WRONG hammer)
![snap1067](https://user-images.githubusercontent.com/29383891/34922714-869b529a-f98b-11e7-8742-cea308c6f6dd.png)
and not this one (which i crafted at workbench)
![snap1068](https://user-images.githubusercontent.com/29383891/34922719-9a634b98-f98b-11e7-90dc-f5a158f03a0d.png)
which is perfectly fine placing in Repair Station

**Comment by MarjieAVolk** [comment]
If that's the case, then decreasing the priority on this.  But it should still be able to handle this case.  And also it's still possible to get a regular Hammer via /give

**Comment by Conchipedia** [comment]
just checked and can see its already been changed to Stone Hammer as reward now, the only glitch is the ones already in the world owned by players before fix, it might be possible to either have them removed or swapped over to Stone hammer in next staging if you think its important to do so, will leave that to you
