### ISSUE TITLE
USER ISSUE: Road Tool + Repair Station, Game Crach

### ISSUE THREAD

**Issue by Zaskersky** [StrangeLoopGames/EcoIssues#3485]
**Version:** 0.6.4.0 alpha

**Steps to Reproduce:**
1: Take a road tool,
2: put the road tool in repair slot of repair station
3: game disconects and gives eror message 1,
4: log back into the game, road tool in the Repair station,
5: try to repair it, as its in the slot now, game craches again with error message 2.

**Expected behavior:**
Road tool, should be reparable in the repair table,

**Actual behavior:**
game disconect/crach, error message.

**Error message 1,**
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on ToolbarInventory!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Skills.RequiresSkillAttribute.get_Description()
   at Eco.Gameplay.Components.RepairComponent.RepairSlotChanged(User user)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Error message 2,**
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Repair on RepairComponent!

Value cannot be null.
Parameter name: key

Stack:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Skills.Skillset.GetSkill(Type skillType)
   at Eco.Gameplay.Skills.RequiresSkillAttribute.IsMet(User user)
   at Eco.Gameplay.Components.RepairComponent.Repair(Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by pamduncan** [comment]
I don't believe this was a crash - as no crash log, just and exception log.  The user was probably kicked from the game and mistook that as a crash.  I can verify that these two tools, as well as others that have been posted, do cause random exceptions to occur and kick the player from the game however they are able to get right back in.  Also, while its happening often its not happening all the time that the player is kicked.  Had the exception generate and other then the tool not working or not repairing nothing else happens.

**Comment by Zaskersky** [comment]
Ok, yea its not a crach il next time post it as a exception that made me disconect from the game.

I can vertify myself that i get disconected from the server 10 out of 10 times in a row when trying to repair a Road tool.

I did a seartch in the github and did not find a recent earlyer post of Road tool giving problems that why i posted it.

Yes i can get right back into the game, but that does not solve the problem that a Road tool is not reparable.

And pamduncan, im trying to help here by posting this, so you are aware of the isue's and can fix the problem in time, so the game doesent get released full of bugs/bad programing.
But from the way you react, i'l reconsider being helpfull in future times. As its not apreciated i spend hours of time, unpaid testing the game software. I wish you goodluck with the game. 
But i do not with you a good day as you are a terible person in my opinion, and thats not only based on this 1 reaction, but of feedback of manny others.

**Comment by Arend90** [comment]
Amen to his last past!!!

**Comment by Conchipedia** [comment]
this is linked to
Placing a Hammer in Repair Station Slot kicks me with Error #3397

**Comment by MarjieAVolk** [comment]
@Zaskersky Thank you for helping us test Eco, it is much appreciated.  And of course this is a serious issue.  @pamduncan 's comment was also correct and helpful.  Please be polite, everyone can get what they want here :)

@Conchipedia Thanks for the link; I'm going to leave these issues both open as they are for different tools, but they likely have similar causes.
