### ISSUE TITLE
[6.4] Server will not load and crashes

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3489]
6.4 was installed on server and loaded and ran for several hours before starting to experience one crash after another.  (see Dumps from before hotfix).  Updated server with most current hotfix and while it was converting and/or loading the existing save the save disappeared (?).  Restarted server to allow it to creat new world and it will create the .db files but never creates a saved world and since console no longer runs during world generation process we cannot tell where its stopping.  After a  while it crashes (see dump after hotfix) This will not even create a new world and we cannot figure out why this would be

https://www.dropbox.com/s/v4kqw6wg2a9b1e2/ForrestR_crashes.zip?dl=0

The following are events trigger by the server regarding the server during this tine when it will not build or load

**Comment by pamduncan** [comment]
Faulting application name: EcoServer.exe, version: 1.0.0.0, time stamp: 0x5a3d8c3f
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18666, time stamp: 0x58f33794
Exception code: 0xe0434352
Fault offset: 0x00000000000095fc
Faulting process id: 0x9744
Faulting application start time: 0x01d38fcec2f81489
Faulting application path: D:\TCAFiles\Users\ForrestR\2621\EcoServer.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: eb7413ec-fbc2-11e7-80e0-002590a3d803
Faulting package full name: 
Faulting package-relative application ID:

**Comment by pamduncan** [comment]
Application: EcoServer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException
   at Eco.Core.Serialization.DataStore.Load[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.Action`2<System.__Canon,Eco.Core.Serialization.IPersistent>)
   at Eco.Stats.SimStats..ctor()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, Boolean)
   at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at System.Activator.CreateInstance(System.Type, System.Object[])
   at Eco.Server.PluginManager.AddPlugin(System.Type, System.Object[])
   at System.Threading.Tasks.Task.Execute()

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[], Int32, System.Threading.CancellationToken)
   at Eco.Server.PluginManager.<.ctor>b__8_0()
   at System.Threading.Tasks.Task.Execute()

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[], Int32, System.Threading.CancellationToken)
   at Eco.Server.PluginManager..ctor(System.String)
   at Eco.Server.Startup.Start(System.String[])
   at Eco.Server.MainClass.Main(System.String[])

**Comment by MarjieAVolk** [comment]
Hmmm @metachronism so it is crashing in SimStats constructor?  But that class should no longer exist in this version.

@pamduncan So just going to check this is correct: Originally you were running a migrated world, which worked for a while but then started crashing.  But then you tried to generate a new world and that also crashed?

**Comment by pamduncan** [comment]
@MarjieAVolk  Originally I this servers was running 6.3.1 and which was upgraded to 6.4 apparently successfully on release day and it ran well for about a day then started developing the crashing issues.  Since then to try and get the server running we have reinstalled the server files and generated a new world and it will not generate.  I do have other servers that never had anything but 6.4 on them that are not building worlds either so it maybe that the crashing issue and now the not building issue are two different causes but just happening to the same user.  This server actually belongs to Nes (one of the wiki editors) not sure if he can tell you more about what symptoms in game or not

**Comment by metachronism** [comment]
not seeing a crash withe the same storage files and the latest release.  Can you give it a try with the new hotfix (6.4.1) and reopen if there is still an issue?
