### ISSUE TITLE
[6.4] Server started crashing after restart 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3491]
Server was running normally until about an hour ago.  It is updated to the latest 6.4 hotfix.  It rebooted and started crashing.  Zip inclused world save files and dump files with crash logs.  this was a fresh world created for 6.4 not a converted world

https://www.dropbox.com/s/w0jz8h99lb69g1a/PamelaD_ModTestServer.zip?dl=0

**Comment by pamduncan** [comment]
Addition error occurring in windows event log - 

Faulting application name: EcoServer.exe, version: 1.0.0.0, time stamp: 0x5a601e19
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18666, time stamp: 0x58f33794
Exception code: 0xe0434352
Fault offset: 0x00000000000095fc
Faulting process id: 0x244c
Faulting application start time: 0x01d39084e4500c0c
Faulting application path: D:\TCAFiles\Users\PamelaD\2613\EcoServer.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 24fd9509-fc78-11e7-80e1-002590a3d803
Faulting package full name: 
Faulting package-relative application ID:

**Comment by pamduncan** [comment]
Application: EcoServer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Ionic.Zip.BadReadException
   at Ionic.Zip.ZipEntry.ReadHeader(Ionic.Zip.ZipEntry, System.Text.Encoding)
   at Ionic.Zip.ZipEntry.ReadEntry(Ionic.Zip.ZipContainer, Boolean)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(Ionic.Zip.ZipFile)
   at Ionic.Zip.ZipFile.ReadIntoInstance(Ionic.Zip.ZipFile)

Exception Info: Ionic.Zip.ZipException
   at Ionic.Zip.ZipFile.ReadIntoInstance(Ionic.Zip.ZipFile)
   at Ionic.Zip.ZipFile._InitInstance(System.String, System.IO.TextWriter)
   at Ionic.Zip.ZipFile..ctor(System.String)

Exception Info: Ionic.Zip.ZipException
   at Ionic.Zip.ZipFile..ctor(System.String)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager..ctor(System.String)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at System.Activator.CreateInstance(System.Type, System.Object[])
   at Eco.Server.PluginManager.AddPlugin(System.Type, System.Object[])
   at Eco.Server.PluginManager+<>c__DisplayClass8_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.Execute()

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[], Int32, System.Threading.CancellationToken)
   at Eco.Server.PluginManager..ctor(System.String, System.String)
   at Eco.Server.Startup.Start(System.String[])
   at Eco.Server.MainClass.Main(System.String[])

**Comment by MarjieAVolk** [comment]
Sounds like the same thing as https://github.com/StrangeLoopGames/EcoIssues/issues/3489?

Although you have a different stack trace there, so maybe not

**Comment by metachronism** [comment]
looks like a corrupted zip file
