### ISSUE TITLE
Closing tutorial on first login crashed server

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#3504]
Generated a new world
Hit the x to close the first tutorial that showed up

had a null user in
```
        protected override ThreadSafeAction Subscription    => this.user.UserUI.OnCursor;

   at Eco.Gameplay.Tutorial.UserSubTaskShowCursor.get_Subscription()
   at Eco.Gameplay.Tutorial.UserSubTaskSubscribe.DeInit()
   at Eco.Gameplay.Tutorial.UserSubTaskShowCursor.DeInit()
   at Eco.Gameplay.Tutorial.UserTask.<DeInit>b__28_0(UserSubTask x)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Tutorial.UserTask.DeInit()
   at Eco.Gameplay.Tutorial.UserTaskManager.TaskComplete()
   at Eco.Core.Utils.ThreadSafeAction.Invoke()
   at Eco.Gameplay.Tutorial.UserTask.SkipTask(Player player)
```

**Comment by johnkslg** [comment]
Fixed
