### ISSUE TITLE
Server threw exception, maybe while connecting?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3634]
I think the server would not have crashed from this in the build, since it was in an RPC thing, but got this server exception right as I started unity up, presumably while it was auto-connecting.

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=Eco.Shared
  StackTrace:
   at Eco.Shared.Networking.RPCManager.UnpackArgs(BSONObject bson, MethodInfo[] methods, Object extensionMethodObject, MethodInfo& targetMethod) in C:\Projects\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 233
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result) in C:\Projects\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 188
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname) in C:\Projects\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 167
   at Eco.Core.Controller.ControllerManager.HandleViewRPC(Guid controllerID, String methodname, BSONObject bson) in C:\Projects\Eco\Server\Eco.Core\Controller\ControllerManager.cs:line 333
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson) in C:\Projects\Eco\Server\Eco.Plugins\Networking\Clients\Client.cs:line 390

```

**Comment by MarjieAVolk** [comment]
Just got it again.  'Caught exception invoking RPC ViewRPC on Client!'  Maybe related to disabling auth?

**Comment by MarjieAVolk** [comment]
In fact I am getting it every time right now, so can't run like this O.o  Fortunately I am able to connect far enough to see my generated avatar, which is what I was testing lol

**Comment by MarjieAVolk** [comment]
I am seeing it with auth enabled as usual, it'll happen like a few seconds after I connect, every time O.o
