### ISSUE TITLE
[7.0 staging-e27abc9c] Networking Issues with NAT

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3647]
**When starting server with DetectNAT = True it throws this error**
(Server shows online in game browser but no users can connect)
NAT detect error: Exception of type 'Open.Nat.NatDeviceNotFoundException' was thrown.
Open.NAT Information: 0 : Start Discovery
Open.NAT Information: 0 : Searching for: UpnpSearcher
Open.NAT Information: 0 : Stop Discovery
Open.NAT Information: 0 : Device not found. Common reasons:
Open.NAT Information: 0 : 	* No device is present or,
Open.NAT Information: 0 : 	* Upnp is disabled in the router or
Open.NAT Information: 0 : 	* Antivirus software is filtering SSDP (discovery protocol).

**When starting server with DetectNAT = False** 
(Server shows as offline in game browser)
Server never comes "online" in game browser and no clients are able to connect.

**Comment by Senlarus** [comment]
--BEGIN DUMP--
Dump Time
01/26/2018 08:20:45

Exception
System.Exception: Caught exception invoking RPC EnteringWorld on Player!

Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.RPCManager.DoCall(String methodname, INetObject obj, AwaitedQuery query, INetClient target, Object[] args)
   at Eco.Gameplay.Tutorial.UserSubTaskShowCursor.Init(User user)
   at Eco.Gameplay.Tutorial.UserTask.<>c__DisplayClass28_0.<Init>b__0(UserSubTask x)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Tutorial.UserTask.Init(User user)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Players.Player.EnteringWorld()

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__51_0()

--END DUMP--

**Comment by metachronism** [comment]
man you guys waste no time testing new undocumented features :P

this should be fixed in the next staging
