### ISSUE TITLE
USER ISSUE: 6.4.2 Solo game Putting lumber in stockpile causes game crash

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3657]
Moving lumber form carry slot to stockpile and moving lumber from stockpile to stockpile

Game locks up and then crashes.

Put 10 lumber in carry slot - move to stockpile, it take 4 of the 10 and locks up. when yu try to clikc on anything it then crashes
I cannot repo this in dedi server

Crash report

Dump Time
01/27/2018 00:30:19

Exception
System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state.
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.Modify(Action`1 callback, User user)
   at Eco.Gameplay.Components.StockpileComponent.TryUpdateInventoryFromWorld()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by MarjieAVolk** [comment]
Sorry we didn't ask for this sooner, but do you have a save file where you can repro this?  Or alternatively, do you remember what else was in the stockpile?

**Comment by metachronism** [comment]
could not repro this in 7.0.0
