### ISSUE TITLE
USER ISSUE: Unable to set up contracts

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#3674]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
click on contract board and attempt to set up any contract

**Expected behavior:**
I should be able to select targets and clause also select target player for contract

**Actual behavior:**
any attempt to modify setup or type in any of the fields causes the client to crash to server select screen also cannot select who contract is owned by name contract or select clauses

Error message received
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC ChangeClause on Contract!

Specified argument was out of the range of valid values.
Parameter name: index

Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.RemoveAt(Int32 index)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass12_0.<RemoveAt>b__0()
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Gameplay.Economy.Contracts.ClauseListExtensions.ChangeClause(IClauseList list, Int32 index, String newClauseType)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by MillanAireson** [comment]
For me the Contract board comes up and when I click the "Create Contract" button the next window where you create the contract appears partially off the top of the screen.  No apparent way to move it down.  The first line I see is: Source....  Everything above that is cut off.  You can't appear to complete the contract.  When you escape out of it, it apparently leaves an unfinished contract behind that you can no longer get to, but if you attempt to create another one you get an error that says, "Contract 'Unnamed Contract" is invalid, must fix, or delete before posting another one."  The only way around this appears to be picking up the contract board itself which I guess cancels out the pending contracts.

**Comment by Spaceferret42** [comment]
I have also noticed that version of the bug but discovered a work around is that if you try resizing the window it reveals itself. i also noticed that the offscreen bug appears fixed in 0.6.4.2

**Comment by Spaceferret42** [comment]
I noticed that this has been fixed in 7.0.5

**Comment by johnkslg** [comment]
Fixed!
