### ISSUE TITLE
USER ISSUE: Kicked from server when attempting to ban

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3702]
**Version:** 0.7.0.0 beta staging-a5db4bb6

**Steps to Reproduce:**
Typed ban command
/ban Usernamehere, Just testin', no hard feelin's broski

**Expected behavior:**
Banned him

**Actual behavior:**
Kicked from server
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.

Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

**Comment by Nanders** [comment]
@Senlarus What was the username you were trying to ban?

It wouldn't have happened to be a Dummy, would it?

**Comment by Senlarus** [comment]
It was crazykitty

**Comment by Nanders** [comment]
I got this fixed
