### ISSUE TITLE
USER ISSUE: Fir Tree i can chop down and split up but cannot collect pieces

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3712]
**Version:** 0.7.0.0 beta staging-7da08558

**Steps to Reproduce:**
chop down a fir tree, chop fallen tree into pieces

**Expected behavior:**
allowed to pickup what i have chopped

**Actual behavior:**
kicks me with this error:

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by ty2u** [comment]
Getting the same thing in **Version:** 0.7.0.0 beta staging-e983511d

Figured I should probably just post that here instead of making a new issue.
