### ISSUE TITLE
USER ISSUE: Cactus broken

### ISSUE THREAD

**Issue by LucianoBradley** [StrangeLoopGames/EcoIssues#3734]
**Version:** 0.7.0.0 beta staging-71fcbff4

**Steps to Reproduce:**
Chop down a cactus and pick it up

**Expected behavior:**
Kicked from server

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by craig-jong** [comment]
fixed alongside other new trees
