### ISSUE TITLE
Meteor Plant exception

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#3799]
after meteor impact, small meteors still falling
```
System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs:line 2155
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs:line 3189
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Parallel.cs:line 1287
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Parallel.cs:line 2241
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body) in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Parallel.cs:line 1674
   at Eco.World.WorldPlugin.Run() in C:\slg\Eco\Server\Eco.World\WorldPlugin.cs:line 89
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 954
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 902
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 891
   at System.Threading.ThreadHelper.ThreadStart(Object obj) in f:\dd\ndp\clr\src\BCL\system\threading\thread.cs:line 93

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.

   at Eco.Simulation.PlantSim.KillPlant(Plant plant, DeathType deathType, Boolean applyToWorldLayer)
   at Eco.Simulation.PlantSim.DestroyPlant(Plant plant, DeathType deathType, Boolean applyToWorldLayer)
   at Eco.Gameplay.Plants.PlantBlock.Tick(Vector3i worldPosition)
   at Eco.World.PersistentChunk.Tick()
   at Eco.World.WorldPlugin.<>c__DisplayClass24_0.<Run>b__0(PersistentChunk chunk)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
```

**Comment by metachronism** [comment]
fixed
