### ISSUE TITLE
Server crash- Staging 05b7abef

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3805]
My server is unable to recover from this crash, every time I start it up it crashes again.

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.WorkOrder.set_UncraftedQuantity(Int32 value)
   at Eco.Gameplay.Items.WorkOrder.UpdateCrafted()
   at Eco.Gameplay.Items.WorkOrder.set_Progress(Double value)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders(Single dtime)
   at Eco.Gameplay.Components.CraftingComponent.Tick()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by Senlarus** [comment]
Turns out someone was crafting a waterwheel and every time it finishes the server crashes

**Comment by metachronism** [comment]
Do you have the save perchance?  Just crafted a waterwheel without issue as a test, something else must be going on

**Comment by MarjieAVolk** [comment]
Looks like the same stack trace as this one: https://github.com/StrangeLoopGames/EcoIssues/issues/3804

Closing as duplicate.  If you have game save and/or more certain repro steps, please shared on that one
