### ISSUE TITLE
Staging Issue + Crashes - Issues with Mechanics Skill

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3808]
When you spec into Mechanics you cannot learn the first item in the tree. When you attempt to unlearn Mechanics, you get kicked and the game crashes. DUMP below image.
![image](https://user-images.githubusercontent.com/1503963/35761584-38dd19c2-0858-11e8-84fc-617426563e80.png)

--BEGIN DUMP--
Dump Time
02/02/2018 17:25:38

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC AbandonSpecialty on MechanicsSkill!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Skills.Skill.AbandonSpecialty(Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()

--END DUMP--

**Comment by Senlarus** [comment]
I think I have more information... In the new 7.0.0 Beta build starting a fresh server this skill works just fine. The only issue is when an existing server has a player that has read the skill scroll PRIOR to the change to how the mechanics tree was laid out. Anyone who read the page before hand cannot spec into the first skill because it wasn't there to be "unlocked" when they read the page beforehand. I suspect I could adjust this player data in the database file but I cannot open it with any SQLite tools, probably because it's encrypted. There is also not an admin command to UNLEARN all skills, which would be handy in this situation.

**Comment by Senlarus** [comment]
Here's the save file.
https://1drv.ms/u/s!AtWN_MtzJ9-Gy0WIj6OlIzGwFd1E

**Comment by MarjieAVolk** [comment]
Hm I can't even load that save file :'(

**Comment by Senlarus** [comment]
You should be able to repro by loading an old staging before the mechanics changes, learning mechanics, then upgrading to a newer staging version.

Brandon

**Comment by MarjieAVolk** [comment]
Fixed, will be available in next hotfix (should be released today, possibly tomorrow)
