### ISSUE TITLE
Disconnect exception

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3966]
1) queue up 5 hewn log orders at a workbench
2) let them all finish
3) with logs in hand, try to place them into the table (right click)
4) client gets disconnected with error

--BEGIN DUMP--
Dump Time
02/05/2018 21:08:13

Exception
System.Exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.BlockItem.OnActRight(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()

--END DUMP--

**Comment by MarjieAVolk** [comment]
ooh sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/3906

**Comment by MarjieAVolk** [comment]
Hm these steps were still not enough to repro it.

**Comment by MarjieAVolk** [comment]
So, we've had two reports of this.  Both times it was right clicking on a table with a block item in hand.  BlockItem.OnActRight returns no op immediately if context.HasBlock is false (and that block is the targeted block in the world), so I'm presuming what's going on is that the context is inaccurately providing a targeted block.

**Comment by MarjieAVolk** [comment]
HasBlock checks BlockPosition and not Block, so possibly it is providing a BlockPosition with no Block

**Comment by MarjieAVolk** [comment]
OMG I got it.  This is the weirdest bug ever.  You have to be holding seeds and targeting the top side of the table in order to do it.  It's because of a recent change in SeedItem that edits the context object
