### ISSUE TITLE
Singleplayer is crashing on some users machines 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#4002]
--BEGIN DUMP--
Dump Time
02/06/2018 20:35:12

Exception
System.IO.IOException: the handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Eco.Core.Utils.TimedTask..ctor(String taskName, Boolean reportOnSameLine)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

People get this error when creating a singleplayer world .

Deleting and generating a fresh world is also not working ..
For some it takes a few minutes for other the server crashes the same time they try to start a new world (no file created ) There seems to be maybe a pathing issue with the server or so when its run via the game ? on all machines i tested i worked perfectly to run the server manually

**Comment by guitarlix** [comment]
Yes, please help!  I have the exact same problem with the exact same dump.  running windows 10

**Comment by metachronism** [comment]
this should be fixed in 7.2
