### ISSUE TITLE
Creating an election crashes server

### ISSUE THREAD

**Issue by magnehg** [StrangeLoopGames/EcoIssues#4180]
When i try to start an election, server crashes. 

--BEGIN DUMP--
Dump Time
02/09/2018 15:11:55

Exception
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Election.GetVotingRounds(Boolean forceEnd)
   at Eco.Gameplay.Election.ApplyIfFinished(Boolean forceEnd)
   at Eco.Gameplay.Legislation.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by stormoffires** [comment]
are elections disabled in 7.1? i keep getting an error in the server when i try to run.
![2018-02-12](https://user-images.githubusercontent.com/20627148/36130430-06cc91e0-102a-11e8-9bad-762c5c2d58bd.png)

**Comment by MarjieAVolk** [comment]
They shouldn't be disabled, no.  The error message from your screenshot has a fix.  It should be rolled out soon.

**Comment by MarjieAVolk** [comment]
Okay, sorry I've taken so long to get around to this.  But I haven't been able to repro this problem.  Have you seen it since you reported it?  I imagine you don't still have the save file where this happened.

**Comment by MarjieAVolk** [comment]
Well, haven't seen anybody else with this problem in all this time, so closing as no repro for now.  If you see it again and/or get a save file that does it, let me know.
