### ISSUE TITLE
Server crashes on startup after installing 7.0.6

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#4207]
No mods, updated and started it up, and it worked OK. Went to restart it 2 minutes later, and upon startup this happens, here is the dump file.
[Crash AggregateException 02091952.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1712817/Crash.AggregateException.02091952.txt)

**Comment by Quicksilv3r710** [comment]
7.0.7 has the same crash.

**Comment by Quicksilv3r710** [comment]
If needed, I can provide the game.eco file as well.

**Comment by knexer** [comment]
It might be an issue with contracts serialization introduced in 7.0.6, should've been fixed in 7.0.7.  Can you try deleting the Economy folder inside your save (make a backup first!)?  If it is the contracts issue, the save should load fine, with all your contracts and currencies gone.

**Comment by MarjieAVolk** [comment]
I was just talking with DrHardware in discord, so he is doing that now

**Comment by knexer** [comment]
If that does fix your issue, we'd appreciate your game.eco file, so we can dig into the issue more.

**Comment by MarjieAVolk** [comment]
I am now in posession of the save file.  Apparently deleting the Economy folder eliminated the reported issue but then there was another issue

**Comment by Dr-Hardware** [comment]
This one?

<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC ShouldSelectUser on Client!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Plugins.Networking.Clients.Client.ShouldSelectUser()

**Comment by Dr-Hardware** [comment]
Found a SLG only user is able to connect, but i can't from either steam or SLG>

**Comment by Quicksilv3r710** [comment]
We fixed the issue. DrHardware knows more about the inner workings than me, so if your curious ask him.  I know he has thanked you already, but I really appreciate the time you guys put into getting my world working again =) thank you VERY VERY much.

**Comment by MarjieAVolk** [comment]
Okay I will follow up with DrHardware tomorrow to see what we need to fix.
