### ISSUE TITLE
[Server Bug] 

### ISSUE THREAD

**Issue by csalajan** [StrangeLoopGames/EcoIssues#4294]
```
[42:29] Disconnecting client [reason: Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
]...
```

We haven't figured out what exactly is causing this, but it has happened twice in 2 days on our server. When it happens, it doesn't crash the server, but it does kick everybody currently connected to it off.

this is on version 7.0.8

**Comment by MarjieAVolk** [comment]
I have seen someone else give a similar error message.

This should be related to a specific action done with right click, left click, or E; such as picking up or placing something, harvesting a plant, opening a UI.  If you could determine what the person was in the middle of doing when they get this error, that would help us find the problem a lot faster.

**Comment by MarjieAVolk** [comment]
Closing as duplciate of https://github.com/StrangeLoopGames/EcoIssues/issues/4222

I realized I was being a little silly, as I can see in the trace you were opening a crafting station window.  I have some leads on this now.
