### ISSUE TITLE
USER ISSUE: item transfer bug

### ISSUE THREAD

**Issue by celtbane** [StrangeLoopGames/EcoIssues#4300]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
tried to transfer a stack of iron ore to an empty stockpile right next to the one it was in. (Transfer threw inventories)

**Expected behavior:**
ore moved

**Actual behavior:**
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on AuthorizationInventory!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.AuthorizationInventory.CanMoveItems(ItemStack toMove, Boolean taking, User user)
   at Eco.Gameplay.Items.Inventory.CheckAuthForMove(ItemStack source, ItemStack target, User user)
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by MarjieAVolk** [comment]
Haven't been able to repro this.  It looks like one of these stockpiles may be in a bad state.  Do you happen to still have the save file where this happened?  Have you seen it happen more than once?

**Comment by MarjieAVolk** [comment]
Closing as no repro for now - there were some other inventory fixes recently, so it might already be fixed.
