### ISSUE TITLE
USER ISSUE: Exception on putting items into storage

### ISSUE THREAD

**Issue by TropicalTeabag** [StrangeLoopGames/EcoIssues#4312]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. relog
2. try put Stoen mason in storage box No.3 
3. Cry myself to sleep

**Expected behavior:**
Place things in my Storage containers and get on with the game play... Hope my progress didn;t get lost 

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on LimitedInventory!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

```

**Comment by MarjieAVolk** [comment]
Should be fixed in 7.2.3, let us know if you see it again.
