### ISSUE TITLE
USER ISSUE: Client crash when attempting to repair

### ISSUE THREAD

**Issue by theb33rm4n** [StrangeLoopGames/EcoIssues#4358]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
put in iron hoe to fix
hit repair without anything else inputted besides the iron hoe

**Expected behavior:**
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Repair on RepairComponent!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.Inventory.TryRemoveItems(ItemStack stack, User user)
   at Eco.Gameplay.Components.RepairComponent.Repair(Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Repair on RepairComponent!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.Inventory.TryRemoveItems(ItemStack stack, User user)
   at Eco.Gameplay.Components.RepairComponent.Repair(Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

```

**Comment by MarjieAVolk** [comment]
I believe this is related to not having any of the crafting material in your inventory.

**Comment by metachronism** [comment]
verified as working in 7.2
