### ISSUE TITLE
7.1 (and 7.1.2) Server crashed

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#4368]
![2018-02-11 2](https://user-images.githubusercontent.com/20627148/36080836-d98e067c-0f53-11e8-8a29-ced527dfd4f2.png)

**Comment by TekPK** [comment]
I've been getting this as well...

--BEGIN DUMP--
Dump Time
02/11/2018 19:46:53

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by stormoffires** [comment]
3 crashs in the last 4 hours from the update...

**Comment by stormoffires** [comment]
--BEGIN DUMP--
Dump Time
02/11/2018 19:22:22

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Objects.RubbleObject.get_Active()
   at Eco.Shared.Networking.NetObjectManager.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()

--END DUMP--

**Comment by stormoffires** [comment]
another crash..

--BEGIN DUMP--
Dump Time
02/11/2018 19:35:12

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Simulation.WorldLayers.WorldLayerManager.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()

--END DUMP--

--BEGIN DUMP--
Dump Time
02/11/2018 19:35:12

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by Last2Night** [comment]
Windows Server 2016. 2 crashes in less than 12 hours period.


--BEGIN DUMP--
Dump Time
02/13/2018 05:37:36
Exception
System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
at System.Collections.Immutable.ImmutableList1.Node.RemoveAll(Predicate1 match)
at System.Collections.Immutable.ImmutableList1.RemoveAll(Predicate1 match)
at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
at Eco.Core.Controller.ControllerManager.Run()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart(Object obj)
--END DUMP--

--BEGIN DUMP--
Dump Time
02/13/2018 15:09:22
Exception
System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
at System.Collections.Immutable.ImmutableList1.Node.RemoveAll(Predicate1 match)
at System.Collections.Immutable.ImmutableList1.RemoveAll(Predicate1 match)
at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
at Eco.Core.Controller.ControllerManager.Run()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart(Object obj)
--END DUMP--

**Comment by stormoffires** [comment]
Same as Last2Night.

**Comment by Blanclour** [comment]
Continuing to lose a steady stream of players to this specific bug.

**Comment by Blanclour** [comment]
Players are using this bug to excessively duplicate resources.

**Comment by Blanclour** [comment]
I've been telling myself not to do this, but the amount of rage this is causing on my server is unbelievable. It has been several days since the developers have given us any updates on how the patching is going and it is infuriating everybody. Please I beg of you devs, at least give us a shred of hope. The crashes have been happening every 5-15 minutes during peak times and every 30 minutes to an hour for other times. We need some kind of fix soon.

**Comment by Quicksilv3r710** [comment]
I'm also getting the ecoserver.exe not responding bug, seems to happen randomly. Same with this one im going to link. The more people that are on the more it crashes with this exception. Everytime I update my server, it crashes at least 2 or 3 times with the aggregate error before it decides to work. Everytime I update/restart the program I feel like I'm taking a gamble lol. 
[Crash AggregateException 02174142.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1734325/Crash.AggregateException.02174142.txt)

**Comment by Blanclour** [comment]
The chair and table duplication that players are using on my server is getting outrageous. Not to mention rebuilding and re-digging countless combined hours of work due to this crash, devs please fix soon.

**Comment by Quicksilv3r710** [comment]
Yea I think I lost about half my population, used to be about 25 people a day, now im lucky if i get 10 people. The only ones that stayed are the ones that joined my discord and are "in the know". I've set backups to every 10 minutes for now, its all I can do.

**Comment by Blanclour** [comment]
Players are now expecting the crashes, and mass duplicating furniture with it. I have never heard of a game developer company that waited this long to fix a critical bug.

**Comment by stormoffires** [comment]
these new steam servers make me laugh... these bugs and crashes are not new... the game is in its early development still and server population will fluctuate about as fast as Bitcoin. I have heard of pretty much every developer in the industry taking their time to fix critical bugs so dont fret over it. These devs are working hard to correct these issues.

If you are getting crashes at 5-15 min intervals then this might be a bigger issue. On average we only crash 7 to 10 times a day, with no loss of work. (yes we are seeing the dupeing issue tho) Our peak is 40-50 players and low is 5-10. 

if your crashes are forcing hours of work to be repeated you have other issues going on. I have been a server host for almost 2 years now with ECO, and have had our server featured in PAX2017. You knew what you where getting into when you bought the game, be happy to have even 10 people on, there was a time 5-6 was normal for a busy server. 

also if you are going to post here complaining, at least post your logs if they are different then the above ones.

**Comment by Blanclour** [comment]
@stormoffires I run a tier 1 killservers.com server, the crashes come at random intervals between 5 minutes and 2 hours. I apologize for my other comments on this post, I am simply happy that someone has responded. It can be very frustrating when everyone on my server is complaining about losing their work and when I lose my own work as well. Here is my crash dump, if there are any recommendations on modifying my server configuration to increase stability I would be immeasurably thankful.

--BEGIN DUMP--
Dump Time
02/08/2018 23:03:47

Exception
System.Exception: Caught exception invoking RPC PlayerInteract on Player!

Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()

--END DUMP--

**Comment by Blanclour** [comment]
This is a screenshot of the dumps my server created for today alone:
![capturelist](https://user-images.githubusercontent.com/2582909/36355330-202fa222-14a7-11e8-9183-f6a71b75b919.PNG)

**Comment by Quicksilv3r710** [comment]
I was in no way bitching, and am simply relaying information to the devs so they can fix the issues. and BTW, im not a "steam server". I've existed for 8 months before the game launched on steam. Don't know why you feel the need to attack me personally.

**Comment by MarjieAVolk** [comment]
I'm hearing from multiple people that this is somehow related to a corrupted world object.  As a workaround, people who are seeing this error might be able to doctor their save by deleting objects from it until it goes away >>

**Comment by Blanclour** [comment]
I started a new world and learned something about this bug. It starts out nonexistent, but as people develop the server it becomes more and more frequent. Could be debris, perhaps carts. I don't know how to tell which class of object it's related to. However it is definitely something produced by the players as they either harvest or craft.

**Comment by metachronism** [comment]
the original posted issue should be fixed in 7.2
