### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by hoiikmaak** [StrangeLoopGames/EcoIssues#4450]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC SetWorking on Avatar!

Value cannot be null.
Parameter name: key


Stack:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Shared.Utils.DictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dict, TKey key)
   at Eco.Core.Controller.ControllerManager.NotifyChanged(IController controller, String name)
   at Eco.Gameplay.Players.Avatar.SetWorking(Boolean working)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

```

**Comment by SlayksWood** [comment]
Seems fixed.
