### ISSUE TITLE
USER ISSUE: Caught exception invoking JobFinished on Contract

### ISSUE THREAD

**Issue by Komorek94** [StrangeLoopGames/EcoIssues#4592]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**
I was try finish contract

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC JobFinished on Contract!

Value cannot be null.
Parameter name: source


Stack:
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Utils.PickerTracker.Test()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Economy.Contracts.ContractClauseNested.Test(User contractor, User client)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Eco.Core.Utils.ResultExtensions.Merge(IEnumerable`1 list)
   at Eco.Gameplay.Economy.Contracts.Contract.JobFinished(Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

```

**Comment by johnkslg** [comment]
There have been a lot of contract fixes, this is probably fixed. Havent seen it in lots of recent testing.  If you can still make it happen reopen, and more details about the contract would be helpful. Thanks for the bug report!
