### ISSUE TITLE
USER ISSUE: Server Crash

### ISSUE THREAD

**Issue by yankeejim** [StrangeLoopGames/EcoIssues#4736]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
--BEGIN DUMP--
Dump Time
02/17/2018 14:27:44
 
Exception
System.Exception: Caught exception invoking RPC SetTag on ChatManager!
 
Object reference not set to an instance of an object.
 
 
Stack:
   at Eco.Gameplay.Systems.Chat.ChatManager.SetTag(ChatTagSetting chatTagSetting, Int32 playerID)
 
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()
 
--END DUMP--

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Well, okay so SetTag is related to choosing which chat channel/tag you are looking at/talking into.  This could be either via clicking the buttons in the tags panel on the chat log, or by entering eg. '#Chat abc' into chat, which would switch you to the #Chat channel.

I have been playing with fancy chat stuff, and changing channels, and haven't seen anything yet.

One thing I'm wondering is maybe this is related to clicking on a player's name?  Doing so will switch you to a PM channel with that person.  If they have a name with special characters or something, maybe it throws.  I tried it with a few special characters, but no dice so far.

**Comment by mirasrael** [comment]
Should be fixed in 8.2. Please re-open if still a case.
