### ISSUE TITLE
Server Crash Log

### ISSUE THREAD

**Issue by yanphi** [StrangeLoopGames/EcoIssues#4790]
--BEGIN DUMP--
Dump Time
02/19/2018 00:39:10

Exception
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.LegislationSystem.Districts.GetDistrictAt(WorldPosition3i position)
   at Eco.Gameplay.Stats.PlayerActionExtensions.SetPosition(IHasPositionContext action, WorldPosition3i position)
   at Eco.Gameplay.Stats.PlayerActionManager1.CreateTypedDefaultAction(User user)
   at Eco.Gameplay.Stats.ConcretePlayerActions.PolluteAirPlayerActionManager.CreateAction(User user, AirPollutionComponent obj, Single value)
   at Eco.Gameplay.Components.AirPollutionComponent.Tick()
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

Not too sure what the problem is.

**Comment by MarjieAVolk** [comment]
Fixed in next hotfix.

**Comment by ljej1989** [comment]
.



Sent from my Samsung Galaxy smartphone.

-------- Original message --------
