### ISSUE TITLE
USER ISSUE: Exception when killing an animal

### ISSUE THREAD

**Issue by KrasinMech** [StrangeLoopGames/EcoIssues#4860]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Hunting

**Expected behavior:**
Hunting

**Actual behavior:**
```
Caught exception: Caught exception invoking RPC Hit on ArrowEntity!

Object reference not set to an instance of an object.


Stack:
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Simulation.Agents.Animal.Damage(Single amount, DeathType damageSource)
   at Eco.Gameplay.Animals.AnimalEntity.TryApplyDamage(INetObject damager, Single damage, InteractionContext context)
   at ArrowEntity.Hit(NetObjAttachInfo hitAttachInfo, Vector3 position)

```

**Comment by MarjieAVolk** [comment]
This reported trace looks like the same bug, but is slightly different (it's from a server crash):

```
Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Simulation.Agents.Animal.Damage(Single amount, DeathType damageSource)
   at Eco.Simulation.WorldLayers.Layers.AnimalLayer.DamageAnimals(Vector2i layerPos, Single maxDamage)
   at Eco.Simulation.WorldLayers.Layers.AnimalLayer.Push(Vector2i layerPos)
   at Eco.Simulation.WorldLayers.Layers.AnimalLayer.Push()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Simulation.WorldLayers.WorldLayerSync.<>c.<Tick>b__11_5()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerSync.Tick()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Tick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.TryTick()
   at Eco.Simulation.WorldLayers.WorldLayerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
```

**Comment by MarjieAVolk** [comment]
Similar thing reported with AnimalTrapComponent as well

**Comment by MarjieAVolk** [comment]
Another very similar trace:

```
Caught exception:

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.SendInitialState(BSONObject obj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by SeanAtr0n** [comment]
Fixed next hotfix (hopefully... couldn't actually reproduce it)
