### ISSUE TITLE
SERVER ISSUE: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by LotheronPrime** [StrangeLoopGames/EcoIssues#4865]
Dedicated server on local network to me: my client was receiving notifications that people were disconnecting and reconnecting immediately.  They did not realize this was happening but it showed up in my chat log.  

I could continue performing actions and so could other users but they could not connect at some point.  I checked the server and then saw the error with dump below:  

`--BEGIN DUMP--
Dump Time
02/19/2018 16:47:18

Exception
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Minimap.MinimapManager.GetChangesSince(ChunkMap chunkMap, Double time, String valueTypeName)
   at Eco.Gameplay.Minimap.MinimapManager.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()

--END DUMP--`

Had to force stop EcoServer.exe and everyone rolled back about 3 minutes. Unfortunately, no one knows what actions they were performing as none were out of the ordinary might have caused this.

**Comment by MarjieAVolk** [comment]
So the server crashed and didn't disconnect people huh?  That's odd.

**Comment by LotheronPrime** [comment]
That is correct. I will still able to perform actions but they were obviously not saved since the server crashed.  No one knew they ere disconnected until I noticed the Error.. was about two minutes or so trying to figure out what was going on. Four of us playing were all on discord.  Was very strange indeed.

**Comment by MarjieAVolk** [comment]
Here is a save file that apparently repros this very frequently: https://drive.google.com/open?id=1LGJVn32BqUlSZJX4NIgh-bP4hI0SZPww (@Amphysbaenas)

**Comment by metachronism** [comment]
fixed
