### ISSUE TITLE
Server Crash: PersistentChunk.Tick

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4873]
"Something unknown happened to make the server crash. Upon a few seconds after server restart (after the server was technically fully loaded, and the server browser was brought up), the following error is thrown-

```
Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.World.PersistentChunk.Tick()
   at Eco.World.WorldPlugin.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

 This happened every time the server was restarted, as well as when a copy of the save was moved to a different computer and was tested over there. 

 The server was rolled back by 9-10 hours and allowed to run for 10+ hours and the error has not recreated itself yet.
 
 The game.eco file can be downloaded here - https://www.dropbox.com/s/337o9jkposwfis0/Game.eco?dl=0
 Head's up, it's a 388 MB file for a 200x200 world."

**Comment by metachronism** [comment]
should be fixed
