### ISSUE TITLE
7.1.2 Ecotopia server crash every 5-15 min

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#4955]
`--BEGIN DUMP--
Dump Time
02/22/2018 20:47:00

Exception
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Minimap.MinimapManager.GetChangesSince(ChunkMap chunkMap, Double time, String valueTypeName)
   at Eco.Gameplay.Minimap.MinimapManager.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()

--END DUMP--`

**Comment by Amphysbaenas** [comment]
`--BEGIN DUMP--
Dump Time
02/22/2018 20:47:07

Exception
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Minimap.MinimapManager.GetChangesSince(ChunkMap chunkMap, Double time, String valueTypeName)
   at Eco.Gameplay.Minimap.MinimapManager.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()

--END DUMP--`

**Comment by Amphysbaenas** [comment]
`--BEGIN DUMP--
Dump Time
02/22/2018 20:47:11

Exception
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Minimap.MinimapManager.GetChangesSince(ChunkMap chunkMap, Double time, String valueTypeName)
   at Eco.Gameplay.Minimap.MinimapManager.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()

--END DUMP--`

**Comment by Amphysbaenas** [comment]
`--BEGIN DUMP--
Dump Time
02/22/2018 20:47:11

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()

--END DUMP--`

**Comment by Amphysbaenas** [comment]
`--BEGIN DUMP--
Dump Time
02/22/2018 20:47:13

Exception
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Minimap.MinimapManager.GetChangesSince(ChunkMap chunkMap, Double time, String valueTypeName)
   at Eco.Gameplay.Minimap.MinimapManager.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()

--END DUMP--`

**Comment by Amphysbaenas** [comment]
`--BEGIN DUMP--
Dump Time
02/22/2018 20:47:13

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Disasters.MeteorObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(List`1 newObjects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_1()

--END DUMP--`

**Comment by Amphysbaenas** [comment]
`--BEGIN DUMP--
Dump Time
02/22/2018 20:47:13

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--`

**Comment by Amphysbaenas** [comment]
My last 12 hours dump folder ...
![image](https://user-images.githubusercontent.com/29807119/36561397-e2732448-1813-11e8-8001-1b9881533e61.png)

**Comment by Amphysbaenas** [comment]
direct link to save and dump folder:
https://drive.google.com/open?id=1LGJVn32BqUlSZJX4NIgh-bP4hI0SZPww

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4865.  Copying your save file link over there.

Unfortunately I can't tell you yet what is wrong
