### ISSUE TITLE
USER ISSUE: Kicked from Game when running commands as admin

### ISSUE THREAD

**Issue by SirusX** [StrangeLoopGames/EcoIssues#5018]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Log into server as an admin
2. type any command into chat. /help for example

**Expected behavior:**
Command should run

**Actual behavior:**
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Value cannot be null.
Parameter name: key

Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

**Comment by SirusX** [comment]
Discovered issue: Somehow an old version of the AdminUtils Mod was installed on the server. The version installed was 7.0.8 while our server was 7.1.2. After installing the correct AdminUtils mod, the issue has corrected itself. 

This may be noted for any others having this issue when running any command as an admin.
