### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by ronniek09** [StrangeLoopGames/EcoIssues#5163]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Error converting value 12 to type 'Eco.CTK.Logs'. Path '', line 1, position 2.
Could not cast or convert from System.Int64 to Eco.CTK.Logs.


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

```

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/4391
