### ISSUE TITLE
USER ISSUE: Picking up a log from cut down tree

### ISSUE THREAD

**Issue by psaul3** [StrangeLoopGames/EcoIssues#5186]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Try to pick up a log?

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668
