### ISSUE TITLE
Player unable to pay tax, crashes server

### ISSUE THREAD

**Issue by SalaMAD123** [StrangeLoopGames/EcoIssues#5187]
When a player has to pay tax from a law and don´t have enough currency on him the server crashes, see copy pasted crash dump bellow.

--BEGIN DUMP--
Dump Time
02/27/2018 19:08:29

Exception
System.Exception: You were prevented from playing on this server: <style="Error">Cannot violate law <b><link="Law:5c2c3131-1bf3-428a-b5dd-260194acdf2a">Pro Food Reform</link></b></style>: Undomesticated Genie cannot afford to pay a tax of <b><link="Currency:94df9e98-e999-4974-9911-982a42f6be81"><style="Currency">2 Snuggle Bunnies</style></link></b>
   at Eco.Gameplay.Players.User.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Gameplay.Players.UserManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by MarjieAVolk** [comment]
Fixed in the next staging build (and the next release)
