### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by alex1412108** [StrangeLoopGames/EcoIssues#5197]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
start game
press continue

**Expected behavior:**
start up world (local)

**Actual behavior:**
upon loading plants reaching 100% the window minimizes, when i go back to the game window it says:
Connection Failed

additional note: can load into a newly created local world, just not the one i made a few days ago. last logged into the world yesterday

**Comment by MarjieAVolk** [comment]
Can you try loading your world again, and then afterwards attach your client log file ('C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt') and any crash dump files in  '[...]\steamapps\common\Eco Server'?

Others who had a similar problem found that using the Eco Server tool to run their server worked for them.  You might also check for a firewall / antivirus confirmation popup.  Still trying to figure this one out.

**Comment by MarjieAVolk** [comment]
Closing due to no response.

**Comment by alex1412108** [comment]
Sorry for the delay, went on holiday before getting a response and just got back. Here is the output log: 
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1787257/output_log.txt)
and a crash file I found in *\Eco\Eco_Data\Server\Dump:
[Crash AggregateException 03070758.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1787349/Crash.AggregateException.03070758.txt)

Ive been able to start a server using the server tool (both in the *\steam\steamapps\common\Eco\Eco_Data\Server and through the steam tools interface) but im not sure how to choose the world file that gets used for this (it created a new world in *\Server\Storage called game).

**Comment by MarjieAVolk** [comment]
No problem, I was just closing things in a frantic attempt to keep track of what we needed to do :P  To load an existing game with the server tool, I believe you will actually just have to copy the save file in there and rename it to "Game.eco" (like the one that it autogenerated).

Thanks for the crash dump, looks like that is indeed your problem, since the output log also shows the server stopping while loading plants.  So I am guessing the server tool will not open this save file either, but you can still give it a try.  Since it looks like the save file is corrupted, could you send the save file over?

I could have sworn we had another bug with this same stack trace, but can't find one.

```
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error(s) occurred when loading Plants
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.Simulation.PlantSim..ctor()
   at Eco.Simulation.EcoSim.Initialize()
   at Eco.Simulation.EcoSim..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_3()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error(s) occurred when loading Plants
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.Simulation.PlantSim..ctor()
   at Eco.Simulation.EcoSim.Initialize()
   at Eco.Simulation.EcoSim..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_3()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by alex1412108** [comment]
Np, makes sense. yeah, i tried it with the server tool and renaming the save file to Game.eco and it didnt work. Here is the game save file, though i did have to tag it as .txt for github to take it. Let me know if there is a better way to send it.
[test.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1791039/test.txt)

**Comment by alex1412108** [comment]
any hope for the save file or should I give up on it and try the backups?

**Comment by MarjieAVolk** [comment]
Hm, looks like I can't run your save file at all.  Like it's not in the right format.

I would recommend that you go get a backup.  Sorry about that!

**Comment by craig-jong** [comment]
We DID fix an issue a while ago where loading would get stuck at 100% for plants. Because the save is non-functional, I'm going to close this as fixed. If it happens again, reopen this and I'll see what I can do (hopefully in a more timely manner).
