### ISSUE TITLE
[7.2 Staging Bc863b4b]  Crash and Multiple Exception

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#5208]
Lastest beta is generating many exceptions and ha d unknown crash.  Server is experiencing a great deal more latency then it did with previous staging.  Yesterday we were hosting 30 players with no noticeable lag.  Only gotten up to 10 players since Bc863b4b was released to day but at that point had to log off server as i was unable to walk or clamber up a block.  Was unable to place claim flags and unable to open any chests

https://www.dropbox.com/s/avzbhc1j9zlap3p/Staging%20Beta%207.2.0%20%23Bc863b4b_Dump.zip?dl=0

**Comment by MarjieAVolk** [comment]
Here are all the distinct stack traces:

1.
```
Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__55_0()
```

2.
```
System.Exception: Caught exception invoking RPC PlayerInteract on Player!

The given key was not present in the dictionary.


Stack:
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Plugins.Networking.QuadTree`1.Remove(T item)
   at Eco.Shared.Networking.NetObjectManager.Remove(INetObject netObject)
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at Eco.Simulation.PlantSim.DestroyPlant(Plant plant, DeathType deathType, Boolean applyToWorldLayer)
   at HoeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
```

3.
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Plugins.Networking.QuadTree`1.Remove(T item)
   at Eco.Shared.Networking.NetObjectManager.Remove(INetObject netObject)
   at ArrowEntity.Destroy()
   at ArrowEntity.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
```

4.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
```

5.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by MarjieAVolk** [comment]
Split into separate issues for each distinct call stack, that didn't already have its own bug.
