### ISSUE TITLE
Server Crash: Trying to kill tree with hoe?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#5247]
From crash dumps linked in https://github.com/StrangeLoopGames/EcoIssues/issues/5208:

```
System.Exception: Caught exception invoking RPC PlayerInteract on Player!

The given key was not present in the dictionary.


Stack:
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Plugins.Networking.QuadTree`1.Remove(T item)
   at Eco.Shared.Networking.NetObjectManager.Remove(INetObject netObject)
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at Eco.Simulation.PlantSim.DestroyPlant(Plant plant, DeathType deathType, Boolean applyToWorldLayer)
   at HoeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
```

**Comment by metachronism** [comment]
fixed
