### ISSUE TITLE
Server Crash: Something something QuadTree

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#5248]
From crash dumps linked in #5208:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
```

**Comment by craig-jong** [comment]
Depending on what version this was, it might have been fishing. I was getting quadtree exception when fishing because I was deleting the fish incorrectly. Should be fixed in that PR that went in this morning.

**Comment by MarjieAVolk** [comment]
Was [7.2 Staging Bc863b4b]

**Comment by metachronism** [comment]
fixed
