### ISSUE TITLE
SERVER ISSUE : [STAGING] Crash when fishing

### ISSUE THREAD

**Issue by B1sounours** [StrangeLoopGames/EcoIssues#5254]
Version: Staging 7.2 tested on bc863b4b

Steps to Reproduce:
Fish one time get the fish and relaunch the pole two time > crash

Expected behavior:
Fishing

Actual behavior:
Crash server

(On the 733ef85f the crash seem to not happening anymore but we still have two bait and no wire on the fishing pole and the fish doesnt come anymore we need to switch to another tool and retake the fishing pole to make it work again)

Dump:

--BEGIN DUMP--
Dump Time
02/28/2018 23:39:36

Exception
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary2.get_Item(TKey key)
   at Eco.Plugins.Networking.QuadTree1.Remove(T item)
   at Eco.Plugins.Networking.QuadTreeNetObjectCollection.OnObjectMoved(INetObjectPosition obj)
   at Eco.Simulation.Agents.Animal.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by craig-jong** [comment]
Apparently the crash doesn't happen anymore as a crash, but there is still an issue here.

The fishing pole in general needs a good look at anyway.

**Comment by craig-jong** [comment]
Well it was fixed to work with the spoky fp controller. Still could do more, but I'm going to close this.
