### ISSUE TITLE
USER ISSUE: Crash when exceeding certain height

### ISSUE THREAD

**Issue by imthe666st** [StrangeLoopGames/EcoIssues#5280]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Get Hewn Logs or similar
1a. (optional) Get DevToolItem and enable fly for quick building
2. Build a tower into the sky

The world should crash with the error below

**Expected behavior:**
The player should be prevented from building above a certain height

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Total world volume of 4000 x * 134,2177279375 y * 4000 z = 2147483647 is larger than the max supported size of int.MaxValue (2147483647).


Stack:
   at Eco.Shared.Math.WorldPosition3i.Initialize(Vector3i worldSize)
   at Eco.Shared.Voxel.ChunkGrid`1.AddChunk(TChunk chunk)
   at Eco.Shared.Voxel.ChunkGrid`1.GetOrAddChunk(Vector3i chunkPos)
   at Eco.World.WorldChunkGrid.SetBlock(Type blockType, Vector3i worldPos, Object[] args)
   at Eco.Gameplay.Items.UsableItemUtils.PlayerPlaceBlock(Type blockType, Vector3i blockPosition, Player player, Boolean replaceBlock, IAtomicAction[] additionalActions)
   at Eco.Gameplay.Items.BlockItem.PlaceBlock(Type blockType, Vector3i targetPos, Player player, Boolean replaceBlock)
   at Eco.Gameplay.Items.BlockItem.OnActRight(InteractionContext context)
   at DevtoolItem.OnActRight(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by D3nnis3n** [comment]
Fixed in 7.8.
