### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Arti-llery** [StrangeLoopGames/EcoIssues#5318]
--BEGIN DUMP--
Dump Time
03/02/2018 21:55:33

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList1.Node.RemoveAll(Predicate1 match)
   at System.Collections.Immutable.ImmutableList1.RemoveAll(Predicate1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

Only 3 of us on at the time, and we were chatting mainly.

**Comment by Arti-llery** [comment]
I'm beginning to wonder if this isn't in reference to someone mass breaking stone or ores. as we just had another crash with the same exact thing.

**Comment by MarjieAVolk** [comment]
This should be fixed in 7.2
