### ISSUE TITLE
USER ISSUE: reaping

### ISSUE THREAD

**Issue by GrimmLiberty** [StrangeLoopGames/EcoIssues#5354]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Big world, iron scythe, reap grass too fast....

**Expected behavior:**
reap grass, stack items in slot

**Actual behavior:**
The following error message popped up:
```Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Value cannot be null.
Parameter name: key


Stack:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Items.ItemAttribute.Get[T](Type itemType)
   at Eco.Gameplay.Plants.PlantEntity.TryHarvest(Player player, Boolean picked)
   at Eco.Mods.TechTree.ScytheItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Value cannot be null.
Parameter name: key


Stack:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.Gameplay.Items.ItemAttribute.Get[T](Type itemType)
   at Eco.Gameplay.Plants.PlantEntity.TryHarvest(Player player, Boolean picked)
   at Eco.Mods.TechTree.ScytheItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by craig-jong** [comment]
This was an issue with plants not granting correct materials. Should be fixed. Please reopen it if you encounter it again.
