### ISSUE TITLE
USER ISSUE: tree part

### ISSUE THREAD

**Issue by justinwho** [StrangeLoopGames/EcoIssues#5460]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
crash while cutting down a tree

**Expected behavior:**
game crash

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment]
This should be fixed in 7.2
