### ISSUE TITLE
USER ISSUE: Crash: Picking up another players birchlogs

### ISSUE THREAD

**Issue by SebastianFranken** [StrangeLoopGames/EcoIssues#5470]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Went to a abandoned cut (birch-)tree from another player (unclaimed).
2. Hacked the debris (Wood Pulp)
3. Pressed 'E' on the single left over piece of Logs (still in sliced Tree-Form) to pick it up

**Expected behavior:**
A few pieces of Logs should have gone into my inventory.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment]
Fixed in 7.2
