### ISSUE TITLE
USER ISSUE : cart carried item issue

### ISSUE THREAD

**Issue by fbettocchi** [StrangeLoopGames/EcoIssues#5486]
Version: 0.7.2 beta-staging-f6bf50db

Steps to Reproduce:
take max carried item (eg : 20 stone)
put into cart (small or big, whatever)
take another fullstack of different carried item (eg:  gold)
left click (instead of right click, like a mistake) 

Expected behavior:
Do nothing or switch with first/last cart items

Actual behavior:

game crash, tested on 2 pc / server differents, clean world.

Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.Inventory.MoveAsManyItemsAsPossible(Inventory destination, Func`2 sourceStackPredicate, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>]...

**Comment by fbettocchi** [comment]
Fixed with 7.2.1 hotfix
