### ISSUE TITLE
USER ISSUE: Transfer to Stockpile Causes Exception/Crash to Main Menu

### ISSUE THREAD

**Issue by Pthfndr324** [StrangeLoopGames/EcoIssues#5500]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
1. Go underground 15 levels.
2. Using stone hammer, hit to pick up placed Mortared Stone (7 total).
3. Transfer carried Mortared Stone to underground Stockpile by right clicking on it (the Stockpile is currently ~1/2 full with Tailings).

**Expected behavior:**
The Mortared Stone should have been transferred to the Stockpile. 

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.Inventory.MoveAsManyItemsAsPossible(Inventory destination, Func`2 sourceStackPredicate, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActRight(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
Fixed in latest hotfix
