### ISSUE TITLE
USER ISSUE: Crash on trying to take Hewn wood from stockpile while already holding hewn wood

### ISSUE THREAD

**Issue by kshood** [StrangeLoopGames/EcoIssues#5502]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
1. From a stockpile, press LMB to take a stack of hewn wood. You should now have 15 hewn wood.
2. From the same stockpile, press LMB to try and take hewn wood again while still holding the 15 hewn wood.

Note: I think this happens for other material as well, but I have not tested it for more than Hewn wood and Lumber.

**Expected behavior:**
Either do nothing or top off to 20 hewn wood.

**Actual behavior:**
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.Inventory.MoveAsManyItemsAsPossible(Inventory destination, Func`2 sourceStackPredicate, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>

**Comment by SeanAtr0n** [comment]
fixed in 7.2.1
