### ISSUE TITLE
Crash on server startup 7.2

### ISSUE THREAD

**Issue by Capps0611** [StrangeLoopGames/EcoIssues#5505]
I recently upgraded my dedicated server to 7.2 using the files on the SLG website. below is the crash that I get on start up.

--BEGIN DUMP--
Dump Time
03/06/2018 19:55:26

Exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error in Acorn at 19: Partial declarations of 'Eco.Mods.TechTree.AcornItem' must not specify different base classes (CS0263)
Error in Torch at 45: Partial declarations of 'Eco.Mods.TechTree.TorchItem' must not specify different base classes (CS0263)
Error in Acorn at 25: The type 'Eco.Mods.TechTree.AcornItem' already contains a definition for 'nutrition' (CS0102)
Error in Acorn at 27: The type 'Eco.Mods.TechTree.AcornItem' already contains a definition for 'FriendlyName' (CS0102)
Error in Acorn at 28: The type 'Eco.Mods.TechTree.AcornItem' already contains a definition for 'Description' (CS0102)
Error in Acorn at 31: The type 'Eco.Mods.TechTree.AcornItem' already contains a definition for 'Calories' (CS0102)
Error in Acorn at 32: The type 'Eco.Mods.TechTree.AcornItem' already contains a definition for 'Nutrition' (CS0102)

   at Eco.ModKit.RuntimeCompiler.HandleCompilerError(CompilerResults results)
   at Eco.ModKit.RuntimeCompiler.LoadOrCompileMods()
   at Eco.ModKit.ModKitPlugin..ctor(ManualResetEvent doneEvent)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

Inner Exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error in Acorn at 19: Partial declarations of 'Eco.Mods.TechTree.AcornItem' must not specify different base classes (CS0263)
Error in Torch at 45: Partial declarations of 'Eco.Mods.TechTree.TorchItem' must not specify different base classes (CS0263)
Error in Acorn at 25: The type 'Eco.Mods.TechTree.AcornItem' already contains a definition for 'nutrition' (CS0102)
Error in Acorn at 27: The type 'Eco.Mods.TechTree.AcornItem' already contains a definition for 'FriendlyName' (CS0102)
Error in Acorn at 28: The type 'Eco.Mods.TechTree.AcornItem' already contains a definition for 'Description' (CS0102)
Error in Acorn at 31: The type 'Eco.Mods.TechTree.AcornItem' already contains a definition for 'Calories' (CS0102)
Error in Acorn at 32: The type 'Eco.Mods.TechTree.AcornItem' already contains a definition for 'Nutrition' (CS0102)

   at Eco.ModKit.RuntimeCompiler.HandleCompilerError(CompilerResults results)
   at Eco.ModKit.RuntimeCompiler.LoadOrCompileMods()
   at Eco.ModKit.ModKitPlugin..ctor(ManualResetEvent doneEvent)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

--END DUMP--

**Comment by FetssteF** [comment]
To avoid this error, you need to delete the mods folder and send it again so that the old files are deleted as shown in http://ecoforum.strangeloopgames.com/topic/3008/how-to-do-a-clean -server-install-for-new-update

**Comment by Capps0611** [comment]
Works like a charm
