### ISSUE TITLE
USER ISSUE: Reaping Stockpile multiple times with scythe crash

### ISSUE THREAD

**Issue by SethHubbell** [StrangeLoopGames/EcoIssues#5523]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
Place down Stockpile
Put some logs in stockpile
Put some stone in stockpile

Reap stockpile with scythe (should put logs in carry slot)
Reap stockpile again (with logs still in hand)

**Expected behavior:**
It should display an error showing that you have no room to carry the stone. (Either that or the scythe shouldn't load items from the stockpile?)

**Actual behavior:**
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.Inventory.MoveAsManyItemsAsPossible(Inventory destination, Func`2 sourceStackPredicate, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>

**Comment by SeanAtr0n** [comment]
Fixed in 7.2.1
