### ISSUE TITLE
7.2.0 - Crash while walking

### ISSUE THREAD

**Issue by DumpsterDave** [StrangeLoopGames/EcoIssues#5527]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
was walking towards my crafting stations.  did not perform any actions other than walking

**Expected behavior:**
nothing

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Specified argument was out of the range of valid values.
Parameter name: arrayIndex


Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by MarjieAVolk** [comment]
Had a report of this on 7.2.3

**Comment by metachronism** [comment]
should be fixed in 7.2.3

**Comment by MarjieAVolk** [comment]
Had multiple reports in 7.2.3
