### ISSUE TITLE
USER ISSUE: Fallen branch

### ISSUE THREAD

**Issue by CaptainBakaneko** [StrangeLoopGames/EcoIssues#5548]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
when i try to clean up  after the fallen trees the twisted one's

**Expected behavior:**
harvest them

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'.


Stack:
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.TransactionService.PersistDirtyPages()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.UsableItemUtils.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   at Eco.Gameplay.Items.ToolItem.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, Single calorieMultiplier, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject b

**Comment by MarjieAVolk** [comment]
Sigh, looks like LiteDB concurrency has bugs: https://github.com/mbdavid/LiteDB/issues/641

**Comment by MarjieAVolk** [comment]
Would you be able to pass over the .db file for the save where this is happening?  If you are running your own server, it should be '[...]\steamapps\common\Eco\Eco_Data\Server\Storage\[GameName].db'

**Comment by NSH4RPY** [comment]
Here you go, we reverted to a backup and continued on that but guess this will be useful for troubleshooting :)

[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1804988/Game.zip)

**Comment by MarjieAVolk** [comment]
Okay, I've talked with the developer of the third party database software that this error is coming out of.  He told me that the problem should be fixed in the latest version of the software, which we have updated to for 7.3.  However, people who are currently seeing this error (and possibly people who migrate saves from 7.2.5 or lower) will need to clear their database in order to get rid of the error.  You can do this by deleting your .db file, which is one of your save files and will have the same name as your save game.  FYI, this will clear all your stats and graphs, and reset action counts used in laws.
