### ISSUE TITLE
USER ISSUE: Stockpile Crash

### ISSUE THREAD

**Issue by NurseJoy** [StrangeLoopGames/EcoIssues#5560]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
Remove hewn log from house while back to a stock pile full of resources, with hewn logs in your held inventory. 

**Expected behavior:**
Added the hewn logs to held inventory

**Actual behavior:**
The following error message popped up:
```

Interactions around stockpiles, even while looking up/away are quite strange. The game interprets your right clicks/actions as interactions with the stockpile - rather than with whatever you're targeting.
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.Inventory.MoveAsManyItemsAsPossible(Inventory destination, Func`2 sourceStackPredicate, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by SeanAtr0n** [comment]
fixed in 7.2.1
