### ISSUE TITLE
USER ISSUE: Hitting stockpile with hammer with full hand crashes

### ISSUE THREAD

**Issue by raindirve** [StrangeLoopGames/EcoIssues#5572]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
0. Carrying a full stack of Hewn Logs,
1. Have a stockpile containing multiple resources including large amounts of the type currently carried,
2. Whack the stockpile with a hammer.

**Expected behavior:**
It should have moved the maximum possible amount of Hewn Logs to my hand: 0 logs.

**Actual behavior:**
Game crashed.
The following error message popped up:
```Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.Inventory.MoveAsManyItemsAsPossible(Inventory destination, Func`2 sourceStackPredicate, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack

**Comment by SeanAtr0n** [comment]
Fixed in 7.2.1
