### ISSUE TITLE
USER ISSUE: Mining Bug

### ISSUE THREAD

**Issue by Kildwar** [StrangeLoopGames/EcoIssues#5589]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
1. First attempt to mine during tutorial	

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Could not load type 'System.Numerics.Quaternion' from assembly 'System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.


Stack:
   at Eco.Gameplay.Objects.RubbleObject.TrySpawnFromBlock(Type blockType, Vector3 position)
   at Eco.Mods.TechTree.PickaxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.<>c__DisplayClass0_1`1.<ExecuteUntilSuccess>b__1()
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by metachronism** [comment]
try updating your .NET installed version?
