### ISSUE TITLE
USER ISSUE: tried to pick up a log i found lying around

### ISSUE THREAD

**Issue by squished-01** [StrangeLoopGames/EcoIssues#5595]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
Fixed in 7.2

**Comment by MarjieAVolk** [comment]
Oh darn, I didn't see this was in 7.2.  GUESS IT'S NOT FIXED THEN :'(

**Comment by MarjieAVolk** [comment]
One person noted the log was an oak.

**Comment by MarjieAVolk** [comment]
One person noted that they hold down both LMB and E while chopping trees, so their problems might be related to initialization of something or other.
