### ISSUE TITLE
[SERVER ISSUE] ClientNetworkException

### ISSUE THREAD

**Issue by Ekkelus** [StrangeLoopGames/EcoIssues#5600]
--BEGIN DUMP--
Dump Time
03/07/2018 15:26:13

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveSomeItems on AuthorizationInventory!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.CarriedRestriction.MaxAccepted(Item item, Int32 currentQuantity)
   at Eco.Gameplay.Items.Inventory.GetRestrictionMessage(Item item, Int32 currentQuantity, Int32 desiredQuantity, ResultBuilder result)
   at Eco.Gameplay.Items.Inventory.MoveSomeItems(ItemStack sourceStack, ItemStack targetStack, Int32 quantity, Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

**Comment by metachronism** [comment]
any more info or repro steps if possible?
