### ISSUE TITLE
USER ISSUE: Crash after removing Blocks

### ISSUE THREAD

**Issue by Taratsamura** [StrangeLoopGames/EcoIssues#5610]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
1. i don't know
2. Have a Nitrado server
3. Server crashed for no reason
4. Server Restart
5. Invisble Blocks appeard where i can move on, but not interact in any other way (don't even see them)
6. Can't remove blocks anymore, i instantly get kicked.

**Expected behavior:**
No invisible Blocks
Be able to remove blocks.

**Actual behavior:**
The following error message popped up:
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.IndexPage'.

Stack:
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.UsableItemUtils.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, BlockItem fallbackGiveItem, IAtomicAction[] additionalActions)
   at Eco.Gameplay.Items.ToolItem.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, Single calorieMultiplier

**Comment by Taratsamura** [comment]
Update: The problem got solved after disabling the stats.

**Comment by MarjieAVolk** [comment]
Would you be able to pass over the .db file for the save where this is happening?  If you are running your own server, it should be '[...]\steamapps\common\Eco\Eco_Data\Server\Storage\[GameName].db'

**Comment by MarjieAVolk** [comment]
Okay, I've talked with the developer of the third party database software that this error is coming out of.  He told me that the problem should be fixed in the latest version of the software, which we have updated to for 7.3.  However, people who are currently seeing this error (and possibly people who migrate saves from 7.2.5 or lower) will need to clear their database in order to get rid of the error.  You can do this by deleting your .db file, which is one of your save files and will have the same name as your save game.  FYI, this will clear all your stats and graphs, and reset action counts used in laws.
