### ISSUE TITLE
[SERVER ISSUE] RPC Delete on StoreComponent, memory leak followed.

### ISSUE THREAD

**Issue by Ekkelus** [StrangeLoopGames/EcoIssues#5626]
--BEGIN DUMP--
Dump Time
03/07/2018 22:07:22

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Delete on StoreComponent!

Specified argument was out of the range of valid values.
Parameter name: index

Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.RemoveAt(Int32 index)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass12_0.<RemoveAt>b__0()
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Core.Controller.RPCListExtensions.Delete(IContainsRPCLists obj, Int32 iList, Int32 iEntry)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

**Comment by MarjieAVolk** [comment]
What version of the game are you on?  This is fixed in 7.2.
