### ISSUE TITLE
Using the give command and try to open the cheat menu throws an error on the server

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#563]
at Eco.Gameplay.Controller.ControllerManager.GetController(Guid key) in I:\Eco testing\New folder\Eco\Server\Eco.Gameplay\Controller\ControllerManager.cs:line 220
   at Eco.Gameplay.Controller.ControllerManager.HandleViewRPC(Guid controllerToken, String methodname, BSONObject bson) in I:\Eco testing\New folder\Eco\Server\Eco.Gameplay\Controller\ControllerManager.cs:line 232
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson) in I:\Eco testing\New folder\Eco\Server\Eco.Plugins\Networking\Clients\Client.cs:line 359

**Comment by metachronism** [comment]
Use the SearchAndSelectItem for now, gets you almost the same thing
