### ISSUE TITLE
USER ISSUE: Exception when hitting a stockpile with a pickaxe

### ISSUE THREAD

**Issue by Homeblest** [StrangeLoopGames/EcoIssues#5634]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
1. Have a stockpile underground
2. Have stone and coal in it
3. Equip a pickaxe
4. Swing the pickaxe at the stockpile (maybe jump meanwhile)
5. Maybe swing at the stockpile while having something in your hands (like stone)

**Expected behavior:**
It should have placed items in my hand, or if i had stuff in my hand it should have done nothing and not crashed

**Actual behavior:**
Kicked out of the server and got this, happened twice now:
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.Inventory.MoveAsManyItemsAsPossible(Inventory destination, Func`2 sourceStackPredicate, User user)
   at Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
Fixed in 7.2.1
