### ISSUE TITLE
USER ISSUE: Deleting Sale caused crash.

### ISSUE THREAD

**Issue by tywarr** [StrangeLoopGames/EcoIssues#5673]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
1. Listed Item fish trap for sale x2 for price 0.
2. Clicked to delete sale. 
3. Immediate Crash	

**Expected behavior:**
Just deleted the sale and gone back to a blank store.

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Delete on StoreComponent!

Specified argument was out of the range of valid values.
Parameter name: index


Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.RemoveAt(Int32 index)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass12_0.<RemoveAt>b__0()
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Core.Controller.RPCListExtensions.Delete(IContainsRPCLists obj, Int32 iList, Int32 iEntry)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Netw

**Comment by AndyClausen** [comment]
Could it be that another player did the same thing at the same time? Or maybe you clicked twice quickly?
As it was an out of range exception, it seems like the game could not find the sale you wanted to delete.

**Comment by tywarr** [comment]
It’s likely the double clicking thing because my mouse has a tendency to rapidly double click unwanted. If that helps at all.

**Comment by tywarr** [comment]
But I was on the server by myself at the time.

**Comment by AndyClausen** [comment]
Quick disclaimer: I'm not a Dev, just a friendly player.

I'm sure any information helps. If you have anything else, don't hesitate.
Double clicking is a common problem in all kinds of software, and it very well might be the case here. Just out of curiosity; which mouse do you have?

**Comment by tywarr** [comment]
It’s a razer deathadder if I remember right. I wish I had something else. It does this random aforementioned double clicking. Either left of right doesn’t matter. Comes and goes. Doesn’t matter the program I’m on or any settings.
