### ISSUE TITLE
USER ISSUE: Cant place any blocks

### ISSUE THREAD

**Issue by willsor** [StrangeLoopGames/EcoIssues#5707]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
i'm not sure	

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Unable to cast object of type 'LiteDB.DataPage' to type 'LiteDB.IndexPage'.


Stack:
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.UsableItemUtils.PlayerPlaceBlock(Type blockType, Vector3i blockPosition, Player player, Boolean replaceBlock, IAtomicAction[] additionalActions)
   at Eco.Gameplay.Items.BlockItem.PlaceBlock(Type blockType, Vector3i targetPos, Player player, Boolean replaceBlock)
   at Eco.Gameplay.Items.BlockItem.OnActRight(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/5610

**Comment by MarjieAVolk** [comment]
Would you be able to pass over the .db file for the save where this is happening?  If you are running your own server, it should be '[...]\steamapps\common\Eco\Eco_Data\Server\Storage\[GameName].db'

**Comment by GophTheGreat** [comment]
+1 from Kayako.

 "when I will put any block on the floor the server crash" 

They included their error message:

Caught exception: 
  
<size=60,00%>Caught exception invoking RPC PlayerInteract on Player! 
  
Não é possível converter um objeto do tipo 'LiteDB.IndexPage' no tipo 'LiteDB.DataPage'. 
  
  
Stack: 
   em LiteDB.PageService.GetPage[T](UInt32 pageID) 
   em LiteDB.PageService.GetFreePage[T](UInt32 startPageID, Int32 size) 
   em LiteDB.DataService.Insert(CollectionPage col, Byte[] data) 
   em LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId) 
   em LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col) 
   em LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action) 
   em LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId) 
   em LiteDB.LiteCollection`1.Insert(T document) 
   em Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply() 
   em Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply() 
   em Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply() 
   em Eco.Gameplay.Items.UsableItemUtils.PlayerPlaceBlock(Type blockType, Vector3i blockPosition, Player player, Boolean replaceBlock, IAtomicAction[] additionalActions) 
   em Eco.Gameplay.Items.BlockItem.PlaceBlock(Type blockType, Vector3i targetPos, Player player, Boolean replaceBlock) 
   em Eco.Gameplay.Items.BlockItem.OnActRight(InteractionContext context) 
   em Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results) 
   em Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info) 
  
  
  
Stack: 
   em Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result) 
   em Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname) 
   em Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson) 
   em Eco.Shared.Networking.NetPort.ProcessBuffer() 
   em Eco.Shared.Networking.NetPort.Update() 
   em Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0() 
</size>

**Comment by MarjieAVolk** [comment]
Okay, I've talked with the developer of the third party database software that this error is coming out of.  He told me that the problem should be fixed in the latest version of the software, which we have updated to for 7.3.  However, people who are currently seeing this error (and possibly people who migrate saves from 7.2.5 or lower) will need to clear their database in order to get rid of the error.  You can do this by deleting your .db file, which is one of your save files and will have the same name as your save game.  FYI, this will clear all your stats and graphs, and reset action counts used in laws.
