### ISSUE TITLE
USER ISSUE: Crash on removing workstation

### ISSUE THREAD

**Issue by UnralJake** [StrangeLoopGames/EcoIssues#5844]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Attempt to cancel a non-active work order in a cast iron stove. 
2. Fail.
3. Smack Cast iron stove with hammer repeatedly
4. Crash

**Expected behavior:**
Cancel the work order and return any non processed ingredients to inventory, along with cast iron stove. 

**Actual behavior:**
The following error message popped up:
Caught exception:

<size=60,00%>Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC CancelWorkOrder on CraftingComponent!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Components.CraftingComponent.CancelWorkOrder(Player player, WorkOrder workOrder)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by UnralJake** [comment]
After logging back in, I think I realised the issue. 

I was carrying four iron pipes on me, and my character was trying to remove the coal from the fuel supply of the cast iron stove. Still not sure why the work orders weren't being cancelled.

**Comment by MarjieAVolk** [comment]
Well, we haven't had any more reports or repros of this in all this time, so I'm just going to commit a little null check that may or may not have fixed this crash, and call it a day on this one.
