### ISSUE TITLE
Exception setting off .Net shutdown

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#5871]
The following issue is raising a .Net issue which is shutting down servers

--BEGIN DUMP--
Dump Time
03/10/2018 18:51:18

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.Agents.AI.AITarget.<UpdatePosition>b__32_0()
   at Eco.Shared.Utils.LockUtils.TryLock(Object lockObject, Action ifLockAcquired, Int32 millisecondsTimeout)
   at Eco.Simulation.Agents.AI.AITarget.UpdatePosition()
   at Eco.Simulation.Agents.AI.AITarget.get_Position()
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by SeanAtr0n** [comment]
fixed 7.4
