### ISSUE TITLE
Crash after downgrade to 7.1.2 from 7.2.3

### ISSUE THREAD

**Issue by hurraybies** [StrangeLoopGames/EcoIssues#5872]
When updating my 7.1.2 world to 7.2.3, an issue I had earlier in 7.2.2 with ramps being invisible and with no collision was still apparent. When converting back down to 7.1.2, the server would no longer load. This is the dump.

```
--BEGIN DUMP--
Dump Time
03/10/2018 18:33:06

Exception
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error(s) occurred when loading World
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.World.PersistentChunkGrid.Load()
   at Eco.World.WorldPlugin..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_1()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager.<.ctor>b__10_0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error(s) occurred when loading World
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.World.PersistentChunkGrid.Load()
   at Eco.World.WorldPlugin..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_1()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager.<.ctor>b__10_0()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error(s) occurred when loading World
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.World.PersistentChunkGrid.Load()
   at Eco.World.WorldPlugin..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_1()
   at System.Threading.Tasks.Task.Execute()<---
<---


Inner Exception
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error(s) occurred when loading World
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.World.PersistentChunkGrid.Load()
   at Eco.World.WorldPlugin..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_1()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager.<.ctor>b__10_0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error(s) occurred when loading World
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.World.PersistentChunkGrid.Load()
   at Eco.World.WorldPlugin..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_1()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager.<.ctor>b__10_0()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error(s) occurred when loading World
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.World.PersistentChunkGrid.Load()
   at Eco.World.WorldPlugin..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_1()
   at System.Threading.Tasks.Task.Execute()<---
<---


--END DUMP--

```

**Comment by Thyriel** [comment]
I doubt that you can downgrade a 7.2 world to 7.1 as they changed the way worldsaving works (2 files in 7.2 while it was one file in 7.1)

**Comment by lefavilla** [comment]
you should run for the latest stable. 7.1 had some hard bugs what can bring you big problems.

**Comment by pamduncan** [comment]
Did you go back to a backup that was from the version your downgraded to?  As soon as you ran a world in the upgraded version  it was migrated to that version and cannot be used on the version you rolled back to.

**Comment by MarjieAVolk** [comment]
Downgrading to previous versions is not supported.  A backup that was saved on the previous version is your best bet.  Although I think 7.2.3 is pretty stable now.
