### ISSUE TITLE
USER ISSUE: Bug 

### ISSUE THREAD

**Issue by joefunk00** [StrangeLoopGames/EcoIssues#5875]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
walking in or out of mine, (up or down ramp) would send me out of the map. having to disconnect everytime

**Expected behavior:**
let me walk down the mine 

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Value cannot be null.
Parameter name: item


Stack:
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by Villerger27** [comment]
There is commands that you can use, and /fly is basically No-Clip, but I can see why that is a bug

**Comment by MarjieAVolk** [comment]
If you can get this to happen reliably, could you send us the save file where this happens?  And let us know the coordinates where it happens?

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5328.
