### ISSUE TITLE
USER ISSUE: Random Crash while walking

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#5880]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Serialization.SimpleBSON.EncodeBinary(MemoryStream stream, Byte[] buf)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.SimpleBSON.EncodeDocument(MemoryStream stream, BSONObject obj)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.SimpleBSON.EncodeArray(MemoryStream stream, BSONArray array)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.SimpleBSON.EncodeDocument(MemoryStream stream, BSONObject obj)
   at Eco.Shared.Networking.NetPort.SendEvent(NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by metachronism** [comment]
should be fixed as of 7.3
