### ISSUE TITLE
[SERVER ISSUE] Server crashing every 10 minutes

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#5932]
3 different crash reasons repeat over and over again.

Update: Ive just witnessed the crash, EcoServer.exe window prints all 3 dumps and then it crashes. So they are somehow connected. Also prior to crash CPU usage went unusually high, while typical usage with 20 players online sits at 20%, at the moment of crash there were 9 players online and the CPU usage skyrocketed to 30% and stayed there up until server crashed. After server restarted it went back to 10% usage.
Update 2: It also clears the admins list every time it crashes.

```
--BEGIN DUMP--
Dump Time
03/12/2018 00:16:07

Exception
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: arrayIndex
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeMembers(BinaryWriter writer, Object instance)
   at Eco.Core.Serialization.SimpleSerializer.Serialize(Object obj)
   at Eco.Core.Serialization.ZipBlob.Persist(Object obj)
   at Eco.Gameplay.Systems.Chat.ChatServer.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
```

```
--BEGIN DUMP--
Dump Time
03/11/2018 23:02:43

Exception
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: arrayIndex
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.AddSubTreeContents(List`1 collection)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode`1.Query(Rect queryArea, List`1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--
```

```
--BEGIN DUMP--
Dump Time
03/11/2018 22:28:07

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--
```

**Comment by fisele** [comment]
Same here!

--BEGIN DUMP--
Dump Time
03/12/2018 00:28:54

Exception
System.ArgumentOutOfRangeException: Das angegebene Argument liegt außerhalb des gültigen Wertebereichs.
Parametername: arrayIndex
   bei System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   bei System.Collections.Immutable.ImmutableList`1.CopyTo(T[] array, Int32 arrayIndex)
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   bei Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeMembers(BinaryWriter writer, Object instance)
   bei Eco.Core.Serialization.SimpleSerializer.Serialize(Object obj)
   bei Eco.Core.Serialization.ZipBlob.Persist(Object obj)
   bei Eco.Gameplay.Systems.Chat.ChatServer.Run()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by Last2Night** [comment]
Ive just witnessed the crash, EcoServer.exe window prints all 3 dumps and then it crashes.

**Comment by Last2Night** [comment]
Ive just had the server window print this dump, it didnt crash the server but i spoke to the players that caused it and they said they just opened their inventory and closed it.

Caught update exception from Gilded Nova!  Disconnecting...
[38:50] Disconnecting client [reason: Caught exception:

<size=60.00%>Specified argument was out of the range of valid values.
Parameter name: arrayIndex


Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List1.InsertRange(Int32 index, IEnumerable1 collection)
   at Eco.Plugins.Networking.QuadTreeNode1.AddSubTreeContents(List1 collection)
   at Eco.Plugins.Networking.QuadTreeNode1.AddSubTreeContents(List1 collection)
   at Eco.Plugins.Networking.QuadTreeNode1.AddSubTreeContents(List1 collection)
   at Eco.Plugins.Networking.QuadTreeNode1.AddSubTreeContents(List1 collection)
   at Eco.Plugins.Networking.QuadTreeNode1.AddSubTreeContents(List1 collection)
   at Eco.Plugins.Networking.QuadTreeNode1.Query(Rect queryArea, List1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode1.Query(Rect queryArea, List1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode1.Query(Rect queryArea, List1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode1.Query(Rect queryArea, List1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNode1.Query(Rect queryArea, List1 results, Boolean rootNode)
   at Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects(INetObjectViewer viewer, ICollection1 alreadyRelevant)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>]...

**Comment by Last2Night** [comment]
An update. It also clears the admins list every time it crashes.

**Comment by Yorkforce** [comment]
We also get these crashes, along with database lockups and 30 mins restart times, in its current state this version is unplayable.

**Comment by MarjieAVolk** [comment]
Second stack trace is https://github.com/StrangeLoopGames/EcoIssues/issues/5527
Third stack trace is https://github.com/StrangeLoopGames/EcoIssues/issues/5496

Leaving open though, as you suggest they are all related.

**Comment by Last2Night** [comment]
@MarjieAVolk As far as my observation goes those exceptions when being printed by EcoServer.exe not stacked but rather 1 by 1 dont crash the server, however when all 3 pop up at once the server stops responding and crashes. It might be crashing even when a single exception appears as im not monitoring the server 24/7.

**Comment by lefavilla** [comment]
@Last2Night could you please provide the seednumber?

**Comment by Last2Night** [comment]
@lefavilla Seed: 773660843
