### ISSUE TITLE
USER ISSUE: World Crashes to Main Menu

### ISSUE THREAD

**Issue by Manjack4060** [StrangeLoopGames/EcoIssues#5935]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Game was running when PC bluescreened, went to continue world and the proceed to pick up huckleberries from a natural bush and then crashes to the main menu.

**Expected behavior:**
Should have picked up the berries no problem

**Actual behavior:**
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Cannot insert duplicate key in unique index '_id'. The duplicate value is '187'.

Stack:
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Plants.PlantEntity.TryHarvest(Player player, Boolean picked)
   at Eco.Gameplay.Plants.InteractablePlantBlock.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>

**Comment by MarjieAVolk** [comment]
This will be fixed in the next release.
