### ISSUE TITLE
USER ISSUE: Chop a tree with Iron Axe, crash

### ISSUE THREAD

**Issue by Skintkingle** [StrangeLoopGames/EcoIssues#6017]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
1. equip an iron Axe.
2. Hit a tree

**Expected behavior:**
It should have started chopping a tree

**Actual behavior:**
Caught exception:

Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at TreeEntity.TryDamageUnfelledTree(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>

**Comment by MarjieAVolk** [comment]
Similar to https://github.com/StrangeLoopGames/EcoIssues/issues/5619

**Comment by D3nnis3n** [comment]
Fixed long ago.
