### ISSUE TITLE
Client exception 7.3.0 staging

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#6044]
```
--BEGIN DUMP--
Dump Time
03/13/2018 21:50:32

Exception
System.Exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Property.PropertyManager.IsAuthorized(User user, Vector3i pos, IInteractable target, String action)
   at Eco.Gameplay.Items.AuthorizationInventory.CanMoveItems(Type itemType, Int32 delta, User user)
   at Eco.Gameplay.Items.Inventory.CheckAuthForMove(ItemStack source, ItemStack target, User user)
   at Eco.Gameplay.Items.InventoryChangeSet.MoveItemsInternal[TKey](Type itemType, Int32 quantity, Inventory source, Inventory destination, Func`2 sourceStackPredicate, Func`2 sourceStackOrder)
   at Eco.Gameplay.Components.StorageComponent.OnPickUp(Player player, InventoryChangeSet playerInvChanges)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.Objects.WorldObject.PickUp(Player player)
   at HammerItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

```

**Comment by MarjieAVolk** [comment]
Well this is weird, I tried to repro this a bunch of different ways, was about to conclude this code path was not possible, and then suddenly I reproed it, did nothing different as far as I can tell.  I think there's either a race condition (in whether you will get Hammer.OnActLeft or WorldObject.OnActLeft), or you have to like target it at a specific angle or something.

Anyways, my guess was right that the problem is that the acting User on the changeset is null, so fixing that.

**Comment by MarjieAVolk** [comment]
I guess WorldObject.OnActLeft has to fail/noop, so the inventory has to be empty.  I think that's not a sufficient condition though?  Unless I forgot what I did.

**Comment by MarjieAVolk** [comment]
Okay I seriously don't know what I was tripping on, I guess it does happen any time you pick up a chest with stuff in it.  Maybe??? Anyway, fixed.
