### ISSUE TITLE
7.2.4 Server crash at startup with new world

### ISSUE THREAD

**Issue by LIII-XXII** [StrangeLoopGames/EcoIssues#6048]
How to reproduce:

1. Create a new 140x140 world in the single player game
2. Copy files to server
3. Start server

Exception from server log:

```
--BEGIN DUMP--
Dump Time
03/14/2018 18:53:37

Exception
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Eco.Core.Serialization.SimpleSerializer.GetOrCreateSerializerFromSchemaType(SimpleSerializer newSerializer, SerializerSchema schema)
   at Eco.Core.Serialization.SimpleSerializer..ctor(SimpleSerializer newSerializer, String schema, Dictionary`2 migrations)
   at Eco.Core.Serialization.EcoSerializer.Initialize()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Eco.Core.Serialization.SimpleSerializer.GetOrCreateSerializerFromSchemaType(SimpleSerializer newSerializer, SerializerSchema schema)
   at Eco.Core.Serialization.SimpleSerializer..ctor(SimpleSerializer newSerializer, String schema, Dictionary`2 migrations)
   at Eco.Core.Serialization.EcoSerializer.Initialize()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.Execute()<---


Inner Exception
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Eco.Core.Serialization.SimpleSerializer.GetOrCreateSerializerFromSchemaType(SimpleSerializer newSerializer, SerializerSchema schema)
   at Eco.Core.Serialization.SimpleSerializer..ctor(SimpleSerializer newSerializer, String schema, Dictionary`2 migrations)
   at Eco.Core.Serialization.EcoSerializer.Initialize()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Eco.Core.Serialization.SimpleSerializer.GetOrCreateSerializerFromSchemaType(SimpleSerializer newSerializer, SerializerSchema schema)
   at Eco.Core.Serialization.SimpleSerializer..ctor(SimpleSerializer newSerializer, String schema, Dictionary`2 migrations)
   at Eco.Core.Serialization.EcoSerializer.Initialize()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.Execute()<---


--END DUMP--
```

**Comment by Venalyo** [comment]
Exactly the same call stack on our Staging world 7.3.0 (3decfca7).
The only difference is we are not creating a new world, but trying to upgrade our world which was on previous staging a5ac01f4.

**Comment by metachronism** [comment]
actually, I know what this is - the cause is from a staging->staging localization serialization bug.

If you still want your save migrated, I can attempt to fix it for you, but if you are OK with losing that world for now just leave this issue closed

**Comment by JankKeks** [comment]
hi @metachronism, I suggest it is the same bug for me: https://github.com/StrangeLoopGames/EcoIssues/issues/6489 - If this one doesn't get fixed, may u fix my savegame? I attached savegame, log etc. in the issue
