### ISSUE TITLE
USER ISSUE: 7.2.4 Unknown cause

### ISSUE THREAD

**Issue by ZeskaN** [StrangeLoopGames/EcoIssues#6064]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.EnumerableItemExtensions.<>c.<Describe>b__5_3(IGrouping`2 group)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, String noneText)
   at Eco.Gameplay.Utils.PickerObject.get_Contents()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, String memberName)
   at Eco.Core.Controller.ControllerManager.GetChanges(INetClient client)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by johnkslg** [comment]
This was a localization error that should be fixed now
