### ISSUE TITLE
Database lockups happening whenever players interact with the browser.

### ISSUE THREAD

**Issue by SaiyerDed** [StrangeLoopGames/EcoIssues#6174]
This has been a growing issue on my server and it tends to happen whenever someone is working on proposing a new law, signing up for world leader, or casting a vote. Below I'll post the relevant occasions and their corresponding crash dumps.

--Server DB lockup on new world leader election and initial votes:
-Screenshot of dump folder getting tons of logs in a short amount of time: https://i.imgur.com/NLh03Di.png
-Dropbox link to ZIP that contains the above dumps: https://www.dropbox.com/s/pe38r0jf69e906r/Eco%20Dumps.rar?dl=0

--Server DB lockup when I was working on a new law to prevent people from cutting down more trees beyond x amount, if they didn't pick up y amount of wood pulp. (Intended to help clean the server). While making the law, I kept getting "an error has occurred" and my players complained of massive lag until we finally went down due to a DB lockup.
-Screenshot of dump folder around the time of making the law and the DB lockup: https://i.imgur.com/lCas0KI.png
-Dropbox link to ZIP that contains the above dumps: https://www.dropbox.com/s/7nraz98dyeqyvhf/Eco%20Dumps%202.rar?dl=0

**Comment by SaiyerDed** [comment]
We've now had at least 5 DB lockup crashes today over the past 12 hours between votes and browser interactions from what I understand. People keep losing a few minutes of progress and pushing me (the server owner) to fix it as if I can.

Here's the past 12 hours of crash dumps if they'll help the investigation into DB issues: https://www.dropbox.com/s/pdn5gg7gyx5sn4a/Eco%20Dumps%203.rar?dl=0

**Comment by GophTheGreat** [comment]
+1, encountered a user reporting this through Discord.

**Comment by MarjieAVolk** [comment]
Okay I looked through the dumps - most are the same as https://github.com/StrangeLoopGames/EcoIssues/issues/5343, as you noted.  You've also got a couple of https://github.com/StrangeLoopGames/EcoIssues/issues/5328, as well as these 2 which I've never seen before:

```
--BEGIN DUMP--
Dump Time
03/16/2018 17:39:40

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC QueryInteraction on StockpileObject!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Objects.WorldObject.QueryInteraction(Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--
```

```
--BEGIN DUMP--
Dump Time
03/16/2018 17:32:57

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.Agents.AI.AITarget.<UpdatePosition>b__32_0()
   at Eco.Shared.Utils.LockUtils.TryLock(Object lockObject, Action ifLockAcquired, Int32 millisecondsTimeout)
   at Eco.Simulation.Agents.AI.AITarget.UpdatePosition()
   at Eco.Simulation.Agents.AI.AITarget.get_Position()
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

```

**Comment by MarjieAVolk** [comment]
jk, the second one I posted is this: https://github.com/StrangeLoopGames/EcoIssues/issues/5871

**Comment by MarjieAVolk** [comment]
For the first one, I filed a separate bug: https://github.com/StrangeLoopGames/EcoIssues/issues/6321

So closing this bug out.
