### ISSUE TITLE
USER ISSUE: Bow repair problem

### ISSUE THREAD

**Issue by Eastborn** [StrangeLoopGames/EcoIssues#6252]
**Version:** 0.7.3.0 beta staging-fb586bc2

**Steps to Reproduce:**
repair bow

**Expected behavior:**
repari bow

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on ToolbarInventory!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.DurabilityItem.RepairCost(User user)
   at Eco.Gameplay.Components.RepairComponent.NeededStack(User user)
   at Eco.Gameplay.Components.RepairComponent.RepairSlotChanged(User user)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
Had this reported for stone axe also, so probably not item specific

**Comment by craig-jong** [comment]
Should be fixed in the latest staging. Please reopen if the issue still exists after 7.3 release.
