### ISSUE TITLE
Server crash on look at stockpile?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#6321]
```
--BEGIN DUMP--
Dump Time
03/16/2018 17:39:40

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC QueryInteraction on StockpileObject!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Objects.WorldObject.QueryInteraction(Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--
```

**Comment by metachronism** [comment]
closing as no repro, need more steps (likely related to duplicate stockpile bugs too)
