### ISSUE TITLE
USER ISSUE: Multiple people spam eating from the same stack, crash

### ISSUE THREAD

**Issue by Zarcos** [StrangeLoopGames/EcoIssues#6341]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. 2 People spamming right-click (eat) on Corn Seed from chest... 

**Expected behavior:**

**Actual behavior:**
Caught exception:

<size=60.00%>Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC UseStack on AuthorizationInventory!

Changes could not be applied, the requested operation would result in an invalid inventory state.

Stack:
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.UseStack(ItemStack stack, Player player)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>

**Comment by MarjieAVolk** [comment]
Fixed in 7.3
