### ISSUE TITLE
USER ISSUE: Exception when opening chest

### ISSUE THREAD

**Issue by darkshad9999** [StrangeLoopGames/EcoIssues#6391]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Unknown tried to reproduce it didnt reproduce	

**Expected behavior:**
Noexeception I should be able to open my storage chest without getting this error.

**Actual behavior:**
So I was opening my storage chests in my house I have several of them stacked up and this error showed up.

I can't get it to reproduce though! 

Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Value cannot be null.
Parameter name: item

Stack:
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   at Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients

**Comment by MarjieAVolk** [comment]
Same as https://github.com/StrangeLoopGames/EcoIssues/issues/5328

Fixed in 7.3
