### ISSUE TITLE
Repetative Error that times out players and crashes the server. (Couldn't find where if addressed elsewhere)

### ISSUE THREAD

**Issue by PerksPrisoner** [StrangeLoopGames/EcoIssues#6418]
This is from console. It repeats constantly and I can't find a way to prevent it. You can just change out the players name and the error is otherwise the same.

Stack:

   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)

   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)

   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)

   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)

   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)

   at Eco.Gameplay.Players.Player.SendInitialState(BSONObject obj, INetObjectViewer viewer)

   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)

   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)

   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

</size>]...

[01:38] Caught update exception from xEMOx Cut_n_iBleed!  Disconnecting...

[01:38] Disconnecting client [reason: Caught exception:

 

<size=60.00%>Value cannot be null.

Parameter name: item

**Comment by MarjieAVolk** [comment]
Same as https://github.com/StrangeLoopGames/EcoIssues/issues/5328

Fixed in 7.3
