### ISSUE TITLE
USER ISSUE: Beta Staging - Hammer a chest with inventory

### ISSUE THREAD

**Issue by bruteman** [StrangeLoopGames/EcoIssues#6458]
**Version:** 0.7.3.0 beta staging-1c5d112f

**Steps to Reproduce:**
put items in a chest (this one was wood pulp) 
Pull out stone hammer and try and pick up the chest.

**Expected behavior:**
put items into your inventory and pick up the chest.

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Property.PropertyManager.IsAuthorized(User user, Vector3i pos, IInteractable target, String action)
   at Eco.Gameplay.Items.AuthorizationInventory.CanMoveItems(Type itemType, Int32 delta, User user)
   at Eco.Gameplay.Items.Inventory.CheckAuthForMove(ItemStack source, ItemStack target, User user)
   at Eco.Gameplay.Items.InventoryChangeSet.MoveItemsInternal[TKey](Type itemType, Int32 quantity, Inventory source, Inventory destination, Func`2 sourceStackPredicate, Func`2 sourceStackOrder)
   at Eco.Gameplay.Components.StorageComponent.OnPickUp(Player player, InventoryChangeSet playerInvChanges)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.Objects.WorldObject.PickUp(Player player)
   at HammerItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by bruteman** [comment]
hammer anything with any kind of status and it crashes the server this includes campfires with no inventory in them but remaining burn time.
