### ISSUE TITLE
USER ISSUE: Stockpile Placing Crash

### ISSUE THREAD

**Issue by ahollist** [StrangeLoopGames/EcoIssues#6473]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Clear an area for a stockpile, with one or two walls being directly next to stockpile edges.
2. Place stockpile with two edges touching, but not inside, the walls (in this case dirt).	

**Expected behavior:**
Placed a stockpile. 

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60.00%>Exception has been thrown by the target of an invocation.
The given key was not present in the dictionary.


Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, String memberName)
   at Eco.Core.Controller.ControllerManager.GetChanges(INetClient client)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
</size>
```

**Comment by metachronism** [comment]
verified this is working - unsure how the above could have happened, but it seems fixed now
