### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by Smitth** [StrangeLoopGames/EcoIssues#6522]
Hi, I have some crash dumps from when my server hosted by pingperfect (all vanilla settings) 
These happend a few minutes appart and required a server restart. Also happend a few days ago Thanks in advance.

--BEGIN DUMP--
Dump Time
03/26/2018 20:25:42
 
Exception
System.ArgumentNullException: Value cannot be null.
Parameter name: item
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Eco.Shared.Networking.INetObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
 
--END DUMP--

--BEGIN DUMP--
Dump Time
03/26/2018 20:21:02
 
Exception
System.ArgumentNullException: Value cannot be null.
Parameter name: item
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Eco.Core.Controller.ControllerInstanceInfo.TryBind(INetClient client)
   at Eco.Core.Controller.ControllerManager.TryBindController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.WorldObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()
 
--END DUMP--

**Comment by MarjieAVolk** [comment]
Thank you - This will be fixed in 7.3 :)  Should be released tomorrow.

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5328
