### ISSUE TITLE
USER ISSUE: /ownnone

### ISSUE THREAD

**Issue by ZeskaN** [StrangeLoopGames/EcoIssues#6538]
**Version:** 0.7.3.0 beta staging-e0fb66f4

**Steps to Reproduce:**
/ownnone
with no playername in order to unclaim everything

**Expected behavior:**
unclaimed every plot I own

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60,00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Systems.Chat.AdminCommands.<>c__DisplayClass45_0.<OwnNone>b__0(PropertyPlot x)
   at Eco.Shared.Utils.ArrayExtensions.ForEach[T](T[] enumeration, Action`1 action)
   at Eco.Gameplay.Systems.Chat.AdminCommands.OwnNone(User user, User otherPlayer)
</size>
```

**Comment by MarjieAVolk** [comment]
@craig-jong I think your recent change fixed this?

**Comment by craig-jong** [comment]
I just tried this command and it seems to work. Please reopen it if it still doesn't work in a new build of the game.
