### ISSUE TITLE
Server crash in WorldLayerSync

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#654]
--BEGIN DUMP--
Dump Time
10/23/2016 16:37:26

Exception
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Eco.Simulation.ExternalInputs.WorldLayerSync.KillAnimals(List`1 patch, SpeciesLayer layer, Int32 toRemove)
   at Eco.Simulation.ExternalInputs.WorldLayerSync.SyncLayerPatch(Vector2i layerPos, SpeciesLayer layer, Func`4 tryCreate, Action`3 remove)
   at Eco.Simulation.ExternalInputs.WorldLayerSync.<>c__DisplayClass13_2.<Tick>b__14(Vector2i layerXZ)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Simulation.ExternalInputs.WorldLayerSync.<Tick>b__13_13(SpeciesLayer layer)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Simulation.ExternalInputs.WorldLayerSync.Tick(Boolean worldInteraction)
   at Eco.WorldLayerSystem.WorldLayerSimulation.ForceTick(Boolean worldInteraction)
   at Eco.WorldLayerSystem.WorldLayerSimulation.TryTick(Double time)
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by metachronism** [comment]
closing as have not seen this issue in a few weeks
