### ISSUE TITLE
Server crash during stress test

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6546]
```
Exception
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary2.get_Item(TKey key)
   at Eco.Gameplay.Components.LinkComponent.GetLinkSettings(String username, WorldObject linkedObj)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable1 source, Func2 keySelector, Func2 elementSelector, IEqualityComparer1 comparer)
   at Eco.Gameplay.Components.LinkComponent.GetLinkedComponents(User user)
   at Eco.Gameplay.Components.LinkComponent.GetSortedLinkedComponents(User user)
   at Eco.Gameplay.Components.StoreComponent.GetLinkedInventories(User user)
   at Eco.Gameplay.Components.StoreComponent.UpdateStock(Boolean initializing)
   at Eco.Gameplay.Components.StoreComponent.Tick()
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by MarjieAVolk** [comment]
Literally how is this possible :P
