### ISSUE TITLE
USER ISSUE: Disconnected from game due to excavator

### ISSUE THREAD

**Issue by silkysmoothnuts** [StrangeLoopGames/EcoIssues#6611]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. Join random server
2. Find someone's excavator
3. Attempt to drive, even without permissions
4. Error message

**Expected behavior:**
Tell me I couldn't enter

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by SeanAtr0n** [comment]
fixed in an upcomming hotfix
