### ISSUE TITLE
USER ISSUE: Small Cart Exception Error

### ISSUE THREAD

**Issue by ScreenFlare** [StrangeLoopGames/EcoIssues#6620]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. Open Eco
2. Click Continue (hosting game for Steam friends)
3. Wait until world loads
4. Press E on small cart owned by another player

**Expected behavior:**
It should have given me a message telling me I can't use the small cart because it's owned by another player.

**Actual behavior:**
The following error message popped up:
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
This should be fixed now :)
