### ISSUE TITLE
USER ISSUE: Can't cut tree

### ISSUE THREAD

**Issue by MigzGit** [StrangeLoopGames/EcoIssues#6621]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Try to cut a young tree.

**Expected behavior:**
The tree disapear

**Actual behavior:**
The game crash ! and :

The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
Should be fixed in the next hotfix (https://github.com/StrangeLoopGames/EcoIssues/issues/5619)
