### ISSUE TITLE
USER ISSUE: Openning chest 

### ISSUE THREAD

**Issue by fartwizard** [StrangeLoopGames/EcoIssues#6622]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Tried to open chest not owned by me.
Crashed.

**Expected behavior:**
Said I do not have rights to the chest, and not crash.

**Actual behavior:**
The following error message popped up:Caught exception

<size=60.00%>Object reference not set to an instance of an object.

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
This should be fixed now :)
