### ISSUE TITLE
server dont show with ip

### ISSUE THREAD

**Issue by Drakemilember** [StrangeLoopGames/EcoIssues#6630]
cant find server in public server but can find lan one and this is the crash report i get when i tried a new world default with my ip in it

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Eco.WorldGenerator.WorldGeneratorPlugin.InitModules(Module module, Random randomizer)
   at Eco.WorldGenerator.WorldGeneratorPlugin.CreateWorld()
   at Eco.WorldGenerator.WorldGeneratorPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

**Comment by metachronism** [comment]
@Drakemilember looks like the config for the world generator is broken or messed up.  You will need to refresh that config file (located in Server/Configs) and then your world should generate properly.
