### ISSUE TITLE
CLIENT ISSUE: Inherited/whitelisted Objects are Kicking Client

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#6649]
So, TinyTina and I may of found a problem.
If you have a door and have the Auth set to Inherited or Whitelisted and someone not on that door tries to open it they get an error and get kicked. This is in the new update (7.3.0) and test on multiple servers...

+Seems to be an issue with anyone using anything when they arent on the Inherited or Whitelist. We have tested doors, powered carts, and stock piles and signs.

Caught exception

<size=60.00%>Object reference not set to an instance of an object.

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>

**Comment by MarjieAVolk** [comment]
This is fixed now.  Thanks!
