### ISSUE TITLE
USER ISSUE: User can not attempt to open someone else's chest 

### ISSUE THREAD

**Issue by LexCaputo** [StrangeLoopGames/EcoIssues#6711]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. find a storage chest that does not belong to you
1. Attempt to open it
1. note it logs you out with an error

**Expected behavior:**
User should get a validation error if they try to open a chest that does not belong to you

**Actual behavior:**
Currently it just logs you out and gives you an exception error.
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```
##ADDITIONAL NOTES
I'm not quite sure if this is what triggered the issue, this is just exactly what I did right before it logged me out

**Comment by MarjieAVolk** [comment]
This is fixed now :)
