### ISSUE TITLE
USER ISSUE: WOOOOD

### ISSUE THREAD

**Issue by Avamarine** [StrangeLoopGames/EcoIssues#6720]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Loaded in
Turned
Walked to a log from a tree
Hit E
Crash

**Expected behavior:**
Picked up the wood

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
We are hoping this is fixed in the upcoming hotfix today 🤞 (see https://github.com/StrangeLoopGames/EcoIssues/issues/3752)
