### ISSUE TITLE
Voting Token Crashes Me

### ISSUE THREAD

**Issue by NexusNovaz** [StrangeLoopGames/EcoIssues#6734]
Caught exception

<size=60.00%>Attempt by method 'Eco.CTK.Items.TokenItem.OnUsed(Eco.Gameplay.Items.ItemStack, Eco.Gameplay.Players.Player)' to access method 'Eco.Gameplay.Items.ItemStack.get_Parent()' failed.

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>

**Comment by ecoemmeck** [comment]
I believe this is part of clays toolkit. This should be fixed once eco 7.3.1 is released

**Comment by MarjieAVolk** [comment]
Ah yes, ItemStack.Parent was made public in a hotfix.
