### ISSUE TITLE
USER ISSUE: Trying to use an item you don't have permission on causes a stack exception

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#6735]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Try to use an item you can't

**Expected behavior:**
It should have said you can't use this

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.


Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
This is fixed now :)

**Comment by CuAnnan** [comment]
Many thanks
