### ISSUE TITLE
USER ISSUE: Nullpointer?

### ISSUE THREAD

**Issue by Denise-Bos** [StrangeLoopGames/EcoIssues#6744]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. Have a carpentry table that you have no access to (other user is owner)
2. Click the carpentry table (it will be red)

**Expected behavior:**
It should just say you don't have access?

**Actual behavior:**
The following error message popped up:
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
Fixed in 7.3.1
