### ISSUE TITLE
USER ISSUE: crash client

### ISSUE THREAD

**Issue by FrancoisECO** [StrangeLoopGames/EcoIssues#6780]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at Eco.Simulation.Agents.Plant.Destroy()
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
when i tried to cut a baby tree with no dirt at his feet
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at Eco.Simulation.Agents.Plant.Destroy()
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment]
We believe this is fixed in the next hotfix (https://github.com/StrangeLoopGames/EcoIssues/issues/5619)
