### ISSUE TITLE
USER ISSUE: crash on underwater tree axing

### ISSUE THREAD

**Issue by lashtear** [StrangeLoopGames/EcoIssues#6785]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Find a tree underwater
2. Whack its leaves with an axe

**Expected behavior:**
Not sure, probably shouldn't be trees underwater.

**Actual behavior:**
The following error message popped up:
```
Caught exception

Object reference not set to an instance of an object.

   at Eco.Simulation.Agents.Plant.Destroy()
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
```

**Comment by lashtear** [comment]
Possible dup of #6780

**Comment by MarjieAVolk** [comment]
We believe this is fixed in the next hotfix (https://github.com/StrangeLoopGames/EcoIssues/issues/5619)
