### ISSUE TITLE
USER ISSUE: Cutting down a baby tree causes local client crash

### ISSUE THREAD

**Issue by theDeus** [StrangeLoopGames/EcoIssues#6793]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Find baby tree. Unknown tree type.
Attempt to cut it down.
Client crashes.

**Expected behavior:**
Baby tree should go away

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at Eco.Simulation.Agents.Plant.Destroy()
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by theDeus** [comment]
![20180331000856_1](https://user-images.githubusercontent.com/1639160/38160800-dd300af2-3477-11e8-9d33-2699d0c9fb29.jpg)
![20180331000849_1](https://user-images.githubusercontent.com/1639160/38160802-de6c3de6-3477-11e8-8db2-9fda79de08d4.jpg)

**Comment by MarjieAVolk** [comment]
We believe this is fixed in the next hotfix (https://github.com/StrangeLoopGames/EcoIssues/issues/5619)
