### ISSUE TITLE
USER ISSUE: Rescue my rice!

### ISSUE THREAD

**Issue by CaptainKnorke** [StrangeLoopGames/EcoIssues#6808]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. a bad wild tree has invaded my rice field and try to grow there.
2. my army (my axe and the great Captain Knorke (me)) try to cut him down.
3. the wild bad baby tree, hacked your game to defend himself and kicked me from the server with the war declaration that you find below.

**Expected behavior:**
Kick president Trump and look at the unity code, please. And hurry up, because i am armed with german sausages and a pot of mustard!

**Actual behavior:**
Caught exception

<size=60,00%>Object reference not set to an instance of an object.

   at Eco.Simulation.Agents.Plant.Destroy()
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>

**Comment by MarjieAVolk** [comment]
We believe this is fixed in the next hotfix (https://github.com/StrangeLoopGames/EcoIssues/issues/5619)
