### ISSUE TITLE
USER ISSUE: Chope small Tree

### ISSUE THREAD

**Issue by spykees** [StrangeLoopGames/EcoIssues#6832]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Chop small tree after restarting server

**Expected behavior:**

**Actual behavior:**
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at Eco.Simulation.Agents.Plant.Destroy()
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
Sorry for bad English

**Comment by MarjieAVolk** [comment]
We believe this is fixed in the next hotfix (https://github.com/StrangeLoopGames/EcoIssues/issues/5619)
