### ISSUE TITLE
Server Crash - Laws - Districts

### ISSUE THREAD

**Issue by syhrus** [StrangeLoopGames/EcoIssues#6842]
Hey yall, so I think we encountered a bug that crashes the server. Here's the steps we took to "achieve" it:

Define a district
Start a law vote for a law specific to the district
Start a definition for new districts
Pass the law first proposed.
Pass the law to redefine districts.
Error we're getting on the server logs:
nhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.GetDistricts()
at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DistrictDropDown.IdToSelectedData(String id)
at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown1.RefreshSelectedData() at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown1.GetSelectedData()
at System.Linq.Enumerable.WhereSelectListIterator2.MoveNext() at System.Linq.Enumerable.<SelectManyIterator>d__172.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext() at System.Linq.Enumerable.<DistinctIterator>d__641.MoveNext()
at System.Linq.Enumerable.<IntersectIterator>d__701.MoveNext() at System.Linq.Enumerable.Any[TSource](IEnumerable1 source)
at Eco.Gameplay.LegislationSystem.LawLogic.PassedActions.DistrictEditor.IsValidSelf()
at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValid()
at System.Linq.Enumerable.WhereSelectArrayIterator2.MoveNext() at System.Collections.Generic.List1.InsertRange(Int32 index, IEnumerable1 collection) at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValid() at System.Linq.Enumerable.WhereSelectArrayIterator2.MoveNext()
at System.Collections.Generic.List1.InsertRange(Int32 index, IEnumerable1 collection)
at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValid()
at System.Linq.Enumerable.WhereSelectArrayIterator2.MoveNext() at System.Collections.Generic.List1.InsertRange(Int32 index, IEnumerable1 collection) at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValid() at System.Linq.Enumerable.WhereSelectArrayIterator2.MoveNext()
at System.Collections.Generic.List1.InsertRange(Int32 index, IEnumerable1 collection)
at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValid()
at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext() at System.Collections.Generic.List1.InsertRange(Int32 index, IEnumerable1 collection) at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValid() at System.Linq.Enumerable.WhereSelectArrayIterator2.MoveNext()
at System.Collections.Generic.List1.InsertRange(Int32 index, IEnumerable1 collection)
at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValid()
at Eco.Gameplay.Items.Law.OnLegislationDeserialized()
at Eco.Gameplay.Legislation..ctor()
--- End of inner exception stack trace ---
at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
at System.Activator.CreateInstance(Type type, Object[] args)
at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
at Eco.Server.PluginManager.<.ctor>b__10_3()
at System.Threading.Tasks.Task.Execute()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
at Eco.Server.PluginManager..ctor()
at Eco.Server.Startup.Start(String[] args)
at Eco.Server.MainClass.Main(String[] args)

Have fun with that. I'm going to attempt surgery on the laws file.

**Comment by Murph90210** [comment]
I had the exact same issue, my only option was to blow away the Laws files data

**Comment by syhrus** [comment]
Yep I ended up rolling back the world. We redid the laws and admin passed them in the right order.

**Comment by MarjieAVolk** [comment]
Could you give me the save file where this happens?

**Comment by syhrus** [comment]
No worries, Github only lets me upload <10MB files, so here's a link:

http://www.mediafire.com/file/p3o5hffk53fas3q/Game.zip
