### ISSUE TITLE
USER ISSUE: Tree causing crash

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#6863]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Try to chop a tree, CRASH, try to devtool the tree CRASH

**Expected behavior:**
choped up

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at Eco.Simulation.Agents.Plant.Destroy()
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at DevtoolItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment]
We believe this is fixed in the next hotfix (https://github.com/StrangeLoopGames/EcoIssues/issues/5619)
