### ISSUE TITLE
USER ISSUE: Problem with a birch tree

### ISSUE THREAD

**Issue by xciting** [StrangeLoopGames/EcoIssues#6879]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
not sure. i only tried to cut down a random branch of a birch tree. a friend also tried to cut the whole tree and practically got the same error

**Expected behavior:**
when cutting a tree it should result in a cutted tree not a disconnect with error, right.

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60,00%>Object reference not set to an instance of an object.

   at TreeEntity.TryDamageBranch(TreeBranch branch, Int32 branchID, Single amount)
   at TreeEntity.TryDamageBranch(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/3752?
