### ISSUE TITLE
USER ISSUE: Crash when chopping shrub on my farmland

### ISSUE THREAD

**Issue by CalQL8ed-K-OS** [StrangeLoopGames/EcoIssues#6927]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
I tried to chop a shrub that was on my farmland, game crashed

**Expected behavior:**
not crashed :)

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at Eco.Simulation.Agents.Plant.Destroy()
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by SeanAtr0n** [comment]
will be fixed in 7.3.2
