### ISSUE TITLE
USER ISSUE: Bush crash

### ISSUE THREAD

**Issue by OrangeeAble** [StrangeLoopGames/EcoIssues#6938]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Find small bush
2. Break with Iron axe

**Expected behavior:**
It should have broke, instead it kicks you off the server and errors

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at Eco.Simulation.Agents.Plant.Destroy()
   at Eco.Simulation.Agents.Tree.Destroy()
   at TreeEntity.Destroy()
   at TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   at Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   at Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment]
Same as https://github.com/StrangeLoopGames/EcoIssues/issues/5619, though I'm starting to wonder if this isn't a different issue now, since I think that fix was already released.
