### ISSUE TITLE
USER ISSUE: Picking up log caught exception 0.7.3.1 Beta

### ISSUE THREAD

**Issue by darkshad9999** [StrangeLoopGames/EcoIssues#6944]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Go over and pick up an already cut piece of wood which is sitting on the ground

**Expected behavior:**
That there would be no exception when trying to pick up a log which is already cut and
sitting on the ground.

**Actual behavior:**
Caught exception the wood was already cut and sitting on the ground and
was cut. This may be a different exception than the one from when you
are cutting the tree down.

Now I can't get it to reproduce again I tried. 

Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>

**Comment by darkshad9999** [comment]
Ok so after picking up a few more logs sitting on the ground the client crashed again a 2nd time.
Now this is just getting annoying.  It doesn't seem to matter if I am in third person or first person mode 
it seems to always crash.  It is April 3 2018 at about 4:05 PM MST (GMT-0700) so now I am able to reproduce it. 

Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>

**Comment by MarjieAVolk** [comment]
Should be fixed in next hotfix, later today
