### ISSUE TITLE
USER ISSUE: Crash when picking up log

### ISSUE THREAD

**Issue by dlouwers** [StrangeLoopGames/EcoIssues#6953]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Pick up log

**Expected behavior:**
Log carried

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>
```

**Comment by MarjieAVolk** [comment]
This should be fixed in 7.3.2
