### ISSUE TITLE
[SERVER ISSUE] System.Threading.ThreadAbortException: Thread was being aborted.

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#6996]
`--BEGIN DUMP--
Dump Time
04/05/2018 16:46:59

Exception
System.Threading.ThreadAbortException: Thread was being aborted.
   at Eco.Stats.StatDatabase.DoDatabaseRead[T](Func`1 action, T defaultVal)
   at Eco.Gameplay.Players.WelcomeMessage.<>c__DisplayClass2_0.<Get>b__2(<>f__AnonymousType13`2 <>h__TransparentIdentifier0)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Systems.Tooltip.TooltipExtensions.FoldoutList(IEnumerable`1 list, LocString itemNounSingular, Int32 max)
   at Eco.Gameplay.Players.WelcomeMessage.Get(Player player)
   at Eco.Gameplay.Systems.Chat.ChatManager.Eco.Shared.Networking.INetObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_1()

--END DUMP--`

**Comment by Last2Night** [comment]
Dear devs, 
This is not even funny anymore, server software is extremely unstable for a server only game. With every bug fix introduced by your patching, you also introduce 2 new bugs and im not talking about minor problems, im talking about major server stability issues. Im hosting ECO since its release on Steam and we havnt had a single somewhat stable server software version through those long 4 months. If you want to have a testing platform for the game, make sure its stable and not crashing every moment. Im terrified on what major issues transport content update will introduce, i hope you run a series of changes in your priorities and stop releasing content and minor bugs updates until server software is actually stable.
Thank you.

**Comment by Dreepa** [comment]
For the record: I was playing at that time on that server. What I did was press L, and pass laws.
Webbrowser opened. I was able to set up "prevent action - when claiming property on district "districtname" 

Then I clicked on the follow up line: "allow" and changed it to "condition". That is when the webUI stopped responding to any input.
Directly there after I got disconnected from the game. Server shown as offline.

I waited, and reconnected. I opened the webinterface again. This time I didn't even get to see the interface, but only a green screen with "loading". Then the loading disappeared, and there was just the green screen.

I then got disconnected from the game again. Server shown as offline for 20 seconds. When the server was listed again, I reconnected, this time stuck on "entering world".

**Comment by Last2Night** [comment]
I have disabled Stats in hopes it increases the stability.

**Comment by Dreepa** [comment]
The server crash can be reliably reproduced. Just did it again.

**Comment by Last2Night** [comment]
To be more precise what @Dreepa did was open laws via in-game and it immediately crashed the server even thou Stats are disabled.

Disabling Stats brought the server to somewhat stable state (excluding laws window crashing the server), please take care of the Stats problems prior to adding more content to the game. Stats control very important aspect of the game - Government. 7.3 is all about bugs fixing and stabilization, so lets use this branch accordingly, I would like too see Stats fixed before we head into 7.4 no matter how long it takes.
Thank you.

**Comment by MarjieAVolk** [comment]
Okay - the first crash you posted was in the welcome message.  If the second crash was related to opening the laws window, can you share that crash?  I assume it is different.

Also, if your save file repros the issue consistently, could you send it to us?

**Comment by Last2Night** [comment]
@metachronism @MarjieAVolk 
It left no dump files, more over it didnt even open a typical window with "EcoServer.exe stopped responding...". Thats why I updated this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/5579

Game.eco: https://drive.google.com/open?id=16PV9pnBtrHLzinkcrqLJtZJweo2rSriA
Game.db: https://drive.google.com/open?id=1YdkUimwIHEygIeN-lJpdprig_c5KNSoI

**Comment by Dreepa** [comment]
Second crash was the same. I just was too sleepy and totally forgot about it. Shame on me.

**Comment by MarjieAVolk** [comment]
Okay, well that crash should only be triggered by someone logging in, might not be related to opening the laws window at all.  Thanks for the save!

**Comment by Dreepa** [comment]
![image](https://user-images.githubusercontent.com/37662083/38447140-01880bc8-39fc-11e8-9f51-ea0c38845577.png)

**Comment by Dreepa** [comment]
Update:

We did some more tests. 
-Create a new (small) world
-Have just 3 players join.
-Setup 2 claims
-Setup district over that claim, with the same naming as before.
-Propose the same law as seen above.

-> When proposing the law, when selecting "condition" in the lower button, the server CPU spikes x10 - x20 and the game lags for a moment.

Since this new world is small and without player content, translating this CPU spike to our old (large) world could probably be a hefty calculation. In the old world everything was busy and a lot of claims and player items were inside the refered district, that the "condition" button needs to fetch to display for its sub-options.

Maybe this helps in any way.

**Comment by Last2Night** [comment]
@metachronism @MarjieAVolk 
A bit of extra info to add to @Dreepa report.
We run on 10 cores Intel Xeon E5-2630 v4 2.2GHz, the size of the world we performed our tests to duplicate the crash with no dump files was 44x44. EcoServer.exe was consuming 0.4%-0.6% CPU power, while during "condition" selection as described by @Dreepa it skyrockets to 10%-12% CPU usage for a few seconds then going back down to 0.4%. Our live word has a size of 240x240 and consumes 10%-20% of CPU power during regular operation while selecting "condition" instantly closes EcoServer.exe
Now the question is why is it instantly crashing the software instead of recovering after CPU has finished performing all the operations even if it takes 10 minutes under 100% CPU usage.

**Comment by gabeux** [comment]
Above reports might have been caused due to district laws causing instabilities in 7.3.2. 
If the problem still persists in 7.3.3 [District laws were fixed], then it's something else. 
Plenty of users have the inactivity issues and a workaround is to disable the stat tracking.

**Comment by TrueBale** [comment]
Hey, as @gabeux have said, there have been instability issues that are somewhat similar to this one. The first time it happened, the server became unresponsive when I tried to enable a law that said prevent craft where item is acorn, prevent craft where item is cedar seed - and then I got kicked due to inactivity, which triggered the following error on the server:

```
Exception
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_0()
```

This error also comes up when you try to reconnect (using either continue or join - regardless of whether the client has been restarted or not), get stuck on "Entering World" (which is very likely) and then ALT+F4 out of your misery. 

I have two other errors that have been logged within the timespan the server was unresponsive. I don't know what happened on the server at that moment or what a user might have done, etc.:

```
Exception
System.Exception: Could not find matching method ShouldSelectUser on type AnimalEntity taking 0 parameters.
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_0()
```
```
Exception
System.Threading.ThreadAbortException: Thread was being aborted.
   at Eco.Stats.StatDatabase.DoDatabaseRead[T](Func`1 action, T defaultVal)
   at Eco.Gameplay.Players.WelcomeMessage.<>c__DisplayClass2_0.<Get>b__2(<>f__AnonymousType13`2 <>h__TransparentIdentifier0)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Systems.Tooltip.TooltipExtensions.FoldoutList(IEnumerable`1 list, LocString itemNounSingular, Int32 max)
   at Eco.Gameplay.Players.WelcomeMessage.Get(Player player)
   at Eco.Gameplay.Systems.Chat.ChatManager.Eco.Shared.Networking.INetObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_1()
```

**Comment by MarjieAVolk** [comment]
I am not sure what is going on with the second error, that one is very bizarre.  The third one matches the OP error.  I still have not seen this one in person, and I'm not aware that anything we've done would have addressed it, thus why this bug is still open, but reducing the priority a bit since this one's been around for a while and hasn't been reported very often.
