### ISSUE TITLE
[SERVER ISSUE 7.3.2] Exception System.Threading.ThreadAbortException

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#7052]
```
--BEGIN DUMP--
Dump Time
04/07/2018 17:54:22

Exception
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_0()

--END DUMP--
```

**Comment by MarjieAVolk** [comment]
I'm guessing this is the same as https://github.com/StrangeLoopGames/EcoIssues/issues/6996 - we had some changes to our stack traces recently that confused some things, but the message is the same as that one, only place I have seen that message, so I think that is the same.
