### ISSUE TITLE
server wont boot

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#7062]
Exception
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Eco.Gameplay.Components.PowerGrid.Join(PowerGridComponent componentA, PowerGridComponent componentB)
   at Eco.Gameplay.Components.PowerGridComponent.<>c__DisplayClass44_0.<LinkToGrid>b__1(PowerGridComponent component)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Components.PowerGridComponent.<LinkToGrid>b__44_0(WorldObject worldObject)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Components.PowerGridComponent.LinkToGrid()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass13_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__1(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Eco.Gameplay.Components.PowerGrid.Join(PowerGridComponent componentA, PowerGridComponent componentB)
   at Eco.Gameplay.Components.PowerGridComponent.<>c__DisplayClass44_0.<LinkToGrid>b__1(PowerGridComponent component)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Components.PowerGridComponent.<LinkToGrid>b__44_0(WorldObject worldObject)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Components.PowerGridComponent.LinkToGrid()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass13_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__1(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Inner Exception
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Eco.Gameplay.Components.PowerGrid.Join(PowerGridComponent componentA, PowerGridComponent componentB)
   at Eco.Gameplay.Components.PowerGridComponent.<>c__DisplayClass44_0.<LinkToGrid>b__1(PowerGridComponent component)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Components.PowerGridComponent.<LinkToGrid>b__44_0(WorldObject worldObject)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Components.PowerGridComponent.LinkToGrid()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass13_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__1(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Eco.Gameplay.Components.PowerGrid.Join(PowerGridComponent componentA, PowerGridComponent componentB)
   at Eco.Gameplay.Components.PowerGridComponent.<>c__DisplayClass44_0.<LinkToGrid>b__1(PowerGridComponent component)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Components.PowerGridComponent.<LinkToGrid>b__44_0(WorldObject worldObject)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Components.PowerGridComponent.LinkToGrid()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass13_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__1(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

--END DUMP--

only thing i can think of trying is to delete everyone's generators but i really don't want to do that 

EDIT 1 ive deleted all wind turbines and solar generators and still have the same issue at this stage im not sure how to get the server to boot again

EDIT 2 deleted all electric wall lamps and street lamps some outcome

EDIT 3 deleted all electric world objects still wont load.  im out of ideas for now

EDIT 4 also tried removing the mods folder and placing a fresh copy of the mods folder in still no good

**Comment by ecoemmeck** [comment]
at this stage it appears it was a compilation with a mod though I'm not 100% sure that's what caused it

**Comment by metachronism** [comment]
@ecoemmeck if you have a copy of this save I'd be happy to take a look

**Comment by ecoemmeck** [comment]
server owner deleted the save and loaded a back up so i no longer have a copy of the world.

we only ended up going back a day or 2
