### ISSUE TITLE
USER ISSUE: Connection failed

### ISSUE THREAD

**Issue by pcking99** [StrangeLoopGames/EcoIssues#7064]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
1. clicked Join
2. clicked Connect on a server i wanted to join

**Expected behavior:**
Come in on the server.

**Actual behavior:**
The following error message popped up:
Caught exception: The given key was not present in the dictionary.
<size=150%>Connection Failed</size>

Caught exception

<size=60,00%>The given key was not present in the dictionary.

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.ModKit.ModContentSync.SendContentFiles(List`1 requestList, INetClient targetClient)
   at Eco.Plugins.Networking.Clients.Client.RequestContent(List`1 requestList)
</size>
```

**Comment by MarjieAVolk** [comment]
Okay, my guess would be that this is a mod problem - maybe there is a mod mismatch between the server and the client?

**Comment by MarjieAVolk** [comment]
🤔 Well okay, thanks for letting us know.
