### ISSUE TITLE
USER ISSUE: Mint placing error

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7127]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
Placed a mint

**Expected behavior:**
Should have placed

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.

   at Eco.Gameplay.Components.MintComponent.InitializeCurrency(Guid currencyId)
   at Eco.Mods.TechTree.MintItem.OnWorldObjectPlaced(WorldObject placedObject)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass13_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_0()
</size>
```

**Comment by johnkslg** [comment]
This was a tricky one to figure out.
If you place down a mint, name the currency, pick a backing item as 'search and select item', it sets backing item to null.  Then picking up and putting down again will cause this crash.
Fixed!
