### ISSUE TITLE
[SERVER ISSUE 7.3.3] System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#7171]
```
--BEGIN DUMP--
Dump Time
04/13/2018 05:29:46

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.EnumerableItemExtensions.<>c.<Describe>b__5_3(IGrouping`2 group)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, String noneText)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, LocString noneText)
   at Eco.Gameplay.Items.EnumerableItemExtensions.Describe(IEnumerable`1 stacks)
   at Eco.Gameplay.Utils.PickerObject.get_Contents()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, String memberName)
   at Eco.Core.Controller.ControllerManager.GetChanges(INetClient client)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_1()

--END DUMP--

```

**Comment by GophTheGreat** [comment]
+1 Steam report: 

"Could not start server:
Every time ECO updates, the single player world I'm on can no longer be accessed.

I get this.

"Could not start server: Object reference not set to an instance of an object"

So...yeah....what do?"

**Comment by D3nnis3n** [comment]
Old issue, should no longer happen.

**Comment by sawfear** [comment]
Got it today with my 2 days old server 

[12:18:12.356] [1] [ Info] [Eco] Failed to load server, Exception was Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Gameplay

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at Eco.Gameplay.Components.FakePlantComponent.UpdatePlantType(User obj)
   at Eco.Mods.TechTree.PlanterPotRoundObject.Initialize()
   at Eco.Gameplay.Objects.WorldObject.BeginInitialize()
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass16_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__0(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)

**Comment by Cllynn** [comment]
Not sure if anyone will see this but we've had a multiplayer server open for about a week with about 30 hours put into it, no mods or moving around files or anything like that. Tried to open it today and got the response "the server has crashed with error "Value cannot be null. (Parameter 'key') and you can't play. Check logs. I did everything I could from google searches, verified files, made sure my game is updated. This is what I found within the logs that has been different.

[15:02:11.665] [29] [ Info] [Eco] Shutdown finished
 
[15:02:11.665] [29] [Error] [Eco] Errors report:
Failed to start the server. Exception was Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'key')
Source:System.Private.CoreLib

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Eco.Stats.LiteDbEnumMapper.SyncWithDatabase()
   at Eco.Stats.LiteDbEnumMapper.Initialize()
   at Eco.Stats.Stats.InitEnumMapper()
   at Eco.Stats.Stats.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo): 1

Hopefully someone can help, anything would be great! Just don't want to start a new server for it to happen all over again.
