### ISSUE TITLE
USER ISSUE: Tried to Pick Up Trash on a Staging Server

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#7179]
**Version:** 0.7.4.0 beta staging-b8e0bc58

**Steps to Reproduce:**
1. Pick up trash.

**Expected behavior:**
It should have picked up the trash.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Objects.GarbageInventoryBlock.get_Inventory()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Gameplay.Objects.GarbageInventoryBlock.GetBSON(InteractionContext context)
   at Eco.Gameplay.Objects.GarbageInventoryBlock.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>
```

**Comment by craig-jong** [comment]
This should be fixed in the next staging version.
