### ISSUE TITLE
USER ISSUE: Caught exception

### ISSUE THREAD

**Issue by Twelve57** [StrangeLoopGames/EcoIssues#7192]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Powered Cart on an asphalt ramp in a cave (~ 9 bloc hight)

**Expected behavior:**
Nothing

**Actual behavior:**
The following error message popped up:
```index was outside the bounds of the array
Caught exception

<size=60,00%>Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.Contains(T item)
   at Eco.Plugins.Networking.Clients.ClientManager.SendEvent(NetworkEvent netEvent, BSONObject bsonObj, INetClient target, INetObject netObj)
   at Eco.Shared.Networking.RPCManager.DoCall(String methodname, INetObject obj, AwaitedQuery query, INetClient target, Object[] args)
   at Eco.Shared.Networking.NetPhysicsEntity.SetPhysicsController(INetObjectViewer owner)
   at Eco.Shared.Networking.NetPhysicsEntity.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_1()</size>
```

**Comment by SeanAtr0n** [comment]
Looks like monitoredobjects would have to be changing in 2 different threads?

**Comment by Twelve57** [comment]
At this time, we have lost approximately 10 or 15 excavators with this issue. 
And I've already founded 4 abandoned Excavators ^^ Cannot find the other at the moment, but it's maybe better to remove all of them in the .eco file ?

**Comment by Twelve57** [comment]
This is the same issue : #7306 
don't know why is duplicated.

**Comment by metachronism** [comment]
fixed
