### ISSUE TITLE
USER ISSUE: CRASH CAUGHT EXCEPTION

### ISSUE THREAD

**Issue by chopperprop** [StrangeLoopGames/EcoIssues#7198]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Caught exception

Creative mode error when objects fill up the head area

**Comment by chopperprop** [comment]
Caught exception

<size=60.00%>Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.ClothingInventory.SetUpSuitCallback(User user)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.TryAddItem(Type itemType, User user)
   at Eco.Gameplay.Objects.RubbleObject`1.TryPickup(Inventory inv)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>

**Comment by metachronism** [comment]
@craig-jong probably only relevant if you use the cheat command, so lowering priority
assigning to you cause you created the command
