### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by jvmcmaster** [StrangeLoopGames/EcoIssues#7212]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Walk up some stairs	

**Expected behavior:**
allowed me to reach the top

**Actual behavior:**
Caught exception

<size=60.00%>Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.EnumerableItemExtensions.<>c.<Describe>b__5_3(IGrouping`2 group)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, String noneText)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, LocString noneText)
   at Eco.Gameplay.Items.EnumerableItemExtensions.Describe(IEnumerable`1 stacks)
   at Eco.Gameplay.Utils.PickerObject.get_Contents()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, String memberName)
   at Eco.Core.Controller.ControllerManager.GetChanges(INetClient client)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_1()</size>

**Comment by johnkslg** [comment]
Fixed!
