### ISSUE TITLE
Game.db in use by other process?  

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7303]
Can find no other process using the stats.db and stats are actually turned off

The server is crashing now ever few minutes on this issue.  Stats are disabled.  What could be trying to write to Game.db?

--BEGIN DUMP--
Dump Time
04/19/2018 18:44:11

Exception
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Eco.Gameplay.Stats.PlayerActions' threw an exception. ---> System.IO.IOException: The process cannot access the file 'D:\TCAFiles\Users\PamelaD\2531\Storage\Game.db' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at LiteDB.FileDiskService.Initialize(Logger log, String password)
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)
   at Eco.Stats.StatDatabase.EnsureIndex[T](IEnumerable`1 fieldNames)
   at Eco.Gameplay.Stats.ConcretePlayerActions.AcceptContractPlayerStatManager..ctor()
   at Eco.Gameplay.Stats.PlayerActions..cctor()
   --- End of inner exception stack trace ---
   at Eco.Gameplay.Stats.PlayerActions.get_ActionManagers()
   at Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventableActionDropDown.DisplayedManagersStatic()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.get_UnsortedOptions()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.IdToDisplayName(String id)
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.RefreshDisplayName()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.Items.Law.Initialize()
   at Eco.Gameplay.Legislation..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_3()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Eco.Gameplay.Stats.PlayerActions' threw an exception. ---> System.IO.IOException: The process cannot access the file 'D:\TCAFiles\Users\PamelaD\2531\Storage\Game.db' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at LiteDB.FileDiskService.Initialize(Logger log, String password)
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)
   at Eco.Stats.StatDatabase.EnsureIndex[T](IEnumerable`1 fieldNames)
   at Eco.Gameplay.Stats.ConcretePlayerActions.AcceptContractPlayerStatManager..ctor()
   at Eco.Gameplay.Stats.PlayerActions..cctor()
   --- End of inner exception stack trace ---
   at Eco.Gameplay.Stats.PlayerActions.get_ActionManagers()
   at Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventableActionDropDown.DisplayedManagersStatic()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.get_UnsortedOptions()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.IdToDisplayName(String id)
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.RefreshDisplayName()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.Items.Law.Initialize()
   at Eco.Gameplay.Legislation..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_3()
   at System.Threading.Tasks.Task.Execute()<---

Inner Exception
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Eco.Gameplay.Stats.PlayerActions' threw an exception. ---> System.IO.IOException: The process cannot access the file 'D:\TCAFiles\Users\PamelaD\2531\Storage\Game.db' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at LiteDB.FileDiskService.Initialize(Logger log, String password)
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)
   at Eco.Stats.StatDatabase.EnsureIndex[T](IEnumerable`1 fieldNames)
   at Eco.Gameplay.Stats.ConcretePlayerActions.AcceptContractPlayerStatManager..ctor()
   at Eco.Gameplay.Stats.PlayerActions..cctor()
   --- End of inner exception stack trace ---
   at Eco.Gameplay.Stats.PlayerActions.get_ActionManagers()
   at Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventableActionDropDown.DisplayedManagersStatic()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.get_UnsortedOptions()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.IdToDisplayName(String id)
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.RefreshDisplayName()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.Items.Law.Initialize()
   at Eco.Gameplay.Legislation..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_3()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Eco.Gameplay.Stats.PlayerActions' threw an exception. ---> System.IO.IOException: The process cannot access the file 'D:\TCAFiles\Users\PamelaD\2531\Storage\Game.db' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at LiteDB.FileDiskService.Initialize(Logger log, String password)
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)
   at Eco.Stats.StatDatabase.EnsureIndex[T](IEnumerable`1 fieldNames)
   at Eco.Gameplay.Stats.ConcretePlayerActions.AcceptContractPlayerStatManager..ctor()
   at Eco.Gameplay.Stats.PlayerActions..cctor()
   --- End of inner exception stack trace ---
   at Eco.Gameplay.Stats.PlayerActions.get_ActionManagers()
   at Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventableActionDropDown.DisplayedManagersStatic()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.get_UnsortedOptions()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.IdToDisplayName(String id)
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.RefreshDisplayName()
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
   at Eco.Gameplay.Items.Law.Initialize()
   at Eco.Gameplay.Legislation..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_3()
   at System.Threading.Tasks.Task.Execute()<---

--END DUMP--

**Comment by pamduncan** [comment]
we actually ended up deleting all the contracts and that helped but we were still crashing several times an hour so .  Finally we deleted all the contract boards and the crashing stopped

**Comment by pamduncan** [comment]
This started happen again when a contact was added to the contract board.  and the server crashed every few minutes until the board was removed

**Comment by metachronism** [comment]
seems contracts related

**Comment by johnkslg** [comment]
Any idea how this could happen Marjie? Perhaps close if no longer reported in crash viewer.

**Comment by MarjieAVolk** [comment]
>> As far as I know, the only things that use the file are the stats api, and backups.  IDK how contracts could be related.  Unless they are using the stats api a lot perhaps.

**Comment by MarjieAVolk** [comment]
Guess I will close as 'mysterious', until we see it again.
