### ISSUE TITLE
USER ISSUE: Shot rabbit and it gave me this bug report

### ISSUE THREAD

**Issue by PaleGhost** [StrangeLoopGames/EcoIssues#7308]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:Caught exception

<size=60.00%>Object reference not set to an instance of an object.
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Simulation.Agents.Animal.Damage(Single amount, DeathType damageSource)
   at Eco.Gameplay.Animals.AnimalEntity.TryApplyDamage(INetObject damager, Single damage, InteractionContext context)
   at ArrowEntity.Hit(NetObjAttachInfo hitAttachInfo, Vector3 position)</size>
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Simulation.Agents.Animal.Damage(Single amount, DeathType damageSource)
   at Eco.Gameplay.Animals.AnimalEntity.TryApplyDamage(INetObject damager, Single damage, InteractionContext context)
   at ArrowEntity.Hit(NetObjAttachInfo hitAttachInfo, Vector3 position)</size>
```

**Comment by metachronism** [comment]
fixed 7.4.0 release
