### ISSUE TITLE
USER ISSUE: Shovel Repair Crashing game

### ISSUE THREAD

**Issue by Oreo246** [StrangeLoopGames/EcoIssues#7319]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
1. Open a repair table
2. Place a stone stovel in
3. Try to repair it with a sufficent supply of stone

**Expected behavior:**
Repaired the Shover

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.Inventory.TryRemoveItems(ItemStack stack, User user)
   at Eco.Gameplay.Components.RepairComponent.Repair(Player player)

Exception has been thrown by the target of an invocation.
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)</size>
```

**Comment by metachronism** [comment]
fixed 7.4.0 release
