### ISSUE TITLE
[SERVER ISSUE 7.3.3] Exception System.Threading.ThreadAbortException

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#7330]
```
--BEGIN DUMP--
Dump Time
04/21/2018 09:25:38

Exception
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at LZ4.LZ4Stream.FlushCurrentChunk()
   at LZ4.LZ4Stream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Eco.Shared.Utils.CompressionUtils.Compress(Byte[] source)
   at Eco.Simulation.WorldLayers.Layers.WorldLayer.get_RawData()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, String memberName)
   at Eco.Core.Controller.ControllerManager.GetChanges(INetClient client)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_1()

--END DUMP--

```

**Comment by metachronism** [comment]
various controller/view changes likely made this bug no longer relevant
