### ISSUE TITLE
Apparent Power Grid issue causes server crash loop [and requires long rollback]

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#7361]
Hello!

A strange issue cropped up on the server I play on. 
After destroying the meteor, people may have went crazy with plopping down power generation objects. This may have caused some issue that got the server in a crashing loop. When trying to restore backup, previous backups also had the issue, making a rollback of around 1 day of playing required.

I don't have my dev environment setup (nor the gamedev experience) to provide more info, so I'll leave the files that the server owner [Revenant#0368] made available to me, and the trace:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Eco.Gameplay.Components.PowerGrid.Join(PowerGridComponent componentA, PowerGridComponent componentB)
   at Eco.Gameplay.Components.PowerGridComponent.<>cDisplayClass44_0.<LinkToGrid>b1(PowerGridComponent component)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action1 action)
   at Eco.Gameplay.Components.PowerGridComponent.<LinkToGrid>b44_0(WorldObject worldObject)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action1 action)
   at Eco.Gameplay.Components.PowerGridComponent.LinkToGrid()
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.<>cDisplayClass13_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b1(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>cDisplayClass42_0`2.<PartitionerForEachWorker>b1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>cDisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner1 source, ParallelOptions parallelOptions, Action1 simpleBody, Action2 bodyWithState, Action3 bodyWithStateAndIndex, Func4 bodyWithStateAndLocal, Func5 bodyWithEverything, Func1 localInit, Action1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable1 source, ParallelOptions parallelOptions, Action1 body, Action2 bodyWithState, Action3 bodyWithStateAndIndex, Func4 bodyWithStateAndLocal, Func5 bodyWithEverything, Func1 localInit, Action1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable1 source, Action1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
```
Game.eco & Dump .zip:
https://drive.google.com/file/d/1-Bd1MlVMMzsUTceZ5pzQeHz_qEvdif7o/view

**Comment by SessionExpired** [comment]
I'm also receiving this same crash loop issue, any insight on whats causing it as rollbacks are a pain as it means the server goes back 8 hours or sometimes even longer.

**Comment by mirasrael** [comment]
Fixed in referred pull request (at least loading time). Let me know if you still have crashes.
