### ISSUE TITLE
[7.4.0 #68e3874b] Trying to open trash bag after leaving game

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7366]
Dropped full trash bag and had to leave game, returned to game and clicked on trash bag to get items and got this instead:

Server encountered an exception:

<size=60.00%>The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Objects.GarbageInventoryBlock.get_Inventory()
   at Eco.Gameplay.Objects.GarbageInventoryBlock.GetBSON(InteractionContext context)
   at Eco.Gameplay.Objects.GarbageInventoryBlock.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>

I had to log off so that a restart could happen on the server, not sure if that mean bag was not saved properly or not

**Comment by craig-jong** [comment]
Should be fixed in the lastest staging
