### ISSUE TITLE
USER ISSUE: unexpected crash

### ISSUE THREAD

**Issue by talamatur** [StrangeLoopGames/EcoIssues#7383]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
dont know,
maybe it has something to do with the contract board and a contract i wan't to accept. I opened the menu y -> contracts, and choose a contract. then a message poped up. you are to far away from contract board.

other possibility is my bloomery with 2 orders and full stockpiles

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60,00%>Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.EnumerableItemExtensions.<>c.<Describe>b__5_3(IGrouping`2 group)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, String noneText)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, LocString noneText)
   at Eco.Gameplay.Items.EnumerableItemExtensions.Describe(IEnumerable`1 stacks)
   at Eco.Gameplay.Utils.PickerObject.get_Contents()
   at Eco.Gameplay.Utils.PickerTracker.get_Contents()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, String memberName)
   at Eco.Core.Controller.ControllerManager.GetChanges(INetClient client)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_1()</size>
```

**Comment by johnkslg** [comment]
Added some tests to this area of the code that should address it.
