### ISSUE TITLE
Probably laser-related: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by TrueBale** [StrangeLoopGames/EcoIssues#7390]
The following error occurred (server did continue to run, no crash):

```
Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.Agents.AI.AITarget.<UpdatePosition>b__32_0()
   at Eco.Shared.Utils.LockUtils.TryLock(Object lockObject, Action ifLockAcquired, Int32 millisecondsTimeout)
   at Eco.Simulation.Agents.AI.AITarget.UpdatePosition()
   at Eco.Simulation.Agents.AI.AITarget.get_Position()
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_1()

--END DUMP--
```

Meteor on this server is deactivated.

**Comment by metachronism** [comment]
not likely laser related - however this code has been changed a bunch since posting, so closing this for now
