### ISSUE TITLE
Garbage crash

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7411]
From dump log on 4-23
Данный ключ отсутствует в словаре. (This key is not in the dictionary.)
   в System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   в Eco.Gameplay.Objects.GarbageInventoryBlock.get_Inventory()
   в Eco.Gameplay.Objects.GarbageInventoryBlock.GetBSON(InteractionContext context)
   в Eco.Gameplay.Objects.GarbageInventoryBlock.OnActInteract(InteractionContext context)
   в Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   в Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by johnkslg** [comment]
Also:
Index was outside the bounds of the array.
   at Eco.Gameplay.Items.GarbageBagBlock.UpdateVisuals()
   at Eco.Gameplay.Items.DecayingInventory.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Gameplay.Garbage.GarbageManager.Tick()
   at Eco.Gameplay.Garbage.GarbagePlugin.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by johnkslg** [comment]
Dozens of these in the crash dump collector

**Comment by craig-jong** [comment]
I need to know when these happened - I recently refactored garbage which should have fixed a lot of these.

**Comment by craig-jong** [comment]
Crashes like these should be fixed - check PR above.
