### ISSUE TITLE
Crash when hitting animal with arrow

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7412]
4-23 dump log
Object reference not set to an instance of an object.
   at C5.IntervalHeap`1.checkHandle(IPriorityQueueHandle`1 handle, Int32& cell, Boolean& isfirst)
   at C5.IntervalHeap`1.Replace(IPriorityQueueHandle`1 handle, T item)
   at Eco.Simulation.Simulation.UpdateElementInQueue(ITickable element)
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Simulation.Agents.Animal.Damage(Single amount, DeathType damageSource)
   at Eco.Gameplay.Animals.AnimalEntity.TryApplyDamage(INetObject damager, Single damage, InteractionContext context)
   at ArrowEntity.Hit(NetObjAttachInfo hitAttachInfo, Vector3 position)

**Comment by SeanAtr0n** [comment]
fixed 7.4
