### ISSUE TITLE
Crash when trying to tick crafting

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7417]
Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.AuthorizationInventory.MakeGameAction(Type itemType, Int32 delta, User user)
   at Eco.Gameplay.Items.AuthorizationInventory.InventoryChanged(User user, IEnumerable`1 changes)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.TryModify(Action`1 callback, User user)
   at Eco.Gameplay.Items.WorkOrder.TryToGiveItems(Inventory destInventory, User performer)
   at Eco.Gameplay.Components.CraftingComponent.Tick()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by MarjieAVolk** [comment]
So I'm assuming the owning object is null.  Or the handle to the owning object.  Which should not be possible, especially since the inventory is accessed through the owning object's tick, so adding a null check would not be appropriate.
