### ISSUE TITLE
Crash accessing MasterServerListing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7419]
Value cannot be null.
Parameter name: address
   at System.Net.IPEndPoint..ctor(IPAddress address, Int32 port)
   at Eco.Plugins.Networking.NetworkServer.<>c__DisplayClass10_0.<RefreshMasterServerListing>b__0(NetOutgoingMessage message)
   at Eco.Shared.Networking.NetMessage.SendMasterServerMessage(NetPeer peer, Byte messageType, Action`1 handler)
   at Eco.Plugins.Networking.NetworkServer.RefreshMasterServerListing(Boolean publicServer)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by metachronism** [comment]
yeah this was my computer
