### ISSUE TITLE
Crash exceeding NetConfiguration.MaximumTransmissionUnit in Lidgren

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7421]
Unconnected messages too long! Must be shorter than NetConfiguration.MaximumTransmissionUnit (currently 1408)
   bei Lidgren.Network.NetPeer.SendUnconnectedMessage(NetOutgoingMessage msg, IPEndPoint recipient)
   bei Eco.Core.Utils.ExceptionExtensions.Dump(Exception exception, String dumpType)
   bei Eco.Plugins.Networking.NetworkServer.<>c__DisplayClass16_0.<ProcessIncomingDataMessage>b__0(Object o)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by MarjieAVolk** [comment]
@elfl0rd reported seeing a very similar stack on 7.4.5 just now.

> server start ok, and if user try to connect - they crash

```
--BEGIN DUMP--
Dump Time
05/17/2018 17:07:53

Exception
Exception: NetException
Message:Unconnected messages too long! Must be shorter than NetConfiguration.MaximumTransmissionUnit (currently 1408)
Source:Lidgren.Network

Lidgren.Network.NetException: Unconnected messages too long! Must be shorter than NetConfiguration.MaximumTransmissionUnit (currently 1408)
   at Lidgren.Network.NetPeer.SendUnconnectedMessage(NetOutgoingMessage msg, IPEndPoint recipient)
   at Eco.Core.Utils.ExceptionExtensions.Dump(Exception exception, String dumpType, String userID)
   at Eco.Plugins.Networking.Client.<.ctor>b__52_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--
```

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/7803

**Comment by MarjieAVolk** [comment]
Okay closing in favor of the one you filed :)
