### ISSUE TITLE
Crash in NetworkServer incoming message

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7423]
The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Plugins.Networking.NetworkServer.<>c__DisplayClass16_0.<ProcessIncomingDataMessage>b__0(Object o)

**Comment by johnkslg** [comment]
Also:

指定されたキーはディレクトリ内に存在しませんでした。
   場所 System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   場所 Eco.Plugins.Networking.NetworkServer.<>c__DisplayClass16_0.<ProcessIncomingDataMessage>b__0(Object o)

**Comment by metachronism** [comment]
fixed
