### ISSUE TITLE
SkidSteer Initialize crash

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7426]
Object reference not set to an instance of an object.
   at Eco.Mods.TechTree.SkidSteerObject.Initialize()
   at Eco.Gameplay.Objects.WorldObject.BeginInitialize()
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.Add(WorldObject worldObject, User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.TryToAdd(Type worldObjectType, User creator, Vector3 position, Quaternion rotation, Boolean validatePlacement, WorldObjectItem item)
   at Eco.Gameplay.Objects.WorldObjectManager.TryPlaceWorldObject(Player player, WorldObjectItem item, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass13_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.<>c__DisplayClass16_0.<ProcessIncomingDataMessage>b__0(Object o)

**Comment by SeanAtr0n** [comment]
works for me?
