### ISSUE TITLE
Crash in thread pool dispatch

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7429]
The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Plugins.Networking.NetworkServer.<>c__DisplayClass16_0.<ProcessIncomingDataMessage>b__0(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by metachronism** [comment]
no longer relvant
