### ISSUE TITLE
Network Exception kicking all players repeatedly

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7430]
This keeps happening on a server and all players are kicked.  Server stays up and running but will not allow connections again for 10-30 minutes or until a reboot is performed.  Server shows 'offline' immediately after this happens in some cases or if it still appears online players get 'connection failed' when thy try to log on.  This goes on for up to 30 minutes and then server shows back up online or allows connections to the game without intervention.  If a reboot is performed during thia time server will allow connections and appear online when it reloads.

--BEGIN DUMP--
Dump Time
04/26/2018 03:11:46

Exception
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<Initialize>b__58_0()

--END DUMP--

**Comment by johnkslg** [comment]
Upon investigation, I found that Thread.Abort calls that were in 7.3.3 are no longer in 7.4, due to the networking system upgrade. So this bug should be fixed in staging. Thanks for the report!
