### ISSUE TITLE
USER ISSUE: Chopped down tree - client crashed

### ISSUE THREAD

**Issue by turnburgler** [StrangeLoopGames/EcoIssues#7456]
**Version:** 0.7.4.0 beta staging-68e3874b

**Steps to Reproduce:**
Forest biome, chopped down oak tree and game crashed mid-fall.

**Expected behavior:**
The tree should have fallen, since I was there to see it.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.HashSet`1.SetCapacity(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at TreeEntity.CollideWithTerrain(Player player, Vector3i position)</size>
```

**Comment by metachronism** [comment]
fixed
