### ISSUE TITLE
USER ISSUE: Exception on teleporting player (who bugged himself outside boundaries?)

### ISSUE THREAD

**Issue by TrueBale** [StrangeLoopGames/EcoIssues#7477]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Normal player:
1. Stand on asphaltramp
2. Try to place an asphaltramp on the already existing asphaltramp (fiddle with snappoints so that you will stand on the low end of the ramp)
3. Repeat until out of boundaries (since it should push you up one block, on top of the new asphalt ramp)

Admin player:
1. Try to teleport bugged player into safe zone with /teleporttarget
2. Fail and get an exception

**Expected behavior:**
Teleported the player to the new position

**Actual behavior:**
The following error message popped up:
```Caught exception

<size=60,00%>Object reference not set to an instance of an object.
   at Eco.Gameplay.Systems.Chat.AdminCommands.TeleportTarget(User user, User otherPlayer, Int32 x, Int32 y, Int32 z)

Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)</size>```
Caught exception

<size=60,00%>Object reference not set to an instance of an object.
   at Eco.Gameplay.Systems.Chat.AdminCommands.TeleportTarget(User user, User otherPlayer, Int32 x, Int32 y, Int32 z)

Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)</size>
```

**Comment by SeanAtr0n** [comment]
Think @Nanders might have already fixed the chat command exception

**Comment by WeaselDog** [comment]
I can't replicate this in the latest version. It appears to have been fixed.
