### ISSUE TITLE
USER ISSUE: Crashed when tried to portal

### ISSUE THREAD

**Issue by Kimrian** [StrangeLoopGames/EcoIssues#7486]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
tried to portal ingame

**Expected behavior:**
Not crash

**Actual behavior:**
Caught exception

<size=60.00%>Object reference not set to an instance of an object.
   at Eco.CTK.Teleport.TpAccept(User user)

Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)</size>

**Comment by metachronism** [comment]
closing this, its a mod bug - I've forwarded the info to Clay though
