### ISSUE TITLE
Ligdren crash: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7512]
From collected crash 
Index was outside the bounds of the array.
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset)
   at Eco.Plugins.Networking.NetworkServer.HandleUnconnectedDataMessage(NetIncomingMessage message)
   at Eco.Plugins.Networking.NetworkServer.<Initialize>b__17_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ironsquishy** [comment]
I would like to add that our server would also have the same issue that would lead into server crash.
