### ISSUE TITLE
Crash in ChatManager

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7518]
Object reference not set to an instance of an object.
   at Eco.Gameplay.Systems.Chat.ChatManager.<>c__DisplayClass36_0.<SetTag>b__0(ChatTagSetting x)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Eco.Gameplay.Systems.Chat.ChatManager.SetTag(ChatTagSetting chatTagSetting, Int32 playerID)

**Comment by johnkslg** [comment]
Fixed
