### ISSUE TITLE
Crash in AI

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7520]
An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Eco.Simulation.Agents.AI.AIStateMachine`1.set_State(AIStateType value)
   at Eco.Simulation.Agents.Animal.SetState[StateType]()
   at Eco.Simulation.Agents.Animal.Kill(DeathType deathType)
   at Eco.Simulation.Agents.Animal.Damage(Single amount, DeathType damageSource)
   at Eco.Gameplay.Animals.AnimalEntity.TryApplyDamage(INetObject damager, Single damage, InteractionContext context)
   at ArrowEntity.Hit(NetObjAttachInfo hitAttachInfo, Vector3 position)

**Comment by SeanAtr0n** [comment]
fixed 7.4
