### ISSUE TITLE
[Server] Connection fails when i try to launch my save file

### ISSUE THREAD

**Issue by MasterJ767** [StrangeLoopGames/EcoIssues#7607]
ECO Version - I'm not sure I play the game through Steam

When I launch my save game file, it says the normal loading screen phrases until it reaches "Starting GameplayStats Plugin..." then the ECO window is minimized. When I open the window again it says "Connecting..." and then "Connection failed". this only happens when I launch this save file and not my other save files. It has been happening ever since my computer crashed whilst the game was running and that save file was open. 

These are screenshots of what happens when i attempt to launch the save file:

![image](https://user-images.githubusercontent.com/22119506/39717506-6166c10a-522b-11e8-9839-9f2850ae32ff.png)
![image](https://user-images.githubusercontent.com/22119506/39717536-7c1f319e-522b-11e8-8862-b0547e710826.png)

Operating system: Windows 10
System Specs: AMD FX(tm)-4350 Quad-core Processor, 4200 Mhz, 2 Cores, 4 logical procesors

I struggled to upload the crash report so I've copied and pasted the text to here of the latest dump:

--BEGIN DUMP--
Dump Time
05/07/2018 19:18:47

Exception
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Ionic.Zip.ZipException: Could not read Storage\Venov.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x0070698F
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   at Ionic.Zip.ZipFile..ctor(String fileName)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Ionic.Zip.ZipException: Could not read Storage\Venov.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x0070698F
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   at Ionic.Zip.ZipFile..ctor(String fileName)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.Execute()<---

Inner Exception
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Ionic.Zip.ZipException: Could not read Storage\Venov.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x0070698F
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   at Ionic.Zip.ZipFile..ctor(String fileName)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Ionic.Zip.ZipException: Could not read Storage\Venov.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x0070698F
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   at Ionic.Zip.ZipFile..ctor(String fileName)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.Execute()<---

--END DUMP--

**Comment by GophTheGreat** [comment]
Your save is corrupted. You might be able to find a backup in D:\Games\Steam\steamapps\common\Eco\Eco_Data\Server\Storage\Backup if the save is old enough.
