### ISSUE TITLE
USER ISSUE: /reward bug

### ISSUE THREAD

**Issue by Greatw00d** [StrangeLoopGames/EcoIssues#7627]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
typed /reward to get daily reward from server mod	

**Expected behavior:**
given an error that i had already recieved a reward

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.CTK.Vote.DoReward(User user)

Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)</size>
```

**Comment by Greatw00d** [comment]
was also riding in a powered cart at the time

**Comment by KyeEco** [comment]
hey @Greatw00d was this from a mod on the server? if so do you know which one? also if you do i would suggest contacting the creator of the mod via their discord name or through the eco forums as most of them can be found there or even on https://eco-mods.com/ the devs can not really help with mods as they may not have made the specific mod you are using,

**Comment by craig-jong** [comment]
This looks like an issue with the mod.

I would also recommend you bring it up with ClayC.
