### ISSUE TITLE
USER ISSUE: [0.7.5.0 edge] HandPlough crash

### ISSUE THREAD

**Issue by Thineboot** [StrangeLoopGames/EcoIssues#7652]
**Version:** 0.7.5.0 beta staging-7be2f02c

**Steps to Reproduce:**

1. fresh install [bleeding_edge_staging]
2. new game
3. /give HandPlough
4. place HandPlough

crash

**Expected behavior:**
placed HandPlough

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.TailingsReportComponent.Initialize()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.FinishInitialize()
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.Add(WorldObject worldObject, User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.TryToAdd(Type worldObjectType, User creator, Vector3 position, Quaternion rotation, Boolean validatePlacement, WorldObjectItem item)
   at Eco.Gameplay.Objects.WorldObjectManager.TryPlaceWorldObject(Player player, WorldObjectItem item, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass13_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.Client.<.ctor>b__53_1()</size>
```

<details>
<summary>Log File</summary>(...previous log truncated...)

ing icons: AssemblyLineItem, HewnLogDoorItem, LumberDoorItem, RoboticAssemblyLineItem, StoneDoorItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AssemblyLineObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, StuffedElkObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at PostProcessingManager.UpdateHypoxia () [0x00000] in <filename unknown>:0 
  at Eco.Shared.View.ISubscriberExtensions.SubscribeAndCall (ISubscriber s, System.String propname, System.Action changedCallback) [0x00000] in <filename unknown>:0 
  at PostProcessingManager.Start () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[00:58] Exception in view notify: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: 
  at (wrapper managed-to-native) UnityEngine.Animator:SetBoolString (string,bool)
  at UnityEngine.Animator.SetBool (System.String name, Boolean value) [0x00000] in <filename unknown>:0 
  at AvatarAnimationManager.UpdateTool () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00000] in <filename unknown>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x00000] in <filename unknown>:0 
[01:02] Disconnected from server.Shutting down server
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer - Saving...

LocalServer -  Saving world... 

LocalServer - Finished in 91.3msDone

</details>

**Comment by craig-jong** [comment]
This is fixed in current staging and will be fixed in the next release of 7.5
