### ISSUE TITLE
NullReferenceException on Initialize WorldObjectManager

### ISSUE THREAD

**Issue by PapaHarni** [StrangeLoopGames/EcoIssues#7696]
Hey,

since update to 0.7.4.x i cant start more my server while i get following exception error.

`--BEGIN DUMP--
Dump Time
05/10/2018 22:15:08

Exception
Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Gameplay

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at Eco.Gameplay.Components.CreditComponent.OnCreate()
   at Eco.Gameplay.Objects.WorldObject.AddComponent(Type componentType, Object[] args)
   at Eco.Gameplay.Objects.WorldObject.ValidateComponents()
   at Eco.Gameplay.Objects.WorldObject.BeginInitialize()
   at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass13_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__0(KeyValuePair`2 pair)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

--END DUMP--`

Anyone can help to run the world again?

![worldobjectmanager error](https://user-images.githubusercontent.com/6943360/39892230-35450eca-54a0-11e8-8bcb-e25cc6dec655.jpg)

**Comment by elfl0rd** [comment]
> Anyone can help to run the world again?

Attach save

**Comment by PapaHarni** [comment]
@elfl0rd , i mean with tip and trick ;-) The save has a size of 1 GB. ;-)

**Comment by elfl0rd** [comment]
create backup, add .zip after .eco extension (of save file)
open
remove garbage folder
rename back and try

**Comment by PapaHarni** [comment]
i open it easier with rar on double click. but thanks ;-)
There isn't a garbage folder. The error comes from loading few objects in WorldObjects folder. But i dont know yet which object it is. I search it by remove part of part from eco file.

**Comment by PapaHarni** [comment]
Error comes from (Asphalt/Dirt/Stone) Ramp's and Door's

**Comment by metachronism** [comment]
will need gamesave to fix this.  if you still have it, please attach the file and reopen this bug
