### ISSUE TITLE
USER ISSUE: crash client

### ISSUE THREAD

**Issue by porfirius1983** [StrangeLoopGames/EcoIssues#7727]
**Version:** 0.7.4.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Ссылка на объект не указывает на экземпляр объекта.
Source:Eco.Mods

System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   at HammerItem.TryPickUp(WorldObject obj, InteractionContext context)
   at HammerItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>
```

<details>
<summary>Log File</summary>(...previous log truncated...)

e) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <0a145ea5364c43bdb183fda8134bdbfd>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <0a145ea5364c43bdb183fda8134bdbfd>:0 
[10:54] Exception in view notify: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component:get_gameObject (UnityEngine.Component)
  at UnityEngine.Component.GetComponentInParent (System.Type t) [0x00001] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at UnityEngine.Component.GetComponentInParent[T] () [0x00001] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at UI.BaseItemUI.OnChange () [0x00000] in <4e372b8d18fc4ffc9a0797b4c3bb5a85>:0 
  at UI.ItemCollectionUI.OnChange () [0x00000] in <4e372b8d18fc4ffc9a0797b4c3bb5a85>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <0a145ea5364c43bdb183fda8134bdbfd>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <0a145ea5364c43bdb183fda8134bdbfd>:0 
Can not play a disabled audio source
 
(Filename:  Line: 707)

[11:21] Disconnected from server.Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by metachronism** [comment]
already fixed in 7.4.4
