### ISSUE TITLE
Server Version Upgrade Issue, 

### ISSUE THREAD

**Issue by KyeEco** [StrangeLoopGames/EcoIssues#7729]
hey guys we have a world from 7.3.3, when we tried to upgrade to any of the 7.4 series updates the server always crashes right after loading the WorldObjects, we have looked into this and the only solution we have found is deleting all the world objects then the server will boot, but this is the full exception we get when the servers crash, 

please note it only happens when we try to add mods back onto the servers, we have tried converting the worlds to the new formats and then adding the mods, but its the same issue, and once the worlds have failed loading the worlds become useless and don't seem to be reusable, thus making us use a backup

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error(s) occurred when loading WorldObjects
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.Gameplay.Objects.WorldObjectManager..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.<.ctor>b__10_2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

**Comment by elfl0rd** [comment]
attach .ecodmp file please.

**Comment by metachronism** [comment]
need a copy of the gamesave, please reopen and attach it if possible
