### ISSUE TITLE
USER ISSUE: Crash whith /level command

### ISSUE THREAD

**Issue by duxter** [StrangeLoopGames/EcoIssues#7802]
**Version:** 0.7.4.5 beta

**Steps to Reproduce:**
/level 3,3,ErroredBlockName

**Expected behavior:**
Message in the chat like "ErroredBlockName is not a valid block"

**Actual behavior:**

Server encountered an exception:

<size=60,00%>Exception: ArgumentNullException
Message:La valeur ne peut pas être null.
Parameter name: key
Source:mscorlib

System.ArgumentNullException: La valeur ne peut pas être null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.World.BlockManager.Create(Type blockType, Object[] args)
   at Eco.World.WorldChunkGrid.SetBlock(Type blockType, Vector3i worldPos, Object[] args)
   at Eco.Gameplay.WorldObjectDebugUtil.<>c__DisplayClass4_0.<LevelTerrain>b__0(Vector3i pos)
   at Eco.Shared.Math.WorldRange.ForEachInc(Action`1 a)
   at Eco.Gameplay.WorldObjectDebugUtil.LevelTerrain(Vector2i size, Vector3i position, Type blockType, Player player)
   at Eco.Gameplay.Systems.Chat.AdminCommands.Level(User user, Int32 x, Int32 y, String blockType)</size>
```

<details>
<summary>Log File</summary>(...previous log truncated...)

calServer -  Starting RoomPlugin... 
LocalServer -  Loading Rooms... 
LocalServer -  Starting ObjectivePlugin... 
LocalServer -  Loading Objectives... 
LocalServer -  Starting Legislation... 
LocalServer -  Loading Laws... 
LocalServer -  Starting WebServerPlugin... 
LocalServer -  Starting HousingTierDefinition... 
LocalServer -  Initializing LocalizationPlugin... 
LocalServer -  Initializing WorldGeneratorPlugin... 
LocalServer -  Initializing UserManager... 
LocalServer -  Initializing MinimapManager... 
LocalServer -  Initializing WorldObjectManager... 
LocalServer -  Initializing RoomPlugin... 
LocalServer -  Initializing HousingTierDefinition... 
LocalServer -  Initializing WorldPlugin... 
LocalServer -  Ticking... 
LocalServer -  Compressing... 
LocalServer -  Initializing WorldLayerManager... 
LocalServer -  Initializing WebServerPlugin... 
LocalServer -  Server Initialization finished in 12�328,8ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[45:11] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at PostProcessingManager.UpdateHypoxia () [0x0002f] in <2c9362ff3b6f4767b4b44352d17195ba>:0 
  at Eco.Shared.View.ISubscriberExtensions.SubscribeAndCall (Eco.Shared.View.ISubscriber s, System.String propname, System.Action changedCallback) [0x00008] in <522b50c462ea4e44bfad45c74e5ed0ae>:0 
  at PostProcessingManager.Start () [0x00081] in <2c9362ff3b6f4767b4b44352d17195ba>:0 
 
(Filename: <2c9362ff3b6f4767b4b44352d17195ba> Line: 0)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[45:42] Disconnected from server.Shutting down server
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer - Saving...
LocalServer -  Saving world... 
Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer - Finished in 125,5msDone
</details>

**Comment by Nanders** [comment]
this is fixed in 7.5.0
