### ISSUE TITLE
Addition of new blocks in code creates an Index out of bounds error.

### ISSUE THREAD

**Issue by FishAus** [StrangeLoopGames/EcoIssues#7842]
Adding new blocks to the game will eventually cause an Index Out Of Bounds exception.

`Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Eco.Simulation.WorldLayers.History.WorldLayerHistory.SaveGIF(String name, Int32 width, Int32 height, Func 3 pixelFunc, Color[] pallette, Boolean animate, Boolean backup)
at Eco.Simulation.WorldLayers.History.WorldLayerHistory.GenerateTerrainImage()
at Eco.Simulation.WorldLayers.History.WorldLayerHistory.Update()
` [SIC]

It appears currently to only cope with 256 blocks in the game.

This happens at about the 10th addition of a new bock so it's not many and server owners will start noticing this bug soon as more mods are including blocks.

**Comment by SeanAtr0n** [comment]
fixed in 7.5
