### ISSUE TITLE
Crash Eco Server 0.7.5.0 beta staging-77a8710c

### ISSUE THREAD

**Issue by Gerkiz** [StrangeLoopGames/EcoIssues#7867]
[44:24] Eco Server 0.7.5.0 beta staging-77a8710c
[44:24] Server Initialization...
[44:24] Starting LocalizationPlugin... Finished in 427,5ms
[44:24] Starting ModKitPlugin... Finished in 237,2ms
[44:25] Loading mods... Finished in 9,8ms
[44:25] Starting NetworkManager... Finished in 68,7ms
[44:25] Initializing items... Finished in 4 966,0ms
[44:25] Starting GameplayStatsPlugin... Finished in 0,3ms
[44:25] Starting WorldGeneratorPlugin... Finished in 109,2ms
[44:25] Starting BackupPlugin... Finished in 7,3ms
[44:25] Starting StorageManager... Finished in 2 657,5ms
[44:30] Initializing skills... Finished in 140,2ms
[44:30] Starting StatDatabase... Finished in 47,1ms
[44:30] Starting WorldPlugin... Finished in 1 822,2ms
[44:30] Loading World... Finished in 1 381,5ms
[44:31] Initializing world... Finished in 377,8ms
[44:32] Starting TimePlugin... Finished in 12,1ms
[44:32] Loading Time... Finished in 1,6ms
[44:32] Starting ReputationPlugin... Finished in 8,1ms
[44:32] Loading Reputation... Finished in 4,1ms
[44:32] Starting PlayerHousingManager... Finished in 2,3ms
[44:32] Starting UserManager... Finished in 325,1ms
[44:32] Loading Users... Finished in 231,3ms
[44:32] Initializing inventories... Finished in 52,1ms
[44:32] Starting EcoObjectManager... Finished in 71,1ms
[44:32] Loading Objects... Finished in 67,6ms
[44:32] Starting GarbagePlugin... Finished in 14,5ms
[44:32] Starting DisasterPlugin... Finished in 32,4ms
[44:32] Starting ControllerManager... Finished in 2 494,4ms
[44:32] Loading Garbage... Finished in 10,1ms
[44:32] Starting DifficultySettings... Finished in 12,7ms
[44:32] Starting ChatServer... Finished in 154,6ms
[44:32] Starting PropertyManager... Finished in 153,7ms
[44:32] Starting WirePlugin... Finished in 4,3ms
[44:32] Starting EcoSim... Finished in 2 592,3ms
[44:32] Loading Disasters... Finished in 0,5ms
[44:32] Loading Property... Finished in 85,3ms
[44:32] Loading Chat... Finished in 43,3ms
[44:32] Starting MinimapManager... Finished in 15,4ms
[44:33] Loading Plants... Finished in 575,5ms
[44:33] Initializing plants... Finished in 1 378,0ms
[44:35] Starting RouteProbingPlugin... Finished in 542,2ms
[44:35] Loading RouteProbing... Finished in 532,7ms
[44:35] Starting WorldLayerManager... Finished in 1 386,5ms
[44:35] Loading Layers... Finished in 154,6ms
[44:35] Initializing world layers... Finished in 1 202,0ms
[44:35] Loading ClimateSim... Finished in 1,0ms
[44:37] Starting EconomyTracker... Finished in 3,8ms
[44:37] Starting WorldObjectManager... Finished in 182,2ms
[44:37] Loading WorldObjects... Finished in 111,9ms
[44:37] Starting EconomyPlugin... Finished in 41,3ms
[44:37] Loading Economy... Finished in 38,0ms
[44:37] Starting RoomPlugin... Finished in 15,7ms
[44:37] Loading Rooms... Finished in 9,8ms
[44:37] Starting ObjectivePlugin... Finished in 24,1ms
[44:37] Loading Objectives... Finished in 1,8ms
[44:37] Starting Legislation... Finished in 521,5ms
[44:37] Loading Laws... Finished in 24,0ms
[44:37] Starting WebServerPlugin... Finished in 0,3ms
[44:37] Starting HousingTierDefinition... Finished in 2,2ms
[44:37] Initializing LocalizationPlugin... Finished in 103,3ms
[44:37] Initializing WorldGeneratorPlugin... Finished in 0,6ms
[44:37] Initializing UserManager... Finished in 45,1ms
[44:38] Initializing MinimapManager... Finished in 494,5ms
[44:38] Initializing WorldObjectManager... Finished in 262,1ms
[44:38] Initializing EconomyPlugin... Finished in 3,3ms
[44:38] Initializing RoomPlugin... Finished in 104,0ms
[44:38] Initializing HousingTierDefinition... Finished in 0,9ms
[44:38] Initializing WorldPlugin... Finished in 1 662,1ms
[44:38] Ticking... Finished in 26,9ms
[44:38] Compressing... Finished in 1 143,9ms
[44:40] Initializing NetworkManager... Finished in 72,7ms
[44:40] Initializing WorldLayerManager... Finished in 0,3ms
[44:40] Initializing WebServerPlugin... Finished in 1 106,3ms
[44:41] Server Initialization finished in 17 331,7ms

Unhandled Exception: Lidgren.Network.NetException: Unconnected messages too long! Must be shorter than NetConfiguration.MaximumTransmissionUnit (currently 1408)
   at Lidgren.Network.NetPeer.SendUnconnectedMessage(NetOutgoingMessage msg, IPEndPoint recipient)
   at Eco.Core.Utils.ExceptionExtensions.Dump(Exception exception, String dumpType, String userID)
   at Eco.Plugins.Networking.Client.<.ctor>b__52_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

The issue occur when a player connects to the server.

MTU on the nic is set to 1500.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/7803
