### ISSUE TITLE
Server Crash after the last update

### ISSUE THREAD

**Issue by Gjafar** [StrangeLoopGames/EcoIssues#7897]
--BEGIN DUMP--
Dump Time
05/26/2018 10:10:04

Exception
Exception: IndexOutOfRangeException
Message:Der Index war außerhalb des Arraybereichs.
Source:Eco.Simulation

System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.SaveGIF(String name, Int32 width, Int32 height, Func`3 pixelFunc, Color[] pallette, Boolean animate, Boolean backup)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.GenerateTerrainImage()
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.Update()
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by Gjafar** [comment]
It's modded server  Glorious Bean Modpack and  updated last mods manual.

**Comment by pamduncan** [comment]
This error was generated by a mod conflict.  He went back to vanilla with the mods removed and the game loaded . Unsure which mod was the issue or if it was a combination of mods.

**Comment by Kirthos** [comment]
There is a bug were you can't add more than 256 block in the game. This was already fixed but not available on the 7.4.6 version.

**Comment by gabeux** [comment]
Yep. Player probably added more mods to the pack and went over the 256 blocks limit - that is the crash.

**Comment by GophTheGreat** [comment]
Closing this issue then.
