### ISSUE TITLE
USER ISSUE: Mint crash

### ISSUE THREAD

**Issue by funnybunnyofdoom** [StrangeLoopGames/EcoIssues#7912]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
Place a mint in a valid location
try to name the currency

**Expected behavior:**
allowed me to create another currency

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.MintComponent.<>c__DisplayClass26_0.<SetCurrencyNameNoCheck>b__0(MintComponent x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Components.MintComponent.SetCurrencyNameNoCheck(Player player, LocString currencyName)</size>
```

<details>
<summary>Log File</summary>(...previous log truncated...)

 Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Toggled Heisenberg
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to select while already selecting an object.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[44:54] Disconnected from server.NullReferenceException: Object reference not set to an instance of an object
  at Player.get_NetObject () [0x00005] in <a14c2a2baa3940d0969f235d02df648a>:0 
  at MinimapUI.OnDisable () [0x00025] in <a14c2a2baa3940d0969f235d02df648a>:0 
UnityEngine.Object:Destroy(Object, Single)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject)
UI.UIManager:CloseAll()
Player:OnDestroy()
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at MinimapUIObjectManager.OnDestroy () [0x00005] in <a14c2a2baa3940d0969f235d02df648a>:0 
  at MinimapUI.OnDestroy () [0x00067] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by MarjieAVolk** [comment]
While playing around with this, I also saw the following exception when trying to place a Mint that already had a created currency on it:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Eco.Gameplay
  StackTrace:
   at Eco.Gameplay.Components.MintComponent.InitializeCurrency(Guid currencyId) in C:\Projects\Eco\Server\Eco.Gameplay\Components\MintComponent.cs:line 61
   at Eco.Mods.TechTree.MintItem.OnWorldObjectPlaced(WorldObject placedObject) in c:\Projects\Eco\Server\Mods\Objects\MintObject.cs:line 33
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass13_0.<OnActRight>b__0(BSONObject response) in C:\Projects\Eco\Server\Eco.Gameplay\Items\WorldObjectItem.cs:line 103
   at Eco.Shared.Networking.RPCManager.<>c__DisplayClass12_0`1.<Call>b__0(Object o) in C:\Projects\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 72
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson) in C:\Projects\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 122
   at Eco.Plugins.Networking.NetworkServer.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bson) in C:\Projects\Eco\Server\Eco.Plugins\Networking\NetworkServer.cs:line 158
   at Eco.Shared.Networking.NetObject.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bson) in C:\Projects\Eco\Server\Eco.Shared\Networking\NetObject.cs:line 69
   at Eco.Plugins.Networking.Client.<.ctor>b__52_1() in C:\Projects\Eco\Server\Eco.Plugins\Networking\Client.cs:line 126
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

**Comment by johnkslg** [comment]
Wasn't able to repro this, and since this bug a lot of changes have gone into currency null checks and how currency is loaded, saved, and migrated.  The callstack you posted Marjie is from before Eric's checkin to this effect, so I believe this should all be fixed now.
