### ISSUE TITLE
Server Crash unexpected (ClientReceiveException TargetInvocationException / WorldObject.UpdateUsingPlayers)

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#7938]
Server Version 7.4.6

--BEGIN DUMP--
Dump Time
05/28/2018 18:05:22

Exception
Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Gameplay

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at Eco.Gameplay.Objects.WorldObject.<>c__DisplayClass82_0.<DecrementUsing>b__1(WeakReference x)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Gameplay.Objects.WorldObject.UpdateUsingPlayers(Action action)

--END DUMP--

**Comment by MarjieAVolk** [comment]
Hm, well this is weird, since no one has touched UsingPlayers in over a year, as far as I know.  I don't really see how it could happen 🤔
