### ISSUE TITLE
USER ISSUE: client crash on creating contract

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7946]
**Version:** 0.7.5.0 beta staging-87e67f1f

**Steps to Reproduce:**
try to create custom clause contract, edit description, try to edit name.

The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: Exception
Message:Wrong number of args passed to method: set_Description.
Source:Eco.Shared

System.Exception: Wrong number of args passed to method: set_Description.
   at Eco.Shared.Networking.RPCManager.UnpackArgs(BSONObject bson, RPCMethod[] methods, Object extensionMethodObject, RPCMethod& targetMethod)
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)</size>
```

<details>
<summary>Log File</summary>(...previous log truncated...)

m.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.Serialization.BsonManipulator.FromBsonIList (System.Type ty

**Comment by johnkslg** [comment]
Re-titling this bug as it relates to AutoRPCs

Problems are as follows:
- AutoRPC, which was rewritten from SyncProp, no longer accepts a passed in User.  Many features of the Loan system rely on this as well, where lots of different handling was performed depending on the user making viewing or making the change.

Additional repro steps to whats listed above:
Create a contract and attempt to select a loan clause.  It will not display the clause, cant test further that the clause works.

**Comment by MarjieAVolk** [comment]
John marked this as fixed in https://github.com/StrangeLoopGames/EcoIssues/issues/8244 - Should we close this?

**Comment by metachronism** [comment]
needs to handle SetXXXX( ... ) override methods, instead of calling the set method of the property, when said methods exist
