### ISSUE TITLE
USER ISSUE: 0.7.5.0 Placing a store crashes the game

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#7986]
**Version:** 0.7.5.0 beta staging-907d79a5

**Steps to Reproduce:**
1. Generated new version of Eco
2. Placed a store object on the sand on a beach

**Expected behavior:**
Store should have been placed

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.StoreComponent.get_Enabled()
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Objects.WorldObject.UpdateEnabledAndOperating()
   at Eco.Gameplay.Components.SolidGroundComponent.UpdateEnabled()
   at Eco.Gameplay.Objects.WorldObject.AddComponent(Type componentType, Object[] args)
   at Eco.Gameplay.Objects.WorldObject.ValidateComponents()
   at Eco.Gameplay.Objects.WorldObject.BeginInitialize()
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.Add(WorldObject worldObject, User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.TryToAdd(Type worldObjectType, User creator, Vector3 position, Quaternion rotation, Boolean validatePlacement, WorldObjectItem item)
   at Eco.Gameplay.Objects.WorldObjectManager.TryPlaceWorldObject(Player player, WorldObjectItem item, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass13_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.Client.<.ctor>b__52_1()</size>
```

<details>
<summary>Log File</summary>(...previous log truncated...)

n.cpp Line: 51)

Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following icons: CraneItem, SteamTractorHarvesterItem, SteamTractorItem, SteamTractorPloughItem, SteamTractorSowerItem, VehicleToolItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Exception in view notify: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Animator:SetBoolString (UnityEngine.Animator,string,bool)
  at UnityEngine.Animator.SetBool (System.String name, System.Boolean value) [0x00001] in <631a8b01f775461aaefeab8ef216af40>:0 
  at AvatarAnimationManager.UpdateTool () [0x00080] in <08eb06922d8a4ea3ad2724d2db807a7d>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <307b288167134d279e7b684a3450ad38>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <307b288167134d279e7b684a3450ad38>:0 
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Shutting down server
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer - Saving...
LocalServer -  Saving world... 
LocalServer - Finished in 176.5msDone
</details>

**Comment by BlazeGuy2** [comment]
Possibly fixed.  We'll see.

**Comment by BlazeGuy2** [comment]
Fixed, store placement works again.
