### ISSUE TITLE
Store crash game instantly

### ISSUE THREAD

**Issue by Blakkcat** [StrangeLoopGames/EcoIssues#8002]
Hello, everyone !

Sorry for bad english, i do my best :/
I have a server, up about 2 days. 
Each time an user want to place a store, the server disconnect all users and i got this message : 

Unhandled Exception: Lidgren.Network.NetException: Unconnected messages too long! Must be shorter than NetConfiguration.MaximumTransmissionUnit (currently 1408)

   at Lidgren.Network.NetPeer.SendUnconnectedMessage(NetOutgoingMessage msg, IPEndPoint recipient)

   at Eco.Core.Utils.ExceptionExtensions.Dump(Exception exception, String dumpType, String userID)

   at Eco.Plugins.Networking.Client.<.ctor>b__52_1()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart()

If anyone has any idea , thank you guys

**Comment by BlazeGuy2** [comment]
What version of Eco are you using?

**Comment by Blakkcat** [comment]
It's the   0.7.4.6

**Comment by BlazeGuy2** [comment]
The stores bug is a known issue.  The fix is currently on the master branch, should be deployed on 7.5.0 next week.  Let me know when the update comes out if you're still having the bug and I'll reopen the issue and revisit the bug.
