### ISSUE TITLE
USER ISSUE: /level command exception

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#8065]
**Version:** 0.7.4.7 beta

**Steps to Reproduce:**
1. Be an admin on the s erver
2. Do /level 10,10,rock or /level 10,10,RockBlock

**Expected behavior:**
should not get an exception 

**Actual behavior:**

The format for the /level command is as follows
https://eco.gamepedia.com/Chat_Commands#Admin_Commands

/level [x(default=10)],[y(default=10)],[BlockType(default=GrassBlock)]

so I did a /level 10,10,Rock 

Also crashes if you do a /level 10,10,RockBlock

and it throws an unhanded exception. 

The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: ArgumentNullException
Message:Value cannot be null.
Parameter name: key
Source:mscorlib

System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Eco.World.BlockManager.Create(Type blockType, Object[] args)
   at Eco.World.WorldChunkGrid.SetBlock(Type blockType, Vector3i worldPos, Object[] args)
   at Eco.Gameplay.WorldObjectDebugUtil.<>c__DisplayClass4_0.<LevelTerrain>b__0(Vector3i pos)
   at Eco.Shared.Math.WorldRange.ForEachInc(Action`1 a)
   at Eco.Gameplay.WorldObjectDebugUtil.LevelTerrain(Vector2i size, Vector3i position, Type blockType, Player player)
   at Eco.Gameplay.Systems.Chat.AdminCommands.Level(User user, Int32 x, Int32 y, String blockType)</size>
```

<details>
<summary>Log File</summary>(...previous log truncated...)

ture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <b8319955f33e4680a6e54e432483393e>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <b8319955f33e4680a6e54e432483393e>:0 
Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

[50:45] Disconnected from server.NullReferenceException: Object reference not set to an instance of an object
  at Player.get_NetObject () [0x00005] in <5d6a28c6303f486ea059aa5adcf9181a>:0 
  at MinimapUI.OnDisable () [0x00025] in <5d6a28c6303f486ea059aa5adcf9181a>:0 
UnityEngine.Object:Destroy(Object, Single)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject)
UI.UIManager:CloseAll()
Player:OnDestroy()
 
(Filename: <5d6a28c6303f486ea059aa5adcf9181a> Line: 0)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[12:12] Disconnected from server.NullReferenceException: Object reference not set to an instance of an object
  at Player.get_NetObject () [0x00005] in <5d6a28c6303f486ea059aa5adcf9181a>:0 
  at MinimapUI.OnDisable () [0x00025] in <5d6a28c6303f486ea059aa5adcf9181a>:0 
UnityEngine.Object:Destroy(Object, Single)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject)
UI.UIManager:CloseAll()
Player:OnDestroy()
 
(Filename: <5d6a28c6303f486ea059aa5adcf9181a> Line: 0)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by craig-jong** [comment]
Level will no longer cause an exception in 7.5+

The correct term for natural stone is "StoneBlock"
