### ISSUE TITLE
USER ISSUE: Server Crash NullReferenceException

### ISSUE THREAD

**Issue by Loomie** [StrangeLoopGames/EcoIssues#8083]
**Version:** 0.7.4.7 beta

**Steps to Reproduce:**
unknowm

**Expected behavior:**
continue running

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.EnumerableItemExtensions.<>c.<Describe>b__5_3(IGrouping`2 group)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, String noneText)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, LocString noneText)
   at Eco.Gameplay.Items.EnumerableItemExtensions.Describe(IEnumerable`1 stacks)
   at Eco.Gameplay.Utils.PickerObject.get_Contents()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, String memberName)
   at Eco.Core.Controller.ControllerManager.GetChanges(INetClient client)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__52_0()</size>
```

<details>
<summary>Log File</summary>(...previous log truncated...)

d6a28c6303f486ea059aa5adcf9181a>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <b8319955f33e4680a6e54e432483393e>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <b8319955f33e4680a6e54e432483393e>:0 
[04:03] Exception in view notify: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component:get_gameObject (UnityEngine.Component)
  at UnityEngine.Component.GetComponentInParent (System.Type t) [0x00001] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at UnityEngine.Component.GetComponentInParent[T] () [0x00001] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at UI.BaseItemUI.OnChange () [0x00000] in <5d6a28c6303f486ea059aa5adcf9181a>:0 
  at UI.ItemCollectionUI.OnChange () [0x00000] in <5d6a28c6303f486ea059aa5adcf9181a>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <b8319955f33e4680a6e54e432483393e>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <b8319955f33e4680a6e54e432483393e>:0 
[04:11] Disconnected from server.Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by johnkslg** [comment]
Already fixed in latest as far as I can tell.
