### ISSUE TITLE
USER ISSUE: server cannot start, exception on layer generation.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8098]
**Version:** 0.7.5.0 beta staging-bad4361f
Exception on layer generation
![default](https://user-images.githubusercontent.com/4980243/41619702-d8a41474-740f-11e8-91b7-4fddb971ac66.png)

--BEGIN DUMP--
Dump Time
06/19/2018 22:17:41

Exception
Exception: IndexOutOfRangeException
Message:Индекс находился вне границ массива.
Source:Eco.Simulation

System.IndexOutOfRangeException: Индекс находился вне границ массива.
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.MakeDeltaBitmap(Int32 width, Int32 height, Byte[] history, Func`3 pixelFunc, Boolean firstFrame)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.SaveGIF(String name, Int32 width, Int32 height, Func`3 pixelFunc, Boolean animate, Boolean backup)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.SaveGIF(WorldLayer layer, Boolean backup)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.Update()
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
https://www.dropbox.com/s/nu7gnvvyxbuoxl9/Storage_layer_exception.rar?dl=1
https://www.dropbox.com/s/uox8qnwt8gaav59/ServerCrash%20IndexOutOfRangeException%2006191741.ecodmp?dl=1

**Comment by SeanAtr0n** [comment]
Already talked to GDragon, but if anyone else hits this issue you can either restore a backup from before the bleeding edge build yesterday or if you want to keep your progress from that build:

1. Open your Game.eco with 7zip (or rename it to Game.zip and double click it)
2. Delete the LayerHistory folder
3. Optionally find a save in your backups that still has a History folder and copy that folder into your current save if you want to keep your layer history
4. Close whatever you are using to inspect Game.eco before restarting the server

**Comment by elfl0rd** [comment]
Replacing from old save helped, thx :)

**Comment by elfl0rd** [comment]
I close it now.
