### ISSUE TITLE
7.5 Servers crashing on load with error of files in use

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8161]
--BEGIN DUMP--
Dump Time
06/26/2018 22:12:26

Exception
Exception: IOException
Message:The process cannot access the file 'D:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Storage\1.db' because it is being used by another process.
Source:mscorlib

System.IO.IOException: The process cannot access the file 'D:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Storage\1.db' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at LiteDB.FileDiskService.Initialize(Logger log, String password)
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)
   at Eco.Stats.StatDatabase.EnsureIndex[T](IEnumerable`1 fieldNames)
   at Eco.Gameplay.Stats.ConcretePlayerActions.AcceptContractPlayerStatManager..ctor()
   at Eco.Gameplay.Stats.PlayerActions..cctor()

--END DUMP--

--BEGIN DUMP--
Dump Time
06/26/2018 22:25:37

Exception
Exception: Exception
Message:Error in FishingPoleItem at 19: Field 'Eco.Mods.TechTree.FishingPoleItem.caloriesBurn' is never assigned to, and will always have its default value null (CS0649)
Error in FishingPoleItem at 20: The field 'Eco.Mods.TechTree.FishingPoleItem.damage' is never used (CS0169)
Error in  at 0: Could not write to output file 'd:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Eco.Mods.dll' -- 'The process cannot access the file because it is being used by another process. ' (CS0016)

Source:Eco.ModKit

System.Exception: Error in FishingPoleItem at 19: Field 'Eco.Mods.TechTree.FishingPoleItem.caloriesBurn' is never assigned to, and will always have its default value null (CS0649)
Error in FishingPoleItem at 20: The field 'Eco.Mods.TechTree.FishingPoleItem.damage' is never used (CS0169)
Error in  at 0: Could not write to output file 'd:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Eco.Mods.dll' -- 'The process cannot access the file because it is being used by another process. ' (CS0016)

   at Eco.ModKit.RuntimeCompiler.HandleCompilerError(CompilerResults results)
   at Eco.ModKit.RuntimeCompiler.LoadOrCompileMods()
   at Eco.ModKit.ModKitPlugin..ctor(ManualResetEvent doneEvent)

--END DUMP--

**Comment by metachronism** [comment]
fixed in 7.5.1
