### ISSUE TITLE
USER ISSUE: [0.7.6.0] Issue With Minimap Markers

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8197]
**Version:** 0.7.6.0 beta staging-4767aa88

**Steps to Reproduce:**
1. Open Map
2. Click Drop marker
3. L-Click on my newly dropped marker

**Expected behavior:**
Marker Info should appear on the screen

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Wrong number of args passed to method: ShowLocationPos.
Source:Eco.Shared

System.Exception: Wrong number of args passed to method: ShowLocationPos.
   at Eco.Shared.Networking.RPCManager.UnpackArgs(INetClient client, BSONObject bson, RPCMethod[] methods, Object target, RPCMethod& targetMethod)
   at Eco.Shared.Networking.RPCManager.TryInvoke(INetClient client, Object target, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Plugins.Networking.Client.<.ctor>b__52_1()</size>
```

**Comment by BlazeGuy2** [comment]
Happens everytime I click on the marker.  On Bleeding Edge

**Comment by SeanAtr0n** [comment]
Looks like @MarjieAVolk removed 2 parameters? not really sure whats going on here
![image](https://user-images.githubusercontent.com/774628/42065416-a3a7402a-7aef-11e8-8170-26dcc6b5cec3.png)

**Comment by MarjieAVolk** [comment]
Yeah I removed those, because one wasn't being used, and the other one was only being used for dropping markers, which I removed from that method.  I updated it on the client everywhere I could find it... there must be a string in a prefab somewhere pointing to this method. STRINGS

**Comment by MarjieAVolk** [comment]
Fixed in next build
