### ISSUE TITLE
Server in Crash Loop with Receive Exception

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8225]
--BEGIN DUMP--
Dump Time
06/27/2018 21:00:48

Exception
Exception: Exception
Message:Original type is Object. Cannot convert from Object to Guid
Source:Eco.Shared

System.Exception: Original type is Object. Cannot convert from Object to Guid
   at Eco.Shared.Serialization.BSONValue.get_GuidValue()
   at Eco.Gameplay.Economy.Currency.<>c.<.cctor>b__45_0(BSONValue v)
   at Eco.Shared.Serialization.BsonManipulator.FromBson(BSONValue value, Type type)
   at Eco.Shared.Networking.RPCManager.UnpackArgs(BSONObject bson, RPCMethod[] methods, Object extensionMethodObject, RPCMethod& targetMethod)

--END DUMP--

**Comment by johnkslg** [comment]
Related to #8211 I believe
