### ISSUE TITLE
update 7.47 to 7.5.1 crash 

### ISSUE THREAD

**Issue by LaTrouTe** [StrangeLoopGames/EcoIssues#8250]
hello I want to put the server to the new version 7 .5.1

but the crash server with log message included in the email

version 0.7.4.7 to 7.5.1

log crash info

--BEGIN DUMP--
Dump Time
06/29/2018 19:55:02

Exception
Exception: IndexOutOfRangeException
Message:L'index se trouve en dehors des limites du tableau.
Source:Eco.Simulation

System.IndexOutOfRangeException: L'index se trouve en dehors des limites du tableau.
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.MakeDeltaBitmap(Int32 width, Int32 height, Byte[] history, Func`3 pixelFunc, Boolean firstFrame)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.SaveGIF(String name, Int32 width, Int32 height, Func`3 pixelFunc, Boolean animate, Boolean backup)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.SaveGIF(WorldLayer layer, Boolean backup)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.Update()
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by SeanAtr0n** [comment]
please upload the save file

**Comment by elfl0rd** [comment]
@LaTrouTe https://github.com/StrangeLoopGames/EcoIssues/issues/8098

**Comment by metachronism** [comment]
dropping priority till we get a save file to debug

**Comment by SeanAtr0n** [comment]
This won't crash anymore in 7.7

but also you can fix this by opening the Game.eco file with winrar/7zip and deleting the Layers directory then starting the server (make sure you close Game.eco before starting the server)

**Comment by LaTrouTe** [comment]
but also you can fix this by opening the Game.eco file with winrar/7zip and deleting the Layers directory then starting the server (make sure you close Game.eco before starting the server)

error and message server

Exception
Exception: IndexOutOfRangeException
Message:L'index se trouve en dehors des limites du tableau.
Source:Eco.Simulation

System.IndexOutOfRangeException: L'index se trouve en dehors des limites du tableau.
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.MakeDeltaBitmap(Int32 width, Int32 height, Byte[] history, Func`3 pixelFunc, Boolean firstFrame)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.SaveGIF(String name, Int32 width, Int32 height, Func`3 pixelFunc, Boolean animate, Boolean backup)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.SaveGIF(WorldLayer layer, Boolean backup)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.Update()
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
