### ISSUE TITLE
USER ISSUE: Treasury

### ISSUE THREAD

**Issue by FlamingDemon** [StrangeLoopGames/EcoIssues#8277]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
set tax, gain money in treasury, click allocate

**Expected behavior:**
it should have given me a pop up to allocate money

**Actual behavior:**
The following error message popped up:
`Server encountered an exceptio: Message:Original type is Object. Cannot convert from Object to Guid Source:Eco.Shared`
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Original type is Object. Cannot convert from Object to Guid
Source:Eco.Shared

System.Exception: Original type is Object. Cannot convert from Object to Guid
   at Eco.Shared.Serialization.BSONValue.get_GuidValue()
   at Eco.Gameplay.Economy.Currency.<>c.<.cctor>b__45_0(BSONValue v)
   at Eco.Shared.Serialization.BsonManipulator.FromBson(BSONValue value, Type type)
   at Eco.Shared.Networking.RPCManager.UnpackArgs(BSONObject bson, RPCMethod[] methods, Object extensionMethodObject, RPCMethod& targetMethod)</size>
```

**Comment by Deantwo** [comment]
same as #8211

**Comment by johnkslg** [comment]
Fixed in staging
