### ISSUE TITLE
[7.5.1] Server Dump / System.Exception: Wrong number of args passed to method: set_Description

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8281]
I found some dump files at the server. 

[ClientReceiveException TargetInvocationException 07020735.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2156754/ClientReceiveException.TargetInvocationException.07020735.zip)

**Comment by BlazeGuy2** [comment]
Contents for all of the dumps:

--BEGIN DUMP--
Dump Time
07/02/2018 14:07:35

Exception
Exception: Exception
Message:Wrong number of args passed to method: set_Description.
Source:Eco.Shared

System.Exception: Wrong number of args passed to method: set_Description.
   at Eco.Shared.Networking.RPCManager.UnpackArgs(BSONObject bson, RPCMethod[] methods, Object extensionMethodObject, RPCMethod& targetMethod)
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

--END DUMP--

**Comment by MarjieAVolk** [comment]
Okaaay, looks like the only property called Description with AutoRPC on it is ContractClauseCustom.Description.  This stuff seems to be coming from down in the auto view system somewhere, which is crazy hard to debug.

**Comment by Voosle** [comment]
Got it!

At Contract Board:
Create new contract
Select Custom Clause 
Enter some text in the work field
Click outside the edit field (e.g. to Switch Currency)
--> Exception!

Server side crash Dump: 
--BEGIN DUMP--
Dump Time
07/03/2018 23:00:35

Exception
Exception: Exception
Message:Wrong number of args passed to method: set_Description.
Source:Eco.Shared

System.Exception: Wrong number of args passed to method: set_Description.
   at Eco.Shared.Networking.RPCManager.UnpackArgs(BSONObject bson, RPCMethod[] methods, Object extensionMethodObject, RPCMethod& targetMethod)
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

--END DUMP--

Client side logs:
[ErrLog_2018-07-03_GCOM.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2161060/ErrLog_2018-07-03_GCOM.zip)

**Comment by johnkslg** [comment]
Fixed!
