### ISSUE TITLE
USER ISSUE: 7.6.0 bug

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8301]
**Version:** 0.7.6.0 beta staging-e6b8cd07

**Steps to Reproduce:**
1. I walked over to Will to talk to him
2. I walked back to my desk and sat in my chair
3. Game crashed

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.Deed.<>c.<get_Ownables>b__58_1(IOwnableHandle h)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Eco.Gameplay.Property.Deed.get_Ownables()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   at Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.GetChanges(INetClient client)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__52_0()</size>
```

**Comment by BlazeGuy2** [comment]
Occurred in the show 'n tell

**Comment by MarjieAVolk** [comment]
Thanks, was just looking at this.

**Comment by MarjieAVolk** [comment]
Fixed
