### ISSUE TITLE
[7.6.0] No response from host

### ISSUE THREAD

**Issue by miketek1** [StrangeLoopGames/EcoIssues#8308]
After loading the single player server the game sits on connecting, than gives message "failed to establish connection - no response from host" 

```
--BEGIN DUMP--
Dump Time
07/03/2018 18:21:09

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.InventoryUtils.<>c.<Intersection>b__3_5(ItemStack x)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at Eco.Gameplay.Items.InventoryUtils.Intersection(IEnumerable`1 stacksToCull, IEnumerable`1 contents)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Items.EnumerableItemExtensions.DescribeTextOnly(IEnumerable`1 stacks, Int32 max)
   at Eco.Gameplay.Economy.EconomyTracker.UpdateDistributionStationText()
   at Eco.Gameplay.Economy.EconomyTracker.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--


```

**Comment by WeaselDog** [comment]
I am not able to reproduce this is the latest version and it appears to be fixed.

Thanks for your report and please reply back if you experience this issue again.
