### ISSUE TITLE
Game crash when clicking allocate at treasury

### ISSUE THREAD

**Issue by duschott** [StrangeLoopGames/EcoIssues#8343]
Dedicated server, client side crash. When accessing treasury to allocate funds, clicking on allocate drops me out of server.  This is the log file from server. 

--BEGIN DUMP--
Dump Time
07/05/2018 09:40:35

Exception
Exception: Exception
Message:Original type is Object. Cannot convert from Object to Guid
Source:Eco.Shared

System.Exception: Original type is Object. Cannot convert from Object to Guid
   at Eco.Shared.Serialization.BSONValue.get_GuidValue()
   at Eco.Gameplay.Economy.Currency.<>c.<.cctor>b__45_0(BSONValue v)
   at Eco.Shared.Serialization.BsonManipulator.FromBson(BSONValue value, Type type)
   at Eco.Shared.Networking.RPCManager.UnpackArgs(BSONObject bson, RPCMethod[] methods, Object extensionMethodObject, RPCMethod& targetMethod)

--END DUMP--

**Comment by elfl0rd** [comment]
Dupe - https://github.com/StrangeLoopGames/EcoIssues/issues/8211

**Comment by johnkslg** [comment]
Fixed!
