### ISSUE TITLE
USER ISSUE: Removing construction post crash client.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8356]
**Version:** 0.7.6.0 beta staging-f5159538
Removing construction post crash client.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Ссылка на объект не указывает на экземпляр объекта.
Source:Eco.Gameplay

System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   at Eco.Gameplay.Economy.PointOfInterestList.Remove(WorldObject obj)
   at Eco.Gameplay.Objects.WorldObject.TryPickUp(Player player)
   at HammerItem.TryPickUp(WorldObject obj, InteractionContext context)
   at HammerItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>
```

**Comment by johnkslg** [comment]
Fixed!
