### ISSUE TITLE
[7.5.1] Client crash when place Mint / NullReferenceException at .MintComponent.InitializeCurrency

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8389]
When place Mint on ground, Client crashes with attached crash log.

There is no crafted coin of the configured currency (maybe that's important) .

Server Dump:
--BEGIN DUMP--
Dump Time
07/08/2018 00:28:55

Exception
Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Gameplay

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at Eco.Gameplay.Components.MintComponent.InitializeCurrency(CurrencyHandle currencyHandle)
   at Eco.Mods.TechTree.MintItem.OnWorldObjectPlaced(WorldObject placedObject)
   at Eco.Gameplay.Items.WorldObjectItem.<>c__DisplayClass13_0.<OnActRight>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.Client.<.ctor>b__52_1()

--END DUMP--

[Client crash log.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2173219/Client.crash.log.zip)

**Comment by johnkslg** [comment]
Fixed!
