### ISSUE TITLE
USER ISSUE: Chopped Down A tree to complete the harvest contract

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8412]
**Version:** 0.7.6.0 beta staging-2b46eb65

**Steps to Reproduce:**
1. Accept harvest cedar contract
2. Chop down tree
3. Pick up some logs

**Expected behavior:**
Collect the logs

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClause.Changed(Object clauseObject, PropertyChangedEventArgs args)
   at Eco.Gameplay.Economy.Contracts.ContractClauseHarvest.ActionPerformed(GameAction action)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.GameActions.ActionManager.ActionPerformed(GameAction action)
   at TreeEntity.PickupLog(Player player, Guid logID)
   at TreeEntity.OnActInteract(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>
```

**Comment by johnkslg** [comment]
Fixed!
