### ISSUE TITLE
USER ISSUE: Can't Create Custom contract.

### ISSUE THREAD

**Issue by eviltek2099** [StrangeLoopGames/EcoIssues#8417]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
custom contract with text:

"Dig 2x2 tunnel at (862,54,780) to (862,55,830)"

then leave field by clicking anywhere
Also can't uncheck the auto complete

**Expected behavior:**
not crash

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Wrong number of args passed to method: set_Description.
Source:Eco.Shared

System.Exception: Wrong number of args passed to method: set_Description.
   at Eco.Shared.Networking.RPCManager.UnpackArgs(BSONObject bson, RPCMethod[] methods, Object extensionMethodObject, RPCMethod& targetMethod)
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)</size>
```

**Comment by BlazeGuy2** [comment]
Auto complete checkbox fix is in https://github.com/StrangeLoopGames/Eco/pull/3053, which will show up in 7.6.0.
