### ISSUE TITLE
assert in GetUpdatedMinimapObjects

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#843]
--BEGIN DUMP--
Dump Time
11/29/2016 13:42:07

Exception
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Minimap.MinimapManager.GetUpdatedMinimapObjects(INetObjectViewer viewer, Boolean only_updated)
   at Eco.Gameplay.Minimap.MinimapManager.SendUpdate(BSONObject bsonObj, INetObjectViewer viewer)
   at Eco.Shared.Networking.NetObjectManager.GetObjectUpdates(IEnumerable`1 objects, INetObjectViewer viewer)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_1()

--END DUMP--

**Comment by stett** [comment]
@metachronism were there any objects in the world that would have icons?

**Comment by stett** [comment]
can't seem to reproduce this
