### ISSUE TITLE
USER ISSUE: [7.6.0 Stage] Crash when open Currency Report from economy view / Currency in Use

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8461]
**Version:** 0.7.6.0 beta staging-2b46eb65

**Steps to Reproduce:**
Click on 'Currency Report' to open the report.

![image](https://user-images.githubusercontent.com/22961978/42704627-e7681482-86d0-11e8-857f-2c4044bbffbb.png)

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Gameplay

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at Eco.Gameplay.Economy.Trackers.ExchangeRates.GetExchangeRates(Currency currency)
   at Eco.Gameplay.Economy.Trackers.ExchangeRates.DescribeRatesForCurrency(Currency cur, ExchangeType exchangeType)
   at Eco.Gameplay.Economy.Currency.ShowCurrencyReport(Player player)</size>
```

**Comment by johnkslg** [comment]
Fixed!!! Will hotfix this in.

**Comment by Voosle** [comment]
Thank you for this quick fix :-)
