### ISSUE TITLE
update server crash

### ISSUE THREAD

**Issue by Touch-My** [StrangeLoopGames/EcoIssues#8477]
hello, my server is updated 7.5.1 to 7.6.0 and since that is the result:
I have no mods on it

--BEGIN DUMP--
Dump Time
07/13/2018 20:45:16

Exception
Exception: ArgumentException
Message:Could not cast or convert from System.String to System.Type.
Source:Newtonsoft.Json

System.ArgumentException: Could not cast or convert from System.String to System.Type.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

--END DUMP--

**Comment by BlazeGuy2** [comment]
Looks like a config bug, can you try doing a fresh install of the game?

**Comment by BlazeGuy2** [comment]
No response, closing
