### ISSUE TITLE
7.6.0 - Server Crash

### ISSUE THREAD

**Issue by Stephmos** [StrangeLoopGames/EcoIssues#8497]
A crash resulting in this log occurred 3 times since the latest update.
Let me know what else you guys need! Thank you!

--BEGIN DUMP--
Dump Time
07/13/2018 15:54:03

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.PropertyManager.CreateAction(User user, Vector3i pos, IInteractable target)
   at Eco.Gameplay.Property.PropertyManager.IsAuthorizedOnObject(WorldObject worldObject, User user, String verb)
   at Eco.Gameplay.Components.LinkComponent.<>c__DisplayClass32_0.<GetAuthorizedLinkedObjects>b__0(LinkComponent linked)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Eco.Gameplay.Components.LinkComponent.GetLinkedComponents(User user)
   at Eco.Gameplay.Components.LinkComponent.GetSortedLinkedComponents(User user)
   at Eco.Gameplay.Components.StoreComponent.GetLinkedInventories(User user)
   at Eco.Gameplay.Components.StoreComponent.UpdateStock(Boolean initializing)
   at Eco.Gameplay.Components.StoreComponent.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by Stephmos** [comment]
Another crash with a similar log.

--BEGIN DUMP--
Dump Time
07/14/2018 19:31:02

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.InventoryUtils.<>c.<Intersection>b__3_5(ItemStack x)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at Eco.Gameplay.Items.InventoryUtils.Intersection(IEnumerable`1 stacksToCull, IEnumerable`1 contents)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Items.EnumerableItemExtensions.DescribeTextOnly(IEnumerable`1 stacks, Int32 max)
   at Eco.Gameplay.Economy.EconomyTracker.UpdateDistributionStationText()
   at Eco.Gameplay.Economy.EconomyTracker.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by MarjieAVolk** [comment]
First one is the same as https://github.com/StrangeLoopGames/EcoIssues/issues/8549

**Comment by MarjieAVolk** [comment]
The second one is in the inventory system, looks like @johnkslg is the author of InventoryUtils.Intersection

**Comment by johnkslg** [comment]
Fixed

**Comment by Amphysbaenas** [comment]
same for Ecotopia , a rollback before using distribution center helped us

**Comment by johnkslg** [comment]
Fixed
