### ISSUE TITLE
Animal update exception

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#852]
--BEGIN DUMP--
Dump Time
11/29/2016 14:01:45

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.Agents.Animal.get_Active()
   at Eco.Shared.Networking.NetObjectManager.GetRelevantObjects(INetObjectViewer viewer, ICollection`1 alreadyRelevant)
   at Eco.Plugins.Networking.Clients.Client.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_1()

--END DUMP--

**Comment by stett** [comment]
This happened because Animal.NetObj was null
