### ISSUE TITLE
USER ISSUE: Real Estate Desk crash to loading screen

### ISSUE THREAD

**Issue by DHG-RipJaw** [StrangeLoopGames/EcoIssues#8523]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
When you click currency report in the Real Estate Desk, your game will crash to the loading screen.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Trackers.ExchangeRates.GetExchangeRates(Currency currency)
   at Eco.Gameplay.Economy.Trackers.ExchangeRates.DescribeRatesForCurrency(Currency cur, ExchangeType exchangeType)
   at Eco.Gameplay.Economy.Currency.ShowCurrencyReport(Player player)
   at Eco.Gameplay.Components.CreditComponent.CurrencyReport(Player player)</size>
```

**Comment by johnkslg** [comment]
Awaiting hotfix release

**Comment by johnkslg** [comment]
7.6.1
