### ISSUE TITLE
[7.6.0] Server dump: NullReferenceException at Items.EnumerableItemExtensions at... .Utils.PickerTracker.get_Contents

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8542]
Just found two of this dump file on our server. I don't know what a player did to force this…

--BEGIN DUMP--
Dump Time
07/15/2018 16:11:08

Exception
Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Gameplay

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at Eco.Gameplay.Items.EnumerableItemExtensions.<>c.<Describe>b__5_3(IGrouping`2 group)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, String noneText)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, LocString noneText)
   at Eco.Gameplay.Items.EnumerableItemExtensions.Describe(IEnumerable`1 stacks)
   at Eco.Gameplay.Utils.PickerObject.get_Contents()
   at Eco.Gameplay.Utils.PickerTracker.get_Contents()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass11_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageMember(BSONObject bson, INetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.GetChanges(INetClient client)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__52_0()

--END DUMP--

**Comment by johnkslg** [comment]
Having a hard time tracking this down or reproducing it.  If you can figure out how the user triggered it that would be very helpful.

**Comment by johnkslg** [comment]
Depends on https://github.com/StrangeLoopGames/EcoIssues/issues/8542

**Comment by johnkslg** [comment]
Fixed in next hotfix
