### ISSUE TITLE
[7.6.0] Server dump: InvalidOperationException at .Linq.Enumerable.First() at ... StoreComponent.SendTradeNotifications

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8556]
--BEGIN DUMP--
Dump Time
07/16/2018 14:25:26

Exception
Exception: InvalidOperationException
Message:Die Sequenz enthÃ¤lt keine Elemente.
Source:System.Core

System.InvalidOperationException: Die Sequenz enthÃ¤lt keine Elemente.
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, String noneText)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, LocString noneText)
   at Eco.Gameplay.Items.EnumerableItemExtensions.DescribeNoNum(IEnumerable`1 stacks, Boolean plural)
   at Eco.Gameplay.Components.StoreComponent.SendTradeNotifications(PurchaseData data, Player purchaser)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)

--END DUMP--

**Comment by johnkslg** [comment]
Will be in next hotfix, thank you!
