### ISSUE TITLE
Server keeps crashing

### ISSUE THREAD

**Issue by Gjafar** [StrangeLoopGames/EcoIssues#8576]
Vanilla Server crashes always with same error:

--BEGIN DUMP--
Dump Time
07/17/2018 19:40:55

Exception
Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Gameplay

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at Eco.Gameplay.Property.PropertyManager.CreateAction(User user, Vector3i pos, IInteractable target)
   at Eco.Gameplay.Property.PropertyManager.IsAuthorizedOnObject(WorldObject worldObject, User user, String verb)
   at Eco.Gameplay.Components.LinkComponent.<>c__DisplayClass32_0.<GetAuthorizedLinkedObjects>b__0(LinkComponent linked)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Eco.Gameplay.Components.LinkComponent.GetLinkedComponents(User user)
   at Eco.Gameplay.Components.LinkComponent.GetSortedLinkedComponents(User user)
   at Eco.Gameplay.Components.StoreComponent.GetLinkedInventories(User user)
   at Eco.Gameplay.Components.StoreComponent.UpdateStock(Boolean initializing)
   at Eco.Gameplay.Components.StoreComponent.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by BlazeGuy2** [comment]
Are you running 7.6.0?

**Comment by Gjafar** [comment]
Yes, i'am running  Beta 7.6.0.

**Comment by BlazeGuy2** [comment]
We might have a fix for this coming out in 7.6.1 soon.  I'll let you know when it's live.

**Comment by Gjafar** [comment]
Last Log in Chat was,
" _Trades: ASGARD's SUPERMARKT - VERKAUF is now selling Geschmortes Fleisch (added by ThePocky)."
I think it isa issue with the store.

**Comment by BlazeGuy2** [comment]
Alright, 7.6.1 is live.  Try updating and let me know if the issue is still present.

**Comment by Gjafar** [comment]
Hi there,
another crash now

ClientReceiveException TargetInvocationException 07181221
`--BEGIN DUMP--
Dump Time
07/18/2018 03:12:21

Exception
Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Gameplay

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at Eco.Gameplay.Items.ItemStackExtensions.<>c.<Consolidate>b__0_0(ItemStack x)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   at System.Collections.Immutable.ImmutableList`1.CreateRange(IEnumerable`1 items)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Gameplay.Utils.ItemTracker.LockTracker(IEnumerable`1 stacks, User user, Vector3i pos, LocString prependText)
   at Eco.Gameplay.Components.ItemDistributionComponent.AddUser(User user)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Components.ItemDistributionComponent.Apply(Player player)

--END DUMP--`

and ServerCrash NullReferenceException 07181241:

`--BEGIN DUMP--
Dump Time
07/18/2018 03:12:41

Exception
Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Gameplay

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at Eco.Gameplay.Items.InventoryUtils.<>c.<Intersection>b__3_5(ItemStack x)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at Eco.Gameplay.Items.InventoryUtils.Intersection(IEnumerable`1 stacksToCull, IEnumerable`1 contents)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Items.EnumerableItemExtensions.DescribeTextOnly(IEnumerable`1 stacks, Int32 max)
   at Eco.Gameplay.Economy.EconomyTracker.UpdateDistributionStationText()
   at Eco.Gameplay.Economy.EconomyTracker.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
`

**Comment by johnkslg** [comment]
Fixed in next hotfix
