### ISSUE TITLE
[7.7.0] Exception thrown while messing with the elevator

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8609]
**Steps to Reproduce**
1. spawn with /testelevator
2. press the up and down buttons and pause buttons (go up and down in the elevator multiple times)

**Expected behavior:**
No exception

**Actual Behavior:**
![elevator_bug](https://user-images.githubusercontent.com/35509188/42909704-e82299fc-8a99-11e8-805e-51b03633ee21.PNG)

This 400,000ish line long exception report
[longtextfile.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2207468/longtextfile.zip)

**Comment by BlazeGuy2** [comment]
Repeated thousands of times: NullReferenceException: Object reference not set to an instance of an object.
  at UI.RecipeUI.UpdateQuantities () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

**Comment by BlazeGuy2** [comment]
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Original type is Vector3. Cannot convert from Vector3 to Int32
Source:Eco.Shared

System.Exception: Original type is Vector3. Cannot convert from Vector3 to Int32
   at Eco.Shared.Serialization.BSONValue.get_Int32Value()
   at Eco.Shared.Networking.NetObjectManager.UpdateObjects(BSONObject bsonRoot)
   at Eco.Plugins.Networking.Client.<.ctor>b__52_1()</size>

Log File:
Initialize engine version: 2018.2.0f2 (787658998520)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 3GB (ID=0x1c02)
    Vendor:   
    VRAM:     2988 MB
    Driver:   24.21.13.9811
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.354703 ms
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1775)

WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Top Stretch' - Pass 'DEFERRED' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Top Stretch' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Top Stretch' - Pass 'FORWARD_DELTA' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Top Stretch' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Top Stretch' - All passes removed
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar' - Pass 'DEFERRED' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar' - Pass 'FORWARD_DELTA' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar' - All passes removed
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Pollutable' - Pass 'DEFERRED' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Pollutable' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Pollutable' - Pass 'FORWARD_DELTA' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Pollutable' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Pollutable' - All passes removed
NotSupportedException: To marshal a managed method, please add an attribute named 'MonoPInvokeCallback' to the method definition.
  at Steamworks.NativeMethods.ISteamClient_SetWarningMessageHook (Steamworks.SteamAPIWarningMessageHook_t pFunction) [0x00000] in <00000000000000000000000000000000>:0 
  at SteamManager.OnEnable () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

Client version: 0.7.7.0 beta staging-9ff6e4e9
Monday, July 16, 2018 4:24 PM
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Settings:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following icons: CraneItem, RubberWheelItem, SmallWoodCartItem, SteelAxleItem, SteelGearItem, SteelPlateItem, SyntheticRubberItem
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<CreateMissingItems>c__Iterator3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>c__Iterator4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<BuildFromModKit>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>c__Iterator2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Caught exception on MinimapManager while in NetObject ReceiveUpdate.
Exception: An item with the same key has already been added. Key: (145, 595)
Callstack:   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.MinimapManager.UpdateProperty (Eco.Shared.Serialization.BSONArray propertiesBSON) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.MinimapManager.ParseUpdate (Eco.Shared.Serialization.BSONObject obj) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.MinimapManager.ReceiveUpdate (Eco.Shared.Serialization.BSONObject obj) [0x00000] in <00000000000000000000000000000000>:0 
  at NetObjComponent.Eco.Shared.Networking.INetObject.ReceiveUpdate (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObjectManager.UpdateObjects (Eco.Shared.Serialization.BSONObject bsonRoot) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObject.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
BSON: BSONValue (Object)
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogError(Object, Object)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveUpdate(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Closing tooltip
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
TooltipUI:DoCloseTooltip()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

NullReferenceException: Object reference not set to an instance of an object.
  at HasTooltip.get_HoverRect () [0x00000] in <00000000000000000000000000000000>:0 
  at TooltipUI+<VerifyAndFadeIn>c__Iterator0.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

NullReferenceException: Object reference not set to an instance of an object.
  at HasTooltip.get_HoverRect () [0x00000] in <00000000000000000000000000000000>:0 
  at TooltipUI+<VerifyAndFadeIn>c__Iterator0.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

Closing tooltip
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
TooltipUI:DoCloseTooltip()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Closing tooltip
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
TooltipUI:DoCloseTooltip()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Can not play a disabled audio source
System.Action`1:Invoke(T)
UnityEngine.Events.InvokableCall`1:Invoke(T1)
UnityEngine.Events.UnityEvent`1:Invoke(T0)
EscapeMenuUI:Start()

[ line 447] 
(Filename:  Line: 447)

Disconnected from server.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

NullReferenceException: Object reference not set to an instance of an object.
  at MinimapUIObjectManager.OnDestroy () [0x00000] in <00000000000000000000000000000000>:0 
  at MinimapUI.OnDestroy () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

Missing following icons: CraneItem, RubberWheelItem, SmallWoodCartItem, SteelAxleItem, SteelGearItem, SteelPlateItem, SyntheticRubberItem
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<CreateMissingItems>c__Iterator3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>c__Iterator4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<BuildFromModKit>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>c__Iterator2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Closing tooltip
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
TooltipUI:DoCloseTooltip()
TooltipUI:CloseAllTooltips()
<VerifyAndFadeIn>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Closing tooltip
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
TooltipUI:DoCloseTooltip()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Caught exception on MinimapManager while in NetObject ReceiveUpdate.
Exception: An item with the same key has already been added. Key: (345, 210)
Callstack:   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.MinimapManager.UpdateProperty (Eco.Shared.Serialization.BSONArray propertiesBSON) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.MinimapManager.ParseUpdate (Eco.Shared.Serialization.BSONObject obj) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.MinimapManager.ReceiveUpdate (Eco.Shared.Serialization.BSONObject obj) [0x00000] in <00000000000000000000000000000000>:0 
  at NetObjComponent.Eco.Shared.Networking.INetObject.ReceiveUpdate (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObjectManager.UpdateObjects (Eco.Shared.Serialization.BSONObject bsonRoot) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObject.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
BSON: BSONValue (Object)
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogError(Object, Object)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveUpdate(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

IndexOutOfRangeException: Index was outside the bounds of the array.
  at TMPro.TMP_Text.FillCharacterVertexBuffers (System.Int32 i, System.Int32 index_X4) [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.GenerateTextMesh () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.GenerateTextMesh () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.GenerateTextMesh () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.GenerateTextMesh () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.GenerateTextMesh () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.GenerateTextMesh () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.GenerateTextMesh () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.GenerateTextMesh () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.GenerateTextMesh () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.GenerateTextMesh () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.OnPreRenderCanvas () [0x00000] in <00000000000000000000000000000000>:0 
  at TMPro.TextMeshProUGUI.Rebuild (UnityEngine.UI.CanvasUpdate update) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at RootMotion.FinalIK.IKSolver+UpdateDelegate.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception, Object)
UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()
RootMotion.FinalIK.UpdateDelegate:Invoke()
 
(Filename: currently not available on il2cpp Line: -1)

Must call RecipeListUI.Init before use.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
UnityEngine.Object:Instantiate(Object, Transform, Boolean)
UnityEngine.Object:Instantiate(T, Transform, Boolean)
UI.WorldObjectUI:InitPanel(String)
UI.WorldObjectUI:OnToggleValueChanged(Toggle, Boolean)
System.Action`1:Invoke(T)
UnityEngine.Events.InvokableCall`1:Invoke(T1)
UnityEngine.Events.UnityEvent`1:Invoke(T0)
UnityEngine.UI.Toggle:Set(Boolean, Boolean)
UI.WorldObjectUI:SelectTab()
UI.WorldObjectUI:Init(BSONObject)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Toggle(String, BSONObject, UILayer)
GenericClient`1:ToggleUI(String, BSONObject)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
System.ResolveEventHandler:Invoke(Object, ResolveEventArgs)
Eco.Shared.Networking.RPCManager:TryInvoke(INetClient, Object, String, BSONObject, Object&)
Eco.Shared.Networking.RPCManager:InvokeOn(INetClient, BSONObject, Object, String)
Eco.Shared.Networking.RPCManager:HandleReceiveRPC(INetClient, BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

NullReferenceException: Object reference not set to an instance of an object.
  at GetWorldObjectUIScrollbar.TakeScrollbar () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Transform parent, System.Boolean instantiateInWorldSpace) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Transform parent, System.Boolean worldPositionStays) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.WorldObjectUI.InitPanel (System.String panelName) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.WorldObjectUI.OnToggleValueChanged (UnityEngine.UI.Toggle toggle, System.Boolean enabled) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.Toggle.Set (System.Boolean value, System.Boolean sendCallback) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.Toggle.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (UnityEngine.EventSystems.PointerInputModule+MouseButtonEventData data) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32 id) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.EventSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Object:Instantiate(Object, Transform, Boolean)
UnityEngine.Object:Instantiate(T, Transform, Boolean)
UI.WorldObjectUI:InitPanel(String)
UI.WorldObjectUI:OnToggleValueChanged(Toggle, Boolean)
System.Action`1:Invoke(T)
UnityEngine.Events.InvokableCall`1:Invoke(T1)
UnityEngine.Events.UnityEvent`1:Invoke(T0)
UnityEngine.UI.Toggle:Set(Boolean, Boolean)
UnityEngine.UI.Toggle:OnPointerClick(PointerEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: currently not available on il2cpp Line: -1)

NullReferenceException: Object reference not set to an instance of an object.
  at GetWorldObjectUIScrollbar.TakeScrollbar () [0x00000] in <00000000000000000000000000000000>:0 
  at UI.StorageUI.OnShow () [0x00000] in <00000000000000000000000000000000>:0 
  at UI.WorldObjectUI.OnToggleValueChanged (UnityEngine.UI.Toggle toggle, System.Boolean enabled) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.Toggle.Set (System.Boolean value, System.Boolean sendCallback) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.Toggle.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (UnityEngine.EventSystems.PointerInputModule+MouseButtonEventData data) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32 id) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.EventSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: currently not available on il2cpp Line: -1)

Closing tooltip
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
TooltipUI:DoCloseTooltip()
TooltipUI:CloseAllTooltips()
<VerifyAndFadeIn>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Closing tooltip
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
TooltipUI:DoCloseTooltip()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

NullReferenceException: Object reference not set to an instance of an object.
  at GetWorldObjectUIScrollbar.ReleaseScrollbar () [0x00000] in <00000000000000000000000000000000>:0 
  at UI.StorageUI.OnHide () [0x00000] in <00000000000000000000000000000000>:0 
  at UI.WorldObjectUI.OnHide () [0x00000] in <00000000000000000000000000000000>:0 
  at UI.UIManager.Hide (UnityEngine.GameObject gui) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.UIManager.Close (UnityEngine.GameObject existingGUI) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.UIManager.Close (System.String guiName, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.UIManager.CloseWindows () [0x00000] in <00000000000000000000000000000000>:0 
  at UI.UIManager.HideCursorAndCloseWindows () [0x00000] in <00000000000000000000000000000000>:0 
  at PlayerUIInputToggler.OnPointerDown (UnityEngine.EventSystems.PointerEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.ExecuteHierarchy[T] (UnityEngine.GameObject root, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] callbackFunction) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (UnityEngine.EventSystems.PointerInputModule+MouseButtonEventData data) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32 id) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.EventSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.ExecuteEvents:ExecuteHierarchy(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: currently not available on il2cpp Line: -1)

**Comment by BlazeGuy2** [comment]
Top 300 or so lines from the log^

**Comment by SeanAtr0n** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/3127
