### ISSUE TITLE
[7.7.0] can't use the spawnlasers command

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8611]
**Steps:**
type /spawnlasers

**Expected Behavior**
lasers spawn

**Result**

Server encountered an exception:

<size=60.00%>Exception: ArgumentException
Message:An element with the same key but a different value already exists. Key: LaserObject
Source:System.Collections.Immutable

System.ArgumentException: An element with the same key but a different value already exists. Key: LaserObject
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Gameplay.Objects.WorldObject.AddOccupancy(Type t, List`1 occupancyList)
   at LaserObject..cctor()</size>

Log File:
Initialize engine version: 2018.2.0f2 (787658998520)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 3GB (ID=0x1c02)
    Vendor:   
    VRAM:     2988 MB
    Driver:   24.21.13.9811
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.460452 ms
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1775)

WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Top Stretch' - Pass 'DEFERRED' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Top Stretch' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Top Stretch' - Pass 'FORWARD_DELTA' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Top Stretch' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Top Stretch' - All passes removed
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar' - Pass 'DEFERRED' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar' - Pass 'FORWARD_DELTA' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar' - All passes removed
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Pollutable' - Pass 'DEFERRED' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Pollutable' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Pollutable' - Pass 'FORWARD_DELTA' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Pollutable' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Triplanar/Masked Triplanar Pollutable' - All passes removed
NotSupportedException: To marshal a managed method, please add an attribute named 'MonoPInvokeCallback' to the method definition.
  at Steamworks.NativeMethods.ISteamClient_SetWarningMessageHook (Steamworks.SteamAPIWarningMessageHook_t pFunction) [0x00000] in <00000000000000000000000000000000>:0 
  at SteamManager.OnEnable () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

Client version: 0.7.7.0 beta staging-9ff6e4e9
Monday, July 16, 2018 4:24 PM
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Settings:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following icons: CraneItem, RubberWheelItem, SmallWoodCartItem, SteelAxleItem, SteelGearItem, SteelPlateItem, SyntheticRubberItem
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<CreateMissingItems>c__Iterator3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>c__Iterator4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<BuildFromModKit>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>c__Iterator2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Exception: Original type is String. Cannot convert from String to Int32
  at Eco.Shared.Serialization.BSONValue.get_Int32Value () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObjectManager.UpdateObjects (Eco.Shared.Serialization.BSONObject bsonRoot) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObject.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObjectManager.UpdateObjects (Eco.Shared.Serialization.BSONObject bsonRoot) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObject.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObjectManager.UpdateObjects (Eco.Shared.Serialization.BSONObject bsonRoot) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObject.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

Caught exception on Fir while in NetObject ReceiveInitialState.
Exception: An item with the same key has already been added. Key: 0
Callstack:   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <00000000000000000000000000000000>:0 
  at TreeNetComponent.SpawnBranch (Eco.Shared.Serialization.BSONObject branchBson) [0x00000] in <00000000000000000000000000000000>:0 
  at TreeNetComponent.CreateBranches (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at TreeNetComponent.ReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at NetObjComponent.OnReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at NetObjComponent.Eco.Shared.Networking.INetObject.ReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObjectManager.UpdateObjects (Eco.Shared.Serialization.BSONObject bsonRoot) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObject.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
BSON: BSONValue (Object)
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogError(Object, Object)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Caught exception on Fir while in NetObject ReceiveInitialState.
Exception: An item with the same key has already been added. Key: 0
Callstack:   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <00000000000000000000000000000000>:0 
  at TreeNetComponent.SpawnBranch (Eco.Shared.Serialization.BSONObject branchBson) [0x00000] in <00000000000000000000000000000000>:0 
  at TreeNetComponent.CreateBranches (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at TreeNetComponent.ReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at NetObjComponent.OnReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at NetObjComponent.Eco.Shared.Networking.INetObject.ReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObjectManager.UpdateObjects (Eco.Shared.Serialization.BSONObject bsonRoot) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetObject.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
BSON: BSONValue (Object)
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogError(Object, Object)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Exception when updating object RenderedChunkGrid: Object reference not set to an instance of an object.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Couldn't find mapping for object 'AtmosphereRegulatorObject'
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
ClientObjectMap:InstantiateFromType(String)
GenericClient`1:SpawnObject(Int32, BSONObject, String)
GenericClient`1:NewNetworkObject(Int32, BSONObject)
Assets.UI.Scripts.Utilities.CreateAtIndexFunc:Invoke(Int32, Transform)
Eco.Shared.Networking.NetObjectManager:GetObject(Int32, BSONObject, Boolean)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

The Text Container component is now Obsolete and can safely be removed from [Name].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
UnityEngine.Object:Instantiate(T)
AttachmentManager:SetupAttachments(WorldObject)
System.Xml.OnRemoveWriter:Invoke(XmlRawWriter)
NetObjComponent:OnReceiveInitialState(BSONObject)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

The Text Container component is now Obsolete and can safely be removed from [Name].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
UnityEngine.Object:Instantiate(T)
AttachmentManager:SetupAttachments(WorldObject)
System.Xml.OnRemoveWriter:Invoke(XmlRawWriter)
NetObjComponent:OnReceiveInitialState(BSONObject)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

The Text Container component is now Obsolete and can safely be removed from [Name].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
UnityEngine.Object:Instantiate(T)
AttachmentManager:SetupAttachments(WorldObject)
System.Xml.OnRemoveWriter:Invoke(XmlRawWriter)
NetObjComponent:OnReceiveInitialState(BSONObject)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Couldn't find mapping for object 'AtmosphereTesterObject'
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
ClientObjectMap:InstantiateFromType(String)
GenericClient`1:SpawnObject(Int32, BSONObject, String)
GenericClient`1:NewNetworkObject(Int32, BSONObject)
Assets.UI.Scripts.Utilities.CreateAtIndexFunc:Invoke(Int32, Transform)
Eco.Shared.Networking.NetObjectManager:GetObject(Int32, BSONObject, Boolean)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

The Text Container component is now Obsolete and can safely be removed from [Name].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
UnityEngine.Object:Instantiate(T)
AttachmentManager:SetupAttachments(WorldObject)
System.Xml.OnRemoveWriter:Invoke(XmlRawWriter)
NetObjComponent:OnReceiveInitialState(BSONObject)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Couldn't find mapping for object 'SwitchObject'
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
ClientObjectMap:InstantiateFromType(String)
GenericClient`1:SpawnObject(Int32, BSONObject, String)
GenericClient`1:NewNetworkObject(Int32, BSONObject)
Assets.UI.Scripts.Utilities.CreateAtIndexFunc:Invoke(Int32, Transform)
Eco.Shared.Networking.NetObjectManager:GetObject(Int32, BSONObject, Boolean)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

The Text Container component is now Obsolete and can safely be removed from [Name].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
UnityEngine.Object:Instantiate(T)
AttachmentManager:SetupAttachments(WorldObject)
System.Xml.OnRemoveWriter:Invoke(XmlRawWriter)
NetObjComponent:OnReceiveInitialState(BSONObject)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Couldn't find mapping for object 'ButtonObject'
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
ClientObjectMap:InstantiateFromType(String)
GenericClient`1:SpawnObject(Int32, BSONObject, String)
GenericClient`1:NewNetworkObject(Int32, BSONObject)
Assets.UI.Scripts.Utilities.CreateAtIndexFunc:Invoke(Int32, Transform)
Eco.Shared.Networking.NetObjectManager:GetObject(Int32, BSONObject, Boolean)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Couldn't find mapping for object 'APGenObject'
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
ClientObjectMap:InstantiateFromType(String)
GenericClient`1:SpawnObject(Int32, BSONObject, String)
GenericClient`1:NewNetworkObject(Int32, BSONObject)
Assets.UI.Scripts.Utilities.CreateAtIndexFunc:Invoke(Int32, Transform)
Eco.Shared.Networking.NetObjectManager:GetObject(Int32, BSONObject, Boolean)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

**Comment by craig-jong** [comment]
fixed in a PR
