### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8693]
**==Sent from Eco Crash Server==**
**Details:**
Message:Changes could not be applied, the requested operation would result in an invalid inventory state.
Source:Eco.Gameplay

**Stack:**
at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.AddItem(Item item, User user)
   at Eco.Mods.TechTreeCommands.&lt;&gt;c__DisplayClass6.<creative>b__0(SkillScroll x)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Mods.TechTreeCommands.Creative(User user)</creative>

27 occurrences.

**Comment by SlayksWood** [comment]
Seems fixed
