### ISSUE TITLE
USER ISSUE: Currency Exchange Bug

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8746]
**Version:** 0.7.7.0 beta staging-89185ed9

**Steps to Reproduce:**
1. Change currency from testalpha credit to walkaflakaflame credit at the currency exchange

**Expected behavior:**
Changed

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Original type is Object. Cannot convert from Object to Guid
Source:Eco.Shared

System.Exception: Original type is Object. Cannot convert from Object to Guid
   at Eco.Shared.Serialization.BSONValue.get_GuidValue()
   at Eco.Shared.Serialization.BsonManipulator.<>c.<.cctor>b__14_15(BSONValue value)
   at Eco.Shared.Serialization.BsonManipulator.FromBson(BSONValue value, Type type)
   at Eco.Shared.Networking.RPCManager.UnpackArgs(INetClient client, BSONObject bson, RPCMethod[] methods, Object target, RPCMethod& targetMethod)</size>
```

**Comment by johnkslg** [comment]
Fixed already in master
