### ISSUE TITLE
Distribution exception (master)

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#8749]
Trying to debug another issue using this save
Using this save https://www.dropbox.com/s/cmr1v6sfahgi70s/terryh_EcoGS_2018-07-23_15-43.zip?dl=0
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Eco.Gameplay
  StackTrace:
   at Eco.Gameplay.Items.ItemStackExtensions.<>c.<Consolidate>b__0_0(ItemStack x) in C:\slg\Eco\Server\Eco.Gameplay\Items\Inventory.cs:line 1743
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   at System.Collections.Immutable.ImmutableList`1.CreateRange(IEnumerable`1 items)
   at Eco.Core.Utils.ThreadSafeList`1.<>c__DisplayClass15_0.<AddRange>b__0(ImmutableList`1 x) in C:\slg\Eco\Server\Eco.Core\Utils\ThreadSafeList.cs:line 41
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply) in C:\slg\Eco\Server\Eco.Core\Utils\ImmutableHelper.cs:line 19
   at Eco.Core.Utils.ThreadSafeList`1.AddRange(IEnumerable`1 items) in C:\slg\Eco\Server\Eco.Core\Utils\ThreadSafeList.cs:line 41
   at Eco.Core.Utils.ThreadSafeList`1..ctor(IEnumerable`1 contents) in C:\slg\Eco\Server\Eco.Core\Utils\ThreadSafeList.cs:line 36
   at Eco.Gameplay.Utils.ItemTracker.LockTracker(IEnumerable`1 stacks, User user, Vector3i pos, LocString prependText) in C:\slg\Eco\Server\Eco.Gameplay\Utils\ItemTracker.cs:line 36
   at Eco.Gameplay.Utils.ItemTracker..ctor(IEnumerable`1 stacks, User user, Vector3i pos, LocString prependText) in C:\slg\Eco\Server\Eco.Gameplay\Utils\ItemTracker.cs:line 29
   at Eco.Gameplay.Components.ItemDistributionComponent.AddUser(User user) in C:\slg\Eco\Server\Eco.Gameplay\Components\ItemDistributionComponent.cs:line 57
   at Eco.Core.Utils.ThreadSafeAction`1.Invoke(T t) in C:\slg\Eco\Server\Eco.Core\Utils\ThreadSafeAction.cs:line 57
   at Eco.Gameplay.Players.UserManager.GetOrCreateUser(String steamId, String slgId, String username) in C:\slg\Eco\Server\Eco.Gameplay\Players\UserManager.cs:line 278
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language) in C:\slg\Eco\Server\Eco.Plugins\Networking\Client.cs:line 161

```

**Comment by GophTheGreat** [comment]
File deleted from dropbox, so I'm closing this.
