### ISSUE TITLE
Crash in room checker

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#875]
--BEGIN DUMP--
Dump Time
12/03/2016 21:20:45

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Objects.WorldObjectHandle..ctor(WorldObject obj)
   at Eco.Gameplay.Property.RoomChecker.<>c.<GetRoomStats>b__2_4(WorldObject x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Property.RoomChecker.GetRoomStats(List`1 placementPosList, Int32 allowedFenceHeight, WorldObject owner)
   at Eco.Gameplay.Property.RoomChecker.CheckRoom(RoomRequirements requirements, List`1 placementPosList, WorldObject owner)
   at Eco.Gameplay.Components.RoomRequirementsComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Eco.Simulation.ITickable.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/1608/server-crash
--BEGIN DUMP--
Dump Time
02/10/2017 07:55:47

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Objects.WorldObjectHandle..ctor(WorldObject obj)
   at Eco.Gameplay.Property.RoomChecker.<>c.<GetRoomStats>b__2_4(WorldObject x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Property.RoomChecker.GetRoomStats(List`1 placementPosList, Int32 allowedFenceHeight, WorldObject owner)
   at Eco.Gameplay.Property.RoomChecker.CheckRoom(RoomRequirements requirements, List`1 placementPosList, WorldObject owner)
   at Eco.Gameplay.Components.RoomRequirementsComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by MarjieAVolk** [comment]
From a user who saw this:
"Seems to be related to type of room it is placed in. Crash was happening when placing in a room made of wood and dirt, worked fine when placed in a room made of wood and mortared stone. Rooms were roughly same size."

**Comment by metachronism** [comment]
no longer relevant with 5.6 room detection changes
