### ISSUE TITLE
Store Exception error

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8756]
--BEGIN DUMP--
Dump Time
07/26/2018 00:38:34

Exception
Exception: InvalidOperationException
Message:Sequence contains no elements
Source:System.Core

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, String noneText)
   at Eco.Shared.Utils.StringExtensions.CommaList(IEnumerable`1 phrases, LocString noneText)
   at Eco.Gameplay.Items.EnumerableItemExtensions.DescribeNoNum(IEnumerable`1 stacks, Boolean plural)
   at Eco.Gameplay.Components.StoreComponent.SendTradeNotifications(PurchaseData data, Player purchaser)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)

--END DUMP--

**Comment by BlazeGuy2** [comment]
Is this on current release or bleeding_edge_staging?
