### ISSUE TITLE
Client Update Argument Null Exception

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8834]
--BEGIN DUMP--
Dump Time
07/31/2018 16:14:23

Exception
Exception: ArgumentNullException
Message:Value cannot be null.
Source:mscorlib

System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnterTimeout(Object obj, Int32 timeout, Boolean& lockTaken)
   at Eco.Shared.Utils.LockUtils.TryLock(Object lockObject, Action ifLockAcquired, Int32 millisecondsTimeout)
   at Eco.Simulation.Agents.AI.AITarget.UpdatePosition()
   at Eco.Simulation.Agents.AI.AITarget.get_Position()
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__52_0()

--END DUMP--

**Comment by SeanAtr0n** [comment]
fixed in 7.7
