### ISSUE TITLE
Distribution station exception

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#8888]
Try to setup a distribution station and click apply

System.Exception
  HResult=0x80131500
  Message=Could not finding matching RPC signature for method: Apply.
  Source=Eco.Shared
  StackTrace:
   at Eco.Shared.Networking.RPCManager.UnpackArgs(INetClient client, BSONObject bson, RPCMethod[] methods, Object target, RPCMethod& targetMethod) in C:\slg\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 426
   at Eco.Shared.Networking.RPCManager.TryInvoke(INetClient client, Object target, String methodname, BSONObject bsonArgs, Object& result) in C:\slg\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 302
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname) in C:\slg\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 271
   at Eco.Core.Controller.ControllerManager.HandleViewRPC(INetClient client, Int32 controllerID, String methodname, BSONObject bson) in C:\slg\Eco\Server\Eco.Core\Controller\ControllerManager.cs:line 503
   at Eco.Plugins.Networking.Client.ViewRPC(INetClient client, Int32 id, String methodname, BSONObject bson) in C:\slg\Eco\Server\Eco.Plugins\Networking\Client.cs:line 394

Inner Exception 1:
InvalidOperationException: Cannot convert value: BSONValue (int32 22319) to type: User

**Comment by mirasrael** [comment]
Working on this

**Comment by mirasrael** [comment]
Fix provided
