### ISSUE TITLE
USER ISSUE: [7.7.0] Test cranes placing stone from truck caused and exception

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8914]
**Version:** 0.7.7.0 beta staging-aaf5ba98

**Steps to Reproduce:**
1. Invoke /testcranes
2. Grab stone from the truck
3. Place the stones in a 5x2 stack

**Expected behavior:**
Stones are placed

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

Exception: InvalidOperationException
Message:Reentrancy check corruption
Source:Eco.Core

System.InvalidOperationException: Reentrancy check corruption
   at Eco.Core.Utils.ReentranceDetection`1.Test(TQuery t)
   at Eco.Gameplay.Auth.AuthManager.ReentranceCheck(User user)
   at Eco.Gameplay.Auth.AuthManager.IsAuthorized(Vector2i pos, User user, AccessType access, GameAction action)
   at Eco.Gameplay.Auth.AuthManager.IsAuthorizedOnLandRange(WorldRange range, User user, AccessType access)
   at Eco.Gameplay.Components.CraneToolComponent.Build(Player player, Vector3i min, Vector3i max)</size>
```

**Comment by BlazeGuy2** [comment]
Also occurs when trying to place Hewn Logs from stockpile

**Comment by johnkslg** [comment]
Fixed!
