### ISSUE TITLE
[7.7.0] Log ArgumentException

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8925]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2276041/output_log.txt)

```
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

LocalServer -  System.ArgumentException: An element with the same key but a different value already exists. Key: Eco.Gameplay.Wires.LogicGateObject
LocalServer -    at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
LocalServer -    at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
LocalServer -    at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
LocalServer - (T& original, Func`2 apply)
LocalServer -    at Eco.Gameplay.Objects.WorldObject.AddOccupancy(Type t, List`1 occupancyList)
LocalServer -    at Eco.Gameplay.Wires.LogicGateObject.OnCreate()
LocalServer -    at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, Vector3 position, Quaternion rotation)
LocalServer -    at Eco.Gameplay.Objects.WorldObjectManager.Add(WorldObject worldObject, User creator, Vector3 position, Quaternion rotation)
LocalServer -    at Eco.Gameplay.Objects.WorldObjectManager.TryToAdd(Type worldObjectType, User creator, Vector3 position, Quaternion rotation, Boolean validatePlacement, WorldObjectItem item)
LocalServer -    at Eco.Gameplay.Systems.Chat.AdminCommands.AllWorldObjects(User user)
Couldn't find mapping for object 'ButtonObject'
```

**Comment by metachronism** [comment]
wires related?

**Comment by mirasrael** [comment]
Wasn't able to reproduce in Unity. Can you provide more details about testing environment?
