### ISSUE TITLE
crash server 7.6.3 error message server

### ISSUE THREAD

**Issue by LaTrouTe** [StrangeLoopGames/EcoIssues#8934]
but also you can fix this by opening the Game.eco file with winrar/7zip and deleting the Layers directory then starting the server (make sure you close Game.eco before starting the server)

error and message server

Exception
Exception: IndexOutOfRangeException
Message:L'index se trouve en dehors des limites du tableau.
Source:Eco.Simulation

System.IndexOutOfRangeException: L'index se trouve en dehors des limites du tableau.
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.MakeDeltaBitmap(Int32 width, Int32 height, Byte[] history, Func`3 pixelFunc, Boolean firstFrame)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.SaveGIF(String name, Int32 width, Int32 height, Func`3 pixelFunc, Boolean animate, Boolean backup)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.SaveGIF(WorldLayer layer, Boolean backup)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.Update()
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by metachronism** [comment]
I believe sean fixed this already

**Comment by LaTrouTe** [comment]
deleting the Layers directory 


I deleted the directory but still can not start the server

**Comment by SeanAtr0n** [comment]
Please send us your Game.eco file

**Comment by LaTrouTe** [comment]
ok is file is not modified

http://www.mediafire.com/file/cz3z9m5ibu7zlp7/Game.rar

**Comment by SeanAtr0n** [comment]
Sorry, you can get past the issue by opening the Game.eco file and deleting the 'History' folder.

I'll keep this bug open as a reminder to eventually support resizing the gifs in response to world layer size changes. Looks like this save is really old and after it was started the voxels per entry for a bunch of layers was changed from 4 to 5

**Comment by LaTrouTe** [comment]
thank you very much the server is gone
