### ISSUE TITLE
/trashcity crashed

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9106]
![image](https://user-images.githubusercontent.com/3536496/44743201-b1e2ca00-aab6-11e8-9c75-1cfb234ac46c.png)

@BlazeGuy2 can you make sure this command is being used in the qa pass, is there a section on garbage testing?

**Comment by craig-jong** [comment]
That's the exact number of garbage blocks in the game plus the base class they all derive from.

Does your test place down all the blocks?

Should I be modifying Inventory Blocks to work when placed with no inventory? They're transient so they don't generally make their own inventories - that part is managed by something else.

**Comment by elfl0rd** [comment]
no more crashed at first call, but break if you try to call it secondary, after first.
```
System.ArgumentException
  HResult=0x80070057
  Сообщение = An element with the same key but a different value already exists. Key: (472, 66, 231)
  Источник = System.Collections.Immutable
  Трассировка стека:
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
   at Eco.Core.Utils.ThreadSafeDictionary`2.<>c__DisplayClass20_0.<Add>b__0(ImmutableDictionary`2 x) in D:\DevelopECO\Eco\Server\Eco.Core\Utils\ThreadSafeDictionary.cs:line 36
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply) in D:\DevelopECO\Eco\Server\Eco.Core\Utils\ImmutableHelper.cs:line 19
   at Eco.Core.Utils.ThreadSafeDictionary`2.Add(TKey key, TValue value) in D:\DevelopECO\Eco\Server\Eco.Core\Utils\ThreadSafeDictionary.cs:line 36
   at Eco.Gameplay.Garbage.GarbageManager.RegisterDecayingInventory(Vector3i pos, DecayingInventory inv) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Garbage\GarbageManager.cs:line 71
   at Eco.Mods.PollutionCommands.<>c__DisplayClass3.<TrashCity>b__1() in d:\DevelopECO\Eco\Server\Mods\Commands\PollutionCommands.cs:line 34
   at System.Threading.Tasks.Task.Execute()

```

**Comment by SlayksWood** [comment]
Seems fixed.
