### ISSUE TITLE
[SERVER] Crash when upgrading from 0.7.6.3 Beta to 0.7.7.0 Beta

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#9259]
Version: 0.7.7.0 server beta

Steps to Reproduce:
1. install a 0.7.6.3 server  get the server fully setup and generate a world and everything and
have a couple of players log in as well for good measure. 

2. Upgrade the server now from 0.7.6.3 Beta to 0.7.7.0 Beta

3. Try and start the 0.7.7.0 Server and watch for it to crash

Expected behavior:
Should smoothly upgrade from 0.7.6.3 Beta to 0.7.7.0 Beta 

Actual behavior:

Well when I upgraded from 0.7.7.0 from 0.7.6.3 Beta and I went to start the server
up like I normally would do now I am getting the following error showing and the server
crashes back to my desktop.

Server has 20 GB of memory and was running 0.7.6.3 with no problems what so
ever. 

This comes from my ServerCrash TargetInvocationException 09083921.ecodmp file
in the Eco Server\Dump directory. 

There are absolutely NO mods on this server it is a vanilla server. 

--BEGIN DUMP--
Dump Time
09/08/2018 00:39:21

Exception
Exception: Exception
Message:Error in WoodSignObject at 17: The name 'AuthModeType' does not exist in the current context (CS0103)

Source:Eco.ModKit

System.Exception: Error in WoodSignObject at 17: The name 'AuthModeType' does not exist in the current context (CS0103)

   at Eco.ModKit.RuntimeCompiler.HandleCompilerError(CompilerResults results)
   at Eco.ModKit.RuntimeCompiler.LoadOrCompileMods()
   at Eco.ModKit.ModKitPlugin..ctor(ManualResetEvent doneEvent)

--END DUMP--

now the server won't start I have tried a couple of times now already and the
server won't start.

**Comment by BlazeGuy2** [comment]
Exception occurs when server isn't updated cleanly (mods need a clean install, not a merge).  @thereporter42 can you try to do a fresh install whle preserving the Storage and Configs folders?

**Comment by thereporter42** [comment]
Well I got it going with a fresh install but I should have been able to update it from 
one version to the next without having to do a fresh install like that every time.
