### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#9313]
**==Sent from Eco Crash Server==**
**Details:**
Message: Method not found: 'Void Eco.Gameplay.Property.RequireRoomMaterialTierAttribute..ctor(Int32, Int32)'.
Source:mscorlib
**Stack:**
at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly&amp; lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType&amp; attributeType, IRuntimeMethodInfo&amp; ctor, Boolean&amp; ctorHasParameters, Boolean&amp; isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at Eco.Shared.Utils.ReflectionUtils.Attributes[T](MemberInfo member, Boolean inherit)
   at Eco.Gameplay.Property.RoomRequirements.CreateFor(Type worldObjectType)
   at Eco.Gameplay.Property.RoomRequirements.&lt;&gt;c.&lt;.cctor&gt;b__9_0(Type woType)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Eco.Gameplay.Property.RoomRequirements..cctor()

**Comment by BlazeGuy2** [comment]
new on 7.7.X, 31 occurrences.

**Comment by Spydarlee** [comment]
The RequireRoomMaterialTierAttribute has a constructor that accepts a single float argument, so someone trying to call with two integers would cause this. But all use cases I can find in the base game are auto-generated with correct parameters so I think this must be a mod problem?
