### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#9314]
**==Sent from Eco Crash Server==**
**Details:**
Message: The specified argument is outside the valid value range
Parameter name: index
Source:System.Collections.Immutable
**Stack:**
at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.get_Item(Int32 index)
   at GetPlayerCurrency_Patch1(Object name, String )
   at Eco.Gameplay.Components.CreditComponent.OnCreate()
   at Eco.Gameplay.Objects.WorldObject.AddComponent(Type componentType, Object[] args)
   at Eco.Gameplay.Objects.WorldObject.ValidateComponents()
   at Eco.Gameplay.Objects.WorldObject.BeginInitialize()
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.Add(WorldObject worldObject, User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.TryToAdd(Type worldObjectType, User creator, Vector3 position, Quaternion rotation, Boolean validatePlacement, WorldObjectItem item)
   at Eco.Gameplay.Objects.WorldObjectManager.TryPlaceWorldObject(Player player, WorldObjectItem item, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.&lt;&gt;c__DisplayClass14_0.<onactright>b__0(BSONObject response)
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.Client.&lt;.ctor&gt;b__53_1()</onactright>

**Comment by BlazeGuy2** [comment]
new to 7.7.X, 7 occurrences.

**Comment by Spydarlee** [comment]
Not sure where the method "GetPlayerCurrency_Patch1" is coming from. Is that a custom modification or automatically generated method or something? Can't find it on release or master.

The real method (without the "_Patch1" suffix) accesses the Currencies collection with FirstOrDefault which shouldn't be able to trigger this exception.

**Comment by johnkslg** [comment]
Must be a mod!
