### ISSUE TITLE
USER ISSUE: Exception: Exception

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#9472]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
https://youtu.be/XO6aLLXcZV4

**Expected behavior:**

**Actual behavior:**
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2407204/output_log.txt)
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters.
Source:Eco.Shared

System.Exception: Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters.
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname, Type& resultType)
   at Eco.Plugins.Networking.Client.ViewRPC(INetClient client, Int32 id, String methodname, BSONObject bson)</size>
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters.
Source:Eco.Shared

System.Exception: Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters.
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname, Type& resultType)
   at Eco.Plugins.Networking.Client.ViewRPC(INetClient client, Int32 id, String methodname, BSONObject bson)</size>
```

**Comment by johnkslg** [comment]
Fixed in latest
