### ISSUE TITLE
ServerCrash Issue with Tax

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#9485]
--BEGIN DUMP--
Dump Time
09/22/2018 16:21:03

Exception
Exception: Exception
Message:A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: You cannot afford to pay a tax of <b><link="Currency:cab1af47-c2a5-450f-8fa4-f32c6eedbeb6"><style="Currency">1 Eco Dollar</style></link></b>
Source:Eco.Core

System.Exception: A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: You cannot afford to pay a tax of <b><link="Currency:cab1af47-c2a5-450f-8fa4-f32c6eedbeb6"><style="Currency">1 Eco Dollar</style></link></b>
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.WorkOrder.UpdateCrafted()
   at Eco.Gameplay.Items.WorkOrder.set_Progress(Double value)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders(Single dtime)
   at Eco.Gameplay.Components.CraftingComponent.Tick()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by Sekor2600** [comment]
We have a Law where the Smith pays Tax for crafting Tailings

**Comment by SHviid** [comment]
We had this problem aswell. If a users currency balance is below what is being taxed, the server can go into a crash loop. We fixed it by making a law stating if currency balance >50 then prevent crafting tailings.

**Comment by johnkslg** [comment]
Adding saves from other bug:
All Crash reports up to now:
dumps.zip

Game save: https://drive.google.com/open?id=16oSQNLK_uVwHtgt-Patn5l7u10-hLlVB
(Already deleted the distributing law in hope it would fix the issue, but it doesn't.)

**Comment by Deantwo** [comment]
Just had this happen on the server I play on too.
Server owner said it was because of a tailings tax law identical to the one @Sekor2600 posted. He said it was because someone had a project trying to produce tailings, but the player had no money to cover the tax, and this crashed/ the server.

I'll attempt the mentioned workaround of adding a condition to the law.

**Comment by Deantwo** [comment]
The workaround in v7.7.2 of adding a condition to check for the currency seem to work fine.
