### ISSUE TITLE
Master: Chop down any tree - crash server

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9646]
**Version:** 0.7.8.0 beta master-1c78c1ee debug

```
System.Exception
  HResult=0x80131500
  Сообщение = Could not find matching method DestroyBranch on type Cedar taking 1 parameters.
  Источник = Eco.Shared

  Трассировка стека:
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname, Type& resultType) in D:\DevelopECO\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 271
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson) in D:\DevelopECO\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 465
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj) in D:\DevelopECO\Eco\Server\Eco.Plugins\Networking\NetworkServer.cs:line 146
   at Eco.Shared.Networking.NetObject.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj) in D:\DevelopECO\Eco\Server\Eco.Shared\Networking\NetObject.cs:line 70
   at Eco.Plugins.Networking.Client.<.ctor>b__54_2() in D:\DevelopECO\Eco\Server\Eco.Plugins\Networking\Client.cs:line 129
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

```
System.Exception
  HResult=0x80131500
  Сообщение = Could not find matching method DestroyLeaf on type Birch taking 2 parameters.
  Источник = Eco.Shared
  Трассировка стека:
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname, Type& resultType) in D:\DevelopECO\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 271
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson) in D:\DevelopECO\Eco\Server\Eco.Shared\Networking\RPCManager.cs:line 465
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj) in D:\DevelopECO\Eco\Server\Eco.Plugins\Networking\NetworkServer.cs:line 146
   at Eco.Shared.Networking.NetObject.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj) in D:\DevelopECO\Eco\Server\Eco.Shared\Networking\NetObject.cs:line 70
   at Eco.Plugins.Networking.Client.<.ctor>b__54_2() in D:\DevelopECO\Eco\Server\Eco.Plugins\Networking\Client.cs:line 129
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

throw new Exception($"Could not find matching method {methodname} on type {target.GetType().Name} taking {args.Count} parameters.");

**Comment by BlazeGuy2** [comment]
![treebug](https://user-images.githubusercontent.com/35509188/46638362-64c23100-cb15-11e8-9483-0397b1ce3613.PNG)
Confirmed that trees crash on Master.  Logged for 8.0 milestone.

**Comment by SeanAtr0n** [comment]
fixed in master
