### ISSUE TITLE
Master - remove all text throw exception.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9683]
Step 1
Add text, save

Step 2
Remove all text (you see "Enter text")
Hit save

now you get exception.

All vechicles text, all signs, etc.

```
throw new ArgumentNullException("Text is required");

System.ArgumentNullException
  HResult=0x80004003
  Сообщение = Значение не может быть неопределенным.
  Источник = Eco.Shared
  Трассировка стека:
   at Eco.Shared.Utils.ProfanityFilter.CleanTextProfanity(String text) in D:\DevelopECO\Eco\Server\Eco.Shared\Utils\ProfanityFilter.cs:line 76
   at Eco.Gameplay.Components.CustomTextComponent.SetText(Player player, String text) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Components\CustomTextComponent.cs:line 37

```

**Comment by BlazeGuy2** [comment]
Should be fixed in Craig's PR
