### ISSUE TITLE
Master: Cutting down birch tree branches causes an exception

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#9706]
This broke on master.

--BEGIN DUMP--
Dump Time
10/15/2018 16:10:51

Exception
Exception: Exception
Message:Could not find matching method DestroyBranch on type Birch taking 1 parameters.
Source:Eco.Shared

System.Exception: Could not find matching method DestroyBranch on type Birch taking 1 parameters.
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__54_2()

--END DUMP--

**Comment by BlazeGuy2** [comment]
As a side note, my CI system found it, so self high-five.

**Comment by elfl0rd** [comment]
Dupe - https://github.com/StrangeLoopGames/EcoIssues/issues/9646

**Comment by BlazeGuy2** [comment]
Dupe issue fixed a while ago.
