### ISSUE TITLE
Server Crash, again

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9822]
```
--BEGIN DUMP--
Dump Time
10/21/2018 20:31:19

Exception
Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Gameplay

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at Eco.Gameplay.Components.VehicleComponent.Tick()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

--END DUMP--
```

We had 30 players online, there is no way to know who did what at that moment.

**Comment by SeanAtr0n** [comment]
7.8
