### ISSUE TITLE
Laws don't migrate to 8.0

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#9844]
Generate a world in 7.8, switch to master and you get:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Eco.Gameplay
  StackTrace:
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.IsValidSelf() in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 116
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 77
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.<>c__DisplayClass31_0.<IsValidRecursive>b__0(LawLogicNode child) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValidRecursive(LawLogicEnvironment env) in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 82
   at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.IsValid() in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\LawLogicNode.cs:line 71
   at Eco.Gameplay.Items.Law.CheckValidity() in C:\slg\Eco\Server\Eco.Gameplay\Items\Law.cs:line 126
   at Eco.Gameplay.Legislation..ctor() in C:\slg\Eco\Server\Eco.Gameplay\LegislationSystem\Legislation.cs:line 107

```

**Comment by seccombew** [comment]
Reopen if issue persists in 8.1
