### ISSUE TITLE
Staging branch: can not make a new world from scratch

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9945]
Assets/Scripts/System/Settings.cs(189,29): error CS0117: TOD_Sky' does not contain a definition forAmbientDayOverride'
Assets/Scripts/System/Settings.cs(190,29): error CS0117: TOD_Sky' does not contain a definition forAmbientNightOverride'

**Comment by BlazeGuy2** [comment]
@elfl0rd Works just fine for me on a fresh pull.  Make sure that your SVN branch is on branches/staging.

**Comment by elfl0rd** [comment]
Ok, i try it.

**Comment by BlazeGuy2** [comment]
@elfl0rd Let me know if that works for ya.

**Comment by Quadbro** [comment]
@elfl0rd @BlazeGuy2  Yes, staging branch fixes that error

**Comment by elfl0rd** [comment]
Okay, that error fixed... But now, server cannot start legislation....

System.NullReferenceException
  HResult=0x80004003
  Сообщение = Ссылка на объект не указывает на экземпляр объекта.
  Источник = Eco.Gameplay
  Трассировка стека:
   at Eco.Gameplay.Property.PropertyManager.GetAllDeeds() in D:\DevelopECO\Eco\Server\Eco.Gameplay\Property\PropertyManager.cs:line 93
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.PropertyDropDown.get_UnsortedOptions() in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\PropertyDropDown.cs:line 17
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.HasValidOptions() in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 173
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init() in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 120
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1..ctor(LawLogicNode parent, Boolean sorted) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 67
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.PropertyDropDown..ctor(LawLogicNode parent) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\PropertyDropDown.cs:line 26
   at Eco.Gameplay.LegislationSystem.LawLogic.Conditions.PropertyCondition..ctor(LawLogicNode parent) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Conditions\PropertyCondition.cs:line 24
   at Eco.Gameplay.LegislationSystem.LawLogic.Conditions.LawConditionDropDown.<>c.<.cctor>b__8_0(LawLogicNode parent) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Conditions\LawConditionDropDown.cs:line 45
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.EnumToNodeDropDown`2.IdToSelectedData(String id) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 270
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.EnumToNodeDropDown`2.IsAvailableOption(DropDownOption option) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 283
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.EnumToNodeDropDown`2.IsValidOption(DropDownOption option) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 274
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.EnumToNodeDropDown`2.HasValidOptions() in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 266
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init() in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 120
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1..ctor(LawLogicNode parent, Boolean sorted) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 67
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseEnumDropDown`2..ctor(LawLogicNode parent) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 185
   at Eco.Gameplay.LegislationSystem.LawLogic.Fields.EnumToNodeDropDown`2..ctor(LawLogicNode parent) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Fields\DropDown.cs:line 264
   at Eco.Gameplay.LegislationSystem.LawLogic.Conditions.LawConditionDropDown..ctor(LawLogicNode parent) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\LawLogic\Conditions\LawConditionDropDown.cs:line 60
   at Eco.Gameplay.Legislation.CreateCitizenDemographic(LegislationData data) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\Legislation.cs:line 158
   at Eco.Gameplay.Legislation.InitDefaultLaws(LegislationData data) in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\Legislation.cs:line 120
   at Eco.Core.Plugins.StorageManager.CreateOrLoad[StorageType](String folder, Action`1 onCreate) in D:\DevelopECO\Eco\Server\Eco.Core\Plugins\StorageManager.cs:line 147
   at Eco.Gameplay.Legislation..ctor() in D:\DevelopECO\Eco\Server\Eco.Gameplay\LegislationSystem\Legislation.cs:line 60

![default](https://user-images.githubusercontent.com/4980243/48156905-61ba8c00-e2df-11e8-8965-9cb626d8d5c9.png)

**Comment by BlazeGuy2** [comment]
Pretty sure the fix for that was merged to the staging branch this morning.  Did you update from github?

**Comment by BlazeGuy2** [comment]
Problem there is a dual dependency between demographics and property manager.  I made a fix for it yesterday.

**Comment by BlazeGuy2** [comment]
Nope, it is a bug.  I was testing with a working save, didn't try genning from scratch.
